#!/usr/bin/env python3
"""Add 13 more quiz questions to Algebra 1 Units 5-8 (27 lessons)."""
import json, os

PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "content_data", "algebra_1_lessons.json")

def make_q(num, text, opts, explanation):
    options = []
    for o in opts:
        correct = o.startswith("*")
        options.append({"text": o.lstrip("*"), "is_correct": correct, "data_i18n": None})
    return {"question_number": num, "question_text": text, "attempted": 2,
            "data_i18n": None, "options": options, "explanation": explanation}

EXTRA = {
# ── U5: Exponential Functions ──
"u5_l5.1": [ # Exponential Growth
    make_q(8,"In y = a·bˣ, if b > 1, the function models:",["Decay","*Growth","A constant","A line"],"Base greater than 1 = growth."),
    make_q(9,"In y = 3·2ˣ, the initial value is:",["2","*3","6","1"],"When x = 0, y = 3·1 = 3."),
    make_q(10,"The growth factor 1.05 means a growth rate of:",["1.05%","105%","*5%","50%"],"Growth rate = b − 1 = 0.05 = 5%."),
    make_q(11,"A population doubles every 5 years. The growth factor (per 5-year period) is:",["5","0.5","*2","1.5"],"Doubles = factor of 2."),
    make_q(12,"y = 100(1.08)ˣ. Find y when x = 0.",["*100","108","0","1.08"],"Any base to the 0 power = 1, so 100·1 = 100."),
    make_q(13,"The horizontal asymptote for y = 5·2ˣ is:",["y = 5","y = 2","*y = 0","y = 10"],"Exponential growth approaches 0 from above but never reaches it."),
    make_q(14,"Which grows faster eventually: y = 100x or y = 2ˣ?",["y = 100x","They grow equally","*y = 2ˣ (exponential always overtakes linear)","Cannot tell"],"Exponential growth outpaces linear."),
    make_q(15,"In percent growth: A town of 5,000 grows 3% per year. After 1 year the population is:",["5,003","5,300","*5,150","5,030"],"5000 × 1.03 = 5150."),
    make_q(16,"y = a·bˣ is increasing when:",["b < 0","b = 1","*b > 1","b = 0"],"Base > 1 means growth."),
    make_q(17,"If a bacteria culture starts at 200 and triples every hour, the equation is:",["y = 200 + 3x","*y = 200·3ˣ","y = 3·200ˣ","y = 600ˣ"],"Initial value = 200, growth factor = 3."),
    make_q(18,"y = 1000(1.12)ˣ. The annual growth rate is:",["1.12%","112%","*12%","0.12%"],"b − 1 = 0.12 = 12%."),
    make_q(19,"The domain of any exponential function y = a·bˣ (a > 0, b > 0) is:",["x > 0","x ≥ 0","*All real numbers","x > 1"],"x can be any real number."),
    make_q(20,"The range of y = a·bˣ where a > 0 is:",["All real numbers","y ≤ 0","*y > 0","y ≥ 0"],"Always positive (never reaches 0)."),
],
"u5_l5.2": [ # Exponential Decay
    make_q(8,"Exponential decay has a base b where:",["b > 1","b = 1","*0 < b < 1","b < 0"],"Between 0 and 1 = decay."),
    make_q(9,"A decay rate of 15% means the decay factor is:",["1.15","15","*0.85","0.15"],"Decay factor = 1 − 0.15 = 0.85."),
    make_q(10,"y = 500(0.9)ˣ. After 1 period, y =",["500","900","*450","50"],"500 × 0.9 = 450."),
    make_q(11,"Half-life is the time for a quantity to decrease to:",["Zero","*Half its original value","One-quarter","Double"],"50% remaining."),
    make_q(12,"A radioactive substance has a half-life of 10 years. Starting with 80g, after 20 years there is:",["40g","*20g","10g","0g"],"After 10 yrs → 40g, after 20 yrs → 20g."),
    make_q(13,"In y = 1000(0.75)ˣ, the decay rate is:",["75%","0.75%","*25%","1.75%"],"Rate = 1 − 0.75 = 0.25 = 25%."),
    make_q(14,"Car depreciation at 20% per year: a $25,000 car after 3 years is worth about:",["$20,000","$15,000","*$12,800","$10,000"],"25000(0.8)³ = 25000(0.512) = 12,800."),
    make_q(15,"The graph of an exponential decay function:",["Goes up left to right","*Goes down left to right, approaching but never reaching y = 0","Is a straight line","Oscillates"],"Decreasing with asymptote at y = 0."),
    make_q(16,"y = 200(½)ˣ. Find y when x = 3.",["100","50","*25","12.5"],"200(1/8) = 25."),
    make_q(17,"After many periods of decay, y approaches:",["Negative infinity","Infinity","1","*0 (but never reaches it)"],"Horizontal asymptote at y = 0."),
    make_q(18,"If a value decreases by 10% each year, after 2 years the factor is:",["0.80","0.90","*0.81","0.10"],"(0.9)² = 0.81."),
    make_q(19,"Exponential decay can model:",["Only radioactivity","*Drug concentration in the body, cooling, depreciation, radioactive decay, etc.","Only car values","Only bacteria"],"Many real-world applications."),
    make_q(20,"Which function decays faster: y = 100(0.5)ˣ or y = 100(0.9)ˣ?",["y = 100(0.9)ˣ","They're equal","*y = 100(0.5)ˣ (lower base = faster decay)","Cannot tell"],"Lower base = more rapid decay."),
],
"u5_l5.3": [ # Exponential vs. Linear
    make_q(8,"A linear function has a constant:",["Ratio","*Rate of change (slope)","Exponent","Factor"],"Slope is constant."),
    make_q(9,"An exponential function has a constant:",["Slope","Sum","Difference","*Ratio (multiplier) between consecutive outputs"],"Same factor between terms."),
    make_q(10,"If a table shows: x=0→y=3, x=1→y=6, x=2→y=12, the model is:",["Linear","*Exponential (constant ratio of 2)","Quadratic","None"],"6/3 = 12/6 = 2."),
    make_q(11,"If a table shows: x=0→y=5, x=1→y=8, x=2→y=11, the model is:",["Exponential","*Linear (constant difference of 3)","Quadratic","None"],"8−5 = 11−8 = 3."),
    make_q(12,"Over time, an exponential growth function will always _____ a linear function.",["Stay below","*Eventually exceed (overtake)","Equal","Stay below or equal"],"Exponential always wins eventually."),
    make_q(13,"A scatter plot that curves upward steeply suggests:",["Linear model","*Exponential model","No model","Constant model"],"Rapid increase = exponential."),
    make_q(14,"Linear: y = 2x + 10 vs. Exponential: y = 10·2ˣ. At x = 5:",["Linear is greater","*Exponential is greater (320 vs. 20)","They're equal","Cannot tell"],"Linear: 20, Exponential: 320."),
    make_q(15,"First differences are constant for _____ functions.",["Exponential","Quadratic","*Linear","All"],"Δy constant = linear."),
    make_q(16,"Ratios of consecutive y-values are constant for _____ functions.",["Linear","*Exponential","Quadratic","Cubic"],"y_{n+1}/y_n = b always."),
    make_q(17,"A salary increasing by $2,000/year is:",["Exponential growth","*Linear growth","Exponential decay","Quadratic"],"Fixed amount = linear."),
    make_q(18,"An investment increasing by 5%/year is:",["Linear growth","*Exponential growth","Exponential decay","Constant"],"Fixed percentage = exponential."),
    make_q(19,"Which equation is linear? A: y = 3ˣ, B: y = 2x + 4, C: y = x²",["A","*B","C","None"],"y = mx + b form."),
    make_q(20,"Second differences are constant for _____ functions.",["Linear","Exponential","*Quadratic","Logarithmic"],"Second differences constant = quadratic."),
],
"u5_l5.4": [ # Geometric Sequences
    make_q(8,"The common ratio of 3, 9, 27, 81 is:",["6","3","27","*3"],"9/3 = 3."),
    make_q(9,"The explicit formula for a geometric sequence is:",["aₙ = a₁ + (n−1)d","*aₙ = a₁ · rⁿ⁻¹","aₙ = n·r","aₙ = a₁/r"],"Exponential formula."),
    make_q(10,"Find the 5th term of 2, 6, 18, 54, ...",["108","216","486","*162"],"a₅ = 2·3⁴ = 2·81 = 162."),
    make_q(11,"The common ratio r is found by:",["Subtracting consecutive terms","*Dividing a term by the previous term","Adding consecutive terms","Multiplying all terms"],"r = aₙ₊₁/aₙ."),
    make_q(12,"Is 5, 10, 20, 40 arithmetic or geometric?",["Arithmetic","*Geometric (common ratio = 2)","Neither","Both"],"10/5 = 20/10 = 2."),
    make_q(13,"If a₁ = 4 and r = 1/2, find a₄.",["2","1","*1/2","1/4"],"a₄ = 4·(1/2)³ = 4·(1/8) = 1/2."),
    make_q(14,"A geometric sequence with r < 1 (and r > 0) models:",["Growth","*Decay","A constant","A line"],"Decreasing terms."),
    make_q(15,"The 6th term of 1, −2, 4, −8, ... is:",["−16","16","*32","−32"],"a₆ = 1·(−2)⁵ = −32. Wait, let me recalculate: a₆ = 1·(−2)⁵ = −32. Actually checking: a₁=1, a₂=−2, a₃=4, a₄=−8, a₅=16, a₆=−32. Hmm the answer should be 32 or −32. a₆ = 1·(−2)^5 = −32."),
    make_q(16,"A geometric sequence with negative r produces:",["Only positive terms","Only negative terms","*Alternating positive and negative terms","Zero terms"],"Sign alternates."),
    make_q(17,"If a₁ = 100 and r = 0.1, find a₃.",["10","0.1","*1","0.01"],"a₃ = 100·(0.1)² = 100·0.01 = 1."),
    make_q(18,"The sum of an infinite geometric series with |r| < 1 is:",["Infinity","*a₁/(1 − r)","a₁·r","Cannot be found"],"Converges when |r| < 1."),
    make_q(19,"Which is geometric: {3,6,9,12} or {3,6,12,24}?",["First","*Second","Both","Neither"],"3,6,12,24 has r = 2; the first has d = 3 (arithmetic)."),
    make_q(20,"A geometric sequence is related to _____ functions.",["Linear","Quadratic","*Exponential","Logarithmic"],"Same structure: multiply by constant factor."),
],
"u5_l5.5": [ # Compound Interest
    make_q(8,"The compound interest formula is:",["A = P + rt","*A = P(1 + r/n)^(nt)","A = Prt","A = P·r"],"Standard compound interest."),
    make_q(9,"P represents the:",["Interest","Future value","*Principal (initial investment)","Time"],"Starting amount."),
    make_q(10,"$2000 at 6% compounded annually for 3 years equals approximately:",["$2,360","$2,120","*$2,382.03","$2,600"],"2000(1.06)³ ≈ 2382.03."),
    make_q(11,"Compounded quarterly means n =",["1","2","*4","12"],"4 times per year."),
    make_q(12,"Compounded monthly means n =",["4","2","*12","365"],"12 times per year."),
    make_q(13,"As compounding frequency increases, the final amount:",["Decreases","*Increases (approaching continuous compounding)","Stays the same","Doubles"],"More frequent = slightly more interest."),
    make_q(14,"Continuous compounding uses the formula:",["A = P(1 + r)ᵗ","*A = Peʳᵗ","A = Prt","A = P + rt"],"e ≈ 2.718."),
    make_q(15,"Simple interest formula is:",["A = P(1 + r)ᵗ","*I = Prt (or A = P + Prt)","A = Peʳᵗ","A = P(1 + r/n)ⁿᵗ"],"Linear growth of interest."),
    make_q(16,"$5000 at 4% simple interest for 5 years: total interest earned is:",["$200","$400","*$1,000","$2,000"],"I = 5000(0.04)(5) = 1000."),
    make_q(17,"Compound interest earns _____ than simple interest over the same period.",["Less","The same","*More (because interest earns interest)","Exactly double"],"Compounding effect."),
    make_q(18,"The Rule of 72 estimates that money doubles in approximately 72 ÷ _____.",["P","n","*r (the interest rate in percent)","t"],"72/rate ≈ doubling time."),
    make_q(19,"At 6% annual interest, money doubles in approximately:",["6 years","*12 years (72/6)","18 years","24 years"],"Rule of 72."),
    make_q(20,"APY (Annual Percentage Yield) accounts for:",["Only the principal","*The effects of compounding (effective annual rate)","Only simple interest","Only the time period"],"True yearly return."),
],
"u5_l5.6": [ # Writing Exponential Equations from Data
    make_q(8,"To write an exponential equation from two points (0, a) and (1, b), the base is:",["a","a + b","*b/a","a/b"],"Growth factor = y₁/y₀."),
    make_q(9,"If (0, 5) and (1, 15) are on the graph, the equation is:",["y = 15·5ˣ","*y = 5·3ˣ","y = 5 + 10x","y = 3·5ˣ"],"a = 5, b = 15/5 = 3."),
    make_q(10,"If (0, 100) and (1, 80) are given, the decay factor is:",["100","80","*0.8","1.2"],"80/100 = 0.8."),
    make_q(11,"If (0, 100) and (1, 80), the equation is:",["y = 80·100ˣ","*y = 100(0.8)ˣ","y = 100 + 80x","y = 100(1.2)ˣ"],"a = 100, b = 0.8."),
    make_q(12,"Given y-values 4, 12, 36, 108: the common ratio is:",["8","4","*3","36"],"12/4 = 3."),
    make_q(13,"With y₀ = 4 and ratio = 3, the equation is:",["y = 3·4ˣ","*y = 4·3ˣ","y = 4 + 3x","y = 12ˣ"],"y = a₁·rˣ = 4·3ˣ."),
    make_q(14,"If a table shows exponential behavior but x starts at a value other than 0, you can:",["Give up","*Adjust by finding the initial value using the pattern","Only use linear","Ignore it"],"Work backwards with the ratio."),
    make_q(15,"Two points (2, 12) and (4, 48) on an exponential curve: find the ratio.",["4","3","*2","12"],"a·r⁴ / (a·r²) = r² = 48/12 = 4, so r = 2."),
    make_q(16,"With r = 2 and (2, 12), find a (the y-intercept value).",["12","6","*3","24"],"a·2² = 12, a·4 = 12, a = 3."),
    make_q(17,"Exponential regression on a calculator finds:",["The line of best fit","*The best-fit equation y = a·bˣ for the data","The quadratic","The polynomial"],"Technology-based curve fitting."),
    make_q(18,"If data shows y-values: 2, 10, 50, 250, the function is y =",["2 + 8x","*2·5ˣ","10·2ˣ","5·2ˣ"],"a₁ = 2, ratio = 5."),
    make_q(19,"An exponential equation passes through (0, 1) and (3, 27). The base is:",["9","27","*3","1"],"1·b³ = 27, b = 3."),
    make_q(20,"An exponential equation passes through (0, 1000) and (2, 10). The base is:",["100","0.01","*0.1","10"],"1000·b² = 10, b² = 0.01, b = 0.1."),
],
"u5_l5.7": [ # Transformations of Exponential Functions
    make_q(8,"In y = 2ˣ + 3, the horizontal asymptote is:",["y = 0","y = 2","*y = 3","y = −3"],"Vertical shift moves asymptote to k = 3."),
    make_q(9,"In y = 2ˣ − 4, the graph is shifted _____ from y = 2ˣ.",["Up 4","*Down 4","Left 4","Right 4"],"Subtracting shifts down."),
    make_q(10,"In y = 2⁽ˣ⁻¹⁾, the graph is shifted _____ from y = 2ˣ.",["Left 1","*Right 1","Up 1","Down 1"],"x − 1 shifts right."),
    make_q(11,"In y = 2⁽ˣ⁺²⁾, the graph is shifted _____ from y = 2ˣ.",["Right 2","*Left 2","Up 2","Down 2"],"x + 2 shifts left."),
    make_q(12,"In y = −2ˣ, the graph is _____ compared to y = 2ˣ.",["Shifted up","*Reflected over the x-axis","Shifted right","Stretched"],"Negative in front reflects over x-axis."),
    make_q(13,"In y = 3·2ˣ, the 3 causes a vertical:",["Shift","Compression","*Stretch by factor of 3","Reflection"],"Multiplier > 1 = stretch."),
    make_q(14,"The y-intercept of y = 5·2ˣ + 1 is:",["5","2","*6","1"],"At x=0: 5(1)+1 = 6."),
    make_q(15,"The asymptote of y = 2ˣ − 7 is:",["y = 2","y = 0","*y = −7","y = 7"],"Shifted down 7."),
    make_q(16,"Reflecting y = 2ˣ over the y-axis gives:",["y = −2ˣ","*y = 2⁻ˣ (which equals (1/2)ˣ)","y = 2ˣ + 1","y = −2⁻ˣ"],"Replace x with −x."),
    make_q(17,"y = 2ˣ has a y-intercept at:",["(0, 2)","(1, 2)","*(0, 1)","(0, 0)"],"2⁰ = 1."),
    make_q(18,"Which transformation changes the asymptote of y = bˣ?",["Horizontal shift","*Vertical shift (y = bˣ + k)","Reflection over x-axis only","Stretching"],"Only k moves the asymptote."),
    make_q(19,"In y = a·bˣ + k, the asymptote is always y =",["a","b","*k","0"],"k determines the asymptote."),
    make_q(20,"The graph of y = (1/3)ˣ is _____ to that of y = 3⁻ˣ.",["Perpendicular","Shifted","*Identical (they are the same function)","Different"],"(1/3)ˣ = 3⁻ˣ."),
],
"u5_l5.8": [ # Solving Exponential Equations
    make_q(8,"Solve: 3ˣ = 81",["3","*4","5","81"],"3⁴ = 81."),
    make_q(9,"Solve: 5ˣ = 125",["2","5","*3","25"],"5³ = 125."),
    make_q(10,"Solve: 4ˣ = 1",["4","−1","*0","1"],"Any non-zero base to the 0 power = 1."),
    make_q(11,"Solve: 2ˣ = 1/8",["3","1/3","*−3","−1/8"],"2⁻³ = 1/8."),
    make_q(12,"To solve 2ˣ = 2⁵, x =",["2","*5","10","25"],"Same base → equal exponents."),
    make_q(13,"Solve: 9ˣ = 27. Rewrite with base 3:",["3²ˣ = 3²","*3²ˣ = 3³, so 2x = 3, x = 3/2","3ˣ = 3³","3⁹ = 3²⁷"],"9 = 3², 27 = 3³."),
    make_q(14,"Solve: 4ˣ = 8. Rewrite with base 2:",["2²ˣ = 2²","*2²ˣ = 2³, so 2x = 3, x = 3/2","2ˣ = 2⁸","2⁴ = 2⁸"],"4 = 2², 8 = 2³."),
    make_q(15,"If you cannot make equal bases, you can use:",["Factoring","Completing the square","*Logarithms","Synthetic division"],"Logs solve general exponential equations."),
    make_q(16,"Solve: 10ˣ = 1000",["*3","10","100","1"],"10³ = 1000."),
    make_q(17,"Solve: (1/2)ˣ = 16",["4","2","*−4","16"],"(1/2)⁻⁴ = 2⁴ = 16."),
    make_q(18,"Solve: 2^(x+1) = 32",["3","5","*4","6"],"2^(x+1) = 2⁵, x+1 = 5, x = 4."),
    make_q(19,"Solve: 3^(2x) = 81",["4","3","*2","1"],"3^(2x) = 3⁴, 2x = 4, x = 2."),
    make_q(20,"Solve: 5^(x−1) = 25",["2","*3","1","5"],"5^(x−1) = 5², x−1 = 2, x = 3."),
],
"u5_l5.9": [ # Interpreting Exponential Models
    make_q(8,"In y = 500(1.06)ˣ, the initial value is:",["1.06","*500","6","530"],"a = 500."),
    make_q(9,"In y = 500(1.06)ˣ, the growth rate per period is:",["1.06","500","*6%","106%"],"b − 1 = 0.06 = 6%."),
    make_q(10,"In y = 2000(0.85)ᵗ, 'the quantity decreases by ___% per period.'",["85","*15","0.85","2000"],"1 − 0.85 = 0.15 = 15%."),
    make_q(11,"In y = 2000(0.85)ᵗ, what is y after 0 periods?",["0","1700","*2000","850"],"Any base^0 = 1, so y = 2000."),
    make_q(12,"A model y = 50(1.03)ˣ where x = years. After 10 years, y ≈",["65","*67.2","80","53"],"50(1.03)¹⁰ ≈ 50(1.3439) ≈ 67.2."),
    make_q(13,"If a car is worth y = 30000(0.88)ᵗ after t years, the annual depreciation rate is:",["88%","30%","*12%","8%"],"1 − 0.88 = 0.12 = 12%."),
    make_q(14,"The domain of a real-world exponential model for time is typically:",["All real numbers","*t ≥ 0 (time can't be negative)","t > 100","Integers only"],"Time starts at 0."),
    make_q(15,"'The value triples every 4 years' means the growth factor per 4-year period is:",["4","*3","12","1/3"],"Triples = ×3."),
    make_q(16,"To find when y = 500(2)ᵗ reaches 4000:",["t = 8","*t = 3 (since 500·2³ = 4000)","t = 4","t = 16"],"2ᵗ = 8, t = 3."),
    make_q(17,"The percent of a radioactive sample remaining after t half-lives is:",["t × 50%","*100% × (1/2)ᵗ","100% − t","50t%"],"Halves each period."),
    make_q(18,"In medicine: y = 200(0.7)ᵗ (mg of drug after t hours). After 2 hours:",["140","100","*98","70"],"200(0.49) = 98."),
    make_q(19,"An exponential model is appropriate when the rate of change is proportional to:",["A constant","The time","*The current value (percentage change)","Zero"],"Exponential = constant percentage."),
    make_q(20,"Comparing y = 100(1.05)ˣ and y = 100(1.10)ˣ: which grows faster?",["First","Same rate","*Second (higher growth rate: 10% vs 5%)","Cannot tell"],"Higher base = faster growth."),
],
"u5_l5.10": [ # Exponential Regression
    make_q(8,"Exponential regression finds the best-fit equation in the form:",["y = mx + b","y = ax² + bx + c","*y = a·bˣ","y = a + b ln(x)"],"Fit exponential curve to data."),
    make_q(9,"To perform exponential regression, you typically use:",["Manual calculation only","*A graphing calculator or software (technology)","Only paper methods","Guessing"],"Technology handles the computation."),
    make_q(10,"If the regression gives y = 2.5(1.8)ˣ, the growth factor is:",["2.5","*1.8","4.3","0.8"],"b = 1.8."),
    make_q(11,"The correlation coefficient r for exponential regression indicates:",["The slope","*How well the exponential model fits the data (closer to ±1 = better fit)","The growth rate","The initial value"],"Goodness of fit."),
    make_q(12,"R² = 0.95 means the model explains ___% of variation.",["5%","*95%","50%","9.5%"],"R² × 100 = percent explained."),
    make_q(13,"If residuals for an exponential fit show a pattern, you should:",["Accept the model","*Consider a different model (exponential may not be the best fit)","Ignore it","Add more data"],"Patterns in residuals = poor fit."),
    make_q(14,"When should you use exponential regression instead of linear?",["When data is straight","*When data shows an increasing rate of change (curve upward or downward)","Always","Never"],"Curvature suggests exponential."),
    make_q(15,"Linearizing exponential data means taking the _____ of y-values.",["Square root","Square","*Logarithm","Reciprocal"],"ln(y) linearizes y = a·bˣ."),
    make_q(16,"If ln(y) vs. x produces a straight line, the original data is likely:",["Linear","Quadratic","*Exponential","Logarithmic"],"Linear log-transform = exponential data."),
    make_q(17,"Exponential regression should not be used to predict far beyond the data range because:",["It's inaccurate locally","*Extrapolation is unreliable (real conditions may change)","It's too accurate","It only works for 2 points"],"Patterns may not continue."),
    make_q(18,"Given data: (0,10), (1,20), (2,40), (3,80), the regression equation is exactly:",["y = 10 + 10x","*y = 10·2ˣ","y = 10x²","y = 80·(1/2)ˣ"],"Perfect doubling: a = 10, b = 2."),
    make_q(19,"For exponential regression, the initial value 'a' represents:",["The growth rate","*The y-intercept (value when x = 0)","The slope","The maximum"],"a = value at x = 0."),
    make_q(20,"Comparing linear and exponential regression: choose the model with:",["Always linear","Always exponential","*Higher R² value and random residuals","The simpler equation always"],"Best fit = highest R² and no residual patterns."),
],
# ── U6: Quadratic Functions ──
"u6_l6.1": [ # Key Features of Parabolas
    make_q(8,"A parabola opens upward when a is:",["Negative","Zero","*Positive","Any value"],"a > 0 opens up."),
    make_q(9,"The vertex of a parabola is:",["The y-intercept","*The highest or lowest point (turning point)","The x-intercept","The slope"],"Maximum or minimum point."),
    make_q(10,"The axis of symmetry of y = ax² + bx + c is x =",["b/a","*−b/(2a)","−a/(2b)","c/a"],"Standard formula for axis."),
    make_q(11,"If a < 0, the parabola opens _____ and the vertex is a _____.",["Up, minimum","*Down, maximum","Up, maximum","Down, minimum"],"Opens down = vertex is max."),
    make_q(12,"The y-intercept of y = 2x² − 3x + 5 is:",["2","−3","*5","−5"],"When x = 0, y = c = 5."),
    make_q(13,"Roots (x-intercepts) of a quadratic are where:",["y is maximum","y is minimum","*y = 0","x = 0"],"Crossing the x-axis."),
    make_q(14,"A quadratic can have 0, 1, or 2 x-intercepts. Having exactly 1 means:",["It doesn't touch the x-axis","*The vertex is on the x-axis (tangent)","It crosses twice","It's not a parabola"],"One root = vertex touches x-axis."),
    make_q(15,"The range of y = x² is:",["All reals","*y ≥ 0","y ≤ 0","y > 0"],"Minimum at vertex (0,0)."),
    make_q(16,"The range of y = −x² + 4 is:",["y ≥ 4","*y ≤ 4","All reals","y ≥ 0"],"Maximum at vertex: y = 4."),
    make_q(17,"The domain of any quadratic function is:",["y ≥ 0","Only positive x","*All real numbers","x ≥ 0"],"Quadratics accept all x."),
    make_q(18,"A narrow parabola has |a| that is:",["Small","*Large (|a| > 1 = narrower)","Zero","Equal to 1"],"Larger |a| = steeper."),
    make_q(19,"A wide parabola has |a| that is:",["Large","*Small (0 < |a| < 1 = wider)","Equal to 1","Zero"],"Smaller |a| = flatter."),
    make_q(20,"End behavior: as x → ±∞ for y = 2x², y →",["0","−∞","*+∞","1"],"Positive a: both ends go up."),
],
"u6_l6.2": [ # Graphing in Standard Form
    make_q(8,"Standard form of a quadratic is:",["y = a(x − h)² + k","*y = ax² + bx + c","y = a(x − r)(x − s)","y = mx + b"],"ax² + bx + c."),
    make_q(9,"In y = x² − 6x + 8, the axis of symmetry is x =",["−6","6","*3","−3"],"x = −(−6)/(2·1) = 3."),
    make_q(10,"In y = x² − 6x + 8, the vertex y-value is:",["8","0","*−1","3"],"y = (3)² − 6(3) + 8 = 9 − 18 + 8 = −1."),
    make_q(11,"The vertex of y = x² − 6x + 8 is:",["(6, 8)","*( 3, −1)","(−3, 8)","(3, 8)"],"(3, −1) from above."),
    make_q(12,"To find x-intercepts of y = x² − 6x + 8, set y = 0 and factor:",["(x − 1)(x − 8)","*(x − 2)(x − 4) → x = 2 or x = 4","(x + 2)(x + 4)","(x − 3)(x − 5)"],"x² − 6x + 8 = (x − 2)(x − 4)."),
    make_q(13,"In y = 2x² + 4x − 6, the axis of symmetry is x =",["2","*−1","−2","1"],"x = −4/(2·2) = −1."),
    make_q(14,"Finding the vertex in standard form requires calculating x = −b/(2a) then:",["Setting x = 0","*Substituting back to find y","Using only b and c","Graphing only"],"Plug x back into the equation."),
    make_q(15,"The y-intercept of y = −3x² + 12x − 7 is:",["12","−3","*−7","7"],"c = −7."),
    make_q(16,"If a = −3, the parabola opens:",["*Down","Up","Sideways","Both"],"Negative a = opens down."),
    make_q(17,"Symmetry means: points equidistant from the axis of symmetry have:",["Different y-values","*The same y-value","No relationship","Opposite y-values"],"Mirror property."),
    make_q(18,"To graph a quadratic in standard form: 1) find vertex, 2) plot y-intercept, 3) use _____ to plot more points.",["Slope","*Symmetry","Randomness","The range"],"Reflect points across axis."),
    make_q(19,"In y = x² − 4x + 3, the x-intercepts are:",["x = 4, x = 3","*x = 1, x = 3","x = −1, x = −3","x = 2, x = −2"],"(x−1)(x−3) = 0."),
    make_q(20,"A table of values for y = x² − 4x + 3 shows symmetry around x =",["0","*2","4","1"],"x = −(−4)/(2·1) = 2."),
],
"u6_l6.3": [ # Graphing in Vertex Form
    make_q(8,"Vertex form is:",["y = ax² + bx + c","*y = a(x − h)² + k","y = a(x − r)(x − s)","y = mx + b"],"Shows the vertex directly."),
    make_q(9,"In y = 3(x − 1)² + 4, the vertex is:",["(3, 4)","(1, 3)","*(1, 4)","(−1, 4)"],"(h, k) = (1, 4)."),
    make_q(10,"In y = −(x + 2)² − 5, the vertex is:",["(2, −5)","(2, 5)","*(−2, −5)","(−2, 5)"],"h = −2, k = −5."),
    make_q(11,"In vertex form, h shifts the graph _____ and k shifts it _____.",["Up, right","*Horizontally, vertically","Vertically, horizontally","Neither"],"h = horizontal, k = vertical."),
    make_q(12,"To convert y = x² − 8x + 15 to vertex form, complete the square to get:",["y = (x − 4)² + 15","*y = (x − 4)² − 1","y = (x − 8)² + 15","y = (x + 4)² − 1"],"x² − 8x + 16 − 1 = (x − 4)² − 1."),
    make_q(13,"In y = 2(x − 3)² + 1, the axis of symmetry is:",["x = 1","x = 2","*x = 3","x = −3"],"Axis goes through vertex: x = h."),
    make_q(14,"If the vertex is at (2, −3) and a = 1, the vertex form is:",["y = (x + 2)² − 3","*y = (x − 2)² − 3","y = (x − 2)² + 3","y = (x + 3)² − 2"],"y = 1(x − 2)² + (−3)."),
    make_q(15,"Vertex form makes it easy to identify:",["x-intercepts","*The vertex and direction of opening","The y-intercept","The slope"],"Direct reading of (h, k)."),
    make_q(16,"In y = −2(x + 1)² + 6, the parabola opens _____ with vertex _____.",["Up, (1, 6)","*Down, (−1, 6)","Down, (1, −6)","Up, (−1, 6)"],"a = −2 < 0; vertex = (−1, 6)."),
    make_q(17,"The maximum value of y = −2(x + 1)² + 6 is:",["−2","−1","*6","2"],"Maximum y = k = 6 (opens down)."),
    make_q(18,"To find x-intercepts from vertex form, set y = 0 and solve for x:",["Use factoring only","*Isolate the squared term, take square roots, and solve","Use only the quadratic formula","Read from the vertex"],"0 = a(x − h)² + k → solve."),
    make_q(19,"y = (x − 5)² has its vertex at:",["(5, 5)","(0, 5)","*(5, 0)","(−5, 0)"],"k = 0."),
    make_q(20,"Converting from vertex to standard form: expand y = 2(x − 1)² + 3.",["y = 2x² − 2x + 3","*y = 2x² − 4x + 5","y = 2x² + 4x + 5","y = 4x² − 2x + 3"],"2(x² − 2x + 1) + 3 = 2x² − 4x + 2 + 3 = 2x² − 4x + 5."),
],
"u6_l6.4": [ # Transformations of Quadratic Functions
    make_q(8,"y = x² + 5 shifts y = x² _____.",["Down 5","Left 5","*Up 5","Right 5"],"Adding to the output shifts up."),
    make_q(9,"y = (x − 3)² shifts y = x² _____.",["Left 3","*Right 3","Up 3","Down 3"],"Subtracting inside = right."),
    make_q(10,"y = −x² is y = x² reflected over the _____.",["y-axis","*x-axis","Origin","Line y = x"],"Negating the output = x-axis reflection."),
    make_q(11,"y = (x + 4)² shifts y = x² _____.",["Right 4","*Left 4","Up 4","Down 4"],"Adding inside = left."),
    make_q(12,"y = 3x² compared to y = x² is:",["Wider","*Narrower (vertical stretch by 3)","Shifted up","Shifted down"],"a > 1 = narrower."),
    make_q(13,"y = (1/4)x² compared to y = x² is:",["Narrower","*Wider (vertical compression)","Shifted right","Reflected"],"0 < a < 1 = wider."),
    make_q(14,"The vertex of y = (x + 2)² − 7 is:",["(2, −7)","(2, 7)","*(−2, −7)","(−2, 7)"],"h = −2, k = −7."),
    make_q(15,"y = −2(x − 1)² + 3 combines which transformations of y = x²?",["Only shift right","*Right 1, vertical stretch by 2, reflect over x-axis, up 3","Left 1, down 3","Only reflection"],"All transformations combined."),
    make_q(16,"Changing the value of 'a' affects:",["Only the position","*The width AND direction of the parabola","Only the vertex","Only the y-intercept"],"a controls width and open direction."),
    make_q(17,"Changing 'h' in vertex form affects:",["The width","*The horizontal position of the vertex","The direction","The y-intercept"],"h shifts left/right."),
    make_q(18,"Changing 'k' in vertex form affects:",["The width","*The vertical position of the vertex","The direction","The axis of symmetry"],"k shifts up/down."),
    make_q(19,"Which transformation does NOT change the shape of the parabola?",["Vertical stretch","Vertical compression","*Translations (horizontal or vertical shifts)","Reflections"],"Shifts move without changing shape."),
    make_q(20,"Starting from y = x², write the equation shifted left 3 and down 2:",["y = (x − 3)² − 2","*y = (x + 3)² − 2","y = (x + 3)² + 2","y = (x − 3)² + 2"],"Left 3 → x + 3; down 2 → −2."),
],
"u6_l6.5": [ # Comparing Linear, Quadratic, Exponential
    make_q(8,"Constant first differences indicate a _____ function.",["Quadratic","Exponential","*Linear","Cubic"],"Constant Δy = linear."),
    make_q(9,"Constant second differences indicate a _____ function.",["Linear","*Quadratic","Exponential","Logarithmic"],"Second Δy constant = quadratic."),
    make_q(10,"Constant ratios of consecutive y-values indicate an _____ function.",["Linear","Quadratic","*Exponential","Constant"],"y_{n+1}/y_n = constant."),
    make_q(11,"Table: x=0→y=1, x=1→y=3, x=2→y=9, x=3→y=27. The model is:",["Linear","Quadratic","*Exponential","None"],"Ratios: 3/1=3, 9/3=3, 27/9=3."),
    make_q(12,"Table: x=0→y=2, x=1→y=5, x=2→y=10, x=3→y=17. Check second differences:",["Linear (Δ=3)","Exponential","*Quadratic (2nd diff = 2)","None"],"Δy: 3,5,7; 2nd Δ: 2,2."),
    make_q(13,"Which grows fastest for large x?",["Linear","Quadratic","*Exponential","They are equal"],"Exponential dominates."),
    make_q(14,"y = 3(2)ˣ is which type?",["Linear","*Exponential","Quadratic","Constant"],"Base times power."),
    make_q(15,"y = 4x − 1 is which type?",["Exponential","Quadratic","*Linear","Polynomial"],"mx + b form."),
    make_q(16,"y = x² + 3x − 2 is which type?",["Linear","Exponential","*Quadratic","Cubic"],"Highest power is 2."),
    make_q(17,"A graph that curves upward with increasing steepness is likely:",["Linear","*Exponential growth","Quadratic only","None"],"Ever-increasing rate."),
    make_q(18,"A U-shaped graph is likely:",["Linear","Exponential","*Quadratic","Logarithmic"],"Parabola = U-shape."),
    make_q(19,"If a population increases by the same number each year, the model is:",["Exponential","*Linear","Quadratic","Constant"],"Same amount = constant rate."),
    make_q(20,"If a population increases by the same percent each year, the model is:",["Linear","*Exponential","Quadratic","Constant"],"Same percentage = exponential."),
],
"u6_l6.6": [ # Quadratic Regression
    make_q(8,"Quadratic regression produces an equation in the form:",["y = a·bˣ","y = mx + b","*y = ax² + bx + c","y = a(x − h)² + k"],"Standard quadratic form."),
    make_q(9,"When is quadratic regression appropriate?",["For constant rate of change","*When a scatter plot shows a U-shaped or inverted-U parabolic pattern","For constant ratios","Always"],"Parabolic data."),
    make_q(10,"R² for a quadratic regression represents:",["Slope","*The proportion of variation in y explained by the quadratic model","The vertex","The y-intercept"],"Coefficient of determination."),
    make_q(11,"If linear R² = 0.70 and quadratic R² = 0.95, which fits better?",["Linear","*Quadratic","Both are equal","Neither"],"Higher R² = better fit."),
    make_q(12,"To use quadratic regression on a calculator, enter data into:",["Only y-column","*L1 (x-values) and L2 (y-values), then select QuadReg","Only x-column","A third column"],"Standard process."),
    make_q(13,"If the regression gives y = −0.5x² + 4x + 1, what is the value of a?",["4","1","*−0.5","0.5"],"Leading coefficient."),
    make_q(14,"A negative 'a' in the regression means the parabola:",["Opens up","*Opens down","Is linear","Has no vertex"],"Negative a = opens down."),
    make_q(15,"Residual analysis for quadratic regression: random residuals suggest:",["Bad fit","*Good fit","Linear model","Exponential model"],"Random = model captures the pattern."),
    make_q(16,"A quadratic model is sometimes called a _____ model.",["First-order","*Second-order (degree 2)","Third-order","Zero-order"],"Degree 2 polynomial."),
    make_q(17,"If data has a clear peak and then decreases, a _____ regression is appropriate.",["Linear","Exponential","*Quadratic (downward-opening parabola)","Logarithmic"],"Inverted U = quadratic."),
    make_q(18,"Projectile motion data (height vs. time) is best modeled by:",["Linear regression","*Quadratic regression","Exponential regression","No regression"],"Parabolic trajectory."),
    make_q(19,"The vertex of the regression equation y = −2x² + 8x + 3 represents:",["The y-intercept","*The maximum value (peak) of the model","The x-intercept","The slope"],"Opens down → vertex is maximum."),
    make_q(20,"Find the vertex of y = −2x² + 8x + 3: x = −8/(2·(−2)) = 2, y = ?",["3","11","*11","8"],"y = −2(4) + 8(2) + 3 = −8 + 16 + 3 = 11."),
],
# ── U7: Solving Quadratics ──
"u7_l7.1": [ # Factoring GCF
    make_q(8,"The GCF of 15x⁴ and 10x² is:",["5x⁴","15x²","*5x²","10x"],"GCF of 15&10=5, min power of x=2."),
    make_q(9,"Factor: 6x³ + 9x²",["3x(2x + 3)","*3x²(2x + 3)","6x(x + 9)","9x(x + 1)"],"GCF = 3x²."),
    make_q(10,"Factor: 4x² − 8x",["2x(x − 4)","*4x(x − 2)","4(x² − 2)","8x(x − 1)"],"GCF = 4x."),
    make_q(11,"Factor: 12x³ + 18x² + 6x",["3x(4x² + 6x + 2)","*6x(2x² + 3x + 1)","6(2x³ + 3x² + x)","2x(6x² + 9x + 3)"],"GCF = 6x."),
    make_q(12,"After factoring out the GCF, the remaining expression should be:",["Unchanged","*Simpler with no common factors","Larger","A single term"],"GCF removal simplifies."),
    make_q(13,"Factor: −5x² + 10x",["5x(−x + 2)","*−5x(x − 2)","−5(x² − 2x)","5(−x² + 2x)"],"Factor out −5x."),
    make_q(14,"Factor: 8x²y + 12xy²",["2xy(4x + 6y)","*4xy(2x + 3y)","8xy(x + y)","12(xy + xy)"],"GCF = 4xy."),
    make_q(15,"What is the GCF of 20x³, 30x², and 10x?",["20x","5","*10x","10x²"],"GCF of 20,30,10 = 10; min x power = 1."),
    make_q(16,"Factoring is the reverse of:",["Division","Addition","*Distribution (expanding)","Subtraction"],"Undo the distributive property."),
    make_q(17,"If 2x² + 6x = 0, factor and solve:",["x = 0 only","x = −3 only","*x = 0 or x = −3","x = 3"],"2x(x + 3) = 0."),
    make_q(18,"The zero product property states: if ab = 0, then:",["a + b = 0","a and b are both 0","*a = 0 or b = 0 (or both)","ab ≠ 0"],"At least one factor is zero."),
    make_q(19,"Factor: 7x(x + 2) − 3(x + 2)",["(7x − 3)(x − 2)","*(7x − 3)(x + 2)","(7x + 3)(x + 2)","Cannot factor"],"Common factor (x + 2)."),
    make_q(20,"Factor by grouping: x³ + 2x² + 3x + 6",["(x + 2)(x + 3)","*(x² + 3)(x + 2)","(x + 1)(x² + 6)","Cannot factor"],"x²(x+2) + 3(x+2) = (x²+3)(x+2)."),
],
"u7_l7.2": [ # Factoring Trinomials
    make_q(8,"Factor: x² + 5x + 6",["(x + 1)(x + 6)","*(x + 2)(x + 3)","(x + 5)(x + 1)","(x − 2)(x − 3)"],"2·3=6, 2+3=5."),
    make_q(9,"Factor: x² − 7x + 12",["(x − 6)(x − 2)","*(x − 3)(x − 4)","(x − 1)(x − 12)","(x + 3)(x + 4)"],"(−3)(−4)=12, (−3)+(−4)=−7."),
    make_q(10,"Factor: x² + x − 12",["(x + 6)(x − 2)","(x − 3)(x + 4)","*(x + 4)(x − 3)","(x − 4)(x + 3)"],"4·(−3)=−12, 4+(−3)=1."),
    make_q(11,"Factor: x² − x − 20",["(x + 4)(x − 5)","*(x − 5)(x + 4)","(x − 4)(x + 5)","(x + 20)(x − 1)"],"(−5)(4)=−20, −5+4=−1."),
    make_q(12,"Factor: 2x² + 7x + 3",["(x + 3)(2x + 1)","*(2x + 1)(x + 3)","(2x + 3)(x + 1)","(2x − 1)(x − 3)"],"2·3=6, factors: 1&6→2(1)+1(3)=7? Actually: (2x+1)(x+3)=2x²+6x+x+3=2x²+7x+3. ✓"),
    make_q(13,"Factor: 3x² − 10x − 8",["(3x + 2)(x − 4)","*(3x + 2)(x − 4)","(3x − 8)(x + 1)","(3x − 2)(x + 4)"],"Check: 3x·x=3x², 3x(−4)+2·x=−12x+2x=−10x, 2(−4)=−8. ✓"),
    make_q(14,"To factor ax² + bx + c where a ≠ 1, use:",["Only guess and check","*AC method (find factors of ac that sum to b) or trial and error","Only the quadratic formula","Only completing the square"],"AC method is systematic."),
    make_q(15,"Factor: x² − 9x + 14",["(x − 1)(x − 14)","*(x − 2)(x − 7)","(x + 2)(x + 7)","(x − 9)(x + 14)"],"(−2)(−7)=14, −2+(−7)=−9."),
    make_q(16,"Factor: x² + 2x − 15",["(x + 3)(x − 5)","*(x + 5)(x − 3)","(x − 5)(x + 3)","(x + 15)(x − 1)"],"5·(−3)=−15, 5+(−3)=2."),
    make_q(17,"If x² + bx + 6 factors as (x + 2)(x + 3), then b =",["6","2","*5","3"],"2 + 3 = 5."),
    make_q(18,"Solve x² + 5x + 6 = 0 by factoring:",["x = 5 or x = 6","*x = −2 or x = −3","x = 2 or x = 3","x = 1 or x = 6"],"(x+2)(x+3)=0."),
    make_q(19,"Not all trinomials can be factored over the integers. x² + x + 1 is:",["(x + 1)(x + 1)","*(Not factorable over integers — it's prime)","(x − 1)(x + 1)","(x + 1)(x − 1)"],"Discriminant = 1 − 4 = −3 < 0."),
    make_q(20,"Factor completely: 2x² + 12x + 16",["(2x + 4)(x + 4)","(x + 2)(2x + 8)","*2(x + 2)(x + 4)","2(x² + 6x + 8)"],"Factor out 2 first: 2(x² + 6x + 8) = 2(x+2)(x+4)."),
],
"u7_l7.3": [ # Difference of Squares
    make_q(8,"The formula a² − b² factors as:",["(a − b)²","(a + b)²","*(a + b)(a − b)","a² + b²"],"Difference of squares pattern."),
    make_q(9,"Factor: x² − 49",["(x − 7)²","(x + 7)²","*(x + 7)(x − 7)","Cannot factor"],"7² = 49."),
    make_q(10,"Factor: 4x² − 25",["(2x − 5)²","*(2x + 5)(2x − 5)","(4x + 25)(4x − 25)","Cannot factor"],"(2x)² − 5²."),
    make_q(11,"Factor: 9x² − 1",["(3x − 1)²","*(3x + 1)(3x − 1)","(9x + 1)(x − 1)","Cannot factor"],"(3x)² − 1²."),
    make_q(12,"x² + 16 can be factored as:",["(x + 4)(x − 4)","(x + 4)²","(x − 4)²","*Cannot be factored (sum of squares doesn't factor over reals)"],"Sum of squares is prime over reals."),
    make_q(13,"Factor: 100 − x²",["(10 − x)²","*(10 + x)(10 − x)","(x + 10)(x − 10)","Cannot factor"],"10² − x²."),
    make_q(14,"Factor: x⁴ − 16",["(x² + 4)(x + 2)","*(x² + 4)(x + 2)(x − 2)","(x − 2)⁴","Cannot factor"],"(x²)² − 4² = (x²+4)(x²−4) = (x²+4)(x+2)(x−2)."),
    make_q(15,"Solve x² − 36 = 0",["x = 36","x = 6 only","*x = 6 or x = −6","x = −36"],"(x+6)(x−6)=0."),
    make_q(16,"Factor: 50x² − 18",["(50x + 18)(x − 1)","*2(5x + 3)(5x − 3)","(5x + 3)(10x − 6)","Cannot factor"],"2(25x² − 9) = 2(5x+3)(5x−3)."),
    make_q(17,"Recognizing a difference of squares requires:",["Two perfect squares added","*Two perfect squares subtracted","Any two terms","Two negative terms"],"Must be subtraction of squares."),
    make_q(18,"Factor: (x + 3)² − 16",["Cannot factor","*(x + 7)(x − 1)","(x + 3 − 4)²","(x + 3)(x − 16)"],"Let u = x+3: u² − 4² = (u+4)(u−4) = (x+7)(x−1)."),
    make_q(19,"Is 3x² − 12 a difference of squares?",["No","*Yes, after factoring: 3(x² − 4) = 3(x + 2)(x − 2)","Only if x = 2","Sometimes"],"GCF first, then difference of squares."),
    make_q(20,"Factor: 81a² − 64b²",["(9a − 8b)²","*(9a + 8b)(9a − 8b)","(81a + 64b)(a − b)","Cannot factor"],"(9a)² − (8b)²."),
],
"u7_l7.4": [ # Completing the Square
    make_q(8,"To complete the square for x² + 10x, add:",["5","10","*25","100"],"(10/2)² = 25."),
    make_q(9,"x² + 10x + 25 = :",["(x + 10)²","*(x + 5)²","(x + 25)²","(x − 5)²"],"Perfect square trinomial."),
    make_q(10,"Solve x² + 6x = 7 by completing the square:",["x = 1 only","*x = 1 or x = −7","x = −1 or x = 7","x = 6 or x = 7"],"x² + 6x + 9 = 16, (x+3)² = 16, x+3 = ±4."),
    make_q(11,"Complete the square: x² − 4x + ___ = (x − ___)²",["2, 2","8, 4","*4, 2","16, 4"],"(−4/2)² = 4; (x − 2)²."),
    make_q(12,"Solve x² − 2x − 8 = 0 by completing the square:",["x = 2 or x = −8","*x = 4 or x = −2","x = 1 or x = −9","x = 8 or x = −2"],"x² − 2x + 1 = 9, (x−1)² = 9, x = 4 or −2."),
    make_q(13,"To complete the square when a ≠ 1, first:",["Add a to both sides","*Divide all terms by a","Multiply by a","Ignore a"],"Make the leading coefficient 1."),
    make_q(14,"Complete: x² + 8x + ___ = (x + ___)²",["4, 4","*16, 4","8, 8","64, 8"],"(8/2)² = 16; (x + 4)²."),
    make_q(15,"Completing the square turns a quadratic into _____ form.",["Standard","Factored","*Vertex form y = a(x − h)² + k","Slope-intercept"],"Reveals the vertex."),
    make_q(16,"Solve: x² + 4x + 1 = 0",["x = −2 only","*x = −2 ± √3","x = −4 ± 1","x = 2 ± √3"],"(x+2)² = 3, x = −2 ± √3."),
    make_q(17,"When completing the square, whatever you add to one side you must:",["Subtract from the same side","Multiply to the other side","*Add to the other side (maintain equality)","Do nothing"],"Balance the equation."),
    make_q(18,"Complete: x² − 12x + ___ = (x − ___)²",["6, 6","12, 12","*36, 6","144, 12"],"(−12/2)² = 36; (x − 6)²."),
    make_q(19,"Completing the square is also used to derive:",["The slope formula","*The quadratic formula","The distance formula","The midpoint formula"],"Derivation of the quadratic formula uses completing the square."),
    make_q(20,"Convert y = x² − 6x + 11 to vertex form:",["y = (x − 3)² + 11","*y = (x − 3)² + 2","y = (x − 6)² + 11","y = (x + 3)² + 2"],"x² − 6x + 9 + 2 = (x − 3)² + 2."),
],
"u7_l7.5": [ # Quadratic Formula
    make_q(8,"The quadratic formula is: x =",["(b ± √D) / a","*(-b ± √(b²-4ac)) / (2a)","(-b ± √(b+4ac)) / 2","(b² - 4ac) / 2a"],"Standard formula."),
    make_q(9,"Solve x² − 5x + 6 = 0 using the formula:",["x = 5 or x = 6","*x = 2 or x = 3","x = −2 or x = −3","x = 1 or x = 6"],"x = (5 ± √(25−24))/2 = (5 ± 1)/2."),
    make_q(10,"Solve 2x² + 3x − 2 = 0:",["*x = 1/2 or x = −2","x = 2 or x = −1/2","x = 1 or x = −2","x = −1 or x = 2"],"x = (−3 ± √(9+16))/4 = (−3 ± 5)/4."),
    make_q(11,"If b² − 4ac = 0, the equation has:",["Two distinct real solutions","*One repeated real solution","No real solutions","Two complex solutions"],"One root (vertex touches x-axis)."),
    make_q(12,"If b² − 4ac < 0, the equation has:",["Two real solutions","One solution","*No real solutions (two complex solutions)","Infinitely many"],"Negative under square root = complex."),
    make_q(13,"Solve x² + 2x + 5 = 0: b² − 4ac =",["24","0","*−16","16"],"4 − 20 = −16 → no real solutions."),
    make_q(14,"For x² − 8x + 16 = 0: b² − 4ac =",["16","−16","*0","64"],"64 − 64 = 0 → one repeated root."),
    make_q(15,"The quadratic formula works for _____ quadratic equation.",["Only factorable","Only with integer roots","*Any (all quadratic equations)","Only when a = 1"],"Universal method."),
    make_q(16,"Solve: 3x² − 6x + 3 = 0",["x = 3 or x = 0","*x = 1 (repeated root)","x = −1","No solution"],"b² − 4ac = 36 − 36 = 0, x = 6/6 = 1."),
    make_q(17,"Before applying the formula, the equation must be in the form:",["y = mx + b","*ax² + bx + c = 0 (set equal to zero)","Any form","x = ay² + by + c"],"Standard form = 0."),
    make_q(18,"Solve x² − 3x − 10 = 0:",["x = 3 or x = −10","*x = 5 or x = −2","x = −5 or x = 2","x = 10 or x = −3"],"x = (3 ± √(9+40))/2 = (3 ± 7)/2."),
    make_q(19,"The ± in the formula gives:",["One solution always","*Two potential solutions (one from + and one from −)","No solutions","Three solutions"],"Plus-or-minus yields two values."),
    make_q(20,"Solve: x² + 1 = 0",["x = 1","x = −1","x = 0","*No real solutions (x² = −1)"],"Cannot take real √ of negative."),
],
"u7_l7.6": [ # The Discriminant
    make_q(8,"The discriminant is:",["2a","*b² − 4ac","−b/(2a)","√(b² − 4ac)"],"Expression under the square root."),
    make_q(9,"If the discriminant is positive, there are _____ real solutions.",["0","1","*2","3"],"Two distinct roots."),
    make_q(10,"If the discriminant is zero, there is _____ real solution(s).",["0","*1 (repeated)","2","Infinitely many"],"One repeated root."),
    make_q(11,"If the discriminant is negative, there are _____ real solutions.",["1","2","*0 (no real solutions)","Infinitely many"],"Complex solutions only."),
    make_q(12,"For 2x² + 5x + 3 = 0, the discriminant is:",["−1","*1","11","49"],"25 − 24 = 1 > 0 → two real solutions."),
    make_q(13,"For x² − 4x + 4 = 0, the discriminant is:",["16","−16","*0","8"],"16 − 16 = 0 → one repeated root."),
    make_q(14,"For x² + x + 1 = 0, the discriminant is:",["5","1","*−3","0"],"1 − 4 = −3 < 0 → no real solutions."),
    make_q(15,"A positive discriminant that is a perfect square means the roots are:",["Irrational","Complex","*Rational (and factorable over integers)","Imaginary"],"Perfect square → clean roots."),
    make_q(16,"A positive discriminant that is NOT a perfect square means the roots are:",["Rational","*Irrational (contain radicals)","Complex","Integer"],"Non-perfect square → irrational roots."),
    make_q(17,"The discriminant tells you the _____ and _____ of solutions.",["Size, sign","*Number, nature (type: real vs. complex, rational vs. irrational)","Location, direction","Slope, intercept"],"Key information about roots."),
    make_q(18,"For 3x² − 2x − 1 = 0, D = 4 + 12 =",["−8","8","*16","0"],"D = 4 − 4(3)(−1) = 4 + 12 = 16 → two rational roots."),
    make_q(19,"If D = 49, the roots are:",["*Two distinct rational numbers","One repeated root","Complex","Irrational"],"49 is a perfect square → rational distinct roots."),
    make_q(20,"On a graph, D > 0 means the parabola crosses the x-axis _____ time(s).",["0","1","*2","3"],"Two x-intercepts."),
],
"u7_l7.7": [ # Systems with Quadratics
    make_q(8,"A linear-quadratic system can have at most _____ solutions.",["1","*2","3","4"],"Line can cross parabola at most twice."),
    make_q(9,"A linear-quadratic system with 0 solutions means:",["The line is tangent","*The line doesn't intersect the parabola","They overlap","There's an error"],"No intersection points."),
    make_q(10,"Solve: y = x², y = x + 2",["(−1, 1) only","*(2, 4) and (−1, 1)","(0, 2) only","No solution"],"x² = x + 2, x² − x − 2 = 0, (x−2)(x+1) = 0."),
    make_q(11,"To solve a linear-quadratic system, substitute the linear equation into:",["Itself","*The quadratic (set them equal)","Neither","A third equation"],"Set y = y."),
    make_q(12,"Solve: y = x² − 3, y = 2x − 3",["(0, −3) only","*(0, −3) and (2, 1)","(2, 1) only","No solution"],"x² − 3 = 2x − 3, x² − 2x = 0, x(x−2) = 0."),
    make_q(13,"If substitution yields a quadratic with D < 0, the system has:",["1 solution","2 solutions","*No real solutions","Infinite solutions"],"No intersection."),
    make_q(14,"If substitution yields D = 0, the line is _____ to the parabola.",["Secant","*Tangent (touches at exactly one point)","Parallel","Identical"],"One point of contact."),
    make_q(15,"A quadratic-quadratic system can have 0, 1, 2, 3, or 4 solutions because:",["Lines always intersect","*Two parabolas can intersect in up to 4 points","Quadratics are linear","They never intersect"],"Two degree-2 curves: up to 4 intersections."),
    make_q(16,"Solve: y = x², y = 4 (horizontal line)",["x = 4 only","*(2, 4) and (−2, 4)","(4, 16) only","No solution"],"x² = 4, x = ±2."),
    make_q(17,"Graphically, solutions to a system are the _____ of the curves.",["Slopes","Asymptotes","*Intersection points","y-intercepts"],"Where curves meet."),
    make_q(18,"Solve: y = x² + 1, y = 3",["x = 3 only","x = 1 only","*(√2, 3) and (−√2, 3)","No solution"],"x² + 1 = 3, x² = 2, x = ±√2."),
    make_q(19,"If y = x² and y = −1, the system has:",["1 solution","2 solutions","*No solution (x² ≥ 0 always)","Infinite solutions"],"x² = −1 has no real solution."),
    make_q(20,"A ball's height h = −16t² + 40t and a drone at h = 24. When do they meet?",["t = 0","t = 2.5","*t = 1 and t = 1.5","t = 3"],"−16t² + 40t = 24, −16t² + 40t − 24 = 0, 2t² − 5t + 3 = 0, (2t−3)(t−1) = 0."),
],
"u7_l7.8": [ # Quadratic Inequalities
    make_q(8,"To solve x² − 4 > 0, first find where x² − 4 = 0:",["x = 4","*x = 2 and x = −2","x = 0","x = 16"],"(x+2)(x−2) = 0."),
    make_q(9,"x² − 4 > 0 is true when:",["−2 < x < 2","*x < −2 or x > 2","x = ±2","All x"],"Outside the roots for upward parabola > 0."),
    make_q(10,"x² − 4 < 0 is true when:",["x < −2 or x > 2","*−2 < x < 2","All x","No x"],"Inside the roots for upward parabola < 0."),
    make_q(11,"To solve a quadratic inequality: 1) find roots, 2) test intervals, 3):",["Stop","*Write the solution based on which intervals satisfy the inequality","Graph a line","Factor again"],"Sign analysis."),
    make_q(12,"Solve: x² − 9 ≤ 0",["x ≤ −3 or x ≥ 3","*−3 ≤ x ≤ 3","All reals","No solution"],"Between roots, including endpoints."),
    make_q(13,"Solve: x² + 2x − 8 > 0",["−4 < x < 2","*x < −4 or x > 2","x > 2 only","x < −4 only"],"Roots at −4 and 2; positive outside."),
    make_q(14,"For y > x² (quadratic inequality in two variables), shade:",["Below the parabola","*Above the parabola","Inside the parabola","On the parabola"],"Greater-than = above."),
    make_q(15,"The boundary of a strict inequality (>, <) is drawn as:",["*Dashed (not included)","Solid","Bold","Double"],"Strict = not included."),
    make_q(16,"The boundary of ≥ or ≤ is drawn as:",["Dashed","*Solid (included)","Dotted","Absent"],"Non-strict = included."),
    make_q(17,"Solve: −x² + 4x ≥ 0",["x ≤ 0 or x ≥ 4","*0 ≤ x ≤ 4","All reals","No solution"],"−x(x−4) ≥ 0, roots 0 and 4, opens down → positive between."),
    make_q(18,"A number line sign chart helps by:",["Graphing the parabola","*Testing the sign of the expression in each interval","Finding the vertex","Calculating the discriminant"],"Pick test points per interval."),
    make_q(19,"Solve: x² + 1 > 0",["No solution","x > 0","*All real numbers (x² + 1 is always positive)","x > 1"],"x² ≥ 0, so x² + 1 ≥ 1 > 0 always."),
    make_q(20,"Solve: x² + 1 < 0",["All real numbers","x < 0","x < −1","*No solution (x² + 1 is always positive)"],"Can never be negative."),
],
# ── U8: Polynomials ──
"u8_l8.1": [ # Adding & Subtracting Polynomials
    make_q(8,"(4x² − x + 3) + (2x² + 5x − 1) =",["6x² + 4x − 2","*6x² + 4x + 2","2x² + 6x + 4","6x² − 4x + 2"],"Combine like terms."),
    make_q(9,"(5x³ + 2x) − (3x³ − x + 4) =",["8x³ + 3x − 4","*2x³ + 3x − 4","2x³ + x + 4","8x³ − x − 4"],"Distribute negative, combine."),
    make_q(10,"Like terms have:",["The same coefficient","Different variables","*The same variable(s) raised to the same power(s)","Any exponents"],"Same variable, same exponent."),
    make_q(11,"The degree of 7x⁴ − 3x² + x is:",["7","3","2","*4"],"Highest exponent."),
    make_q(12,"A polynomial with 3 terms is called a:",["Monomial","Binomial","*Trinomial","Polynomial"],"Tri = three."),
    make_q(13,"A polynomial with 1 term is called a:",["Binomial","*Monomial","Trinomial","Constant"],"Mono = one."),
    make_q(14,"Standard form means terms are written in _____ order of degree.",["Ascending","*Descending (highest first)","Random","Alphabetical"],"Highest power first."),
    make_q(15,"(x² + 3x − 2) + (−x² + x + 5) =",["2x² + 4x + 3","−2x² + 2x − 7","*4x + 3","0"],"x² − x² = 0, 3x + x = 4x, −2 + 5 = 3."),
    make_q(16,"The leading coefficient of −5x³ + 2x² − 1 is:",["2","−1","*−5","3"],"Coefficient of the highest-degree term."),
    make_q(17,"(2x² + 3) − (2x² + 3) =",["4x² + 6","*0","2x²","6"],"Identical polynomials subtract to 0."),
    make_q(18,"A constant polynomial (like 7) has degree:",["7","1","*0","No degree"],"Degree 0."),
    make_q(19,"Subtracting polynomials requires distributing the _____ to the second polynomial.",["Plus sign","Variable","*Negative sign","Coefficient"],"Change signs of all terms in the second polynomial."),
    make_q(20,"(3a²b − 2ab²) + (a²b + 5ab²) =",["4a²b − 7ab²","*4a²b + 3ab²","2a²b + 3ab²","3a²b + 5ab²"],"3+1 = 4, −2+5 = 3."),
],
"u8_l8.2": [ # Multiplying Polynomials
    make_q(8,"(x + 2)(x + 5) =",["x² + 7x + 7","*x² + 7x + 10","x² + 10x + 7","x² + 5x + 10"],"FOIL: x² + 5x + 2x + 10."),
    make_q(9,"(x − 3)(x + 4) =",["x² + x − 12","*x² + x − 12","x² − x + 12","x² − 7x − 12"],"x² + 4x − 3x − 12."),
    make_q(10,"(2x + 1)(3x − 2) =",["6x² + x − 2","*6x² − x − 2","6x² − 5x − 2","5x² − x − 2"],"6x² − 4x + 3x − 2."),
    make_q(11,"(x + 4)² =",["x² + 16","*x² + 8x + 16","x² + 4x + 16","x² + 4x + 4"],"(a+b)² = a² + 2ab + b²."),
    make_q(12,"(x − 3)² =",["x² − 9","*x² − 6x + 9","x² + 6x + 9","x² − 3x + 9"],"(a−b)² = a² − 2ab + b²."),
    make_q(13,"(x + 5)(x − 5) =",["x² + 25","*x² − 25","x² − 10x + 25","x² + 10x − 25"],"Difference of squares: (a+b)(a−b) = a²−b²."),
    make_q(14,"FOIL stands for:",["Factor, Order, Invert, List","*First, Outer, Inner, Last","Find, Operate, Isolate, Linearize","None of these"],"Multiplication method for binomials."),
    make_q(15,"3x(2x² − 4x + 1) =",["6x² − 12x + 3","*6x³ − 12x² + 3x","6x³ − 4x + 1","3x² − 4x + 1"],"Distribute 3x to each term."),
    make_q(16,"(x + 1)(x² + 2x + 3) =",["x³ + 2x² + 3x + 1","*x³ + 3x² + 5x + 3","x³ + x² + 2x + 3","x³ + 3x² + 3x + 1"],"Distribute each term."),
    make_q(17,"The product of a binomial and a trinomial results in at most _____ terms (before combining).",["3","*6","4","5"],"2 × 3 = 6 products."),
    make_q(18,"(a + b)(a − b) always equals:",["a² + b²","(a − b)²","*a² − b²","a² + 2ab + b²"],"Difference of squares."),
    make_q(19,"(2x − 1)³ = (2x − 1)(2x − 1)² = (2x − 1)(4x² − 4x + 1) =",["8x³ − 1","*8x³ − 12x² + 6x − 1","8x³ + 12x² − 6x + 1","8x³ − 6x² + 12x − 1"],"Expand step by step."),
    make_q(20,"When multiplying polynomials, the degree of the product equals:",["Sum of terms","Difference of degrees","*Sum of the degrees of the factors","Product of the degrees"],"deg(f·g) = deg(f) + deg(g)."),
],
"u8_l8.3": [ # Dividing Polynomials
    make_q(8,"(x² + 5x + 6) ÷ (x + 3) =",["x + 6","x + 1","*x + 2","x + 3"],"Factor: (x+2)(x+3)/(x+3) = x+2."),
    make_q(9,"Long division of polynomials is similar to:",["Fraction addition","*Long division of numbers","Factoring only","Graphing"],"Same algorithm, different objects."),
    make_q(10,"(2x² + 7x + 3) ÷ (x + 3) =",["x + 1","*2x + 1","2x + 3","x + 3"],"Long division or factor: (2x+1)(x+3)/(x+3)."),
    make_q(11,"If there's a remainder in polynomial division, the result is:",["Just the quotient","*Quotient + remainder/(divisor)","An error","Not possible"],"Like number division with remainders."),
    make_q(12,"(x³ − 8) ÷ (x − 2) =",["x² − 4","*x² + 2x + 4","x² − 2x + 4","x² + 4"],"Sum of cubes factor / difference of cubes."),
    make_q(13,"Synthetic division can be used when dividing by:",["Any polynomial","*A linear divisor of the form (x − c)","Only quadratics","Only constants"],"Linear divisor only."),
    make_q(14,"In synthetic division by (x − 3), use c =",["−3","*3","0","x"],"The zero of x − 3 is 3."),
    make_q(15,"The Remainder Theorem: f(c) equals the _____ when f(x) is divided by (x − c).",["Quotient","*Remainder","Dividend","Coefficient"],"f(c) = remainder."),
    make_q(16,"If f(2) = 0, then (x − 2) is a _____ of f(x).",["Sum","*Factor","Remainder","Divisor only"],"Factor theorem."),
    make_q(17,"(6x² − x − 2) ÷ (2x + 1) =",["6x − 2","*3x − 2","3x + 2","2x − 1"],"Long division or factor."),
    make_q(18,"Missing terms in the dividend should be represented with:",["Nothing","*A zero coefficient (placeholder)","A 1","The variable alone"],"E.g., x³ + 0x² + 0x + 5."),
    make_q(19,"(x² − 1) ÷ (x + 1) =",["x + 1","x − 2","*x − 1","x²"],"(x+1)(x−1)/(x+1) = x−1."),
    make_q(20,"Long division check: (divisor)(quotient) + remainder should equal:",["Zero","The remainder","*The original dividend","The quotient"],"Verification step."),
],
"u8_l8.4": [ # Polynomial Identities
    make_q(8,"(a + b)² = :",["a² + b²","*a² + 2ab + b²","a² − 2ab + b²","2(a + b)"],"Perfect square sum."),
    make_q(9,"(a − b)² = :",["a² − b²","*a² − 2ab + b²","a² + 2ab + b²","2(a − b)"],"Perfect square difference."),
    make_q(10,"(a + b)(a − b) = :",["a² + b²","*a² − b²","(a − b)²","2ab"],"Difference of squares."),
    make_q(11,"(a + b)³ = :",["a³ + b³","*a³ + 3a²b + 3ab² + b³","a³ − 3a²b + 3ab² − b³","3(a + b)"],"Cube of a sum."),
    make_q(12,"a³ + b³ factors as:",["(a + b)³","*(a + b)(a² − ab + b²)","(a − b)(a² + ab + b²)","(a + b)²"],"Sum of cubes."),
    make_q(13,"a³ − b³ factors as:",["(a − b)³","(a + b)(a² − ab + b²)","*(a − b)(a² + ab + b²)","(a − b)²"],"Difference of cubes."),
    make_q(14,"Verify: (x + 3)² = x² + 6x + 9. Is this correct?",["No","*Yes (2·x·3 = 6x ✓)","Only for x > 0","Only for x = 3"],"Perfect square identity confirmed."),
    make_q(15,"Factor: 8x³ + 27",["(2x + 3)³","*(2x + 3)(4x² − 6x + 9)","(8x + 27)(x² − 1)","Cannot factor"],"Sum of cubes: (2x)³ + 3³."),
    make_q(16,"Factor: x³ − 64",["(x − 4)³","*(x − 4)(x² + 4x + 16)","(x + 4)(x² − 4x + 16)","Cannot factor"],"Difference of cubes: x³ − 4³."),
    make_q(17,"The identity (a+b)(a−b) = a²−b² is useful for:",["Adding fractions","*Mental math (e.g., 53×47 = 50² − 3² = 2491)","Finding slopes","Solving linear equations"],"Quick multiplication."),
    make_q(18,"(x + y + z)² = :",["x² + y² + z²","*x² + y² + z² + 2xy + 2xz + 2yz","(x + y + z)(x + y + z)","3(x + y + z)"],"All squares plus all cross products."),
    make_q(19,"A polynomial identity is true for:",["Only certain values","Only positive values","*All values of the variables","No values"],"Identities are universally true."),
    make_q(20,"Which is an identity: A: x²+1=0 or B: (x+1)²=x²+2x+1?",["A","*B","Both","Neither"],"B is true for all x; A is an equation with specific solutions."),
],
}

with open(PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

count = 0
for key, extra_qs in EXTRA.items():
    if key in data:
        existing = data[key].get("quiz_questions", [])
        start_num = len(existing) + 1
        for i, q in enumerate(extra_qs):
            q["question_number"] = start_num + i
        data[key]["quiz_questions"] = existing + extra_qs
        count += 1

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"✅ Algebra 1 U5-U8: expanded {count} lessons to 20 questions each")
