#!/usr/bin/env python3
"""Add 13 more quiz questions to Algebra 1 Units 1-4 (26 lessons)."""
import json, os

PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "content_data", "algebra_1_lessons.json")

def make_q(num, text, opts, explanation):
    options = []
    for o in opts:
        correct = o.startswith("*")
        options.append({"text": o.lstrip("*"), "is_correct": correct, "data_i18n": None})
    return {"question_number": num, "question_text": text, "attempted": 2,
            "data_i18n": None, "options": options, "explanation": explanation}

EXTRA = {
# ── U1: Data Analysis ──
"u1_l1.1": [ # Mean, Median, Mode
    make_q(8,"The median of {3, 7, 9, 12, 15} is:",["7","3","*9","12"],"Median is the middle value in an ordered set."),
    make_q(9,"Which measure of center is most affected by outliers?",["Median","Mode","*Mean","Range"],"The mean shifts toward extreme values."),
    make_q(10,"The mode of {2, 5, 5, 7, 8, 8, 8} is:",["5","2","7","*8"],"8 appears most often."),
    make_q(11,"Find the mean of {10, 20, 30, 40, 50}.",["*30","20","50","25"],"Sum = 150, divided by 5 = 30."),
    make_q(12,"A data set has mean 15 and five values. The total sum is:",["30","*75","15","60"],"Mean × n = 15 × 5 = 75."),
    make_q(13,"For the set {1, 1, 2, 3, 100}, which is more representative: mean or median?",["Mean","Neither","*Median","Mode"],"The outlier 100 inflates the mean; median (2) better represents the center."),
    make_q(14,"If every value in a data set is increased by 5, the mean:",["Stays the same","Doubles","*Increases by 5","Increases by 10"],"Adding a constant shifts the mean by the same amount."),
    make_q(15,"A bimodal data set has:",["No mode","One mode","*Two modes","Three modes"],"Bimodal = two values that appear most frequently."),
    make_q(16,"The mean of 6 numbers is 12. If a 7th number (26) is added, the new mean is:",["12","*14","15","13"],"Sum was 72, now 98/7 = 14."),
    make_q(17,"Which is NOT a measure of center?",["Mean","Median","Mode","*Range"],"Range measures spread, not center."),
    make_q(18,"The median of {4, 8, 12, 16} is:",["8","12","*10","16"],"Average of the two middle values: (8+12)/2 = 10."),
    make_q(19,"The weighted mean accounts for:",["Only the highest values","*Different importance (weights) of data values","Only the lowest values","All values equally"],"Weights assign different importance to values."),
    make_q(20,"If all values in a data set are identical, mean, median, and mode are:",["Different","*All equal","Undefined","Only mean is defined"],"All three equal that repeated value."),
],
"u1_l1.2": [ # Measures of Spread
    make_q(8,"The range of {3, 8, 15, 22, 30} is:",["22","*27","15","33"],"Range = max − min = 30 − 3 = 27."),
    make_q(9,"The interquartile range (IQR) measures the spread of:",["All data","Outliers","*The middle 50% of data (Q3 − Q1)","The top 25%"],"IQR = Q3 − Q1."),
    make_q(10,"Standard deviation measures:",["Center","*How far values typically are from the mean","Maximum value","Minimum value"],"Average distance from the mean."),
    make_q(11,"If every data value is multiplied by 2, the standard deviation:",["Stays the same","Is halved","*Doubles","Triples"],"Scaling data by k scales SD by |k|."),
    make_q(12,"For {10, 10, 10, 10}, the standard deviation is:",["10","5","*0","1"],"All values are the same, so no spread."),
    make_q(13,"A high standard deviation indicates data are:",["Clustered near the mean","All equal","*Widely spread from the mean","All positive"],"More spread = higher SD."),
    make_q(14,"Variance is:",["Range squared","*Standard deviation squared","Mean squared","IQR squared"],"Variance = SD²."),
    make_q(15,"Q1 is the median of the _____ half of ordered data.",["Upper","*Lower","Middle","Entire"],"Q1 = first quartile = median of lower half."),
    make_q(16,"Adding a constant to every data value changes the standard deviation by:",["The same constant","*Nothing (standard deviation doesn't change)","Twice the constant","Half the constant"],"Shifting doesn't change spread."),
    make_q(17,"Which data set has greater spread: A = {5,5,5,5} or B = {1,3,7,9}?",["A","Same","*B","Cannot tell"],"B has values farther from its mean."),
    make_q(18,"The five-number summary includes:",["Mean, mode, range, SD, IQR","*Min, Q1, median, Q3, max","Mean, SD, variance, range, mode","Only min and max"],"Five-number summary: Min, Q1, Med, Q3, Max."),
    make_q(19,"Mean absolute deviation (MAD) uses:",["Squared differences","*Absolute differences from the mean","Percentage differences","Logarithmic differences"],"MAD = average of |xᵢ − mean|."),
    make_q(20,"If the IQR is 10 and Q1 = 25, then Q3 is:",["15","10","*35","30"],"Q3 = Q1 + IQR = 25 + 10 = 35."),
],
"u1_l1.3": [ # Data Distributions
    make_q(8,"A symmetric distribution has:",["Only high values","*Roughly equal halves on either side of the center","A long tail on one side","No pattern"],"Mirror images around center."),
    make_q(9,"A right-skewed distribution has a tail extending to the:",["Left","Center","*Right (mean > median)","Both sides"],"The long tail is on the right."),
    make_q(10,"In a left-skewed distribution, the mean is typically:",["Greater than the median","Equal to the median","*Less than the median","Equal to the mode"],"Mean is pulled toward the left tail."),
    make_q(11,"A uniform distribution has:",["One peak","*All values appearing approximately equally often","Two peaks","No values"],"All bars roughly the same height."),
    make_q(12,"A bell-shaped distribution is also called:",["Skewed","Uniform","*Normal (Gaussian)","Bimodal"],"Bell curve = normal distribution."),
    make_q(13,"In a normal distribution, approximately ___% of data falls within 1 SD of the mean.",["50","95","99","*68"],"The 68-95-99.7 rule."),
    make_q(14,"Approximately ___% of data falls within 2 SDs of the mean in a normal distribution.",["68","*95","99.7","50"],"The 68-95-99.7 rule."),
    make_q(15,"A bimodal distribution has:",["Zero peaks","One peak","*Two peaks","Always symmetric shape"],"Two modes = two peaks."),
    make_q(16,"The shape of a distribution is best visualized with a:",["Scatter plot","Line graph","*Histogram or dot plot","Bar chart of categories"],"Histograms show frequency over intervals."),
    make_q(17,"If a distribution is symmetric, the mean and median are:",["Far apart","Mean > Median","*Approximately equal","Mean < Median"],"Symmetry keeps them at center."),
    make_q(18,"A distribution with a gap might indicate:",["Normal data","*Separate groups or an error in data collection","Perfect data","Uniform data"],"Gaps suggest distinct groups or issues."),
    make_q(19,"Which is most resistant to skew: mean or median?",["Mean","Both equally","*Median","Neither"],"Median isn't pulled by extreme values."),
    make_q(20,"The spread of a distribution is described by:",["Only the shape","Only the center","*Range, IQR, or standard deviation","Only the mode"],"Spread = how data varies."),
],
"u1_l1.4": [ # Describing Distributions
    make_q(8,"When describing a distribution, always mention:",["Only center","Only shape","*Shape, center, spread, and outliers","Only outliers"],"Full description uses S.O.C.S."),
    make_q(9,"SOCS stands for:",["Sum, Order, Count, Standard","*Shape, Outliers, Center, Spread","Skew, Origin, Cluster, Size","Standard, Outlier, Core, Sum"],"SOCS framework for describing distributions."),
    make_q(10,"Which word describes a symmetric, mound-shaped distribution?",["*Bell-shaped (normal)","Skewed right","Uniform","Bimodal"],"Bell curve shape."),
    make_q(11,"'The distribution is skewed right with a median of 45 and IQR of 12' addresses:",["Only shape","Only center","Only spread","*Shape, center, and spread"],"Shape (skewed right), center (median 45), spread (IQR 12)."),
    make_q(12,"For skewed data, the best measures of center and spread are:",["Mean and SD","Mean and range","*Median and IQR","Mode and range"],"Median and IQR resist outliers."),
    make_q(13,"For symmetric data, the best measures of center and spread are:",["Median and IQR","Mode and range","*Mean and standard deviation","Only the mode"],"Mean and SD work well with symmetric data."),
    make_q(14,"A cluster in a distribution is:",["A gap","An outlier","*A group of values close together","A missing value"],"Values bunched in one area."),
    make_q(15,"An outlier is typically defined as a value more than _____ × IQR from Q1 or Q3.",["1.0","*1.5","2.0","3.0"],"The 1.5 × IQR rule."),
    make_q(16,"If Q1 = 20, Q3 = 40, any value above _____ is an outlier.",["50","60","*70","80"],"Upper fence = Q3 + 1.5(IQR) = 40 + 1.5(20) = 70."),
    make_q(17,"Comparing two distributions, you should discuss:",["Only their shapes","*How their shapes, centers, and spreads compare (similarities and differences)","Only the means","Only the outliers"],"Compare using all aspects of the description."),
    make_q(18,"Which sentence best describes a distribution?",["It goes up","*'The distribution is approximately symmetric with a center around 50 and spread from 30 to 70.'","It has numbers","The data is normal"],"Uses shape, center, and spread with context."),
    make_q(19,"When distributions have different spreads, it means:",["They're identical","*The values in one are more variable (spread out) than the other","One has more data","One is symmetric"],"Spread indicates variability."),
    make_q(20,"Context matters in describing data because:",["Numbers are meaningless","*The same statistics can mean different things depending on what's being measured","Context is optional","Only teachers care"],"Units and meaning give statistics purpose."),
],
"u1_l1.5": [ # Box Plots
    make_q(8,"A box plot displays the:",["Mean and mode","*Five-number summary: min, Q1, median, Q3, max","Standard deviation","All individual data points"],"Five-number summary visualization."),
    make_q(9,"The 'box' in a box plot spans from:",["Min to max","Mean to mode","*Q1 to Q3 (the IQR)","Median to max"],"The box represents the middle 50%."),
    make_q(10,"The line inside the box represents the:",["Mean","Mode","*Median","Range"],"The center line is the median."),
    make_q(11,"Whiskers on a box plot extend to:",["The mean","*The minimum and maximum values (or to the fence for modified box plots)","Q1 and Q3","Only the right side"],"Whiskers show the range (excluding outliers in modified plots)."),
    make_q(12,"In a modified box plot, points beyond the whiskers represent:",["Normal values","*Potential outliers","Missing data","Errors"],"Individual points beyond 1.5 × IQR."),
    make_q(13,"If the median is closer to Q1 than Q3 in a box plot, the distribution is:",["Left-skewed","Symmetric","*Right-skewed","Bimodal"],"More data packed near the left, tail extends right."),
    make_q(14,"Two side-by-side box plots are useful for:",["Displaying raw data","*Comparing distributions between two groups","Showing correlation","Finding equations"],"Comparing center, spread, shape."),
    make_q(15,"The IQR in a box plot is the:",["Length of the whiskers","*Width of the box (Q3 − Q1)","Position of the median","Total range"],"Box width = IQR."),
    make_q(16,"A box plot with a very long right whisker suggests:",["Left skew","Symmetry","*Right skew (or a high outlier)","No spread"],"Long tail = skew in that direction."),
    make_q(17,"About what percent of data falls in the box?",["25%","75%","100%","*50%"],"Q1 to Q3 = middle 50%."),
    make_q(18,"A box plot does NOT show:",["The median","Quartiles","Range","*Individual data values (except outliers in modified plots)"],"Box plots summarize; they don't show every value."),
    make_q(19,"Which has a larger spread: a box with width 20 or width 5?",["Width 5","*Width 20","Same spread","Cannot determine"],"Larger IQR (box width) = larger spread."),
    make_q(20,"If the median in box plot A is higher than in box plot B, then:",["A has more data","B has more data","*A's center is higher","A has more spread"],"Higher median = higher center."),
],
"u1_l1.6": [ # Two-Way Tables
    make_q(8,"A two-way table displays data for:",["One variable","*Two categorical variables","Only numerical data","Three variables"],"Two categories organized in rows and columns."),
    make_q(9,"Marginal totals in a two-way table are found:",["In the center cells","*In the row and column totals (margins)","Only diagonally","Nowhere in the table"],"Margins = totals for each category."),
    make_q(10,"Joint frequency is the count in:",["A marginal row","A column total","*An individual cell where two categories intersect","The grand total"],"Where row and column meet."),
    make_q(11,"A survey shows: Cat owners who exercise = 30, Cat owners who don't = 20. The marginal total for cat owners is:",["30","20","*50","10"],"30 + 20 = 50."),
    make_q(12,"If a two-way table has 3 rows and 4 columns, there are _____ joint frequency cells.",["7","3","4","*12"],"3 × 4 = 12 inner cells."),
    make_q(13,"Two-way tables are used to look for _____ between categorical variables.",["*Associations (patterns)","Slopes","Functions","Exact causation"],"Patterns between categories."),
    make_q(14,"A conditional distribution shows percentages within:",["The grand total only","*A specific row or column (given one variable's category)","All cells","No specific category"],"Conditional = given one category."),
    make_q(15,"The grand total in a two-way table equals:",["The largest cell","The smallest cell","*The sum of all data values","The number of categories"],"All values summed."),
    make_q(16,"If 40 out of 100 students prefer math AND are female, the joint frequency is:",["100","*40","60","0.4"],"The actual count in that cell."),
    make_q(17,"To test for association, compare:",["Only the grand total","*Conditional distributions across categories (if they differ, there's association)","Only marginal totals","Individual values"],"If conditional distributions differ, variables may be associated."),
    make_q(18,"A two-way table cannot be used for:",["Finding joint frequencies","Finding marginal totals","*Determining a line of best fit","Finding conditional distributions"],"Lines of best fit are for quantitative bivariate data."),
    make_q(19,"If row conditional percentages are roughly the same across columns, the variables are:",["Strongly associated","*Not associated (independent)","Perfectly correlated","Causal"],"No difference in conditionals = no association."),
    make_q(20,"Segmented bar charts display two-way table data by:",["Individual data points","*Stacked bars showing proportions within each category","Only marginal totals","Only joint frequencies"],"Stacked bars visualize conditional distributions."),
],
"u1_l1.7": [ # Outliers
    make_q(8,"An outlier is a data value that:",["Is the most common","*Falls significantly outside the overall pattern","Is the median","Is always an error"],"Unusually far from other data."),
    make_q(9,"The IQR method identifies an outlier as any value below Q1 − _____ or above Q3 + _____.",["1.0 × IQR","2.0 × IQR","*1.5 × IQR","0.5 × IQR"],"1.5 × IQR rule."),
    make_q(10,"If Q1 = 10 and Q3 = 30, the lower fence for outliers is:",["0","5","*−20","10"],"Lower fence = Q1 − 1.5(IQR) = 10 − 1.5(20) = −20."),
    make_q(11,"Outliers affect the _____ more than the _____.",["Median, mean","Range, IQR","*Mean, median","Mode, range"],"Mean is pulled toward outliers."),
    make_q(12,"Should outliers always be removed?",["Yes","*No — investigate first (could be errors or legitimate extreme values)","Always if they're large","Only if negative"],"Outliers might carry meaningful information."),
    make_q(13,"An outlier caused by a data entry error should:",["Stay in the data","*Be corrected or removed","Increase the sample size","Be doubled"],"Errors should be fixed."),
    make_q(14,"Adding an outlier that is much higher than the other values will:",["Decrease the mean","*Increase the mean and possibly the range and SD","Decrease the range","Have no effect"],"Extreme high value pulls mean up, increases range/SD."),
    make_q(15,"The z-score method flags outliers when |z| >:",["1","*2 or 3 (depending on the threshold chosen)","0.5","10"],"Values more than 2-3 SDs from mean are potential outliers."),
    make_q(16,"Outliers are easier to see on a:",["Frequency table","*Box plot (shown as individual points beyond whiskers)","Pie chart","Bar chart"],"Modified box plots show outliers explicitly."),
    make_q(17,"A data set has Q1=20, Q3=40. Is the value 75 an outlier?",["*Yes (upper fence = 40 + 1.5(20) = 70, and 75 > 70)","No","Cannot tell","Only if the mean is high"],"75 exceeds the upper fence of 70."),
    make_q(18,"How do outliers affect the standard deviation?",["Decrease it","No effect","*Increase it (the distance from the mean is large)","Make it zero"],"Outliers increase the average distance from the mean."),
    make_q(19,"When reporting the center of data with outliers, prefer:",["Mean","*Median","Mode","Range"],"Median resists outlier influence."),
    make_q(20,"Multiple outliers in the same direction suggest:",["Random error","*Possible skewness in the data or a distinct subgroup","Perfect data","Symmetry"],"Consistent extreme values may indicate genuine skew."),
],
# ── U2: Equations and Inequalities ──
"u2_l2.1": [ # One-Step & Two-Step Equations
    make_q(8,"Solve: x − 9 = 4",["−5","5","*13","−13"],"x = 4 + 9 = 13."),
    make_q(9,"Solve: 3x = 21",["3","21","*7","9"],"x = 21/3 = 7."),
    make_q(10,"Solve: x/5 = 8",["5","8","*40","3"],"x = 8 × 5 = 40."),
    make_q(11,"Solve: 2x + 5 = 17",["5","7","*6","11"],"2x = 12, x = 6."),
    make_q(12,"Solve: x/3 − 4 = 2",["2","*18","6","12"],"x/3 = 6, x = 18."),
    make_q(13,"Solve: −4x = 20",["4","20","*−5","5"],"x = 20/(−4) = −5."),
    make_q(14,"What is the first step in solving 5x + 3 = 28?",["Divide by 5","Multiply by 3","*Subtract 3 from both sides","Add 5 to both sides"],"Undo addition first."),
    make_q(15,"Solve: 7 − x = 3",["7","3","*4","−4"],"−x = −4, x = 4."),
    make_q(16,"Solve: 0.5x = 10",["5","0.5","*20","10"],"x = 10/0.5 = 20."),
    make_q(17,"An equation has infinitely many solutions when:",["There are variables","*Both sides simplify to the same expression (identity)","It has no variables","The variable cancels to leave a false statement"],"E.g., 2x + 4 = 2(x + 2) is always true."),
    make_q(18,"An equation has no solution when:",["It has a variable","*Simplifying produces a false statement like 5 = 3","It has large numbers","It's too long"],"Contradiction means no solution."),
    make_q(19,"Solve: −x + 8 = 2",["−6","8","−10","*6"],"−x = −6, x = 6."),
    make_q(20,"The goal of solving an equation is to:",["Make it longer","*Isolate the variable on one side","Remove all numbers","Graph a line"],"Get variable alone."),
],
"u2_l2.2": [ # Multi-Step Equations
    make_q(8,"Solve: 3(x − 4) = 9",["3","4","*7","1"],"3x − 12 = 9, 3x = 21, x = 7."),
    make_q(9,"Solve: 4x + 2(x − 1) = 16",["4","2","*3","6"],"6x − 2 = 16, 6x = 18, x = 3."),
    make_q(10,"Solve: (2x + 6)/2 = 10",["6","10","*7","5"],"2x + 6 = 20, 2x = 14, x = 7."),
    make_q(11,"Solve: 5(x + 1) − 3 = 22",["5","3","*4","22"],"5x + 5 − 3 = 22, 5x = 20, x = 4."),
    make_q(12,"When solving multi-step equations, first:",["Divide by the coefficient","*Simplify each side (distribute and combine like terms)","Guess and check","Flip the equation"],"Simplify before isolating."),
    make_q(13,"Solve: 2(3x − 1) + 4 = 20",["4","2","*3","6"],"6x − 2 + 4 = 20, 6x + 2 = 20, 6x = 18, x = 3."),
    make_q(14,"Solve: 10 − 2(x + 3) = 0",["3","*2","0","4"],"10 − 2x − 6 = 0, 4 − 2x = 0, x = 2."),
    make_q(15,"Solve: x/4 + 3 = 6",["6","*12","3","4"],"x/4 = 3, x = 12."),
    make_q(16,"To clear fractions in an equation like x/3 + x/4 = 7, multiply everything by:",["3","4","*12 (the LCD)","7"],"LCD of 3 and 4 is 12."),
    make_q(17,"Solve: 0.2x + 1.4 = 3.0",["3","4","*8","16"],"0.2x = 1.6, x = 8."),
    make_q(18,"Combining like terms: 4x + 3 − 2x + 7 simplifies to:",["6x + 10","4x + 10","*2x + 10","2x − 4"],"4x − 2x = 2x, 3 + 7 = 10."),
    make_q(19,"Solve: −(x − 5) = 3",["−2","3","5","*2"],"−x + 5 = 3, −x = −2, x = 2."),
    make_q(20,"If an equation simplifies to 0 = 0, it has:",["No solution","One solution","*Infinitely many solutions","Exactly two solutions"],"An identity is always true."),
],
"u2_l2.3": [ # Variables on Both Sides
    make_q(8,"Solve: 5x + 2 = 3x + 10",["2","5","*4","10"],"2x = 8, x = 4."),
    make_q(9,"Solve: 7x − 3 = 4x + 9",["3","7","*4","−4"],"3x = 12, x = 4."),
    make_q(10,"Solve: 2(x + 1) = x + 5",["1","2","*3","5"],"2x + 2 = x + 5, x = 3."),
    make_q(11,"Solve: 6x − 4 = 2x + 12",["2","*4","6","8"],"4x = 16, x = 4."),
    make_q(12,"The first step when variables appear on both sides is to:",["Add the variables","*Move variable terms to one side (add/subtract)","Multiply by -1","Ignore one side"],"Combine variable terms."),
    make_q(13,"Solve: 3(x − 2) = 2(x + 1)",["2","−2","*8","6"],"3x − 6 = 2x + 2, x = 8."),
    make_q(14,"Solve: 4x + 3 = 4x + 7",["0","1","*No solution","Infinitely many"],"0 = 4 is false: no solution."),
    make_q(15,"Solve: 5(x − 1) = 5x − 5",["1","0","5","*Infinitely many solutions"],"5x − 5 = 5x − 5 is always true."),
    make_q(16,"Solve: 8 − x = 2x − 1",["1","*3","8","−1"],"9 = 3x, x = 3."),
    make_q(17,"Solve: −2x + 10 = x + 1",["10","1","*3","−3"],"9 = 3x, x = 3."),
    make_q(18,"Solve: 0.5x + 4 = 1.5x − 2",["2","*6","4","8"],"6 = x."),
    make_q(19,"When both sides simplify to the same expression, the equation is called:",["Conditional","Impossible","*An identity","A contradiction"],"True for all x values."),
    make_q(20,"Solve: x + 3 = −(2 − x)",["1","*No solution (3 = −2 is false)","5","0"],"x + 3 = −2 + x → 3 = −2, impossible."),
],
"u2_l2.4": [ # Literal Equations
    make_q(8,"Solve for h: A = bh",["h = Ab","h = b/A","*h = A/b","h = A + b"],"Divide both sides by b."),
    make_q(9,"Solve for t: d = rt",["t = dr","t = d + r","*t = d/r","t = r/d"],"Divide both sides by r."),
    make_q(10,"Solve for w: P = 2l + 2w",["w = P − l","w = P/2","*w = (P − 2l)/2","w = 2P − l"],"P − 2l = 2w, w = (P − 2l)/2."),
    make_q(11,"Solve for r: C = 2πr",["r = 2πC","r = C − 2π","*r = C/(2π)","r = 2C/π"],"Divide both sides by 2π."),
    make_q(12,"Solve for b: A = ½bh",["b = Ah/2","b = A/(2h)","b = 2Ah","*b = 2A/h"],"2A = bh, b = 2A/h."),
    make_q(13,"Solve for F: C = (5/9)(F − 32)",["F = 9C/5 + 32","F = C − 32","*F = (9C/5) + 32","F = 5C/9 + 32"],"9C/5 = F − 32, F = 9C/5 + 32."),
    make_q(14,"A literal equation has:",["No variables","Only numbers","*Two or more variables","Only one variable"],"Multiple variables like A = lw."),
    make_q(15,"Solve for x: ax + b = c",["x = c − b","x = (c + b)/a","*x = (c − b)/a","x = a(c − b)"],"ax = c − b, x = (c − b)/a."),
    make_q(16,"Solve for y: 3x + 2y = 12",["y = 12 − 3x","y = (12 + 3x)/2","*y = (12 − 3x)/2","y = 3x − 12"],"2y = 12 − 3x, y = (12 − 3x)/2."),
    make_q(17,"Solve for m: y = mx + b",["m = y − b + x","*m = (y − b)/x","m = y/x + b","m = x(y − b)"],"y − b = mx, m = (y − b)/x."),
    make_q(18,"The process for solving literal equations is the same as regular equations except:",["You use different operations","*You leave the answer in terms of other variables (not a number)","You can't use inverse operations","There's no solution"],"Same steps, but result has variables."),
    make_q(19,"Solve for a: v = u + at",["a = vt − u","a = v − u − t","*a = (v − u)/t","a = (v + u)/t"],"v − u = at, a = (v − u)/t."),
    make_q(20,"Solve for r: A = πr²",["r = A/π","r = √A","*r = √(A/π)","r = A²/π"],"r² = A/π, r = √(A/π)."),
],
"u2_l2.5": [ # One-Variable Inequalities
    make_q(8,"Solve: x − 5 > 3",["x > 3","x < 8","*x > 8","x > −2"],"x > 8."),
    make_q(9,"Solve: 2x ≤ 14",["x ≤ 14","x ≤ 2","*x ≤ 7","x ≥ 7"],"x ≤ 7."),
    make_q(10,"When multiplying or dividing an inequality by a negative number, you must:",["Do nothing special","Add to both sides","*Reverse (flip) the inequality sign","Remove the variable"],"Key rule for negative multiplication/division."),
    make_q(11,"Solve: −3x > 12",["x > 12","x > −4","*x < −4","x < 4"],"Divide by −3 and flip: x < −4."),
    make_q(12,"Solve: 4x + 1 ≥ 13",["x ≥ 13","x ≥ 4","*x ≥ 3","x ≤ 3"],"4x ≥ 12, x ≥ 3."),
    make_q(13,"On a number line, x > 5 is shown with:",["A closed circle at 5","*An open circle at 5 with shading to the right","Shading to the left","A closed circle and left shading"],"Open circle = not included; > means right."),
    make_q(14,"On a number line, x ≤ 3 is shown with:",["Open circle, shade right","*Closed circle at 3, shade left","Open circle, shade left","Closed circle, shade right"],"Closed = included; ≤ means left."),
    make_q(15,"Solve: 5 − x < 2",["x < 3","x < −3","*x > 3","x > −3"],"−x < −3, x > 3 (flip sign)."),
    make_q(16,"Solve: x/2 + 3 ≥ 7",["x ≥ 7","x ≥ 2","*x ≥ 8","x ≤ 8"],"x/2 ≥ 4, x ≥ 8."),
    make_q(17,"Which value is in the solution set of x > −2?",["−3","−2","*0","None of these"],"0 > −2 is true."),
    make_q(18,"Solve: 3(x − 2) ≤ 9",["x ≤ 9","x ≤ 3","*x ≤ 5","x ≥ 5"],"3x − 6 ≤ 9, 3x ≤ 15, x ≤ 5."),
    make_q(19,"An inequality with no solution means:",["x = 0","*No value of x makes the statement true (e.g., x > x + 1)","All values work","Only negative values"],"Contradiction in inequality."),
    make_q(20,"Solve: −2(x + 1) > 6",["x > −4","x > 4","*x < −4","x < 4"],"−2x − 2 > 6, −2x > 8, x < −4."),
],
"u2_l2.6": [ # Compound Inequalities
    make_q(8,"An 'and' compound inequality like 2 < x < 8 means x is:",["Outside the interval","*Between 2 and 8 (exclusive)","Less than 2","Greater than 8"],"Both conditions must be true simultaneously."),
    make_q(9,"An 'or' compound inequality means:",["Both must be true","*At least one of the conditions must be true","Neither is true","Exactly one is true"],"Union of solution sets."),
    make_q(10,"Solve: −1 < 2x + 3 < 9",["−2 < x < 9","1 < x < 3","*−2 < x < 3","0 < x < 6"],"Subtract 3: −4 < 2x < 6, divide by 2: −2 < x < 3."),
    make_q(11,"Solve: x + 2 < 1 OR x + 2 > 7",["1 < x < 7","*x < −1 OR x > 5","−1 < x < 5","x < 1 OR x > 7"],"x < −1 or x > 5."),
    make_q(12,"Graph of 'AND' inequality is a _____ on the number line.",["Two rays","Two open dots","*Connected segment (between two points)","The entire line"],"Overlap of two conditions."),
    make_q(13,"Graph of 'OR' inequality is _____ on the number line.",["A connected segment","*Two rays pointing outward","A single point","The empty set"],"Union of two separate conditions."),
    make_q(14,"Solve: 3 ≤ x − 1 ≤ 7",["3 ≤ x ≤ 7","*4 ≤ x ≤ 8","2 ≤ x ≤ 6","1 ≤ x ≤ 8"],"Add 1: 4 ≤ x ≤ 8."),
    make_q(15,"Solve: 2x < −4 OR 3x > 12",["−2 < x < 4","*x < −2 OR x > 4","x < 4 OR x > −2","No solution"],"x < −2 or x > 4."),
    make_q(16,"If −5 ≤ 3x + 1 ≤ 10, find x.",["*−2 ≤ x ≤ 3","−5 ≤ x ≤ 10","−1 ≤ x ≤ 3","0 ≤ x ≤ 3"],"Subtract 1: −6 ≤ 3x ≤ 9, divide by 3: −2 ≤ x ≤ 3."),
    make_q(17,"The compound inequality x > 5 AND x < 2 has:",["x = 3.5","All real numbers","*No solution (no number is both >5 and <2)","x = 0"],"Contradictory conditions."),
    make_q(18,"The compound inequality x > 2 OR x < 8 has:",["Only 2 < x < 8","No solution","*All real numbers (every number satisfies at least one)","Only x = 5"],"Every x is either >2 or <8 (or both)."),
    make_q(19,"Express 'x is at least 3 and at most 10' as a compound inequality.",["x < 3 AND x > 10","*3 ≤ x ≤ 10","x > 3 OR x < 10","3 < x < 10"],"At least = ≥, at most = ≤."),
    make_q(20,"Solve: −4 < −2x < 10",["−5 < x < 2","2 < x < −5","*−5 < x < 2","−2 < x < 5"],"Divide by −2 and flip: −5 < x < 2."),
],
"u2_l2.7": [ # Absolute Value Equations
    make_q(8,"Solve: |x| = 5",["x = 5 only","x = −5 only","*x = 5 or x = −5","No solution"],"Absolute value yields two cases."),
    make_q(9,"Solve: |x − 3| = 7",["x = 4 only","x = −4 only","*x = 10 or x = −4","x = 7"],"x − 3 = 7 → x = 10; x − 3 = −7 → x = −4."),
    make_q(10,"Solve: |2x + 1| = 9",["x = 4 only","x = −5 only","*x = 4 or x = −5","x = 5"],"2x + 1 = 9 → x = 4; 2x + 1 = −9 → x = −5."),
    make_q(11,"|x| = −3 has:",["x = −3","x = 3","*No solution (absolute value can't be negative)","x = ±3"],"Absolute value ≥ 0 always."),
    make_q(12,"Solve: |x + 4| = 0",["x = 4","x = −4 and x = 4","*x = −4","No solution"],"Only one solution: x + 4 = 0 → x = −4."),
    make_q(13,"Solve: 3|x| = 18",["x = 18","*x = 6 or x = −6","x = 6 only","x = 3"],"​|x| = 6, so x = ±6."),
    make_q(14,"|x − 5| = |x + 1| means:",["x = 5","x = 1","*x = 2","x = −1"],"Case analysis: x − 5 = x + 1 gives −5 = 1 (false); x − 5 = −(x + 1) gives 2x = 4, x = 2."),
    make_q(15,"Solve: |3x − 6| = 12",["x = 6 only","*x = 6 or x = −2","x = 2 only","x = −6"],"3x − 6 = 12 → x = 6; 3x − 6 = −12 → x = −2."),
    make_q(16,"The number of solutions to |ax + b| = c depends on whether c is:",["Positive only","Zero only","*Positive (2 solutions), zero (1 solution), or negative (no solution)","Always 2"],"Sign of c determines solution count."),
    make_q(17,"Solve: |x| + 3 = 10",["x = 3","*x = 7 or x = −7","x = 10","No solution"],"​|x| = 7, x = ±7."),
    make_q(18,"Absolute value represents _____ on a number line.",["Direction","*Distance from zero","Position","Magnitude only"],"Distance is always non-negative."),
    make_q(19,"Solve: 2|x − 1| + 3 = 11",["*x = 5 or x = −3","x = 4 or x = −2","x = 5 only","No solution"],"2|x − 1| = 8, |x − 1| = 4, x = 5 or x = −3."),
    make_q(20,"The graph of y = |x| is:",["A straight line","A parabola","*A V-shape with vertex at the origin","A circle"],"Classic V-shape."),
],
"u2_l2.8": [ # Systems of Equations
    make_q(8,"Solve by substitution: y = x + 1, 2x + y = 7",["x = 3, y = 4","*x = 2, y = 3","x = 1, y = 2","x = 4, y = 5"],"2x + (x + 1) = 7, 3x = 6, x = 2, y = 3."),
    make_q(9,"Solve by elimination: x + y = 10, x − y = 4",["x = 3, y = 7","*x = 7, y = 3","x = 10, y = 4","x = 4, y = 6"],"Add equations: 2x = 14, x = 7, y = 3."),
    make_q(10,"A system with no solution has lines that are:",["Intersecting","*Parallel (same slope, different y-intercepts)","Identical","Perpendicular"],"Parallel lines never meet."),
    make_q(11,"A system with infinitely many solutions has lines that are:",["Parallel","Perpendicular","*Identical (the same line)","Intersecting at one point"],"Same line = overlapping."),
    make_q(12,"The solution to a system of two linear equations is:",["Always one point","*The point(s) where the lines intersect (if they do)","Always two points","Never a point"],"Intersection = solution."),
    make_q(13,"Solve: 3x + y = 10, y = 2x",["x = 10, y = 20","*x = 2, y = 4","x = 3, y = 4","x = 5, y = 10"],"3x + 2x = 10, 5x = 10, x = 2, y = 4."),
    make_q(14,"To eliminate y from 2x + 3y = 12 and x − 3y = 6, you can:",["Subtract the equations","*Add the equations (3y and −3y cancel)","Multiply both by 3","Divide both by 3"],"Adding eliminates y."),
    make_q(15,"Solve: 2x + y = 8, x + y = 5",["x = 5, y = 0","*x = 3, y = 2","x = 2, y = 3","x = 4, y = 1"],"Subtract: x = 3, y = 2."),
    make_q(16,"When graphing, the solution to a system is the:",["y-intercept","x-intercept","Slope","*Point of intersection"],"Where lines cross."),
    make_q(17,"Solve: y = −x + 6, y = x − 2",["x = 6, y = 0","*x = 4, y = 2","x = 2, y = 4","x = −2, y = 8"],"−x + 6 = x − 2, 8 = 2x, x = 4, y = 2."),
    make_q(18,"A consistent system has:",["No solution","*At least one solution","Only negative solutions","Infinitely many only"],"Consistent = solutions exist."),
    make_q(19,"An inconsistent system has:",["One solution","Infinitely many","*No solution (parallel lines)","Two solutions"],"No intersection."),
    make_q(20,"To solve 4x + 2y = 10 and 3x + 2y = 8 by elimination:",["Add the equations","*Subtract the equations (2y cancels)","Multiply both by 2","Divide both by 2"],"(4x + 2y) − (3x + 2y) = 10 − 8 → x = 2."),
],
"u2_l2.9": [ # Systems of Inequalities
    make_q(8,"The solution to a system of inequalities is:",["A single point","A line","*A shaded region (the overlap of all individual inequality regions)","An equation"],"Intersection of regions."),
    make_q(9,"When graphing y > 2x + 1, the boundary line is:",["Solid","*Dashed (because > is strict, not ≥)","Bold","Absent"],"Strict inequality = dashed line."),
    make_q(10,"When graphing y ≥ x − 3, the boundary line is:",["Dashed","*Solid (because ≥ includes equality)","Dotted","Double"],"Non-strict inequality = solid line."),
    make_q(11,"Is the point (0, 0) in the solution of y > 2x + 1?",["*No (0 > 1 is false)","Yes","Cannot tell","Only if graphed"],"Test: 0 > 2(0) + 1 → 0 > 1 is false."),
    make_q(12,"For y < 3x − 2, you shade:",["Above the line","On the line","*Below the line","Both sides"],"< means below for y."),
    make_q(13,"For y > −x + 4, you shade:",["Below the line","*Above the line","On the line","Neither"],"Greater-than means above for y."),
    make_q(14,"A system of inequalities can have:",["Exactly one solution","*Infinitely many solutions or no solutions","Exactly two solutions","Only integer solutions"],"Regions contain infinitely many points (or none if no overlap)."),
    make_q(15,"If the shaded regions of two inequalities don't overlap, the system has:",["One solution","*No solution","Infinitely many solutions","Two solutions"],"No overlap = no common solutions."),
    make_q(16,"To check if (2, 5) is a solution to y ≤ 3x + 1 AND y ≥ x + 2:",["Only check one","*Substitute into both: 5 ≤ 7 ✓ and 5 ≥ 4 ✓ — yes, it's a solution","It can't be","Don't substitute"],"Must satisfy ALL inequalities."),
    make_q(17,"The vertices (corner points) of a feasible region are important in:",["All algebra","*Linear programming (optimization problems)","Only graphing","Only geometry"],"Optimal solutions occur at vertices."),
    make_q(18,"How many inequalities can a system contain?",["Only two","Exactly three","*Two or more","Only one"],"Systems can have any number of constraints."),
    make_q(19,"Graph y > 0 AND x > 0. The solution region is:",["Left of y-axis","Below x-axis","*Quadrant I (upper right)","All four quadrants"],"Positive x and y = first quadrant."),
    make_q(20,"The feasible region for a system of linear inequalities is always:",["A circle","A single point","*A polygonal region (or unbounded region) with straight edges","A curve"],"Linear inequalities produce straight boundaries."),
],
# ── U3: Linear Models ──
"u3_l3.1": [ # Scatter Plots
    make_q(8,"A scatter plot shows the relationship between:",["One variable over time","*Two quantitative variables (one on each axis)","Two categorical variables","Frequency of one variable"],"Bivariate quantitative data."),
    make_q(9,"A positive association in a scatter plot means:",["No pattern","*As x increases, y tends to increase","As x increases, y decreases","Points form a circle"],"Upward trend."),
    make_q(10,"A negative association means:",["No pattern","As x increases, y increases","*As x increases, y tends to decrease","Points are random"],"Downward trend."),
    make_q(11,"If points are widely scattered with no trend, the association is:",["Positive","Negative","*No association (no clear pattern)","Perfectly linear"],"Random scatter."),
    make_q(12,"A strong association means points are:",["Spread far apart","In a circle","*Close to a clear pattern or line","Only at two values"],"Clustered near a trend."),
    make_q(13,"An outlier in a scatter plot is a point that:",["Is at the origin","*Falls far from the overall pattern","Is on the x-axis","Is the highest y-value"],"Deviates from the trend."),
    make_q(14,"The explanatory (independent) variable goes on the:",["y-axis","Either axis","*x-axis","Neither axis"],"x-axis for the predictor variable."),
    make_q(15,"The response (dependent) variable goes on the:",["x-axis","*y-axis","Either axis","Neither axis"],"y-axis for the outcome variable."),
    make_q(16,"A scatter plot with a curved pattern suggests:",["Linear model","*A nonlinear relationship (quadratic, exponential, etc.)","No relationship","Perfect correlation"],"Curves indicate nonlinear models."),
    make_q(17,"Clustering in a scatter plot may indicate:",["Errors","*Subgroups in the data","Perfect correlation","No relationship"],"Clusters suggest distinct groups."),
    make_q(18,"Which is best displayed with a scatter plot?",["Favorite colors","*Height vs. weight of students","Categories of pets","Frequency of names"],"Two quantitative variables."),
    make_q(19,"If doubling x roughly doubles y, the relationship is likely:",["Quadratic","*Linear (constant rate of change)","Exponential","No relationship"],"Proportional = linear."),
    make_q(20,"To describe a scatter plot, mention:",["Only the direction","Only the form","*Direction, form (linear/nonlinear), strength, and outliers","Only outliers"],"Full description of the association."),
],
"u3_l3.2": [ # Line of Best Fit
    make_q(8,"A line of best fit is also called:",["The median line","*A regression line (least-squares line)","The mode line","The range line"],"Least-squares regression."),
    make_q(9,"The line of best fit minimizes:",["The maximum residual","*The sum of squared residuals","The range of data","The number of points"],"Least squares criterion."),
    make_q(10,"In ŷ = mx + b, m represents:",["The y-intercept","*The slope (predicted change in y per unit increase in x)","A data point","The residual"],"Slope interpretation."),
    make_q(11,"In ŷ = mx + b, b represents:",["The slope","*The y-intercept (predicted y when x = 0)","A residual","The mean"],"Starting value."),
    make_q(12,"If ŷ = 2x + 5, predict y when x = 10.",["15","20","*25","30"],"ŷ = 2(10) + 5 = 25."),
    make_q(13,"Extrapolation (predicting outside the data range) is:",["Always accurate","*Risky because the pattern may not hold beyond the data","Recommended","Impossible"],"Outside the range is unreliable."),
    make_q(14,"Interpolation (predicting within the data range) is:",["Unreliable","*Generally more reliable than extrapolation","Impossible","Only for categorical data"],"Within range is safer."),
    make_q(15,"A slope of −3 means:",["y increases 3 per unit x","*y decreases 3 for each 1-unit increase in x","No change","x decreases 3"],"Negative slope = negative association."),
    make_q(16,"The line of best fit always passes through:",["The origin","Every data point","*(x̄, ȳ) — the point of averages","The largest data point"],"Goes through the mean point."),
    make_q(17,"If data points are far from the line of best fit, the model is:",["Very accurate","Perfect","*A poor fit (weak association)","Invalid"],"Large residuals = poor fit."),
    make_q(18,"A line of best fit with slope 0 suggests:",["Strong positive association","Strong negative association","*No linear association (horizontal line)","Perfect correlation"],"Flat line = no linear trend."),
    make_q(19,"Which line is the best fit for most data: one with r = 0.95 or r = 0.40?",["r = 0.40","*r = 0.95 (closer to ±1 = stronger fit)","Both are equal","Neither"],"Higher |r| = better fit."),
    make_q(20,"In context: ŷ = 0.5x + 10 where x = study hours and y = test score. The slope means:",["Score starts at 10","*Each additional hour of study predicts a 0.5-point increase in test score","Tests take 10 hours","Time has no effect"],"Slope = rate of change in context."),
],
"u3_l3.3": [ # Residuals
    make_q(8,"A residual is calculated as:",["Predicted − Actual","*Actual − Predicted (observed y − ŷ)","Actual + Predicted","Predicted × Actual"],"Residual = y − ŷ."),
    make_q(9,"A positive residual means the actual value is _____ the predicted value.",["Below","Equal to","*Above","Unrelated to"],"y − ŷ > 0 means y > ŷ."),
    make_q(10,"A negative residual means the model:",["Underpredicted","*Overpredicted (predicted higher than actual)","Was exact","Failed"],"ŷ > y."),
    make_q(11,"If the actual value is 20 and the predicted value is 18, the residual is:",["−2","18","*2","38"],"20 − 18 = 2."),
    make_q(12,"A residual plot should show:",["A clear pattern","An upward trend","*Random scatter (no pattern) if the model is a good fit","A downward trend"],"Randomness validates the linear model."),
    make_q(13,"A curved pattern in a residual plot suggests:",["A perfect fit","*The relationship is not linear (a nonlinear model may be better)","Random error","No association"],"Pattern = model misspecification."),
    make_q(14,"The sum of all residuals for a least-squares line is:",["Always positive","Always negative","*Zero (by design of least squares)","The slope"],"Residuals sum to zero."),
    make_q(15,"A residual of 0 means:",["No data","*The model predicted perfectly for that point","An error occurred","The point is an outlier"],"Actual = Predicted."),
    make_q(16,"Small residuals overall indicate:",["Poor fit","*A good fit (predictions close to actual)","No relationship","Large errors"],"Low residuals = accurate predictions."),
    make_q(17,"An influential point is one that:",["Has a zero residual","Is in the middle of the data","*Significantly changes the regression line if removed","Is always an outlier"],"It pulls the line toward itself."),
    make_q(18,"If predicted = 50 and actual = 42, the residual is:",["50","8","*−8","92"],"42 − 50 = −8."),
    make_q(19,"A fan shape in a residual plot indicates:",["Good fit","*Non-constant variance (heteroscedasticity)","Perfect linearity","No relationship"],"Spread changes = non-constant variance."),
    make_q(20,"Residual plots use _____ on the y-axis and _____ on the x-axis.",["y-values, x-values","*Residuals, predicted values (or x-values)","Predicted, actual","None of these"],"Standard residual plot axes."),
],
"u3_l3.4": [ # Correlation vs. Causation
    make_q(8,"Correlation means:",["One variable causes the other","*Two variables have a statistical association (move together)","Variables are independent","Causation is proven"],"Association only."),
    make_q(9,"'Correlation does not imply causation' means:",["Correlation is useless","*A statistical relationship doesn't prove one variable causes changes in the other","Causation is impossible to prove","Correlation is always weak"],"Lurking variables may be responsible."),
    make_q(10,"A lurking (confounding) variable is:",["The dependent variable","*A hidden variable that affects both variables, creating a misleading association","The independent variable","Always measured"],"Third variable problem."),
    make_q(11,"Ice cream sales and drowning rates are positively correlated. The lurking variable is likely:",["*Hot weather (summer)","Ice cream","Drowning","Water"],"Both increase in summer."),
    make_q(12,"To establish causation, the best method is:",["Observation only","Surveys","*A well-designed controlled experiment","Correlation analysis"],"Experiments control for confounders."),
    make_q(13,"A controlled experiment includes:",["Only observation","*A control group and a treatment group with random assignment","No comparison","Only surveys"],"Isolating the variable of interest."),
    make_q(14,"The correlation coefficient r ranges from:",["0 to 1","0 to ∞","*−1 to 1","−∞ to ∞"],"−1 ≤ r ≤ 1."),
    make_q(15,"r = −0.92 indicates:",["Weak positive","Strong positive","*Strong negative association","No association"],"Close to −1 = strong negative."),
    make_q(16,"r = 0.05 indicates:",["Strong positive","Strong negative","*Very weak or no linear association","Perfect correlation"],"Near 0 = negligible."),
    make_q(17,"r² = 0.81 means ___% of the variation in y is explained by x.",["8.1%","90%","*81%","18%"],"r² × 100 = percent explained."),
    make_q(18,"Even with r close to 1, you cannot claim causation from:",["An experiment","*An observational study (confounders may exist)","A controlled trial","Both"],"Observation ≠ causation."),
    make_q(19,"A spurious correlation is:",["A real causal link","*A statistical correlation between unrelated variables (often due to coincidence or confounders)","A negative correlation","No correlation"],"Misleading association."),
    make_q(20,"Reverse causation means:",["A causes B","There's no causal link","*B actually causes A (opposite of what was assumed)","Both cause each other equally"],"Direction of causation matters."),
],
"u3_l3.5": [ # Two-Way Frequency Tables (Bivariate)
    make_q(8,"A two-way frequency table organizes data for:",["One numerical variable","*Two categorical variables","One categorical variable","Quantitative data"],"Two categories."),
    make_q(9,"Joint frequency refers to:",["Row totals","Column totals","*The count in a specific cell (intersection of two categories)","The grand total"],"Individual cell count."),
    make_q(10,"Marginal frequency refers to:",["Individual cells","*Row or column totals","The center cell","The title"],"Edge totals."),
    make_q(11,"In a table: Male & Dog = 30, Male & Cat = 20. The marginal total for males is:",["30","20","*50","10"],"30 + 20 = 50."),
    make_q(12,"Conditional frequency is calculated by dividing a joint frequency by:",["The grand total","Another joint frequency","*A marginal total (row or column total)","Zero"],"Conditional = cell ÷ margin."),
    make_q(13,"If 60 out of 200 total students prefer math, the relative frequency is:",["60","*0.30 or 30%","200","0.60"],"60/200 = 0.30."),
    make_q(14,"A segmented bar chart displays:",["Individual data points","*Proportions of subcategories within each category (stacked to 100%)","Only raw counts","Only one variable"],"Visual comparison of distributions."),
    make_q(15,"Two variables are independent if:",["They have no data","*The conditional distributions are the same across categories","They are always equal","They have the same frequency"],"Same proportions in all groups = independent."),
    make_q(16,"If the conditional probability of preferring math is 40% for males and 40% for females, the variables are likely:",["Dependent","*Independent","Causal","Unknown"],"Same conditional → independent."),
    make_q(17,"The grand total equals:",["The largest category","*The sum of all cells (or the sum of all marginal totals from one dimension)","The number of categories","The average"],"Sum of everything."),
    make_q(18,"Creating a two-way table from raw data requires:",["Sorting by one variable","*Counting occurrences for each combination of the two variables","Only calculating means","Graphing a scatter plot"],"Tally each category pair."),
    make_q(19,"Chi-square tests use two-way tables to test for:",["Correlation coefficients","*Whether two categorical variables are independent or associated","Linear regression","Means"],"Independence test."),
    make_q(20,"A mosaic plot displays two-way table data using:",["Dots","Lines","*Rectangles whose areas are proportional to frequencies","Bars of equal width"],"Area-based visualization."),
],
"u3_l3.6": [ # Relative Frequency
    make_q(8,"Relative frequency is calculated as:",["Count × Total","*Count ÷ Total (expressed as a fraction, decimal, or percent)","Total ÷ Count","Count + Total"],"Part divided by whole."),
    make_q(9,"If 15 out of 50 students chose pizza, the relative frequency is:",["50","15","*0.30 (or 30%)","35"],"15/50 = 0.30."),
    make_q(10,"All relative frequencies in a distribution sum to:",["0","50%","The total count","*1 (or 100%)"],"They represent the whole."),
    make_q(11,"Relative frequency is more useful than raw frequency when:",["Comparing groups of the same size","*Comparing groups of different sizes","Never","Only with large data"],"Proportions allow fair comparison."),
    make_q(12,"In a relative frequency table, each entry is between:",["−1 and 1","*0 and 1 (inclusive)","0 and the total","1 and 100"],"Non-negative fractions of the whole."),
    make_q(13,"A joint relative frequency is a cell count divided by:",["The row total","The column total","*The grand total","Another cell"],"Cell ÷ grand total."),
    make_q(14,"A conditional relative frequency is a cell count divided by:",["The grand total","*The relevant marginal total (row or column)","Nothing","All other cells"],"Cell ÷ row or column total."),
    make_q(15,"If a column's conditional relative frequencies are similar across rows, the variables appear:",["Associated","*Independent","Causal","Random"],"Same proportions → independence."),
    make_q(16,"Row relative frequencies sum to _____ for each row.",["0.5","*1 (or 100%)","The row total","The grand total"],"Each row sums to 100%."),
    make_q(17,"A relative frequency histogram has bars whose heights represent:",["Counts","*Proportions (or percentages)","Cumulative counts","Absolute values"],"Heights are fractions of the total."),
    make_q(18,"Cumulative relative frequency adds up relative frequencies from:",["Right to left","Largest to smallest","*Smallest to largest (running total)","Random order"],"Running total of proportions."),
    make_q(19,"If Class A: 30/60 prefer blue and Class B: 50/100 prefer blue, both have relative frequency:",["0.30 and 0.50","*0.50 and 0.50 (equal)","0.60 and 1.00","Different"],"30/60 = 50/100 = 0.50."),
    make_q(20,"Converting frequencies to relative frequencies preserves the _____ of the distribution.",["Exact counts","*Shape (proportional relationships)","Standard deviation","Mean"],"Same shape, different scale."),
],
"u3_l3.7": [ # Association in Categorical Data
    make_q(8,"Two categorical variables are associated if:",["They have the same frequency","*The distribution of one variable changes depending on the value of the other","They are independent","They have no data"],"Different conditionals = association."),
    make_q(9,"If the conditional distributions are different across categories, the variables are:",["Independent","*Associated","Unrelated","Causal"],"Differing patterns show association."),
    make_q(10,"A side-by-side bar chart is useful for comparing:",["One variable","*Conditional distributions of a categorical variable across groups","Only means","Only medians"],"Visual comparison of proportions."),
    make_q(11,"If 70% of athletes prefer sports drinks vs. 30% of non-athletes, there is:",["No association","*An association between athlete status and drink preference","Causation","Independence"],"Different proportions = association."),
    make_q(12,"Association does NOT prove:",["A relationship exists","Statistical significance","*Causation (one variable causing the other)","Different proportions"],"Association ≠ causation."),
    make_q(13,"Simpson's paradox occurs when:",["Data is missing","*A trend that appears in subgroups reverses when groups are combined","Variables are independent","Perfect association exists"],"Aggregation reverses the trend."),
    make_q(14,"To determine association from a two-way table, compare:",["Only joint frequencies","Only marginal totals","*Conditional percentages across the groups","Only the grand total"],"Conditional comparison reveals patterns."),
    make_q(15,"Weak association means:",["No relationship at all","*Conditional distributions differ only slightly","Perfect dependence","Variables are causal"],"Small differences in proportions."),
    make_q(16,"Strong association means:",["Variables are independent","Variables are causal","*Conditional distributions differ substantially","Only one variable matters"],"Big differences in proportions."),
    make_q(17,"A scatter plot is not used for association between categorical variables because:",["It's too complicated","It doesn't exist","*Scatter plots require quantitative data on both axes","It's always wrong"],"Wrong data type for scatter plots."),
    make_q(18,"Statistical significance of association can be tested with:",["Correlation coefficient","*A chi-square test of independence","A t-test","Linear regression"],"Chi-square for categorical data."),
    make_q(19,"If gender and major choice show no association, then:",["Only males choose certain majors","*The proportion choosing each major is approximately the same for all genders","Gender determines major","Majors determine gender"],"Equal proportions = no association."),
    make_q(20,"A sample may show apparent association due to:",["True causation only","*Random chance, sampling bias, or confounding variables","Nothing","Only one variable"],"Sample associations may not reflect the population."),
],
# ── U4: Functions ──
"u4_l4.1": [ # Intro to Functions
    make_q(8,"A function is a relation where each input has:",["Multiple outputs","No outputs","*Exactly one output","At least two outputs"],"One output per input."),
    make_q(9,"Which test determines if a graph is a function?",["Horizontal line test","*Vertical line test","Diagonal line test","Slope test"],"If any vertical line hits twice, it's not a function."),
    make_q(10,"The set of all input values is called the:",["Range","Codomain","*Domain","Output"],"Domain = all x-values."),
    make_q(11,"The set of all output values is called the:",["Domain","Input","*Range","Codomain"],"Range = all y-values."),
    make_q(12,"Is {(1,2), (3,4), (1,5)} a function?",["Yes","*No (x = 1 maps to both 2 and 5)","It depends","Cannot tell"],"Same input, different outputs = not a function."),
    make_q(13,"Is {(1,3), (2,3), (4,3)} a function?",["No","*Yes (each input has exactly one output — different inputs can share an output)","Cannot tell","Only if x is unique"],"Different inputs can share outputs."),
    make_q(14,"In f(x) = 2x − 1, f is the _____ name.",["Variable","Equation","*Function","Domain"],"f names the function."),
    make_q(15,"The independent variable is usually:",["y","*x","f","m"],"x is the input/independent variable."),
    make_q(16,"The dependent variable is usually:",["*y (or f(x))","x","m","b"],"y depends on x."),
    make_q(17,"A mapping diagram shows a function if:",["All arrows go to one output","*Each input has exactly one arrow going to an output","Arrows cross","No arrows exist"],"One arrow per input."),
    make_q(18,"Which represents a function? A: y = x², B: x = y², C: x² + y² = 1",["B","C","*A (each x-value gives exactly one y-value)","All of them"],"y = x² passes the vertical line test."),
    make_q(19,"In a real-world function like temperature over time, time is the:",["Range","*Domain (input)","Output","Function name"],"Time is the independent variable."),
    make_q(20,"A discrete function has:",["A smooth curve","*Separate, distinct points (not connected)","A continuous line","No graph"],"Individual points like sequences."),
],
"u4_l4.2": [ # Function Notation
    make_q(8,"If f(x) = 4x + 1, then f(3) =",["4","7","*13","12"],"4(3) + 1 = 13."),
    make_q(9,"If g(x) = x² − 5, then g(−2) =",["−9","9","*−1","1"],"(−2)² − 5 = 4 − 5 = −1."),
    make_q(10,"f(x) = 3x + 2. Find x if f(x) = 14.",["14","*4","2","6"],"3x + 2 = 14, 3x = 12, x = 4."),
    make_q(11,"If h(x) = x² + 2x, then h(0) =",["2","*0","−2","4"],"0 + 0 = 0."),
    make_q(12,"In f(x) notation, x represents:",["The output","The function name","*The input value","A constant"],"x is what you plug in."),
    make_q(13,"f(x) = −2x + 8. Find f(−3).",["2","*14","−14","8"],"−2(−3) + 8 = 6 + 8 = 14."),
    make_q(14,"If f(x) = 5, what type of function is this?",["Linear","Quadratic","*Constant","Exponential"],"Output is always 5 regardless of x."),
    make_q(15,"f(a + 1) means substitute _____ for x.",["a","1","*a + 1","f + 1"],"Replace x with the expression a + 1."),
    make_q(16,"If f(x) = 2x and g(x) = x + 3, then f(g(2)) =",["7","8","*10","4"],"g(2) = 5, f(5) = 10."),
    make_q(17,"The notation f(2) = 7 means:",["x is 7","f is 2","*When the input is 2, the output is 7","f = 2 and x = 7"],"Input 2, output 7."),
    make_q(18,"If f(x) = |x − 4|, then f(1) =",["1","−3","*3","4"],"​|1 − 4| = |−3| = 3."),
    make_q(19,"Evaluate: f(x) = 3x² − 1 at x = −1.",["−4","0","*2","−2"],"3(1) − 1 = 2."),
    make_q(20,"f(x) and y are related by:",["They're unrelated","*f(x) is another way to write y in terms of x","f(x) replaces x","y replaces f"],"f(x) = y."),
],
"u4_l4.3": [ # Domain and Range
    make_q(8,"The domain of f(x) = 1/(x − 4) excludes:",["x = 0","x = 1","*x = 4 (division by zero is undefined)","x = −4"],"Denominator can't be zero."),
    make_q(9,"The domain of f(x) = √(x − 2) is:",["All real numbers","x > 2","*x ≥ 2","x ≤ 2"],"Radicand must be ≥ 0: x − 2 ≥ 0."),
    make_q(10,"The range of f(x) = x² is:",["All real numbers","x ≥ 0","*y ≥ 0 (outputs are non-negative)","y ≤ 0"],"Squaring gives non-negative outputs."),
    make_q(11,"The domain of f(x) = 3x + 7 is:",["x > 0","x ≥ 7","*All real numbers","x ≠ 7"],"Linear functions have no restrictions."),
    make_q(12,"On a graph, the domain is all _____ values covered by the graph.",["*x","y","Slope","Intercept"],"Domain = horizontal extent."),
    make_q(13,"On a graph, the range is all _____ values covered by the graph.",["x","*y","Slope","Intercept"],"Range = vertical extent."),
    make_q(14,"The domain of f(x) = 1/(x² − 9) excludes:",["x = 0","x = 9","*x = 3 and x = −3","x = 1"],"x² − 9 = 0 when x = ±3."),
    make_q(15,"For the ordered pairs {(1,5), (2,8), (3,11)}, the domain is:",["*{1, 2, 3}","{5, 8, 11}","{1, 5}","{2, 8}"],"Domain = set of inputs (x-values)."),
    make_q(16,"For the ordered pairs {(1,5), (2,8), (3,11)}, the range is:",["​{1, 2, 3}","*{5, 8, 11}","​{1, 5}","​{2, 8}"],"Range = set of outputs (y-values)."),
    make_q(17,"In a real-world context, domain restrictions often come from:",["Math conventions only","*Physical constraints (you can't have negative time, negative length, etc.)","Random choice","The range"],"Context limits inputs."),
    make_q(18,"The range of f(x) = |x| is:",["All real numbers","*y ≥ 0","y ≤ 0","y > 0"],"Absolute value is always ≥ 0."),
    make_q(19,"A function defined on [−3, 5] means its domain is:",["All real numbers","x > −3 and x < 5","*−3 ≤ x ≤ 5 (including endpoints)","x = −3 or x = 5"],"Bracket notation includes endpoints."),
    make_q(20,"If a graph has a highest point at y = 10, the range includes:",["Only 10","y > 10","*y ≤ 10 (and whatever the minimum is)","All real numbers"],"Maximum constrains the range."),
],
"u4_l4.4": [ # Evaluating Functions
    make_q(8,"If f(x) = 2x² − 3x + 1, find f(2).",["1","5","*3","7"],"2(4) − 3(2) + 1 = 8 − 6 + 1 = 3."),
    make_q(9,"If g(t) = −t + 10, find g(−4).",["6","−14","*14","−6"],"−(−4) + 10 = 14."),
    make_q(10,"If h(x) = 3x − 7, for what x does h(x) = 8?",["3","8","*5","7"],"3x − 7 = 8, 3x = 15, x = 5."),
    make_q(11,"If f(x) = x³, find f(−2).",["8","−6","*−8","6"],"(−2)³ = −8."),
    make_q(12,"If f(x) = x + 5 and g(x) = 2x, find f(g(3)).",["8","*11","16","6"],"g(3) = 6, f(6) = 11."),
    make_q(13,"Given f(x) = 4x − 1, find f(a + 2).",["4a − 1","4a + 1","*4a + 7","4a + 2"],"4(a + 2) − 1 = 4a + 8 − 1 = 4a + 7."),
    make_q(14,"If f(x) = |2x − 6|, find f(1).",["−4","*4","6","2"],"​|2 − 6| = |−4| = 4."),
    make_q(15,"If f(x) = √(x + 9), find f(0).",["0","9","*3","√9"],"​√(0 + 9) = √9 = 3."),
    make_q(16,"f(x) = 5. What is f(100)?",["100","500","*5","0"],"Constant function always outputs 5."),
    make_q(17,"If f(x) = −x², then f(−3) =",["9","3","*−9","−3"],"−(−3)² = −9."),
    make_q(18,"If g(x) = 2ˣ, find g(5).",["10","25","*32","16"],"2⁵ = 32."),
    make_q(19,"If f(x) = x/(x+1), find f(3).",["1","1/3","*3/4","3/2"],"3/(3+1) = 3/4."),
    make_q(20,"Evaluating a function means:",["Finding the domain","Graphing it","*Substituting a specific input and calculating the output","Simplifying the expression"],"Plug in and compute."),
],
"u4_l4.5": [ # Slope and Rate of Change
    make_q(8,"Slope is calculated as:",["Run over rise","*Rise over run (Δy/Δx)","x over y","y plus x"],"m = (y₂ − y₁)/(x₂ − x₁)."),
    make_q(9,"Find the slope between (2, 3) and (6, 11).",["4","*2","8","1/2"],"(11 − 3)/(6 − 2) = 8/4 = 2."),
    make_q(10,"A horizontal line has a slope of:",["Undefined","1","*0","Infinity"],"No rise = zero slope."),
    make_q(11,"A vertical line has a slope that is:",["0","1","*Undefined","Negative"],"Division by zero (Δx = 0)."),
    make_q(12,"A positive slope means the line goes:",["Down left to right","*Up from left to right","Horizontal","Vertical"],"Rising = positive."),
    make_q(13,"A negative slope means the line goes:",["Up left to right","*Down from left to right","Horizontal","Vertical"],"Falling = negative."),
    make_q(14,"Rate of change in a real-world context represents:",["A fixed number","*How fast one quantity changes compared to another (e.g., speed = distance/time)","Only the y-intercept","A constant"],"Slope = rate of change."),
    make_q(15,"If a car travels 150 miles in 3 hours, the rate of change (speed) is:",["3 mph","150 mph","*50 mph","450 mph"],"150/3 = 50 mph."),
    make_q(16,"Parallel lines have slopes that are:",["Negative reciprocals","*Equal","Opposite signs","Adding to 1"],"Same slope = parallel."),
    make_q(17,"Perpendicular lines have slopes that are:",["Equal","*Negative reciprocals (product = −1)","Both zero","Both undefined"],"m₁ · m₂ = −1."),
    make_q(18,"The slope of a line perpendicular to one with slope 2/3 is:",["2/3","*−3/2","3/2","−2/3"],"Negative reciprocal of 2/3."),
    make_q(19,"Find the slope between (−1, 4) and (3, −2).",["3/2","*−3/2","2/3","−2/3"],"(−2 − 4)/(3 − (−1)) = −6/4 = −3/2."),
    make_q(20,"A constant rate of change produces a _____ graph.",["Curved","Exponential","*Straight line (linear)","Parabolic"],"Linear functions have constant slope."),
],
"u4_l4.6": [ # Arithmetic Sequences
    make_q(8,"The common difference of 3, 7, 11, 15 is:",["3","7","*4","15"],"7 − 3 = 4."),
    make_q(9,"The explicit formula for an arithmetic sequence is:",["aₙ = a₁ · rⁿ⁻¹","*aₙ = a₁ + (n − 1)d","aₙ = n²","aₙ = a₁/n"],"Linear formula."),
    make_q(10,"Find the 10th term of 5, 8, 11, 14, ...",["35","30","*32","38"],"a₁₀ = 5 + 9(3) = 32."),
    make_q(11,"The recursive formula for an arithmetic sequence is:",["*aₙ = aₙ₋₁ + d","aₙ = aₙ₋₁ × r","aₙ = a₁ · n","aₙ = n + 1"],"Each term = previous + d."),
    make_q(12,"Is 2, 6, 18, 54 arithmetic?",["Yes","*No (the differences aren't constant — this is geometric)","Cannot tell","Only partially"],"6−2 = 4, 18−6 = 12 (not constant)."),
    make_q(13,"Find d for the sequence: 20, 15, 10, 5, ...",["5","15","*−5","−10"],"15 − 20 = −5."),
    make_q(14,"An arithmetic sequence is a _____ function with domain of natural numbers.",["Quadratic","Exponential","*Linear","Logarithmic"],"Constant rate of change = linear."),
    make_q(15,"The 50th term of 1, 4, 7, 10, ... is:",["150","151","*148","147"],"a₅₀ = 1 + 49(3) = 148."),
    make_q(16,"If a₁ = 10 and d = −2, find a₆.",["2","*0","−2","10"],"a₆ = 10 + 5(−2) = 0."),
    make_q(17,"The common difference can be found by:",["Dividing consecutive terms","Multiplying consecutive terms","*Subtracting consecutive terms (aₙ₊₁ − aₙ)","Adding all terms"],"d = next − current."),
    make_q(18,"If the 5th term is 23 and d = 4, find a₁.",["23","*7","15","19"],"23 = a₁ + 4(4), a₁ = 23 − 16 = 7."),
    make_q(19,"The sum of the first n terms of an arithmetic sequence is:",["n × d","*Sₙ = n(a₁ + aₙ)/2","a₁ × n","n²"],"Average of first and last, times n."),
    make_q(20,"Graph an arithmetic sequence and the points form a:",["Curve","Parabola","*Straight line","Circle"],"Linear pattern."),
],
"u4_l4.7": [ # Piecewise Functions
    make_q(8,"A piecewise function is defined by:",["One rule for all x","*Different rules for different intervals of the domain","No rules","Only graphs"],"Multiple formulas."),
    make_q(9,"If f(x) = {2x if x < 0; x + 3 if x ≥ 0}, find f(4).",["8","*7","4","3"],"x = 4 ≥ 0, so f(4) = 4 + 3 = 7."),
    make_q(10,"If f(x) = {2x if x < 0; x + 3 if x ≥ 0}, find f(−2).",["1","*−4","5","−2"],"x = −2 < 0, so f(−2) = 2(−2) = −4."),
    make_q(11,"A step function is a type of piecewise function where the output is:",["Always increasing","*Constant over each interval (like stair steps)","Always zero","A straight line"],"Flat segments like a staircase."),
    make_q(12,"The graph of a piecewise function may have:",["Only one piece","*Open and closed circles to indicate included/excluded endpoints","No endpoints","Only curves"],"Endpoints mark transitions between rules."),
    make_q(13,"If f(x) = {x² if x ≤ 1; 3x − 2 if x > 1}, find f(1).",["1 and 1","*1 (uses x²)","3","Both rules"],"x = 1 falls in x ≤ 1 → f(1) = 1² = 1."),
    make_q(14,"If f(x) = {x² if x ≤ 1; 3x − 2 if x > 1}, find f(2).",["4","2","*4","6"],"x = 2 > 1 → f(2) = 3(2) − 2 = 4."),
    make_q(15,"A piecewise function is continuous at a transition point if:",["There's always a gap","*The two pieces meet at the same y-value at that point","The pieces never meet","It's undefined there"],"No gap = continuous."),
    make_q(16,"Which real-world situation is modeled by a piecewise function?",["y = 2x","*Tax brackets (different rates for different income ranges)","y = x²","y = |x|"],"Different rules for different intervals."),
    make_q(17,"The absolute value function f(x) = |x| can be written as a piecewise function:",["f(x) = x for all x","*f(x) = {x if x ≥ 0; −x if x < 0}","f(x) = −x for all x","f(x) = 0"],"Two rules depending on sign."),
    make_q(18,"Graphing a piecewise function requires graphing each:",["Only the first piece","*Piece on its specified domain interval","Piece on the whole domain","Piece as a full function"],"Each piece only on its interval."),
    make_q(19,"If f(x) = {5 if x < 3; 2x if x ≥ 3}, is f continuous at x = 3?",["Yes","*No (left piece gives 5, right piece gives 6)","Cannot determine","Always continuous"],"5 ≠ 6, so there's a jump."),
    make_q(20,"The greatest integer function (floor function) is a piecewise function that:",["Rounds up","*Returns the greatest integer less than or equal to x","Returns x","Is always continuous"],"E.g., floor(3.7) = 3."),
],
"u4_l4.8": [ # Function Transformations
    make_q(8,"f(x) + k shifts the graph:",["Left k","Right k","*Up k units","Down k units"],"Vertical shift up."),
    make_q(9,"f(x) − k shifts the graph:",["Up k","Left k","*Down k units","Right k"],"Vertical shift down."),
    make_q(10,"f(x − h) shifts the graph:",["Left h","Up h","*Right h units","Down h"],"Opposite of the sign inside."),
    make_q(11,"f(x + h) shifts the graph:",["Right h","*Left h units","Up h","Down h"],"Opposite: +h means left."),
    make_q(12,"−f(x) reflects the graph over:",["The y-axis","The origin","*The x-axis","The line y = x"],"Negating output = x-axis reflection."),
    make_q(13,"f(−x) reflects the graph over:",["The x-axis","*The y-axis","The origin","The line y = x"],"Negating input = y-axis reflection."),
    make_q(14,"a·f(x) where a > 1 _____ the graph vertically.",["Compresses","*Stretches","Shifts up","Shifts down"],"Factor > 1 = vertical stretch."),
    make_q(15,"a·f(x) where 0 < a < 1 _____ the graph vertically.",["Stretches","*Compresses","Shifts up","Shifts down"],"Factor between 0 and 1 = compression."),
    make_q(16,"The parent function of y = 3(x − 2)² + 5 is:",["y = 3x²","y = x + 5","*y = x²","y = (x − 2)²"],"The basic function before transformations."),
    make_q(17,"In y = 3(x − 2)² + 5, the vertex is at:",["(3, 5)","(−2, 5)","*(2, 5)","(2, 3)"],"h = 2, k = 5."),
    make_q(18,"If f(x) = x², then f(x − 4) + 1 shifts the parabola:",["Left 4, Down 1","*Right 4, Up 1","Left 4, Up 1","Right 4, Down 1"],"(x − 4) = right 4; +1 = up 1."),
    make_q(19,"The order of transformations is typically:",["*Horizontal shifts and stretches, then vertical stretches and shifts","Any random order","Only vertical first","Reflections last always"],"Inside operations first, then outside."),
    make_q(20,"If f(x) = |x|, describe y = −|x + 2| − 3.",["Shift right 2 and up 3","*Shift left 2, reflect over x-axis, shift down 3","Shift right 2 and down 3","No change"],"L2, reflection, D3."),
],
}

with open(PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

count = 0
for key, extra_qs in EXTRA.items():
    if key in data:
        existing = data[key].get("quiz_questions", [])
        start_num = len(existing) + 1
        for i, q in enumerate(extra_qs):
            q["question_number"] = start_num + i
        data[key]["quiz_questions"] = existing + extra_qs
        count += 1

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"✅ Algebra 1 U1-U4: expanded {count} lessons to 20 questions each")
