#!/usr/bin/env python3
"""Expand Physics U7-U9 quizzes from 7 to 20 questions each (20 lessons)."""
import json, os

PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "content_data", "physics_lessons.json")

NEW_QS = {
# ── Unit 7: Waves & Oscillations ──
"u7_l7.1": [  # Simple Harmonic Motion (SHM)
    ("A mass on a spring oscillates with SHM. At maximum displacement, the velocity is:", ["Maximum","*Zero","Half of maximum","Undefined"], "At max displacement, all energy is potential; velocity = 0."),
    ("The restoring force in SHM is proportional to:", ["Velocity","Acceleration","*Displacement from equilibrium","Mass only"], "F = −kx; force proportional to displacement."),
    ("The angular frequency ω of a mass-spring system is:", ["√(m/k)","*√(k/m)","k/m","m/k"], "ω = √(k/m)."),
    ("If the spring constant doubles, the period of oscillation:", ["Doubles","*Decreases by factor of √2","Stays the same","Halves"], "T = 2π√(m/k); doubling k divides T by √2."),
    ("In SHM, acceleration is maximum when:", ["Velocity is maximum","*Displacement is maximum","At equilibrium","Energy is zero"], "a = −ω²x; max when x is max."),
    ("A simple pendulum's period depends on:", ["Mass","Amplitude (for small angles)","*Length and gravitational acceleration","Spring constant"], "T = 2π√(L/g)."),
    ("Doubling the length of a pendulum changes the period by a factor of:", ["2","1/2","*√2","4"], "T ∝ √L."),
    ("The phase constant φ in x = A cos(ωt + φ) determines:", ["Amplitude","Frequency","*Initial position at t = 0","Maximum speed"], "φ sets the starting phase."),
    ("SHM can be viewed as the projection of:", ["Linear motion","*Uniform circular motion onto a diameter","Parabolic motion","Random motion"], "SHM is the 1D projection of circular motion."),
    ("For SHM, the maximum speed v_max equals:", ["Aω²","A/ω","*Aω","ω/A"], "v_max = Aω."),
    ("Damped oscillations have amplitude that:", ["Increases","Stays constant","*Decreases exponentially over time","Oscillates"], "Damping removes energy, reducing amplitude."),
    ("Critical damping causes the system to:", ["Oscillate forever","Oscillate once","*Return to equilibrium fastest without oscillating","Never return"], "Fastest non-oscillatory return."),
    ("Forced oscillations at the natural frequency produce:", ["Minimum amplitude","*Resonance (maximum amplitude)","No motion","Damping"], "Resonance occurs at natural frequency."),
],
"u7_l7.2": [  # Period, Frequency, Amplitude
    ("Period T and frequency f are related by:", ["T = f","T = 2f","*T = 1/f","T = f²"], "T = 1/f."),
    ("If a wave has frequency 500 Hz, the period is:", ["500 s","0.5 s","*0.002 s","50 s"], "T = 1/500 = 0.002 s."),
    ("Amplitude of a wave measures:", ["Speed","Wavelength","*Maximum displacement from equilibrium","Frequency"], "Amplitude = max displacement."),
    ("Doubling the amplitude of SHM changes the total energy by a factor of:", ["2","√2","*4","8"], "E = ½kA²; energy scales as A²."),
    ("The unit of frequency is:", ["Seconds","Meters","*Hertz (Hz = s⁻¹)","Newtons"], "Hz = cycles per second."),
    ("Angular frequency ω relates to frequency f by:", ["ω = f","ω = f/2π","*ω = 2πf","ω = πf"], "ω = 2πf."),
    ("A 2 Hz oscillation completes one full cycle in:", ["2 s","1 s","*0.5 s","0.25 s"], "T = 1/2 = 0.5 s."),
    ("Increasing the mass on a spring _____ the period.", ["Decreases","*Increases","Doesn't change","Doubles exactly"], "T = 2π√(m/k); more mass → longer period."),
    ("The frequency of a simple pendulum on the Moon (g_Moon ≈ g/6) compared to Earth:", ["Same","*Lower (about 0.41× Earth frequency)","Higher","Double"], "f ∝ √g; lower g → lower f."),
    ("In the equation x = A sin(ωt), x = 0 at t = 0 means the object starts at:", ["Maximum displacement","*Equilibrium","Minimum displacement","Rest"], "sin(0) = 0; starts at equilibrium."),
    ("Period of a mass-spring system does NOT depend on:", ["Mass","Spring constant","*Amplitude (for ideal SHM)","None — it depends on all three"], "Period is independent of amplitude in ideal SHM."),
    ("If frequency is 60 Hz, angular frequency is approximately:", ["60 rad/s","120 rad/s","*377 rad/s","600 rad/s"], "ω = 2π(60) ≈ 377 rad/s."),
    ("A grandfather clock pendulum has a period of approximately _____ to tick each second.", ["0.5 s","*2 s (one tick per half-cycle)","1 s","4 s"], "2-second pendulum; each swing = 1 s."),
],
"u7_l7.3": [  # Energy in SHM
    ("Total energy in undamped SHM is:", ["Constantly changing","*Constant (sum of KE + PE)","Zero","Only kinetic"], "Energy is conserved in undamped SHM."),
    ("At equilibrium in SHM, kinetic energy is _____ and potential energy is _____.", ["Zero, maximum","*Maximum, zero","Both zero","Both maximum"], "All energy is kinetic at equilibrium."),
    ("The total energy of a mass-spring system equals:", ["½mv²","½kx²","*½kA² (where A is amplitude)","mgA"], "E_total = ½kA²."),
    ("If amplitude is tripled, total energy increases by a factor of:", ["3","6","*9","27"], "E ∝ A²."),
    ("The potential energy at displacement x is:", ["½mv²","*½kx²","½kA²","kx"], "PE = ½kx²."),
    ("At x = A/2, what fraction of total energy is potential?", ["1/2","*1/4","3/4","1/8"], "PE/E = (A/2)²/A² = 1/4."),
    ("At x = A/2, kinetic energy is _____ of total energy.", ["1/4","1/2","*3/4","All of it"], "KE = E − PE = 1 − 1/4 = 3/4."),
    ("The velocity at displacement x is:", ["*v = ω√(A² − x²)","v = ωx","v = ωA","v = A/x"], "From energy conservation."),
    ("In a pendulum, energy transforms between:", ["Elastic and thermal","*Gravitational PE and kinetic energy","Chemical and kinetic","Nuclear and kinetic"], "Pendulum swaps KE ↔ gravitational PE."),
    ("If a spring constant is 200 N/m and amplitude is 0.1 m, total energy is:", ["20 J","2 J","*1 J","0.1 J"], "E = ½(200)(0.1²) = 1 J."),
    ("Energy dissipation in damped SHM is primarily due to:", ["Gravity","*Friction/air resistance converting mechanical energy to thermal energy","Spring failure","Mass change"], "Damping converts mechanical → thermal."),
    ("The energy vs. displacement graph for PE in SHM is:", ["Linear","Exponential","*Parabolic (U-shaped)","Sinusoidal"], "PE = ½kx² is a parabola."),
    ("At what displacement is KE = PE?", ["x = 0","x = A","*x = A/√2","x = A/2"], "½kx² = ½k(A²−x²) → x = A/√2."),
],
"u7_l7.4": [  # Wave Properties
    ("A transverse wave has particle motion _____ to the direction of propagation.", ["Parallel","*Perpendicular","At 45°","Random"], "Transverse = perpendicular motion."),
    ("A longitudinal wave has particle motion _____ to the direction of propagation.", ["Perpendicular","*Parallel","At 90°","Circular"], "Longitudinal = parallel motion."),
    ("The wave equation relating speed, frequency, and wavelength is:", ["v = λ/f","v = f/λ","*v = fλ","v = f + λ"], "v = fλ."),
    ("If a wave has frequency 200 Hz and wavelength 1.5 m, its speed is:", ["133 m/s","150 m/s","*300 m/s","400 m/s"], "v = 200 × 1.5 = 300 m/s."),
    ("Sound is an example of a _____ wave.", ["Transverse","*Longitudinal","Electromagnetic","Standing"], "Sound is a longitudinal pressure wave."),
    ("Light is an example of a _____ wave.", ["Longitudinal","*Transverse (electromagnetic)","Mechanical","Longitudinal and transverse"], "EM waves are transverse."),
    ("Wavelength is defined as:", ["Amplitude × frequency","*Distance between consecutive identical points (e.g., crest to crest)","Speed × time","Period × amplitude"], "One full spatial cycle."),
    ("Increasing frequency while speed stays constant causes wavelength to:", ["Increase","*Decrease","Stay the same","Double"], "λ = v/f; higher f → shorter λ."),
    ("Mechanical waves require a _____ to propagate.", ["Vacuum","Electric field","*Medium (solid, liquid, or gas)","Magnetic field"], "Mechanical waves need matter."),
    ("Electromagnetic waves can travel through:", ["Only solids","Only air","*Vacuum (and all media)","Only water"], "EM waves don't need a medium."),
    ("The speed of light in vacuum is approximately:", ["3 × 10⁶ m/s","*3 × 10⁸ m/s","3 × 10¹⁰ m/s","3 × 10⁵ m/s"], "c ≈ 3 × 10⁸ m/s."),
    ("Wave energy is proportional to:", ["Amplitude","Frequency²","*Amplitude² (and also frequency² for EM waves)","Wavelength"], "Energy ∝ A²."),
    ("A wave pulse traveling along a rope and reflecting off a fixed end:", ["Continues unchanged","*Inverts (180° phase change)","Disappears","Speeds up"], "Fixed end → inverted reflection."),
],
"u7_l7.5": [  # Wave Superposition & Interference
    ("The principle of superposition states that overlapping waves:", ["Cancel always","Double always","*Add algebraically (resultant = sum of individual displacements)","Ignore each other"], "Displacement = Σ individual displacements."),
    ("Constructive interference occurs when waves are:", ["Out of phase","*In phase (crests align with crests)","At different frequencies","Perpendicular"], "In-phase → amplitudes add."),
    ("Destructive interference occurs when waves are:", ["In phase","At the same amplitude","*Out of phase by 180° (crests align with troughs)","At different speeds"], "Anti-phase → amplitudes subtract."),
    ("Two waves of equal amplitude interfere constructively. The resultant amplitude is:", ["Same as one wave","*Double the original amplitude","Zero","Half"], "A + A = 2A."),
    ("Two waves of equal amplitude interfere destructively. The resultant amplitude is:", ["Double","Same","*Zero (complete cancellation)","Half"], "A − A = 0."),
    ("Path difference for constructive interference must be:", ["λ/2","λ/4","*nλ (integer multiples of wavelength)","(n+½)λ"], "Whole-number wavelength difference."),
    ("Path difference for destructive interference must be:", ["nλ","0","*(n+½)λ (half-integer multiples of wavelength)","2nλ"], "Half-wavelength offset."),
    ("Young's double-slit experiment demonstrates:", ["Particle nature of light","*Wave nature of light through interference patterns","Reflection","Refraction"], "Interference fringes prove wave behavior."),
    ("In Young's experiment, the fringe spacing increases when:", ["Slit separation increases","*Wavelength increases or slit separation decreases","Frequency increases","Screen moves closer"], "Δy = λL/d; larger λ or smaller d → wider fringes."),
    ("Noise-canceling headphones use:", ["Amplification","*Destructive interference (producing anti-phase sound to cancel ambient noise)","Reflection","Refraction"], "Anti-phase cancellation."),
    ("Thin-film interference (soap bubbles) produces colors because:", ["Reflection only","*Different wavelengths constructively interfere at different film thicknesses","Refraction only","Diffraction only"], "Path difference varies with thickness and wavelength."),
    ("When two waves of slightly different frequencies overlap, they produce:", ["Silence","*Beats (periodic variation in loudness)","A standing wave","Only constructive interference"], "Beat frequency = |f₁ − f₂|."),
    ("Superposition applies to _____ waves.", ["Only transverse","Only longitudinal","Only light","*All types of waves (it's a universal wave principle)"], "Universal wave property."),
],
"u7_l7.6": [  # Standing Waves & Resonance
    ("A standing wave is formed by:", ["A single traveling wave","*Two waves of the same frequency traveling in opposite directions","Two waves of different frequencies","Sound only"], "Counter-propagating waves with same f."),
    ("Points of zero displacement in a standing wave are called:", ["Antinodes","Crests","*Nodes","Troughs"], "Nodes = zero displacement."),
    ("Points of maximum displacement in a standing wave are called:", ["Nodes","*Antinodes","Troughs","Equilibrium points"], "Antinodes = max displacement."),
    ("The fundamental frequency (first harmonic) of a string has:", ["Two antinodes","*One antinode and two nodes (at the fixed ends)","No nodes","Three antinodes"], "Fundamental: simplest mode."),
    ("The second harmonic has _____ the frequency of the fundamental.", ["Half","*Twice","The same","Three times"], "f₂ = 2f₁."),
    ("For a string fixed at both ends, the wavelength of the nth harmonic is:", ["L/n","nL","*2L/n","L/(2n)"], "λₙ = 2L/n."),
    ("Resonance occurs when the driving frequency equals:", ["Any frequency","*The natural frequency (or a harmonic) of the system","Zero","Twice the natural frequency"], "Maximum energy transfer at natural frequency."),
    ("The Tacoma Narrows Bridge collapse (1940) is an example of:", ["Constructive interference","*Resonance (wind-driven oscillations at the bridge's natural frequency)","Diffraction","Reflection"], "Catastrophic resonance."),
    ("An open organ pipe has _____ at both ends.", ["Nodes","*Antinodes","One node and one antinode","Neither"], "Open ends = antinodes."),
    ("A closed organ pipe has a _____ at the closed end and a _____ at the open end.", ["Antinode, node","*Node, antinode","Node, node","Antinode, antinode"], "Closed = node; open = antinode."),
    ("A closed pipe only produces _____ harmonics.", ["Even","*Odd","All","No"], "Closed pipes: 1st, 3rd, 5th... harmonics only."),
    ("The speed of a wave on a string depends on:", ["Amplitude","Frequency","*Tension and linear mass density (v = √(T/μ))","Color"], "v = √(T/μ)."),
    ("Increasing string tension _____ the wave speed and _____ the frequency of harmonics.", ["Decreases, decreases","*Increases, increases","Increases, decreases","Decreases, increases"], "Higher tension → faster waves → higher frequencies."),
],
"u7_l7.7": [  # Doppler Effect
    ("The Doppler effect causes the frequency to appear _____ when a source approaches.", ["Lower","*Higher","The same","Zero"], "Approaching source → compressed waves → higher f."),
    ("When an ambulance drives away from you, the siren pitch:", ["Increases","*Decreases","Stays the same","Stops"], "Receding source → stretched waves → lower f."),
    ("The Doppler effect applies to:", ["Only sound","Only light","*All types of waves (sound, light, water, etc.)","Only electromagnetic waves"], "Universal wave phenomenon."),
    ("If a source moves toward a stationary observer at speed vs, the observed frequency is:", ["f₀(v − v_s)/v","*f₀ × v/(v − v_s)","f₀ × v_s/v","f₀/2"], "Observer hears higher f."),
    ("A star moving away from Earth shows light shifted toward:", ["Blue (shorter wavelength)","*Red (longer wavelength, called redshift)","Green","No change"], "Recession → redshift."),
    ("Blueshift indicates the source is:", ["Stationary","Moving away","*Moving toward the observer","Rotating"], "Approaching → blueshift."),
    ("Hubble's observation of galactic redshift supports:", ["Static universe","*Expanding universe","Contracting universe","Flat universe"], "Redshift → galaxies receding → universe expanding."),
    ("Sonic boom occurs when a source travels:", ["At speed of sound","Below speed of sound","*Faster than the speed of sound (supersonic)","At half the speed of sound"], "Shock wave from v > v_sound."),
    ("The Mach number is defined as:", ["Speed of sound ÷ object speed","*Object speed ÷ speed of sound","Object speed × frequency","Wavelength ÷ speed"], "Mach = v_object / v_sound."),
    ("Mach 2 means the object travels at _____ the speed of sound.", ["Half","Same as","*Twice","Four times"], "Mach 2 = 2× speed of sound."),
    ("Doppler radar measures:", ["Temperature","*Speed of objects (like weather systems) by analyzing frequency shifts of reflected waves","Only distance","Only direction"], "Frequency shift → velocity."),
    ("A source and observer both moving toward each other experience:", ["No Doppler effect","*Maximum Doppler shift (both motions add to increase observed frequency)","Only the source's contribution","Destructive interference"], "Both approaching maximizes the shift."),
    ("Medical ultrasound uses the Doppler effect to measure:", ["Bone density","*Blood flow velocity","Body temperature","Brain waves"], "Frequency shift of reflected ultrasound from moving blood."),
],
"u7_l7.8": [  # Wave-Particle Duality
    ("Wave-particle duality states that:", ["Particles are only particles","Waves are only waves","*All matter and radiation exhibit both wave-like and particle-like properties","Only light shows duality"], "Fundamental quantum concept."),
    ("The de Broglie wavelength of a particle is:", ["*λ = h/p (Planck's constant divided by momentum)","λ = p/h","λ = mc²","λ = hf"], "λ = h/(mv)."),
    ("As a particle's momentum increases, its de Broglie wavelength:", ["Increases","*Decreases","Stays the same","Becomes infinite"], "λ = h/p; larger p → smaller λ."),
    ("Electron diffraction experiments confirmed that electrons:", ["Are only particles","*Have wave properties (they produce diffraction patterns)","Have no mass","Move faster than light"], "Davisson-Germer experiment confirmed electron waves."),
    ("Photons exhibit particle behavior in:", ["Interference","Diffraction","*The photoelectric effect (energy delivered in discrete quanta)","Polarization"], "Photoelectric effect = particle behavior."),
    ("Photons exhibit wave behavior in:", ["Compton scattering","*Double-slit interference (producing an interference pattern)","Photoelectric effect","Pair production"], "Double-slit = wave behavior."),
    ("Heisenberg's uncertainty principle states:", ["Position and velocity can both be known exactly","*Position and momentum cannot both be precisely known simultaneously (Δx·Δp ≥ ℏ/2)","Energy is not conserved","Waves don't exist"], "Fundamental quantum limit."),
    ("The double-slit experiment with single electrons shows:", ["Electrons are only particles","*Individual electrons eventually build up an interference pattern (each electron interferes with itself)","No pattern forms","Electrons don't pass through slits"], "Quantum weirdness — self-interference."),
    ("Planck's constant h ≈:", ["*6.63 × 10⁻³⁴ J·s","6.63 × 10⁻²⁴ J·s","9.81 m/s²","3 × 10⁸ m/s"], "h ≈ 6.63 × 10⁻³⁴ J·s."),
    ("A baseball (0.15 kg at 40 m/s) has a de Broglie wavelength of approximately:", ["1 m","1 mm","*~10⁻³⁴ m (undetectably small)","1 nm"], "λ = h/(0.15×40) ≈ 10⁻³⁴ m."),
    ("Wave-particle duality is significant for:", ["Macroscopic objects","*Subatomic particles (electrons, photons — where λ is comparable to atomic dimensions)","Only baseballs","Only planets"], "Relevant at quantum scales."),
    ("The complementarity principle (Bohr) states:", ["Both properties can be observed simultaneously","*Wave and particle aspects are complementary — observing one excludes observing the other simultaneously","Duality doesn't exist","Only particles exist"], "Measurement determines which aspect is observed."),
    ("Wave-particle duality is foundational to:", ["Classical mechanics","Thermodynamics","*Quantum mechanics (the entire framework rests on this duality)","Only optics"], "Cornerstone of QM."),
],

# ── Unit 8: Sound ──
"u8_l8.1": [  # Nature of Sound Waves
    ("Sound waves are _____ waves.", ["Transverse","*Longitudinal","Electromagnetic","Standing"], "Sound = longitudinal pressure waves."),
    ("Sound requires a _____ to travel.", ["Vacuum","*Medium (solid, liquid, or gas)","Magnetic field","Electric field"], "Mechanical wave needs matter."),
    ("Sound travels fastest in:", ["Gases","*Solids (particles are closest, transmitting vibrations most efficiently)","Liquids","Vacuum"], "Solid > liquid > gas."),
    ("The compressions and rarefactions of a sound wave correspond to regions of:", ["Equal pressure","*High pressure and low pressure","No particles","Maximum displacement only"], "Compressions = high P; rarefactions = low P."),
    ("The frequency range of human hearing is approximately:", ["1 Hz to 100 Hz","*20 Hz to 20,000 Hz","100 Hz to 50,000 Hz","0 Hz to infinity"], "20 Hz – 20 kHz."),
    ("Frequencies above 20,000 Hz are called:", ["Infrasound","*Ultrasound","Audible","Subsonic"], "Above human hearing range."),
    ("Frequencies below 20 Hz are called:", ["Ultrasound","*Infrasound","Audible","Supersonic"], "Below human hearing range."),
    ("Sound cannot travel in:", ["Air","Water","Steel","*A vacuum (no particles to vibrate)"], "No medium → no sound."),
    ("Increasing the temperature of air _____ the speed of sound.", ["Decreases","*Increases (hotter air → faster molecular motion → faster sound transmission)","Doesn't affect","Halves"], "v_sound ∝ √T."),
    ("The human ear converts sound waves to:", ["Light","Heat","*Electrical nerve impulses sent to the brain","Chemical energy"], "Mechanical → electrical transduction."),
    ("Echolocation (used by bats and dolphins) relies on:", ["Light reflection","*Sound wave reflection and timing","Magnetic fields","Infrared radiation"], "Emit sound, listen for echo, compute distance."),
    ("An echo requires a minimum distance of about _____ from the reflecting surface.", ["1 m","5 m","*17 m (sound travels ~34 m round trip in ~0.1 s — minimum for ear to distinguish)","50 m"], "~17 m minimum for perceivable echo."),
    ("Sound intensity decreases with distance because:", ["Frequency changes","*Energy spreads over a larger area (inverse-square law for point source)","Wavelength changes","Speed changes"], "I ∝ 1/r²."),
],
"u8_l8.2": [  # Speed of Sound
    ("The speed of sound in air at 20°C is approximately:", ["100 m/s","*343 m/s","700 m/s","1,000 m/s"], "v ≈ 343 m/s at 20°C."),
    ("The speed of sound in water is approximately:", ["343 m/s","*1,480 m/s","5,000 m/s","300 m/s"], "~1,480 m/s in water."),
    ("The speed of sound in steel is approximately:", ["343 m/s","1,480 m/s","*~5,960 m/s","100 m/s"], "~5,960 m/s in steel."),
    ("Sound speed in air increases by about _____ for each 1°C rise in temperature.", ["1 m/s","*0.6 m/s","3 m/s","10 m/s"], "v ≈ 331 + 0.6T m/s."),
    ("At 0°C, the speed of sound in air is approximately:", ["300 m/s","*331 m/s","343 m/s","350 m/s"], "v = 331 m/s at 0°C."),
    ("If thunder is heard 3 seconds after lightning, the lightning is approximately _____ away.", ["300 m","*1,029 m (~1 km)","3 km","500 m"], "d = 343 × 3 ≈ 1,029 m."),
    ("Sound travels faster in denser media because:", ["There's more space","*Particles are closer together, transmitting vibrations more efficiently","Less friction","Temperature is higher"], "Closer particles = faster transmission."),
    ("The speed of sound depends on the _____ of the medium.", ["Color","*Density and elasticity (bulk modulus)","Frequency","Amplitude"], "v = √(B/ρ) for fluids."),
    ("Mach 1 represents:", ["Twice the speed of sound","Half the speed of sound","*Exactly the speed of sound","The speed of light"], "Mach 1 = speed of sound."),
    ("Sound travels faster in humid air than dry air because:", ["Water is heavier","*Water molecules (H₂O, M=18) are lighter than N₂ (M=28) and O₂ (M=32), reducing average molecular mass","Humidity adds pressure","Temperature increases"], "Lighter molecules → faster speed."),
    ("The relationship v = fλ applies to sound waves:", ["Only in a vacuum","Only in solids","*In all media (universal wave equation)","Only at specific frequencies"], "v = fλ applies to all waves."),
    ("When sound enters a denser medium, its speed _____ and wavelength _____.", ["Decreases, increases","*Increases, increases (frequency stays constant)","Stays same, stays same","Decreases, stays same"], "Higher speed in denser medium → longer wavelength."),
    ("Sonar uses the speed of sound in water to:", ["Generate electricity","*Calculate distances to underwater objects (d = vt/2)","Create waves","Heat water"], "Echo timing → distance."),
],
"u8_l8.3": [  # Intensity & Loudness
    ("Sound intensity is measured in:", ["Hertz","*Watts per square meter (W/m²)","Meters","Newtons"], "I = Power/Area."),
    ("The decibel (dB) scale is:", ["Linear","*Logarithmic (each 10 dB increase = 10× intensity)","Exponential","Constant"], "dB = 10 log(I/I₀)."),
    ("The threshold of hearing (I₀) is approximately:", ["1 W/m²","*10⁻¹² W/m²","10⁻⁶ W/m²","10⁻³ W/m²"], "I₀ = 10⁻¹² W/m²."),
    ("An increase of 10 dB corresponds to intensity multiplied by:", ["2","5","*10","100"], "10 dB = 10× intensity."),
    ("Normal conversation is approximately:", ["20 dB","*60 dB","90 dB","120 dB"], "~60 dB for normal speech."),
    ("The threshold of pain is approximately:", ["60 dB","90 dB","*120-130 dB","200 dB"], "~120-130 dB."),
    ("Prolonged exposure above _____ dB can cause hearing damage.", ["40 dB","60 dB","*85 dB","120 dB"], "85 dB = onset of damage risk."),
    ("If one speaker produces 70 dB, two identical speakers together produce approximately:", ["140 dB","70 dB","*73 dB (double intensity = +3 dB)","80 dB"], "Double intensity → +3 dB."),
    ("Intensity follows the inverse-square law: doubling distance reduces intensity by:", ["Half","*One-quarter (I ∝ 1/r²)","One-eighth","No change"], "I ∝ 1/r²."),
    ("Loudness is the _____ perception of sound intensity.", ["Objective","*Subjective (human perception; depends on frequency and intensity)","Measured","Physical"], "Loudness = perceived intensity."),
    ("A whisper is approximately:", ["0 dB","10 dB","*20-30 dB","60 dB"], "~20-30 dB."),
    ("A jet engine at close range is approximately:", ["80 dB","100 dB","120 dB","*140+ dB"], "~140 dB near a jet engine."),
    ("Sound level meters measure:", ["Frequency","*Decibel level (sound pressure level)","Wavelength","Speed"], "Measures dB SPL."),
],
"u8_l8.4": [  # Pitch & Frequency
    ("Pitch is the perceptual correlate of:", ["Amplitude","*Frequency (higher frequency = higher pitch)","Speed","Wavelength"], "Pitch ∝ frequency."),
    ("Middle C on a piano has a frequency of approximately:", ["200 Hz","*262 Hz","440 Hz","1000 Hz"], "Middle C ≈ 262 Hz."),
    ("Concert pitch A (A4) is tuned to:", ["220 Hz","262 Hz","*440 Hz","880 Hz"], "A4 = 440 Hz standard."),
    ("An octave higher means the frequency:", ["Increases by 100 Hz","*Doubles","Triples","Stays the same"], "Octave = 2× frequency."),
    ("A4 = 440 Hz; A5 (one octave above) =", ["*880 Hz","660 Hz","440 Hz","220 Hz"], "880 Hz = 2 × 440."),
    ("Shorter strings produce _____ frequency and _____ pitch.", ["Lower, lower","*Higher, higher","Higher, lower","Same, same"], "Shorter string → higher f → higher pitch."),
    ("Tighter strings produce _____ pitch.", ["Lower","*Higher (increased tension raises frequency)","The same","No sound"], "More tension → higher frequency."),
    ("The human voice produces sound by:", ["Blowing air","*Vibration of vocal cords (folds) in the larynx","Clapping","Electronic means"], "Vocal cord vibration."),
    ("Men's voices are generally lower-pitched because their vocal cords are:", ["Shorter","*Longer and thicker (lower natural frequency)","The same size","Thinner"], "Longer/thicker → lower frequency."),
    ("Musical instruments produce rich sounds through:", ["Only the fundamental frequency","*The fundamental plus overtones/harmonics (creating unique timbre)","Only noise","Only one frequency"], "Harmonics create timbre."),
    ("Two notes an octave apart sound 'similar' because:", ["Same amplitude","*Their frequencies have a simple 2:1 ratio (perceived as consonant)","Same wavelength","They're identical"], "2:1 ratio = octave consonance."),
    ("Infrasound (below 20 Hz) can be produced by:", ["Whistles","*Earthquakes, volcanoes, large machinery, wind","Tuning forks","Violins"], "Very low-frequency sources."),
    ("Ultrasound (above 20 kHz) is used in:", ["Radio broadcasting","*Medical imaging, cleaning, and sonar","Music production","Photography"], "Medical ultrasound, etc."),
],
"u8_l8.5": [  # Resonance in Air Columns
    ("In an open pipe, the fundamental wavelength equals:", ["L","*2L (where L is the pipe length)","L/2","4L"], "Open pipe fundamental: λ₁ = 2L."),
    ("In a closed pipe, the fundamental wavelength equals:", ["2L","L","*4L","L/2"], "Closed pipe fundamental: λ₁ = 4L."),
    ("Open pipes produce:", ["Only odd harmonics","*All harmonics (1st, 2nd, 3rd, 4th, etc.)","Only even harmonics","No harmonics"], "Open pipe: all harmonics."),
    ("Closed pipes produce:", ["All harmonics","Only even harmonics","*Only odd harmonics (1st, 3rd, 5th, etc.)","No harmonics"], "Closed pipe: odd harmonics only."),
    ("The frequency of the fundamental in an open pipe of length 0.5 m (v = 343 m/s) is:", ["171.5 Hz","*343 Hz","686 Hz","85.75 Hz"], "f₁ = v/(2L) = 343/1 = 343 Hz."),
    ("The frequency of the fundamental in a closed pipe of length 0.5 m (v = 343 m/s) is:", ["343 Hz","*171.5 Hz","686 Hz","85.75 Hz"], "f₁ = v/(4L) = 343/2 = 171.5 Hz."),
    ("A longer pipe produces a _____ fundamental frequency.", ["Higher","*Lower","Same","Undefined"], "f ∝ 1/L; longer pipe → lower f."),
    ("Wind instruments change pitch by:", ["Changing material","*Changing effective length of the air column (valves, slides, finger holes)","Changing temperature","Changing air pressure"], "Length changes → frequency changes."),
    ("End correction accounts for the fact that:", ["Sound stops at the end","*The antinode extends slightly beyond the physical end of the pipe","Nodes don't form","Temperature varies"], "Effective length > physical length."),
    ("A flute is modeled as a(n) _____ pipe.", ["Closed","*Open (at both ends)","Neither","Partially closed"], "Flute = open pipe."),
    ("A clarinet is modeled as a(n) _____ pipe.", ["Open","*Closed (at one end — the reed end acts as a closed end)","Neither","Double open"], "Clarinet = closed pipe (reed end)."),
    ("The second harmonic of an open pipe has frequency:", ["f₁/2","*2f₁","3f₁","4f₁"], "f₂ = 2f₁ for open pipe."),
    ("The third harmonic of a closed pipe has frequency:", ["2f₁","*3f₁","4f₁","f₁/3"], "Closed pipe: 3rd harmonic = 3f₁."),
],
"u8_l8.6": [  # Beats & Harmonics
    ("Beat frequency equals:", ["f₁ + f₂","f₁ × f₂","*|f₁ − f₂|","f₁ / f₂"], "f_beat = |f₁ − f₂|."),
    ("If two tuning forks vibrate at 440 Hz and 444 Hz, the beat frequency is:", ["884 Hz","440 Hz","*4 Hz (4 beats per second)","222 Hz"], "|444 − 440| = 4 Hz."),
    ("Beats are heard as:", ["A constant tone","*Periodic pulsation in loudness","A change in pitch","Silence"], "Alternating constructive/destructive interference."),
    ("Musicians use beats to tune instruments by:", ["Maximizing beat frequency","*Adjusting until beat frequency is zero (frequencies match exactly)","Ignoring the sound","Increasing volume"], "Zero beats = in tune."),
    ("The fundamental frequency is also called the:", ["*First harmonic","Second harmonic","Zeroth harmonic","No harmonic"], "Fundamental = 1st harmonic."),
    ("The nth harmonic has frequency:", ["f₁/n","f₁ + n","*nf₁ (n times the fundamental)","f₁ − n"], "fₙ = nf₁."),
    ("Timbre (tone quality) is determined by:", ["Only frequency","Only amplitude","*The mixture and relative amplitudes of harmonics present","Only speed"], "Harmonic content = timbre."),
    ("A violin and piano playing the same note sound different because of:", ["Different frequencies","Different amplitudes","*Different harmonic content (different timbre)","Different speeds of sound"], "Same fundamental, different overtone structure."),
    ("Fourier analysis decomposes a complex wave into:", ["Random noise","*A sum of sinusoidal components (harmonics) at different frequencies and amplitudes","One frequency","Pure silence"], "Any periodic wave = sum of sine waves."),
    ("If beat frequency is 2 Hz and one source is 256 Hz, the other is:", ["254 Hz only","258 Hz only","*Either 254 Hz or 258 Hz","256 Hz"], "f₂ = 256 ± 2 Hz."),
    ("Harmonics that are integer multiples of the fundamental are also called:", ["Noise","*Overtones (the 2nd harmonic = 1st overtone, etc.)","Dissonance","Subharmonics"], "Overtone numbering."),
    ("A pure tone (single frequency) contains:", ["Many harmonics","*Only the fundamental (no overtones)","Only odd harmonics","No frequency"], "Pure tone = single sinusoidal frequency."),
    ("Rich, warm musical tones contain:", ["No harmonics","Only the fundamental","*Strong lower harmonics (few high-frequency overtones)","Only odd harmonics"], "Strong lower harmonics = warm sound."),
],

# ── Unit 9: Optics ──
"u9_l9.1": [  # Reflection & Refraction
    ("The law of reflection states:", ["Angle of incidence > angle of reflection","*Angle of incidence = angle of reflection (measured from normal)","Angles are measured from surface","Light bends at mirrors"], "θᵢ = θᵣ."),
    ("Snell's Law relates:", ["Angle and speed only","*n₁ sin θ₁ = n₂ sin θ₂ (angles of incidence and refraction to refractive indices)","Only reflection","Only diffraction"], "Snell's Law of refraction."),
    ("The index of refraction of a vacuum is:", ["0","*1","1.5","2"], "n_vacuum = 1 (by definition)."),
    ("The index of refraction of water is approximately:", ["1.0","*1.33","1.5","2.0"], "n_water ≈ 1.33."),
    ("The index of refraction of glass is approximately:", ["1.0","1.33","*1.5","2.0"], "n_glass ≈ 1.5."),
    ("When light enters a denser medium (higher n), it bends:", ["Away from normal","*Toward the normal","Not at all","Backwards"], "Higher n → slower speed → toward normal."),
    ("When light enters a less dense medium (lower n), it bends:", ["Toward the normal","*Away from the normal","Not at all","Backward"], "Lower n → faster speed → away from normal."),
    ("The speed of light in a medium with n = 1.5 is:", ["3 × 10⁸ m/s","*2 × 10⁸ m/s","1.5 × 10⁸ m/s","4.5 × 10⁸ m/s"], "v = c/n = 3×10⁸/1.5 = 2×10⁸ m/s."),
    ("A rainbow forms due to:", ["Only reflection","Only refraction","*Refraction, dispersion, and internal reflection in water droplets","Diffraction only"], "Multiple optical phenomena in droplets."),
    ("Dispersion separates white light into colors because:", ["All colors travel at the same speed","*Different wavelengths have slightly different refractive indices (shorter λ bends more)","Only red is refracted","Mirrors split light"], "n varies with λ."),
    ("A pencil in water appears bent due to:", ["Reflection","*Refraction (light changes direction crossing the water-air boundary)","Diffraction","Interference"], "Refraction at the interface."),
    ("Specular reflection occurs on _____ surfaces.", ["Rough","*Smooth (mirror-like)","All","No"], "Smooth → specular; rough → diffuse."),
    ("Diffuse reflection occurs on _____ surfaces.", ["Smooth","*Rough (light scatters in many directions)","Transparent","No"], "Rough surface scatters light."),
],
"u9_l9.2": [  # Lenses & Mirrors
    ("A convex (converging) lens brings parallel light to a:", ["Virtual focus","*Real focal point","No focus","Infinity"], "Convex lens converges light."),
    ("A concave (diverging) lens causes parallel light to:", ["Converge","*Diverge (appear to come from a virtual focal point)","Stay parallel","Stop"], "Concave lens diverges light."),
    ("The thin lens equation is:", ["*1/f = 1/dₒ + 1/dᵢ","f = dₒ + dᵢ","f = dₒ × dᵢ","1/f = 1/dₒ − 1/dᵢ"], "Thin lens equation."),
    ("Magnification m = −dᵢ/dₒ. A negative m means the image is:", ["Upright","*Inverted","Virtual","Enlarged"], "Negative m → inverted image."),
    ("A concave mirror converges light and can form:", ["Only virtual images","*Both real and virtual images (depending on object distance)","No images","Only inverted images"], "Concave: real or virtual depending on dₒ."),
    ("A convex mirror always forms images that are:", ["Real and inverted","*Virtual, upright, and diminished","Real and upright","Virtual and enlarged"], "Convex mirrors: always virtual, upright, smaller."),
    ("The focal length of a mirror relates to its radius of curvature by:", ["f = R","*f = R/2","f = 2R","f = R²"], "f = R/2."),
    ("Real images are formed _____ the lens/mirror and can be _____ on a screen.", ["Behind, not projected","*On the opposite side, projected","At the lens, never","Only by concave lenses"], "Real images can be projected."),
    ("Virtual images are formed _____ and cannot be projected on a screen.", ["*On the same side as the object (for mirrors) or behind the lens","In front of everything","At infinity","Nowhere"], "Virtual images cannot be caught on a screen."),
    ("A magnifying glass uses a _____ lens with the object inside the _____.", ["Concave, focal point","*Convex, focal length (dₒ < f, creating enlarged virtual image)","Flat, center","Concave, center"], "Object closer than f → virtual magnified image."),
    ("Nearsightedness (myopia) is corrected with:", ["Convex lenses","*Concave (diverging) lenses","Flat lenses","Mirrors"], "Diverging lens moves focus back to retina."),
    ("Farsightedness (hyperopia) is corrected with:", ["Concave lenses","*Convex (converging) lenses","Flat lenses","Prisms"], "Converging lens moves focus forward to retina."),
    ("Lens power is measured in diopters (D) where D =", ["f","f²","*1/f (where f is in meters)","f/2"], "D = 1/f (in meters)."),
],
"u9_l9.3": [  # Total Internal Reflection
    ("Total internal reflection occurs when light travels from a _____ medium to a _____ medium.", ["Less dense, more dense","*More dense (higher n), less dense (lower n)","Same, same","Any, any"], "Dense → less dense, at angles above critical."),
    ("The critical angle is the angle of incidence at which:", ["Light is fully refracted","*The refracted ray travels along the boundary (angle of refraction = 90°)","No light passes","Light speeds up"], "At critical angle, refracted ray = 90°."),
    ("Above the critical angle, light is:", ["Partially refracted","Absorbed","*Totally internally reflected (no refraction occurs)","Diffracted"], "100% reflection above critical angle."),
    ("The critical angle for glass (n=1.5) to air is approximately:", ["30°","*42°","60°","90°"], "sin θc = 1/1.5 → θc ≈ 42°."),
    ("The critical angle for water (n=1.33) to air is approximately:", ["42°","*49°","60°","33°"], "sin θc = 1/1.33 → θc ≈ 49°."),
    ("Fiber optics work by:", ["Refraction only","Diffraction","*Total internal reflection (light bounces along the fiber's interior)","Absorption"], "TIR keeps light inside the fiber."),
    ("Optical fibers are used in:", ["Only decoration","*Telecommunications, medical endoscopy, internet data transmission","Only art","Only lighting"], "Many practical applications."),
    ("Diamonds sparkle intensely because:", ["They're hard","*They have a very high refractive index (n≈2.42) → very small critical angle → extensive TIR","They're expensive","They absorb light"], "High n → small critical angle → lots of internal reflections."),
    ("The critical angle formula is:", ["sin θc = n₂/n₁ (n₁ < n₂)","*sin θc = n₂/n₁ (where n₁ > n₂)","θc = n₁ + n₂","θc = 45° always"], "sin θc = n₂/n₁ (going from denser to less dense)."),
    ("A mirage on a hot road is caused by:", ["Water on the road","*TIR-like refraction: light bends due to temperature gradient in air near hot surface","Reflection from the road","Diffraction"], "Temperature gradient creates refractive index gradient."),
    ("For TIR to occur, light must be traveling in the medium with _____ refractive index.", ["Lower","*Higher","Equal","Zero"], "Must go from higher to lower n."),
    ("Prisms use refraction to:", ["Reflect all light","*Separate white light into a spectrum (dispersion) and redirect beams","Absorb light","Block light"], "Prism → dispersion via refraction."),
    ("In fiber optic cables, the core has a _____ refractive index than the cladding.", ["Lower","*Higher (so light undergoes TIR at the core-cladding boundary)","Equal","Variable"], "Core n > cladding n for TIR."),
],
"u9_l9.4": [  # Optical Instruments
    ("The human eye focuses light using a:", ["Concave lens","*Convex (converging) lens that changes shape (accommodation)","Mirror","Prism"], "Eye lens is convex; ciliary muscles change its curvature."),
    ("A camera uses a _____ to form a real image on the sensor/film.", ["Concave lens","*Convex lens (or lens system)","Mirror only","Prism"], "Camera lens → real inverted image on sensor."),
    ("A compound microscope uses _____ converging lenses.", ["One","*Two (objective and eyepiece)","Three","No"], "Objective + eyepiece."),
    ("The objective lens of a microscope produces:", ["A virtual image","*A real, magnified, inverted intermediate image","A diminished image","No image"], "Objective → real magnified intermediate image."),
    ("Total magnification of a compound microscope =", ["m_objective + m_eyepiece","*m_objective × m_eyepiece","m_objective − m_eyepiece","m_objective / m_eyepiece"], "Multiply the two magnifications."),
    ("A refracting telescope uses:", ["Mirrors","Only one lens","*Two converging lenses (objective + eyepiece)","Prisms only"], "Two lenses for refracting telescope."),
    ("A reflecting telescope (Newtonian) uses a _____ as the primary light-gathering element.", ["Lens","*Concave mirror","Convex mirror","Prism"], "Concave mirror gathers and focuses light."),
    ("The magnifying power of a telescope =", ["f_eyepiece / f_objective","*f_objective / f_eyepiece","f_objective + f_eyepiece","f_objective × f_eyepiece"], "M = f_obj / f_eye."),
    ("Larger objective lenses/mirrors in telescopes provide:", ["Less light","*More light-gathering ability and better resolution","Smaller images","No advantage"], "Bigger aperture → more light, better resolution."),
    ("Aberrations in lenses include:", ["Only one type","*Chromatic (color fringing) and spherical (edge distortion)","No errors","Only for mirrors"], "Common lens defects."),
    ("Chromatic aberration occurs because:", ["Lenses are dirty","*Different wavelengths focus at slightly different points (dispersion in the lens)","Lenses are too thick","Mirrors cause it"], "Different colors → different focal lengths."),
    ("An endoscope uses _____ to view inside the body.", ["X-rays","*Fiber optics (total internal reflection to transmit images)","Sound waves","Magnets"], "Fiber optic medical instrument."),
    ("Adaptive optics in telescopes correct for:", ["Lens scratches","*Atmospheric distortion (turbulence that blurs images)","Chromatic aberration","Dust on mirrors"], "Deformable mirror corrects atmospheric effects."),
],
"u9_l9.5": [  # Diffraction & Interference
    ("Diffraction is the _____ of waves around obstacles or through openings.", ["Reflection","Refraction","*Bending/spreading","Absorption"], "Waves spread around barriers/through slits."),
    ("Diffraction is most noticeable when the slit/obstacle size is:", ["Much larger than wavelength","*Comparable to the wavelength","Much smaller than wavelength","Infinite"], "Significant when aperture ≈ λ."),
    ("Single-slit diffraction produces:", ["Sharp lines","*A central bright maximum with dimmer secondary maxima on both sides","No pattern","Only darkness"], "Central max + secondary fringes."),
    ("For single-slit diffraction, the first minimum occurs at:", ["*a sin θ = λ (where a is slit width)","a sin θ = 2λ","a cos θ = λ","No minimum exists"], "First dark fringe: a sin θ = λ."),
    ("A diffraction grating has _____ slits.", ["One","Two","*Many (hundreds to thousands per mm)","Zero"], "Many parallel slits for sharp maxima."),
    ("Diffraction grating maxima occur at:", ["*d sin θ = nλ (where d is slit spacing)","d cos θ = nλ","d sin θ = (n+½)λ","d/λ = n"], "Constructive interference condition."),
    ("CDs and DVDs display rainbow colors because:", ["They contain dye","*Their closely spaced tracks act as a diffraction grating","They reflect all light","They absorb colors"], "Track spacing ≈ light wavelength → diffraction."),
    ("Increasing the number of slits in a grating makes maxima:", ["Broader","*Sharper and brighter (more precise wavelength selection)","Wider","Dimmer"], "More slits → sharper peaks."),
    ("X-ray diffraction is used to determine:", ["Color","*Crystal structure and atomic spacing (Bragg diffraction)","Temperature","Sound speed"], "X-rays diffract off crystal planes."),
    ("The resolving power of a telescope increases with:", ["Smaller aperture","*Larger aperture (better angular resolution)","Longer focal length","Higher magnification only"], "Resolution ∝ D/λ."),
    ("Rayleigh's criterion for resolution states two sources are just resolved when:", ["Their images overlap completely","*The central maximum of one falls on the first minimum of the other","They're at different distances","They have different colors"], "Minimum resolvable angle."),
    ("Diffraction limits the _____ of all optical instruments.", ["Magnification","Brightness","*Resolution (ability to distinguish fine details)","Focal length"], "Diffraction sets resolution limit."),
    ("Electron microscopes achieve better resolution than light microscopes because:", ["Electrons are bigger","*Electrons have much shorter de Broglie wavelength → smaller diffraction limit","They use more power","They're newer"], "Shorter λ → better resolution."),
],
"u9_l9.6": [  # Polarization
    ("Polarization demonstrates that light is a:", ["Longitudinal wave","*Transverse wave (only transverse waves can be polarized)","Standing wave","Sound wave"], "Polarization = transverse wave evidence."),
    ("Unpolarized light has electric field vibrations in:", ["One direction","Two directions","*All directions perpendicular to propagation","None"], "Random E-field directions."),
    ("A polarizing filter transmits light vibrating in:", ["All directions","*One specific direction (the transmission axis)","No direction","Two directions"], "Passes one polarization direction."),
    ("Malus's Law states that the intensity through a second polarizer is:", ["I₀ cos θ","I₀ sin θ","*I₀ cos²θ (where θ is the angle between polarizer axes)","I₀ sin²θ"], "I = I₀ cos²θ."),
    ("When two polarizers are crossed (90° apart), the transmitted intensity is:", ["I₀","I₀/2","*Zero (cos²90° = 0)","I₀/4"], "Crossed polarizers block all light."),
    ("Unpolarized light passing through one polarizer has intensity reduced to:", ["Zero","I₀","*I₀/2","I₀/4"], "First polarizer passes half."),
    ("Polarized sunglasses reduce glare by:", ["Absorbing all light","*Blocking horizontally polarized reflected light (glare is predominantly horizontally polarized)","Being tinted","Reflecting light"], "Vertical transmission axis blocks horizontal glare."),
    ("Light reflected from a surface at Brewster's angle is:", ["Unpolarized","Circularly polarized","*Completely polarized (parallel to the surface)","Not reflected"], "At Brewster's angle, reflected light is fully polarized."),
    ("Brewster's angle θ_B satisfies:", ["sin θ_B = n₂/n₁","*tan θ_B = n₂/n₁","cos θ_B = n₂/n₁","θ_B = 45° always"], "tan θ_B = n₂/n₁."),
    ("LCD screens use:", ["Only mirrors","*Polarized light controlled by liquid crystals between two polarizing filters","Sound waves","Only LEDs"], "Polarization-based display technology."),
    ("Circular polarization involves the E-field vector:", ["Staying fixed","*Rotating as the wave propagates (tracing a circle or ellipse)","Oscillating linearly","Disappearing"], "E-field rotates in a helix."),
    ("Optical activity (rotating polarization plane) is exhibited by:", ["All materials","*Certain crystals and solutions (like sugar solutions — used to measure concentration)","Only metals","Only gases"], "Optically active substances rotate polarization."),
    ("Polarimetry measures:", ["Light speed","*The rotation of polarized light through optically active substances (determining concentration)","Wavelength","Amplitude"], "Sugar concentration measured by polarization rotation."),
],
}

# ── Write ──
with open(PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

count = 0
for key, questions in NEW_QS.items():
    if key not in data:
        print(f"⚠️ Key {key} not found, skipping")
        continue
    existing = data[key].get("quiz_questions", [])
    start_num = len(existing) + 1
    for i, (qt, opts, exp) in enumerate(questions):
        options = []
        for o in opts:
            correct = o.startswith("*")
            options.append({"text": o.lstrip("*"), "is_correct": correct, "data_i18n": None})
        existing.append({
            "question_number": start_num + i,
            "question_text": qt,
            "attempted": 2,
            "data_i18n": None,
            "options": options,
            "explanation": exp
        })
    data[key]["quiz_questions"] = existing
    count += 1

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"✅ Physics U7-U9: expanded {count} lessons to 20 questions each")
