#!/usr/bin/env python3
"""Add 13 more quiz questions to Biology Units 5-8 (24 lessons)."""
import json, os

PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "content_data", "biology_lessons.json")

def make_q(num, text, opts, explanation):
    options = []
    for o in opts:
        correct = o.startswith("*")
        options.append({"text": o.lstrip("*"), "is_correct": correct, "data_i18n": None})
    return {"question_number": num, "question_text": text, "attempted": 2,
            "data_i18n": None, "options": options, "explanation": explanation}

EXTRA = {
# ── U5: Biodiversity & Conservation ──
"u5_l5.1": [ # Biodiversity
    make_q(8,"Species diversity, genetic diversity, and ecosystem diversity are the three levels of:",["Evolution","*Biodiversity","Taxonomy","Ecology"],"Three levels of biodiversity."),
    make_q(9,"A biodiversity 'hotspot' is defined by having at least _____ endemic plant species and having lost 70%+ of original habitat.",["100","500","*1,500","10,000"],"Hotspot criteria."),
    make_q(10,"Which biome has the highest species diversity?",["Tundra","Temperate forest","Desert","*Tropical rainforest"],"Richest biome."),
    make_q(11,"The number of different species in a given area is called:",["Genetic diversity","*Species richness","Population density","Biomass"],"Species richness definition."),
    make_q(12,"Why are keystone species important to biodiversity?",["They are the most abundant","*Their removal causes disproportionate ecosystem change","They are the largest","They produce the most offspring"],"Disproportionate impact."),
    make_q(13,"Islands generally have _____ biodiversity than mainland areas of the same size.",["Higher","*Lower","The same","Unpredictable"],"Island biogeography."),
    make_q(14,"Ecosystem services provided by biodiversity include:",["Only food","Only medicine","Only timber","*Pollination, water purification, climate regulation, food, and medicine"],"Multiple services."),
    make_q(15,"The latitudinal diversity gradient means biodiversity is generally:",["Higher at poles","*Higher near the equator","Equal everywhere","Higher in deserts"],"Equatorial richness."),
    make_q(16,"Which metric accounts for both species richness AND evenness?",["Population size","*Shannon diversity index","Carrying capacity","Birth rate"],"Diversity indices."),
    make_q(17,"Coral reefs are called 'rainforests of the sea' because they:",["Are warm","Are wet","*Support enormous biodiversity despite covering less than 1% of ocean floor","Are colorful"],"Marine biodiversity hotspot."),
    make_q(18,"Genetic diversity within a species is important because it:",["Makes organisms identical","*Provides variation for adaptation to changing environments","Reduces mutation","Slows evolution"],"Adaptation potential."),
    make_q(19,"Approximately how many species have been identified on Earth?",["100,000","500,000","*~1.5-2 million (estimated 8-10 million total)","50 million"],"Known species count."),
    make_q(20,"Biodiversity tends to decrease with:",["Increasing temperature","*Increasing latitude (toward the poles)","Increasing rainfall","Increasing elevation only"],"Latitude effect."),
],
"u5_l5.2": [ # Threats to Biodiversity
    make_q(8,"The greatest current threat to biodiversity is:",["Pollution","Invasive species","*Habitat loss and fragmentation","Overexploitation"],"Primary threat."),
    make_q(9,"Habitat fragmentation reduces biodiversity by:",["Increasing predators","*Isolating populations, reducing gene flow, and creating edge effects","Increasing food","Reducing sunlight"],"Fragmentation impacts."),
    make_q(10,"Invasive species harm native biodiversity by:",["Improving habitats","*Competing for resources, preying on natives, and introducing diseases","Increasing diversity","Adding nutrients"],"Competition and predation."),
    make_q(11,"Ocean acidification threatens marine biodiversity because it:",["Warms water","*Dissolves calcium carbonate shells and coral skeletons","Adds oxygen","Reduces salt"],"CO₂ absorption effect."),
    make_q(12,"The current rate of extinction is estimated to be _____ times the background rate.",["2-5","10-50","*100-1,000","Exactly the same"],"Mass extinction rate."),
    make_q(13,"Deforestation in tropical regions eliminates approximately _____ acres annually.",["1,000","100,000","*~18 million (about 27 soccer fields per minute)","1 billion"],"Tropical loss rate."),
    make_q(14,"Pollution affects biodiversity through:",["Only water contamination","Only air quality","*Water, air, and soil contamination plus bioaccumulation of toxins in food chains","Only noise"],"Multiple pollution pathways."),
    make_q(15,"Overexploitation of species includes:",["Only hunting","Only fishing","*Overhunting, overfishing, illegal wildlife trade, and excessive harvesting of plants","Only logging"],"Multiple forms."),
    make_q(16,"Climate change threatens biodiversity by:",["Only warming","*Shifting habitats faster than many species can adapt or migrate, altering phenology and food webs","Only flooding","Only drought"],"Complex climate impacts."),
    make_q(17,"An 'edge effect' in fragmented habitats means:",["More interior habitat","*Conditions at habitat borders differ from interior, favoring generalists over specialists","Less wind","Better food"],"Edge vs. interior."),
    make_q(18,"Bioaccumulation refers to:",["Quick decomposition","*Buildup of toxins (like mercury, DDT) in organisms at higher levels in the food chain","Nutrient cycling","Photosynthesis"],"Toxin concentration."),
    make_q(19,"Which human activity contributes most to freshwater biodiversity loss?",["Tourism","*Dam construction and water diversion (disrupting natural flow regimes)","Recreation","Photography"],"Freshwater threats."),
    make_q(20,"The IUCN Red List classifies species by:",["Size only","Habitat only","*Extinction risk level (Least Concern to Critically Endangered to Extinct)","Color only"],"Conservation status."),
],
"u5_l5.3": [ # Conserving Biodiversity
    make_q(8,"In situ conservation means:",["Preservation in zoos","*Protecting species in their natural habitat (parks, reserves, wilderness areas)","Moving species to new locations","Laboratory preservation"],"In-habitat protection."),
    make_q(9,"Ex situ conservation means:",["Protecting natural habitats","*Preserving species outside their natural habitat (zoos, seed banks, aquariums)","Removing invasive species","Releasing captive animals"],"Off-site preservation."),
    make_q(10,"Wildlife corridors help conservation by:",["Blocking migration","*Connecting fragmented habitats so animals can move, find mates, and maintain gene flow","Increasing fragmentation","Reducing population"],"Connectivity."),
    make_q(11,"The Endangered Species Act (ESA) protects species by:",["Only listing them","*Making it illegal to harm listed species and requiring habitat protection plans","Removing them from habitats","Only funding zoos"],"Legal protection."),
    make_q(12,"CITES regulates:",["Domestic pet ownership","*International trade in endangered species and their products","Only fishing","Only hunting"],"Trade regulation."),
    make_q(13,"A biodiversity action plan typically includes:",["Only one strategy","*Habitat restoration, species monitoring, community engagement, and policy development","Only raising money","Only propaganda"],"Comprehensive planning."),
    make_q(14,"Seed banks like the Svalbard Global Seed Vault preserve:",["Animal DNA","*Seeds from crop species and wild plants as insurance against extinction","Fossils","Water samples"],"Genetic backup."),
    make_q(15,"Captive breeding programs aim to:",["Keep animals in cages permanently","*Breed endangered species for eventual reintroduction to the wild","Create pets","Only study behavior"],"Population recovery."),
    make_q(16,"Marine Protected Areas (MPAs) help conservation by:",["Blocking all boats","*Restricting fishing and development to allow ecosystem recovery","Draining the ocean","Only for tourism"],"Ocean conservation."),
    make_q(17,"Community-based conservation is effective because:",["Scientists know best","*Local communities understand and depend on their ecosystems, creating sustainable stewardship","Governments alone solve problems","Only in cities"],"Local engagement."),
    make_q(18,"Ecotourism benefits conservation by:",["Destroying habitats","*Providing economic incentive for local communities to protect natural areas","Only for wealthy nations","Increasing pollution"],"Economic incentive."),
    make_q(19,"Restoration ecology focuses on:",["Preventing all human use","*Rebuilding degraded ecosystems to recover biodiversity and function","Only planting trees","Only removing invasive species"],"Ecosystem repair."),
    make_q(20,"Which conservation approach is generally most cost-effective?",["Captive breeding","*Habitat protection and restoration (preventing loss is cheaper than recovering species)","Genetic engineering","Relocation only"],"Prevention over cure."),
],
"u5_l5.4": [ # Endangered Species
    make_q(8,"A species is considered 'endangered' when:",["It's common","*It faces a very high risk of extinction in the wild","It's in a zoo","It's abundant"],"IUCN definition."),
    make_q(9,"The difference between 'endangered' and 'threatened' is:",["No difference","*Threatened species may become endangered; endangered are at higher immediate risk","Endangered is less serious","Threatened are extinct"],"Risk gradient."),
    make_q(10,"The California condor was saved from extinction by:",["Doing nothing","*Captive breeding (population went from 22 to 500+)","Releasing predators","Building dams"],"Recovery success."),
    make_q(11,"Minimum viable population (MVP) is:",["Any number","*The smallest population size that can survive long-term (typically 500-5,000 individuals)","Only 2 individuals","Millions"],"Population threshold."),
    make_q(12,"Genetic bottleneck occurs when:",["Population grows","*Population drops drastically, reducing genetic diversity for future generations","Genes increase","New species form"],"Diversity loss event."),
    make_q(13,"Indicator species reveal:",["Nothing useful","*The health of an ecosystem (their decline signals environmental problems)","Only temperature","Only rainfall"],"Environmental health."),
    make_q(14,"Umbrella species like grizzly bears protect biodiversity because:",["They eat everything","*Protecting their large habitat range simultaneously protects many other species","They are cute","They are common"],"Broad habitat protection."),
    make_q(15,"The biggest challenge in species recovery programs is:",["Funding alone","*Habitat loss continues, genetic diversity may be too low, and human-wildlife conflict persists","Too many volunteers","Public interest"],"Multiple challenges."),
    make_q(16,"De-extinction (resurrecting extinct species) raises the concern of:",["Too many species","*Diverted resources from living endangered species and uncertain ecosystem reintegration","Zero cost","Being too easy"],"Ethical debate."),
    make_q(17,"The Endangered Species Act has prevented the extinction of approximately:",["0 species","10 species","*99%+ of listed species (very effective law)","All species everywhere"],"ESA effectiveness."),
    make_q(18,"Flagship species (like pandas) help conservation by:",["Being common","*Attracting public attention and funding that benefits entire ecosystems","Being small","Being easy to breed"],"Charismatic appeal."),
    make_q(19,"Population viability analysis (PVA) uses _____ to predict extinction risk.",["Only observation","*Computer models that simulate population dynamics under different scenarios","Only fossil data","Guesswork"],"Modeling extinction risk."),
    make_q(20,"Reintroduction of wolves to Yellowstone demonstrated:",["Wolves are harmful","*Trophic cascades — wolves changed elk behavior, benefiting rivers, vegetation, and other species","Wolves are unnecessary","No ecosystem effects"],"Trophic cascade."),
],
"u5_l5.5": [ # Global Conservation Efforts
    make_q(8,"The Convention on Biological Diversity (CBD) aims to:",["Only protect animals","*Conserve biodiversity, sustainably use components, and fairly share genetic resource benefits","Only fund research","Only restrict trade"],"Three CBD objectives."),
    make_q(9,"The '30 by 30' global conservation target means:",["30 species in 30 years","*Protecting 30% of land and ocean by 2030","30 countries by 2030","30 billion dollars"],"Area protection goal."),
    make_q(10,"IUCN stands for:",["International Union for Conservation of Nations","*International Union for Conservation of Nature","Intergovernmental Union for Conservation of Nature","International Unit for Conservation of Nature"],"Organizational name."),
    make_q(11,"The Paris Agreement relates to biodiversity by:",["It doesn't","*Addressing climate change, which is a major driver of biodiversity loss","Only economic issues","Only pollution"],"Climate-biodiversity link."),
    make_q(12,"Biodiversity loss affects human health through:",["No connection","*Reduced medical resources (many drugs come from nature), increased disease transmission, and reduced food security","Only allergies","Only animal attacks"],"Health connections."),
    make_q(13,"Sustainable development means:",["No development","*Meeting present needs without compromising future generations' ability to meet theirs","Maximum development","Only economic growth"],"Sustainability definition."),
    make_q(14,"Payment for Ecosystem Services (PES) works by:",["Free services","*Compensating landowners/communities who protect ecosystems that provide services (water filtration, carbon storage)","Taxing nature","Privatizing parks"],"Economic incentive."),
    make_q(15,"The Global Environment Facility (GEF) supports conservation by:",["Regulating trade","*Funding environmental projects in developing countries across 170+ nations","Banning deforestation","Only monitoring"],"International funding."),
    make_q(16,"Indigenous peoples manage approximately _____ of the world's remaining biodiversity.",["10%","25%","*~80% (their traditional lands hold the majority of remaining biodiversity)","50%"],"Indigenous stewardship."),
    make_q(17,"Citizen science contributes to conservation by:",["Replacing scientists","*Enabling thousands of volunteers to collect data (bird counts, species sightings, water quality)","Only funding","Only advocacy"],"Public participation."),
    make_q(18,"The United Nations Sustainable Development Goals include:",["No environmental goals","*Goal 14 (Life Below Water) and Goal 15 (Life on Land) directly address biodiversity","Only economic goals","Only education"],"SDG alignment."),
    make_q(19,"Why is international cooperation essential for biodiversity?",["It isn't","*Species migrate across borders, ecosystems span multiple countries, and threats are global (climate, trade)","Only for politics","Only for funding"],"Transboundary challenges."),
    make_q(20,"The greatest hope for global conservation is:",["Technology alone","*Integration of science, policy, local communities, education, and sustainable economic practices","Ignoring the problem","Only government action"],"Comprehensive approach."),
],
# ── U6: Chemistry of Life ──
"u6_l6.1": [ # Matter and Atomic Structure
    make_q(8,"An atom is the smallest unit of:",["A molecule","A cell","*An element that retains the element's properties","A compound"],"Fundamental unit."),
    make_q(9,"Electrons are located in:",["The nucleus","*Electron shells (energy levels) surrounding the nucleus","Protons","Neutrons"],"Electron location."),
    make_q(10,"The number of protons determines an element's:",["Mass","Charge","*Atomic number (and identity)","Color"],"Proton = identity."),
    make_q(11,"Isotopes differ in the number of:",["Protons","Electrons","*Neutrons","Shells"],"Same protons, different neutrons."),
    make_q(12,"A covalent bond forms when atoms:",["Transfer electrons","*Share electrons","Repel each other","Lose neutrons"],"Electron sharing."),
    make_q(13,"An ionic bond forms when atoms:",["Share electrons equally","*Transfer electrons (one gains, one loses), creating opposite charges that attract","Repel each other","Share neutrons"],"Electron transfer."),
    make_q(14,"The octet rule states that atoms tend to:",["Lose all electrons","*Bond until they have 8 electrons in their outer shell (achieving stability)","Have 8 protons","Form 8 bonds"],"Stability rule."),
    make_q(15,"Hydrogen bonds are important in biology because they:",["Are the strongest bonds","*Hold water molecules together and stabilize DNA's double helix structure","Don't exist in nature","Only form in labs"],"Biological importance."),
    make_q(16,"The three subatomic particles are:",["Atoms, molecules, ions","*Protons (positive), neutrons (neutral), electrons (negative)","Cells, tissues, organs","Solid, liquid, gas"],"Subatomic particles."),
    make_q(17,"Carbon is essential to life because it can:",["Only form 1 bond","*Form 4 covalent bonds (creating diverse, complex organic molecules)","Only dissolve in water","Only bond with oxygen"],"Carbon's versatility."),
    make_q(18,"The pH scale measures:",["Temperature","Pressure","*How acidic or basic a solution is (0-14, 7 is neutral)","Density"],"Acidity measure."),
    make_q(19,"A buffer in biology:",["Creates extreme pH","*Resists changes in pH, maintaining a stable environment for biochemical reactions","Only adds acid","Only adds base"],"pH stability."),
    make_q(20,"Van der Waals forces are:",["Strong covalent bonds","*Weak intermolecular attractions important for protein folding and gecko adhesion","Ionic bonds","Nuclear forces"],"Weak attractions."),
],
"u6_l6.2": [ # Chemical Reactions and Enzymes
    make_q(8,"Enzymes are biological catalysts made primarily of:",["Lipids","Carbohydrates","*Proteins (a few are RNA — ribozymes)","Nucleic acids only"],"Enzyme composition."),
    make_q(9,"The active site of an enzyme is:",["The entire protein","*The specific region where the substrate binds and the reaction is catalyzed","The product","The inhibitor"],"Binding region."),
    make_q(10,"The induced fit model describes how:",["Enzymes are rigid","*The enzyme slightly changes shape when the substrate binds, improving catalysis","Substrates dissolve","Products form randomly"],"Flexible binding."),
    make_q(11,"Enzymes speed up reactions by:",["Adding energy","*Lowering the activation energy needed for the reaction to proceed","Removing products","Creating substrates"],"Activation energy."),
    make_q(12,"Each enzyme is specific to its substrate because of:",["Size only","*The unique 3D shape of its active site (lock-and-key / induced fit specificity)","Color","Temperature"],"Shape specificity."),
    make_q(13,"Denaturation occurs when an enzyme:",["Works faster","*Loses its 3D shape (and function) due to extreme temperature, pH, or chemicals","Gains energy","Becomes stronger"],"Shape loss."),
    make_q(14,"Competitive inhibitors work by:",["Changing pH","*Binding to the active site, blocking the substrate from entering","Binding to a different site","Destroying the enzyme"],"Active site blocking."),
    make_q(15,"Noncompetitive (allosteric) inhibitors bind to:",["The active site","*A site other than the active site, changing the enzyme's shape","The substrate","The product"],"Allosteric site."),
    make_q(16,"Cofactors and coenzymes help enzymes by:",["Inhibiting them","*Assisting in catalysis (cofactors are inorganic ions; coenzymes are organic molecules like vitamins)","Destroying them","Replacing them"],"Enzyme helpers."),
    make_q(17,"Feedback inhibition regulates metabolism by:",["Always activating enzymes","*Product of a pathway inhibits an earlier enzyme, preventing overproduction","Destroying all enzymes","Only at high temperatures"],"Metabolic regulation."),
    make_q(18,"Endothermic reactions:",["Release energy","*Absorb energy from the surroundings (products have more energy than reactants)","Create enzymes","Destroy enzymes"],"Energy absorption."),
    make_q(19,"Exothermic reactions:",["Absorb energy","*Release energy to the surroundings (products have less energy than reactants)","Require enzymes always","Only occur in labs"],"Energy release."),
    make_q(20,"Activation energy is:",["Energy released by a reaction","*The minimum energy required to start a chemical reaction (enzymes lower this barrier)","The energy of products","The enzyme's energy"],"Energy barrier."),
],
"u6_l6.3": [ # Water and Its Solutions
    make_q(8,"Water is called the 'universal solvent' because:",["It dissolves everything","*Its polarity allows it to dissolve more substances than any other liquid","It's abundant","It's clear"],"Solvent properties."),
    make_q(9,"Cohesion in water is caused by:",["Ionic bonds","*Hydrogen bonds between water molecules (water sticking to water)","Covalent bonds only","Gravity"],"Water-water attraction."),
    make_q(10,"Adhesion is water's tendency to:",["Stick to itself","*Stick to other surfaces (like glass in a graduated cylinder — the meniscus)","Evaporate","Freeze"],"Water-surface attraction."),
    make_q(11,"Water's high specific heat means:",["It heats quickly","*It resists temperature changes (absorbs/releases large amounts of heat with small temperature change)","It freezes easily","It evaporates instantly"],"Temperature buffer."),
    make_q(12,"Surface tension in water results from:",["Gravity","Chemical additives","*Cohesive hydrogen bonds at the surface creating a 'film' (insects can walk on it)","Wind"],"Surface cohesion."),
    make_q(13,"Ice floats because:",["It's heavy","*Water expands when freezing; ice is less dense than liquid water (hydrogen bond geometry)","It has no bonds","It's warmer"],"Anomalous expansion."),
    make_q(14,"The biological significance of ice floating is:",["None","*Insulates water below, allowing aquatic life to survive winter; if ice sank, lakes would freeze solid","Only aesthetic","Makes ice fishing possible"],"Life under ice."),
    make_q(15,"A hydrophilic molecule:",["Repels water","*Is attracted to and dissolves in water (polar or charged molecules)","Is nonpolar","Is a lipid"],"Water-loving."),
    make_q(16,"A hydrophobic molecule:",["Dissolves in water","*Repels water and does not dissolve (nonpolar molecules like oils and fats)","Is charged","Is ionic"],"Water-fearing."),
    make_q(17,"Capillary action allows water to:",["Flow downhill only","*Move upward against gravity through narrow spaces (crucial for water transport in plants)","Dissolve minerals","Freeze faster"],"Upward movement."),
    make_q(18,"In a solution, the solvent is:",["The substance dissolved","*The substance doing the dissolving (water in most biological solutions)","The precipitate","The gas"],"Dissolving medium."),
    make_q(19,"Water's bent molecular shape creates:",["No polarity","*A polar molecule with partial positive (H) and partial negative (O) ends","A neutral molecule","A symmetric molecule"],"Molecular polarity."),
    make_q(20,"Evaporative cooling works because:",["Hot water sinks","*The highest-energy water molecules escape, lowering the temperature of the remaining liquid (sweating)","Water condenses","Water freezes"],"Cooling mechanism."),
],
"u6_l6.4": [ # Building Blocks of Life
    make_q(8,"The four major macromolecules in biology are:",["Minerals, water, vitamins, fiber","*Carbohydrates, lipids, proteins, and nucleic acids","Atoms, molecules, cells, tissues","Iron, calcium, sodium, potassium"],"Four macromolecules."),
    make_q(9,"Monomers join to form polymers through:",["Hydrolysis","*Dehydration synthesis (condensation) — removing water to form bonds","Evaporation","Denaturation"],"Building polymers."),
    make_q(10,"Carbohydrates are made of _____ monomers.",["Amino acids","Nucleotides","*Monosaccharides (simple sugars like glucose)","Fatty acids"],"Sugar subunits."),
    make_q(11,"Proteins are polymers of:",["Monosaccharides","*Amino acids (20 different types linked by peptide bonds)","Nucleotides","Glycerol"],"Amino acid chains."),
    make_q(12,"Lipids differ from other macromolecules because they:",["Are the largest","*Are NOT true polymers and are NOT water-soluble (hydrophobic)","Are always solid","Are made of amino acids"],"Unique category."),
    make_q(13,"Nucleic acids (DNA, RNA) are polymers of:",["Amino acids","Monosaccharides","*Nucleotides (sugar + phosphate + nitrogenous base)","Fatty acids"],"Nucleotide chains."),
    make_q(14,"The primary function of carbohydrates is:",["Storing genetic info","Building cell structure only","*Providing quick energy (glucose) and structural support (cellulose, chitin)","Catalyzing reactions"],"Energy and structure."),
    make_q(15,"Proteins function as:",["Only structural support","Only enzymes","*Enzymes, structural components, transport, immune defense, hormones, and much more","Only antibodies"],"Diverse functions."),
    make_q(16,"The function of lipids includes:",["Only energy storage","*Energy storage, cell membrane structure, insulation, and hormone production (steroids)","Only insulation","Only membrane"],"Multiple lipid roles."),
    make_q(17,"Hydrolysis breaks polymers by:",["Removing water","*Adding water to break bonds between monomers","Heating them","Dissolving them in acid"],"Water-splitting."),
    make_q(18,"Saturated fats have:",["Double bonds","*No double bonds between carbons in the fatty acid chain (solid at room temp — butter, lard)","Triple bonds","Ring structures"],"No double bonds."),
    make_q(19,"Unsaturated fats have:",["No double bonds","*One or more double bonds in the fatty acid chain (liquid at room temp — olive oil)","Only single bonds","Only triple bonds"],"Double bonds present."),
    make_q(20,"A protein's shape (and function) is determined by:",["Only temperature","*Its amino acid sequence, which dictates folding into specific 3D structures (primary → quaternary)","Only pH","Only size"],"Sequence determines shape."),
],
"u6_l6.5": [ # DNA and RNA
    make_q(8,"DNA stands for:",["Deoxyribose Nucleotide Acid","*Deoxyribonucleic Acid","Dynamic Nucleic Acid","Dual Nitrogen Acid"],"Full name."),
    make_q(9,"DNA's sugar is _____, while RNA's sugar is _____.",["Glucose, fructose","*Deoxyribose, ribose","Ribose, deoxyribose","Sucrose, maltose"],"Sugar difference."),
    make_q(10,"DNA base pairing rules: A pairs with _____, C pairs with _____.",["C, A","*T (thymine), G (guanine)","G, T","U, A"],"Complementary pairs."),
    make_q(11,"RNA uses _____ instead of thymine.",["Cytosine","Guanine","*Uracil","Adenine"],"RNA base difference."),
    make_q(12,"DNA is typically:",["Single-stranded","*Double-stranded (double helix)","Triple-stranded","Circular only"],"Structure."),
    make_q(13,"The three types of RNA involved in protein synthesis are:",["Only mRNA","*mRNA (messenger), tRNA (transfer), rRNA (ribosomal)","DNA, RNA, protein","ATP, ADP, AMP"],"RNA types."),
    make_q(14,"mRNA carries genetic instructions from:",["Ribosome to cytoplasm","*DNA in the nucleus to ribosomes in the cytoplasm","Cytoplasm to nucleus","tRNA to DNA"],"Message carrier."),
    make_q(15,"tRNA's function is to:",["Copy DNA","*Bring specific amino acids to the ribosome during translation","Destroy RNA","Store genetic info"],"Amino acid delivery."),
    make_q(16,"A codon is:",["A single base","*A three-nucleotide sequence on mRNA that codes for a specific amino acid","A protein","An enzyme"],"Triplet code."),
    make_q(17,"The central dogma of molecular biology is:",["Protein → DNA → RNA","*DNA → RNA → Protein (the flow of genetic information)","RNA → DNA → Protein","Protein → RNA → DNA"],"Information flow."),
    make_q(18,"Chargaff's rules state that:",["All bases are equal","*A = T and C = G (the amount of adenine equals thymine, cytosine equals guanine)","A = C always","T = G always"],"Base pair ratios."),
    make_q(19,"Watson and Crick are credited with:",["Discovering DNA","*Determining DNA's double helix structure (with data from Rosalind Franklin)","Creating RNA","Inventing PCR"],"Structure discovery."),
    make_q(20,"Mutations in DNA can be caused by:",["Only radiation","Only chemicals","*UV radiation, chemicals, errors in replication, and viral insertion","Only during cell division"],"Mutation sources."),
],
"u6_l6.6": [ # Biochemistry in Everyday Life
    make_q(8,"Vitamins function in the body primarily as:",["Energy sources","Building blocks","*Coenzymes that assist enzymes in biochemical reactions","Structural components"],"Vitamin role."),
    make_q(9,"Cholesterol is important because it:",["Is always harmful","*Is a component of cell membranes and a precursor for hormones (LDL vs. HDL matters)","Has no biological role","Only comes from food"],"Cholesterol function."),
    make_q(10,"Lactose intolerance results from:",["Allergy to milk protein","*Insufficient lactase enzyme to break down lactose (milk sugar)","Too much lactase","Excess calcium"],"Enzyme deficiency."),
    make_q(11,"Fermentation in food production (yogurt, bread, beer) relies on:",["Photosynthesis","*Anaerobic metabolism by microorganisms (yeast, bacteria)","Combustion","Hydrolysis only"],"Microbial metabolism."),
    make_q(12,"Antioxidants (vitamins C, E) protect cells by:",["Adding free radicals","*Neutralizing free radicals that damage DNA, proteins, and cell membranes","Increasing oxidation","Removing all oxygen"],"Cellular protection."),
    make_q(13,"Amino acid supplements are popular because:",["Everyone is deficient","*Some believe extra amino acids enhance muscle protein synthesis (though a balanced diet typically suffices)","They replace water","They cure diseases"],"Supplement context."),
    make_q(14,"Trans fats are harmful because they:",["Are unsaturated","*Raise LDL ('bad') cholesterol and lower HDL ('good') cholesterol, increasing heart disease risk","Are natural","Have no effect"],"Trans fat danger."),
    make_q(15,"Enzymes in laundry detergent (proteases, lipases) work by:",["Bleaching stains","*Breaking down protein and fat stains through biochemical catalysis","Dissolving fabric","Only removing dirt"],"Industrial enzymes."),
    make_q(16,"Blood glucose regulation involves:",["Only insulin","*Insulin (lowers glucose) and glucagon (raises glucose) working antagonistically","Only glucagon","Only diet"],"Hormonal balance."),
    make_q(17,"DNA fingerprinting is used in forensics because:",["Everyone has the same DNA","*Each person's DNA sequence has unique repetitive patterns (STRs) that identify individuals","DNA can't be compared","Only twins have unique DNA"],"Forensic identification."),
    make_q(18,"Bioluminescence in organisms like fireflies involves:",["Solar power","*Chemical reactions (luciferin + luciferase + ATP + O₂ → light)","Electricity","Reflection"],"Biological light."),
    make_q(19,"PCR (Polymerase Chain Reaction) is used to:",["Destroy DNA","*Amplify (make millions of copies of) specific DNA segments for analysis","Create new genes","Sequence proteins"],"DNA amplification."),
    make_q(20,"Understanding biochemistry is practical because it:",["Has no everyday application","*Explains nutrition, medicine, food science, forensics, environmental science, and biotech","Only matters in labs","Is purely theoretical"],"Real-world relevance."),
],
# ── U7: Cell Biology ──
"u7_l7.1": [ # Cell Structure and Function
    make_q(8,"The cell theory states that:",["Only plants have cells","*All living things are made of cells, cells are the basic unit of life, and new cells come from existing cells","Cells are made of atoms only","Only animals have cells"],"Three tenets."),
    make_q(9,"The nucleus contains:",["Ribosomes only","Mitochondria","*The cell's DNA organized into chromosomes","Cell membrane"],"Genetic control center."),
    make_q(10,"Mitochondria are called the 'powerhouse' because they:",["Produce proteins","*Generate ATP through cellular respiration","Store DNA","Digest waste"],"Energy production."),
    make_q(11,"The endoplasmic reticulum (ER) comes in two types:",["Large and small","*Rough ER (with ribosomes — protein processing) and Smooth ER (no ribosomes — lipid synthesis)","Inner and outer","Upper and lower"],"ER types."),
    make_q(12,"The Golgi apparatus functions as the cell's:",["Power plant","*Packaging and shipping center (modifies, sorts, and packages proteins for export)","Control center","Recycling center"],"Protein processing."),
    make_q(13,"Lysosomes contain _____ that break down waste and cellular debris.",["DNA","*Digestive enzymes","ATP","Hormones"],"Cellular digestion."),
    make_q(14,"Ribosomes are the site of:",["DNA replication","*Protein synthesis (translating mRNA into amino acid chains)","Cell division","Energy production"],"Protein factories."),
    make_q(15,"The cytoskeleton provides:",["Only energy","*Structural support, cell shape, and intracellular transport (microfilaments, microtubules, intermediate filaments)","Only protection","Only storage"],"Cell framework."),
    make_q(16,"Chloroplasts are found in _____ cells and perform _____.",["Animal, respiration","*Plant (and some protist), photosynthesis","All, digestion","Bacterial, reproduction"],"Plant organelle."),
    make_q(17,"The cell membrane is composed primarily of:",["Carbohydrates","*A phospholipid bilayer with embedded proteins","DNA","Only protein"],"Membrane structure."),
    make_q(18,"Vacuoles in plant cells are typically:",["Small and many","*Large and central (storing water, nutrients, waste — maintaining turgor pressure)","Absent","Only in animal cells"],"Plant vacuole."),
    make_q(19,"Centrioles are involved in:",["Protein synthesis","*Organizing spindle fibers during cell division (found in animal cells)","Photosynthesis","Digestion"],"Division organizer."),
    make_q(20,"Peroxisomes function to:",["Create DNA","*Break down fatty acids and detoxify harmful substances (including hydrogen peroxide)","Build proteins","Store sugar"],"Detoxification."),
],
"u7_l7.2": [ # Cell Discovery and Theory
    make_q(8,"Robert Hooke (1665) observed _____ and coined the term 'cell'.",["Living bacteria","*Cork cells (dead plant cells) under a microscope","Animal blood","Pond water"],"First cells named."),
    make_q(9,"Anton van Leeuwenhoek is famous for:",["Discovering DNA","*Being the first to observe living single-celled organisms ('animalcules') with his microscopes","Cell theory","Discovering mitochondria"],"Living cells observed."),
    make_q(10,"Matthias Schleiden concluded that:",["Only animals have cells","*All plants are made of cells","Cells come from nonliving matter","Only bacteria have cells"],"Plant cell discovery."),
    make_q(11,"Theodor Schwann extended Schleiden's work by stating:",["Only plants have cells","*All animals are also made of cells","Cells are not important","Only nerves have cells"],"Animal cell discovery."),
    make_q(12,"Rudolf Virchow contributed to cell theory by stating:",["Cells come from nothing","Cells come from chemicals","*All cells come from pre-existing cells (Omnis cellula e cellula)","Cells come from seeds"],"Cell origins."),
    make_q(13,"The cell theory was developed over approximately:",["1 year","10 years","*~200 years (1660s-1850s, through contributions of many scientists)","1,000 years"],"Gradual development."),
    make_q(14,"The electron microscope improved cell biology by:",["Using light better","*Revealing ultrastructure (organelles, membranes) with much higher magnification and resolution than light microscopy","Being cheaper","Being simpler"],"Technology advancement."),
    make_q(15,"The resolution limit of a light microscope is approximately:",["1 mm","*200 nm (0.2 micrometers)","1 nm","1 cm"],"Light microscopy limit."),
    make_q(16,"Transmission electron microscopy (TEM) uses _____ to view thin sections of cells.",["Light","*A beam of electrons passing through ultra-thin specimen slices","Sound waves","X-rays"],"TEM method."),
    make_q(17,"Why do cells need to remain small?",["For easy counting","*Surface area to volume ratio — smaller cells have more surface area relative to volume for efficient exchange","To fit under microscopes","For reproduction only"],"Size limitation."),
    make_q(18,"As a cell grows, its volume increases _____ than its surface area.",["Slower","At the same rate","*Faster (volume grows as cube, surface area as square)","It doesn't grow"],"SA:V ratio."),
    make_q(19,"Modern additions to cell theory include:",["No updates needed","*DNA is the hereditary material, cells contain identical DNA, and cells are the basic unit of metabolism","Cells are indestructible","Cells live forever"],"Updated theory."),
    make_q(20,"Cell fractionation allows scientists to:",["Observe living cells","*Separate and study individual organelles by spinning cell homogenate in a centrifuge","Stain cells","Count cells"],"Organelle isolation."),
],
"u7_l7.3": [ # Plasma Membrane
    make_q(8,"The fluid mosaic model describes the cell membrane as:",["Rigid and solid","*A fluid phospholipid bilayer with a mosaic of embedded and associated proteins","Only lipids","Only proteins"],"Membrane model."),
    make_q(9,"Phospholipids are amphipathic because they have:",["Two nonpolar ends","*A hydrophilic (polar) head and hydrophobic (nonpolar) fatty acid tails","Two polar ends","No distinct parts"],"Dual nature."),
    make_q(10,"Cholesterol in animal cell membranes:",["Makes them rigid","*Maintains fluidity — prevents excessive fluidity at high temps and excessive rigidity at low temps","Has no role","Increases permeability"],"Fluidity buffer."),
    make_q(11,"Membrane proteins that span the entire bilayer are called:",["Peripheral proteins","*Integral (transmembrane) proteins","Surface proteins","Matrix proteins"],"Spanning proteins."),
    make_q(12,"Glycoproteins on the cell surface function in:",["Energy storage","*Cell recognition, signaling, and immune identification (self vs. non-self)","DNA storage","ATP production"],"Cell identity."),
    make_q(13,"The cell membrane is described as 'selectively permeable' because:",["Nothing can pass","Everything can pass","*It allows some molecules through while blocking others based on size, charge, and polarity","It's broken"],"Selective passage."),
    make_q(14,"Small nonpolar molecules (O₂, CO₂) cross the membrane by:",["Active transport","Endocytosis","*Passing directly through the phospholipid bilayer (simple diffusion)","Exocytosis"],"Direct passage."),
    make_q(15,"Ions and large polar molecules cross the membrane through:",["The lipid bilayer directly","*Channel proteins or carrier proteins (facilitated diffusion or active transport)","Osmosis only","Exocytosis only"],"Protein-assisted transport."),
    make_q(16,"Aquaporins are channel proteins that allow rapid transport of:",["Glucose","Amino acids","*Water molecules","Sodium ions"],"Water channels."),
    make_q(17,"Signal transduction begins when a _____ binds to a membrane _____.",["Product, lipid","*Ligand (signal molecule), receptor protein","Gene, DNA","Enzyme, substrate"],"Signaling initiation."),
    make_q(18,"Membrane fluidity increases with:",["More saturated fatty acids","*More unsaturated fatty acids (double bonds create kinks, preventing tight packing)","More cholesterol only","Lower temperature only"],"Fluidity factors."),
    make_q(19,"The Na⁺/K⁺ ATPase pump is an example of:",["Passive transport","Diffusion","*Active transport (using ATP to pump 3 Na⁺ out and 2 K⁺ in against their gradients)","Osmosis"],"Active pump."),
    make_q(20,"Endocytosis is the process of:",["Releasing cell contents","*The cell membrane folding inward to bring large molecules or particles INTO the cell","Cell division","Protein synthesis"],"Cellular intake."),
],
"u7_l7.4": [ # Cellular Transport
    make_q(8,"Passive transport requires:",["ATP","Enzymes","*No energy — molecules move down their concentration gradient","Ribosomes"],"No energy needed."),
    make_q(9,"Active transport moves molecules:",["Down the gradient","With the flow","*Against their concentration gradient (from low to high concentration, requiring ATP)","Only water"],"Against gradient."),
    make_q(10,"Osmosis is the diffusion of _____ across a selectively permeable membrane.",["Solute","Glucose","*Water (from high water concentration to low water concentration)","Oxygen"],"Water movement."),
    make_q(11,"In a hypertonic solution, a cell will:",["Swell","Stay the same","*Shrink (crenate) as water moves OUT of the cell by osmosis","Divide"],"Water leaves cell."),
    make_q(12,"In a hypotonic solution, a cell will:",["Shrink","Stay the same","*Swell (and possibly lyse/burst in animal cells) as water moves INTO the cell","Divide"],"Water enters cell."),
    make_q(13,"An isotonic solution means:",["The cell swells","The cell shrinks","*Solute concentration is equal inside and outside; no net water movement","The cell divides"],"Equilibrium."),
    make_q(14,"Facilitated diffusion uses _____ but does NOT require _____.",["ATP, proteins","*Membrane proteins (channels or carriers), ATP (still passive — down the gradient)","Energy, proteins","Lipids, water"],"Assisted passive transport."),
    make_q(15,"The sodium-potassium pump moves:",["Na⁺ in, K⁺ out","*3 Na⁺ out and 2 K⁺ in per ATP hydrolyzed","Equal amounts both ways","Only Na⁺"],"Pump stoichiometry."),
    make_q(16,"Exocytosis is used by cells to:",["Absorb food","*Export/release large molecules (like proteins or neurotransmitters) by fusing vesicles with the cell membrane","Divide","Import DNA"],"Secretion."),
    make_q(17,"Phagocytosis ('cell eating') is a type of:",["Exocytosis","*Endocytosis where the cell engulfs large particles or even other cells","Passive transport","Osmosis"],"Particle engulfment."),
    make_q(18,"Pinocytosis ('cell drinking') involves:",["Eating solid food","*Taking in dissolved molecules and fluids through small vesicles at the cell surface","Releasing water","Active ion pumping"],"Fluid uptake."),
    make_q(19,"Plant cells in a hypotonic solution don't burst because of their:",["Chloroplasts","Mitochondria","*Rigid cell wall (provides turgor pressure that resists over-expansion)","Vacuole disappearing"],"Wall protection."),
    make_q(20,"Plasmolysis in plant cells occurs when:",["Water enters","*Water leaves the cell in a hypertonic environment, and the cell membrane pulls away from the cell wall","The cell divides","ATP is produced"],"Plant cell shrinkage."),
],
"u7_l7.5": [ # Structures and Organelles
    make_q(8,"The endomembrane system includes:",["Only the nucleus","*The nuclear envelope, ER, Golgi apparatus, lysosomes, and vesicles — connected by membrane flow","Only mitochondria","Only ribosomes"],"Connected system."),
    make_q(9,"Rough ER produces _____, while smooth ER synthesizes _____.",["Lipids, proteins","*Proteins (membrane-bound and secreted), lipids and detoxifies drugs","DNA, RNA","ATP, glucose"],"ER specialization."),
    make_q(10,"The Golgi apparatus receives products from the _____ side and ships from the _____ side.",["Trans, cis","*Cis (receiving), trans (shipping)","Top, bottom","Inside, outside"],"Golgi polarity."),
    make_q(11,"Mitochondria have their own DNA because they likely:",["Were created by the cell","*Were once free-living bacteria that were engulfed (endosymbiont theory)","Stole DNA from the nucleus","Don't actually have DNA"],"Endosymbiosis."),
    make_q(12,"The endosymbiotic theory is supported by the fact that mitochondria and chloroplasts:",["Are large","*Have double membranes, own circular DNA, own ribosomes, and replicate independently","Are in all organisms","Were created in labs"],"Theory evidence."),
    make_q(13,"The cytoplasm includes everything:",["Inside the nucleus","Outside the cell","*Between the cell membrane and the nuclear envelope (cytosol + organelles)","Only water"],"Cellular interior."),
    make_q(14,"Microtubules function in:",["Only cell shape","*Cell shape, intracellular transport, forming cilia/flagella, and spindle fibers during cell division","Only transport","Only division"],"Multiple roles."),
    make_q(15,"Cilia and flagella both contain:",["Random fibers","*A 9+2 arrangement of microtubules (nine doublets surrounding two central microtubules)","Only actin","No structure"],"9+2 arrangement."),
    make_q(16,"The nucleolus within the nucleus is responsible for:",["DNA replication","*Producing ribosomal RNA (rRNA) and assembling ribosome subunits","Protein folding","Cell division"],"Ribosome factory."),
    make_q(17,"Intermediate filaments provide:",["Movement","Energy","*Mechanical strength and resistance to tension (like ropes inside the cell)","Genetic information"],"Structural support."),
    make_q(18,"Plant cells have _____ that animal cells lack.",["Lysosomes","Centrioles","*Cell wall, chloroplasts, and large central vacuole","Ribosomes"],"Plant-unique structures."),
    make_q(19,"Motor proteins (kinesin, dynein) transport cargo along:",["Actin only","*Microtubules (like trains on tracks within the cell)","The cell membrane","DNA strands"],"Intracellular transport."),
    make_q(20,"The extracellular matrix (ECM) in animal cells provides:",["Nothing","*Structural support, signaling, and cell-to-cell communication (made of collagen, proteoglycans)","Only color","Only shape"],"External framework."),
],
"u7_l7.6": [ # Prokaryotic vs. Eukaryotic Cells
    make_q(8,"Prokaryotic cells lack:",["A cell membrane","Ribosomes","*A membrane-bound nucleus and membrane-bound organelles","DNA"],"Key absence."),
    make_q(9,"Eukaryotic cells are generally _____ than prokaryotic cells.",["Smaller","The same size","*Larger (10-100 μm vs. 1-10 μm for prokaryotes)","Invisible"],"Size difference."),
    make_q(10,"Prokaryotic DNA is typically:",["Linear chromosomes in a nucleus","*A single circular chromosome in the nucleoid region (no membrane)","Multiple linear chromosomes","Contained in organelles"],"Prokaryotic genome."),
    make_q(11,"Examples of prokaryotes include:",["Plants and animals","Fungi and protists","*Bacteria and archaea","Only viruses"],"Prokaryote kingdoms."),
    make_q(12,"Eukaryotic organisms include:",["Only animals","Only plants","*Animals, plants, fungi, and protists","Only bacteria"],"Eukaryote diversity."),
    make_q(13,"Prokaryotic ribosomes are _____ (size) compared to eukaryotic _____.",["80S, 70S","*70S, 80S (smaller prokaryotic ribosomes — targeted by certain antibiotics)","Equal size","90S, 60S"],"Ribosome sizes."),
    make_q(14,"Many prokaryotes have a capsule that helps them:",["Photosynthesize","*Resist phagocytosis, adhere to surfaces, and protect against desiccation","Store DNA","Produce ATP"],"Capsule functions."),
    make_q(15,"Pili (fimbriae) in prokaryotes are used for:",["Swimming","*Attachment to surfaces and conjugation (transfer of DNA between bacteria)","Photosynthesis","Cell division"],"Attachment structures."),
    make_q(16,"Flagella in prokaryotes vs. eukaryotes differ in:",["Nothing","*Structure: prokaryotic flagella rotate like propellers (flagellin protein); eukaryotic use 9+2 microtubule whip","Color only","Size only"],"Structural difference."),
    make_q(17,"Plasmids in prokaryotes are:",["Main chromosomes","*Small circular DNA molecules that can carry genes for antibiotic resistance and other traits","Ribosomes","Organelles"],"Extra DNA."),
    make_q(18,"Binary fission in prokaryotes is:",["Meiosis","*Asexual reproduction: DNA replicates, cell elongates, and divides into two identical daughter cells","Mitosis","Budding"],"Simple division."),
    make_q(19,"Archaea differ from bacteria in:",["Nothing","*Cell membrane chemistry (ether linkages vs. ester), cell wall composition, and many thrive in extreme environments","Being eukaryotic","Having a nucleus"],"Third domain."),
    make_q(20,"Antibiotics that target 70S ribosomes are effective against bacteria because:",["They also affect human cells","*Human cells have 80S ribosomes (different structure), so the antibiotic selectively inhibits only bacterial protein synthesis","They destroy all cells","They are not selective"],"Selective toxicity."),
],
"u7_l7.7": [ # Microscopy and Cell Imaging
    make_q(8,"Light microscopy uses _____ to illuminate specimens.",["Electrons","*Visible light (with glass lenses to magnify)","X-rays","Sound waves"],"Light source."),
    make_q(9,"The maximum useful magnification of a light microscope is approximately:",["100×","*~1,000-1,500×","10,000×","100,000×"],"Practical limit."),
    make_q(10,"Scanning electron microscopy (SEM) produces:",["Internal cell views","*3D images of specimen surfaces (detailed external topography)","Thin section views","Living cell videos"],"Surface imaging."),
    make_q(11,"Transmission electron microscopy (TEM) produces:",["Surface images","*2D images of thin internal sections (revealing organelle ultrastructure)","3D surface views","Only living cells"],"Internal imaging."),
    make_q(12,"Fluorescence microscopy uses:",["Regular light","*Fluorescent dyes or proteins (like GFP) that emit light when excited — allowing specific molecule tracking","Electron beams","Sound waves"],"Molecular tracking."),
    make_q(13,"GFP (Green Fluorescent Protein) is used to:",["Kill cells","*Tag specific proteins so their location and movement can be tracked in living cells","Stain DNA only","Fix specimens"],"Live cell tracking."),
    make_q(14,"The difference between magnification and resolution is:",["They're the same","*Magnification enlarges the image; resolution is the ability to distinguish two close objects as separate","Resolution makes things bigger","Magnification clarifies"],"Key distinction."),
    make_q(15,"Phase contrast microscopy is useful for:",["Dead specimens only","*Viewing living cells without staining (enhances contrast of transparent specimens)","Only stained cells","Only with electrons"],"Living cell observation."),
    make_q(16,"Confocal microscopy improves images by:",["Using wider beams","*Using a pinhole to eliminate out-of-focus light, creating optical sections for 3D reconstruction","Using electrons","Using X-rays"],"Optical sectioning."),
    make_q(17,"Cell staining (like Gram staining in microbiology) helps by:",["Killing all cells","*Adding contrast to visualize structures and differentiate cell types (Gram+ vs. Gram−)","Making cells larger","Replacing microscopes"],"Contrast enhancement."),
    make_q(18,"Cryo-electron microscopy (cryo-EM) is revolutionary because it:",["Uses heat","*Preserves specimens in near-native state by rapid freezing, revealing molecular structures without crystallization","Uses sound","Is cheap"],"Near-native imaging."),
    make_q(19,"The unit of measurement for most cells is:",["Meters","Centimeters","*Micrometers (μm, 10⁻⁶ m)","Nanometers"],"Cell-scale measurement."),
    make_q(20,"Advances in microscopy have been essential to biology because:",["They replaced experiments","*They revealed cells, organelles, molecular structures, and dynamic processes invisible to the naked eye","They are decorative","They only confirm known facts"],"Technology drives discovery."),
],
# ── U8: Energy & Metabolism ──
"u8_l8.1": [ # How Organisms Obtain Energy
    make_q(8,"Autotrophs obtain energy by:",["Eating other organisms","*Converting inorganic molecules to organic molecules (photosynthesis or chemosynthesis)","Only from ATP","Absorbing organic matter"],"Self-feeders."),
    make_q(9,"Heterotrophs obtain energy by:",["Making their own food","*Consuming other organisms (herbivores, carnivores, omnivores, decomposers)","Only from sunlight","Chemosynthesis"],"Other-feeders."),
    make_q(10,"Chemosynthesis is performed by organisms near:",["Sunny meadows","*Deep-sea hydrothermal vents (using chemical energy from H₂S instead of sunlight)","Freshwater lakes only","Arctic tundra"],"Chemical energy source."),
    make_q(11,"In a food chain, energy flows from:",["Consumers to producers","*Producers → primary consumers → secondary consumers → tertiary consumers","Decomposers to producers only","All directions equally"],"Energy direction."),
    make_q(12,"Only about _____ of energy is transferred to the next trophic level.",["1%","50%","*10% (the 10% rule)","90%"],"Energy transfer efficiency."),
    make_q(13,"The ultimate source of energy for most ecosystems is:",["Geothermal heat","Chemical reactions","*The sun","Wind"],"Solar energy."),
],
"u8_l8.2": [ # Chemical Energy and ATP
    make_q(8,"ATP stands for:",["Adenine Triphosphate","*Adenosine Triphosphate","Amino Triphosphate","Acid Triphosphate"],"Full name."),
    make_q(9,"ATP stores energy in its:",["Adenine base","Ribose sugar","*High-energy phosphate bonds (especially the terminal bond)","Nitrogen groups"],"Energy storage."),
    make_q(10,"When ATP loses a phosphate group, it becomes:",["AMP","*ADP (adenosine diphosphate) + inorganic phosphate + released energy","More ATP","GDP"],"Hydrolysis product."),
    make_q(11,"ATP is regenerated from ADP + Pᵢ by:",["Hydrolysis","Photolysis","*Cellular respiration and photophosphorylation (adding phosphate back using energy)","Spontaneous reaction"],"ATP recycling."),
    make_q(12,"A human body recycles approximately _____ of ATP per day.",["1 gram","100 grams","*~40 kg (about body weight — constant recycling of the same molecules)","1,000 kg"],"Enormous turnover."),
    make_q(13,"ATP is called the 'energy currency' of cells because:",["It's expensive","*It provides immediately usable energy for virtually all cellular work (mechanical, transport, chemical)","It's stored in banks","It's rare"],"Universal energy."),
],
"u8_l8.3": [ # Photosynthesis
    make_q(8,"The overall equation for photosynthesis is:",["C₆H₁₂O₆ + O₂ → CO₂ + H₂O","*6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂","CO₂ + H₂O → O₂","Only CO₂ → O₂"],"Net equation."),
    make_q(9,"The light-dependent reactions occur in the:",["Stroma","*Thylakoid membranes of chloroplasts","Cytoplasm","Mitochondria"],"Thylakoid location."),
    make_q(10,"The Calvin cycle (light-independent reactions) occurs in the:",["Thylakoid membrane","*Stroma of chloroplasts","Cytoplasm","Nucleus"],"Stroma location."),
    make_q(11,"Chlorophyll absorbs _____ light most effectively and reflects _____.",["Green, red","*Red and blue, green (which is why plants appear green)","All colors equally","Only infrared"],"Light absorption."),
    make_q(12,"The oxygen released during photosynthesis comes from:",["CO₂","*Water (H₂O split during the light reactions)","Glucose","ATP"],"Photolysis of water."),
    make_q(13,"The Calvin cycle uses CO₂ to build:",["ATP","Water","*G3P (glyceraldehyde-3-phosphate), which is used to make glucose","Oxygen"],"Carbon fixation product."),
    make_q(14,"Photosystems I and II work together to:",["Only absorb light","*Convert light energy to chemical energy (ATP and NADPH via the electron transport chain and photolysis)","Only split water","Only fix carbon"],"Light reactions."),
    make_q(15,"CAM and C4 plants are adapted to:",["Cold environments","*Hot, dry environments (minimizing water loss while still fixing CO₂ efficiently)","Aquatic environments","Shady environments"],"Drought adaptations."),
    make_q(16,"The rate of photosynthesis is affected by:",["Only light","Only CO₂","*Light intensity, CO₂ concentration, temperature, and water availability","Only temperature"],"Multiple factors."),
    make_q(17,"NADPH produced in the light reactions:",["Is a waste product","*Carries high-energy electrons to the Calvin cycle for carbon fixation","Leaves the cell","Destroys glucose"],"Electron carrier."),
    make_q(18,"Photosynthesis and cellular respiration are _____ processes.",["Identical","Unrelated","*Complementary and essentially reverse (photosynthesis stores energy; respiration releases it)","Random"],"Complementary cycles."),
    make_q(19,"Stomata in leaves regulate photosynthesis by:",["Absorbing light","*Controlling gas exchange (CO₂ in, O₂ out) and water loss (transpiration)","Producing chlorophyll","Storing glucose"],"Gas exchange."),
    make_q(20,"Without photosynthesis, life on Earth would:",["Be unchanged","*Collapse — no O₂ production, no food base for almost all food webs","Improve","Only affect plants"],"Foundational process."),
],
"u8_l8.4": [ # Cellular Respiration
    make_q(8,"The overall equation for aerobic cellular respiration is:",["6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂","*C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ~36-38 ATP","C₆H₁₂O₆ → CO₂ + ATP only","O₂ → CO₂ + H₂O"],"Net equation."),
    make_q(9,"The three stages of cellular respiration are:",["Only glycolysis","*Glycolysis, Krebs cycle (citric acid cycle), and the electron transport chain/oxidative phosphorylation","Only the Krebs cycle","Photolysis, Calvin cycle, fermentation"],"Three stages."),
    make_q(10,"Glycolysis occurs in the:",["Mitochondria","*Cytoplasm (it doesn't require oxygen or organelles)","Nucleus","Chloroplast"],"Cytoplasmic location."),
    make_q(11,"The Krebs cycle occurs in the:",["Cytoplasm","*Mitochondrial matrix","Nucleus","Cell membrane"],"Matrix location."),
    make_q(12,"The electron transport chain is located in the:",["Cytoplasm","Matrix","*Inner mitochondrial membrane (cristae)","Outer membrane"],"Cristae location."),
    make_q(13,"Glycolysis produces a net gain of _____ ATP per glucose molecule.",["0","1","*2","36"],"Glycolysis ATP yield."),
    make_q(14,"The total ATP yield from one glucose molecule (aerobic respiration) is approximately:",["2","4","*36-38 (most from the electron transport chain)","100"],"Total yield."),
    make_q(15,"NAD⁺ and FAD are important in respiration because they:",["Provide oxygen","*Accept and carry high-energy electrons (as NADH and FADH₂) to the electron transport chain","Are enzymes","Are substrates"],"Electron carriers."),
    make_q(16,"Oxygen's role in cellular respiration is as the:",["Initial substrate","Energy source","*Final electron acceptor in the electron transport chain (forming water)","Catalyst"],"Terminal acceptor."),
    make_q(17,"Pyruvate from glycolysis enters the mitochondria and is converted to:",["Glucose","ATP directly","*Acetyl-CoA (releasing CO₂) before entering the Krebs cycle","Water"],"Pyruvate oxidation."),
    make_q(18,"Chemiosmosis drives ATP synthesis by:",["Direct chemistry","*Using the H⁺ gradient across the inner membrane to power ATP synthase (like a turbine)","Breaking glucose","Splitting water"],"Proton gradient."),
    make_q(19,"ATP synthase is sometimes called a 'molecular motor' because it:",["Runs on electricity","*Physically rotates as H⁺ ions flow through it, mechanically catalyzing ATP synthesis","Burns fuel","Only works once"],"Rotary enzyme."),
    make_q(20,"Without oxygen, cells can still get energy through:",["Full respiration","*Fermentation (anaerobic glycolysis — producing only 2 ATP per glucose)","None","Photosynthesis"],"Anaerobic fallback."),
],
"u8_l8.5": [ # Fermentation
    make_q(8,"Fermentation occurs when _____ is NOT available.",["Glucose","Water","*Oxygen (it's an anaerobic process)","Light"],"Anaerobic condition."),
    make_q(9,"The two main types of fermentation are:",["Aerobic and anaerobic","*Lactic acid fermentation and alcoholic (ethanol) fermentation","Photosynthesis and respiration","Glycolysis and Krebs"],"Two pathways."),
    make_q(10,"Lactic acid fermentation occurs in:",["Only bacteria","Only yeast","*Human muscle cells during intense exercise AND certain bacteria (yogurt, cheese production)","Only plants"],"Where it occurs."),
    make_q(11,"Alcoholic fermentation produces:",["Lactic acid","*Ethanol + CO₂ (used in brewing beer, making wine, and baking bread — CO₂ makes bread rise)","Glucose","Oxygen"],"Products."),
    make_q(12,"Fermentation produces only _____ ATP per glucose (vs. ~36-38 for aerobic respiration).",["0","*2","10","20"],"Low yield."),
    make_q(13,"The purpose of fermentation is NOT to produce ATP directly but to:",["Create oxygen","*Regenerate NAD⁺ so glycolysis can continue producing the 2 ATP anaerobically","Break down glucose completely","Produce CO₂"],"NAD⁺ recycling."),
    make_q(14,"Muscle soreness after intense exercise was traditionally attributed to:",["Oxygen buildup","*Lactic acid accumulation (though current research suggests it's more complex — microtrauma, inflammation)","Sugar depletion","Water loss"],"Exercise physiology."),
    make_q(15,"Yeast is used in baking because:",["It adds flavor only","*Alcoholic fermentation produces CO₂ gas that causes dough to rise (ethanol evaporates during baking)","It adds color","It preserves bread"],"Leavening agent."),
    make_q(16,"In winemaking, yeast ferments grape sugars until:",["Oxygen appears","*Alcohol concentration reaches ~12-16% (toxic to yeast, stopping fermentation)","All sugar is consumed always","Temperature drops"],"Natural limit."),
    make_q(17,"Obligate anaerobes are organisms that:",["Need oxygen","Can use oxygen or not","*Cannot survive in the presence of oxygen (it's toxic to them)","Only use fermentation sometimes"],"Strict anaerobes."),
    make_q(18,"Facultative anaerobes like yeast can:",["Only ferment","*Switch between aerobic respiration (when O₂ is present) and fermentation (when it's not)","Only respire aerobically","Not survive without O₂"],"Metabolic flexibility."),
    make_q(19,"Industrial fermentation is used to produce:",["Only bread","Only beer","*Bread, beer, wine, yogurt, cheese, biofuels, antibiotics, and many other products","Nothing commercially"],"Widespread industrial use."),
    make_q(20,"Compared to aerobic respiration, fermentation is _____ efficient.",["More","Equally","*Much less (2 vs. ~36-38 ATP per glucose — only ~5% as efficient)","Not comparable"],"Efficiency comparison."),
],
"u8_l8.6": [ # Energy Flow in Living Systems
    make_q(8,"Energy in ecosystems flows in _____ direction(s), while nutrients _____.",["Both cycle","*One direction (producers → consumers → decomposers), while nutrients cycle and are recycled","Random, one direction","Neither flows"],"Flow vs. cycle."),
    make_q(9,"A food web differs from a food chain because it:",["Is simpler","*Shows multiple interconnected feeding relationships (more realistic than a single chain)","Has fewer organisms","Only includes plants"],"Complexity."),
    make_q(10,"Trophic levels represent:",["Species names","*Feeding positions in a food chain (producer = 1st, primary consumer = 2nd, etc.)","Habitat types","Population sizes"],"Feeding positions."),
    make_q(11,"An ecological pyramid of energy shows that:",["Energy increases at higher levels","*Energy decreases at each trophic level (10% rule — only ~10% transferred upward)","Energy is equal at all levels","Energy only exists at bottom"],"Energy loss."),
    make_q(12,"Most energy at each trophic level is lost as:",["Light","Sound","*Heat (through metabolic processes — cellular respiration)","Stored as fat"],"Heat loss."),
    make_q(13,"Decomposers are essential because they:",["Only eat dead organisms","*Break down dead matter and waste, recycling nutrients back to the soil for producers","Produce oxygen","Are at the top of food chains"],"Nutrient recycling."),
    make_q(14,"Primary productivity is:",["Consumer growth rate","*The rate at which producers convert solar energy to chemical energy (biomass) through photosynthesis","Decomposition rate","Respiration rate"],"Producer output."),
    make_q(15,"Gross primary productivity minus respiration by producers equals:",["Total energy","*Net primary productivity (NPP — the energy available to consumers)","Zero","Gross secondary productivity"],"Available energy."),
    make_q(16,"Biological magnification refers to toxins:",["Decreasing in food chains","*Increasing in concentration at higher trophic levels (e.g., DDT, mercury in top predators)","Being eliminated","Only in water"],"Toxin concentration."),
    make_q(17,"The most productive ecosystems on Earth include:",["Deserts","Tundra","*Tropical rainforests, estuaries, and coral reefs (high primary productivity)","Polar ice caps"],"Most productive biomes."),
    make_q(18,"Transpiration connects energy flow to the water cycle by:",["Cooling plants only","*Plants absorb water for photosynthesis and release water vapor, linking energy capture to water cycling","Flooding ecosystems","Only in rainforests"],"Water-energy link."),
    make_q(19,"Detritivores differ from decomposers in that they:",["Are the same","*Physically break down dead matter by eating it (earthworms, millipedes) before decomposers (fungi, bacteria) finish chemically","Don't eat dead matter","Are only bacteria"],"Physical vs. chemical breakdown."),
    make_q(20,"Understanding energy flow helps predict:",["Nothing practical","*How ecosystem disruptions (species loss, pollution) affect food webs and how much food an ecosystem can produce","Only weather","Only temperature"],"Practical application."),
],
}

with open(PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

count = 0
for key, extra_qs in EXTRA.items():
    if key in data:
        existing = data[key].get("quiz_questions", [])
        start_num = len(existing) + 1
        for i, q in enumerate(extra_qs):
            q["question_number"] = start_num + i
        data[key]["quiz_questions"] = existing + extra_qs
        count += 1

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"✅ Biology U5-U8: expanded {count} lessons to 20 questions each")
