#!/usr/bin/env python3
"""Add 13 more quiz questions to Biology Units 9-12 (25 lessons)."""
import json, os

PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "content_data", "biology_lessons.json")

def make_q(num, text, opts, explanation):
    options = []
    for o in opts:
        correct = o.startswith("*")
        options.append({"text": o.lstrip("*"), "is_correct": correct, "data_i18n": None})
    return {"question_number": num, "question_text": text, "attempted": 2,
            "data_i18n": None, "options": options, "explanation": explanation}

EXTRA = {
# ── U9: Cell Division ──
"u9_l9.1": [ # Cellular Reproduction
    make_q(8,"The two main purposes of cell division are:",["Only reproduction","*Growth/repair (mitosis) and sexual reproduction (meiosis)","Only growth","Only repair"],"Dual purpose."),
    make_q(9,"During interphase, the cell:",["Is dividing","*Grows, replicates DNA, and prepares for division (G1, S, G2 phases)","Is dormant","Is dying"],"Pre-division prep."),
    make_q(10,"DNA replication occurs during the _____ phase of interphase.",["G1","*S (synthesis)","G2","M"],"S phase."),
    make_q(11,"Chromatin condenses into visible chromosomes at the start of:",["Interphase","*Prophase (beginning of mitosis)","Cytokinesis","G1 phase"],"Condensation timing."),
    make_q(12,"Sister chromatids are:",["Different chromosomes","*Identical copies of a chromosome joined at the centromere (formed during S phase)","Unrelated DNA","Paternal and maternal copies"],"Identical copies."),
    make_q(13,"Cytokinesis is the division of:",["The nucleus","DNA","*The cytoplasm (splitting one cell into two daughter cells)","Chromosomes"],"Cytoplasm division."),
    make_q(14,"In animal cells, cytokinesis occurs by:",["Cell plate formation","*Cleavage furrow (the cell membrane pinches inward)","Budding","Fragmentation"],"Animal cell division."),
    make_q(15,"In plant cells, cytokinesis occurs by:",["Cleavage furrow","*Cell plate formation (vesicles fuse to build a new wall between daughter cells)","Pinching","Budding"],"Plant cell division."),
    make_q(16,"Organisms reproduce asexually through:",["Only meiosis","*Binary fission, budding, fragmentation, or mitosis (producing genetically identical offspring)","Only sexual means","Random assembly"],"Asexual methods."),
    make_q(17,"Asexual reproduction produces offspring that are:",["Genetically diverse","*Genetically identical to the parent (clones)","Half the parent's DNA","Always different"],"Clonal offspring."),
    make_q(18,"Sexual reproduction requires:",["One parent only","*Two parents (typically) contributing gametes via meiosis, resulting in genetic variation","No cell division","Only mitosis"],"Two-parent reproduction."),
    make_q(19,"The advantage of sexual reproduction over asexual is:",["Speed","*Genetic variation (increasing adaptability to changing environments)","Fewer offspring","No energy cost"],"Variation advantage."),
    make_q(20,"Prokaryotes reproduce primarily by:",["Mitosis","Meiosis","*Binary fission (simple division with no mitotic spindle)","Budding only"],"Prokaryotic reproduction."),
],
"u9_l9.2": [ # Mitosis
    make_q(8,"Mitosis produces _____ daughter cells that are _____ to the parent cell.",["Four, different","*Two, genetically identical","Two, genetically different","Four, identical"],"Mitosis outcome."),
    make_q(9,"The correct order of mitosis phases is:",["Anaphase, Prophase, Metaphase, Telophase","*Prophase, Metaphase, Anaphase, Telophase (PMAT)","Telophase, Metaphase, Anaphase, Prophase","Metaphase, Prophase, Telophase, Anaphase"],"PMAT order."),
    make_q(10,"During prophase:",["Chromosomes line up","*Chromatin condenses, nuclear envelope breaks down, spindle fibers form","Cells separate","DNA replicates"],"Prophase events."),
    make_q(11,"During metaphase, chromosomes:",["Separate","Condense","*Align at the cell's equator (metaphase plate)","Replicate"],"Chromosome alignment."),
    make_q(12,"During anaphase, sister chromatids:",["Align","Condense","*Are pulled apart to opposite poles by shortening spindle fibers","Replicate"],"Chromatid separation."),
    make_q(13,"During telophase:",["Chromosomes condense","Chromatids separate","*Nuclear envelopes reform around each set of chromosomes, chromosomes decondense","DNA replicates"],"Nuclear reformation."),
    make_q(14,"The mitotic spindle is made of:",["Actin filaments","*Microtubules (organized by centrioles/centrosomes)","Intermediate filaments","Myosin"],"Spindle composition."),
    make_q(15,"Centromeres are important because they:",["Store DNA","*Hold sister chromatids together and are the attachment point for spindle fibers (kinetochore)","Produce energy","Create new chromosomes"],"Attachment point."),
    make_q(16,"Humans have _____ chromosomes after mitosis (same as parent cell).",["23","*46 (diploid — mitosis maintains chromosome number)","92","12"],"Chromosome maintenance."),
    make_q(17,"Mitosis is essential for:",["Gamete production","*Growth, tissue repair, and maintenance of multicellular organisms","Only embryonic development","Only wound healing"],"Body maintenance."),
    make_q(18,"Errors in mitosis can lead to:",["Improved function","*Abnormal chromosome numbers, cell death, or potentially cancer","No consequences","Stronger cells"],"Division errors."),
    make_q(19,"Colchicine disrupts mitosis by:",["Breaking DNA","*Preventing spindle fiber formation (blocking microtubule assembly)","Accelerating division","Replicating DNA"],"Spindle poison."),
    make_q(20,"A cell in G0 phase is:",["Actively dividing","*Not dividing (may re-enter the cycle or remain permanently non-dividing, like neurons)","Dead","In mitosis"],"Quiescent state."),
],
"u9_l9.3": [ # Meiosis and Sexual Reproduction
    make_q(8,"Meiosis produces _____ daughter cells that are _____ to each other.",["Two, identical","*Four, genetically unique (haploid)","Two, different","Four, identical"],"Meiosis outcome."),
    make_q(9,"Meiosis reduces chromosome number from _____ to _____.",["Haploid to diploid","*Diploid (2n) to haploid (n)","Diploid to diploid","Haploid to haploid"],"Reduction division."),
    make_q(10,"Crossing over occurs during:",["Mitosis","*Prophase I of meiosis (homologous chromosomes exchange segments)","Metaphase II","Anaphase I"],"Genetic recombination."),
    make_q(11,"Independent assortment means:",["Chromosomes always segregate the same way","*Homologous chromosome pairs orient randomly at metaphase I, creating diverse gamete combinations","Genes are linked","Chromosomes don't separate"],"Random orientation."),
    make_q(12,"The combination of crossing over and independent assortment produces:",["Identical gametes","*Enormous genetic variation (2²³ combinations from independent assortment alone in humans, plus crossing over)","Only two types of gametes","No variation"],"Variation sources."),
    make_q(13,"Homologous chromosomes are:",["Identical copies","*Matching pairs (one from each parent) with the same genes but potentially different alleles","Sister chromatids","Only in males"],"Chromosome pairs."),
    make_q(14,"In meiosis I, _____ separate; in meiosis II, _____ separate.",["Sister chromatids, homologs","*Homologous chromosomes, sister chromatids","Both separate homologs","Both separate chromatids"],"Two-stage separation."),
    make_q(15,"Nondisjunction is:",["Normal chromosome separation","*Failure of chromosomes to separate properly, resulting in abnormal chromosome numbers (aneuploidy)","Crossing over","Independent assortment"],"Separation failure."),
    make_q(16,"Down syndrome (trisomy 21) results from:",["Crossing over","Deletion","*Nondisjunction producing three copies of chromosome 21","Translocation only"],"Extra chromosome."),
    make_q(17,"Gametes in humans have _____ chromosomes.",["46","*23 (haploid — half the diploid number)","92","12"],"Haploid number."),
    make_q(18,"Fertilization restores the _____ number.",["Haploid","*Diploid (23 from sperm + 23 from egg = 46 in zygote)","Triploid","Tetraploid"],"Chromosome restoration."),
    make_q(19,"Oogenesis produces _____ functional egg(s) from each primary oocyte.",["Four","Two","*One (plus 2-3 polar bodies that degenerate)","Eight"],"Egg production."),
    make_q(20,"Spermatogenesis produces _____ functional sperm from each primary spermatocyte.",["One","Two","*Four","Eight"],"Sperm production."),
],
"u9_l9.4": [ # Cell Cycle and Cancer
    make_q(8,"The cell cycle is regulated by:",["Only DNA","*Cyclins and cyclin-dependent kinases (CDKs) at checkpoints","Only enzymes","Only growth factors"],"Molecular regulators."),
    make_q(9,"Cell cycle checkpoints ensure:",["Faster division","*DNA is intact, replicated correctly, and everything is ready before proceeding to the next phase","Cells never divide","Only large cells divide"],"Quality control."),
    make_q(10,"The G1 checkpoint checks for:",["Spindle attachment","*Cell size, nutrients, growth factors, and DNA integrity before entering S phase","Chromosome alignment","Complete cytokinesis"],"G1 checkpoint function."),
    make_q(11,"Proto-oncogenes normally:",["Cause cancer","*Promote normal cell growth and division (when mutated they become oncogenes)","Suppress tumors","Kill cells"],"Normal growth genes."),
    make_q(12,"Tumor suppressor genes normally:",["Promote growth","*Slow cell division or trigger apoptosis (e.g., p53, Rb — 'brakes' on the cell cycle)","Cause mutations","Are unnecessary"],"Growth brakes."),
    make_q(13,"Cancer results from:",["A single mutation always","*Accumulated mutations in proto-oncogenes AND tumor suppressors (multi-hit hypothesis — typically 3-7 mutations)","Only viral infection","Only chemicals"],"Multiple mutations."),
    make_q(14,"p53 is called the 'guardian of the genome' because it:",["Replicates DNA","*Detects DNA damage and either halts the cycle for repair or triggers apoptosis (cell death)","Promotes division","Only exists in cancer"],"Genome guardian."),
    make_q(15,"Apoptosis is:",["Uncontrolled cell death","*Programmed cell death (controlled, orderly self-destruction — important for removing damaged cells)","Cell growth","Cell division"],"Programmed death."),
    make_q(16,"A benign tumor:",["Spreads everywhere","*Remains localized and does not invade surrounding tissue (generally not life-threatening)","Is always harmless","Doesn't exist"],"Non-invasive growth."),
    make_q(17,"A malignant tumor:",["Stays in place","*Invades surrounding tissues and can metastasize (spread to distant parts of the body via blood/lymph)","Is always benign","Cannot be treated"],"Invasive cancer."),
    make_q(18,"Metastasis is:",["Tumor shrinkage","*The spread of cancer cells from the original site to other parts of the body","Apoptosis","Cell repair"],"Cancer spreading."),
    make_q(19,"Carcinogens are agents that:",["Cure cancer","*Cause cancer by damaging DNA (UV radiation, tobacco smoke, certain chemicals, some viruses)","Prevent mutations","Strengthen cells"],"Cancer-causing agents."),
    make_q(20,"Cancer treatments like chemotherapy target:",["Only cancer cells perfectly","*Rapidly dividing cells (cancer cells divide rapidly, but healthy dividing cells are also affected — causing side effects)","Only healthy cells","Non-dividing cells"],"Treatment mechanism."),
],
"u9_l9.5": [ # Stem Cells and Regenerative Medicine
    make_q(8,"Stem cells are unique because they can:",["Only divide once","*Self-renew AND differentiate into specialized cell types","Only become one cell type","Never divide"],"Dual ability."),
    make_q(9,"Totipotent stem cells can become:",["Only blood cells","Only nerve cells","*ANY cell type including placenta (only in very early embryo — first few divisions)","Only muscle cells"],"Maximum potential."),
    make_q(10,"Pluripotent stem cells can become:",["Only one type","*Almost any cell type in the body (but not placenta — embryonic stem cells)","Only blood cells","No specialized cells"],"Broad potential."),
    make_q(11,"Adult (somatic) stem cells are:",["Totipotent","*Multipotent (can become several related cell types — e.g., bone marrow stem cells → blood cell types)","Pluripotent","Cannot differentiate"],"Limited potential."),
    make_q(12,"Induced pluripotent stem cells (iPSCs) are created by:",["Cloning embryos","*Reprogramming adult cells back to a stem cell-like state using specific factors (Yamanaka factors)","Extracting from embryos","Natural mutation"],"Reprogramming breakthrough."),
    make_q(13,"Bone marrow transplants work because bone marrow contains:",["Muscle cells","*Hematopoietic stem cells that can regenerate all blood cell types","Nerve cells","Skin cells"],"Blood stem cells."),
    make_q(14,"A major ethical concern about embryonic stem cells is:",["Cost only","*They require destruction of human embryos to obtain (iPSCs may circumvent this issue)","They don't work","They're too abundant"],"Ethical debate."),
    make_q(15,"Regenerative medicine aims to:",["Replace all organs with machines","*Repair or replace damaged tissues and organs using stem cells, tissue engineering, and growth factors","Only use drugs","Prevent all disease"],"Repair and replacement."),
    make_q(16,"3D bioprinting uses _____ to create tissue structures.",["Metal","Plastic only","*Living cells (bioink) layered into 3D scaffolds that mimic tissue architecture","Only paper"],"Tissue fabrication."),
    make_q(17,"The HeLa cell line (from Henrietta Lacks) has been important because:",["It's a normal cell","*It was the first immortal human cell line, used in countless medical breakthroughs (polio vaccine, cancer research)","It can't divide","It's from an animal"],"Immortal cells."),
    make_q(18,"Stem cell therapy potential includes treating:",["Only one disease","*Heart disease, diabetes, Parkinson's, spinal cord injuries, blindness, and many other conditions","Nothing yet","Only cancer"],"Broad applications."),
    make_q(19,"Cloning (like Dolly the sheep) involves:",["Sexual reproduction","*Somatic cell nuclear transfer — placing a somatic cell nucleus into an enucleated egg","Meiosis","Natural birth"],"Nuclear transfer."),
    make_q(20,"The greatest challenge in stem cell therapy is:",["Growing cells","*Ensuring transplanted cells integrate properly, don't form tumors, and aren't rejected by the immune system","Finding stem cells","Cost alone"],"Safety challenges."),
],
# ── U10: Genetics ──
"u10_l10.1": [ # Mendelian Genetics
    make_q(8,"Mendel's law of segregation states:",["Alleles stay together","*Each organism carries two alleles for each trait, which separate during gamete formation (one per gamete)","All alleles are dominant","Traits blend"],"Segregation."),
    make_q(9,"A Punnett square is used to:",["Count chromosomes","*Predict the probability of offspring genotypes and phenotypes from a genetic cross","Measure DNA","Sequence genes"],"Genetic prediction."),
    make_q(10,"In a cross between Tt × Tt, the genotypic ratio is:",["All Tt","1:1","*1:2:1 (1 TT : 2 Tt : 1 tt)","3:1"],"Genotypic ratio."),
    make_q(11,"The phenotypic ratio from Tt × Tt (complete dominance) is:",["1:1","1:2:1","*3:1 (3 dominant phenotype : 1 recessive phenotype)","4:0"],"Phenotypic ratio."),
    make_q(12,"An organism with two identical alleles (TT or tt) is:",["Heterozygous","*Homozygous","Incomplete dominant","Codominant"],"Same alleles."),
    make_q(13,"An organism with two different alleles (Tt) is:",["Homozygous","*Heterozygous","Purebred","Mutant"],"Different alleles."),
    make_q(14,"A test cross involves crossing an organism with a dominant phenotype with:",["Another dominant organism","*A homozygous recessive organism (to determine if the dominant organism is TT or Tt)","Itself","A different species"],"Genotype determination."),
    make_q(15,"Mendel chose pea plants because they:",["Were expensive","*Have clear contrasting traits, short generation time, and can self- or cross-pollinate","Are complex","Have one gene"],"Model organism."),
    make_q(16,"The law of independent assortment states that:",["Genes are always linked","*Genes on different chromosomes assort independently during meiosis","All traits are inherited together","Genes don't separate"],"Independent sorting."),
    make_q(17,"A dihybrid cross (AaBb × AaBb) produces a phenotypic ratio of:",["3:1","1:1","*9:3:3:1 (with complete dominance and independent assortment)","1:2:1"],"Dihybrid ratio."),
    make_q(18,"Genotype refers to _____ while phenotype refers to _____.",["Appearance, genes","*Genetic makeup (alleles), physical appearance/traits","DNA, RNA","Protein, DNA"],"Genotype vs. phenotype."),
    make_q(19,"Probability in genetics: if both parents are Tt, the chance of a tt offspring is:",["0%","50%","75%","*25%"],"Single cross probability."),
    make_q(20,"Mendel's work was rediscovered in 1900 by:",["Watson and Crick","*de Vries, Correns, and von Tschermak (independently)","Darwin","Franklin"],"Rediscovery."),
],
"u10_l10.2": [ # Non-Mendelian Genetics
    make_q(8,"Incomplete dominance produces a _____ phenotype in heterozygotes.",["Dominant","Recessive","*Blended/intermediate (e.g., red × white = pink flowers)","No"],"Blending phenotype."),
    make_q(9,"Codominance means both alleles are:",["Blended","Hidden","*Fully expressed simultaneously (e.g., AB blood type shows both A and B antigens)","Recessive"],"Both expressed."),
    make_q(10,"Multiple alleles means a gene has:",["Only one allele","Only two alleles","*Three or more alleles in the population (e.g., ABO blood types: Iᴬ, Iᴮ, i)","Unlimited alleles"],"More than two."),
    make_q(11,"Polygenic traits are controlled by:",["One gene","*Multiple genes (e.g., skin color, height, eye color — producing continuous variation)","No genes","Only environment"],"Multi-gene traits."),
    make_q(12,"Epistasis occurs when:",["Genes are independent","*One gene masks or modifies the expression of another gene (e.g., coat color in Labrador retrievers)","Genes are linked","Alleles are codominant"],"Gene interaction."),
    make_q(13,"Sex-linked traits are carried on:",["Autosomes","*The X chromosome (mostly) — males (XY) are more likely to express X-linked recessive traits","The Y chromosome only","Both equally"],"X-linked inheritance."),
    make_q(14,"Color blindness and hemophilia are examples of:",["Autosomal dominant","Autosomal recessive","*X-linked recessive traits (more common in males)","Y-linked traits"],"Sex-linked examples."),
    make_q(15,"A carrier for an X-linked recessive trait is typically:",["A symptomatic male","*A heterozygous female (one normal X, one affected X — usually asymptomatic)","A homozygous male","Not possible"],"Female carrier."),
    make_q(16,"Pleiotropy means one gene affects:",["One trait","*Multiple phenotypic traits (e.g., sickle cell gene affects blood, joints, spleen, brain)","No traits","Only dominant traits"],"Multiple effects."),
    make_q(17,"Environmental influences on phenotype include:",["Nothing","*Temperature, nutrition, light, chemicals (e.g., temperature affects Siamese cat coat color)","Only genes matter","Only mutations"],"Environment matters."),
    make_q(18,"Linked genes tend to be inherited together because they:",["Are on different chromosomes","*Are close together on the same chromosome (crossing over can separate them)","Are identical","Are always dominant"],"Physical proximity."),
    make_q(19,"The Hardy-Weinberg principle describes:",["Natural selection","*A population in genetic equilibrium (no evolution occurring — allele frequencies stay constant)","Mutation rates","Genetic drift"],"Equilibrium model."),
    make_q(20,"Genomic imprinting means gene expression depends on:",["Allele type only","*Which PARENT the allele was inherited from (some genes are silenced based on parental origin)","Chromosome number","Gene size"],"Parental origin."),
],
"u10_l10.3": [ # DNA Replication, Transcription, and Translation
    make_q(8,"DNA replication is described as semiconservative because:",["Both strands are new","Both strands are old","*Each new DNA molecule has one old (template) strand and one newly synthesized strand","It's approximate"],"Half conserved."),
    make_q(9,"DNA helicase:",["Builds new DNA","*Unwinds the double helix by breaking hydrogen bonds between base pairs","Joins fragments","Proofreads DNA"],"Unwinding enzyme."),
    make_q(10,"DNA polymerase:",["Unwinds DNA","*Synthesizes new DNA strands by adding complementary nucleotides (5' to 3' direction)","Transcribes RNA","Translates protein"],"Building enzyme."),
    make_q(11,"Transcription produces _____ from a DNA template.",["DNA","Protein","*mRNA (messenger RNA)","Lipids"],"RNA synthesis."),
    make_q(12,"Transcription occurs in the:",["Cytoplasm","Ribosome","*Nucleus (in eukaryotes)","Mitochondria only"],"Nuclear process."),
    make_q(13,"RNA polymerase:",["Replicates DNA","*Reads the DNA template strand and synthesizes a complementary mRNA strand","Translates mRNA","Edits protein"],"Transcription enzyme."),
    make_q(14,"A start codon (AUG) codes for:",["Stop","*Methionine (and signals the beginning of translation)","Alanine","Nothing"],"Start signal."),
    make_q(15,"Stop codons (UAA, UAG, UGA) signal:",["Start of translation","*End of translation (release of the polypeptide from the ribosome)","Start of transcription","DNA replication"],"Termination."),
    make_q(16,"Translation occurs at the:",["Nucleus","DNA","*Ribosome (in the cytoplasm or on rough ER)","Golgi"],"Protein synthesis site."),
    make_q(17,"During translation, tRNA matches its _____ to the mRNA _____.",["Codon, anticodon","*Anticodon, codon (bringing the correct amino acid)","Gene, chromosome","Exon, intron"],"Codon-anticodon pairing."),
    make_q(18,"Introns are:",["Expressed sequences","*Non-coding sequences removed from mRNA during RNA processing (spliced out)","Coding sequences","Always harmful"],"Non-coding regions."),
    make_q(19,"Exons are:",["Non-coding sequences","*Expressed (coding) sequences that remain in mature mRNA after splicing","Removed during processing","Always non-functional"],"Coding regions."),
    make_q(20,"The genetic code is described as 'universal' because:",["Each organism has unique codons","*Nearly all organisms use the same codons for the same amino acids","It only applies to humans","It changes constantly"],"Shared code."),
],
"u10_l10.4": [ # Gene Regulation and Expression
    make_q(8,"Gene regulation is important because:",["All genes are always active","*Cells need to express different genes at different times for proper function (not all genes active simultaneously)","Genes can't be controlled","Only in bacteria"],"Selective expression."),
    make_q(9,"An operon (like the lac operon in bacteria) is:",["A single gene","*A cluster of genes with a shared promoter and regulatory elements that are transcribed together","A chromosome","An organism"],"Bacterial gene cluster."),
    make_q(10,"Transcription factors in eukaryotes:",["Block all genes","*Bind to DNA regulatory regions (promoters, enhancers) to activate or repress gene transcription","Destroy mRNA","Only work in bacteria"],"Expression controllers."),
    make_q(11,"Epigenetics involves changes in gene expression that:",["Change the DNA sequence","*Do NOT change the DNA sequence (e.g., DNA methylation, histone modification — can be heritable)","Only affect bacteria","Are not heritable"],"Above genetics."),
    make_q(12,"DNA methylation typically:",["Activates genes","*Silences gene expression (methyl groups on DNA prevent transcription)","Mutates genes","Replicates DNA"],"Gene silencing."),
    make_q(13,"Histone acetylation generally:",["Silences genes","*Activates gene expression (loosens DNA from histones, making it accessible for transcription)","Destroys histones","Replicates chromatin"],"Gene activation."),
    make_q(14,"microRNA (miRNA) regulates gene expression by:",["Activating translation","*Binding to mRNA and blocking translation or triggering mRNA degradation","Replicating DNA","Modifying histones"],"Post-transcriptional regulation."),
    make_q(15,"Cell differentiation occurs because:",["Cells have different DNA","*Different genes are expressed in different cell types (all cells have the same DNA but use different portions)","Mutations accumulate","DNA is lost"],"Same DNA, different expression."),
    make_q(16,"A homeotic (Hox) gene controls:",["One enzyme","*Body plan development (segment identity — what body structures form where during embryonic development)","Only eye color","Only height"],"Body plan genes."),
    make_q(17,"Mutations in gene regulatory regions can:",["Never cause disease","*Alter gene expression levels (producing too much or too little protein, potentially causing disease)","Only affect coding regions","Change amino acids directly"],"Regulatory mutations."),
    make_q(18,"Alternative splicing allows:",["Only one protein per gene","*One gene to produce multiple different mRNA variants (and thus different proteins)","DNA to change","Genes to duplicate"],"Protein diversity."),
    make_q(19,"Signal transduction pathways regulate genes by:",["Directly editing DNA","*Transmitting external signals (hormones, growth factors) to the nucleus to activate specific gene expression","Only in plants","Randomly activating genes"],"Signal-to-gene."),
    make_q(20,"Cancer often involves dysregulation of:",["No genes","*Gene expression — oncogenes become overactive AND tumor suppressors become silenced (multiple regulatory failures)","Only one gene","Only structural genes"],"Expression gone wrong."),
],
"u10_l10.5": [ # Biotechnology (CRISPR, cloning, GMOs)
    make_q(8,"CRISPR-Cas9 works by:",["Random mutation","*Using a guide RNA to direct the Cas9 enzyme to a specific DNA location for precise cutting and editing","Chemical treatment","UV radiation"],"Precision editing."),
    make_q(9,"GMOs (Genetically Modified Organisms) are created by:",["Natural selection only","*Inserting, deleting, or modifying specific genes using biotechnology techniques","Selective breeding only","Random breeding"],"Genetic modification."),
    make_q(10,"Bt crops contain genes from _____ that produce insecticidal proteins.",["Other plants","*Bacillus thuringiensis (a bacterium) — the protein is toxic to certain insect pests but safe for humans","Animals","Fungi"],"Bacterial gene."),
    make_q(11,"Golden Rice was engineered to produce:",["More starch","*Beta-carotene (vitamin A precursor) to address vitamin A deficiency in developing nations","Insect resistance","Herbicide tolerance"],"Nutritional enhancement."),
    make_q(12,"PCR (Polymerase Chain Reaction) is used to:",["Sequence proteins","*Amplify (make billions of copies of) a specific DNA segment using thermal cycling","Clone organisms","Modify genes"],"DNA amplification."),
    make_q(13,"Gel electrophoresis separates DNA fragments by:",["Color","*Size (smaller fragments migrate faster through the gel toward the positive electrode)","Weight","Shape"],"Size separation."),
    make_q(14,"Restriction enzymes:",["Build DNA","*Cut DNA at specific recognition sequences (used as molecular scissors in genetic engineering)","Replicate DNA","Translate mRNA"],"Molecular scissors."),
    make_q(15,"Gene therapy aims to:",["Remove all genes","*Treat genetic diseases by replacing, inactivating, or introducing genes into patient cells","Clone patients","Only diagnose diseases"],"Genetic treatment."),
    make_q(16,"Plasmids are commonly used in genetic engineering because they:",["Are chromosomes","*Are small circular DNA that can carry foreign genes into bacteria (vectors for cloning genes)","Cannot replicate","Are found in humans"],"Cloning vectors."),
    make_q(17,"DNA fingerprinting for forensics uses:",["Protein analysis","*STR (Short Tandem Repeat) analysis — comparing unique repetitive DNA patterns between individuals","Blood type only","Fingerprints only"],"Forensic identification."),
    make_q(18,"The Human Genome Project completed in 2003 revealed:",["100 genes","1,000 genes","*~20,000-25,000 protein-coding genes (far fewer than expected for such complexity)","1 million genes"],"Genome surprise."),
    make_q(19,"Concerns about GMOs include:",["No concerns exist","*Potential environmental impacts, gene flow to wild species, corporate control of seed supply, and public trust","Only cost","Only taste"],"GMO debate."),
    make_q(20,"Bioinformatics combines:",["Only biology","*Biology, computer science, and statistics to analyze large biological datasets (genomics, proteomics)","Only computers","Only chemistry"],"Data-driven biology."),
],
"u10_l10.6": [ # Human Genetics and Genetic Disorders
    make_q(8,"A karyotype is:",["A DNA sequence","*A visual display of an individual's chromosomes arranged by size and shape (used to detect abnormalities)","A gene map","A protein structure"],"Chromosome display."),
    make_q(9,"Autosomal dominant disorders require:",["Two copies of the mutant allele","*Only ONE copy of the mutant allele to be expressed (e.g., Huntington's disease)","No mutant alleles","Three copies"],"One allele sufficient."),
    make_q(10,"Autosomal recessive disorders require:",["One mutant allele","*Two copies of the mutant allele to be expressed (e.g., cystic fibrosis, sickle cell anemia)","No mutant alleles","Only in males"],"Two alleles needed."),
    make_q(11,"Sickle cell anemia is caused by:",["A whole chromosome missing","*A single amino acid substitution in hemoglobin (valine instead of glutamic acid — point mutation)","A viral infection","Environmental factors only"],"Point mutation."),
    make_q(12,"Carriers of sickle cell trait (heterozygous) may have an advantage against:",["Diabetes","Cancer","*Malaria (sickle cells are less hospitable to the malaria parasite — heterozygote advantage)","Heart disease"],"Balanced polymorphism."),
    make_q(13,"Cystic fibrosis affects:",["Only the brain","*Primarily the lungs and digestive system (thick mucus from defective CFTR chloride channel protein)","Only the heart","Only bones"],"Affected organs."),
    make_q(14,"A pedigree chart is used to:",["Count chromosomes","*Trace the inheritance pattern of a trait through a family across generations","Sequence DNA","Measure gene expression"],"Family inheritance."),
    make_q(15,"Genetic counseling helps families by:",["Changing their DNA","*Assessing the risk of genetic disorders in offspring and providing information for informed decisions","Curing genetic diseases","Guaranteeing healthy children"],"Risk assessment."),
    make_q(16,"Trisomy means having:",["One less chromosome","*Three copies of a chromosome instead of the normal two (e.g., Down syndrome = trisomy 21)","Four copies","Normal number"],"Extra chromosome."),
    make_q(17,"Turner syndrome (45, X) results from:",["An extra X","*Having only one X chromosome (monosomy X — affects females)","An extra Y","Trisomy 21"],"Missing sex chromosome."),
    make_q(18,"Klinefelter syndrome (47, XXY) affects:",["Females","*Males (extra X chromosome — may have reduced testosterone, taller stature, possible learning differences)","Both equally","Neither"],"Extra X in males."),
    make_q(19,"Genetic testing can reveal:",["Nothing useful","*Carrier status, disease risk, paternity, and pharmacogenomic information (how you metabolize drugs)","Only eye color","Only blood type"],"Testing applications."),
    make_q(20,"Ethical issues in human genetics include:",["None","*Privacy of genetic data, discrimination (GINA law), designer babies debate, and equitable access to testing/treatment","Only cost","Only time"],"Multiple ethics."),
],
# ── U11: Human Body Systems ──
"u11_l11.1": [ # Organization of the Human Body
    make_q(8,"The levels of organization from simplest to most complex are:",["Organ, tissue, cell, system","*Atom → molecule → organelle → cell → tissue → organ → organ system → organism","System, organ, cell, tissue","Organism → cell → atom"],"Hierarchy."),
    make_q(9,"The four main tissue types are:",["Bone, blood, skin, muscle","*Epithelial, connective, muscle, and nervous tissue","Only muscle and bone","Skin, fat, nerve, organ"],"Tissue types."),
    make_q(10,"Epithelial tissue functions in:",["Movement only","*Covering surfaces, lining organs, secretion, and absorption (skin, intestinal lining)","Energy storage only","Only protection"],"Covering and lining."),
    make_q(11,"Connective tissue includes:",["Only bone","*Bone, cartilage, blood, fat, tendons, and ligaments (most diverse tissue type)","Only blood","Only tendons"],"Diverse category."),
    make_q(12,"Homeostasis is the body's ability to:",["Grow rapidly","*Maintain stable internal conditions despite external changes (temperature, pH, glucose, etc.)","Reproduce","Fight all disease"],"Internal stability."),
    make_q(13,"Negative feedback loops:",["Amplify changes","*Reverse a change to return to the set point (e.g., thermostat controlling body temperature)","Always cause disease","Only increase responses"],"Restoring balance."),
    make_q(14,"Positive feedback loops:",["Reverse changes","*Amplify a response until an endpoint is reached (e.g., blood clotting, labor contractions)","Maintain set points","Are always harmful"],"Amplifying response."),
    make_q(15,"An example of a negative feedback loop is:",["Blood clotting","Labor contractions","*Blood glucose regulation (insulin lowers glucose when it's too high; glucagon raises it when too low)","Sneezing"],"Glucose regulation."),
    make_q(16,"Organ systems work together; for example, the respiratory and circulatory systems collaborate to:",["Digest food","*Deliver oxygen to cells and remove CO₂ (lungs oxygenate blood; heart pumps it throughout the body)","Control movement","Store energy"],"System cooperation."),
    make_q(17,"Smooth muscle is found in:",["Skeleton","Heart only","*Walls of internal organs (intestines, blood vessels, bladder) — involuntary control","Only voluntary muscles"],"Visceral muscle."),
    make_q(18,"Cardiac muscle is unique because it:",["Is voluntary","*Is striated, involuntary, and has intercalated discs for synchronized contraction (found only in the heart)","Is found throughout the body","Cannot contract"],"Heart-specific."),
    make_q(19,"Skeletal muscle is:",["Involuntary","*Voluntary, striated, and attached to bones for movement","Smooth","Found in organs"],"Voluntary movement."),
    make_q(20,"The integumentary system (skin) functions include:",["Only covering the body","*Protection, temperature regulation, sensation, vitamin D synthesis, and immune defense","Only appearance","Only sweating"],"Multiple skin functions."),
],
"u11_l11.2": [ # Circulatory System
    make_q(8,"The heart has _____ chambers.",["Two","Three","*Four (2 atria and 2 ventricles)","Six"],"Chamber count."),
    make_q(9,"The right side of the heart pumps blood to the:",["Body","Brain","*Lungs (pulmonary circuit — for oxygenation)","Liver"],"Pulmonary circuit."),
    make_q(10,"The left side of the heart pumps blood to the:",["Lungs","Right atrium","*Entire body (systemic circuit — delivering oxygenated blood)","Left lung only"],"Systemic circuit."),
    make_q(11,"Arteries carry blood _____ from the heart; veins carry blood _____ the heart.",["Toward, away from","*Away from, toward","Both directions","Neither"],"Vessel direction."),
    make_q(12,"Capillaries are important because they:",["Are the largest vessels","*Are the site of gas, nutrient, and waste exchange between blood and tissues (one cell thick)","Carry the most blood","Produce blood cells"],"Exchange sites."),
    make_q(13,"Red blood cells (erythrocytes) carry oxygen using:",["Plasma","White blood cells","*Hemoglobin (iron-containing protein that binds O₂)","Platelets"],"Oxygen transport."),
    make_q(14,"White blood cells (leukocytes) function primarily in:",["Oxygen transport","*Immune defense (fighting pathogens, producing antibodies)","Clotting","Carrying nutrients"],"Immune cells."),
    make_q(15,"Platelets (thrombocytes) are essential for:",["Fighting infection","*Blood clotting (forming platelet plugs and activating the clotting cascade at wound sites)","Carrying oxygen","Transporting nutrients"],"Clot formation."),
    make_q(16,"Blood pressure is measured as systolic over diastolic. Normal is approximately:",["80/120","*120/80 mmHg","200/150","60/40"],"Normal BP."),
    make_q(17,"The ABO blood type system is determined by _____ on red blood cells.",["Proteins inside the cell","*Antigens (glycoproteins) on the cell surface","Hemoglobin type","Cell size"],"Blood type antigens."),
    make_q(18,"Type O blood is considered the 'universal donor' because:",["It has all antigens","*It has NO A or B antigens (so it won't trigger immune reactions in any recipient)","It's the most common","It's the rarest"],"Universal donor."),
    make_q(19,"Atherosclerosis is:",["Healthy arteries","*Buildup of plaque (cholesterol, fat) inside artery walls, narrowing them and restricting blood flow","A type of anemia","Low blood pressure"],"Artery disease."),
    make_q(20,"The sinoatrial (SA) node is called the 'pacemaker' because it:",["Pumps blood","*Generates electrical impulses that set the heart's rhythm (initiating each heartbeat)","Filters blood","Produces blood cells"],"Heart rhythm."),
],
"u11_l11.3": [ # Respiratory System
    make_q(8,"Gas exchange occurs in the _____ of the lungs.",["Bronchi","Trachea","*Alveoli (tiny air sacs with thin walls surrounded by capillaries)","Bronchioles"],"Exchange site."),
    make_q(9,"The diaphragm aids breathing by:",["Pushing air out","*Contracting and flattening (creating negative pressure that draws air into the lungs during inhalation)","Only during exhalation","Producing mucus"],"Inhalation muscle."),
    make_q(10,"Oxygen moves from alveoli to blood by:",["Active transport","Osmosis","*Diffusion (from high O₂ concentration in alveoli to low O₂ in capillary blood)","Endocytosis"],"Passive gas exchange."),
    make_q(11,"CO₂ moves from blood to alveoli by:",["Active transport","Osmosis","*Diffusion (from high CO₂ in blood to low CO₂ in alveoli — then exhaled)","Filtration"],"CO₂ removal."),
    make_q(12,"The trachea is kept open by:",["Muscle alone","Bone","*C-shaped cartilage rings (preventing collapse while allowing flexibility)","Pressure only"],"Airway support."),
    make_q(13,"Surfactant in the alveoli:",["Creates mucus","*Reduces surface tension, preventing alveoli from collapsing (premature babies may lack surfactant)","Kills bacteria","Produces oxygen"],"Surface tension reducer."),
    make_q(14,"Hemoglobin releases more oxygen when:",["pH increases","*pH decreases (Bohr effect — active tissues produce CO₂/acid, triggering O₂ release where needed)","Temperature decreases","CO₂ decreases"],"Bohr effect."),
    make_q(15,"The respiratory rate is primarily controlled by:",["Oxygen levels","Conscious thought","*CO₂ levels in the blood (detected by chemoreceptors in the brainstem)","Heart rate"],"Breathing control."),
    make_q(16,"Asthma involves:",["Hardened arteries","*Inflammation and narrowing of airways (bronchospasm), causing difficulty breathing","Alveoli destruction","Heart problems"],"Airway condition."),
    make_q(17,"Emphysema destroys _____, reducing surface area for gas exchange.",["Bronchi","*Alveoli (often caused by smoking — irreversible damage)","Trachea","Diaphragm"],"Alveolar destruction."),
    make_q(18,"The epiglottis prevents:",["Breathing","*Food from entering the trachea during swallowing (flap covers the airway)","Speaking","Coughing"],"Airway protection."),
    make_q(19,"Tidal volume is:",["Maximum lung capacity","*The volume of air in a normal breath (~500 mL at rest)","The air remaining after exhalation","Total lung capacity"],"Normal breath volume."),
    make_q(20,"Vital capacity is:",["Normal breath volume","*The maximum volume of air that can be exhaled after a maximum inhalation (~4-5 L)","Air remaining after exhale","Only during exercise"],"Maximum breath capacity."),
],
"u11_l11.4": [ # Digestive System
    make_q(8,"Mechanical digestion includes:",["Enzyme action only","*Chewing, churning in the stomach, and segmentation in the intestines (physical breakdown)","Only in the stomach","Only chemical reactions"],"Physical breakdown."),
    make_q(9,"Chemical digestion involves:",["Chewing only","*Enzymes breaking down macromolecules into monomers (amylase → starch, pepsin → proteins, lipase → fats)","Only in the mouth","Only mechanical forces"],"Enzymatic breakdown."),
    make_q(10,"The correct order of the digestive tract is:",["Stomach, esophagus, mouth, intestine","*Mouth → esophagus → stomach → small intestine → large intestine → rectum","Small intestine, stomach, mouth","Stomach, mouth, intestines"],"GI tract order."),
    make_q(11,"Most nutrient absorption occurs in the:",["Stomach","Mouth","*Small intestine (villi and microvilli increase surface area for maximum absorption)","Large intestine"],"Absorption site."),
    make_q(12,"The liver produces _____ that helps digest fats.",["Insulin","Pepsin","*Bile (stored in the gallbladder, emulsifies fats into smaller droplets)","Amylase"],"Fat digestion aid."),
    make_q(13,"The pancreas produces:",["Only insulin","*Digestive enzymes (amylase, lipase, trypsin) AND hormones (insulin, glucagon)","Only bile","Only stomach acid"],"Dual function organ."),
    make_q(14,"Villi in the small intestine increase:",["Stomach acid","*Surface area for absorption (each villus has microvilli — further increasing absorptive surface by ~600×)","Enzyme production","Mechanical digestion"],"Surface area."),
    make_q(15,"The large intestine's main functions are:",["Enzyme secretion","*Water absorption, vitamin K production (by bacteria), and feces formation","Protein digestion","Fat absorption"],"Large intestine roles."),
    make_q(16,"Hydrochloric acid (HCl) in the stomach:",["Digests carbohydrates","*Creates low pH to activate pepsin, kill bacteria, and begin protein denaturation","Absorbs nutrients","Produces bile"],"Gastric acid."),
    make_q(17,"Peristalsis is:",["Random movement","*Rhythmic, wave-like muscle contractions that push food through the digestive tract","Only in the esophagus","Voluntary movement"],"GI motility."),
    make_q(18,"The gut microbiome:",["Is harmful","*Consists of trillions of beneficial bacteria that aid digestion, produce vitamins, and support immune function","Has no role","Only causes disease"],"Beneficial bacteria."),
    make_q(19,"Celiac disease involves:",["Lactose intolerance","*An immune reaction to gluten that damages small intestine villi, reducing nutrient absorption","Stomach ulcer","Gallstones"],"Gluten sensitivity."),
    make_q(20,"The appendix was once considered vestigial but may:",["Be entirely useless","*Serve as a reservoir for beneficial gut bacteria and play a role in immune function","Digest cellulose","Produce hormones"],"Possible function."),
],
"u11_l11.5": [ # Nervous System
    make_q(8,"The two main divisions of the nervous system are:",["Somatic and autonomic only","*Central Nervous System (brain + spinal cord) and Peripheral Nervous System (all other nerves)","Only the brain","Motor and sensory only"],"Two divisions."),
    make_q(9,"A neuron transmits signals via:",["Blood flow","*Electrical impulses (action potentials) along the axon and chemical signals (neurotransmitters) across synapses","Sound waves","Hormones only"],"Signal transmission."),
    make_q(10,"The three types of neurons are:",["Only sensory","*Sensory (afferent), motor (efferent), and interneurons (connecting neurons)","Only motor","Large and small"],"Neuron types."),
    make_q(11,"The synapse is:",["The cell body","*The gap between two neurons where neurotransmitters carry the signal across","The axon","The dendrite"],"Neural junction."),
    make_q(12,"Myelin sheath functions to:",["Slow signals","*Insulate axons and dramatically speed up nerve impulse conduction (saltatory conduction)","Block signals","Produce ATP"],"Speed insulation."),
    make_q(13,"The autonomic nervous system controls:",["Voluntary movement","*Involuntary functions (heart rate, digestion, breathing — sympathetic and parasympathetic divisions)","Only sensation","Only thinking"],"Involuntary control."),
    make_q(14,"Sympathetic ('fight or flight') responses include:",["Slower heart rate","*Increased heart rate, dilated pupils, increased blood pressure, redirected blood to muscles","Increased digestion","Constricted pupils"],"Stress response."),
    make_q(15,"Parasympathetic ('rest and digest') responses include:",["Faster heart rate","*Decreased heart rate, increased digestion, constricted pupils (calming the body)","Dilated pupils","Increased blood pressure"],"Calming response."),
    make_q(16,"A reflex arc involves:",["Only the brain","*Sensory neuron → spinal cord (interneuron) → motor neuron (bypassing the brain for speed)","Only voluntary response","Only pain receptors"],"Rapid response."),
    make_q(17,"The cerebral cortex is responsible for:",["Only movement","*Higher functions: thinking, language, memory, reasoning, consciousness, and voluntary movement","Only breathing","Only heart rate"],"Higher functions."),
    make_q(18,"The cerebellum coordinates:",["Emotions","*Balance, posture, and fine motor coordination (smooth, precise movements)","Memory","Digestion"],"Movement precision."),
    make_q(19,"Neurotransmitters like dopamine and serotonin affect:",["Only muscle contraction","*Mood, motivation, sleep, pleasure, and pain (imbalances linked to depression, anxiety, addiction)","Only digestion","Only heart rate"],"Chemical messengers."),
    make_q(20,"Multiple sclerosis (MS) involves:",["Neurotransmitter excess","*Immune system attacking myelin sheaths, disrupting nerve signal transmission","Excess dopamine","Neuron overgrowth"],"Autoimmune demyelination."),
],
"u11_l11.6": [ # Endocrine System
    make_q(8,"The endocrine system communicates using:",["Electrical impulses","*Hormones (chemical messengers) released into the bloodstream","Sound waves","Direct contact only"],"Hormone signaling."),
    make_q(9,"The pituitary gland is called the 'master gland' because it:",["Is the largest","*Produces hormones that control other endocrine glands (TSH, ACTH, growth hormone, etc.)","Produces the most hormones","Is in the brain"],"Control center."),
    make_q(10,"The thyroid gland regulates:",["Digestion","Blood sugar","*Metabolism, growth, and development (through thyroid hormones T3 and T4)","Blood clotting"],"Metabolic regulation."),
    make_q(11,"The adrenal glands produce:",["Only cortisol","*Cortisol (stress), aldosterone (blood pressure), and epinephrine/norepinephrine (fight-or-flight)","Only adrenaline","Only insulin"],"Multiple hormones."),
    make_q(12,"The pancreas produces insulin and glucagon to regulate:",["Heart rate","*Blood glucose levels (insulin lowers; glucagon raises)","Body temperature","Growth"],"Glucose homeostasis."),
    make_q(13,"Type 1 diabetes results from:",["Insulin resistance","*Autoimmune destruction of insulin-producing beta cells in the pancreas (no insulin production)","Overeating","Lack of exercise only"],"Autoimmune diabetes."),
    make_q(14,"Type 2 diabetes is characterized by:",["No insulin production","*Insulin resistance (cells don't respond properly) and often insufficient insulin production","Excess glucagon only","Thyroid dysfunction"],"Insulin resistance."),
    make_q(15,"Hormones are specific to their target cells because:",["They travel to every cell","*Only target cells have the specific receptors for that hormone (lock-and-key specificity)","All cells respond equally","Hormones have GPS"],"Receptor specificity."),
    make_q(16,"Negative feedback regulation of hormones means:",["Hormones always increase","*Rising hormone levels signal the gland to reduce production (maintaining stable levels)","Positive signals only","No regulation exists"],"Self-regulation."),
    make_q(17,"Growth hormone (GH) is produced by the:",["Thyroid","Adrenal glands","*Anterior pituitary gland","Pancreas"],"GH source."),
    make_q(18,"Melatonin from the pineal gland regulates:",["Digestion","Growth","*Sleep-wake cycles (circadian rhythm — increases at night, promotes sleepiness)","Blood pressure"],"Sleep hormone."),
    make_q(19,"The hypothalamus links the nervous and endocrine systems by:",["Only sending nerve impulses","*Producing releasing/inhibiting hormones that control the pituitary gland (neuroendocrine interface)","Only producing hormones","Having no connection"],"Brain-hormone link."),
    make_q(20,"Endocrine disruptors are:",["Beneficial supplements","*Environmental chemicals (BPA, pesticides) that interfere with hormone function, potentially causing health issues","Only in medicine","Harmless substances"],"Chemical interference."),
],
"u11_l11.7": [ # Immune System
    make_q(8,"Innate immunity provides:",["Specific, slow response","*Nonspecific, immediate defense (skin, mucous membranes, inflammation, phagocytes)","Learned immunity","Memory cells"],"First line defense."),
    make_q(9,"Adaptive immunity provides:",["Nonspecific defense","*Specific, targeted responses to particular pathogens AND immunological memory","Only skin protection","Only barrier defense"],"Targeted defense."),
    make_q(10,"B cells produce:",["Red blood cells","*Antibodies (immunoglobulins) specific to antigens on pathogens","T cells","Platelets"],"Antibody producers."),
    make_q(11,"T cells include:",["Only helper cells","*Helper T cells (activate immune response) and cytotoxic T cells (kill infected cells directly)","Only killer cells","B cells"],"T cell types."),
    make_q(12,"Vaccines work by:",["Curing diseases","*Exposing the immune system to weakened/inactivated pathogens (or antigens) to create memory cells without causing disease","Killing pathogens directly","Blocking all immune responses"],"Immune training."),
    make_q(13,"Inflammation is characterized by:",["Only pain","*Redness, heat, swelling, and pain (increased blood flow brings immune cells to the site)","Cooling the area","Only swelling"],"Cardinal signs."),
    make_q(14,"Antigens are:",["Antibodies","*Foreign molecules (on pathogens) that trigger an immune response","White blood cells","Self-proteins"],"Immune triggers."),
    make_q(15,"An autoimmune disease occurs when:",["The immune system is too weak","*The immune system attacks the body's own cells (e.g., Type 1 diabetes, lupus, MS)","Only during infection","The immune system shuts down"],"Self-attack."),
    make_q(16,"Allergies are:",["Normal immune responses","*Hypersensitive immune reactions to normally harmless substances (pollen, peanuts) — histamine release","Infections","Autoimmune diseases"],"Overreaction."),
    make_q(17,"HIV/AIDS weakens immunity by:",["Killing B cells","*Destroying helper T cells (CD4+ cells), eventually crippling the adaptive immune response","Blocking skin barriers","Destroying antibodies"],"T cell destruction."),
    make_q(18,"Passive immunity differs from active immunity in that it:",["Lasts longer","*Is temporary (receiving pre-made antibodies, like from mother to baby), while active immunity involves your own immune response and creates memory","Is always artificial","Creates memory cells"],"Borrowed protection."),
    make_q(19,"The complement system:",["Replaces the immune system","*A group of proteins that enhance (complement) the ability of antibodies and phagocytes to clear pathogens","Only works with vaccines","Is in plants only"],"Enhancement system."),
    make_q(20,"Herd immunity is achieved when:",["One person is vaccinated","*A sufficient percentage of a population is immune, reducing spread and protecting those who can't be vaccinated","Everyone gets the disease","No one is vaccinated"],"Community protection."),
],
"u11_l11.8": [ # Reproductive System
    make_q(8,"The primary function of the male reproductive system is:",["Only hormone production","*Producing sperm (spermatogenesis in testes) and delivering them for fertilization","Only testosterone","Only urination"],"Male function."),
    make_q(9,"The primary function of the female reproductive system is:",["Only hormone production","*Producing eggs (oogenesis in ovaries), supporting fertilization, and nurturing the developing embryo","Only estrogen","Only menstruation"],"Female function."),
    make_q(10,"Testosterone is produced in the:",["Pituitary gland","*Testes (Leydig cells — stimulated by LH from the pituitary)","Adrenal glands only","Prostate"],"Male hormone source."),
    make_q(11,"Estrogen and progesterone are produced primarily in the:",["Testes","Pituitary","*Ovaries (and placenta during pregnancy)","Thyroid"],"Female hormone sources."),
    make_q(12,"The menstrual cycle averages _____ days and is regulated by:",["14 days, GH","*~28 days, FSH, LH, estrogen, and progesterone (complex hormonal feedback)","7 days, insulin","35 days, testosterone"],"Cycle length and hormones."),
    make_q(13,"Ovulation occurs when:",["Menstruation starts","*A mature egg is released from the ovary (typically around day 14 — triggered by LH surge)","Fertilization occurs","An embryo implants"],"Egg release."),
    make_q(14,"Fertilization typically occurs in the:",["Uterus","Ovary","*Fallopian tube (oviduct)","Vagina"],"Fertilization location."),
    make_q(15,"The placenta functions during pregnancy to:",["Protect against all diseases","*Exchange nutrients, oxygen, and waste between mother and fetus (also produces hormones)","Produce eggs","Store sperm"],"Fetal support."),
    make_q(16,"Identical twins (monozygotic) result from:",["Two eggs, two sperm","*One fertilized egg that splits into two embryos (genetically identical)","IVF only","Fraternal division"],"Splitting event."),
    make_q(17,"Fraternal twins (dizygotic) result from:",["One egg splitting","*Two separate eggs fertilized by two separate sperm (genetically no more similar than any siblings)","Cloning","One sperm, two eggs"],"Separate fertilizations."),
    make_q(18,"IVF (In Vitro Fertilization) involves:",["Natural conception","*Fertilizing eggs with sperm outside the body, then implanting embryo(s) into the uterus","Only sperm donation","Only hormone therapy"],"Assisted reproduction."),
    make_q(19,"STIs (Sexually Transmitted Infections) include:",["Only bacterial infections","*Bacterial (chlamydia, gonorrhea), viral (HIV, HPV, herpes), and parasitic (trichomoniasis) infections","Only viral","Only one type"],"Multiple pathogen types."),
    make_q(20,"Hormonal contraceptives (the pill) prevent pregnancy primarily by:",["Killing sperm","*Preventing ovulation (synthetic hormones suppress FSH and LH, no egg release)","Blocking fallopian tubes","Changing uterus shape"],"Ovulation suppression."),
],
"u11_l11.9": [ # Homeostasis
    make_q(8,"Body temperature is maintained at approximately:",["100°F","*98.6°F (37°C) through negative feedback mechanisms","95°F","104°F"],"Normal temperature."),
    make_q(9,"When body temperature rises, the hypothalamus triggers:",["Shivering","*Vasodilation (widening blood vessels near skin) and sweating (evaporative cooling)","Vasoconstriction","Eating"],"Cooling response."),
    make_q(10,"When body temperature drops, the body responds with:",["Sweating","*Shivering (muscle contractions generate heat), vasoconstriction, and raising body hair (goosebumps)","Vasodilation","Increased sweating"],"Warming response."),
    make_q(11,"Blood calcium levels are regulated by:",["Insulin and glucagon","*Parathyroid hormone (PTH — raises Ca²⁺) and calcitonin (lowers Ca²⁺)","Only vitamin D","Only diet"],"Calcium balance."),
    make_q(12,"The kidneys maintain homeostasis by:",["Only producing urine","*Filtering blood, regulating water/salt balance, maintaining pH, removing waste, and controlling blood pressure","Only making hormones","Only filtering toxins"],"Multiple kidney functions."),
    make_q(13,"ADH (antidiuretic hormone) helps the body:",["Lose water","*Retain water by increasing water reabsorption in the kidneys (released when dehydrated)","Excrete sodium","Increase urine output"],"Water conservation."),
    make_q(14,"Blood pH is maintained at approximately:",["6.0","*7.35-7.45 (slightly basic — maintained by buffers, lungs, and kidneys)","8.0","5.5"],"Blood pH range."),
    make_q(15,"If blood pH drops (acidosis), the respiratory system compensates by:",["Slowing breathing","*Increasing breathing rate (exhaling more CO₂ to raise pH — CO₂ + H₂O ↔ H₂CO₃)","Stopping breathing","No compensation"],"Respiratory compensation."),
    make_q(16,"The liver maintains homeostasis through:",["Only bile production","*Detoxification, glucose storage/release (glycogen), protein synthesis, and bile production","Only enzyme production","Only immune function"],"Liver's many roles."),
    make_q(17,"Osmoregulation is:",["Temperature control","*The regulation of water and solute concentrations in body fluids (maintaining osmotic balance)","Blood pressure control","Hormone regulation only"],"Water balance."),
    make_q(18,"When you eat a meal, blood glucose rises and:",["Nothing happens","*The pancreas releases insulin, signaling cells to absorb glucose (negative feedback lowers glucose to normal)","Glucagon is released","More glucose is produced"],"Postprandial response."),
    make_q(19,"Disruption of homeostasis can lead to:",["Better health","*Disease or death (diabetes = glucose imbalance, kidney failure = waste accumulation, hypothermia/hyperthermia)","Improved function","No consequences"],"Disease connection."),
    make_q(20,"The set point in homeostasis is:",["Always the same for everyone","*The target value the body strives to maintain (e.g., 37°C for temperature, 70-100 mg/dL for fasting glucose)","Only for temperature","Unmeasurable"],"Target value."),
],
# ── U12: Applied Biology ──
"u12_l12.1": [ # Biotechnology and Genetic Engineering
    make_q(8,"Recombinant DNA technology involves:",["Cloning whole organisms","*Combining DNA from different sources to create new genetic combinations (e.g., human insulin gene in bacteria)","Only natural breeding","Destroying DNA"],"DNA recombination."),
    make_q(9,"Insulin for diabetics is now produced using:",["Pig pancreas only","*Genetically modified bacteria (E. coli) or yeast containing the human insulin gene","Chemical synthesis only","Plant extraction"],"Recombinant insulin."),
    make_q(10,"Transgenic organisms contain:",["No foreign DNA","*Genes from another species (e.g., bacteria with human genes, glow-in-the-dark fish with jellyfish GFP)","Only their own DNA","Random mutations"],"Cross-species genes."),
    make_q(11,"Gene cloning uses _____ to produce many copies of a gene.",["Heat only","*Bacterial plasmids as vectors to replicate genes in bacterial cells (or PCR for in vitro amplification)","Only chemicals","Light"],"Gene amplification."),
    make_q(12,"Stem cell research holds promise for treating:",["Nothing","*Parkinson's, spinal cord injuries, diabetes, heart disease, and many other conditions","Only cancer","Only genetic disorders"],"Therapeutic potential."),
    make_q(13,"Pharming is the use of:",["Only traditional farming","*Genetically modified animals or plants to produce pharmaceutical proteins (e.g., goat milk containing clotting factors)","Only bacteria","Drug manufacturing"],"Biological factories."),
    make_q(14,"Bioremediation uses:",["Chemicals to clean spills","*Organisms (bacteria, fungi, plants) to break down environmental pollutants (oil spills, heavy metals)","Fire to destroy waste","Only humans to clean up"],"Biological cleanup."),
    make_q(15,"Forensic DNA analysis using STRs provides:",["Circumstantial evidence only","*Highly reliable individual identification (probability of random match: 1 in billions to trillions)","Perfect identification always","No useful information"],"Forensic reliability."),
    make_q(16,"Pharmacogenomics studies how:",["All drugs work the same","*An individual's genetic makeup affects their response to drugs (personalized medicine)","Only genetics","Only pharmacology"],"Personalized treatment."),
    make_q(17,"Synthetic biology aims to:",["Only study existing organisms","*Design and build new biological parts, devices, and systems (or redesign existing ones for useful purposes)","Destroy organisms","Replace all medicine"],"Engineering life."),
    make_q(18,"CRISPR has potential applications in:",["Only agriculture","*Medicine (gene therapy), agriculture (disease-resistant crops), research, and potentially eliminating genetic diseases","Only research","Only animals"],"Wide applications."),
    make_q(19,"Concerns about genetic engineering include:",["No concerns","*Unintended genetic consequences, environmental impacts, ethical dilemmas, and equitable access","Only cost","Only in developing nations"],"Valid concerns."),
    make_q(20,"The future of biotechnology will likely include:",["No new advances","*Personalized medicine, gene drives against disease vectors, lab-grown organs, and advanced gene therapies","Only current techniques","Fewer applications"],"Future directions."),
],
"u12_l12.2": [ # Bioethics
    make_q(8,"Bioethics is the study of:",["Only medical ethics","*Ethical issues arising from advances in biology, medicine, and biotechnology","Only environmental ethics","Only legal issues"],"Ethics in biology."),
    make_q(9,"Designer babies raise concerns about:",["Improved health only","*Genetic inequality, eugenics, consent of future children, and commercialization of human traits","Nothing problematic","Only cost"],"Selection concerns."),
    make_q(10,"The ethical principle of autonomy in medicine means:",["Doctors decide everything","*Patients have the right to make informed decisions about their own medical treatment","Government decides","No one decides"],"Patient rights."),
    make_q(11,"Genetic privacy concerns include:",["No concerns","*Employers or insurers potentially discriminating based on genetic predispositions (GINA law helps protect against this)","Only identity theft","Only DNA testing accuracy"],"Privacy risks."),
    make_q(12,"Animal testing in research is ethically debated because:",["Animals don't feel pain","*There's a conflict between potential human medical benefits and animal welfare/suffering","It always works","It never works"],"Welfare debate."),
    make_q(13,"The Nuremberg Code (1947) established:",["GMO regulations","*Ethical principles for human experimentation, including voluntary informed consent","Animal testing rules","Environmental laws"],"Research ethics foundation."),
    make_q(14,"Cloning humans is controversial because of:",["Technical simplicity","*Safety risks, identity concerns, commodification of human life, and ethical/religious objections","Universal agreement","No controversy"],"Multiple objections."),
    make_q(15,"Organ transplant ethics involve questions about:",["Only cost","*Fair allocation, consent, organ markets, xenotransplantation, and living donor risks","No ethical issues","Only the recipient"],"Allocation fairness."),
    make_q(16,"Gene drives could eliminate malaria-carrying mosquitoes but raise concerns about:",["Nothing","*Unintended ecological consequences of eliminating or modifying entire wild species","Only mosquito welfare","Only cost"],"Ecological risk."),
    make_q(17,"The precautionary principle states:",["Act first, think later","*If an action has potential harm, the burden of proof that it is NOT harmful falls on those proposing it","Ignore risks","Only proven harms matter"],"Safety first approach."),
    make_q(18,"Patenting genes was controversial because:",["Patents are free","*Critics argued that naturally occurring genes are discoveries (not inventions) and patents could restrict research","Everyone agreed with patents","Only corporations cared"],"Gene ownership debate."),
    make_q(19,"Informed consent in clinical trials requires:",["No information","*Full disclosure of risks, benefits, alternatives, and the right to withdraw at any time without penalty","Only signing a form","Only verbal agreement"],"Consent requirements."),
    make_q(20,"Bioethics education is important because:",["It's irrelevant","*Rapid advances in biology require informed citizens who can engage in evidence-based ethical discussions and policy decisions","Only scientists need it","Only politicians decide"],"Informed society."),
],
"u12_l12.3": [ # Medicine and Pharmacology
    make_q(8,"Antibiotics work against:",["Viruses","*Bacteria (by targeting bacterial cell walls, ribosomes, or DNA replication — not effective against viruses)","All pathogens","Fungi only"],"Bacterial targeting."),
    make_q(9,"Antibiotic resistance develops because:",["Medicine is ineffective","*Overuse and misuse allow resistant bacteria to survive and reproduce (natural selection)","Bacteria are invincible","Doctors make errors"],"Resistance mechanism."),
    make_q(10,"Vaccines stimulate:",["Innate immunity only","*Adaptive immunity (specifically, production of memory B and T cells for long-term protection)","Passive immunity","No immune response"],"Active immunization."),
    make_q(11,"mRNA vaccines (like COVID-19 vaccines) work by:",["Injecting the virus","*Instructing cells to produce a viral protein (spike protein), triggering an immune response without the virus","Changing DNA","Injecting antibodies"],"mRNA technology."),
    make_q(12,"Pharmacokinetics studies:",["Only drug effects","*How the body processes a drug: absorption, distribution, metabolism, and excretion (ADME)","Only drug design","Only side effects"],"Drug processing."),
    make_q(13,"Drug clinical trials have _____ phases before approval.",["1","2","*3 (Phase I: safety/dosing, Phase II: efficacy, Phase III: large-scale confirmation) + Phase IV post-market","5"],"Trial phases."),
    make_q(14,"Personalized medicine uses:",["One treatment for all","*Genetic, environmental, and lifestyle information to tailor treatment to individual patients","Only generic drugs","Random treatment"],"Tailored treatment."),
    make_q(15,"Antimicrobial stewardship promotes:",["Using antibiotics for everything","*Appropriate use of antibiotics (right drug, right dose, right duration) to slow resistance development","Avoiding all medicine","Only herbal remedies"],"Responsible use."),
    make_q(16,"Zoonotic diseases are:",["Only in animals","*Diseases that spread from animals to humans (Ebola, COVID-19, rabies, influenza — about 75% of emerging diseases)","Only in humans","Only in plants"],"Animal-to-human."),
    make_q(17,"Prions cause disease by:",["Being bacteria","Being viruses","*Being misfolded proteins that cause normal proteins to misfold (e.g., mad cow disease, CJD — no DNA/RNA)","Being parasites"],"Protein-only pathogens."),
    make_q(18,"The placebo effect demonstrates that:",["Placebos are drugs","*Psychological factors can influence physical health outcomes (important to control for in clinical trials)","Medicine doesn't work","Only real drugs help"],"Mind-body connection."),
    make_q(19,"Antimicrobial resistance is considered one of the greatest threats to:",["Technology","*Global public health (could make common infections untreatable if new antibiotics aren't developed)","Education","Transportation"],"Global health threat."),
    make_q(20,"Biologic drugs (like monoclonal antibodies) are:",["Simple chemicals","*Complex molecules produced by living cells, targeting specific disease mechanisms (cancer, autoimmune diseases)","Only vitamins","Only vaccines"],"Targeted biologics."),
],
"u12_l12.4": [ # Environmental Biology
    make_q(8,"Ecology is the study of:",["Only animals","*Interactions between organisms and their environment (at population, community, and ecosystem levels)","Only plants","Only pollution"],"Ecological science."),
    make_q(9,"An ecological niche includes:",["Only where an organism lives","*The organism's role in the ecosystem: its habitat, diet, behavior, interactions, and resource use","Only its food","Only its predators"],"Full role."),
    make_q(10,"Primary succession occurs on:",["Existing soil","*Bare, lifeless surfaces (volcanic rock, new islands) where no soil or life existed before","Recently disturbed areas","Only in water"],"Starting from scratch."),
    make_q(11,"Secondary succession occurs after:",["Primary succession only","*A disturbance that removes most life but leaves soil intact (fire, flood, farming)","No life existed","Extinction events only"],"Soil remains."),
    make_q(12,"The greenhouse effect is:",["Always harmful","*A natural process where atmospheric gases trap heat (essential for life — the problem is ENHANCED greenhouse effect from excess CO₂)","Only caused by humans","Not real"],"Natural vs. enhanced."),
    make_q(13,"Ocean acidification results from:",["Acid rain only","*Oceans absorbing excess atmospheric CO₂, forming carbonic acid (lowering pH and threatening marine life)","Volcanic eruptions only","Sewage only"],"CO₂ absorption."),
    make_q(14,"Eutrophication in water bodies is caused by:",["Clean water","*Excess nutrients (nitrogen, phosphorus) from fertilizer runoff, causing algal blooms that deplete oxygen","Too little nutrients","Only in oceans"],"Nutrient pollution."),
    make_q(15,"Biomagnification is problematic because:",["Toxins dilute in food chains","*Toxin concentrations increase at each trophic level (top predators like eagles accumulate the most)","It helps organisms","It's theoretical"],"Toxin accumulation."),
    make_q(16,"Keystone species affect ecosystems:",["Minimally","*Disproportionately to their abundance (their removal causes dramatic ecosystem changes)","Only through predation","Not at all"],"Disproportionate impact."),
    make_q(17,"The carbon cycle involves:",["Only living things","*Photosynthesis, respiration, decomposition, combustion, and ocean absorption (linking atmosphere, biosphere, lithosphere, hydrosphere)","Only the atmosphere","Only fossil fuels"],"Full carbon cycle."),
    make_q(18,"Invasive species threaten ecosystems by:",["Never causing harm","*Outcompeting natives for resources, altering habitats, and often lacking natural predators in their new environment","Only in small numbers","Only in cities"],"Ecological disruption."),
    make_q(19,"Sustainable practices include:",["Using resources as fast as possible","*Renewable energy, recycling, sustainable agriculture, reducing waste, and conserving biodiversity","Only recycling","Ignoring environmental problems"],"Multiple approaches."),
    make_q(20,"Ecological footprint measures:",["Physical foot size","*The amount of natural resources a person, city, or country consumes (in global hectares of biocapacity)","Only CO₂","Only water use"],"Resource impact."),
],
"u12_l12.5": [ # Astrobiology
    make_q(8,"Astrobiology studies:",["Only astronomy","*The origin, evolution, and possibility of life in the universe","Only biology","Only chemistry"],"Life in the universe."),
    make_q(9,"The habitable zone (Goldilocks zone) is the region around a star where:",["Any planet can have life","*Conditions could allow liquid water on a planet's surface (not too hot, not too cold)","Planets always form","Stars are born"],"Liquid water zone."),
    make_q(10,"Extremophiles are organisms that:",["Are extinct","*Thrive in extreme conditions (heat, cold, acid, pressure) — expanding our understanding of where life can exist","Only live in normal conditions","Are theoretical"],"Extreme life."),
    make_q(11,"Europa (moon of Jupiter) is a target for astrobiology because it:",["Has a thick atmosphere","*Likely has a subsurface liquid water ocean beneath its ice crust (potential habitat for microbial life)","Is closest to Earth","Has visible life"],"Ocean moon."),
    make_q(12,"Mars is studied for past life evidence because it:",["Currently has life","*Shows evidence of past liquid water (river channels, minerals) and may have had habitable conditions billions of years ago","Has a thick atmosphere now","Is identical to Earth"],"Past habitability."),
    make_q(13,"The building blocks of life (amino acids, organic molecules) have been found in:",["Only on Earth","*Meteorites, interstellar space, and comets (suggesting organic chemistry is common in the universe)","Only in labs","Nowhere beyond Earth"],"Universal chemistry."),
    make_q(14,"SETI (Search for Extraterrestrial Intelligence) primarily searches for:",["Physical aliens","*Radio or other electromagnetic signals that could indicate intelligent civilizations","Fossils on other planets","Alien spacecraft"],"Signal detection."),
    make_q(15,"The Miller-Urey experiment (1953) showed that:",["Life was created in a lab","*Simple organic molecules (amino acids) could form from inorganic chemicals under early Earth-like conditions","DNA evolved from RNA","Cells can form spontaneously"],"Prebiotic chemistry."),
    make_q(16,"Panspermia is the hypothesis that:",["Life originated on Earth only","*Life (or its building blocks) could have been transported between planets/moons via meteorites or comets","Aliens planted life on Earth","Life is impossible elsewhere"],"Cosmic seeding."),
    make_q(17,"Biosignatures that scientists look for on other worlds include:",["Only oxygen","*Atmospheric gases (O₂, methane together), organic molecules, liquid water, and energy sources","Only water","Only fossils"],"Life indicators."),
    make_q(18,"Enceladus (moon of Saturn) is interesting for astrobiology because:",["It's warm","*Its geysers shoot water ice into space, suggesting a subsurface ocean with hydrothermal activity","It has an atmosphere","It's the largest moon"],"Active geology."),
    make_q(19,"The Drake Equation estimates:",["The age of the universe","*The number of technologically advanced civilizations in our galaxy (combining astronomical and biological factors)","The size of the universe","The number of stars"],"Civilization estimate."),
    make_q(20,"Understanding biology on Earth helps astrobiology because:",["Earth life is irrelevant","*Earth's extremophiles, biochemistry, and evolutionary history teach us what to look for and where life might survive elsewhere","Only chemical analysis matters","Only physics matters"],"Earth as model."),
],
}

with open(PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

count = 0
for key, extra_qs in EXTRA.items():
    if key in data:
        existing = data[key].get("quiz_questions", [])
        start_num = len(existing) + 1
        for i, q in enumerate(extra_qs):
            q["question_number"] = start_num + i
        data[key]["quiz_questions"] = existing + extra_qs
        count += 1

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"✅ Biology U9-U12: expanded {count} lessons to 20 questions each")
