#!/usr/bin/env python3
"""Replace placeholder questions in Linear Algebra U7-U8 with real questions."""
import json, os

PATH = os.path.join("content_data", "linear_algebra_lessons.json")

QUESTIONS = {
# ── U7: Eigenvalues & Eigenvectors ──
"u7_l7.1": [  # Characteristic Polynomial
    ("What is the characteristic polynomial of a matrix A?", ["det(A − I)", "det(A + λI)", "det(A − λI)", "det(λA − I)"], 2, "The characteristic polynomial is det(A − λI), set equal to zero to find eigenvalues."),
    ("For a 2×2 matrix, the characteristic polynomial has degree:", ["1", "2", "3", "4"], 1, "A 2×2 matrix yields a quadratic characteristic polynomial."),
    ("The roots of the characteristic polynomial are the matrix's:", ["determinants", "traces", "eigenvalues", "pivots"], 2, "Setting det(A − λI) = 0 and solving gives the eigenvalues."),
    ("For A = [[3,1],[0,2]], det(A − λI) equals:", ["(3−λ)(2−λ)", "(3+λ)(2+λ)", "λ² − 5λ + 7", "λ² + 5λ + 6"], 0, "det([[3−λ,1],[0,2−λ]]) = (3−λ)(2−λ) − 0 = (3−λ)(2−λ)."),
    ("The trace of a matrix equals the _____ of the characteristic polynomial's roots.", ["product", "sum", "difference", "minimum"], 1, "The trace equals the sum of eigenvalues (roots of the characteristic polynomial)."),
    ("The determinant of a matrix equals the _____ of all eigenvalues.", ["sum", "product", "average", "maximum"], 1, "det(A) = λ₁·λ₂·…·λₙ."),
    ("If A is 3×3, its characteristic polynomial is degree:", ["1", "2", "3", "4"], 2, "An n×n matrix has a degree-n characteristic polynomial."),
    ("The characteristic polynomial of the identity matrix I₂ is:", ["λ² − 1", "(1 − λ)²", "λ² + 1", "(λ − 2)²"], 1, "det(I − λI) = det((1−λ)I) = (1−λ)²."),
    ("A matrix with characteristic polynomial λ² − 5λ + 6 has eigenvalues:", ["1 and 6", "2 and 3", "−2 and −3", "5 and 1"], 1, "λ² − 5λ + 6 = (λ−2)(λ−3), so λ = 2, 3."),
    ("Repeated roots in the characteristic polynomial indicate:", ["no eigenvalues exist", "the matrix is invertible", "an eigenvalue with algebraic multiplicity > 1", "the matrix is zero"], 2, "A repeated root means that eigenvalue appears more than once."),
    ("The coefficient of λⁿ⁻¹ in the characteristic polynomial relates to:", ["the determinant", "the trace (with a sign factor)", "the rank", "the nullity"], 1, "The λⁿ⁻¹ coefficient equals (−1)¹·trace(A) for the standard form."),
    ("The constant term of the characteristic polynomial equals:", ["trace(A)", "rank(A)", "det(A) up to sign", "zero always"], 2, "Evaluating at λ=0 gives det(A) (possibly with a sign factor)."),
    ("The Cayley-Hamilton theorem states every matrix satisfies:", ["its transpose equation", "its own characteristic polynomial", "the identity equation", "the zero polynomial only"], 1, "Every square matrix satisfies its own characteristic equation."),
    ("For a diagonal matrix diag(4, 7), the characteristic polynomial is:", ["(λ−4)(λ+7)", "(4−λ)(7−λ)", "λ²−3λ+28", "(λ+4)(λ−7)"], 1, "Each diagonal entry gives a factor (entry − λ)."),
    ("If λ=0 is a root of the characteristic polynomial, the matrix is:", ["orthogonal", "symmetric", "singular (non-invertible)", "diagonal"], 2, "λ=0 means det(A)=0, so A is singular."),
    ("The characteristic polynomial is unchanged by:", ["row reduction", "scaling by 2", "similarity transformations P⁻¹AP", "adding the identity"], 2, "Similar matrices share the same characteristic polynomial."),
    ("For a triangular matrix, eigenvalues are:", ["all zero", "all ones", "the diagonal entries", "impossible to determine"], 2, "det(A−λI) for triangular matrices factors directly from the diagonal."),
    ("A 4×4 matrix can have at most _____ distinct eigenvalues.", ["2", "3", "4", "8"], 2, "At most n distinct eigenvalues for an n×n matrix."),
    ("The characteristic polynomial of A and Aᵀ are:", ["unrelated", "identical", "negatives of each other", "reciprocals of each other"], 1, "det(A−λI) = det(Aᵀ−λI) since det equals det of transpose."),
    ("Computing the characteristic polynomial of a large matrix is typically done using:", ["hand expansion", "Gaussian elimination", "numerical algorithms like QR iteration", "Cramer's rule"], 2, "Direct polynomial computation is unstable; iterative methods are preferred."),
],
"u7_l7.2": [  # Finding Eigenvalues
    ("To find eigenvalues, solve:", ["Ax = b", "det(A − λI) = 0", "A + λI = 0", "rank(A) = n"], 1, "Eigenvalues satisfy the characteristic equation det(A − λI) = 0."),
    ("The eigenvalues of A = [[5,0],[0,3]] are:", ["5 and 0", "0 and 3", "5 and 3", "8 and 15"], 2, "Diagonal entries are the eigenvalues of a diagonal matrix."),
    ("A real symmetric matrix always has:", ["complex eigenvalues", "zero eigenvalues", "real eigenvalues", "negative eigenvalues"], 2, "Real symmetric matrices have all real eigenvalues (spectral theorem)."),
    ("If A has eigenvalue λ, then A² has eigenvalue:", ["2λ", "λ/2", "λ²", "√λ"], 2, "If Ax = λx, then A²x = A(λx) = λ(Ax) = λ²x."),
    ("The eigenvalues of A⁻¹ are:", ["the same as A's", "negatives of A's eigenvalues", "reciprocals of A's eigenvalues", "squares of A's eigenvalues"], 2, "If Ax = λx, then A⁻¹x = (1/λ)x."),
    ("A matrix with eigenvalues 2, 3, 5 has trace:", ["30", "10", "6", "0"], 1, "Trace = sum of eigenvalues = 2+3+5 = 10."),
    ("A matrix with eigenvalues 2, 3, 5 has determinant:", ["10", "30", "15", "6"], 1, "det = product of eigenvalues = 2·3·5 = 30."),
    ("Eigenvalues of a skew-symmetric real matrix are:", ["all real nonzero", "all positive", "purely imaginary or zero", "all equal to 1"], 2, "Skew-symmetric matrices have purely imaginary eigenvalues (or zero)."),
    ("If λ is an eigenvalue of A, then λ+3 is an eigenvalue of:", ["3A", "A³", "A + 3I", "A − 3I"], 2, "(A+3I)x = Ax + 3x = λx + 3x = (λ+3)x."),
    ("The algebraic multiplicity of an eigenvalue is:", ["the eigenspace dimension", "its value squared", "its multiplicity as a root of the characteristic polynomial", "always exactly 1"], 2, "Algebraic multiplicity = how many times the root repeats in the polynomial."),
    ("Geometric multiplicity of an eigenvalue equals:", ["the algebraic multiplicity always", "the dimension of null(A−λI)", "the rank of A", "the trace of A"], 1, "Geometric multiplicity = dim(null(A−λI))."),
    ("Geometric multiplicity is always ≤ algebraic multiplicity, so:", ["they must be equal", "the eigenspace can be smaller than the root count", "the eigenspace is always larger", "multiplicity is irrelevant"], 1, "The eigenspace dimension cannot exceed the root multiplicity."),
    ("A matrix with all eigenvalues equal to 1 has determinant:", ["0", "1", "n", "−1"], 1, "Product of all eigenvalues = 1·1·…·1 = 1."),
    ("If A is nilpotent (Aᵏ = 0 for some k), its eigenvalues are:", ["all 1", "all positive", "all zero", "undefined"], 2, "If Ax = λx, then Aᵏx = λᵏx = 0, so λ = 0."),
    ("An idempotent matrix (A² = A) has eigenvalues from the set:", ["{−1, 1}", "{0, 1}", "{0, −1}", "{1, 2}"], 1, "A²x = Ax gives λ² = λ, so λ(λ−1) = 0, meaning λ = 0 or 1."),
    ("The eigenvalues of an orthogonal matrix have absolute value:", ["0", "1", "equal to n", "equal to the trace"], 1, "Orthogonal matrices preserve length, so |λ| = 1."),
    ("Shifting A by cI changes each eigenvalue by:", ["multiplying by c", "adding c", "squaring it", "no change at all"], 1, "(A+cI)x = (λ+c)x."),
    ("To verify λ is an eigenvalue: check that A − λI is:", ["invertible", "symmetric", "singular (det = 0)", "diagonal"], 2, "λ is an eigenvalue ⟺ det(A−λI) = 0 ⟺ A−λI is singular."),
    ("A positive definite matrix has eigenvalues that are all:", ["zero", "negative", "positive", "complex"], 2, "Positive definite ⟺ all eigenvalues > 0."),
    ("The power method iteratively approximates the _____ eigenvalue.", ["smallest", "median", "dominant (largest magnitude)", "closest to zero"], 2, "The power method converges to the eigenvalue with largest absolute value."),
],
"u7_l7.3": [  # Finding Eigenvectors
    ("An eigenvector of A for eigenvalue λ satisfies:", ["Ax = 0", "(A − λI)x = 0 with x ≠ 0", "Ax = x for any x", "x = λA"], 1, "Eigenvectors are nonzero vectors in null(A − λI)."),
    ("To find eigenvectors, you row-reduce:", ["A itself", "A + λI", "A − λI", "A²"], 2, "Row reduce A − λI and find the null space."),
    ("The zero vector is:", ["always an eigenvector", "never an eigenvector", "an eigenvector for λ=0 only", "sometimes an eigenvector"], 1, "By definition, eigenvectors must be nonzero."),
    ("If v is an eigenvector with eigenvalue λ, then 3v has eigenvalue:", ["3λ", "λ/3", "λ", "9λ"], 2, "A(3v) = 3(Av) = 3(λv) = λ(3v). Same eigenvalue."),
    ("The eigenspace for eigenvalue λ is:", ["a single vector", "null(A − λI)", "the column space of A", "the row space of A"], 1, "The eigenspace is the null space of A − λI (plus the zero vector)."),
    ("For A = [[2,0],[0,5]], the eigenvector for λ=5 is (up to scaling):", ["[1, 0]", "[0, 1]", "[1, 1]", "[2, 5]"], 1, "(A−5I)x = [[-3,0],[0,0]]x = 0 gives x = [0,1]."),
    ("Two eigenvectors for distinct eigenvalues are:", ["always parallel", "always equal", "linearly independent", "always orthogonal"], 2, "Eigenvectors for distinct eigenvalues are linearly independent."),
    ("The dimension of an eigenspace is called the:", ["algebraic multiplicity", "geometric multiplicity", "rank", "trace"], 1, "Geometric multiplicity = dim(eigenspace)."),
    ("If A has n linearly independent eigenvectors (n×n), A is:", ["singular", "diagonalizable", "nilpotent", "skew-symmetric"], 1, "n independent eigenvectors ⟺ A is diagonalizable."),
    ("For a 3×3 matrix with eigenvalue λ of algebraic multiplicity 2, the eigenspace dimension is:", ["always 2", "always 1", "either 1 or 2", "always 3"], 2, "Geometric multiplicity can be 1 or 2 (≤ algebraic multiplicity)."),
    ("Eigenvectors of a real symmetric matrix for different eigenvalues are:", ["parallel", "anti-parallel", "orthogonal", "equal in magnitude"], 2, "Symmetric matrices have orthogonal eigenvectors for distinct eigenvalues."),
    ("Free variables in the row-reduction of A−λI correspond to:", ["eigenvalues", "eigenvector components to choose freely", "zero eigenvalues", "pivot columns"], 1, "Free variables parameterize the eigenspace."),
    ("If A − 3I row-reduces to [[1,−2,0],[0,0,0],[0,0,0]], the eigenspace for λ=3 has dimension:", ["1", "2", "3", "0"], 1, "Two free variables (columns 2, 3) → 2D eigenspace."),
    ("A defective matrix has:", ["no eigenvalues at all", "too many eigenvectors", "fewer independent eigenvectors than algebraic multiplicity indicates", "only real eigenvalues"], 2, "Defective: geometric multiplicity < algebraic multiplicity for some eigenvalue."),
    ("The matrix [[2,1],[0,2]] has eigenvalue 2 with algebraic multiplicity 2. Its geometric multiplicity is:", ["2", "1", "0", "3"], 1, "(A−2I) = [[0,1],[0,0]] has rank 1, so nullity = 1."),
    ("If Ax = 3x and Ay = 3y, then A(x+y) equals:", ["6(x+y)", "3x + 3y = 3(x+y)", "9(x+y)", "zero"], 1, "A(x+y) = Ax + Ay = 3x + 3y = 3(x+y)."),
    ("To check if v = [1,2] is an eigenvector of A, compute Av and see if:", ["Av = 0", "Av = cv for some scalar c", "Av = v + A", "Av has unit length"], 1, "Av = λv for some scalar λ."),
    ("In NumPy, eigenvectors are computed using:", ["np.det(A)", "np.linalg.inv(A)", "np.linalg.eig(A)", "np.rank(A)"], 2, "eig() returns both eigenvalues and eigenvectors."),
    ("Generalized eigenvectors satisfy (A − λI)ᵏv = 0 and are used when:", ["the matrix is symmetric", "the matrix is defective", "all eigenvalues are distinct", "the matrix is diagonal"], 1, "Generalized eigenvectors fill in when ordinary eigenvectors are insufficient."),
    ("The set of all eigenvectors for a given eigenvalue, together with 0, forms:", ["a matrix", "a subspace (the eigenspace)", "a single line only", "the entire space Rⁿ"], 1, "Eigenspaces are subspaces of the vector space."),
],
"u7_l7.4": [  # Diagonalization
    ("A matrix A is diagonalizable if:", ["A is symmetric", "P⁻¹AP = D for some invertible P and diagonal D", "A has full rank", "A is triangular"], 1, "Definition: A = PDP⁻¹ with D diagonal."),
    ("The columns of P in A = PDP⁻¹ are:", ["eigenvalues of A", "eigenvectors of A", "rows of D", "columns of A⁻¹"], 1, "P is formed by placing eigenvectors as columns."),
    ("The diagonal entries of D are:", ["the eigenvectors", "the eigenvalues", "the pivots", "the singular values"], 1, "D = diag(λ₁, λ₂, …, λₙ)."),
    ("A 3×3 matrix with 3 distinct eigenvalues is:", ["always singular", "always diagonalizable", "never diagonalizable", "always symmetric"], 1, "Distinct eigenvalues guarantee n independent eigenvectors."),
    ("Diagonalization simplifies computing Aⁿ because:", ["Aⁿ = nA", "Aⁿ = PDⁿP⁻¹ (raise diagonal entries to nth power)", "Aⁿ = DⁿP", "Aⁿ doesn't simplify"], 1, "Aⁿ = PDⁿP⁻¹, and Dⁿ = diag(λ₁ⁿ, λ₂ⁿ, …)."),
    ("A real matrix with complex eigenvalues is diagonalizable over:", ["the reals always", "the complex numbers", "no field", "only rationals"], 1, "It's diagonalizable over ℂ if geometric multiplicities equal algebraic."),
    ("The matrix [[3,1],[0,3]] is:", ["diagonalizable", "not diagonalizable (defective at λ=3)", "diagonalizable with distinct eigenvalues", "the identity matrix"], 1, "Eigenvalue 3 has algebraic mult 2 but geometric mult 1."),
    ("If A is diagonalizable, the matrix exponential eᴬ equals:", ["PeᴰP⁻¹", "eᵈᵉᵗ⁽ᴬ⁾·I", "A·eᴬ", "I + A"], 0, "eᴬ = PeᴰP⁻¹ with diagonal entries exponentiated."),
    ("An orthogonally diagonalizable matrix must be:", ["any square matrix", "real and symmetric", "invertible and triangular", "upper triangular"], 1, "The spectral theorem: real symmetric ⟺ orthogonally diagonalizable."),
    ("For orthogonal diagonalization A = QDQᵀ, Q satisfies:", ["Q² = I", "QᵀQ = I (orthogonal)", "Q = D", "Q = A"], 1, "Q is orthogonal: QᵀQ = QQᵀ = I."),
    ("If D = diag(2,5), then D¹⁰ equals:", ["diag(20, 50)", "diag(1024, 9765625)", "diag(2, 5)", "diag(10, 10)"], 1, "2¹⁰ = 1024, 5¹⁰ = 9765625."),
    ("Diagonalization fails when:", ["eigenvalues are distinct", "the matrix has full rank", "geometric multiplicity < algebraic multiplicity", "the matrix is symmetric"], 2, "Not enough independent eigenvectors → not diagonalizable."),
    ("Similar matrices (B = P⁻¹AP) share:", ["the same eigenvectors", "the same entries", "the same eigenvalues, trace, and determinant", "the same inverse"], 2, "Similar matrices share characteristic polynomial, eigenvalues, trace, det."),
    ("The Jordan normal form generalizes diagonalization for:", ["all invertible matrices", "defective matrices", "only 2×2 matrices", "symmetric matrices only"], 1, "Jordan form handles cases where diagonalization is impossible."),
    ("To diagonalize A = [[4,2],[1,3]], first solve:", ["det(A) = 0", "det(A−λI) = 0 → (4−λ)(3−λ)−2 = 0", "trace(A) = 0", "A − I = 0"], 1, "Expand det(A−λI) and solve for λ."),
    ("If eigenvalues are λ=2 and λ=5, D equals:", ["[[2,5],[0,0]]", "[[2,0],[0,5]]", "[[5,0],[0,2]]", "either [[2,0],[0,5]] or [[5,0],[0,2]]"], 3, "Order of diagonal entries matches order of columns in P."),
    ("A diagonal matrix raised to any power is computed by:", ["multiplying all entries together", "raising only diagonal entries to that power", "adding the power to each entry", "taking the transpose"], 1, "diag(a,b)ⁿ = diag(aⁿ, bⁿ)."),
    ("A diagonalizable matrix with eigenvalues on the unit circle has:", ["divergent powers", "bounded powers (||Aⁿ|| stays finite)", "zero powers after some n", "increasing eigenvalues"], 1, "If |λᵢ|=1, then |λᵢⁿ|=1 for all n."),
    ("How many distinct P matrices diagonalize a given A?", ["exactly one", "exactly zero", "infinitely many", "exactly n"], 2, "Eigenvectors can be scaled and reordered freely."),
    ("Simultaneous diagonalization of A and B requires:", ["A = B", "A and B commute and both are diagonalizable", "only that A is diagonal", "A and B are both singular"], 1, "Commuting diagonalizable matrices share an eigenbasis."),
],
"u7_l7.5": [  # Applications in Differential Equations
    ("The system dx/dt = Ax is solved using:", ["simple integration", "eigenvalues and eigenvectors of A", "the determinant only", "row reduction of Ax=b"], 1, "The general solution involves eλt times eigenvectors."),
    ("If A has eigenvalue λ with eigenvector v, one solution to dx/dt = Ax is:", ["x(t) = λv", "x(t) = eλᵗv", "x(t) = cos(λt)v", "x(t) = v/t"], 1, "Each eigenvalue-eigenvector pair gives x(t) = ceλᵗv."),
    ("For x′ = Ax with A diagonalizable, the general solution is:", ["x = Av", "x(t) = c₁eλ₁ᵗv₁ + c₂eλ₂ᵗv₂ + …", "x(t) = eᵗA always", "x(t) = A⁻¹b"], 1, "Superposition of eigenmode solutions."),
    ("A system with all negative eigenvalues has solutions that:", ["oscillate forever", "grow exponentially", "decay to zero", "remain constant"], 2, "Negative real eigenvalues → eλᵗ → 0 as t → ∞."),
    ("A positive eigenvalue indicates the corresponding mode:", ["decays to zero", "stays constant", "grows exponentially", "oscillates"], 2, "eλᵗ grows when λ > 0."),
    ("Complex eigenvalues α ± βi produce solutions involving:", ["pure exponential growth", "pure exponential decay", "oscillation modulated by eαᵗ", "constant functions"], 2, "eαᵗ(cos βt + i sin βt) → oscillation modulated by eαt."),
    ("The matrix exponential eᴬᵗ represents:", ["a single eigenvalue", "the fundamental solution matrix for dx/dt = Ax", "the inverse of A", "the determinant function"], 1, "eᴬᵗ maps x(0) to x(t): x(t) = eᴬᵗx(0)."),
    ("The equilibrium x = 0 is a stable node when eigenvalues are:", ["both positive real", "both negative real", "complex with positive real part", "both zero"], 1, "Negative real eigenvalues → all solutions approach 0."),
    ("A saddle point occurs when eigenvalues are:", ["both positive", "both negative", "one positive and one negative", "both zero"], 2, "Opposite-sign eigenvalues → attraction in one direction, repulsion in another."),
    ("A spiral occurs when eigenvalues are:", ["real and distinct", "real and equal", "complex with nonzero real part", "purely imaginary"], 2, "Complex with Re ≠ 0 → oscillation spiraling in or out."),
    ("A center (neutrally stable orbit) occurs when eigenvalues are:", ["real positive", "purely imaginary (±βi)", "real negative", "zero"], 1, "Purely imaginary → closed orbits, no growth or decay."),
    ("Phase portraits show:", ["eigenvalue magnitudes", "trajectories of solutions in the state space", "the characteristic polynomial", "individual matrix entries"], 1, "Phase portraits show how solution curves evolve in the plane."),
    ("For the system x′=2x, y′=−3y, eigenvalues are:", ["2 and 3", "2 and −3", "−2 and 3", "−2 and −3"], 1, "Diagonal system: coefficients are the eigenvalues."),
    ("An eigenvalue of 0 means that mode:", ["grows exponentially", "decays exponentially", "remains constant", "oscillates"], 2, "e⁰ᵗ = 1 → the mode neither grows nor decays."),
    ("Diagonalizing the system decouples it into:", ["one complicated equation", "independent scalar equations for each variable", "a nonlinear system", "an unsolvable system"], 1, "Change of variables → each new variable evolves independently."),
    ("In predator-prey models, eigenvalue analysis predicts:", ["exact population counts", "equilibrium stability and oscillation patterns", "individual animal behavior", "extinction always"], 1, "Eigenvalues determine whether equilibria are stable/unstable/oscillatory."),
    ("A repeated eigenvalue with only one eigenvector produces solutions with:", ["only eλᵗ terms", "both eλᵗ and teλᵗ terms", "sin and cos terms only", "polynomial terms only"], 1, "Defective eigenvalue → teλᵗ (secular term) appears."),
    ("The trace of A determines the sum of:", ["eigenvalue products", "eigenvalue real parts", "all matrix entries", "diagonal products"], 1, "trace(A) = Σλᵢ."),
    ("Stiffness in ODE systems means eigenvalues have:", ["similar magnitudes", "vastly different magnitudes", "all zero values", "identical values"], 1, "Stiff systems require special numerical methods due to the wide eigenvalue spread."),
    ("Using diagonalization, eᴬᵗ can be computed as:", ["eᴰ", "Pdiag(eλ₁ᵗ, eλ₂ᵗ, …)P⁻¹", "eᵗʳᵃᶜᵉ·I", "I + At"], 1, "eᴬᵗ = Pdiag(eλ₁ᵗ, eλ₂ᵗ, …)P⁻¹."),
],
"u7_l7.6": [  # Applications in Physics
    ("In quantum mechanics, observable quantities are represented by:", ["any random matrix", "Hermitian operators", "the zero operator", "diagonal matrices only"], 1, "Physical observables correspond to Hermitian operators with real eigenvalues."),
    ("Measuring a quantum observable yields one of its:", ["eigenvectors", "eigenvalues", "matrix entries", "traces"], 1, "Measurement outcomes are eigenvalues of the corresponding operator."),
    ("The moment of inertia tensor's eigenvalues give:", ["angular velocities", "principal moments of inertia", "forces", "torques"], 1, "Diagonalizing the inertia tensor yields principal axes and principal moments."),
    ("Normal modes of coupled oscillators are found by:", ["differentiation", "solving the eigenvalue problem for the system matrix", "Fourier transforms alone", "setting forces to zero"], 1, "Each eigenvalue gives a normal frequency; each eigenvector gives the mode shape."),
    ("In a coupled spring system, eigenvalues correspond to:", ["spring constants directly", "squared angular frequencies of normal modes", "damping rates", "spring lengths"], 1, "ω² values come from the eigenvalue equation Kx = ω²Mx."),
    ("The stress tensor's eigenvalues are called:", ["shear moduli", "principal stresses", "Young's moduli", "Poisson ratios"], 1, "Diagonalizing the stress tensor gives principal stresses and directions."),
    ("Lorentz transformations in special relativity act on:", ["scalars only", "4-vectors in spacetime", "2D vectors", "temperature"], 1, "Lorentz boosts and rotations act on 4-vectors via matrix multiplication."),
    ("Diagonalizing the Hamiltonian matrix yields:", ["position eigenstates", "energy eigenvalues and eigenstates", "momentum only", "spin direction"], 1, "H|ψ> = E|ψ>; diagonalizing H gives energy levels."),
    ("Degeneracy means multiple eigenstates share:", ["different eigenvalues", "the same eigenvalue (energy level)", "the same eigenvector", "zero energy"], 1, "Degenerate eigenvalue = multiple independent states at the same energy."),
    ("In the diffusion equation, eigenvalues of the Laplacian determine:", ["boundary shape", "how fast each spatial mode decays or grows", "the material color", "the temperature unit"], 1, "Each eigenvalue gives the decay rate of its corresponding mode."),
    ("Maxwell's equations in matrix form yield eigenvalues related to:", ["electrical resistance", "wave propagation speeds", "mass", "gravitational constant"], 1, "Eigenvalue analysis gives wave speeds and polarization modes."),
    ("Equilibrium stability depends on the sign of:", ["the determinant only", "the eigenvalues of the linearized system matrix", "the trace only", "individual matrix entries"], 1, "Negative eigenvalues → stable; positive → unstable."),
    ("Coupled pendulums have normal modes because:", ["they swing independently", "the system matrix has independent eigenvectors", "friction decouples them", "only one pendulum moves"], 1, "Each eigenvector gives a mode where all parts oscillate at one frequency."),
    ("Electronic band structure in solids comes from:", ["classical mechanics alone", "eigenvalues of the crystal Hamiltonian", "chemical formulas", "basic algebra"], 1, "Band theory: eigenvalues of periodic Hamiltonians give energy bands."),
    ("Angular momentum eigenvalues in quantum mechanics are:", ["continuous", "quantized (discrete multiples of ℏ)", "always zero", "negative only"], 1, "Angular momentum is quantized: eigenvalues are mℏ."),
    ("Small oscillations are analyzed by:", ["exact nonlinear solution", "linearizing and finding eigenvalues", "ignoring the system", "setting frequency to zero"], 1, "Linearize around equilibrium → eigenvalues give normal frequencies."),
    ("A 3D rotation matrix has at least one eigenvalue equal to:", ["0", "−1", "1 (the rotation axis)", "2"], 2, "Every 3D rotation has λ=1 corresponding to the rotation axis."),
    ("Eigenvalue perturbation theory predicts:", ["exact solutions usually", "how eigenvalues shift under small changes to the operator", "large-scale behavior only", "nothing useful"], 1, "Small changes to the operator → calculable shifts in eigenvalues."),
    ("The tensor of a physical quantity is diagonalized to find:", ["its determinant", "principal directions and principal values", "its trace", "its inverse"], 1, "Principal axes = eigenvectors; principal values = eigenvalues."),
    ("Resonance frequencies of a structure correspond to:", ["zero eigenvalues", "eigenvalues of the stiffness-mass system", "imaginary eigenvalues always", "the matrix rank"], 1, "ω² = eigenvalue of M⁻¹K gives the natural frequencies."),
],
"u7_l7.7": [  # Applications in Computer Science
    ("Google's PageRank models the web as a Markov chain whose _____ gives page importance.", ["determinant", "dominant eigenvector", "inverse matrix", "null space"], 1, "PageRank = dominant eigenvector of the web's stochastic matrix."),
    ("In PCA, eigenvectors of the covariance matrix represent:", ["data outliers", "principal directions of variance", "cluster centers", "random noise"], 1, "PCA finds directions (eigenvectors) of maximum variance."),
    ("The largest eigenvalue in PCA corresponds to the direction of:", ["minimum variance", "maximum variance", "zero variance", "the data mean"], 1, "First PC = direction capturing the most spread in the data."),
    ("Spectral clustering uses eigenvalues of the graph Laplacian to reveal:", ["edge weights directly", "cluster structure in the data", "shortest paths", "maximum flow"], 1, "Small eigenvalues of the Laplacian identify clusters."),
    ("The adjacency matrix spectrum of a graph encodes:", ["vertex labels", "structural properties like connectivity", "file sizes", "memory addresses"], 1, "Graph spectra encode deep structural information."),
    ("In recommendation systems, SVD extracts:", ["user passwords", "latent features from user-item matrices", "alphabetical orderings", "file metadata"], 1, "SVD reveals latent factors (e.g., genre preferences)."),
    ("The steady state of a Markov chain is the eigenvector for eigenvalue:", ["0", "1", "−1", "the smallest eigenvalue"], 1, "Stochastic matrices have λ=1 as the dominant eigenvalue."),
    ("Spectral graph theory studies graphs using:", ["visual inspection only", "eigenvalues of associated matrices", "brute-force enumeration", "random sampling only"], 1, "Eigenanalysis of adjacency and Laplacian matrices."),
    ("In image compression, eigenvalue decomposition helps by:", ["increasing file size", "keeping the most significant components only", "randomizing pixels", "rotating images"], 1, "Keep top eigenvalue components → lossy compression."),
    ("The condition number (ratio of largest to smallest singular value) measures:", ["matrix dimensions", "numerical sensitivity to errors", "the number of eigenvalues", "the trace value"], 1, "Large condition number → ill-conditioned → sensitive to perturbations."),
    ("The Fiedler vector (2nd-smallest Laplacian eigenvector) is used for:", ["finding shortest paths", "graph bipartitioning", "coloring problems", "matrix inversion"], 1, "The Fiedler vector gives an optimal spectral bipartition."),
    ("Eigenfaces in facial recognition use eigenvectors of:", ["the pixel array directly", "the covariance of face images", "random matrices", "user input data"], 1, "PCA on face images → eigenfaces."),
    ("The power iteration method computes:", ["all eigenvalues at once", "the dominant eigenpair", "the inverse matrix", "the determinant"], 1, "Repeatedly multiplying by A converges to the dominant eigenpair."),
    ("In control theory, system stability requires the eigenvalues of A to be:", ["positive", "in the left half-plane (negative real part)", "purely imaginary", "zero"], 1, "All eigenvalues with Re < 0 → stable linear system."),
    ("Spectral methods in numerical analysis use eigensolutions to:", ["generate random numbers", "simplify differential equations into algebraic ones", "sort data", "compress text"], 1, "Eigenfunctions of differential operators simplify PDE solutions."),
    ("Quantum Phase Estimation efficiently finds:", ["classical probabilities", "eigenvalues of unitary operators on a quantum computer", "graph colorings", "sorting orders"], 1, "QPE is a key quantum computing subroutine for eigenvalue estimation."),
    ("Algebraic connectivity (2nd smallest Laplacian eigenvalue) indicates:", ["the number of vertices", "how well-connected the graph is", "the number of edges exactly", "total edge weight"], 1, "Larger algebraic connectivity → more connected graph."),
    ("In data science, eigenvectors reduce dimensions by:", ["deleting random features", "projecting onto top eigenvectors of the covariance matrix", "averaging all columns", "duplicating features"], 1, "Project onto top-k eigenvectors."),
    ("Typical eigenvalue algorithm complexity is:", ["O(n)", "O(n²) to O(n³)", "O(1)", "O(2ⁿ)"], 1, "Standard dense eigensolvers run in O(n³)."),
    ("Power method convergence speed depends on:", ["matrix size alone", "the ratio |λ₂/λ₁| of the two largest eigenvalues", "the number of zero entries", "the trace value"], 1, "Smaller |λ₂/λ₁| → faster convergence."),
],
"u7_l7.8": [  # Applications in Economics
    ("The Leontief input-output model represents:", ["consumer preferences", "inter-industry production dependencies", "stock prices", "interest rates"], 1, "Each entry shows how much industry j supplies to industry i."),
    ("In the Leontief model, total output x satisfies:", ["x = Ax", "x = (I − A)⁻¹d where d is external demand", "x = A⁻¹", "x = d/A"], 1, "(I−A)⁻¹d gives total production to meet internal + external demand."),
    ("The economy is productive (Leontief model works) when the dominant eigenvalue of A is:", ["greater than 1", "less than 1", "exactly 1", "negative"], 1, "If λ_max < 1, then (I−A) is invertible and the model has a feasible solution."),
    ("Steady-state market shares in a brand-switching model are given by:", ["eigenvalues of the transition matrix", "the eigenvector for eigenvalue 1", "the smallest eigenvector", "random values"], 1, "Steady state = dominant eigenvector of the stochastic matrix."),
    ("Leslie population matrices use eigenvalues to predict:", ["individual lifespans", "long-term growth rates and age distributions", "GDP", "inflation rates"], 1, "Dominant eigenvalue = long-term growth factor."),
    ("A Leslie matrix with dominant eigenvalue 1.05 predicts:", ["5% decline per period", "5% growth per period", "zero growth", "immediate extinction"], 1, "λ > 1 → growth at rate (λ−1)×100%."),
    ("Covariance matrix eigenvalues in portfolio theory represent:", ["stock prices", "variances along principal risk directions", "dividend yields", "trading volumes"], 1, "Eigenvalues = principal component variances (risk directions)."),
    ("A discrete dynamical system x_{t+1} = Ax_t is stable when:", ["all |λᵢ| > 1", "all |λᵢ| < 1", "eigenvalues are complex", "the matrix is orthogonal"], 1, "|λᵢ| < 1 for all i → x_t → 0."),
    ("Perron-Frobenius theorem guarantees a positive matrix has:", ["no real eigenvalues", "a unique largest positive eigenvalue with positive eigenvector", "all negative eigenvalues", "zero determinant"], 1, "Positive matrices have a dominant positive eigenvalue with positive eigenvector."),
    ("In macroeconomics, eigenvalue analysis of IS-LM models studies:", ["individual purchases", "how quickly the economy adjusts toward equilibrium", "tax collection only", "trade routes"], 1, "Eigenvalues determine convergence speed to equilibrium."),
    ("Convergence to steady state in a Markov chain depends on:", ["matrix dimensions", "the second-largest eigenvalue magnitude", "only the largest eigenvalue", "the trace value"], 1, "Smaller |λ₂| → faster convergence."),
    ("Near-zero eigenvalues of XᵀX indicate:", ["perfect data quality", "multicollinearity among predictors", "no relationships", "orthogonal predictors"], 1, "Near-zero eigenvalues → nearly linearly dependent predictor variables."),
    ("The condition number of XᵀX measures:", ["dataset size", "sensitivity of regression coefficients to data perturbations", "the number of predictors", "the sample size"], 1, "Large condition number → unstable coefficient estimates."),
    ("The stable age distribution is proportional to:", ["the smallest eigenvector", "the dominant eigenvector of the Leslie matrix", "the identity vector", "the last column"], 1, "Long-term age distribution = normalized dominant eigenvector."),
    ("A shrinking economy has Leslie-model dominant eigenvalue:", ["greater than 1", "equal to 1", "between 0 and 1", "negative"], 2, "0 < λ₁ < 1 → the system declines over time."),
    ("Factor analysis identifies underlying latent factors using:", ["random selection", "eigenvectors of correlation matrices", "simple averages", "the determinant"], 1, "Eigenvectors of correlation reveal common factors."),
    ("Supply chain transition matrices are analyzed via eigenvalues to find:", ["product names", "long-run distribution of goods", "employee counts", "marketing costs"], 1, "Eigenanalysis reveals the long-run equilibrium."),
    ("Diagonalizable economic models are easier to solve because:", ["they can be ignored", "each variable can be analyzed independently after change of basis", "diagonalization deletes variables", "they become random"], 1, "Decoupling → independent scalar equations."),
    ("The payoff matrix in game theory can be analyzed using eigenvalues to find:", ["random strategies", "Nash equilibrium strategies in certain repeated games", "player names", "game duration"], 1, "Eigenanalysis helps find optimal mixed strategies."),
    ("Sensitivity analysis examines how eigenvalues (and outcomes) change when:", ["nothing changes", "model parameters are slightly perturbed", "the model is deleted", "time reverses"], 1, "Small parameter changes → how much do eigenvalues shift?"),
],

# ── U8: Orthogonality & Inner Product Spaces ──
"u8_l8.1": [  # Dot Product & Orthogonality
    ("The dot product of u = [1,2,3] and v = [4,5,6] is:", ["14", "32", "21", "9"], 1, "u·v = 1·4 + 2·5 + 3·6 = 4+10+18 = 32."),
    ("Two vectors are orthogonal when their dot product equals:", ["1", "their magnitudes", "0", "−1"], 2, "u·v = 0 defines orthogonality."),
    ("The dot product u·v can also be written as:", ["uᵀv", "u×v", "det([u,v])", "u+v"], 0, "u·v = uᵀv (row times column = scalar)."),
    ("||v|| (the norm) equals:", ["v·v", "√(v·v)", "Σ|vᵢ|", "max|vᵢ|"], 1, "||v|| = √(v₁² + v₂² + … + vₙ²) = √(v·v)."),
    ("cos θ between u and v equals:", ["u·v", "u·v / ||u||", "u·v / (||u|| · ||v||)", "||u|| · ||v||"], 2, "cos θ = u·v / (||u|| ||v||)."),
    ("If u·v > 0, the angle between them is:", ["exactly 90°", "acute (between 0° and 90°)", "obtuse (between 90° and 180°)", "exactly 180°"], 1, "Positive dot product → acute angle."),
    ("An orthogonal set of nonzero vectors is automatically:", ["spanning", "a basis for the whole space", "linearly independent", "orthonormal"], 2, "Nonzero orthogonal vectors are always linearly independent."),
    ("An orthonormal set has vectors that are:", ["orthogonal with unit length", "parallel with unit length", "orthogonal with arbitrary length", "all of length 2"], 0, "Orthonormal = pairwise orthogonal + each ||v|| = 1."),
    ("The standard basis {e₁, e₂, …, eₙ} is:", ["orthogonal only", "not orthogonal", "orthonormal", "linearly dependent"], 2, "eᵢ · eⱼ = δᵢⱼ."),
    ("W⊥ consists of all vectors orthogonal to:", ["a single vector in W", "every vector in W", "the zero vector only", "vectors outside W"], 1, "W⊥ = {v : v·w = 0 for all w ∈ W}."),
    ("dim(W) + dim(W⊥) equals:", ["dim(W)", "0", "n (dimension of the ambient space)", "2·dim(W)"], 2, "Fundamental relationship: dimensions add to n."),
    ("The dot product satisfies u·v = v·u, which means it is:", ["antisymmetric", "commutative", "distributive only", "undefined for some vectors"], 1, "u·v = v·u for real vectors."),
    ("|u·v| ≤ ||u||·||v|| is called:", ["the triangle inequality", "the Cauchy-Schwarz inequality", "the parallelogram law", "Bessel's inequality"], 1, "Cauchy-Schwarz bounds the dot product by the product of norms."),
    ("||u + v|| ≤ ||u|| + ||v|| is called:", ["Cauchy-Schwarz", "the triangle inequality", "Bessel's inequality", "the parallelogram law"], 1, "Vector version of 'shortest distance is a straight line.'"),
    ("The projection of v onto the line through u is:", ["v − u", "(v·u / u·u) · u", "v × u", "u / ||v||"], 1, "proj_u(v) = (v·u / u·u)u."),
    ("v − proj_u(v) is _____ to u.", ["parallel", "orthogonal", "equal", "antiparallel"], 1, "The residual after projection is perpendicular to u."),
    ("The dot product defines a(n) _____ on Rⁿ.", ["matrix product", "inner product", "cross product", "outer product"], 1, "The standard dot product is the canonical inner product on Rⁿ."),
    ("Work W = F·d uses the dot product because:", ["it gives a vector", "it extracts the force component along displacement", "it doubles the force", "it rotates the force"], 1, "W = |F||d|cos θ = F·d."),
    ("The zero vector is orthogonal to:", ["only itself", "no vector at all", "every vector", "only nonzero vectors"], 2, "0·v = 0 for all v."),
    ("If {u₁,u₂,u₃} is orthonormal and v = 3u₁ − 2u₂ + u₃, then ||v|| =:", ["√14", "√6", "6", "2"], 0, "||v||² = 9+4+1 = 14, so ||v|| = √14."),
],
"u8_l8.2": [  # Orthogonal Projections
    ("The orthogonal projection of v onto W gives the vector in W:", ["farthest from v", "closest to v", "perpendicular to v", "with largest norm"], 1, "Projection minimizes ||v − ŵ|| over all ŵ ∈ W."),
    ("If W = span{u₁,u₂} with orthogonal u₁, u₂, then proj_W(v) =", ["(v·u₁)u₁ + (v·u₂)u₂", "(v·u₁/u₁·u₁)u₁ + (v·u₂/u₂·u₂)u₂", "v − u₁ − u₂", "u₁ + u₂"], 1, "Sum of projections onto each orthogonal basis vector."),
    ("The error e = v − proj_W(v) is:", ["in W", "orthogonal to W", "always zero", "parallel to v"], 1, "The residual is in W⊥."),
    ("A projection matrix P satisfies P² =:", ["2P", "P", "I", "0"], 1, "Idempotent: projecting twice gives the same result."),
    ("For orthonormal columns Q, the projection matrix is:", ["QᵀQ", "QQᵀ", "Q⁻¹", "(QᵀQ)⁻¹"], 1, "P = QQᵀ."),
    ("Least squares solves the normal equation:", ["Ax = b", "AᵀAx̂ = Aᵀb", "x = A⁻¹b", "Ax̂ = 0"], 1, "Projects b onto Col(A)."),
    ("The least squares solution minimizes:", ["||x̂||", "||Ax̂ − b||²", "||A||", "det(AᵀA)"], 1, "Minimizes the squared residual."),
    ("If A has orthonormal columns, AᵀA equals:", ["A", "0", "I", "A²"], 2, "Orthonormal columns → AᵀA = I."),
    ("The hat matrix H = A(AᵀA)⁻¹Aᵀ projects onto:", ["null(A)", "Col(A)", "Row(A)", "null(Aᵀ)"], 1, "H maps b to its projection in the column space."),
    ("Projection matrices are:", ["always invertible", "symmetric and idempotent", "skew-symmetric", "always orthogonal"], 1, "P = Pᵀ and P² = P."),
    ("Eigenvalues of a projection matrix are:", ["arbitrary reals", "only 0 and/or 1", "always all 1", "always negative"], 1, "P² = P → λ² = λ → λ = 0 or 1."),
    ("Projecting v onto a line through u gives a scalar multiple of:", ["v", "u", "v−u", "v+u"], 1, "The result is always in the direction of u."),
    ("In linear regression, ŷ is the projection of y onto:", ["the x-axis", "Col([1|x]) (the column space of the design matrix)", "null(X)", "any random subspace"], 1, "Least squares = projection onto the column space."),
    ("The residual vector b − Ax̂ is orthogonal to:", ["b itself", "every column of A", "the first column only", "x̂"], 1, "Aᵀ(b−Ax̂) = 0."),
    ("If v is already in W, then proj_W(v) =:", ["0", "v", "v/2", "2v"], 1, "Projecting a vector already in the subspace returns it unchanged."),
    ("If v ⊥ W, then proj_W(v) =:", ["v", "v/||v||", "0", "−v"], 2, "No component in W → projection is the zero vector."),
    ("Fourier coefficients are essentially:", ["derivatives", "inner products with basis functions (projections)", "random weights", "matrix entries"], 1, "cₖ = <f, eₖ> / <eₖ, eₖ>."),
    ("The projection onto W⊥ is given by:", ["P_W", "I − P_W", "P_W²", "P_Wᵀ"], 1, "Complementary projection."),
    ("Every v decomposes as v = proj_W(v) + (v − proj_W(v)) with the two parts:", ["parallel", "orthogonal", "equal", "opposite"], 1, "W-component ⊥ W⊥-component."),
    ("QR factorization helps solve least squares because:", ["it eliminates A", "Rx̂ = Qᵀb avoids forming AᵀA (more stable)", "it's always slower", "Q is diagonal"], 1, "QR avoids AᵀA, reducing numerical error."),
],
"u8_l8.3": [  # Gram-Schmidt Process
    ("Gram-Schmidt takes linearly independent vectors and produces:", ["a diagonal matrix", "an orthogonal set spanning the same subspace", "eigenvalues", "a triangular matrix"], 1, "Gram-Schmidt orthogonalizes while preserving the span."),
    ("The first step: u₁ =:", ["v₁ + v₂", "v₁ (keep as-is)", "v₂ − v₁", "v₁/||v₂||"], 1, "Take the first vector directly."),
    ("u₂ = v₂ − proj_{u₁}(v₂) removes the component of v₂ that is:", ["orthogonal to u₁", "in the direction of u₁", "perpendicular to v₂", "in a random direction"], 1, "Subtract the part along u₁ to make u₂ ⊥ u₁."),
    ("After Gram-Schmidt, the resulting vectors are:", ["pairwise orthogonal, same span", "automatically unit length", "linearly dependent", "parallel"], 0, "Orthogonal; normalize separately for orthonormal."),
    ("To make the output orthonormal, divide each uᵢ by:", ["its dot product with v", "its norm ||uᵢ||", "n (the dimension)", "its first entry"], 1, "qᵢ = uᵢ/||uᵢ||."),
    ("Gram-Schmidt on 3 input vectors produces at most:", ["1 orthogonal vector", "2 orthogonal vectors", "3 orthogonal vectors", "6 orthogonal vectors"], 2, "One output per input."),
    ("If the inputs are already orthogonal, Gram-Schmidt:", ["fails", "changes them significantly", "leaves them unchanged", "reverses their order"], 2, "Projection terms vanish."),
    ("Gram-Schmidt is the constructive proof behind:", ["the spectral theorem", "QR factorization", "the rank-nullity theorem", "Cramer's rule"], 1, "Apply Gram-Schmidt to A's columns → Q and R."),
    ("In A = QR, Q's columns are _____ and R encodes _____.", ["eigenvectors; eigenvalues", "orthonormal vectors; projection coefficients", "random vectors; residuals", "pivot columns; free variables"], 1, "Q = orthonormalized columns; R = upper triangular of inner products."),
    ("Classical Gram-Schmidt can suffer from:", ["producing extra vectors", "numerical instability from round-off errors", "always wrong results", "requiring complex numbers"], 1, "Floating-point errors accumulate and destroy orthogonality."),
    ("Modified Gram-Schmidt improves stability by:", ["using a different mathematical formula", "projecting sequentially rather than all at once", "requiring complex arithmetic", "skipping normalization"], 1, "Sequential subtraction reduces error accumulation."),
    ("If Gram-Schmidt yields a zero vector at step k, the inputs were:", ["orthogonal", "linearly dependent", "orthonormal", "all unit vectors"], 1, "vₖ was a linear combination of v₁,…,vₖ₋₁."),
    ("Gram-Schmidt on an m×n matrix (full column rank) gives:", ["A = LU", "A = QR (Q has orthonormal columns, R is upper triangular)", "A = PDP⁻¹", "A = UΣVᵀ"], 1, "QR decomposition."),
    ("R is upper triangular because:", ["Q is orthogonal", "each step only uses previously computed vectors", "it's a coincidence", "R is always diagonal"], 1, "Step k only projects onto u₁,…,uₖ₋₁ → upper triangular structure."),
    ("Gram-Schmidt works in:", ["only R²", "only R³", "any inner product space", "only finite dimensions"], 2, "The process works wherever you have an inner product (including function spaces)."),
    ("Applying Gram-Schmidt to {1, x, x²} on [−1,1] yields (up to scaling):", ["{1, x, x²} unchanged", "the Legendre polynomials", "the Fourier basis", "the standard basis vectors"], 1, "Orthogonalizing monomials on [−1,1] produces Legendre polynomials."),
    ("The computational cost of Gram-Schmidt on n vectors in Rᵐ is:", ["O(n)", "O(n²)", "O(mn²)", "O(2ⁿ)"], 2, "n vectors × (n projections + m-dimensional dot products)."),
    ("Householder reflections are preferred over Gram-Schmidt because they are:", ["less stable", "equally or more numerically stable", "only theoretical", "slower in every case"], 1, "Householder QR is the standard for stability."),
    ("After Gram-Schmidt, coordinates in the new basis are found using:", ["matrix inversion", "simple dot products cᵢ = v·qᵢ", "Gaussian elimination", "eigenvalue computation"], 1, "Orthonormal basis → coordinates = inner products."),
    ("Gram-Schmidt preserves the _____ of the input vectors.", ["eigenvalues", "span", "lengths", "order of magnitude"], 1, "span{v₁,…,vₖ} = span{u₁,…,uₖ}."),
],
"u8_l8.4": [  # Orthogonal Matrices
    ("An orthogonal matrix Q satisfies:", ["Q² = I", "QᵀQ = QQᵀ = I", "Q + Qᵀ = I", "det(Q) = 0"], 1, "Definition of orthogonal matrix."),
    ("The columns of an orthogonal matrix form:", ["a dependent set", "an orthonormal basis for Rⁿ", "a null space basis", "a diagonal"], 1, "QᵀQ = I means columns are orthonormal."),
    ("Q⁻¹ for an orthogonal Q equals:", ["Q", "Qᵀ", "−Q", "Q²"], 1, "Inverse = transpose for orthogonal matrices."),
    ("det(Q) for any orthogonal Q is:", ["0", "±1", "n", "any real number"], 1, "(det Q)² = 1 → det Q = +1 or −1."),
    ("An orthogonal matrix with det = +1 represents:", ["a reflection", "a rotation", "a projection", "a singular transformation"], 1, "det = +1 → proper rotation; det = −1 → reflection or roto-reflection."),
    ("Orthogonal matrices preserve:", ["the trace of other matrices", "vector norms and inner products", "eigenvalues of other matrices", "the zero vector only"], 1, "||Qv|| = ||v|| and (Qu)·(Qv) = u·v."),
    ("The product of two orthogonal matrices is:", ["not orthogonal", "always the identity", "orthogonal", "always symmetric"], 2, "(Q₁Q₂)ᵀ(Q₁Q₂) = Q₂ᵀQ₁ᵀQ₁Q₂ = I."),
    ("The 2×2 rotation matrix [[cosθ, −sinθ],[sinθ, cosθ]] is:", ["symmetric", "orthogonal", "diagonal", "singular"], 1, "RᵀR = I; it rotates vectors by angle θ."),
    ("Eigenvalues of a real orthogonal matrix satisfy:", ["|λ| = 0", "|λ| = 1", "|λ| = n", "λ is always real"], 1, "Norm preservation → eigenvalues on the unit circle."),
    ("SO(3) is the group of:", ["all 3×3 matrices", "3×3 orthogonal matrices with det = +1", "only diagonal 3×3 matrices", "only symmetric 3×3 matrices"], 1, "Special orthogonal = rotations in 3D."),
    ("A Householder matrix H = I − 2uuᵀ (||u|| = 1) has det:", ["0", "−1", "+1", "2"], 1, "Householder reflections have determinant −1."),
    ("In QR factorization, Q is:", ["any invertible matrix", "orthogonal", "lower triangular", "diagonal"], 1, "Q has orthonormal columns."),
    ("Orthogonal transformations are numerically stable because:", ["they increase norms", "they preserve norms, preventing error amplification", "they are always sparse", "they reduce dimensionality"], 1, "Norm preservation = no error magnification."),
    ("Permutation matrices are special cases of:", ["diagonal matrices", "orthogonal matrices", "nilpotent matrices", "projection matrices"], 1, "PᵀP = I."),
    ("cond(Q) in the 2-norm for orthogonal Q equals:", ["0", "1", "n", "∞"], 1, "All singular values = 1, so condition number = 1."),
    ("Gram-Schmidt constructs an orthogonal matrix by:", ["factoring the characteristic polynomial", "building orthonormal columns one by one", "computing eigenvalues", "inverting the input"], 1, "Gram-Schmidt → orthonormal columns → form Q."),
    ("An orthogonal matrix maps the unit sphere to:", ["an ellipsoid", "itself", "a line", "a point"], 1, "||Qv|| = ||v||, so the unit sphere is preserved."),
    ("n×n orthogonal matrices form a _____ under multiplication.", ["vector space", "group (O(n))", "ring", "field"], 1, "Closed under multiplication and inversion → group."),
    ("In 3D graphics, orthogonal matrices handle:", ["scaling only", "rotations and reflections", "color changes", "texture mapping only"], 1, "Rotations and reflections preserve shape and size."),
    ("An orthogonal change of basis preserves:", ["matrix entries", "all geometric properties (inner products, angles, distances)", "computational cost", "the eigenvalues of A"], 1, "Orthogonal transformations are isometries."),
],
"u8_l8.5": [  # Inner Product Spaces
    ("An inner product must satisfy:", ["only linearity", "linearity, symmetry, and positive definiteness", "only symmetry", "no specific properties"], 1, "Three axioms define an inner product."),
    ("The standard inner product on Rⁿ is:", ["u × v", "uᵀv", "u + v", "max(uᵢvᵢ)"], 1, "<u,v> = Σuᵢvᵢ = uᵀv."),
    ("The induced norm ||v|| is defined as:", ["<v,v>", "√<v,v>", "Σ|vᵢ|", "max|vᵢ|"], 1, "||v|| = √<v,v>."),
    ("A weighted inner product uses <u,v> = uᵀWv where W must be:", ["any matrix", "positive definite", "diagonal always", "skew-symmetric"], 1, "W must be positive definite for a valid inner product."),
    ("The L² inner product for functions on [a,b] is:", ["f(a)·g(a)", "∫ₐᵇ f(x)g(x) dx", "f'(x)·g'(x)", "max f(x)·g(x)"], 1, "Integration defines the standard function inner product."),
    ("Two functions are orthogonal on [a,b] when:", ["f(a) = g(a)", "∫ₐᵇ f(x)g(x) dx = 0", "f = g", "f + g = 0"], 1, "<f,g> = 0 defines orthogonality in function spaces."),
    ("sin(x) and cos(x) are orthogonal on [0,2π] because:", ["they have different amplitudes", "∫₀²π sin(x)cos(x) dx = 0", "they have different periods", "sin(0) ≠ cos(0)"], 1, "The integral of their product over a full period is zero."),
    ("Positive definiteness requires <v,v> > 0 when:", ["v is any vector", "v is nonzero", "v = 0", "v has unit length"], 1, "<v,v> ≥ 0 always, and <v,v> = 0 iff v = 0."),
    ("The Cauchy-Schwarz inequality states:", ["|<u,v>| ≥ ||u||·||v||", "|<u,v>| ≤ ||u||·||v||", "<u,v> = ||u||·||v||", "<u,v> = 0 always"], 1, "Universal bound on inner products."),
    ("Fourier series use orthogonal basis functions:", ["polynomials", "sines and cosines", "step functions", "logarithms"], 1, "{1, cos(nx), sin(nx)} are orthogonal on [0,2π]."),
    ("Complex inner products require:", ["<u,v> = <v,u>", "<u,v> = conjugate of <v,u>", "<u,v> = −<v,u>", "<u,v> = |<v,u>|"], 1, "Conjugate symmetry for complex spaces."),
    ("A Hilbert space is:", ["any vector space", "a complete inner product space", "a finite-dimensional space only", "a space without inner product"], 1, "Complete = every Cauchy sequence converges."),
    ("Distance between u and v is:", ["<u,v>", "||u − v||", "|u| + |v|", "u·v"], 1, "d(u,v) = ||u − v|| = √<u−v, u−v>."),
    ("Orthogonal projection minimizes:", ["<v,w>", "||v − w|| over w ∈ W", "the inner product value", "the trace of v"], 1, "Best approximation in the subspace."),
    ("Parseval's identity: Σ|<v,eₖ>|² =:", ["0", "||v||²", "v", "n"], 1, "Sum of squared coefficients = squared norm."),
    ("uᵀAv defines a valid inner product when A is:", ["any matrix", "symmetric positive definite", "only the identity", "skew-symmetric"], 1, "SPD ensures linearity, symmetry, positive definiteness."),
    ("The Riesz representation theorem says every continuous linear functional is:", ["zero", "an inner product with some fixed vector", "a matrix product", "a norm"], 1, "Every bounded linear functional = <·, y> for unique y."),
    ("The Frobenius inner product on matrices is:", ["tr(AB)", "tr(AᵀB)", "det(AB)", "A·B entry-wise sum"], 1, "tr(AᵀB) = Σᵢⱼ AᵢⱼBᵢⱼ."),
    ("In quantum mechanics, |<ψ|φ>|² gives:", ["mass", "probability of measuring state φ given state ψ", "energy", "exact position"], 1, "Born's rule: probability = |amplitude|²."),
    ("A semi-inner product relaxes:", ["linearity", "symmetry", "positive definiteness (allows <v,v>=0 for v≠0)", "all axioms"], 2, "Semi-definite allows non-trivial null vectors."),
],
"u8_l8.6": [  # Applications in Data Compression (PCA)
    ("PCA projects data onto eigenvectors of the covariance matrix with:", ["the smallest eigenvalues", "the largest eigenvalues", "zero eigenvalues", "negative eigenvalues"], 1, "Top eigenvectors capture the most variance."),
    ("The covariance matrix of centered data X (n samples, p features) is:", ["X itself", "XᵀX/(n−1)", "XXᵀ", "X/n"], 1, "S = XᵀX/(n−1) for centered data."),
    ("The first principal component captures:", ["the least variance", "the most variance", "the mean only", "random noise"], 1, "PC1 = direction of maximum variance."),
    ("Each subsequent PC is _____ to all previous ones.", ["parallel", "orthogonal", "opposite", "identical"], 1, "PCs are mutually orthogonal by construction."),
    ("Eigenvalue λₖ represents:", ["the kth data point's value", "variance explained by the kth PC", "the kth sample mean", "the kth feature range"], 1, "Eigenvalue = variance along that principal direction."),
    ("Proportion of variance explained by PC1 is:", ["λ₁", "λ₁ / Σλᵢ", "λ₁²", "λ₁ + λ₂"], 1, "Fraction = eigenvalue / total of all eigenvalues."),
    ("A scree plot shows:", ["raw data points", "eigenvalues in decreasing order", "residuals", "the mean vector"], 1, "Look for an 'elbow' to choose how many PCs to keep."),
    ("Centering data before PCA means:", ["scaling to [0,1]", "subtracting the mean of each variable", "sorting values", "removing outliers"], 1, "Subtract each feature's mean."),
    ("If 3 PCs capture 95% of variance in 50 dimensions, you can reduce to:", ["50 dimensions", "3 dimensions", "47 dimensions", "1 dimension"], 1, "Keep top 3 PCs: 95% of information retained."),
    ("PCA is related to the best rank-k approximation via:", ["QR decomposition", "truncated SVD", "Gaussian elimination", "the inverse"], 1, "Eckart-Young: truncated SVD gives optimal low-rank approximation."),
    ("In image compression, PCA discards components with:", ["large eigenvalues", "small eigenvalues", "all eigenvalues", "the mean component"], 1, "Small eigenvalue components contribute little."),
    ("Standardization before PCA matters when:", ["all variables have the same scale", "variables have very different scales", "data is categorical", "it never matters"], 1, "Different units/scales distort PCA results."),
    ("Loading vectors contain:", ["the data points", "eigenvector entries (variable contributions to each PC)", "eigenvalues", "residuals"], 1, "Loadings = how much each variable contributes to each PC."),
    ("PCA finds optimal _____ projections.", ["nonlinear", "linear", "categorical", "random"], 1, "PCA = best linear dimensionality reduction."),
    ("For nonlinear dimensionality reduction, use:", ["more PCA", "kernel PCA, t-SNE, or UMAP", "simple averaging", "sorting algorithms"], 1, "These methods handle nonlinear manifold structure."),
    ("Reconstruction from k PCs is:", ["exact always", "approximate: X̃ = scores × loadingsᵀ + mean", "impossible", "always zero"], 1, "Multiply scores by loadings and add back the mean."),
    ("In genomics, PCA reveals:", ["exact gene functions", "population structure and variation sources", "individual mutations precisely", "disease cures"], 1, "PCA clusters samples by genetic similarity."),
    ("Reconstruction error decreases as you:", ["remove more PCs", "include more PCs", "decrease sample size", "increase noise"], 1, "More PCs → better approximation."),
    ("PCA is sensitive to:", ["variable names", "outliers (extreme values distort the covariance)", "data storage format", "alphabetical order"], 1, "Outliers shift the covariance structure."),
    ("Robust PCA handles outliers by decomposing data into:", ["two random matrices", "a low-rank + sparse component", "identical copies", "eigenvalue and eigenvector"], 1, "Separates clean signal from sparse corruption."),
],
"u8_l8.7": [  # Applications in Machine Learning
    ("Feature vectors in ML are elements of:", ["an ordered list", "Rⁿ (a vector space)", "a hash table", "a binary tree"], 1, "Each data point is a vector in Rⁿ."),
    ("Linear regression minimizes:", ["||w||", "||Xw − y||² (squared residuals)", "||X||", "det(X)"], 1, "Least squares minimization."),
    ("Ridge regression adds penalty:", ["||XᵀX||", "λ||w||² to the loss (prevents overfitting)", "||y||²", "det(w)"], 1, "Minimize ||Xw−y||² + λ||w||²."),
    ("The SVD of data matrix X = UΣVᵀ is used in:", ["file sorting", "dimensionality reduction, least squares, and recommendations", "audio playback", "text editing"], 1, "SVD is fundamental to many ML algorithms."),
    ("Kernel methods map data to:", ["lower dimensions", "a higher-dimensional space for linear separation", "the same space", "a single point"], 1, "The kernel trick enables nonlinear classification."),
    ("The kernel trick computes K(x,y) = <φ(x),φ(y)> without:", ["any computation", "explicitly computing the mapping φ", "using any data", "inner products"], 1, "Avoids explicit high-dimensional computation."),
    ("In neural networks, weight matrices:", ["store colors", "transform inputs through layers (linear maps)", "define file types", "count epochs"], 1, "Each layer applies Wx + b, then a nonlinearity."),
    ("Backpropagation computes:", ["random values", "gradients of the loss with respect to all weights", "the determinant", "eigenvalues of weights"], 1, "Chain rule applied through layers → efficient gradient computation."),
    ("SVMs find the hyperplane that:", ["passes through all points", "maximizes the margin between classes", "minimizes accuracy", "has the largest norm"], 1, "Maximum-margin classifier."),
    ("The SVM decision boundary is:", ["always a curve", "a hyperplane wᵀx + b = 0", "a circle", "an eigenspace"], 1, "Linear boundary."),
    ("Eigenfaces represent faces using:", ["all pixels equally", "top eigenvectors of the face covariance matrix", "random vectors", "edge detection only"], 1, "PCA on face images → compact representation."),
    ("Matrix factorization for recommendations decomposes the rating matrix as:", ["a single vector", "a product of user and item factor matrices", "an eigenvalue", "a histogram"], 1, "R ≈ UVᵀ predicts missing ratings."),
    ("Word embeddings represent words as:", ["single integers", "dense vectors where proximity reflects similarity", "binary codes", "sorted character lists"], 1, "Similar meaning → nearby vectors."),
    ("Transformer attention computes:", ["eigenvalues", "weighted sums via query-key inner products", "random weights", "fixed averages"], 1, "score(Q,K) via inner products, then weight V."),
    ("Batch normalization normalizes layer activations to have:", ["maximum variance", "zero mean and unit variance", "identical values", "no specific distribution"], 1, "Stabilizes and accelerates training."),
    ("The rank of a data matrix reflects:", ["its file size", "intrinsic dimensionality of the data", "number of rows", "number of classes"], 1, "Rank = number of independent features."),
    ("Low-rank approximation is useful because real data often lies on:", ["the full space", "a low-dimensional subspace", "a single point", "a random distribution"], 1, "Real data has structure captured by fewer dimensions."),
    ("In GANs, generator and discriminator use sequences of:", ["random lookups", "matrix transformations (linear maps + nonlinearities)", "sorting operations", "hash functions"], 1, "Neural networks = compositions of linear and nonlinear maps."),
    ("Transfer learning starts training from:", ["random initialization", "pre-trained weight matrices", "the identity matrix", "zero weights"], 1, "Leverage learned representations from related tasks."),
    ("Graph neural networks combine graph topology with:", ["text only", "feature vectors using adjacency matrices", "audio signals", "tabular data formats"], 1, "GNNs use adjacency structure + node features."),
],
"u8_l8.8": [  # Applications in Quantum Mechanics
    ("Quantum states live in:", ["Rⁿ", "a complex Hilbert space", "a 2D plane only", "a binary space"], 1, "|ψ⟩ lives in a complex Hilbert space."),
    ("In Dirac notation, |ψ⟩ is called a:", ["bra", "ket", "bracket", "scalar"], 1, "Ket = column vector; bra <ψ| = conjugate transpose."),
    ("<φ|ψ> gives:", ["the state |φ⟩", "a probability amplitude", "a new quantum state", "the Hamiltonian"], 1, "|<φ|ψ>|² = measurement probability."),
    ("Observable operators must be:", ["antisymmetric", "Hermitian (A = A†)", "nilpotent", "random matrices"], 1, "Hermitian → real eigenvalues → real measurement outcomes."),
    ("Eigenvalues of a Hermitian operator are:", ["purely imaginary", "complex in general", "real", "always zero"], 2, "Hermitian → real spectrum."),
    ("The Pauli matrices are:", ["4×4 diagonal", "2×2 Hermitian matrices for spin-1/2", "scalar values", "classical vectors"], 1, "Three 2×2 matrices representing spin observables."),
    ("A qubit state α|0⟩ + β|1⟩ requires:", ["|α|+|β| = 1", "|α|²+|β|² = 1", "α = β", "α > β"], 1, "Normalization condition."),
    ("Probability of measuring |0⟩ in state α|0⟩+β|1⟩ is:", ["α", "|α|²", "β²", "|α|+|β|"], 1, "Born's rule: P = |amplitude|²."),
    ("Quantum gates are represented by:", ["diagonal matrices only", "unitary matrices (U†U = I)", "singular matrices", "real symmetric matrices"], 1, "Unitary evolution preserves normalization."),
    ("The tensor product of two qubit spaces has dimension:", ["2", "3", "4", "8"], 2, "ℂ² ⊗ ℂ² = ℂ⁴."),
    ("Entangled states cannot be written as:", ["superpositions", "tensor products of individual states", "normalized vectors", "ket vectors"], 1, "Non-separable: can't factor as |ψ₁⟩⊗|ψ₂⟩."),
    ("The Bell state (|00⟩+|11⟩)/√2 is:", ["separable", "maximally entangled", "a classical state", "an energy eigenstate"], 1, "Cannot be factored → maximally entangled."),
    ("Time evolution |ψ(t)⟩ = e⁻ⁱᴴᵗ/ℏ|ψ(0)⟩ is:", ["non-unitary", "unitary", "classical", "irreversible"], 1, "Quantum evolution is unitary."),
    ("If [A,B] = 0 (commuting observables), then:", ["they cannot be measured", "they share a common eigenbasis", "A = B necessarily", "they anti-commute"], 1, "Commuting → simultaneously diagonalizable."),
    ("[X,P] = iℏI relates to:", ["commutativity of position and momentum", "the uncertainty principle (non-commuting operators)", "energy conservation", "the speed of light"], 1, "Non-commuting → fundamental measurement uncertainty."),
    ("The density matrix for pure state |ψ⟩ is:", ["|ψ⟩<ψ| (outer product)", "<ψ|ψ> (a scalar)", "|ψ⟩+<ψ|", "the identity"], 0, "ρ = |ψ⟩<ψ|."),
    ("tr(ρ) for any valid density matrix equals:", ["0", "1", "n", "depends on the state"], 1, "Trace = 1 because probabilities sum to 1."),
    ("Quantum error correction encodes logical qubits using:", ["single physical qubits", "subspaces of multiple physical qubits", "classical bits", "analog signals"], 1, "Encode in larger Hilbert spaces for error protection."),
    ("Spectral decomposition H = ΣλₖPₖ uses Pₖ as:", ["permutation matrices", "projection operators onto eigenspaces", "rotation matrices", "zero matrices"], 1, "Sum of eigenvalue × projector."),
    ("Quantum teleportation transfers a quantum state using:", ["direct physical transport", "entanglement + classical communication", "faster-than-light signals", "copying the qubit"], 1, "Uses shared entanglement and 2 classical bits."),
],
}

# ── Write ──
with open(PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

count = 0
for key, qs in QUESTIONS.items():
    if key not in data:
        print(f"⚠ {key} not found"); continue
    new_list = []
    for i, (qt, opts, correct_idx, expl) in enumerate(qs):
        options = []
        for j, o in enumerate(opts):
            options.append({"text": o, "is_correct": j == correct_idx, "data_i18n": None})
        new_list.append({
            "question_number": i + 1,
            "question_text": qt,
            "attempted": 2,
            "data_i18n": None,
            "options": options,
            "explanation": expl
        })
    data[key]["quiz_questions"] = new_list
    count += 1

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"✅ Linear Algebra U7-U8: replaced questions for {count} lessons")
