#!/usr/bin/env python3
"""Refix Integrated Science U6 with balanced, high-quality questions."""
import json, os

PATH = os.path.join("content_data", "integrated_science_lessons.json")

QUESTIONS = {
"u6_l6.1": [  # Deforestation & Land Use Changes
    ("Deforestation most directly contributes to climate change by:", ["increasing oxygen in the atmosphere steadily", "releasing stored carbon and reducing CO₂ absorption capacity", "creating new wetland habitats nearby", "cooling the land surface through albedo change"], 1, "Trees store carbon; removing them releases CO₂ and eliminates a carbon sink."),
    ("Which biome has experienced the most rapid deforestation in recent decades?", ["Boreal forests of Canada and Russia", "Tropical rainforests of South America and Southeast Asia", "Temperate forests of northern Europe", "Mediterranean shrublands around the coast"], 1, "Amazon, Congo, and Indonesian forests face intense pressure from agriculture."),
    ("Slash-and-burn agriculture involves:", ["planting crops beneath existing forest canopy", "cutting and burning vegetation to clear land for short-term farming", "flooding fields to create rice paddies", "terracing hillsides for permanent agriculture"], 1, "Nutrients from ash support crops briefly before soil degrades."),
    ("How does deforestation affect the local water cycle?", ["It increases rainfall by exposing more surface area", "It reduces transpiration, lowering regional humidity and rainfall", "It has no measurable effect on precipitation", "It increases groundwater recharge significantly"], 1, "Trees return water to the atmosphere through transpiration."),
    ("Soil erosion accelerates after deforestation because:", ["root systems that anchor soil are removed", "rainfall decreases and dries out the soil", "wind speeds decrease near the ground level", "microorganisms multiply and loosen the soil"], 0, "Roots bind soil particles and slow runoff."),
    ("Which economic activity is the leading driver of tropical deforestation?", ["Mining for rare earth minerals underground", "Expansion of agriculture (cattle ranching, soy, palm oil)", "Urban residential housing developments", "Construction of hydroelectric dam reservoirs"], 1, "Commodity agriculture drives ~70-80% of tropical deforestation."),
    ("Reforestation differs from afforestation in that reforestation:", ["plants trees where none existed historically", "replants trees in an area that was previously forested", "only uses non-native fast-growing species", "occurs exclusively in tropical climate zones"], 1, "Afforestation creates new forest; reforestation restores former forest."),
    ("Deforestation reduces biodiversity primarily by:", ["introducing new species to cleared areas nearby", "destroying habitat that supports diverse communities", "increasing sunlight reaching the forest floor", "reducing competition among remaining organisms"], 1, "Habitat loss is the leading cause of biodiversity decline."),
    ("Which agreement specifically addresses reducing emissions from deforestation?", ["The Montreal Protocol on ozone depletion", "REDD+ (Reducing Emissions from Deforestation and Degradation)", "The Basel Convention on waste management", "The Antarctic Treaty on territorial claims"], 1, "REDD+ provides financial incentives to preserve forests."),
    ("Secondary forests that regrow after clearing typically:", ["immediately match the biodiversity of primary forests", "take decades to centuries to approach original levels", "have higher species diversity than primary forests", "never support any wildlife or plant species"], 1, "Recovery is slow and may never fully restore original species composition."),
    ("Palm oil plantations contribute to deforestation especially in:", ["Northern Canada and Alaska regions broadly", "Indonesia and Malaysia where tropical peat forests are cleared", "Central European lowland areas most recently", "The Australian outback dry grassland regions"], 1, "Southeast Asian peatland destruction releases massive amounts of stored carbon."),
    ("Clear-cutting removes all trees in an area, which can lead to:", ["improved water quality in nearby streams", "increased soil erosion, habitat loss, and altered microclimate", "rapid and complete ecosystem recovery overall", "enhanced carbon sequestration in cleared soils"], 1, "Complete removal eliminates the ecosystem structure."),
    ("Shifting cultivation can be sustainable when:", ["farmers clear primary rainforest each season", "fallow periods allow adequate forest regrowth between cycles", "large areas are cleared by heavy machinery", "the same plot is farmed continuously each year"], 1, "Traditional systems allowed decades of recovery between uses."),
    ("Satellite remote sensing helps monitor deforestation by:", ["planting trees automatically in cleared regions", "detecting changes in forest cover over time across large areas", "predicting where trees will fall during storms", "measuring soil nutrient content from orbit directly"], 1, "Landsat and MODIS data track annual forest loss globally."),
    ("Deforestation of mangrove forests increases coastal vulnerability because:", ["mangroves block all sunlight from reaching shores", "mangrove roots buffer coastlines against storms and erosion", "mangroves contribute to coastal flooding events", "mangroves have no effect on coastal environments"], 1, "Mangroves provide critical natural coastal protection."),
    ("Certification programs like FSC promote:", ["unrestricted logging of any forest areas globally", "sustainable forest management with environmental standards", "banning all wood product consumption entirely", "replacing natural forests with tree plantations"], 1, "Forest Stewardship Council certifies responsibly managed forests."),
    ("The Amazon rainforest is sometimes called the 'lungs of the Earth' because:", ["it produces most of Earth's atmospheric nitrogen gas", "it generates significant oxygen through photosynthesis", "it is the only forest on the entire planet today", "it absorbs all of Earth's carbon dioxide output"], 1, "While the nickname overstates it, the Amazon significantly processes carbon and oxygen."),
    ("Fragmentation from deforestation creates habitat islands that:", ["increase connectivity between animal populations", "isolate populations and reduce genetic diversity", "have no effect on species that can still move", "always support larger populations than contiguous forest"], 1, "Edge effects and isolation threaten fragmented forest species."),
    ("Indigenous land management practices often:", ["accelerate deforestation through slash-and-burn", "maintain forest health through traditional ecological knowledge", "have no measurable impact on forest ecosystems", "focus exclusively on maximizing timber harvest yields"], 1, "Indigenous-managed lands often show lower deforestation rates."),
    ("Converting tropical forest to pasture typically results in:", ["permanent increases in land productivity over decades", "initial productivity followed by rapid soil degradation", "no change in land productivity or soil quality", "improved soil structure from cattle hoof activity"], 1, "Tropical soils lose fertility quickly without forest nutrient cycling."),
],
"u6_l6.2": [  # Urbanization & Soil Degradation
    ("Urbanization increases impervious surface cover, which leads to:", ["greater groundwater recharge in urban areas", "increased stormwater runoff and reduced infiltration", "decreased flooding risk in all situations possible", "improved water quality in urban streams overall"], 1, "Pavement and buildings prevent water from soaking into the ground."),
    ("The urban heat island effect occurs because:", ["cities reflect more sunlight than rural areas", "concrete and asphalt absorb and re-radiate more heat", "urban trees produce excess warmth from respiration", "rural areas have more heat-generating industries"], 1, "Dark surfaces and waste heat raise city temperatures."),
    ("Soil degradation is the decline in soil quality from:", ["natural weathering that creates new minerals", "overuse, erosion, contamination, or compaction", "adding organic matter and nutrients to cropland", "planting deep-rooted native vegetation on slopes"], 1, "Human activities accelerate natural degradation processes."),
    ("Soil salinization in irrigated farmland results from:", ["excessive rainfall washing salt away from fields", "evaporation concentrating salts from irrigation water", "adding fresh compost to the fields regularly", "deep tilling that buries all surface minerals"], 1, "Water evaporates, leaving dissolved salts in the topsoil."),
    ("Desertification is the process by which:", ["deserts naturally shrink over long time periods", "productive land becomes increasingly arid and unproductive", "sand dunes form only in existing desert areas", "rivers erode land into canyon desert formations"], 1, "Climate change and land mismanagement drive desertification."),
    ("Green infrastructure in cities (rain gardens, green roofs) helps by:", ["eliminating all need for stormwater drainage", "absorbing runoff, reducing heat, and providing habitat", "replacing all natural ecosystems more effectively", "increasing impervious surfaces for better drainage"], 1, "Nature-based solutions address multiple urban environmental problems."),
    ("Topsoil formation takes approximately:", ["a few weeks of weathering activity typically", "hundreds to thousands of years per centimeter", "exactly one growing season to regenerate fully", "less than one year under typical conditions"], 1, "Soil is essentially a non-renewable resource on human timescales."),
    ("Overgrazing degrades soil by:", ["adding nutrients through animal waste deposits", "removing vegetation cover and compacting soil", "increasing root depth of remaining grass plants", "reducing erosion through trail formation patterns"], 1, "Bare, compacted soil erodes more easily."),
    ("Soil compaction from heavy machinery reduces:", ["surface temperature of the affected land areas", "pore space needed for water and root growth", "the number of rocks in the upper soil layers", "weed growth on agricultural field margins only"], 1, "Compressed soil limits water movement and root penetration."),
    ("Urban sprawl converts surrounding land to:", ["protected wilderness and national park areas", "low-density residential and commercial development", "higher-productivity irrigated cropland areas", "wetland restoration and wildlife corridor zones"], 1, "Sprawl consumes open space and farmland."),
    ("Contour plowing reduces soil erosion on slopes by:", ["plowing straight up and down the hillside", "plowing along lines of equal elevation on the slope", "removing all vegetation before plowing begins", "adding gravel between the furrow channels"], 1, "Furrows perpendicular to the slope slow water runoff."),
    ("Cover crops planted between growing seasons help soil by:", ["increasing erosion during heavy winter rainfall", "preventing erosion, fixing nitrogen, and adding organic matter", "compacting the soil for next season's planting", "removing all nutrients from the top soil layer"], 1, "Cover crops protect and enrich soil year-round."),
    ("Brownfields are urban sites that are:", ["naturally forested parks within city limits today", "contaminated from previous industrial use, requiring cleanup", "designated for new residential construction only", "protected historic districts in old city centers"], 1, "Remediated brownfields can be redeveloped, reducing sprawl."),
    ("Soil pH affects plant growth because it controls:", ["only the color of the soil surface layer", "nutrient availability and microbial activity in soil", "the temperature of the soil in winter months", "how much sunlight reaches the soil surface"], 1, "Extreme pH locks up essential nutrients."),
    ("Terracing steep hillsides for agriculture prevents erosion by:", ["increasing the slope angle for faster drainage", "creating flat steps that slow water and trap sediment", "removing all soil from the upper slope areas", "planting only shallow-rooted crops on each level"], 1, "Step-like terraces reduce runoff velocity."),
    ("Biochar added to degraded soil can improve it by:", ["increasing soil acidity to toxic levels quickly", "increasing water retention and nutrient availability", "replacing the need for all organic matter input", "dissolving rocks to release new mineral nutrients"], 1, "Charcoal-based amendment with long-lasting soil benefits."),
    ("Urban planning that minimizes soil degradation includes:", ["paving all surfaces to prevent dust generation", "preserving green space and managing stormwater runoff", "building exclusively on agricultural land nearby", "ignoring soil quality in development decisions entirely"], 1, "Integrated planning protects soil resources."),
    ("The Dust Bowl of the 1930s was caused by:", ["excessive irrigation and soil salinization cycles", "drought combined with poor farming that left soil exposed", "mining operations removing the topsoil completely", "volcanic ash deposits covering productive farmland"], 1, "Over-plowed, drought-stricken soil blew away in massive dust storms."),
    ("No-till farming conserves soil by:", ["eliminating all crop planting for several seasons", "leaving crop residue on the surface without plowing", "tilling more deeply to mix all soil horizons", "applying heavy chemical treatments to bare soil"], 1, "Undisturbed soil retains structure and moisture."),
    ("Soil organic matter is critical because it:", ["has no function in healthy productive soils", "improves structure, water-holding, and nutrient cycling", "makes soil more prone to erosion and compaction", "only benefits soil in tropical climate regions only"], 1, "Organic matter is the foundation of soil fertility."),
],
"u6_l6.3": [  # Pollution (Air, Water, Soil)
    ("Point source pollution comes from:", ["diffuse runoff across a wide landscape area", "a single identifiable discharge location like a pipe", "naturally occurring geological mineral deposits", "atmospheric deposition over a broad regional area"], 1, "Traceable to a specific outfall or smokestack."),
    ("Non-point source pollution is difficult to control because:", ["it comes from one easily regulated discharge point", "it originates from many diffuse sources across a landscape", "technology to treat it already exists everywhere", "it only affects small isolated water bodies locally"], 1, "Agricultural runoff, urban stormwater, and atmospheric deposition are examples."),
    ("Acid rain forms when SO₂ and NOₓ emissions react with:", ["soil particles creating mineral acid on contact", "atmospheric water and oxygen to form sulfuric and nitric acid", "ozone in the stratosphere above the cloud level", "carbon dioxide to form carbonic acid exclusively"], 1, "Fossil fuel combustion releases these precursor gases."),
    ("Eutrophication in lakes and coastal waters is caused by:", ["a decrease in all types of nutrient input levels", "excess nitrogen and phosphorus stimulating algal blooms", "increased water clarity from reduced sediment loads", "natural rock weathering adding calcium to the water"], 1, "Nutrient overload → algal bloom → oxygen depletion."),
    ("Ground-level ozone (O₃) is a major component of:", ["the protective stratospheric ozone layer above", "photochemical smog harmful to respiratory health", "clean mountain air at higher elevation sites", "the natural greenhouse effect keeping Earth warm"], 1, "Formed by NOₓ and VOCs reacting in sunlight."),
    ("Heavy metals like mercury bioaccumulate, meaning they:", ["break down quickly in the water environment", "concentrate increasingly at higher trophic levels", "are harmless at all concentrations in food webs", "only affect single-celled organisms in fresh water"], 1, "Top predators carry the highest concentrations."),
    ("Thermal pollution from power plants harms aquatic life by:", ["cooling the water below natural temperature ranges", "raising water temperature, reducing dissolved oxygen", "adding chemical pollutants to the cooling water", "creating beneficial warm-water habitat for species"], 1, "Warm water holds less dissolved oxygen."),
    ("Microplastics in the ocean are concerning because they:", ["dissolve quickly in saltwater within a few days", "are ingested by organisms and transfer toxins up food chains", "are easily filtered out by treatment plants today", "only affect organisms larger than one meter in size"], 1, "Tiny fragments persist and enter the food web."),
    ("The Clean Air Act in the United States has successfully:", ["eliminated all air pollution in North American cities", "reduced emissions of sulfur dioxide, lead, and particulates", "only addressed indoor air quality in office settings", "had no measurable effect on air quality nationwide"], 1, "Regulations have improved air quality since the 1970s."),
    ("Biological oxygen demand (BOD) measures:", ["the oxygen content of the atmosphere above water", "oxygen consumed by organisms decomposing organic matter", "the total oxygen produced by photosynthesis daily", "only the oxygen needs of fish in the water body"], 1, "High BOD indicates heavy organic pollution."),
    ("Soil contamination from industrial chemicals can be remediated by:", ["leaving the site untouched for one growing season", "bioremediation, soil washing, or capping contaminated areas", "simply plowing the chemicals deeper into the ground", "adding more of the same chemical to neutralize it"], 1, "Multiple remediation techniques exist depending on the contaminant."),
    ("Particulate matter (PM2.5) is hazardous because particles:", ["are too large to be inhaled into the lungs at all", "penetrate deep into lung tissue and enter the bloodstream", "only affect buildings and not living organisms", "are composed entirely of harmless water droplets"], 1, "PM2.5 causes respiratory and cardiovascular disease."),
    ("Agricultural runoff pollution can be reduced by:", ["increasing fertilizer application rates on all fields", "buffer strips along waterways and precision fertilizer use", "removing all vegetation from stream and riverbanks", "draining wetlands adjacent to agricultural land areas"], 1, "Riparian buffers filter nutrients before they reach waterways."),
    ("Oil spills in marine environments are cleaned up using:", ["only natural weathering and evaporation over time", "mechanical booms, chemical dispersants, and bioremediation", "adding more oil to dilute the concentration level", "freezing the water surface to trap oil underneath"], 1, "Multiple techniques are usually combined in spill response."),
    ("Indoor air pollution from burning biomass fuels affects:", ["no one — indoor smoke dissipates immediately", "billions of people in developing nations causing illness", "only people allergic to specific types of dust", "only outdoor air quality in surrounding neighborhoods"], 1, "Cooking with wood, dung, or coal in enclosed spaces."),
    ("The precautionary principle in pollution management states:", ["action should wait until harm is conclusively proven", "potential harm should be prevented even before full proof", "economic growth should always take priority over caution", "only proven pollutants need any regulation at all"], 1, "Act to prevent harm rather than react after damage."),
    ("Water treatment plants remove pollutants through:", ["one single filtration step before distribution", "physical, chemical, and biological treatment processes", "only adding chlorine to kill all bacteria present", "simply storing water for a few days before distributing"], 1, "Multi-stage treatment addresses various contaminant types."),
    ("Light pollution affects ecosystems by:", ["having no effect on wildlife behavior patterns", "disrupting nocturnal behavior, migration, and photoperiod", "only affecting human sleep in urban residential areas", "benefiting all species by extending their active hours"], 1, "Artificial light at night alters ecological patterns."),
    ("Persistent organic pollutants (POPs) like DDT are dangerous because they:", ["break down in the environment within a few hours", "resist degradation, bioaccumulate, and travel long distances", "only exist in laboratory settings and not in nature", "are easily removed from water by standard filtration"], 1, "POPs persist for decades and concentrate in food webs."),
    ("Integrated pollution prevention strategies combine:", ["relying on one single regulation for all pollutants", "source reduction, treatment, monitoring, and enforcement", "only end-of-pipe treatment after pollution occurs", "ignoring small sources and focusing only on factories"], 1, "Effective pollution control requires a comprehensive approach."),
],
}

with open(PATH, "r", encoding="utf-8") as f:
    data = json.load(f)
count = 0
for key, qs in QUESTIONS.items():
    if key not in data:
        print(f"⚠ {key} not found"); continue
    new_list = []
    for i, (qt, opts, ci, expl) in enumerate(qs):
        options = []
        for j, o in enumerate(opts):
            options.append({"text": o, "is_correct": j == ci, "data_i18n": None})
        new_list.append({
            "question_number": i + 1, "question_text": qt, "attempted": 2,
            "data_i18n": None, "options": options, "explanation": expl
        })
    data[key]["quiz_questions"] = new_list
    count += 1
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"✅ Integrated Science U6: replaced questions for {count} lessons")
