#!/usr/bin/env python3
"""Replace placeholder questions in Marine Science U3-U4 with real questions."""
import json, os

PATH = os.path.join("content_data", "marine_science_lessons.json")

QUESTIONS = {
# ── U3: Marine Geology ──
"u3_l3.1": [  # Structure of the Ocean Floor
    ("The continental shelf extends from the shoreline to about what depth?", ["5,000 m", "200 m", "2,000 m", "10 m"], 1, "The continental shelf averages roughly 200 m deep before dropping off at the shelf break."),
    ("The deepest part of the ocean is found in:", ["mid-ocean ridges", "the continental shelf", "oceanic trenches", "abyssal plains"], 2, "Oceanic trenches are the deepest features, formed at subduction zones."),
    ("Abyssal plains are characterized by:", ["steep slopes covered in coral", "flat expanses of sediment-covered ocean floor", "volcanic island chains", "shallow coastal waters"], 1, "Abyssal plains are broad, flat regions of the deep ocean floor."),
    ("The continental slope connects the:", ["trench to a ridge", "continental shelf to the deep ocean floor", "mid-ocean ridge to a seamount", "shoreline to the beach"], 1, "The slope is the steep transition from the shelf to the deep."),
    ("Seamounts are:", ["underwater volcanic mountains that don't reach the surface", "shallow reef platforms", "flat-topped continental features", "sediment piles near river deltas"], 0, "Seamounts are volcanic peaks below sea level."),
    ("A guyot differs from a seamount because it has:", ["much deeper roots", "a flat top from erosion at the surface", "coral reefs on its summit", "no volcanic origin"], 1, "Guyots are flat-topped seamounts, eroded when they were at sea level."),
    ("The abyssal zone ranges from approximately:", ["0–200 m", "200–1,000 m", "1,000–4,000 m", "4,000–6,000 m"], 3, "The abyssal zone spans roughly 4,000–6,000 m depth."),
    ("Submarine canyons on the continental slope are carved mainly by:", ["ocean currents only", "turbidity currents (sediment-laden flows)", "tidal action alone", "volcanic eruptions"], 1, "Turbidity currents erode deep submarine canyons."),
    ("The hadal zone refers to depths found in:", ["the continental shelf", "coral reef systems", "oceanic trenches (below ~6,000 m)", "the open surface waters"], 2, "Hadal zone = the ultra-deep trench environment."),
    ("Bathymetry is the study of:", ["marine life distribution", "underwater topography (ocean floor depth)", "coastal erosion rates", "seawater chemistry"], 1, "Bathymetry maps the depth and shape of the ocean floor."),
    ("The average depth of the world's oceans is approximately:", ["500 m", "1,200 m", "3,700 m", "11,000 m"], 2, "Global average ocean depth is about 3,688 m."),
    ("Island arcs form near:", ["mid-ocean ridges", "oceanic trenches at subduction zones", "continental shelves", "abyssal plains"], 1, "Volcanic island arcs develop above subducting oceanic plates."),
    ("The Mariana Trench reaches a maximum depth of about:", ["5,000 m", "7,000 m", "11,000 m", "15,000 m"], 2, "Challenger Deep in the Mariana Trench is ~11,000 m."),
    ("Continental rise is formed by:", ["volcanic activity at ridges", "accumulation of sediment at the base of the continental slope", "coral reef growth", "glacial erosion"], 1, "Sediments pile up at the slope's base forming the continental rise."),
    ("Sonar mapping of the ocean floor works by:", ["bouncing sound waves off the bottom and measuring return time", "using underwater cameras", "measuring water temperature", "tracking ocean currents"], 0, "Echo sounders measure depth from sound travel time."),
    ("Multibeam sonar improves on single-beam by:", ["using light instead of sound", "covering a wider swath of the seafloor per pass", "only working in shallow water", "measuring salinity instead"], 1, "Multibeam collects data across a broad fan shape."),
    ("The mid-ocean ridge system is the longest mountain chain on Earth, stretching about:", ["5,000 km", "20,000 km", "65,000 km", "100,000 km"], 2, "The global mid-ocean ridge system is ~65,000 km long."),
    ("Atolls form when:", ["a volcanic island sinks while its fringing reef continues to grow", "continental shelves erode", "deep-sea vents create circular formations", "rivers deposit sediment in rings"], 0, "Darwin's model: subsidence + continued reef growth = ring-shaped atoll."),
    ("The ocean floor is youngest at:", ["continental margins", "mid-ocean ridges", "deep-sea trenches", "abyssal plains far from ridges"], 1, "New crust forms at ridges and ages as it moves away."),
    ("Passive continental margins (like the U.S. East Coast) are characterized by:", ["earthquake activity and deep trenches", "wide continental shelves and no trenches", "volcanic arcs", "subduction zones"], 1, "Passive margins are tectonically quiet with broad flat shelves."),
],
"u3_l3.2": [  # Plate Tectonics & Seafloor Spreading
    ("Who proposed the theory of continental drift?", ["Charles Darwin", "Alfred Wegener", "Harry Hess", "J. Tuzo Wilson"], 1, "Wegener proposed continental drift in 1912."),
    ("Seafloor spreading was proposed by:", ["Wegener", "Harry Hess", "Marie Tharp", "James Cook"], 1, "Hess proposed that new ocean floor forms at mid-ocean ridges."),
    ("At divergent plate boundaries, new oceanic crust is created by:", ["sediment deposition", "upwelling magma that solidifies at mid-ocean ridges", "subduction of continental plates", "glacial erosion"], 1, "Magma rises at ridges and solidifies to form new basaltic crust."),
    ("Magnetic striping on the ocean floor supports seafloor spreading because:", ["all rocks are magnetic", "symmetric magnetic reversals on both sides of ridges show progressive formation", "magnets are found on the seafloor", "sediment contains metal"], 1, "Alternating normal/reversed polarity stripes mirror ridge formation over time."),
    ("At convergent boundaries, one plate usually:", ["slides past the other", "moves away from the other", "subducts beneath the other", "melts entirely"], 2, "Convergent = collision; denser plate subducts."),
    ("Transform boundaries are characterized by:", ["new crust formation", "plates sliding horizontally past each other", "deep ocean trenches", "volcanic eruptions"], 1, "Plates move laterally; no crust is created or destroyed."),
    ("The driving force behind plate movement is primarily:", ["wind patterns", "convection currents in the mantle", "the moon's gravitational pull", "ocean wave energy"], 1, "Mantle convection drives tectonic plate motion."),
    ("Evidence for Pangaea includes:", ["identical ocean currents worldwide", "matching fossils and rock formations across continents", "uniform ocean salinity", "similar weather on all continents"], 1, "Fossil and geological matches indicate continents were once joined."),
    ("The age of ocean floor increases with:", ["depth below the surface", "distance from a mid-ocean ridge", "proximity to the equator", "salinity of overlying water"], 1, "Crust is oldest far from ridges and youngest at ridges."),
    ("Subduction zones produce:", ["abyssal plains", "deep-sea trenches and volcanic arcs", "wide continental shelves", "coral reefs"], 1, "Subducting plates create trenches and trigger volcanism."),
    ("The Ring of Fire encircles the:", ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"], 2, "The Pacific Ring of Fire is where most subduction occurs."),
    ("Paleomagnetism studies:", ["current ocean temperatures", "the record of Earth's magnetic field preserved in rocks", "marine plant growth patterns", "the salinity of ancient seas"], 1, "Paleomagnetic data shows reversals and plate movement."),
    ("The lithosphere floats on the:", ["inner core", "asthenosphere", "troposphere", "hydrosphere"], 1, "The asthenosphere is partially molten, allowing plates to move."),
    ("Ophiolites are important because they are:", ["deep-sea organisms", "sections of former ocean crust now found on land", "types of coral", "volcanic gases"], 1, "Ophiolites represent uplifted oceanic crust."),
    ("Hot spots produce volcanic chains because:", ["the plate moves over a stationary mantle plume", "ridges shift location frequently", "trenches erupt sideways", "convection stops in that area"], 0, "A fixed mantle plume creates a chain as the plate moves overhead."),
    ("The Hawaiian Islands formed from a:", ["subduction zone", "mid-ocean ridge", "hot spot beneath the Pacific plate", "transform fault"], 2, "Hawaii sits over an intraplate hot spot."),
    ("GPS technology confirms plate motion by measuring:", ["ocean depth changes", "precise movement of stations on different plates", "magnetic field strength", "seawater temperature changes"], 1, "GPS stations detect cm/year movement."),
    ("The Wilson Cycle describes:", ["annual ocean temperature changes", "the opening and closing of ocean basins over geologic time", "daily tidal patterns", "marine species migration"], 1, "Supercontinents form and break apart cyclically."),
    ("Mid-ocean ridges are examples of:", ["convergent boundaries", "transform boundaries", "divergent boundaries", "hot spots"], 2, "Plates pull apart at ridges."),
    ("The oldest oceanic crust is about _____ million years old.", ["50", "200", "1,000", "4,000"], 1, "Oldest ocean crust ~200 Ma; it's recycled at subduction zones."),
],
"u3_l3.3": [  # Mid-Ocean Ridges & Trenches
    ("Mid-ocean ridges form at:", ["convergent boundaries", "transform faults", "divergent plate boundaries", "hot spots only"], 2, "Plates spread apart and magma rises to create ridges."),
    ("The Mid-Atlantic Ridge runs through the middle of the:", ["Pacific Ocean", "Indian Ocean", "Atlantic Ocean", "Arctic Ocean only"], 2, "It separates the North/South American plates from Eurasian/African plates."),
    ("Pillow lavas on mid-ocean ridges form when:", ["lava erupts under high water pressure and cools rapidly", "sediment compresses into rock", "coral grows on basalt", "ice melts under the ocean"], 0, "Rapid cooling of lava underwater creates rounded pillow shapes."),
    ("Rift valleys at ridge crests form due to:", ["compression forces", "tensional forces pulling crust apart", "sediment filling depressions", "coral reef collapse"], 1, "Extension creates a central rift valley."),
    ("Spreading rates at mid-ocean ridges range from:", ["1–20 cm/year", "1–20 m/year", "1–20 km/year", "1–20 mm/century"], 0, "Slow to fast spreading rates span roughly 1–18 cm/yr."),
    ("Fast-spreading ridges tend to have:", ["deep rift valleys", "smoother, broader profiles", "no volcanic activity", "deep trenches alongside"], 1, "Fast spreading = more magma supply → smoother topography."),
    ("Slow-spreading ridges (like the Mid-Atlantic Ridge) tend to have:", ["smooth profiles without rifts", "deep central rift valleys and rugged terrain", "no basalt production", "flat abyssal plains"], 1, "Less magma supply → pronounced rift valley."),
    ("Black smokers at ridges emit:", ["freshwater", "hot, mineral-rich fluids (sulfides)", "pure oxygen", "ozone gas"], 1, "Superheated water dissolves minerals and precipitates them as dark plumes."),
    ("Oceanic trenches are the deepest features on Earth because:", ["erosion carved them deeply", "subducting plates bend downward sharply into the mantle", "volcanic activity hollows them out", "sediments dissolve the rock"], 1, "The subducting plate creates the trench depression."),
    ("The Challenger Deep is located in the:", ["Tonga Trench", "Mariana Trench", "Peru-Chile Trench", "Java Trench"], 1, "Deepest known point on Earth: ~10,994 m."),
    ("Accretionary wedges form at trenches from:", ["volcanic lava flows", "sediment scraped off the subducting plate", "coral reef debris", "glacial deposits"], 1, "Sediment is bulldozed against the overriding plate."),
    ("Back-arc basins form:", ["in front of the trench", "behind the volcanic arc due to extension", "at mid-ocean ridges only", "on the continental shelf"], 1, "Extension behind the arc creates a small basin."),
    ("Earthquakes at trenches can be:", ["only shallow", "shallow, intermediate, and deep along the Benioff zone", "absent entirely", "only at the surface"], 1, "The Benioff zone traces seismicity along the subducting slab."),
    ("Tsunami generation is often linked to:", ["mid-ocean ridge eruptions", "large subduction zone earthquakes displacing the seafloor", "normal weather patterns", "tidal forces alone"], 1, "Sudden vertical displacement of the seafloor generates tsunamis."),
    ("Island arcs curve because:", ["the subducting plate meets a spherical Earth surface", "ocean currents shape them", "they follow continental coastlines", "volcanic eruptions are random"], 0, "The intersection of a plane (plate) with a sphere creates an arc."),
    ("The Japan Trench is associated with:", ["a divergent boundary", "subduction of the Pacific plate beneath the North American plate", "a transform fault", "a hot spot"], 1, "The Pacific plate subducts westward beneath Japan."),
    ("Volcanic activity at subduction zones produces:", ["basaltic lava only", "andesitic to rhyolitic (explosive) eruptions", "no lava at all", "only hydrothermal vents"], 1, "Water lowers melting point → silica-rich, explosive magma."),
    ("Fracture zones that offset mid-ocean ridges are:", ["divergent boundaries", "transform faults", "subduction zones", "hot spot tracks"], 1, "Transform faults connect offset ridge segments."),
    ("The East Pacific Rise is an example of a:", ["slow-spreading ridge", "fast-spreading ridge", "subduction trench", "transform boundary"], 1, "The EPR spreads at up to ~16 cm/yr."),
    ("Magnetic anomaly maps helped confirm:", ["ocean depth everywhere", "the pattern of seafloor spreading and plate motion", "the location of coral reefs", "ocean salinity changes"], 1, "Symmetric anomaly patterns on both sides of ridges."),
],
"u3_l3.4": [  # Marine Sediments
    ("The four main types of marine sediment are:", ["volcanic, glacial, tidal, aeolian", "terrigenous, biogenous, hydrogenous, cosmogenous", "sandy, muddy, rocky, silty", "shallow, deep, mid-water, surface"], 1, "These four categories classify all major ocean sediment types."),
    ("Terrigenous sediments originate from:", ["living organisms", "chemical precipitation from seawater", "weathering and erosion of land rocks", "meteorites"], 2, "Terrigenous = from terra (land)."),
    ("Biogenous sediments are made from:", ["land-derived minerals", "remains of marine organisms (shells, skeletons)", "volcanic ash", "space dust"], 1, "Biogenous = biological origin."),
    ("Calcareous ooze is composed mainly of:", ["silica shells", "calcium carbonate shells (foraminifera, coccolithophores)", "clay minerals", "metal nodules"], 1, "CaCO₃ from planktonic organisms."),
    ("Siliceous ooze is composed mainly of:", ["calcium carbonate", "silica shells (diatoms, radiolarians)", "terrigenous clay", "manganese nodules"], 1, "SiO₂ skeletons from siliceous plankton."),
    ("The CCD (Calcite Compensation Depth) is the depth below which:", ["silica dissolves", "calcite dissolves faster than it accumulates", "sediment cannot settle", "all organisms die"], 1, "Below the CCD, CaCO₃ dissolves; no calcareous ooze accumulates."),
    ("The CCD is typically found at approximately:", ["500 m", "1,500 m", "4,500 m", "10,000 m"], 2, "The CCD averages around 4,000–5,000 m, varying by location."),
    ("Hydrogenous sediments form by:", ["biological activity", "chemical precipitation from seawater", "land erosion", "cosmic bombardment"], 1, "Dissolved minerals precipitate directly from ocean water."),
    ("Manganese nodules are an example of _____ sediment.", ["terrigenous", "biogenous", "hydrogenous", "cosmogenous"], 2, "They precipitate from dissolved metals in seawater."),
    ("Cosmogenous sediments come from:", ["volcanic eruptions", "organisms", "extraterrestrial material (micrometeorites, cosmic dust)", "river discharge"], 2, "Space-origin material entering the ocean."),
    ("Turbidites are deposited by:", ["gentle ocean currents", "turbidity currents (rapid sediment flows)", "wind-blown dust", "biological processes"], 1, "Graded beds from fast-moving sediment-laden flows."),
    ("Pelagic sediments accumulate on the:", ["continental shelf", "deep ocean floor far from land", "beach", "river delta"], 1, "Pelagic = open ocean, far from land influence."),
    ("Neritic sediments are found on the:", ["deep ocean floor", "continental shelf and near shore", "mid-ocean ridge", "abyssal plain exclusively"], 1, "Neritic = near shore, on the shelf."),
    ("Sediment thickness generally increases with:", ["proximity to the mid-ocean ridge", "distance from continents toward the open ocean", "distance from the mid-ocean ridge (older crust, more time to accumulate)", "water depth only"], 2, "Older crust had more time to collect sediment."),
    ("Deep-sea drilling (like ODP/IODP) provides:", ["live marine specimens only", "sediment cores that reveal climate and geologic history", "water samples exclusively", "fresh volcanic rock only"], 1, "Cores give a stratigraphic record of ocean history."),
    ("Wind-blown (aeolian) sediment contributes to:", ["terrigenous deep-sea clay deposits", "biogenous ooze", "hydrogenous nodules", "cosmogenous particles"], 0, "Dust blown from deserts settles across the ocean."),
    ("Red clay dominates the deep ocean floor where:", ["biogenous input is high", "productivity is low and the seafloor is below the CCD", "rivers discharge heavily", "hydrothermal vents are present"], 1, "Where no ooze survives, slow-accumulating clay dominates."),
    ("The rate of pelagic sedimentation is typically:", ["meters per year", "centimeters per thousand years", "meters per day", "kilometers per million years"], 1, "Very slow: a few cm per thousand years."),
    ("Sediment cores help reconstruct past climates by analyzing:", ["the color of the mud only", "oxygen isotope ratios in foraminifera shells", "grain size alone", "the quantity of sand grains"], 1, "δ¹⁸O in foram shells tracks past temperatures and ice volumes."),
    ("Phosphorite deposits form on continental shelves due to:", ["volcanic activity", "upwelling of nutrient-rich water and biological productivity", "glacial processes", "meteorite impacts"], 1, "Phosphorus-rich biological deposits accumulate under upwelling zones."),
],
"u3_l3.5": [  # Hydrothermal Vents
    ("Hydrothermal vents are found primarily along:", ["continental shelves", "mid-ocean ridges and other volcanically active areas", "abyssal plains", "polar ice caps"], 1, "Vents occur where magma heats seawater near spreading centers."),
    ("Black smokers emit fluids that can exceed:", ["50°C", "150°C", "350°C", "1,000°C"], 2, "Some black smoker fluids reach 350–400°C."),
    ("The dark color of black smoker plumes comes from:", ["organic matter", "precipitating metal sulfides (iron, copper, zinc)", "volcanic ash particles", "dissolved carbon dioxide"], 1, "Sulfide minerals precipitate on contact with cold seawater."),
    ("White smokers emit cooler fluids rich in:", ["metal sulfides", "barium, calcium, and silicon compounds", "pure oxygen", "nitrogen gas"], 1, "Lower-temperature fluids precipitate lighter-colored minerals."),
    ("Chemosynthetic bacteria near vents use _____ as an energy source.", ["sunlight", "hydrogen sulfide", "dissolved oxygen", "carbon dioxide alone"], 1, "Chemosynthesis uses H₂S oxidation instead of photosynthesis."),
    ("Giant tube worms (Riftia) survive near vents by:", ["photosynthesizing", "hosting chemosynthetic bacteria in their tissues", "filtering plankton from the water", "absorbing heat energy directly"], 1, "Endosymbiotic bacteria provide nutrition via chemosynthesis."),
    ("Vent ecosystems are unique because they are based on:", ["solar energy transferred through the food web", "chemical energy from the Earth's interior", "thermal energy from ocean currents", "wind-driven productivity"], 1, "Primary production via chemosynthesis, not photosynthesis."),
    ("Massive sulfide deposits near vents contain economically valuable:", ["diamonds", "copper, zinc, gold, and silver", "calcium carbonate", "phosphate minerals"], 1, "Mineral-rich deposits form chimney structures."),
    ("The first hydrothermal vent community was discovered in:", ["1872", "1912", "1977", "2005"], 2, "Alvin discovered vents on the Galápagos Rift in 1977."),
    ("Vent fluids are acidic, with pH values around:", ["8.0 (slightly basic)", "7.0 (neutral)", "2–3 (very acidic)", "12 (very basic)"], 2, "Vent fluids are highly acidic."),
    ("The Alvin submersible was crucial for:", ["mapping the entire ocean floor", "the first direct observation of deep-sea hydrothermal vents", "measuring global sea level", "studying surface currents"], 1, "Alvin enabled scientists to visit the deep-sea vents directly."),
    ("Extremophiles near vents include organisms that thrive in:", ["freshwater only", "extreme heat, acidity, and high metal concentrations", "shallow tropical waters", "polar surface ice only"], 1, "Thermophiles and acidophiles live in vent-influenced waters."),
    ("Vent chimneys grow by:", ["coral-like biological accretion", "mineral precipitation as hot and cold water mix", "sediment compaction", "volcanic eruption building blocks"], 1, "Minerals precipitate when superheated vent fluid meets cold seawater."),
    ("Diffuse venting releases:", ["concentrated plumes only", "lower-temperature fluids spread over a larger area", "no chemicals at all", "fresh water only"], 1, "Diffuse flow: lower temperature, broader area."),
    ("The discovery of vent life changed biology by showing:", ["all life needs sunlight", "complex ecosystems can be sustained by chemical energy alone", "the deep sea is lifeless", "only bacteria can live without light"], 1, "Overturned the assumption that all ecosystems depend on photosynthesis."),
    ("Hydrothermal vents may have been sites for:", ["dinosaur fossil preservation", "the origin of life on Earth", "continental formation", "ice age initiation"], 1, "Prebiotic chemistry at vents may have sparked early life."),
    ("Vent plumes carry dissolved metals that affect:", ["only local vent chemistry", "ocean chemistry over large distances", "the atmosphere directly", "terrestrial rivers"], 1, "Hydrothermal inputs influence global ocean geochemistry."),
    ("EPR (East Pacific Rise) vents differ from MAR (Mid-Atlantic Ridge) vents in:", ["the chemistry is identical", "EPR has faster spreading and more frequent venting", "MAR has no vents at all", "EPR vents are on land"], 1, "Spreading rate influences vent frequency and character."),
    ("Pompeii worms live on vent chimneys and tolerate temperatures up to:", ["30°C", "80°C", "200°C", "350°C"], 1, "Alvinella pompejana is one of the most heat-tolerant animals known (~80°C)."),
    ("Deep-sea mining of vent deposits raises concerns about:", ["over-harvesting sunlight energy", "destroying unique, fragile ecosystems", "excessive freshwater use", "atmospheric pollution only"], 1, "Mining could devastate endemic vent communities."),
],
"u3_l3.6": [  # Case Studies in Marine Geology
    ("The 2004 Indian Ocean tsunami was triggered by a:", ["volcanic island collapse", "magnitude 9.1 subduction zone earthquake off Sumatra", "meteor impact", "submarine landslide only"], 1, "The Sumatra-Andaman earthquake generated a devastating tsunami."),
    ("Loihi is a submarine volcano forming:", ["in the Mariana Trench", "southeast of Hawaii over the Hawaiian hot spot", "in the Arctic Ocean", "at the Mid-Atlantic Ridge crest"], 1, "Loihi is the next island in the Hawaiian chain, still below sea level."),
    ("The discovery of the Mid-Atlantic Ridge rift valley helped confirm:", ["continental drift was wrong", "seafloor spreading theory", "the ocean has no geological activity", "that ridges are not volcanic"], 1, "A central rift valley was consistent with divergent plate motion."),
    ("Marie Tharp's ocean floor maps were groundbreaking because they:", ["used satellite imagery only", "revealed the global mid-ocean ridge system and rift valleys", "showed the ocean floor was completely flat", "mapped ocean surface currents"], 1, "Tharp's physiographic maps transformed our understanding of ocean geology."),
    ("The Mediterranean dried up during the Messinian Salinity Crisis because:", ["rainfall stopped globally", "tectonic movements closed the Strait of Gibraltar, cutting it off from the Atlantic", "all rivers stopped flowing", "polar ice caps redirected water flow"], 1, "Closure of the gateway led to evaporation and salt deposits."),
    ("The Chicxulub impact crater, partially beneath the Gulf of Mexico, is linked to:", ["the formation of the Caribbean Sea", "the mass extinction at the end of the Cretaceous period", "the opening of the Atlantic Ocean", "modern El Niño cycles"], 1, "The asteroid impact 66 Ma ago caused the K-Pg extinction."),
    ("Turbidite deposits in the North Atlantic were caused by:", ["routine tidal processes", "the 1929 Grand Banks earthquake triggering a massive turbidity current", "river flooding alone", "volcanic eruptions on land"], 1, "The earthquake triggered submarine landslides and turbidity currents."),
    ("Zealandia is considered a largely submerged continent because:", ["it has no geological diversity", "it has continental-type crust that is mostly below sea level", "it is made of oceanic basalt", "it formed at a mid-ocean ridge"], 1, "Zealandia has thick, continental crust that is mostly underwater."),
    ("The Tonga Trench in the Pacific is notable for:", ["being the shallowest trench", "hosting some of the deepest earthquakes on Earth", "having no seismic activity", "forming at a divergent boundary"], 1, "The Tonga subduction zone produces very deep earthquakes."),
    ("The Atlantis Massif near the Mid-Atlantic Ridge is studied for its:", ["coral reef ecosystem", "exposures of lower crust and mantle rocks (serpentinite)", "shallow continental shelf", "tropical fish species"], 1, "An oceanic core complex exposing deep crust/mantle."),
    ("Coral reef terraces on uplifted islands record:", ["daily tidal changes", "past sea level stands", "modern climate data exclusively", "abyssal plain topography"], 1, "Elevated reef terraces show historical sea level positions."),
    ("The eruption of Hunga Tonga-Hunga Ha'apai in 2022 demonstrated:", ["volcanoes can't affect the atmosphere", "explosive submarine eruptions can inject material into the stratosphere", "the deep sea is volcanically inactive", "tectonic plates don't move"], 1, "The eruption sent a plume to 57 km altitude."),
    ("The Kerguelen Plateau is a large igneous province formed by:", ["continental collision", "massive volcanic eruptions from a mantle plume", "sediment accumulation", "glacial deposition"], 1, "Large igneous provinces result from extensive flood basalt volcanism."),
    ("Ocean Drilling Program (ODP) cores from the South Atlantic confirmed:", ["the ocean floor is only 100 years old", "that South America and Africa were once joined (matching sediment records)", "that ocean water is fresh", "the Ridge has no volcanic rock"], 1, "Sediment and basement ages confirmed plate tectonic reconstructions."),
    ("Gas hydrates (methane ice) on continental margins are significant because:", ["they are a potential energy source and climate risk", "they drive ocean currents", "they are biologically inert", "they only form in freshwater"], 0, "Destabilized hydrates could release vast amounts of methane."),
    ("Submarine landslides can be triggered by:", ["earthquakes, volcanic eruptions, and gas hydrate dissociation", "everyday tidal changes", "plankton blooms", "cloudless skies"], 0, "Multiple triggers can destabilize underwater slopes."),
    ("The Aleutian Trench formed from subduction of the _____ plate.", ["North American", "Pacific", "Eurasian", "Antarctic"], 1, "The Pacific plate subducts beneath the North American plate."),
    ("Paleomagnetic data from ocean drill cores show:", ["the ocean floor formed all at once", "reversals in Earth's magnetic field recorded in seafloor basalt", "Earth has no magnetic field", "sediment is not magnetic"], 1, "Alternating magnetic polarity in drilled basalt confirms seafloor spreading."),
    ("Studying the geology of the ocean floor requires collaboration between:", ["only geologists", "geologists, geophysicists, geochemists, and oceanographers", "only biologists", "astronomers only"], 1, "Marine geology is highly interdisciplinary."),
    ("Future deep-sea exploration priorities include:", ["stopping all research", "better mapping, mineral assessment, and vent ecosystem protection", "draining the ocean", "converting trenches to farmland"], 1, "Balancing resource discovery with ecosystem conservation."),
],
"u3_l3.7": [  # AP Prep: Plate Tectonics Calculations
    ("If a plate moves 5 cm/year, how far will it move in 10 million years?", ["50 m", "500 m", "500 km", "5,000 km"], 2, "5 cm/yr × 10⁷ yr = 5 × 10⁵ m = 500 km."),
    ("A magnetic stripe is 50 km from the ridge axis. If spreading is 2 cm/yr (per side), how old is that stripe?", ["250,000 years", "2.5 million years", "25 million years", "250 million years"], 1, "50 km / (2 cm/yr) = 50,000 m / 0.02 m/yr = 2.5 × 10⁶ years."),
    ("The half-spreading rate is 3 cm/yr. The full spreading rate is:", ["1.5 cm/yr", "3 cm/yr", "6 cm/yr", "9 cm/yr"], 2, "Full rate = 2 × half-rate = 6 cm/yr."),
    ("Two points currently 3,000 km apart across an ocean. If the spreading rate is 3 cm/yr, the ocean started opening roughly:", ["100 million years ago", "50 million years ago", "10 million years ago", "1 million years ago"], 0, "3,000 km / 3 cm/yr = 3×10⁶ m / 0.03 m/yr = 10⁸ yr = 100 Ma."),
    ("If seafloor basalt at 200 km from a ridge is dated at 5 Ma, the half-rate is:", ["4 cm/yr", "2 cm/yr", "10 cm/yr", "40 cm/yr"], 0, "200 km / 5 Ma = 40 km/Ma = 4 cm/yr."),
    ("A P-wave travels at 6 km/s. If it arrives 30 seconds after an earthquake, the epicenter is approximately:", ["90 km", "180 km", "360 km", "18 km"], 1, "d = v × t = 6 × 30 = 180 km (simplified; real calculations use multiple stations)."),
    ("Sedimentation rate is 2 cm per 1,000 years. A 10-m core spans about:", ["5,000 years", "50,000 years", "500,000 years", "5 million years"], 2, "10 m = 1,000 cm; 1,000 / 2 × 1,000 = 500,000 years."),
    ("If ocean crust moves at 4 cm/yr and a hot spot produces islands 200 km apart, the time between islands is:", ["500,000 years", "5 million years", "50 million years", "50,000 years"], 1, "200 km / 4 cm/yr = 200,000 m / 0.04 m/yr = 5 × 10⁶ yr."),
    ("The Richter scale is logarithmic: a magnitude 7 earthquake releases _____ times more energy than magnitude 5.", ["10", "100", "~1,000 (≈31.6²)", "10,000"], 2, "Each whole number = ~31.6× more energy; 2 steps = ~1,000×."),
    ("If sediment covers the seafloor at 3 cm/kyr, how thick would the sediment be on 10-million-year-old crust?", ["3 m", "30 m", "300 m", "3,000 m"], 2, "3 cm/kyr × 10,000 kyr = 30,000 cm = 300 m."),
    ("A tsunami wave travels at about 200 m/s. How long to cross 2,000 km?", ["~2.8 hours", "~10 hours", "~1 hour", "~24 hours"], 0, "2,000,000 m / 200 m/s = 10,000 s ≈ 2.8 hours."),
    ("Isostasy predicts that if continental crust (density 2,700 kg/m³) floats on mantle (3,300 kg/m³), the fraction submerged is about:", ["20%", "50%", "82%", "95%"], 2, "Submerged fraction = ρ_crust/ρ_mantle = 2,700/3,300 ≈ 0.82."),
    ("A bathymetric survey shows the seafloor is 4,000 m deep. Sound speed is 1,500 m/s. Sonar round-trip time is:", ["2.67 s", "5.33 s", "8.00 s", "1.33 s"], 1, "t = 2d/v = 2(4,000)/1,500 = 5.33 s."),
    ("If Hawaii moves NW at 7 cm/yr and the hot spot trail shows a bend 47 Ma ago, the Pacific plate changed direction:", ["gradually over 100 Ma", "abruptly around 47 Ma from more northerly to northwesterly", "not at all", "only in the last 1 Ma"], 1, "The Emperor-Hawaiian bend records a change in plate motion ~47 Ma."),
    ("Heat flow at a mid-ocean ridge is typically _____ compared to old ocean crust.", ["lower", "the same", "higher (young, thin lithosphere near magma)", "zero"], 2, "Thin crust + nearby magma = high heat flow."),
    ("Calculating total displacement from multiple GPS measurements over 5 years uses:", ["a single reading", "averaging the measurements and multiplying by time span", "only the first measurement", "estimated global averages only"], 1, "Rate × time gives displacement."),
    ("To determine age from radiometric dating, scientists measure:", ["sediment color", "ratio of parent to daughter isotopes", "water temperature", "magnetic field direction only"], 1, "Parent/daughter ratio + known decay rate → age."),
    ("If ocean floor spreading created a 100-km-wide band of crust in 2 million years, the full rate is:", ["2.5 cm/yr", "5 cm/yr", "10 cm/yr", "50 cm/yr"], 1, "100 km / 2 Ma = 50 km/Ma = 5 cm/yr full rate."),
    ("Euler poles describe plate rotation because:", ["plates are flat rectangles", "motion on a sphere can be described as rotation about a fixed pole", "Earth doesn't rotate", "only linear motion occurs"], 1, "All plate motion is a rotation about an Euler pole."),
    ("Dimensional analysis is important in geoscience calculations to ensure:", ["numbers look pretty", "units cancel correctly and results are physically meaningful", "all values are in metric", "only integers appear"], 1, "Checking units catches errors."),
],

# ── U4: Marine Chemistry ──
"u4_l4.1": [  # Chemical Composition of Seawater
    ("Average ocean salinity is approximately:", ["3.5% (35 ppt)", "10% (100 ppt)", "0.5% (5 ppt)", "15% (150 ppt)"], 0, "Global average is about 35 parts per thousand."),
    ("The two most abundant ions in seawater are:", ["calcium and magnesium", "sodium and chloride", "potassium and sulfate", "iron and zinc"], 1, "Na⁺ and Cl⁻ make up ~86% of dissolved salts."),
    ("Salinity is higher near the equator's subtropics because:", ["rivers add more salt there", "evaporation exceeds precipitation in those regions", "organisms produce salt", "polar ice melts add salt"], 1, "Subtropical high-pressure zones have high evaporation, low rainfall."),
    ("The principle of constant proportions states that:", ["salinity is the same everywhere", "the ratios of major ions in seawater are nearly constant worldwide", "all ocean water has pH 7", "tides don't change chemistry"], 1, "Forchhammer's principle: relative proportions stay constant."),
    ("Salinity is lowest near:", ["river mouths and areas of heavy precipitation", "the subtropics", "deep ocean trenches", "mid-ocean ridges"], 0, "Freshwater input dilutes salinity."),
    ("Seawater's buffering capacity depends largely on the:", ["nitrogen cycle", "carbonate system (CO₂, HCO₃⁻, CO₃²⁻)", "iron cycle", "phosphorus cycle"], 1, "The carbonate buffering system stabilizes ocean pH."),
    ("The normal pH range of surface seawater is:", ["5.0–6.0", "6.0–7.0", "7.8–8.3", "9.0–10.0"], 2, "Slightly alkaline due to carbonate buffering."),
    ("Dissolved oxygen in seawater is highest at:", ["deep ocean trenches", "the surface (contact with atmosphere and photosynthesis)", "the oxygen minimum zone", "hydrothermal vents"], 1, "Surface water gains O₂ from the atmosphere and phytoplankton."),
    ("The oxygen minimum zone (OMZ) occurs at ~200–1,000 m because:", ["photosynthesis maxes out there", "decomposition consumes O₂ with no replenishment from the surface", "deep currents bring oxygen there", "organisms produce excess oxygen"], 1, "Sinking organic matter decomposes, using up oxygen."),
    ("Conservative elements in seawater are those whose:", ["concentrations vary wildly", "concentrations change only with salinity (not biological processes)", "concentrations are always zero", "ratios are never constant"], 1, "Na, Cl, Mg, K behave conservatively."),
    ("Non-conservative elements (like nitrogen, phosphorus, silicon) are influenced by:", ["only physical mixing", "biological uptake and release (nutrient cycling)", "nothing at all", "Earth's rotation only"], 1, "Organisms consume these nutrients, then decomposition releases them."),
    ("Residence time of an ion measures:", ["how deep it sinks", "how long it stays in the ocean before being removed", "the ion's atomic mass", "the ion's charge"], 1, "Residence time = amount in ocean / rate of input or removal."),
    ("Sodium has a very long residence time (~260 My) because:", ["it's consumed rapidly by organisms", "it's very unreactive and not easily removed from seawater", "it evaporates quickly", "rivers don't supply it"], 1, "Highly soluble, few removal mechanisms."),
    ("Desalination removes salt from seawater using methods like:", ["freezing only", "reverse osmosis or distillation", "adding more water", "magnetic separation"], 1, "RO pushes water through a membrane; distillation evaporates and condenses."),
    ("The halocline is a layer where _____ changes rapidly with depth.", ["temperature", "salinity", "pressure", "light"], 1, "Halocline = sharp salinity gradient."),
    ("The thermocline is a layer where _____ changes rapidly with depth.", ["salinity", "temperature", "density directly", "nutrient levels"], 1, "Temperature drops sharply through the thermocline."),
    ("Pycnocline refers to a rapid change in:", ["pH", "density", "oxygen levels", "salinity only"], 1, "Pycnocline = density gradient (driven by T and S changes)."),
    ("Trace elements in seawater (e.g., iron, zinc) are important because:", ["they raise salinity significantly", "they are essential micronutrients for marine organisms", "they determine water color alone", "they have no biological role"], 1, "Many trace metals are limiting nutrients for phytoplankton."),
    ("Iron fertilization hypotheses suggest adding iron to the ocean could:", ["increase salinity", "stimulate phytoplankton growth and CO₂ drawdown", "decrease oxygen levels", "eliminate all marine life"], 1, "Iron limits phytoplankton in some ocean regions."),
    ("Conductivity-Temperature-Depth (CTD) instruments measure:", ["fish populations", "salinity (via conductivity), temperature, and depth simultaneously", "only oxygen levels", "only pH levels"], 1, "CTD profiles are fundamental to physical oceanography."),
],
"u4_l4.2": [  # Gas Exchange (Oxygen, Carbon Dioxide)
    ("Oxygen enters the ocean primarily through:", ["volcanic eruptions only", "gas exchange at the surface and photosynthesis", "deep-sea vents", "chemical reactions in sediment"], 1, "Surface atmosphere contact and phytoplankton produce O₂."),
    ("CO₂ dissolves more readily in _____ water.", ["warm", "cold", "salty", "acidic"], 1, "Cold water holds more dissolved gas."),
    ("The biological pump refers to:", ["mechanical water pumps on ships", "the transfer of carbon from surface to deep ocean via sinking organisms", "photosynthesis at the surface alone", "air-sea gas exchange only"], 1, "Sinking organic matter transports carbon to the deep."),
    ("The solubility pump describes CO₂ dissolving because:", ["winds push CO₂ into the water", "cold water at high latitudes absorbs CO₂, then sinks carrying it deep", "pressure forces CO₂ in at depth", "organisms breathe it in"], 1, "Cold, CO₂-rich water sinks at high latitudes."),
    ("Henry's Law relates the amount of dissolved gas to:", ["water depth", "the gas's partial pressure in the atmosphere above", "salinity alone", "the water's age"], 1, "Dissolved gas concentration ∝ partial pressure."),
    ("Photosynthesis in the ocean: 6CO₂ + 6H₂O → C₆H₁₂O₆ + :", ["6N₂", "6O₂", "6CO₂", "6H₂"], 1, "Produces organic matter + oxygen."),
    ("Respiration reverses photosynthesis, consuming O₂ and releasing:", ["N₂", "CO₂", "O₃", "H₂"], 1, "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O."),
    ("The ocean acts as a carbon sink because it absorbs about _____ of anthropogenic CO₂.", ["5%", "25–30%", "75%", "99%"], 1, "The ocean has absorbed roughly 25–30% of human CO₂ emissions."),
    ("Oxygen production in the ocean is dominated by:", ["kelp forests", "coral reefs", "phytoplankton (especially in the euphotic zone)", "deep-sea organisms"], 2, "Phytoplankton produce ~50% of Earth's O₂."),
    ("Dead zones (hypoxic areas) form when:", ["too much oxygen accumulates", "excess nutrients fuel algal blooms; decomposition depletes O₂", "the ocean gets too cold", "coral bleaching occurs"], 1, "Eutrophication → algal bloom → decomposition → O₂ depletion."),
    ("The Revelle factor measures:", ["ocean temperature sensitivity", "how efficiently the ocean absorbs additional CO₂", "wave height", "nutrient concentration"], 1, "Higher Revelle factor = less efficient CO₂ uptake."),
    ("Gas exchange rate between ocean and atmosphere increases with:", ["decreasing wind speed", "increasing wind speed (more surface turbulence)", "warmer water temperatures", "lower salinity only"], 1, "Wind-driven mixing enhances air-sea gas transfer."),
    ("Dissolved organic carbon (DOC) in the ocean represents:", ["a small, insignificant carbon pool", "a vast carbon reservoir comparable to atmospheric CO₂", "only living organisms", "inorganic minerals"], 1, "DOC is one of the largest reactive carbon pools on Earth."),
    ("Deoxygenation (global ocean oxygen loss) is linked to:", ["decreasing temperatures", "warming waters (less soluble O₂) and increased stratification", "increased wind speeds", "lower atmospheric CO₂"], 1, "Warmer water holds less O₂ and stratification reduces mixing."),
    ("In upwelling zones, deep water brings _____ to the surface.", ["warm, oxygen-rich water", "cold, nutrient-rich (but O₂-poor) water", "freshwater", "sediment only"], 1, "Deep water is cold, rich in nutrients from decomposition, lower in O₂."),
    ("Dissolved inorganic carbon (DIC) includes:", ["CO₂, HCO₃⁻, and CO₃²⁻", "only CO₂", "only carbonate ions", "methane and ethane"], 0, "DIC = dissolved CO₂ + bicarbonate + carbonate."),
    ("The compensation depth for photosynthesis is where:", ["O₂ production exceeds respiration", "photosynthesis equals respiration", "no light penetrates at all", "temperature equals zero"], 1, "Below this depth, net O₂ production is zero."),
    ("Methane seeps on the seafloor release CH₄ that can be:", ["purely inert", "oxidized by bacteria before reaching the surface", "only absorbed by sediment", "directly photosynthesized"], 1, "Methanotrophic bacteria consume much of the methane."),
    ("Carbon sequestration strategies include:", ["burning more fossil fuels", "enhancing the biological pump and ocean alkalinity", "reducing ocean currents", "eliminating phytoplankton"], 1, "Boosting natural carbon sinks."),
    ("Measuring dissolved O₂ is commonly done with:", ["a Geiger counter", "a Winkler titration or optical sensor", "a pH meter only", "a thermometer"], 1, "Winkler method and modern optical DO sensors."),
],
"u4_l4.3": [  # Ocean Acidification
    ("Ocean acidification is caused by:", ["excess nitrogen deposition", "increased CO₂ absorption lowering ocean pH", "volcanic acid emissions only", "decrease in salinity"], 1, "CO₂ + H₂O → H₂CO₃ → H⁺ + HCO₃⁻ → lower pH."),
    ("Since pre-industrial times, ocean pH has dropped by about:", ["2.0 units", "0.1 units", "0.5 units", "1.0 unit"], 1, "From ~8.2 to ~8.1 (a ~30% increase in H⁺ concentration)."),
    ("A pH drop of 0.1 corresponds to a _____ increase in H⁺ ion concentration.", ["1%", "10%", "~26% (nearly 30%)", "100%"], 2, "pH is logarithmic: 10^0.1 ≈ 1.26, so ~26% more H⁺."),
    ("Organisms most affected by acidification are those that build shells from:", ["silica", "calcium carbonate (CaCO₃)", "iron oxide", "collagen"], 1, "Lower pH + lower CO₃²⁻ → harder to calcify."),
    ("Pteropods (sea butterflies) are vulnerable because:", ["they are very large", "their thin aragonite shells dissolve in more acidic water", "they live only in freshwater", "they don't have shells"], 1, "Aragonite is more soluble than calcite under low saturation."),
    ("Coral reefs are threatened by acidification because:", ["corals prefer acidic water", "reduced carbonate ion availability slows coral skeleton building", "acidic water increases coral growth", "corals don't use CaCO₃"], 1, "Less CO₃²⁻ → slower calcification → weaker reef structures."),
    ("The carbonate saturation state (Ω) measures:", ["water temperature", "the degree to which seawater favors CaCO₃ formation or dissolution", "salinity levels", "dissolved O₂ concentration"], 1, "Ω > 1 favors formation; Ω < 1 favors dissolution."),
    ("Aragonite saturation is declining fastest in:", ["tropical surface waters", "cold, high-latitude waters (which already have lower Ω)", "deep hydrothermal vents", "river estuaries only"], 1, "Cold water naturally has lower carbonate saturation."),
    ("Ocean acidification also affects:", ["only calcifying organisms", "fish behavior, sensory abilities, and larval development", "nothing beyond shells", "only deep-sea organisms"], 1, "Elevated CO₂ can impair fish neurological function."),
    ("CO₂ emissions from fossil fuels are the primary driver of:", ["only atmospheric warming", "both atmospheric warming and ocean acidification", "only ocean warming", "neither warming nor acidification"], 1, "CO₂ drives both climate change and ocean chemistry change."),
    ("The Southern Ocean absorbs disproportionate CO₂ because:", ["it's small", "its cold waters and strong winds enhance CO₂ uptake", "it has no marine life", "it has the highest salinity"], 1, "Cold + windy = efficient CO₂ absorption."),
    ("Laboratory experiments on acidification use:", ["only field observations", "controlled CO₂ levels (mesocosms) to simulate future ocean conditions", "computer models exclusively", "satellite data only"], 1, "Mesocosm experiments manipulate CO₂ and measure organism responses."),
    ("Natural CO₂ seeps (like off Ischia, Italy) serve as:", ["tourist attractions only", "natural laboratories to study long-term acidification effects", "sources of freshwater", "sites with no relevance to science"], 1, "Volcanic CO₂ seeps lower local pH, allowing ecological studies."),
    ("Coccolithophores may be _____ by moderate acidification.", ["destroyed entirely", "unaffected", "stimulated (some species grow more under higher CO₂)", "turned into corals"], 2, "Some species benefit from more dissolved CO₂ for photosynthesis."),
    ("Economic impacts of acidification include threats to:", ["landlocked industries only", "shellfish aquaculture, fisheries, and coral reef tourism", "oil drilling operations", "freshwater agriculture only"], 1, "Shellfish, coral reef tourism, and fisheries are at risk."),
    ("Reducing CO₂ emissions is the most effective way to:", ["increase acidification", "slow both warming and ocean acidification", "have no effect on the ocean", "only reduce air pollution"], 1, "Addressing the root cause."),
    ("Ocean alkalinity enhancement proposes adding _____ to buffer pH.", ["acid", "mineral bases like olivine or lime", "freshwater only", "nitrogen"], 1, "Increasing alkalinity absorbs more CO₂ and raises pH."),
    ("Monitoring ocean pH over time requires:", ["a single measurement", "sustained observations from buoys, ships, and autonomous sensors", "only satellite data", "only historical records"], 1, "Long-term monitoring networks track pH trends."),
    ("The combination of warming, deoxygenation, and acidification is called:", ["the triple threat or oceanic deadly trio", "a single environmental problem", "a temporary fluctuation", "the oceanic improvement cycle"], 0, "Three stressors amplify each other's impact on marine life."),
    ("Paleoclimate records show past acidification events occurred during:", ["ice ages", "periods of massive CO₂ release (e.g., PETM, 56 Ma)", "magnetic reversals", "continental collisions only"], 1, "The Paleocene-Eocene Thermal Maximum involved rapid CO₂ release."),
],
"u4_l4.4": [  # Nutrient Cycles (Nitrogen, Phosphorus)
    ("The three primary nutrients limiting marine productivity are:", ["carbon, oxygen, hydrogen", "nitrogen, phosphorus, and iron (or silicon for diatoms)", "sodium, chloride, calcium", "gold, silver, copper"], 1, "N, P, and Fe (or Si) limit phytoplankton growth."),
    ("Nitrogen enters the ocean primarily through:", ["only volcanic activity", "atmospheric deposition, river runoff, and nitrogen fixation", "deep-sea vents only", "absorption from rocks"], 1, "Multiple pathways introduce nitrogen to the marine environment."),
    ("Nitrogen fixation converts N₂ gas into:", ["nitrate (NO₃⁻)", "ammonium (NH₄⁺) usable by organisms", "nitrogen dioxide (NO₂)", "pure nitrogen metal"], 1, "Diazotrophs like Trichodesmium fix N₂ to NH₄⁺."),
    ("Nitrification converts ammonium (NH₄⁺) to:", ["N₂ gas", "nitrate (NO₃⁻) via nitrite (NO₂⁻)", "organic nitrogen", "phosphate"], 1, "Bacterial oxidation: NH₄⁺ → NO₂⁻ → NO₃⁻."),
    ("Denitrification converts nitrate back to:", ["ammonium", "N₂ gas (removing bioavailable nitrogen)", "nitrite only", "protein"], 1, "Occurs in low-oxygen zones, returning N to the atmosphere."),
    ("Phosphorus enters the ocean mainly from:", ["the atmosphere", "weathering of continental rocks carried by rivers", "deep-sea volcanic eruptions only", "space debris"], 1, "Phosphorus has no significant atmospheric phase."),
    ("The Redfield ratio (C:N:P ≈ 106:16:1) describes:", ["atmospheric gas composition", "the average elemental ratio in marine phytoplankton", "seawater salinity ratios", "ocean current speeds"], 1, "Phytoplankton incorporate C, N, P in roughly this ratio."),
    ("Upwelling is important for nutrients because it:", ["removes nutrients from the surface", "brings nutrient-rich deep water to the sunlit surface", "only moves warm water", "creates hurricanes"], 1, "Deep water is enriched in nutrients from decomposition."),
    ("Eutrophication in coastal waters is caused by:", ["too little nutrient input", "excess nutrient input (N, P) from agricultural and urban runoff", "cold water intrusion", "lack of sunlight"], 1, "Nutrient overload → algal blooms → oxygen depletion."),
    ("Dead zones result from eutrophication because:", ["too much oxygen accumulates", "massive algal blooms die and decompose, consuming all oxygen", "nutrients poison fish directly", "sediment smothers all organisms"], 1, "Decomposition of bloom biomass depletes O₂."),
    ("Iron is a limiting micronutrient in:", ["coastal waters near rivers", "HNLC (high-nutrient, low-chlorophyll) regions like the Southern Ocean", "tropical coral reefs only", "freshwater lakes only"], 1, "Iron limits phytoplankton growth despite ample N and P."),
    ("Silicon is essential for:", ["all marine bacteria", "diatoms (to build silica frustules)", "fish bone growth", "coral reef building"], 1, "Diatoms need dissolved silica for their shells."),
    ("Nutrient profiles (concentration vs. depth) typically show:", ["high nutrients at the surface, low at depth", "low nutrients at the surface (used by phytoplankton), increasing with depth", "constant nutrients throughout", "nutrients only at the seafloor"], 1, "Surface depletion by biology, deep enrichment by decomposition."),
    ("The microbial loop recycles dissolved organic matter through:", ["large fish", "bacteria and protists, returning nutrients to the food web", "sediment burial only", "atmospheric exchange"], 1, "Bacteria consume DOM; protists eat bacteria → nutrients recycled."),
    ("Anammox (anaerobic ammonium oxidation) removes nitrogen by:", ["combining NH₄⁺ and NO₂⁻ to produce N₂ directly", "converting NO₃⁻ to NH₄⁺", "fixing atmospheric N₂", "producing nitric oxide only"], 0, "Anammox bacteria convert NH₄⁺ + NO₂⁻ → N₂ + 2H₂O."),
    ("Nutrient spiraling in estuaries describes how nutrients:", ["move in a straight line", "cycle between dissolved and particulate forms while being transported downstream", "never change form", "only accumulate in sediments"], 1, "Alternating uptake and release during downstream transport."),
    ("Agricultural fertilizer runoff reaching the ocean contains excess:", ["carbon dioxide only", "nitrogen and phosphorus (from fertilizers)", "heavy metals exclusively", "oxygen"], 1, "Fertilizer N and P drive coastal eutrophication."),
    ("The Gulf of Mexico dead zone is primarily caused by:", ["overfishing", "nutrient runoff from the Mississippi River watershed", "natural upwelling", "volcanic activity"], 1, "Agricultural nutrients from the Mississippi drive seasonal hypoxia."),
    ("Monitoring nutrient levels in the ocean uses:", ["only visual observation", "water sampling, colorimetric analysis, and continuous sensors", "satellite images alone", "sound waves"], 1, "Chemical analysis of water samples plus automated sensors."),
    ("Balancing nutrient inputs to prevent eutrophication requires:", ["increasing fertilizer use", "reducing agricultural runoff, improving wastewater treatment, and using buffer zones", "eliminating all farming", "adding more nutrients to the ocean"], 1, "Multi-pronged approach to nutrient management."),
],
"u4_l4.5": [  # Case Studies in Marine Chemistry
    ("The Great Barrier Reef bleaching events are linked to:", ["increased salinity only", "elevated sea temperatures and ocean acidification stress", "volcanic eruptions nearby", "overfishing exclusively"], 1, "Thermal stress + acidification → coral bleaching."),
    ("The Deepwater Horizon oil spill (2010) released about:", ["1,000 barrels of oil", "~4.9 million barrels of oil into the Gulf of Mexico", "only natural gas", "100 barrels of oil"], 1, "One of the largest marine oil spills in history."),
    ("Chemical dispersants used after oil spills work by:", ["solidifying the oil", "breaking oil into smaller droplets that bacteria can more easily degrade", "evaporating the oil instantly", "converting oil to freshwater"], 1, "Dispersants increase the surface area for microbial degradation."),
    ("Mercury bioaccumulation in the ocean food chain means:", ["mercury dilutes at higher trophic levels", "mercury concentrations increase at each trophic level (biomagnification)", "mercury is harmless to all organisms", "mercury only affects plants"], 1, "Top predators like tuna accumulate the highest mercury levels."),
    ("The Minamata disease case study involved:", ["excess salt in drinking water", "methylmercury contamination of seafood in Japan", "radiation from nuclear testing", "iron overload in seawater"], 1, "Industrial mercury discharge contaminated fish, poisoning thousands."),
    ("Plastic pollution in the ocean introduces chemicals like:", ["pure water", "phthalates and bisphenol A (BPA) that can leach from plastics", "beneficial vitamins", "oxygen only"], 1, "Plastics release harmful additives into seawater."),
    ("Microplastics (< 5 mm) in the ocean are concerning because:", ["they're easily visible and removable", "they're ingested by marine organisms and enter the food chain", "they naturally degrade within days", "they only float on the surface"], 1, "Widespread ingestion from plankton to whales."),
    ("Ocean iron fertilization experiments (e.g., SOFeX) showed:", ["iron has no effect on phytoplankton", "iron additions stimulated phytoplankton blooms in HNLC waters", "iron killed all marine life", "iron only affects freshwater organisms"], 1, "Confirming iron limitation in HNLC regions."),
    ("The pH of the surface ocean near volcanic CO₂ seeps is:", ["higher than normal", "lower than normal (more acidic) due to elevated CO₂", "unchanged by the volcanic input", "extremely basic"], 1, "Natural laboratory for studying acidification impacts."),
    ("Harmful algal blooms (HABs) can produce:", ["beneficial nutrients only", "toxins like domoic acid and brevetoxin that harm marine life and humans", "fresh drinking water", "excess oxygen benefiting fish"], 1, "HAB toxins cause shellfish poisoning and fish kills."),
    ("Red tides are caused by:", ["iron-rich sediment stirred up by storms", "blooms of dinoflagellates (some toxic) that color the water", "volcanic eruptions at sea", "oil spill byproducts"], 1, "Karenia brevis and similar dinoflagellates cause red tides."),
    ("The Antarctic ozone hole affects marine chemistry by:", ["increasing UV-B radiation, which harms phytoplankton", "increasing salinity", "warming the deep ocean", "creating new ocean currents"], 0, "More UV-B can damage phytoplankton DNA and productivity."),
    ("Radioactive contamination from Fukushima (2011) was tracked in:", ["only the immediate vicinity", "Pacific Ocean currents across thousands of kilometers", "the Atlantic only", "freshwater lakes only"], 1, "Cesium-137 was detected far across the Pacific."),
    ("Pharmaceutical pollution in the ocean comes from:", ["natural rock weathering only", "wastewater discharge containing medications and personal care products", "deep-sea volcanic vents", "atmospheric deposition of minerals"], 1, "Incomplete wastewater treatment releases pharmaceuticals."),
    ("PFAS ('forever chemicals') persist in the ocean because:", ["marine bacteria quickly break them down", "their carbon-fluorine bonds are extremely stable", "they evaporate rapidly", "sunlight destroys them instantly"], 1, "C-F bonds are among the strongest in organic chemistry."),
    ("Coral skeleton chemistry serves as a climate proxy because:", ["corals don't incorporate environmental signals", "the ratio of Sr/Ca and δ¹⁸O in coral records past sea temperatures", "corals only grow at constant temperature", "coral chemistry is random"], 1, "Chemical analysis of coral skeletons reconstructs past ocean conditions."),
    ("Marine sediment chemistry near river deltas often shows:", ["no human influence", "elevated levels of heavy metals and pesticides from land runoff", "identical chemistry to open ocean", "only natural mineral content"], 1, "River discharge carries anthropogenic pollutants."),
    ("Blue carbon refers to carbon stored in:", ["glacier ice", "coastal ecosystems (mangroves, seagrasses, salt marshes)", "deep-sea organisms only", "atmospheric clouds"], 1, "Coastal vegetated ecosystems sequester significant carbon."),
    ("Studying chemical tracers (CFCs, tritium) in the ocean helps:", ["only identify pollution", "track deep water circulation patterns and ventilation rates", "measure fish populations", "predict hurricane paths"], 1, "Tracers reveal how deep water forms and circulates."),
    ("Future marine chemistry research priorities include:", ["ignoring ongoing problems", "improving monitoring of acidification, deoxygenation, and pollution in a changing climate", "ceasing all ocean research", "focusing only on salinity"], 1, "Continued monitoring is essential as the ocean changes."),
],
"u4_l4.6": [  # AP Prep: Chemical Equilibria in Oceans
    ("The carbonate system equilibrium is: CO₂ + H₂O ⇌ H₂CO₃ ⇌ H⁺ + HCO₃⁻ ⇌:", ["H₂ + CO₃²⁻", "2H⁺ + CO₃²⁻", "Na⁺ + Cl⁻", "OH⁻ + CO₂"], 1, "Full dissociation: H₂CO₃ → H⁺ + HCO₃⁻ → 2H⁺ + CO₃²⁻."),
    ("Le Chatelier's principle predicts that adding CO₂ to the ocean will:", ["shift equilibrium right, producing more H⁺ and lowering pH", "shift equilibrium left, increasing pH", "have no effect on pH", "remove all bicarbonate"], 0, "More CO₂ drives the reaction forward → more H⁺."),
    ("Bicarbonate (HCO₃⁻) is the dominant inorganic carbon species at:", ["pH < 6", "pH 7.8–8.3 (normal ocean pH)", "pH > 10", "pH = 0"], 1, "At typical ocean pH, ~90% of DIC is HCO₃⁻."),
    ("The solubility product (Ksp) of CaCO₃ determines:", ["ocean salinity", "whether calcite/aragonite precipitates or dissolves", "water temperature", "nitrogen fixation rates"], 1, "If ion product > Ksp → precipitation; if < Ksp → dissolution."),
    ("Increasing temperature generally:", ["decreases the solubility of gases like CO₂ and O₂ in seawater", "increases gas solubility", "has no effect on solubility", "increases solubility of CaCO₃ everywhere"], 0, "Warmer water holds less dissolved gas."),
    ("The total alkalinity of seawater is a measure of its:", ["salt content", "capacity to neutralize acid (buffering capacity)", "temperature", "dissolved oxygen"], 1, "Alkalinity ≈ [HCO₃⁻] + 2[CO₃²⁻] + other minor bases."),
    ("If pH drops from 8.2 to 8.0, the [H⁺] increases by a factor of:", ["0.2", "2", "~1.58 (10^0.2)", "20"], 2, "10^(8.2−8.0) = 10^0.2 ≈ 1.58."),
    ("Aragonite is more soluble than calcite because:", ["it has a different crystal structure (orthorhombic vs. trigonal)", "it contains different elements", "it has higher atomic mass", "it forms at higher temperatures always"], 0, "Same composition (CaCO₃) but different crystal structure."),
    ("At the lysocline, the dissolution rate of CaCO₃ begins to:", ["decrease sharply", "increase noticeably with depth", "become zero", "reverse direction"], 1, "Below the lysocline, dissolution accelerates."),
    ("Salinity affects gas solubility: higher salinity means:", ["more gas dissolves (salting in)", "less gas dissolves (salting out)", "no change in gas solubility", "gas solubility doubles"], 1, "Ions compete for water molecules, reducing gas solubility."),
    ("Buffer capacity is strongest when pH is near the:", ["pKa of the buffering species", "extreme of the pH scale", "freezing point of water", "salinity maximum"], 0, "Buffers work best within ~1 pH unit of their pKa."),
    ("The ocean's carbonate buffering system maintains pH near 8 because the pKa values of CO₂/HCO₃⁻ and HCO₃⁻/CO₃²⁻ bracket ocean pH:", ["exactly", "approximately, providing broad buffering", "not at all", "only at the equator"], 1, "pKa₁ ≈ 6.1 and pKa₂ ≈ 9.1 bracket typical ocean pH."),
    ("Calculating pH from dissolved CO₂ requires knowing:", ["only CO₂ concentration", "CO₂ concentration, equilibrium constants, temperature, and salinity", "ocean depth only", "chloride concentration only"], 1, "All factors affect the carbonate equilibrium."),
    ("In a closed system, adding base to seawater will:", ["not change pH", "increase pH (and shift equilibrium toward CO₃²⁻)", "decrease pH", "remove all dissolved carbon"], 1, "Base consumes H⁺ → pH rises → equilibrium shifts."),
    ("The partial pressure of CO₂ (pCO₂) in surface water drives:", ["ocean currents", "the direction of air-sea CO₂ exchange", "salinity changes", "wave formation"], 1, "CO₂ moves from high pCO₂ to low pCO₂."),
    ("If ocean pCO₂ < atmospheric pCO₂, the ocean is a:", ["source of CO₂", "sink of CO₂ (absorbing from atmosphere)", "neither source nor sink", "contributor to ozone"], 1, "Net flux from atmosphere into the ocean."),
    ("DIC budget: DIC = [CO₂(aq)] + [HCO₃⁻] + [CO₃²⁻]. As pH decreases:", ["[CO₃²⁻] increases", "[CO₂(aq)] increases and [CO₃²⁻] decreases", "all species decrease equally", "[HCO₃⁻] disappears"], 1, "Lower pH shifts equilibrium toward CO₂(aq)."),
    ("A Bjerrum plot shows the relative concentrations of:", ["temperature vs. salinity at different depths", "CO₂, HCO₃⁻, and CO₃²⁻ as a function of pH", "nutrient levels across ocean basins", "dissolved oxygen vs. depth"], 1, "Visualizes the carbonate species distribution."),
    ("Equilibrium calculations for ocean chemistry use _____ corrections.", ["no", "activity coefficients (to account for ionic strength of seawater)", "atmospheric pressure", "tidal force"], 1, "High ionic strength of seawater requires activity corrections."),
    ("Understanding chemical equilibria in the ocean is critical for predicting:", ["only tidal patterns", "the impacts of rising CO₂ on marine organisms and carbon cycling", "fish migration routes only", "earthquake locations"], 1, "Equilibrium chemistry underpins all acidification and carbon cycle predictions."),
],
}

# ── Write ──
with open(PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

count = 0
for key, qs in QUESTIONS.items():
    if key not in data:
        print(f"⚠ {key} not found"); continue
    new_list = []
    for i, (qt, opts, correct_idx, expl) in enumerate(qs):
        options = []
        for j, o in enumerate(opts):
            options.append({"text": o, "is_correct": j == correct_idx, "data_i18n": None})
        new_list.append({
            "question_number": i + 1,
            "question_text": qt,
            "attempted": 2,
            "data_i18n": None,
            "options": options,
            "explanation": expl
        })
    data[key]["quiz_questions"] = new_list
    count += 1

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"✅ Marine Science U3-U4: replaced questions for {count} lessons")
