#!/usr/bin/env python3
"""Refix Integrated Science U6 lessons 6.4-6.8 (missed in earlier pass)."""
import json, os

PATH = os.path.join("content_data", "integrated_science_lessons.json")

QUESTIONS = {
"u6_l6.4": [  # Climate Change & Global Warming
    ("The greenhouse effect is best described as:", ["a process that only occurs inside actual greenhouses", "atmospheric gases trapping infrared radiation near Earth's surface", "the Sun heating Earth without any atmospheric involvement", "a process only found on Venus and not on planet Earth"], 1, "Greenhouse gases absorb and re-emit infrared radiation."),
    ("Carbon dioxide concentration has risen primarily due to:", ["increased volcanic activity over the past century", "burning fossil fuels and land-use changes by humans", "natural ocean outgassing cycles alone without human input", "decreased plant growth reducing CO₂ consumption globally"], 1, "Anthropogenic sources dominate the recent CO₂ increase."),
    ("Methane is a potent greenhouse gas released by:", ["only deep ocean vents and no land-based sources at all", "agriculture, wetlands, and fossil fuel extraction activities", "only factories producing industrial chemicals in large cities", "only wildfires burning in tropical forest environments"], 1, "Multiple sources contribute to atmospheric methane."),
    ("Global average temperature has risen approximately:", ["10°C since 1900 based on satellite measurements", "1.1°C since pre-industrial times according to climate data", "0.01°C total over the entire recorded temperature history", "5°C per decade for the last three consecutive decades"], 1, "About 1.1°C of warming since the late 1800s."),
    ("Sea levels are rising because of:", ["only land subsidence with no ocean volume change", "thermal expansion of water and melting of land-based ice", "the Moon's gravity pulling more water toward coastlines", "increased rainfall filling oceans faster than evaporation"], 1, "Both warming water and ice melt contribute."),
    ("The Keeling Curve shows:", ["decreasing CO₂ levels since measurements first began", "a continuous rise in atmospheric CO₂ measured at Mauna Loa", "constant CO₂ levels that have never changed over time", "only seasonal cycles with no long-term upward trend"], 1, "Started in 1958; documents ongoing CO₂ increase."),
    ("Ice cores provide climate history by:", ["only showing the color of ancient ice at various depths", "trapping atmospheric gas bubbles that record past conditions", "only providing water for drinking research expedition use", "only measuring ice thickness without composition information"], 1, "Air bubbles in ice preserve past atmospheric composition."),
    ("Positive climate feedback from melting permafrost involves:", ["frozen ground absorbing extra heat and stabilizing temperatures", "release of trapped methane that causes additional atmospheric warming", "permafrost expansion into new areas as temperatures increase", "ice formation that reflects more sunlight back toward space"], 1, "Thawing permafrost releases methane, amplifying warming."),
    ("Ocean acidification results from:", ["excess oxygen dissolving into ocean surface waters", "CO₂ absorption forming carbonic acid that lowers ocean pH", "volcanic ash falling into the ocean from major eruptions", "increased salt concentration due to higher evaporation rates"], 1, "CO₂ + H₂O → H₂CO₃, lowering pH."),
    ("The IPCC (Intergovernmental Panel on Climate Change) is:", ["a single country's weather forecasting department only", "an international body that assesses climate change science", "a private company that sells carbon emission credits", "a university that only teaches atmospheric chemistry classes"], 1, "Synthesizes climate research for policymakers worldwide."),
    ("Milankovitch cycles affect climate through changes in:", ["only the chemical composition of Earth's atmosphere", "Earth's orbital eccentricity, axial tilt, and precession", "only the Sun's brightness fluctuating over short periods", "only the distance between Earth and the nearest other star"], 1, "Orbital variations alter solar energy distribution."),
    ("Climate models project future warming depends primarily on:", ["only the current temperature at the time of projection", "future greenhouse gas emission levels from human activities", "only natural volcanic eruption frequency in the future", "only ocean current patterns without atmospheric gas effects"], 1, "Emission scenarios drive different temperature outcomes."),
    ("Coral reef bleaching is triggered by:", ["cold water temperatures dropping below freezing point", "prolonged elevated water temperatures stressing symbiotic algae", "increased nutrients making corals grow too quickly", "excessive sunlight only during midday peak hours"], 1, "Thermal stress causes corals to expel zooxanthellae."),
    ("The difference between weather and climate is:", ["they are the same thing measured at different locations", "weather is short-term conditions; climate is long-term averages", "climate changes daily while weather stays constant over decades", "weather only exists in the atmosphere; climate only in oceans"], 1, "Weather = days; climate = decades."),
    ("Carbon sinks include:", ["only volcanoes that release CO₂ into the atmosphere", "forests and oceans that absorb CO₂ from the atmosphere", "only power plants that burn coal for energy production", "only deserts that have no vegetation or water present"], 1, "Natural sinks absorb roughly half of human emissions."),
    ("The albedo effect relates to warming because:", ["dark surfaces reflect more sunlight back toward outer space", "melting ice exposes dark surfaces that absorb more solar energy", "white surfaces absorb more heat than darker materials do", "albedo only affects temperatures inside enclosed buildings"], 1, "Ice-albedo feedback amplifies polar warming."),
    ("Renewable energy helps mitigate climate change by:", ["producing more greenhouse gases than fossil fuels produce", "generating electricity without direct CO₂ emissions at the source", "only being available during nighttime hours of operation", "only working in equatorial tropical regions of the world"], 1, "Solar, wind, etc. displace fossil fuel combustion."),
    ("Climate change affects biodiversity by:", ["having no impact on any species or ecosystem anywhere", "shifting habitats, altering migration, and increasing extinction risk", "only benefiting all species equally by expanding their range", "only affecting marine species and not any land organisms"], 1, "Species face habitat loss, phenology shifts, and range changes."),
    ("The Paris Agreement set a goal of limiting warming to:", ["10°C above current average global temperature levels", "well below 2°C above pre-industrial global temperature", "exactly 0°C change from any current temperature baseline", "only reducing temperature in Northern Hemisphere countries"], 1, "With an aspirational target of 1.5°C."),
    ("Individual actions to reduce carbon footprint include:", ["increasing personal fossil fuel consumption for convenience", "using public transit, reducing energy waste, and eating less meat", "only writing letters to politicians without changing behavior", "only purchasing more goods to stimulate a green economy"], 1, "Personal choices collectively impact emissions."),
],
"u6_l6.5": [  # Conservation & Restoration Strategies
    ("In situ conservation protects species by:", ["moving them to zoos far from their natural habitats", "preserving their natural habitats through protected areas", "only studying them in laboratory controlled environments", "freezing genetic samples in cryogenic storage facilities"], 1, "Conservation within natural environments."),
    ("Ex situ conservation involves:", ["only protecting large wilderness areas from any development", "maintaining species outside their natural habitat in facilities", "only planting trees to offset industrial carbon emissions", "only passing legislation without any hands-on species work"], 1, "Zoos, seed banks, and botanical gardens are examples."),
    ("Habitat corridors benefit wildlife by:", ["creating barriers that prevent all animal movement", "connecting fragmented habitats to allow species to migrate", "only providing scenic hiking trails for human recreation", "only increasing urban development between nature reserves"], 1, "Corridors reduce isolation and maintain gene flow."),
    ("Ecological restoration aims to:", ["completely replace natural areas with engineered landscapes", "return degraded ecosystems to a more natural functioning state", "only remove invasive species without any other intervention", "only document what ecosystems looked like before degradation"], 1, "Active intervention to recover ecosystem structure and function."),
    ("Seed banks preserve biodiversity by:", ["only collecting seeds from common agricultural crops", "storing diverse plant genetic material for future use", "only displaying seeds in museum collections for visitors", "only grinding seeds to produce organic fertilizer products"], 1, "Insurance against species loss and genetic diversity reduction."),
    ("Marine protected areas (MPAs) support ocean health by:", ["allowing unrestricted commercial fishing within their borders", "restricting harmful activities to let ecosystems recover", "only marking areas on maps without enforcement of rules", "only protecting surface waters and not seafloor organisms"], 1, "No-take zones can rebuild fish populations."),
    ("Reforestation differs from afforestation because:", ["they are identical terms with no difference in meaning", "reforestation plants trees where forests recently existed; afforestation creates new forests", "afforestation involves cutting down existing old-growth forest", "reforestation only uses artificial plastic trees as replacements"], 1, "Both increase forest cover but in different contexts."),
    ("Community-based conservation succeeds when:", ["local people are excluded from all decision-making processes", "local communities participate in and benefit from conservation efforts", "only international organizations make decisions about local resources", "only wealthy landowners determine conservation area boundaries"], 1, "Local engagement improves outcomes and sustainability."),
    ("The IUCN Red List classifies species by:", ["only their physical size from smallest to largest", "extinction risk categories from least concern to extinct", "only their geographic location on each continent globally", "only their economic value to human industries and commerce"], 1, "A global standard for assessing conservation status."),
    ("Captive breeding programs help endangered species by:", ["releasing animals without any preparation into the wild", "maintaining genetic diversity and providing individuals for reintroduction", "only keeping animals in captivity permanently and indefinitely", "only breeding animals for entertainment in theme park attractions"], 1, "Breeding and reintroduction support population recovery."),
    ("Wetland restoration provides benefits including:", ["only aesthetic improvements with no ecological function value", "flood control, water filtration, carbon storage, and habitat creation", "only mosquito breeding habitat and no positive ecosystem services", "only economic benefits to adjacent property values exclusively"], 1, "Wetlands provide critical ecosystem services."),
    ("Payment for ecosystem services (PES) programs:", ["require ecosystems to submit invoices for services rendered", "compensate landowners for maintaining natural services like water filtration", "only apply to tropical rainforest environments and nowhere else", "only reduce ecosystem service quality over a long time period"], 1, "Economic incentives for conservation on private land."),
    ("Invasive species management strategies include:", ["only introducing more invasive species as natural competitors", "physical removal, biological control, and prevention of new introductions", "only building fences around all native species habitat areas", "only observing invasive species without any intervention action"], 1, "Integrated management combines multiple approaches."),
    ("National parks serve conservation by:", ["allowing unrestricted resource extraction within boundaries", "protecting biodiversity, landscapes, and ecosystem processes", "only providing recreation without any conservation purpose", "only preserving historical buildings and not natural features"], 1, "Protected areas are cornerstones of conservation."),
    ("Genetic rescue involves:", ["reducing genetic diversity in small isolated populations", "introducing individuals to increase genetic variation in threatened populations", "only cloning animals in advanced biotechnology laboratory settings", "only studying genetics without any practical conservation application"], 1, "New genes can restore adaptive potential."),
    ("Citizen science contributes to conservation by:", ["only providing entertainment for amateur nature enthusiasts", "engaging the public in data collection that supports scientific research", "only replacing professional scientists with untrained volunteers", "only generating social media content about wildlife photography"], 1, "Volunteers expand monitoring capacity significantly."),
    ("Conservation easements protect land by:", ["transferring all property rights to the government permanently", "legally restricting development while the landowner retains ownership", "only applying to agricultural land and not natural habitats", "only lasting for one year before requiring complete renewal"], 1, "Permanent or long-term restrictions on land use."),
    ("Adaptive management in conservation means:", ["making a single plan and following it without any changes", "adjusting strategies based on monitoring results and new information", "only managing ecosystems during crisis events and not otherwise", "only applying management to species already classified as extinct"], 1, "Flexible, science-based management that evolves with new data."),
    ("Ecosystem-based adaptation uses:", ["only concrete infrastructure to protect against climate change", "natural ecosystems and biodiversity to help communities adapt to change", "only laboratory experiments without any field implementation", "only technology solutions without considering natural system benefits"], 1, "Nature-based solutions for climate adaptation."),
    ("The Convention on Biological Diversity aims to:", ["only catalog species without any protection requirements set", "conserve biodiversity, ensure sustainable use, and share benefits fairly", "only protect charismatic megafauna like pandas and elephants", "only regulate trade in endangered species without other goals"], 1, "A comprehensive international biodiversity framework."),
],
"u6_l6.6": [  # Future Challenges (Population Growth, Resource Scarcity)
    ("Global population is projected to reach approximately:", ["20 billion people by the year 2030 without any doubt", "9.7 billion by 2050 according to United Nations projections", "3 billion by 2100 due to dramatic worldwide decline trends", "exactly the same number as today with no growth expected"], 1, "Continued growth with regional variation."),
    ("The demographic transition model describes:", ["only birth rates without any connection to death rates", "how populations shift from high birth/death rates to low rates during development", "only migration patterns between countries during wartime", "only population changes in one specific country exclusively"], 1, "Economic development changes population dynamics."),
    ("Water scarcity affects approximately:", ["no one because freshwater is unlimited across Earth", "2 billion people who lack access to safe drinking water", "only people in desert environments and no one else anywhere", "only animals and not human populations in any location"], 1, "A growing global challenge with health and security implications."),
    ("Peak phosphorus concerns relate to:", ["unlimited phosphorus reserves that will never run out", "finite phosphate rock supplies essential for agricultural fertilizer", "only the phosphorus content in human dietary supplements", "only laboratory chemical supplies and not agricultural uses"], 1, "Phosphorus is critical for food production with limited reserves."),
    ("Urban sprawl creates environmental problems by:", ["concentrating population efficiently in a small land area", "consuming farmland, increasing car dependence, and fragmenting habitat", "only providing more green space for urban wildlife populations", "only reducing commute times by spreading population out evenly"], 1, "Low-density development has multiple environmental costs."),
    ("Food security challenges include:", ["only overproduction of food creating too much surplus waste", "growing population, climate impacts, soil degradation, and water limits", "only distribution problems with no production challenges at all", "only luxury food shortages and not staple crop supply issues"], 1, "Multiple interacting pressures threaten food systems."),
    ("Rare earth elements are critical for:", ["only decorative jewelry and gemstone cutting industries", "electronics, renewable energy technology, and advanced manufacturing", "only traditional farming tools used in rural agriculture", "only space exploration equipment and nothing on Earth itself"], 1, "Essential for modern technology with limited supply sources."),
    ("The ecological footprint measures:", ["only the physical area of land a person owns or occupies", "total resources consumed and waste generated by a population or individual", "only water consumption without any consideration of other resources", "only forest area needed to produce paper products for use"], 1, "A comprehensive measure of resource demand."),
    ("Desertification is driven by:", ["only natural climate cycles and never by human activities", "overgrazing, deforestation, poor irrigation, and climate change combined", "only flooding events that deposit sand across fertile regions", "only volcanic eruptions covering farmland with ash deposits"], 1, "Human land use and climate interact to degrade drylands."),
    ("Sustainable development goals (SDGs) were adopted by:", ["only three countries in a private agreement in 2010", "193 United Nations member states in 2015 as a global framework", "only environmental organizations without government participation", "only wealthy nations without any developing country involvement"], 1, "17 goals addressing interconnected global challenges."),
    ("Overfishing threatens ocean ecosystems by:", ["only affecting fish species that humans do not consume", "depleting fish populations below levels that can sustain reproduction", "only impacting fish in freshwater lakes and not ocean species", "only reducing fish size without affecting population numbers"], 1, "Exceeding sustainable yield leads to population collapse."),
    ("Energy transition challenges include:", ["only the technical inability to generate renewable power", "infrastructure costs, storage technology, and political barriers to change", "only aesthetic concerns about wind turbine visual appearance", "only opposition from environmental groups to all clean energy"], 1, "Multiple barriers slow the shift to clean energy."),
    ("Soil degradation reduces agricultural productivity by:", ["improving nutrient availability in all soil conditions over time", "depleting nutrients, reducing organic matter, and increasing erosion", "only changing soil color without affecting any crop yields", "only affecting decorative landscaping and not food crop production"], 1, "Degraded soil supports less agriculture."),
    ("Climate migration refers to:", ["only seasonal bird migration patterns changing with weather", "people displaced by climate impacts such as sea-level rise and drought", "only wealthy tourists choosing warmer vacation destinations", "only plant species shifting their geographic range northward"], 1, "A growing humanitarian challenge linked to climate change."),
    ("Circular economy principles aim to:", ["increase waste production for landfill disposal continuously", "minimize waste by designing products for reuse and recycling", "only apply to heavy industry and not consumer product sectors", "only reduce manufacturing costs without environmental benefits"], 1, "Reducing resource extraction and waste simultaneously."),
    ("Groundwater depletion is a concern because:", ["aquifers refill instantly whenever it rains on the surface", "many aquifers recharge slowly and are being pumped faster than replenished", "only surface water is used and groundwater is never extracted", "groundwater has no role in agricultural irrigation worldwide"], 1, "Overdrawing leads to falling water tables."),
    ("Biodiversity loss reduces ecosystem resilience by:", ["increasing the number of species interactions and stability", "removing functional redundancy and adaptive capacity from ecosystems", "only affecting species that humans find aesthetically pleasing", "only mattering in tropical forests and not temperate ecosystems"], 1, "Fewer species = less ability to cope with change."),
    ("Deforestation for agriculture contributes to:", ["increased biodiversity and improved soil quality universally", "carbon emissions, habitat loss, and altered regional water cycling", "only positive economic outcomes without any environmental costs", "only local effects with no broader climate or ecological impact"], 1, "Multiple interconnected environmental consequences."),
    ("Technology can help address resource scarcity through:", ["only increasing consumption rates for all natural resources", "improved efficiency, recycling methods, and alternative material development", "only replacing natural systems with entirely artificial substitutes", "only theoretical research that never produces practical applications"], 1, "Innovation extends resource availability and reduces waste."),
    ("Addressing future challenges requires:", ["only individual actions without any government or policy involvement", "integrated approaches combining science, policy, technology, and social change", "only waiting for problems to solve themselves naturally over time", "only economic growth without any environmental considerations needed"], 1, "Complex challenges demand multifaceted solutions."),
],
"u6_l6.7": [  # Case Studies in Environmental Policy
    ("The Montreal Protocol successfully reduced:", ["carbon dioxide emissions from power plants worldwide", "ozone-depleting substances like CFCs in the stratosphere", "only noise pollution levels in urban residential areas", "only water pollution in the Great Lakes basin region"], 1, "An international success story in environmental protection."),
    ("The Clean Air Act in the United States:", ["only applied to indoor air quality in office buildings", "set standards for air pollutants and reduced emissions significantly", "only addressed carbon dioxide and no other air pollutants", "only applied to one state and not the entire country"], 1, "Major legislation driving air quality improvement."),
    ("The European Union Emissions Trading System (EU ETS):", ["gives companies unlimited free emission permits without limits", "caps total emissions and lets companies trade allowances on a market", "only applies to agricultural emissions from livestock farming", "only monitors emissions without any enforcement or penalties"], 1, "The world's largest cap-and-trade system."),
    ("China's Three Gorges Dam illustrates trade-offs between:", ["only economic costs with no environmental considerations involved", "renewable energy generation and environmental or social displacement impacts", "only fish migration and no other ecological concern at all", "only construction engineering and no resource management issues"], 1, "Major infrastructure involves complex environmental trade-offs."),
    ("The Endangered Species Act has helped recover species like:", ["only invertebrates that were never at risk of any extinction", "the bald eagle and American alligator through legal protections", "only plant species that were listed for cosmetic appeal", "only species from outside the United States exclusively"], 1, "Legal protection enabled population recovery."),
    ("Costa Rica's payment for ecosystem services program:", ["destroyed most of the country's remaining forest areas", "reversed deforestation by compensating landowners for forest conservation", "only applied to urban parks and not rural forested areas", "only lasted one year before being completely abandoned"], 1, "A pioneering PES program with measurable results."),
    ("The Flint water crisis demonstrated:", ["that infrastructure failures have no public health consequences", "how aging infrastructure and management failures can create health emergencies", "only economic costs without any health impacts to any residents", "only temporary water discoloration with no harmful contaminants"], 1, "Lead contamination from corroded pipes harmed thousands."),
    ("The Paris Agreement differs from the Kyoto Protocol by:", ["setting binding targets only for the wealthiest nations today", "including all nations with nationally determined contributions to emissions reduction", "only addressing ocean pollution and not greenhouse gas emissions", "only applying to European Union member states and no others"], 1, "Universal participation with nationally set targets."),
    ("Brazil's deforestation monitoring (DETER/PRODES) uses:", ["only ground-based forest ranger patrols without technology", "satellite imagery to detect and track forest clearing in real time", "only voluntary self-reporting by logging companies operating there", "only aerial photography taken once every ten years consistently"], 1, "Technology enables rapid detection of illegal clearing."),
    ("The Acid Rain Program in the US used cap-and-trade to:", ["increase sulfur dioxide emissions from coal power plants", "reduce sulfur dioxide emissions more cost-effectively than regulations alone", "only address acid rain in one state without broader application", "only monitor rain acidity without any emission reduction goals"], 1, "Market mechanisms achieved reductions ahead of schedule."),
    ("The Aral Sea disaster resulted from:", ["natural drought cycles without any human water management role", "Soviet-era irrigation diversions that drained major river inflows", "only an earthquake that opened cracks in the lake bottom", "only increased evaporation from global temperature rise alone"], 1, "A cautionary case of unsustainable water management."),
    ("Rwanda's plastic bag ban demonstrates:", ["that environmental policy always fails in developing countries", "that small nations can implement effective environmental regulations", "only that bags are a cosmetic issue and not an environmental one", "only that the ban increased plastic waste dumped in waterways"], 1, "Ban reduced pollution and changed consumer behavior."),
    ("Environmental justice cases like Cancer Alley show:", ["that pollution affects all communities equally and fairly", "marginalized communities often bear disproportionate environmental burdens", "only that industrial areas have no health effects on residents", "only economic benefits to communities near industrial facilities"], 1, "Inequitable distribution of environmental hazards."),
    ("The Great Barrier Reef Marine Park Authority manages:", ["only commercial fishing operations and not conservation efforts", "reef protection through zoning, monitoring, and adaptive management", "only tourism activities without any ecosystem management work", "only one small section of the reef and not the entire system"], 1, "Comprehensive management of a World Heritage site."),
    ("Japan's Minamata Convention addresses:", ["only noise pollution from industrial manufacturing facilities", "mercury pollution prevention, reduction, and elimination globally", "only water treatment standards for drinking water systems", "only radioactive waste management from nuclear power plants"], 1, "Named after the mercury poisoning disaster in Minamata."),
    ("California's cap-and-trade program links with:", ["no other jurisdiction's emission trading system at all", "Quebec's system, creating a cross-border carbon market mechanism", "only federal US programs and no international partnerships", "only private company voluntary offset purchasing programs"], 1, "Linked markets expand the scope of emission reduction."),
    ("The Chesapeake Bay restoration involves:", ["only one state acting without any coordinated regional effort", "multi-state cooperation to reduce nutrient pollution and restore habitats", "only dredging the bay bottom without addressing pollution sources", "only commercial fishing regulation and no water quality goals"], 1, "Watershed-scale restoration requires multi-jurisdictional cooperation."),
    ("Lessons from environmental policy case studies show:", ["every policy works perfectly the first time it is implemented", "effective policy requires science, enforcement, adaptation, and public support", "only top-down government mandates work without public involvement", "only voluntary industry action succeeds without any regulation"], 1, "Multiple factors determine policy success."),
    ("Indigenous land management practices demonstrate:", ["that traditional knowledge has no value for modern conservation", "effective long-term stewardship that often improves biodiversity outcomes", "only historical interest without any practical applications today", "only ceremonial practices and not any ecological management skills"], 1, "Traditional ecological knowledge complements Western science."),
    ("Comparing environmental policies across countries reveals:", ["that all countries face identical environmental challenges and solutions", "different contexts require different approaches but share common principles", "only wealthy nations can implement any environmental protections", "that environmental policy never achieves any measurable results"], 1, "Context matters, but evidence-based principles apply broadly."),
],
"u6_l6.8": [  # AP Prep: Climate Models
    ("Climate models are based on:", ["random guesses about future temperature changes only", "physics equations governing atmosphere, ocean, land, and ice processes", "only historical temperature measurements without any physics", "only personal opinions of individual climate scientists alone"], 1, "Conservation of energy, mass, and momentum."),
    ("General Circulation Models (GCMs) divide Earth into:", ["only two hemispheres without further spatial detail required", "a three-dimensional grid of cells solving equations at each point", "only latitude bands without any longitudinal resolution at all", "only land and ocean without any atmospheric component included"], 1, "3D grids capture spatial variation in climate processes."),
    ("Climate model resolution affects:", ["nothing about the quality or usefulness of model output", "the ability to represent small-scale features like clouds and topography", "only the visual appearance of output maps and nothing else", "only the speed of computation and not the accuracy of results"], 1, "Higher resolution captures more detail but costs more computation."),
    ("Emission scenarios (RCPs/SSPs) represent:", ["only one possible climate future that is certain to occur", "a range of possible future greenhouse gas emission pathways", "only historical emission data from the past 100 years period", "only natural emission sources and not any human contributions"], 1, "Scenarios explore different socioeconomic and emission futures."),
    ("Parameterization in climate models handles:", ["only the largest-scale global circulation patterns modeled", "sub-grid-scale processes like cloud formation and turbulence", "only the initial temperature conditions at the model start time", "only output formatting for publication in scientific journals"], 1, "Processes smaller than grid cells need approximate representations."),
    ("Model ensembles provide:", ["only a single definitive answer about future climate conditions", "a range of possible outcomes that helps quantify uncertainty", "only identical outputs from every model run in the ensemble", "only artistic visualizations without any scientific information"], 1, "Multiple runs reveal the range and likelihood of outcomes."),
    ("Validating climate models involves:", ["only checking that the code compiles without programming errors", "comparing model outputs to observations and paleoclimate records", "only asking modelers if they believe their results are correct", "only running the model once and accepting whatever output appears"], 1, "Hindcasting and comparison to data test model reliability."),
    ("Climate sensitivity refers to warming from:", ["a 10% increase in solar luminosity over one century", "a doubling of atmospheric CO₂ above pre-industrial concentrations", "reducing all greenhouse gases to zero instantaneously", "increasing the Earth's orbital distance from the Sun by half"], 1, "Estimated at approximately 2.5-4°C per CO₂ doubling."),
    ("Feedbacks in climate models include:", ["only negative feedbacks and never any positive ones at all", "ice-albedo, water vapor, cloud, and carbon cycle interactions", "only human behavioral responses to temperature change impacts", "only solar output variations over geological time periods"], 1, "Multiple feedbacks amplify or dampen initial changes."),
    ("Downscaling provides:", ["less useful information than global model output alone gives", "regional climate detail by translating global projections to local scales", "only theoretical results with no practical application at all", "only global averages without any regional differentiation used"], 1, "Regional planning requires localized projections."),
    ("Uncertainty in climate projections comes from:", ["only measurement errors in thermometers at weather stations", "emission scenarios, model physics, and natural internal variability", "only the programming language used to code the models today", "only differences between research group funding levels worldwide"], 1, "Multiple sources of uncertainty affect projections."),
    ("Earth System Models extend climate models by adding:", ["only atmospheric chemistry and nothing from other Earth systems", "biogeochemical cycles, vegetation dynamics, and carbon feedbacks", "only solar energy calculations without any land or ocean parts", "only ice sheet models without any other component additions"], 1, "Coupling physical climate with biological and chemical cycles."),
    ("Tipping points in climate models represent:", ["gradual predictable changes that are easily reversed over time", "thresholds where abrupt, potentially irreversible state changes occur", "only theoretical concepts without any observational evidence found", "only temperatures at which all climate models stop working"], 1, "Ice sheet collapse and forest dieback are potential tipping points."),
    ("Interpreting model output on the AP exam requires:", ["only reading numbers from graphs without any critical analysis", "evaluating assumptions, uncertainties, and the implications of different scenarios", "only memorizing specific temperature projections for the year 2100", "only learning the names of all major climate modeling centers"], 1, "Critical analysis of model results is an AP skill."),
    ("The CMIP (Coupled Model Intercomparison Project) helps by:", ["ensuring all models produce exactly identical output results", "comparing models from different groups to find robust conclusions and disagreements", "only archiving old model code that is no longer used today", "only ranking models from best to worst on a public list"], 1, "Multi-model comparison strengthens confidence in shared findings."),
    ("Aerosol effects in climate models are uncertain because:", ["aerosols have no interaction with climate whatsoever at all", "aerosol-cloud interactions are complex and vary by composition and location", "all aerosols behave identically regardless of their type", "only black carbon matters and no other aerosol type exists"], 1, "Aerosols can cool or warm depending on type and cloud interactions."),
    ("Carbon budgets from models tell us:", ["that unlimited CO₂ can be emitted with no temperature consequence", "how much CO₂ can still be emitted to stay within a temperature target", "only how much carbon exists in Earth's crust in total", "only historical emissions without any future emission implications"], 1, "Remaining budget for 1.5°C or 2°C targets."),
    ("Bias correction adjusts model output by:", ["adding random errors to increase uncertainty in the results", "statistically aligning simulations with observed climate data patterns", "only removing all variability from the model output completely", "only changing the color scheme of maps produced by models"], 1, "Reduces systematic differences between models and observations."),
    ("Communicating climate model results effectively requires:", ["using only technical jargon that policymakers cannot understand", "clear language about findings, confidence levels, and limitations of projections", "only presenting best-case scenarios to avoid alarming audiences", "only showing raw data tables without any visual representations"], 1, "Translation from science to actionable information."),
    ("The value of climate models for the AP exam is:", ["no connection between modeling and the AP science curriculum", "developing critical thinking about data, uncertainty, and scientific reasoning", "only providing specific numbers to memorize for test questions", "only relevant for students pursuing careers in computer programming"], 1, "Analytical skills apply across all scientific disciplines."),
],
}

with open(PATH, "r", encoding="utf-8") as f:
    data = json.load(f)
count = 0
for key, qs in QUESTIONS.items():
    if key not in data:
        print(f"⚠ {key} not found"); continue
    new_list = []
    for i, (qt, opts, ci, expl) in enumerate(qs):
        options = []
        for j, o in enumerate(opts):
            options.append({"text": o, "is_correct": j == ci, "data_i18n": None})
        new_list.append({
            "question_number": i + 1, "question_text": qt, "attempted": 2,
            "data_i18n": None, "options": options, "explanation": expl
        })
    data[key]["quiz_questions"] = new_list
    count += 1
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"✅ Integrated Science U6 (extra): replaced questions for {count} lessons")
