#!/usr/bin/env python3
"""Replace placeholder questions in Linear Algebra U9-U10 with real questions."""
import json, os

PATH = os.path.join("content_data", "linear_algebra_lessons.json")

QUESTIONS = {
# ── U9: Advanced Topics ──
"u9_l9.1": [  # Complex Vector Spaces
    ("A complex vector space uses scalars from:", ["R (reals)", "Z (integers)", "C (complex numbers)", "Q (rationals)"], 2, "Complex vector spaces allow multiplication by complex scalars."),
    ("The complex number i satisfies:", ["i = 1", "i² = 1", "i² = −1", "i² = 0"], 2, "The imaginary unit squares to −1."),
    ("The conjugate of z = a + bi is:", ["a + bi", "a − bi", "−a + bi", "b + ai"], 1, "Flip the sign of the imaginary part."),
    ("In Cⁿ, the inner product <u,v> is defined as:", ["uᵀv", "ūᵀv (conjugate-transpose of u times v)", "u·v", "|u|+|v|"], 1, "<u,v> = Σ ūᵢvᵢ uses complex conjugation."),
    ("A Hermitian matrix satisfies:", ["A = Aᵀ", "A = A† (conjugate transpose)", "A = −A", "A² = I"], 1, "Hermitian: equal to its own conjugate transpose."),
    ("Hermitian matrices always have:", ["complex eigenvalues", "purely imaginary eigenvalues", "real eigenvalues", "no eigenvalues"], 2, "The spectral theorem guarantees real eigenvalues."),
    ("A unitary matrix satisfies:", ["U†U = 0", "U†U = UU† = I", "U² = I", "U = Uᵀ"], 1, "Unitary is the complex analog of orthogonal."),
    ("Eigenvalues of a unitary matrix have absolute value:", ["0", "1", "n", "any real number"], 1, "|λ| = 1 for unitary matrices."),
    ("The dimension of Cⁿ as a complex vector space is:", ["2n", "n", "n²", "1"], 1, "n-dimensional over the complex numbers."),
    ("Cⁿ viewed as a real vector space has dimension:", ["n", "2n", "n²", "n/2"], 1, "Each complex dimension contributes 2 real dimensions."),
    ("A skew-Hermitian matrix satisfies:", ["A = A†", "A = −A†", "A = Aᵀ", "A = −Aᵀ"], 1, "Skew-Hermitian: A = −A†."),
    ("Skew-Hermitian matrices have eigenvalues that are:", ["real", "purely imaginary", "positive real", "zero"], 1, "Eigenvalues are purely imaginary (or zero)."),
    ("The Hermitian inner product is:", ["linear in both arguments", "linear in the second argument, conjugate-linear in the first", "always zero", "undefined for complex vectors"], 1, "Sesquilinear: conjugate-linear in one argument."),
    ("A normal matrix satisfies:", ["A†A = AA†", "A² = A", "A = A⁻¹", "det(A) = 1"], 0, "Normal: commutes with its conjugate transpose."),
    ("Normal matrices can be unitarily diagonalized by the:", ["Cayley-Hamilton theorem", "spectral theorem for normal operators", "rank-nullity theorem", "Gram-Schmidt process"], 1, "Normal ⟺ unitarily diagonalizable."),
    ("The complex exponential e^(iθ) equals:", ["cos θ + i sin θ", "cos θ − i sin θ", "sin θ + i cos θ", "i(cos θ + sin θ)"], 0, "Euler's formula."),
    ("The trace of a Hermitian matrix is:", ["always zero", "always real", "always imaginary", "always complex"], 1, "Trace = sum of real eigenvalues → real."),
    ("The tensor product C² ⊗ C² has dimension:", ["2", "3", "4", "8"], 2, "dim = 2 × 2 = 4."),
    ("Complex eigenvalues of a real matrix come in:", ["identical pairs", "conjugate pairs a ± bi", "unrelated values", "only imaginary pairs"], 1, "Real coefficients → complex roots pair with their conjugates."),
    ("The spectral radius of a matrix is:", ["its largest eigenvalue", "the maximum |λᵢ|", "its trace", "its determinant"], 1, "Max absolute eigenvalue."),
],
"u9_l9.2": [  # Jordan Canonical Form
    ("Jordan form is used when a matrix is:", ["diagonalizable", "not diagonalizable (defective)", "orthogonal", "zero"], 1, "Jordan form generalizes diagonalization for defective matrices."),
    ("A Jordan block Jₖ(λ) is a k×k matrix with:", ["λ on diagonal, 1s on superdiagonal, 0s elsewhere", "λ everywhere", "1s on diagonal, λ on superdiagonal", "all zeros"], 0, "Standard Jordan block structure."),
    ("The 2×2 Jordan block J₂(3) is:", ["[[3,0],[0,3]]", "[[3,1],[0,3]]", "[[3,0],[1,3]]", "[[1,3],[3,1]]"], 1, "λ on diagonal, 1 above."),
    ("The number of Jordan blocks for eigenvalue λ equals the:", ["algebraic multiplicity", "geometric multiplicity", "trace", "determinant"], 1, "One block per independent eigenvector."),
    ("A matrix is diagonalizable iff all Jordan blocks are:", ["2×2", "1×1", "upper triangular", "identical"], 1, "1×1 blocks = no defect."),
    ("The Jordan form is unique up to:", ["scaling", "permutation of the blocks", "adding a constant", "transposition"], 1, "Block ordering is the only ambiguity."),
    ("For a defective eigenvalue λ with algebraic mult 3 and geometric mult 1:", ["three 1×1 blocks", "one 3×3 Jordan block", "one 2×2 and one 1×1 block", "impossible to determine"], 1, "Single eigenvector → single 3×3 block."),
    ("Generalized eigenvectors satisfy (A − λI)ᵏv = 0 for some:", ["k = 0", "k ≥ 1", "k = −1", "k = ∞"], 1, "Chain of generalized eigenvectors."),
    ("The Jordan chain of length k produces:", ["k ordinary eigenvectors", "1 eigenvector and k−1 generalized eigenvectors", "k eigenvalues", "k separate blocks"], 1, "First in the chain is the eigenvector; rest are generalized."),
    ("Jₖ(λ)ⁿ involves terms with:", ["only λⁿ", "λⁿ, nλⁿ⁻¹, C(n,2)λⁿ⁻², etc.", "eλⁿ", "factorials only"], 1, "Binomial-like expansion for Jordan block powers."),
    ("eᴶᵏ⁽λ⁾ᵗ has entries involving:", ["only eλᵗ", "eλᵗ, teλᵗ, t²eλᵗ/2!, …", "cos(λt) only", "polynomial terms only"], 1, "Matrix exponential of a Jordan block."),
    ("The Jordan form of a diagonal matrix is:", ["itself", "a single Jordan block", "the identity", "zero"], 0, "Already in Jordan form (all 1×1 blocks)."),
    ("Computing Jordan form numerically is:", ["trivial", "ill-conditioned and avoided in practice", "faster than eigenvalue computation", "always exact"], 1, "Small perturbations can change Jordan structure; use Schur form instead."),
    ("The Schur decomposition A = QTQ† gives:", ["a diagonal T", "an upper triangular T with eigenvalues on diagonal", "a lower triangular T", "a symmetric T"], 1, "Schur form: unitary similarity to upper triangular."),
    ("Jordan form simplifies solving dx/dt = Ax by giving:", ["a diagonal system", "decoupled blocks that each solve independently", "a single scalar equation", "an unsolvable equation"], 1, "Each block gives a small coupled subsystem."),
    ("The minimum polynomial of a Jordan block Jₖ(λ) is:", ["(x − λ)", "(x − λ)ᵏ", "(x − λ)²", "x − 1"], 1, "Minimal polynomial degree = block size."),
    ("Two matrices with the same Jordan form are:", ["equal", "similar", "orthogonal", "inverses of each other"], 1, "Same Jordan form ⟺ similar."),
    ("The index of an eigenvalue is the size of:", ["the smallest Jordan block", "the largest Jordan block for that eigenvalue", "the total algebraic multiplicity", "the geometric multiplicity"], 1, "Index = largest block size."),
    ("For A = [[5,1],[0,5]], the Jordan form is:", ["diag(5,5)", "[[5,1],[0,5]] (already in Jordan form)", "[[1,5],[5,0]]", "diag(5,1)"], 1, "It's already a 2×2 Jordan block."),
    ("Applications of Jordan form include solving:", ["only algebraic equations", "systems of linear ODEs with defective matrices", "quadratic equations", "nonlinear PDEs"], 1, "Jordan form handles defective systems that diagonalization cannot."),
],
"u9_l9.3": [  # Singular Value Decomposition (SVD)
    ("The SVD of an m×n matrix A is A = UΣVᵀ where:", ["U, Σ, V are all square", "U is m×m orthogonal, Σ is m×n diagonal, V is n×n orthogonal", "U and V are diagonal", "Σ is orthogonal"], 1, "Standard SVD dimensions."),
    ("Singular values are:", ["eigenvalues of A", "square roots of eigenvalues of AᵀA", "entries of A", "eigenvalues of A + Aᵀ"], 1, "σᵢ = √(λᵢ(AᵀA))."),
    ("Singular values are always:", ["negative", "complex", "non-negative real", "integers"], 2, "σᵢ ≥ 0 by construction."),
    ("The rank of A equals the number of:", ["rows", "columns", "nonzero singular values", "zero singular values"], 2, "rank = number of positive σᵢ."),
    ("The columns of U are called:", ["right singular vectors", "left singular vectors", "eigenvalues", "pivot columns"], 1, "U columns are left singular vectors (eigenvectors of AAᵀ)."),
    ("The columns of V are called:", ["left singular vectors", "right singular vectors", "eigenvalues", "null vectors"], 1, "V columns are right singular vectors (eigenvectors of AᵀA)."),
    ("The best rank-k approximation of A in Frobenius norm is:", ["the first k rows of A", "Σᵢ₌₁ᵏ σᵢuᵢvᵢᵀ (truncated SVD)", "the last k singular vectors", "A/k"], 1, "Eckart-Young theorem."),
    ("SVD exists for:", ["only square matrices", "only symmetric matrices", "every matrix (any shape)", "only invertible matrices"], 2, "SVD works for any m×n matrix."),
    ("The condition number from SVD is:", ["σ_max + σ_min", "σ_max / σ_min", "σ_max × σ_min", "σ_max − σ_min"], 1, "cond(A) = σ₁/σₙ."),
    ("The pseudoinverse A⁺ from SVD is:", ["VΣ⁻¹Uᵀ (invert nonzero σᵢ only)", "UΣVᵀ", "AᵀA", "(AᵀA)⁻¹"], 0, "A⁺ = VΣ⁺Uᵀ where Σ⁺ inverts nonzero singular values."),
    ("SVD is used in least squares when AᵀA is:", ["well-conditioned", "ill-conditioned or rank-deficient", "diagonal", "the identity"], 1, "SVD gives a stable pseudoinverse."),
    ("In image compression, keeping top k singular values/vectors approximates the image using:", ["k pixels", "k rank-1 matrices", "k colors", "k rows"], 1, "A ≈ Σᵢ₌₁ᵏ σᵢuᵢvᵢᵀ."),
    ("The Frobenius norm ||A||_F equals:", ["max σᵢ", "√(Σσᵢ²)", "Σσᵢ", "σ₁"], 1, "||A||_F = √(σ₁² + σ₂² + … + σᵣ²)."),
    ("The operator 2-norm ||A||₂ equals:", ["σ_min", "σ₁ (largest singular value)", "Σσᵢ", "det(A)"], 1, "||A||₂ = σ_max."),
    ("Total least squares uses SVD to handle errors in:", ["only the response variable", "both the predictor and response variables", "only the predictor", "neither variable"], 1, "Errors in both X and y."),
    ("Latent semantic analysis (LSA) applies SVD to:", ["images", "a term-document matrix", "audio signals", "neural network weights"], 1, "SVD reveals latent topics in text data."),
    ("The compact (thin) SVD uses:", ["all columns of U and V", "only the first r columns of U and V (r = rank)", "only the last columns", "random columns"], 1, "Thin SVD: U is m×r, Σ is r×r, V is n×r."),
    ("SVD relates to PCA: principal components are proportional to:", ["the left singular vectors", "the right singular vectors of the centered data", "eigenvalues of A", "random directions"], 1, "V columns = PC directions for centered data X."),
    ("The nuclear norm (trace norm) is:", ["max σᵢ", "Σσᵢ", "Σσᵢ²", "min σᵢ"], 1, "Sum of all singular values."),
    ("Randomized SVD algorithms:", ["give exact results slowly", "approximate the top singular values/vectors efficiently for large matrices", "don't use randomness at all", "only work for 2×2 matrices"], 1, "Randomized methods scale to large sparse matrices."),
],
"u9_l9.4": [  # Applications in Machine Learning
    ("Linear regression finds w minimizing:", ["||w||", "||Xw − y||²", "||X||", "det(XᵀX)"], 1, "Ordinary least squares."),
    ("The normal equation for linear regression is:", ["Xw = y", "XᵀXw = Xᵀy", "w = y/X", "Xᵀw = Xy"], 1, "Projection onto column space of X."),
    ("Ridge regression solves (XᵀX + λI)w = Xᵀy to:", ["increase overfitting", "regularize and improve conditioning", "remove all features", "maximize the determinant"], 1, "λI stabilizes the inverse."),
    ("PCA reduces dimensions by projecting onto top eigenvectors of:", ["the data matrix", "the covariance matrix", "the identity", "a random matrix"], 1, "Covariance eigenvectors = principal directions."),
    ("Low-rank matrix approximation via SVD keeps the _____ singular values.", ["smallest", "largest", "zero", "negative"], 1, "Top-k singular values → best rank-k fit."),
    ("Collaborative filtering uses matrix factorization to predict:", ["weather", "missing ratings in user-item matrices", "stock prices from eigenvalues", "text translations"], 1, "R ≈ UVᵀ fills in missing entries."),
    ("In neural networks, the weight matrix W transforms:", ["scalars to scalars", "input vectors to output vectors via linear map", "eigenvalues to eigenvectors", "labels to features"], 1, "Each layer: z = Wx + b."),
    ("Gradient descent updates w by:", ["w ← w + α∇L", "w ← w − α∇L", "w ← w × ∇L", "w ← ∇L / w"], 1, "Subtract the gradient times learning rate."),
    ("The Hessian matrix contains:", ["first derivatives", "second partial derivatives of the loss function", "random values", "data points"], 1, "H_ij = ∂²L/∂wᵢ∂wⱼ."),
    ("Positive definite Hessian at a point indicates:", ["a saddle point", "a local maximum", "a local minimum", "no information"], 2, "All-positive eigenvalues → bowl shape → local min."),
    ("Kernel PCA handles nonlinear structure by:", ["using linear PCA twice", "mapping to high-dimensional feature space via kernel", "deleting features", "averaging data points"], 1, "Kernel trick enables nonlinear PCA."),
    ("Spectral clustering uses eigenvectors of:", ["the covariance matrix", "the graph Laplacian", "the data matrix directly", "random matrices"], 1, "Small Laplacian eigenvalues reveal cluster structure."),
    ("Word2Vec embeddings learn vectors where similar words are:", ["far apart", "close in vector space", "orthogonal", "zero vectors"], 1, "Semantic similarity ≈ vector proximity."),
    ("Attention in transformers computes scores via:", ["eigenvalue decomposition", "inner products between query and key vectors", "random sampling", "convolution"], 1, "score = QKᵀ/√d."),
    ("Batch normalization uses the mean and variance to:", ["increase training time", "normalize activations for stable training", "remove features", "reverse gradients"], 1, "Centering and scaling layer activations."),
    ("The condition number of XᵀX affects:", ["the color of visualizations", "the stability of regression coefficient estimates", "the number of data points", "nothing relevant"], 1, "Ill-conditioned → unstable estimates."),
    ("Truncated SVD for large sparse matrices is efficient because:", ["it ignores the matrix", "it computes only the top k singular triplets", "it converts to dense first", "it uses no iterations"], 1, "Only top-k needed; iterative methods suffice."),
    ("Autoencoders learn compressed representations via:", ["manual feature selection", "encoder (compress) and decoder (reconstruct) networks", "random projections only", "sorting inputs"], 1, "Bottleneck layer forces compression."),
    ("Matrix norms regularize neural networks by:", ["making them larger", "constraining weight magnitudes to reduce overfitting", "removing all weights", "doubling the learning rate"], 1, "Weight decay and spectral normalization."),
    ("The Johnson-Lindenstrauss lemma states random projection preserves:", ["exact distances", "approximate distances in lower dimensions", "the full data matrix", "eigenvalues exactly"], 1, "Distances preserved up to (1±ε) with enough random dimensions."),
],
"u9_l9.5": [  # Applications in Quantum Mechanics
    ("The state of a quantum system is described by a:", ["real number", "vector in a complex Hilbert space", "2D plot", "classical trajectory"], 1, "Quantum states are complex vectors."),
    ("Measurement of a Hermitian observable yields:", ["a complex number", "one of its eigenvalues", "a vector", "the trace"], 1, "Eigenvalues = possible measurement outcomes."),
    ("After measurement yielding eigenvalue λ, the state collapses to:", ["zero", "the corresponding eigenstate", "a random state", "the original state unchanged"], 1, "Wavefunction collapse."),
    ("The hydrogen atom energy levels come from eigenvalues of:", ["the position operator", "the Hamiltonian operator", "the momentum operator", "the identity"], 1, "Hψ = Eψ."),
    ("Spin-1/2 particles have a 2D state space because:", ["they have 2 spatial dimensions", "spin has 2 orthogonal states (up/down)", "there are 2 electrons", "the particle has 2 charges"], 1, "Spin up and spin down form a basis."),
    ("The Pauli Z matrix has eigenvalues:", ["0 and 1", "+1 and −1", "i and −i", "2 and −2"], 1, "σ_z = diag(1,−1)."),
    ("Commuting observables [A,B] = 0 can be:", ["never measured together", "simultaneously diagonalized", "ignored", "only imaginary"], 1, "Commuting Hermitian matrices share an eigenbasis."),
    ("The uncertainty principle arises from:", ["experimental error", "non-commuting operators", "large Hilbert spaces", "classical mechanics"], 1, "ΔA·ΔB ≥ |<[A,B]>|/2."),
    ("A density matrix ρ describes:", ["only pure states", "both pure and mixed quantum states", "classical probabilities only", "individual eigenvalues"], 1, "General quantum states (including statistical mixtures)."),
    ("tr(ρ²) = 1 for a pure state and tr(ρ²) < 1 for a:", ["different pure state", "mixed state", "classical state", "vacuum state"], 1, "Purity measure: tr(ρ²) < 1 indicates mixing."),
    ("The CNOT gate acts on 2 qubits and is represented by a _____ matrix.", ["2×2", "4×4 unitary", "3×3", "8×8"], 1, "2 qubits → 4-dimensional space."),
    ("Entanglement entropy measures:", ["total energy", "the degree of quantum correlations between subsystems", "classical information", "temperature"], 1, "Von Neumann entropy of the reduced density matrix."),
    ("The Born rule: probability of outcome λ is:", ["λ²", "|<λ|ψ>|²", "det(H)", "tr(H)/n"], 1, "Probability = squared amplitude."),
    ("Time-independent Schrödinger equation is:", ["Hψ = Eψ (eigenvalue equation)", "iℏ∂ψ/∂t = Hψ", "ψ = 0", "H = E"], 0, "The stationary equation is an eigenvalue problem."),
    ("Quantum harmonic oscillator eigenvalues are:", ["E_n = nℏω", "E_n = (n + 1/2)ℏω", "E_n = n²ℏω", "E_n = ℏ/n"], 1, "Half-integer quantum of energy."),
    ("Creation and annihilation operators relate to:", ["raising and lowering energy eigenstates", "creating new Hilbert spaces", "matrix inversion", "classical forces"], 0, "Ladder operators move between energy levels."),
    ("Quantum computing uses unitary gates because:", ["they're easy to build", "unitary evolution preserves normalization (probabilities sum to 1)", "they're always diagonal", "they're classical"], 1, "Unitarity → valid probability distribution."),
    ("The tensor product |ψ⟩ ⊗ |φ⟩ describes:", ["a single qubit", "the combined state of two independent systems", "an entangled state always", "a classical bit"], 1, "Composite system of two independent subsystems."),
    ("Decoherence causes loss of quantum interference due to:", ["measurement only", "interaction with the environment", "energy conservation", "the Born rule"], 1, "Environment entangles with the system."),
    ("Variational methods find ground state energy by minimizing:", ["<ψ|ψ>", "<ψ|H|ψ> / <ψ|ψ> over trial states", "det(H)", "tr(H)"], 1, "Rayleigh quotient minimization."),
],
"u9_l9.6": [  # Applications in Image Processing
    ("A grayscale image is stored as a:", ["1D vector", "2D matrix of pixel intensities", "3D tensor always", "a single number"], 1, "Rows × columns matrix, values = brightness."),
    ("Color images use three matrices for:", ["height, width, depth", "red, green, blue channels", "hue, saturation, value always", "x, y, z coordinates"], 1, "RGB: 3 channels stacked."),
    ("SVD image compression keeps top k singular values, reducing storage from m×n to:", ["m+n", "k(m + n + 1)", "m×n still", "k²"], 1, "Store k left vectors + k singular values + k right vectors."),
    ("A convolution filter (kernel) applied to an image performs:", ["random pixel deletion", "local weighted averaging (edge detection, blur, etc.)", "matrix inversion", "eigenvalue computation"], 1, "Slide kernel over image, compute weighted sums."),
    ("Image blurring uses a kernel with:", ["large negative values", "all entries approximately equal (averaging)", "a single 1 in the center", "alternating +1 and −1"], 1, "Averaging nearby pixels → smooth/blur effect."),
    ("Edge detection kernels (like Sobel) highlight regions of:", ["constant intensity", "rapid intensity change (gradients)", "zero intensity", "maximum brightness"], 1, "High gradient magnitude = edge."),
    ("The Fourier transform of an image decomposes it into:", ["eigenvalues", "spatial frequency components", "color channels", "pixel coordinates"], 1, "Low frequencies = smooth regions; high = edges/details."),
    ("Low-pass filtering removes:", ["all frequencies", "high-frequency components (noise, edges)", "low-frequency components (background)", "the DC component"], 1, "Keep low frequencies → smoothing."),
    ("The discrete cosine transform (DCT) is used in:", ["PNG format", "JPEG compression", "SVG format", "BMP format"], 1, "JPEG uses blockwise DCT."),
    ("In face recognition, eigenfaces are:", ["original face images", "top eigenvectors of the face covariance matrix", "random face templates", "face outlines"], 1, "PCA on face images → eigenfaces."),
    ("Image denoising via SVD works by:", ["amplifying noise", "removing low-rank signal", "truncating small singular values (keeping signal, discarding noise)", "adding random values"], 2, "Noise contributes to small singular values."),
    ("The rank of a typical photograph is:", ["1", "equal to min(m,n) (full rank)", "much less than min(m,n) (low effective rank)", "always zero"], 2, "Natural images are approximately low-rank."),
    ("Geometric transformations (rotation, scaling) on images use:", ["color changes", "matrix multiplication on coordinate vectors", "sorting pixels", "random permutations"], 1, "Transform coordinates → interpolate pixel values."),
    ("Image morphing interpolates between two images using:", ["simple averaging", "linear algebra operations on corresponding features", "pixel deletion", "color inversion"], 1, "Blend geometry + appearance via linear interpolation."),
    ("The total variation of an image measures:", ["average brightness", "the sum of gradient magnitudes (favoring piecewise-smooth images)", "the number of pixels", "the file size"], 1, "TV regularization preserves edges while smoothing."),
    ("Non-negative matrix factorization (NMF) for images requires:", ["all factors to be negative", "all factor entries to be non-negative", "complex entries", "orthogonal factors"], 1, "Non-negativity gives parts-based (additive) representation."),
    ("Super-resolution uses prior low-rank structure to:", ["reduce image quality", "reconstruct higher-resolution images from low-resolution input", "convert to grayscale", "remove all detail"], 1, "Linear algebra models fill in missing high-frequency detail."),
    ("The bilateral filter preserves edges by weighting based on:", ["only spatial distance", "both spatial distance and intensity similarity", "eigenvalues", "random weights"], 1, "Avoids averaging across edges."),
    ("Optical flow estimation uses system of linear equations relating:", ["colors to labels", "pixel brightness changes to motion vectors", "file sizes to quality", "eigenvalues to frequencies"], 1, "Brightness constancy constraint → linear system."),
    ("Inpainting (filling missing regions) can be posed as:", ["a deterministic lookup", "a low-rank matrix completion problem", "simple copy-paste", "eigenvalue computation"], 1, "Exploit low-rank image structure to fill gaps."),
],
"u9_l9.7": [  # Applications in Signal Processing
    ("A discrete signal is mathematically a:", ["matrix", "sequence (vector) of samples", "single real number", "differential equation"], 1, "Signal = ordered list of amplitude values."),
    ("The DFT transforms a time-domain signal to:", ["another time signal", "frequency-domain representation", "the spatial domain", "a matrix"], 1, "Discrete Fourier Transform → spectral coefficients."),
    ("The DFT matrix F has entries F_{jk} = ωⁿ^(jk) where ωₙ is:", ["1/n", "e^(−2πi/n) (primitive nth root of unity)", "n", "e^n"], 1, "The nth root of unity drives the DFT."),
    ("The FFT computes the DFT in:", ["O(n²)", "O(n log n)", "O(n)", "O(2ⁿ)"], 1, "Fast Fourier Transform: divides and conquers."),
    ("Convolution in the time domain corresponds to _____ in frequency domain.", ["convolution", "pointwise multiplication", "division", "differentiation"], 1, "The convolution theorem."),
    ("A low-pass filter in frequency domain sets high-frequency components to:", ["infinity", "zero (removing noise and sharp features)", "double their value", "negative values"], 1, "Zero out high frequencies → smooth signal."),
    ("The sampling theorem states a signal can be perfectly reconstructed if sampled at:", ["any rate", "at least twice the maximum frequency (Nyquist rate)", "exactly the maximum frequency", "below the maximum frequency"], 1, "Nyquist-Shannon sampling theorem."),
    ("Aliasing occurs when:", ["sampling rate is too high", "sampling rate is below the Nyquist rate", "the signal is zero", "the DFT is applied twice"], 1, "Under-sampling folds high frequencies into lower ones."),
    ("The z-transform is the discrete analog of:", ["the Fourier series", "the Laplace transform", "the wavelet transform", "matrix multiplication"], 1, "z-transform for discrete signals parallels Laplace for continuous."),
    ("Linear time-invariant (LTI) systems are characterized by their:", ["color", "impulse response (or transfer function)", "sampling rate only", "number of inputs"], 1, "Output = input convolved with impulse response."),
    ("The eigenvalues of a circulant matrix are given by:", ["its diagonal entries", "its DFT (Fourier coefficients of the first row)", "random values", "its trace repeated"], 1, "Circulant matrices are diagonalized by the DFT matrix."),
    ("Compressed sensing recovers sparse signals from:", ["many more measurements than needed", "far fewer measurements than traditional sampling requires", "exactly one measurement", "no measurements"], 1, "Exploit sparsity to sample below Nyquist."),
    ("The RIP (Restricted Isometry Property) ensures:", ["signals are always dense", "sparse signal distances are approximately preserved by the measurement matrix", "the DFT is exact", "all eigenvalues equal 1"], 1, "RIP → stable compressed sensing recovery."),
    ("Windowing functions reduce spectral leakage by:", ["increasing signal length infinitely", "tapering signal ends smoothly to zero", "adding noise", "removing the DC component"], 1, "Smooth taper → reduced sidelobes."),
    ("The short-time Fourier transform (STFT) provides:", ["only time information", "only frequency information", "time-frequency localization", "spatial information"], 2, "Windowed DFT shows how spectrum evolves in time."),
    ("Wavelets improve on STFT by providing:", ["fixed resolution", "multi-resolution analysis (adapting window size by scale)", "only time-domain info", "no useful information"], 1, "Short windows for high freq, long for low freq."),
    ("The Wiener filter minimizes:", ["signal power", "mean squared error between estimated and true signal", "computational cost", "the number of frequencies"], 1, "Optimal linear filter in the MSE sense."),
    ("A Toeplitz matrix has:", ["random structure", "constant entries along each diagonal", "all zeros except the main diagonal", "only 1s"], 1, "Convolution → Toeplitz structure."),
    ("Eigendecomposition of the autocorrelation matrix gives:", ["the signal itself", "signal power spectrum directions (Karhunen-Loève transform)", "random noise", "time stamps"], 1, "KLT = optimal decorrelation."),
    ("5G and OFDM use:", ["single-carrier transmission", "DFT/IDFT to multiplex data across orthogonal subcarriers", "analog modulation only", "no linear algebra"], 1, "Orthogonal frequency-division multiplexing."),
],
"u9_l9.8": [  # Applications in Statistics
    ("In regression, the design matrix X has:", ["eigenvalues as entries", "predictor values with rows = observations, columns = features", "response values only", "residuals only"], 1, "Each row is an observation vector."),
    ("The OLS estimator β̂ = (XᵀX)⁻¹Xᵀy minimizes:", ["||β||", "||y − Xβ||²", "||X||", "det(XᵀX)"], 1, "Ordinary least squares."),
    ("Multicollinearity is detected when eigenvalues of XᵀX are:", ["all large and equal", "near zero (indicating near-dependence)", "all negative", "complex"], 1, "Small eigenvalues → nearly dependent predictors."),
    ("PCA in statistics rotates data to:", ["correlated axes", "uncorrelated axes aligned with maximum variance", "random directions", "the original axes"], 1, "PCA diagonalizes the covariance matrix."),
    ("The covariance matrix Σ is always:", ["skew-symmetric", "positive semi-definite and symmetric", "negative definite", "diagonal"], 1, "Variances ≥ 0, covariances symmetric."),
    ("Mahalanobis distance uses the inverse covariance to measure:", ["Euclidean distance", "distance accounting for variable correlations and scales", "angle between vectors", "rank of data"], 1, "d²(x,μ) = (x−μ)ᵀΣ⁻¹(x−μ)."),
    ("Linear discriminant analysis (LDA) maximizes:", ["within-class scatter", "the ratio of between-class to within-class scatter", "total variance", "the number of classes"], 1, "Maximize class separation relative to spread."),
    ("The hat matrix H = X(XᵀX)⁻¹Xᵀ projects y onto:", ["null(X)", "Col(X)", "Row(X)", "residual space"], 1, "ŷ = Hy."),
    ("Leverage values (diagonal of H) measure:", ["prediction accuracy", "how influential each observation is on its own fitted value", "the determinant of X", "the sample mean"], 1, "High leverage = point far from center of predictor space."),
    ("Cook's distance combines leverage and residual to assess:", ["model fit overall", "the influence of each observation on all fitted values", "variable importance", "the p-value"], 1, "Large Cook's D → influential point."),
    ("The variance inflation factor (VIF) for variable j is:", ["1/(1 − Rⱼ²) where Rⱼ² is from regressing xⱼ on other predictors", "det(XᵀX)", "the jth eigenvalue of X", "1/n"], 0, "VIF > 10 often signals problematic multicollinearity."),
    ("Factor analysis models observed variables as linear combinations of:", ["eigenvalues", "latent (unobserved) factors plus noise", "other observed variables", "the response variable"], 1, "x = Λf + ε."),
    ("Canonical correlation analysis finds:", ["the largest eigenvalue", "directions maximizing correlation between two sets of variables", "the sample mean", "individual variable variances"], 1, "CCA = generalized eigenvalue problem."),
    ("The spectral decomposition of the correlation matrix reveals:", ["variable names", "underlying variance structure and potential factor groupings", "the sample size", "categorical relationships"], 1, "Eigenanalysis of correlations → latent structure."),
    ("Regularized regression (Ridge, LASSO) addresses:", ["too few observations", "multicollinearity and overfitting", "missing response values", "non-numerical data"], 1, "Penalty terms stabilize estimation."),
    ("The expected value of the hat matrix trace tr(H) equals:", ["n", "p (number of parameters)", "0", "1"], 1, "tr(H) = p = dim(Col(X))."),
    ("Partial least squares (PLS) finds directions maximizing:", ["variance in X only", "covariance between X and y", "residual magnitude", "the determinant of XᵀX"], 1, "PLS balances X-variance and y-correlation."),
    ("The F-test in regression compares models using:", ["t-statistics", "ratios of explained to unexplained variance", "correlation coefficients", "individual regression coefficients"], 1, "F = (SSR/p) / (SSE/(n−p−1))."),
    ("In Bayesian regression, the posterior covariance involves:", ["only the prior", "Σ_post = (Σ_prior⁻¹ + XᵀX/σ²)⁻¹", "the sample mean only", "the likelihood alone"], 1, "Combines prior precision and data precision."),
    ("The singular values of the centered data matrix relate to:", ["individual data points", "principal component standard deviations", "the class labels", "p-values"], 1, "σᵢ/√(n−1) = standard deviation along PCi."),
],

# ── U10: Applications & Review ──
"u10_l10.1": [  # Proofs in Linear Algebra
    ("A direct proof of 'if P then Q' proceeds by:", ["assuming Q and deriving P", "assuming P and logically deriving Q", "providing a counterexample", "assuming not-Q"], 1, "Assume hypothesis, deduce conclusion."),
    ("Proof by contradiction assumes:", ["the statement is true, then finds a contradiction", "the statement is false, then derives a contradiction", "nothing at all", "only the converse"], 1, "Assume ¬Q, reach a logical impossibility."),
    ("To prove two subspaces are equal (U = W), show:", ["U ⊆ W only", "W ⊆ U only", "U ⊆ W and W ⊆ U", "they have the same dimension"], 2, "Mutual inclusion."),
    ("Proving dimension equality dim(U) = dim(W) shows:", ["U ≠ W", "U and W are isomorphic (same 'size')", "U = W necessarily", "they are orthogonal"], 1, "Same dimension → isomorphic as vector spaces."),
    ("The rank-nullity theorem: rank(A) + nullity(A) =:", ["m (rows)", "n (columns)", "rank(A)²", "det(A)"], 1, "dim(Col(A)) + dim(Null(A)) = n."),
    ("To prove T: V→W is injective, show that:", ["T maps onto W", "T(v)=0 implies v=0", "dim(V) = dim(W)", "T is continuous"], 1, "Trivial kernel ⟺ injective."),
    ("To prove T is surjective, show that:", ["ker(T)={0}", "every w∈W has some v∈V with T(v)=w", "T is injective", "dim(V) > dim(W)"], 1, "Range = codomain."),
    ("Proving a set S is a subspace requires checking:", ["S is nonempty, closed under addition, closed under scalar multiplication", "S contains at most n vectors", "S has a basis", "S intersects every other subspace"], 0, "Three subspace axioms."),
    ("The determinant of the product det(AB) equals:", ["det(A) + det(B)", "det(A) · det(B)", "det(A) / det(B)", "det(A + B)"], 1, "Multiplicative property."),
    ("A key step in proving the spectral theorem is showing:", ["all matrices are diagonal", "eigenvectors of a symmetric matrix for distinct eigenvalues are orthogonal", "only the identity is symmetric", "eigenvalues don't exist"], 1, "Orthogonality of distinct eigen-spaces."),
    ("Mathematical induction on n proves a statement by:", ["checking all cases up to n=100", "proving base case and: if true for n then true for n+1", "proving the contrapositive", "assuming it's always true"], 1, "Base case + inductive step."),
    ("The Cayley-Hamilton theorem is proven by showing A satisfies:", ["its inverse", "its own characteristic polynomial", "any polynomial", "the zero polynomial only"], 1, "p(A) = 0 where p is the characteristic polynomial."),
    ("Proof that similar matrices have the same eigenvalues uses:", ["det(P⁻¹AP − λI) = det(P⁻¹(A−λI)P) = det(A−λI)", "trace computation", "row reduction", "dimension counting"], 0, "Similarity preserves the characteristic polynomial."),
    ("Proving the Cauchy-Schwarz inequality typically uses:", ["matrix inversion", "the non-negativity of ||u − tv||² for all t", "the triangle inequality", "eigenvalue bounds"], 1, "Expand ||u − tv||² ≥ 0, optimize over t."),
    ("An isomorphism between V and W requires T to be:", ["injective only", "surjective only", "bijective (both injective and surjective)", "neither"], 2, "Bijective linear map."),
    ("Proving uniqueness of reduced row echelon form uses:", ["the determinant", "the pivots determine the RREF uniquely", "random tests", "numerical computation"], 1, "Leading entries (pivots) uniquely determine the reduced form."),
    ("The proof that det(Aᵀ) = det(A) relies on:", ["cofactor expansion giving the same result for rows and columns", "the Cayley-Hamilton theorem", "eigenvalue properties", "the rank-nullity theorem"], 0, "Cofactor expansion along rows or columns gives identical results."),
    ("To disprove a universal claim, it suffices to find:", ["a general proof", "one counterexample", "multiple examples confirming it", "a proof by induction"], 1, "One counterexample disproves a 'for all' statement."),
    ("Constructive proofs not only show existence but also:", ["deny it", "provide an explicit example or algorithm", "use contradiction", "rely on axiom of choice"], 1, "Constructive: here is the object."),
    ("Proof techniques in linear algebra often combine:", ["only arithmetic", "algebraic manipulation, dimension arguments, and matrix properties", "only geometry", "only probability"], 1, "Multi-tool approach."),
],
"u10_l10.2": [  # AP-Style Practice Problems
    ("If A is a 3×3 matrix with det(A) = 4, then det(2A) =:", ["8", "32", "16", "64"], 1, "det(cA) = cⁿdet(A) = 2³·4 = 32."),
    ("The null space of a 5×3 matrix of rank 2 has dimension:", ["3", "1", "2", "5"], 1, "nullity = n − rank = 3 − 2 = 1."),
    ("If A has eigenvalues 1, 2, 3 then det(A) =:", ["6", "5", "3", "9"], 0, "det = product of eigenvalues = 1·2·3 = 6."),
    ("For orthogonal Q, ||Qv|| equals:", ["||Q|| · ||v||", "||v||", "0", "||v||²"], 1, "Orthogonal matrices preserve norms."),
    ("The rank of [[1,2],[2,4]] is:", ["2", "0", "1", "4"], 2, "Rows are proportional → rank 1."),
    ("If A is invertible and Ax = b has solution x₀, how many solutions exist?", ["zero", "exactly one (x₀)", "infinitely many", "exactly two"], 1, "Invertible → unique solution."),
    ("The dimension of the column space of a 4×6 matrix of rank 3 is:", ["6", "4", "3", "1"], 2, "dim(Col(A)) = rank = 3."),
    ("Eigenvalues of A² if A has eigenvalues λ are:", ["2λ", "λ²", "λ + 2", "√λ"], 1, "If Ax = λx then A²x = λ²x."),
    ("The trace of A + B equals:", ["trace(A) · trace(B)", "trace(A) + trace(B)", "trace(AB)", "det(A) + det(B)"], 1, "Trace is additive."),
    ("Which matrix is not invertible?", ["I₃", "diag(1,2,3)", "[[1,0],[0,0]]", "[[2,1],[1,1]]"], 2, "det([[1,0],[0,0]]) = 0."),
    ("If V has dimension 4 and W is a subspace of dimension 2, dim(V/W) =:", ["4", "6", "2", "8"], 2, "dim(V/W) = dim(V) − dim(W) = 2."),
    ("The projection of [3,4] onto [1,0] is:", ["[3,0]", "[0,4]", "[3,4]", "[1,0]"], 0, "proj = (3·1+4·0)/(1)·[1,0] = [3,0]."),
    ("If A is 3×3 with eigenvalues 1,1,2 then trace(A) =:", ["3", "4", "2", "6"], 1, "trace = 1+1+2 = 4."),
    ("A change of basis matrix P transforms coordinates by:", ["x_new = Px_old", "x_new = P⁻¹x_old", "x_new = x_old + P", "x_new = Px_old²"], 1, "New coordinates = P⁻¹ times old coordinates."),
    ("Cramer's rule gives xᵢ = det(Aᵢ)/det(A) and requires:", ["rank < n", "det(A) ≠ 0", "A is symmetric", "A has all positive entries"], 1, "A must be invertible (det ≠ 0)."),
    ("The row space and null space of A are _____ subspaces of Rⁿ.", ["identical", "orthogonal complements", "parallel", "equal"], 1, "Row(A) ⊥ Null(A) and dim sums to n."),
    ("A linear transformation T: R³→R² can have kernel dimension at most:", ["0", "1", "2", "3"], 2, "nullity ≤ 3; since rank ≤ 2, nullity ≥ 1; max nullity = 3 if rank=0, but with R²: nullity can be up to 3."),
    ("The Gram matrix Gᵢⱼ = <vᵢ,vⱼ> is positive semi-definite because:", ["it has real entries", "xᵀGx = ||Σxᵢvᵢ||² ≥ 0", "its trace ≥ 0", "eigenvalues are integers"], 1, "Quadratic form equals a squared norm."),
    ("Stacking three 2×2 matrices vertically gives a matrix of size:", ["6×2", "2×6", "6×6", "2×2"], 0, "3 rows of 2×2 blocks → 6 rows, 2 columns."),
    ("Computing A⁻¹ by augmenting [A|I] and row-reducing to [I|A⁻¹] uses:", ["Cramer's rule", "the Gauss-Jordan method", "QR factorization", "eigenvalue decomposition"], 1, "Augmented matrix method."),
],
"u10_l10.3": [  # Applications in Computer Science (networks, algorithms)
    ("Graphs are represented in linear algebra using:", ["strings", "adjacency or Laplacian matrices", "hash tables", "linked lists"], 1, "Matrix representations enable algebraic graph theory."),
    ("Aⁿ_{ij} for adjacency matrix A counts the number of:", ["edges between i and j", "walks of length n from vertex i to vertex j", "shortest paths of length n", "disconnected components"], 1, "Matrix powers count walks."),
    ("PageRank models the web as a:", ["binary tree", "Markov chain with stochastic transition matrix", "linked list", "heap"], 1, "Random surfer model."),
    ("Shortest path algorithms like Floyd-Warshall use:", ["eigenvalue structures", "matrix operations on distance matrices (min-plus algebra)", "random matrices", "inner products"], 1, "Tropical semiring: min replaces addition, plus replaces multiplication."),
    ("The graph Laplacian L = D − A has the property that:", ["all eigenvalues are negative", "the smallest eigenvalue is 0 (with eigenvector 1)", "L is always invertible", "L = I always"], 1, "L1 = 0; 0 is always an eigenvalue."),
    ("The number of connected components equals the multiplicity of eigenvalue _____ of L.", ["1", "0", "the largest eigenvalue", "−1"], 1, "Multiplicity of 0 = number of components."),
    ("In network flow, the incidence matrix maps:", ["edges to nodes", "nodes to colors", "paths to cycles", "flows to adjacency"], 0, "B_{ie} = ±1 shows how edge e connects to node i."),
    ("Error-correcting codes use generator matrices from:", ["random matrices", "carefully designed linear algebra over finite fields", "Euclidean spaces", "complex Hilbert spaces"], 1, "GF(2) or GF(q): linear codes."),
    ("The Hamming code corrects:", ["all errors", "single-bit errors using parity check matrices", "no errors", "only two-bit errors"], 1, "Syndrome decoding via Hx."),
    ("Cryptographic lattice problems rely on:", ["simple matrix inversion", "the hardness of finding short vectors in high-dimensional lattices", "determinant computation", "eigenvalue computation"], 1, "Basis reduction: hard lattice problems → secure crypto."),
    ("Iterative solvers (CG, GMRES) for Ax = b avoid:", ["using A", "forming A⁻¹ explicitly (only use matrix-vector products)", "producing an answer", "any computation"], 1, "Only need Av; never need A⁻¹."),
    ("Sparse matrix storage formats (CSR, CSC) exploit:", ["density", "the large number of zero entries", "matrix symmetry only", "eigenvalue structure"], 1, "Store only nonzero entries + indices."),
    ("In computer graphics, transformations are composed by:", ["adding matrices", "multiplying transformation matrices", "inverting all matrices", "transposing all matrices"], 1, "T_total = T_n · … · T_2 · T_1."),
    ("Homogeneous coordinates allow translations to be expressed as:", ["additions", "matrix multiplications (in one dimension higher)", "scalar products", "subtractions"], 1, "4×4 matrices for 3D affine transforms."),
    ("The Fast Fourier Transform algorithm achieves O(n log n) by:", ["brute force", "recursively splitting even and odd indexed terms", "ignoring half the data", "using random sampling"], 1, "Divide and conquer on the DFT."),
    ("Finite element methods discretize PDEs into:", ["differential equations", "linear systems assembled from element stiffness matrices", "single equations", "polynomial equations"], 1, "Kd = f: global stiffness, displacement, force."),
    ("The condition number determines:", ["the algorithm's correctness", "how much numerical error is amplified in solving Ax=b", "the number of iterations always", "the storage size"], 1, "cond(A) = ||A||·||A⁻¹||."),
    ("Parallel computation of matrix operations distributes:", ["single entries", "blocks of the matrix across processors", "nothing", "only eigenvalues"], 1, "Block decomposition for parallelism."),
    ("GPU acceleration of linear algebra exploits:", ["sequential processing", "massive parallelism for matrix operations", "quantum effects", "file I/O"], 1, "GPUs have thousands of cores for parallel computation."),
    ("Blockchain can use linear algebra for:", ["mining only", "zero-knowledge proofs and polynomial commitments", "storing matrices", "computing eigenvalues"], 1, "Polynomial and matrix-based proof systems."),
],
"u10_l10.4": [  # Applications in Engineering (structural analysis)
    ("In structural analysis, the stiffness matrix K relates:", ["forces to displacements (Kd = f)", "voltages to currents", "temperatures to heat", "pressures to volumes"], 0, "Fundamental structural equation."),
    ("The stiffness matrix of a structure is typically:", ["dense and small", "sparse, symmetric, and positive definite", "diagonal", "random"], 1, "Physical connections → sparse; energy → SPD."),
    ("Finite element analysis discretizes a structure into:", ["continuous curves", "small elements with local stiffness matrices", "individual atoms", "random segments"], 1, "Mesh elements assembled into a global system."),
    ("Natural frequencies of a structure come from solving:", ["Kd = 0", "the eigenvalue problem Kφ = ω²Mφ", "det(K) = 0", "K = M"], 1, "Generalized eigenvalue problem."),
    ("Mode shapes (vibration patterns) are the:", ["eigenvalues of K", "eigenvectors of the K-M system", "diagonal entries of M", "forces on the structure"], 1, "Each eigenvector = a vibration mode shape."),
    ("Buckling load analysis solves:", ["Kd = f", "(K − λKg)v = 0 (geometric stiffness problem)", "λ = trace(K)", "det(M) = 0"], 1, "Buckling = eigenvalue of geometric stiffness."),
    ("A truss element's local stiffness matrix is:", ["4×4 for 2D", "2×2 always", "1×1 always", "6×6 for 2D"], 0, "2 nodes × 2 DOF = 4×4 in 2D."),
    ("Assembly of global stiffness uses:", ["matrix multiplication", "summation of element matrices mapped to global DOFs", "eigenvalue computation", "random placement"], 1, "Direct stiffness method."),
    ("Boundary conditions in FEM are enforced by:", ["ignoring them", "modifying rows/columns of K (eliminating known DOFs)", "adding rows to K", "doubling the matrix"], 1, "Fix known displacements."),
    ("The mass matrix M is typically:", ["negative definite", "positive definite (masses > 0)", "skew-symmetric", "singular"], 1, "Physical masses are positive."),
    ("In circuit analysis, Kirchhoff's laws lead to:", ["differential equations only", "systems of linear equations (node voltage method)", "nonlinear systems always", "matrix multiplication only"], 1, "Linear circuits → Ax = b."),
    ("The impedance matrix Z relates voltage and current phasors via:", ["V = ZI", "V = Z + I", "Z = VI", "I = Z/V"], 0, "V = ZI (Ohm's law in matrix form)."),
    ("Transfer matrices in control describe:", ["static systems only", "input-output relationships of dynamic systems", "file transfers", "data bandwidth"], 1, "G(s) = C(sI − A)⁻¹B + D."),
    ("Poles of a control system are eigenvalues of:", ["the output matrix", "the system matrix A", "the input matrix B", "the feedthrough matrix D"], 1, "Poles determine system dynamics."),
    ("A stable control system has all poles with:", ["positive real parts", "negative real parts", "zero real parts", "magnitude > 1"], 1, "Re(λᵢ) < 0 → stable continuous system."),
    ("The controllability matrix [B, AB, A²B, …] must have:", ["rank 0", "full rank for the system to be controllable", "rank 1", "all zero columns"], 1, "Controllability = full rank condition."),
    ("Modal analysis decomposes vibration into:", ["random components", "independent modes (eigenvectors), each with its own frequency", "DC components only", "nonlinear terms"], 1, "Decoupled modal coordinates."),
    ("Optimization in structural design often minimizes:", ["the number of equations", "weight subject to stress/displacement constraints", "the stiffness matrix size", "the eigenvalue count"], 1, "Design for minimum weight satisfying performance."),
    ("Sensitivity analysis shows how output changes when:", ["nothing varies", "design parameters are perturbed", "the structure is rebuilt", "eigenvalues are set to zero"], 1, "∂output/∂parameter."),
    ("Digital twins use real-time linear algebra to:", ["replace physical systems", "simulate and predict structural behavior from sensor data", "store photos", "generate random matrices"], 1, "Continuous model updating from measurements."),
],
"u10_l10.5": [  # Applications in Physics (quantum states)
    ("A quantum state |ψ⟩ is normalized when:", ["<ψ|ψ> = 0", "<ψ|ψ> = 1", "||ψ|| = 2", "<ψ|ψ> = i"], 1, "Unit norm."),
    ("The superposition principle says valid states include:", ["only eigenstates", "any linear combination α|ψ₁⟩ + β|ψ₂⟩", "products of states only", "classical states only"], 1, "Linearity of quantum mechanics."),
    ("The tensor product space for n qubits has dimension:", ["n", "2n", "2ⁿ", "n²"], 2, "Each qubit contributes factor of 2."),
    ("A separable state of two qubits can be written as:", ["|ψ₁⟩ ⊗ |ψ₂⟩", "any vector in C⁴", "|00⟩ + |11⟩ only", "a 2×2 matrix"], 0, "Product state = separable."),
    ("The GHZ state (|000⟩+|111⟩)/√2 involves:", ["2 qubits", "3 entangled qubits", "1 qubit", "4 classical bits"], 1, "Three-qubit entangled state."),
    ("Quantum gates must be unitary to:", ["increase probability", "preserve total probability (normalization)", "create entanglement always", "reduce dimension"], 1, "U†U = I → probabilities sum to 1."),
    ("The Hadamard gate H maps |0⟩ to:", ["(|0⟩+|1⟩)/√2", "|1⟩", "(|0⟩−|1⟩)/√2", "|0⟩"], 0, "Creates equal superposition."),
    ("Quantum entanglement means:", ["states are separable", "measuring one subsystem instantly affects the other's statistics", "the state has zero energy", "the system is classical"], 1, "Non-local correlations."),
    ("The Bloch sphere represents:", ["multi-qubit states", "a single qubit's pure state geometrically", "classical bits", "the energy landscape"], 1, "Points on sphere ↔ qubit states."),
    ("Quantum error correction protects against:", ["all errors perfectly", "decoherence and gate errors using redundant encoding", "classical noise only", "no errors at all"], 1, "Encode logical qubit in multiple physical qubits."),
    ("The no-cloning theorem states:", ["any state can be copied", "an unknown quantum state cannot be perfectly duplicated", "entanglement can be cloned", "measurement copies the state"], 1, "Fundamental limitation of quantum information."),
    ("Grover's algorithm provides:", ["exponential speedup for all problems", "quadratic speedup for unstructured search", "no speedup", "speedup for factoring only"], 1, "O(√N) vs O(N) classically."),
    ("Shor's algorithm factors integers using:", ["classical division", "quantum Fourier transform and period finding", "Grover's search", "simulated annealing"], 1, "QFT-based: exponential speedup over classical."),
    ("The quantum Fourier transform is a unitary acting on:", ["classical bits", "n-qubit states in 2ⁿ-dimensional Hilbert space", "single qubits only", "real numbers"], 1, "QFT on n qubits."),
    ("Measurement in the computational basis {|0⟩,|1⟩} is a:", ["unitary operation", "projection onto basis states", "rotation", "translation"], 1, "Projective measurement."),
    ("The Schmidt decomposition writes a bipartite state as:", ["a single product state", "Σᵢ λᵢ|aᵢ⟩|bᵢ⟩ (sum of weighted products)", "a density matrix", "a classical probability"], 1, "Optimal bipartite decomposition."),
    ("Quantum teleportation requires:", ["faster-than-light communication", "shared entanglement and 2 classical bits", "3 entangled qubits only", "no classical communication"], 1, "Entanglement + classical bits → state transfer."),
    ("Variational quantum eigensolver (VQE) minimizes:", ["circuit depth", "⟨ψ(θ)|H|ψ(θ)⟩ over parameterized states", "the number of qubits", "classical memory"], 1, "Hybrid algorithm for ground state energy."),
    ("Topological quantum computing encodes information in:", ["individual qubit states", "non-abelian anyons whose braiding is robust to local noise", "classical registers", "photon polarization only"], 1, "Topological protection against decoherence."),
    ("Quantum advantage is achieved when:", ["a quantum computer exists", "a quantum algorithm outperforms all known classical algorithms for the task", "the qubit count exceeds 100", "entanglement is absent"], 1, "Provable or practical quantum speedup."),
],
"u10_l10.6": [  # Applications in Economics (input-output models)
    ("Leontief's input-output model uses a matrix A where aᵢⱼ represents:", ["profit of sector j", "the fraction of sector j's output used by sector i", "consumer demand", "labor cost"], 1, "Technical coefficient."),
    ("The total output x satisfies x = Ax + d, solved as:", ["x = Ad", "x = (I − A)⁻¹d", "x = d − A", "x = A⁻¹d"], 1, "Leontief inverse."),
    ("The Leontief inverse (I − A)⁻¹ exists when:", ["A is symmetric", "the spectral radius of A is less than 1", "A is orthogonal", "det(A) = 1"], 1, "ρ(A) < 1 ensures convergence."),
    ("(I − A)⁻¹ = I + A + A² + A³ + … converges when:", ["always", "spectral radius ρ(A) < 1", "A is diagonal", "A² = 0"], 1, "Neumann series convergence."),
    ("Each entry of (I − A)⁻¹ represents:", ["direct input only", "total (direct + indirect) requirement per unit of final demand", "only the final demand", "the wage rate"], 1, "Captures all rounds of inter-industry production."),
    ("A productive economy requires that for any demand d ≥ 0:", ["x can be negative", "x = (I − A)⁻¹d ≥ 0", "A = I", "(I − A) is singular"], 1, "Non-negative output for non-negative demand."),
    ("The Hawkins-Simon conditions ensure:", ["negative output", "all diagonal minors of (I − A) are positive", "det(A) < 0", "zero production"], 1, "Necessary and sufficient for a productive economy."),
    ("Multiplier effects in an economy are captured by:", ["only the diagonal of A", "the column sums of (I − A)⁻¹", "the eigenvalues of d", "the trace of d"], 1, "How much total output changes per unit of final demand."),
    ("Structural change analysis examines:", ["daily stock prices", "how A changes over time and its effect on output", "individual firm profits", "exchange rates only"], 1, "Tracking technical coefficients across years."),
    ("Dynamic Leontief models add:", ["color coding", "capital accumulation and time-indexed equations", "a second demand vector only", "no additional structure"], 1, "x(t+1) depends on x(t) and investment."),
    ("Social accounting matrices (SAMs) extend I-O models to include:", ["only manufacturing", "government, households, and transfer payments", "only exports", "only imports"], 1, "Broader economic accounting."),
    ("In Markov economic models, the steady state satisfies:", ["πA = π with Σπᵢ = 1", "πA = 0", "π = Aπ + I", "π = A²"], 0, "Left eigenvector for eigenvalue 1."),
    ("The dominant eigenvalue of A indicates:", ["nothing useful", "the overall intensity of inter-industry dependence", "the discount rate", "the unemployment rate"], 1, "Close to 1 = tight coupling."),
    ("Multi-regional I-O models capture:", ["intra-regional trade only", "inter-regional trade and spillover effects", "only national aggregates", "foreign exchange rates"], 1, "Trade between regions."),
    ("Environmental I-O models add:", ["pollution emission coefficients per unit of output", "extra demand vectors", "only labor data", "only capital data"], 0, "Expand A to track environmental impacts."),
    ("Supply-side I-O models fix:", ["demand and compute output", "output and compute demand", "prices and compute quantities", "output and compute value-added and allocation"], 3, "Ghosh model: allocation coefficients."),
    ("Price models in I-O analysis use p = pA + v, solved as:", ["p = v", "p = v(I − A)⁻¹", "p = Av", "p = v − A"], 1, "Price = value added carried through production chains."),
    ("Sensitivity of x to changes in A is studied via:", ["x = d (no dependence)", "the derivative ∂x/∂aᵢⱼ from the Leontief inverse", "ignoring A", "random perturbation"], 1, "Structural path analysis."),
    ("CGE (Computable General Equilibrium) models extend I-O by adding:", ["nothing new", "behavioral equations, substitution, and market-clearing conditions", "only a larger A matrix", "eigenvalue constraints"], 1, "Full economic equilibrium."),
    ("Blockchain-tracked supply chains can update I-O coefficients:", ["never", "in real-time (more accurate A matrix)", "only annually", "only for one sector"], 1, "Real-time data improves model accuracy."),
],
"u10_l10.7": [  # Capstone Project: Real-World Linear Algebra Model
    ("A capstone project typically involves:", ["a single textbook exercise", "identifying a real problem, modeling it with linear algebra, and presenting results", "memorizing formulas", "only theoretical proofs"], 1, "End-to-end applied project."),
    ("The first step in modeling is:", ["writing code", "clearly defining the problem and identifying relevant variables", "finding eigenvalues", "choosing a programming language"], 1, "Problem formulation comes first."),
    ("Choosing between SVD, eigendecomposition, or least squares depends on:", ["personal preference only", "the structure of the problem and data", "which is fastest to compute", "the programming language"], 1, "Match the tool to the problem."),
    ("Data collection for a capstone should consider:", ["only sample size", "relevance, quality, completeness, and ethical sourcing", "only the format", "only public data"], 1, "Data quality matters for meaningful results."),
    ("After building a model, validation involves:", ["hoping it works", "comparing predictions against held-out or real-world data", "never checking", "using only training data"], 1, "Test against data the model hasn't seen."),
    ("Sensitivity analysis in a capstone project shows:", ["the model is always correct", "how robust results are to changes in assumptions or data", "the code compiles", "nothing useful"], 1, "Check if small changes flip the conclusions."),
    ("Visualizing results effectively might use:", ["text-only tables always", "plots, heatmaps, or dimension-reduced scatter plots", "no visuals", "only equations"], 1, "Visual communication aids understanding."),
    ("An economic input-output capstone might model:", ["nothing specific", "inter-industry flows and predict output changes from demand shocks", "only eigenvalues", "random data"], 1, "Real-world I-O application."),
    ("An image processing capstone could apply SVD to:", ["text analysis", "compress or denoise real photographs", "solve ODEs", "build neural networks"], 1, "SVD-based image compression."),
    ("A network analysis capstone uses adjacency matrices to study:", ["random numbers", "connectivity, centrality, and community structure in real networks", "only the number of nodes", "file sizes"], 1, "Graph theory applications."),
    ("Writing a clear report includes:", ["only the final answer", "problem statement, methods, results, and discussion", "code only", "only an abstract"], 1, "Standard technical report format."),
    ("Limitations should be:", ["hidden from the reader", "honestly acknowledged and discussed", "never mentioned", "exaggerated to seem humble"], 1, "Honest assessment of model shortcomings."),
    ("Reproducibility means:", ["others can follow your exact steps and get the same results", "results change each time", "only the author can run the code", "no documentation needed"], 0, "Code + data + method → reproduce."),
    ("Comparing your model to simpler baselines shows:", ["your model is always better", "whether the added complexity is justified", "nothing useful", "only that baselines fail"], 1, "Baselines establish a reference point."),
    ("For a population dynamics capstone, the Leslie matrix models:", ["trade flows", "age-structured population growth over time", "web traffic", "chemical reactions"], 1, "Age classes × fertility × survival."),
    ("Ethical considerations in modeling include:", ["ignoring bias", "examining data bias, model fairness, and societal impact", "using the largest dataset possible", "maximizing accuracy at any cost"], 1, "Responsible modeling."),
    ("A quantum computing capstone might simulate:", ["classical circuits", "quantum gates and entanglement using unitary matrices", "only classical random walks", "database queries"], 1, "Matrix representation of quantum operations."),
    ("Documentation of code should be:", ["nonexistent", "sufficient for another person to understand and modify it", "as brief as possible", "only in comments with no external docs"], 1, "Readable, well-documented code."),
    ("A good capstone presentation balances:", ["only technical detail", "technical depth and accessible explanation for a broad audience", "only visuals", "only code snippets"], 1, "Tailor to the audience."),
    ("Reflecting on what you learned from the project is:", ["a waste of time", "valuable for solidifying understanding and identifying growth areas", "only for grading", "optional always"], 1, "Metacognitive reflection deepens learning."),
],
"u10_l10.8": [  # Comprehensive Review & AP Exam Practice
    ("The four fundamental subspaces of A are Col(A), Null(A), Row(A), and:", ["Col(Aᵀ)", "Null(Aᵀ) (left null space)", "the eigenspace", "the singular space"], 1, "Left null space = Null(Aᵀ)."),
    ("Row(A) and Null(A) are orthogonal complements in:", ["Rᵐ", "Rⁿ", "the column space", "the eigenspace"], 1, "Both are subspaces of Rⁿ."),
    ("A is invertible iff:", ["rank(A) < n", "det(A) ≠ 0", "det(A) = 0", "nullity(A) > 0"], 1, "Full rank ⟺ det ≠ 0 ⟺ invertible."),
    ("The Gram-Schmidt process is key to:", ["LU factorization", "QR factorization", "eigenvalue computation", "Cholesky factorization"], 1, "Orthogonalize columns → QR."),
    ("Diagonalization A = PDP⁻¹ requires A to have:", ["all zero eigenvalues", "n linearly independent eigenvectors", "only positive eigenvalues", "a symmetric structure"], 1, "Full set of independent eigenvectors."),
    ("SVD exists for _____ rectangular matrices.", ["no", "only square", "all", "only invertible"], 2, "Any m×n matrix has an SVD."),
    ("The pseudoinverse A⁺ gives the minimum-norm least-squares solution to:", ["Ax = 0", "Ax = b (even when A is not invertible)", "A = B", "det(A) = 0"], 1, "A⁺b is the best we can do."),
    ("For a positive definite matrix, all eigenvalues are:", ["negative", "zero", "positive", "complex"], 2, "Definition of positive definite."),
    ("The condition number κ(A) measures:", ["the size of A", "sensitivity of Ax=b to perturbations in A or b", "the rank of A", "the trace of A"], 1, "Large κ → ill-conditioned."),
    ("In least squares, the residual b − Ax̂ is in:", ["Col(A)", "Null(A)", "Null(Aᵀ) (the left null space)", "Row(A)"], 2, "Residual ⊥ Col(A), so it's in the left null space."),
    ("The matrix exponential eᴬ converges for:", ["only small A", "only symmetric A", "all square matrices A", "only diagonal A"], 2, "The series converges for any square matrix."),
    ("The Cayley-Hamilton theorem guarantees A satisfies its own:", ["inverse", "transpose", "characteristic polynomial", "singular values"], 2, "p(A) = 0."),
    ("Jordan form generalizes diagonalization by using:", ["lower triangular blocks", "Jordan blocks with 1s above the diagonal", "diagonal blocks only", "random blocks"], 1, "λ on diagonal, 1s on superdiagonal within each block."),
    ("The nuclear norm Σσᵢ is used in optimization to promote:", ["high rank", "low rank", "orthogonality only", "large singular values"], 1, "Convex relaxation of the rank function."),
    ("In quantum computing, a qubit is a unit vector in:", ["R²", "C² (2D complex vector space)", "R³", "C³"], 1, "α|0⟩ + β|1⟩ with |α|² + |β|² = 1."),
    ("The fundamental theorem of linear algebra connects:", ["matrices to scalars", "the four subspaces, rank, and orthogonal complements", "eigenvalues to singular values", "only determinants and traces"], 1, "Unifying framework."),
    ("Numerical stability means an algorithm:", ["is always fast", "gives accurate results despite floating-point arithmetic", "uses exact arithmetic", "avoids matrices"], 1, "Controlled error amplification."),
    ("The best low-rank approximation in Frobenius norm comes from:", ["random projection", "truncated SVD", "Gram-Schmidt", "LU factorization"], 1, "Eckart-Young theorem."),
    ("Linear algebra connects to calculus through:", ["no relationship", "the Jacobian matrix of partial derivatives", "only integration", "polynomial roots"], 1, "Jacobian: matrix of partial derivatives of vector function."),
    ("The ongoing importance of linear algebra comes from its:", ["historical value only", "role as the foundation for most computational and scientific methods", "simplicity only", "limited applications"], 1, "Foundational to modern science, engineering, and computing."),
],
}

# ── Write ──
with open(PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

count = 0
for key, qs in QUESTIONS.items():
    if key not in data:
        print(f"⚠ {key} not found"); continue
    new_list = []
    for i, (qt, opts, correct_idx, expl) in enumerate(qs):
        options = []
        for j, o in enumerate(opts):
            options.append({"text": o, "is_correct": j == correct_idx, "data_i18n": None})
        new_list.append({
            "question_number": i + 1,
            "question_text": qt,
            "attempted": 2,
            "data_i18n": None,
            "options": options,
            "explanation": expl
        })
    data[key]["quiz_questions"] = new_list
    count += 1

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"✅ Linear Algebra U9-U10: replaced questions for {count} lessons")
