import json, os

BASE = r"c:\Users\Peter\pkang6689-pixel.github.io\content_data\AstronomyLessons\Unit2"

def q(num, text, options, explanation):
    opts = []
    for o in options:
        if isinstance(o, tuple):
            opts.append({"text": o[0], "is_correct": o[1], "data_i18n": None})
        else:
            opts.append({"text": o, "is_correct": False, "data_i18n": None})
    return {
        "question_number": num,
        "question_text": text,
        "attempted": 2,
        "data_i18n": None,
        "options": opts,
        "explanation": explanation
    }

def write_quiz(filename, unit, lesson_num, title, questions):
    data = {
        "unit": unit,
        "lesson_number": lesson_num,
        "title": title,
        "course": "Astronomy",
        "quiz_questions": questions
    }
    path = os.path.join(BASE, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Wrote {path} with {len(questions)} questions")

# ============================================================
# Lesson 2.1: Earth's Rotation & Revolution
# ============================================================
L21 = [
    # Easy (1-10)
    q(1, "Earth completes one full rotation on its axis in approximately how many hours?",
      [("24 hours", True), ("12 hours", False), ("36 hours", False), ("48 hours", False)],
      "Earth rotates once on its axis approximately every 24 hours, giving us the cycle of day and night."),
    q(2, "Earth's revolution around the Sun takes approximately:",
      [("365.25 days", True), ("30 days", False), ("180 days", False), ("730 days", False)],
      "Earth takes about 365.25 days to complete one orbit around the Sun, which is why we have leap years."),
    q(3, "What is the approximate tilt of Earth's axis?",
      [("23.5°", True), ("45°", False), ("10°", False), ("90°", False)],
      "Earth's axis is tilted about 23.5° relative to its orbital plane, which causes the seasons."),
    q(4, "A sidereal day is approximately how long?",
      [("23 hours 56 minutes", True), ("24 hours exactly", False), ("25 hours", False), ("22 hours", False)],
      "A sidereal day (one full rotation relative to distant stars) is about 23 hours and 56 minutes."),
    q(5, "Which effect causes moving objects on Earth's surface to deflect from a straight path?",
      [("Coriolis effect", True), ("Doppler effect", False), ("Greenhouse effect", False), ("Tidal effect", False)],
      "The Coriolis effect, caused by Earth's rotation, deflects moving objects to the right in the Northern Hemisphere and to the left in the Southern Hemisphere."),
    q(6, "Perihelion is when Earth is:",
      [("Closest to the Sun", True), ("Farthest from the Sun", False), ("At the equinox", False), ("At the solstice", False)],
      "Perihelion occurs around January 3, when Earth is closest to the Sun in its elliptical orbit."),
    q(7, "What is the shape of Earth's orbit around the Sun?",
      [("Slightly elliptical", True), ("Perfectly circular", False), ("Highly elliptical", False), ("Parabolic", False)],
      "Earth's orbit is nearly circular with an eccentricity of about 0.017, making it only slightly elliptical."),
    q(8, "The plane of Earth's orbit around the Sun is called the:",
      [("Ecliptic plane", True), ("Celestial equator", False), ("Galactic plane", False), ("Meridian plane", False)],
      "The ecliptic plane is the plane of Earth's orbit around the Sun."),
    q(9, "What demonstrated that Earth rotates on its axis?",
      [("Foucault's pendulum", True), ("Hubble telescope", False), ("Kepler's laws", False), ("Newton's prism", False)],
      "Léon Foucault's pendulum experiment in 1851 provided visible proof that Earth rotates."),
    q(10, "Why do we have leap years?",
      [("Earth's orbital period is about 365.25 days", True), ("The Moon's orbit changes", False), ("Earth speeds up every 4 years", False), ("The Sun's gravity fluctuates", False)],
      "Since Earth's orbital period is approximately 365.25 days, we add an extra day every 4 years to keep the calendar aligned."),
    # Vocabulary (11-20)
    q(11, "What is 'rotation' in the context of Earth's motion?",
      [("The spinning of Earth on its axis", True), ("Earth's orbit around the Sun", False), ("The wobble of Earth's axis", False), ("The movement of tectonic plates", False)],
      "Rotation refers to Earth spinning on its own axis, which takes about 24 hours and produces day and night."),
    q(12, "What is 'revolution' in astronomy?",
      [("The orbital motion of one body around another", True), ("The spinning of a planet on its axis", False), ("An explosion on the Sun", False), ("The change of seasons", False)],
      "Revolution is the movement of one celestial body in an orbit around another, such as Earth orbiting the Sun."),
    q(13, "What is a 'sidereal day'?",
      [("The time for one full rotation relative to distant stars", True), ("The time between two consecutive noons", False), ("The time for one orbit around the Sun", False), ("Half of a solar day", False)],
      "A sidereal day is measured by Earth's rotation relative to distant stars, about 23 hours 56 minutes."),
    q(14, "What is the 'ecliptic'?",
      [("The apparent path of the Sun across the sky over a year", True), ("The shadow cast during an eclipse", False), ("The orbit of the Moon", False), ("A type of telescope", False)],
      "The ecliptic is the apparent path the Sun traces across the sky throughout the year, corresponding to Earth's orbital plane."),
    q(15, "What is 'precession'?",
      [("The slow wobble of Earth's rotational axis", True), ("The speeding up of Earth's rotation", False), ("The tilting of the Moon's orbit", False), ("The expansion of the universe", False)],
      "Precession is the slow, conical wobble of Earth's axis over a ~26,000-year cycle, changing which star is the 'North Star.'"),
    q(16, "What does 'perihelion' mean?",
      [("The point in Earth's orbit nearest to the Sun", True), ("The point farthest from the Sun", False), ("The time of an eclipse", False), ("The center of the Sun", False)],
      "Perihelion comes from Greek 'peri' (near) + 'helios' (sun), marking Earth's closest approach to the Sun."),
    q(17, "What does 'aphelion' mean?",
      [("The point in Earth's orbit farthest from the Sun", True), ("The point closest to the Sun", False), ("The highest point in the atmosphere", False), ("The equinox date", False)],
      "Aphelion is when Earth is at its greatest distance from the Sun, occurring around July 4."),
    q(18, "What is the 'Coriolis effect'?",
      [("The deflection of moving objects due to Earth's rotation", True), ("The bending of light near a black hole", False), ("The wobble of Earth's axis", False), ("The pull of the Moon on tides", False)],
      "The Coriolis effect is an apparent deflection of moving objects caused by Earth's rotation, influencing weather patterns and ocean currents."),
    q(19, "What is the 'celestial equator'?",
      [("The projection of Earth's equator onto the celestial sphere", True), ("The orbit of the Moon", False), ("The Sun's equator", False), ("A line connecting the poles of the galaxy", False)],
      "The celestial equator is the imaginary great circle on the celestial sphere directly above Earth's equator."),
    q(20, "What is an 'analemma'?",
      [("A figure-8 pattern showing the Sun's position at the same time each day over a year", True), ("A type of sundial", False), ("A lunar phase diagram", False), ("An eclipse prediction model", False)],
      "An analemma is the figure-8 shape traced by the Sun's position in the sky when observed at the same time and place throughout the year."),
    # Scenario (21-30)
    q(21, "A student notices that shadows are shorter at noon in June than in December (in the Northern Hemisphere). What best explains this?",
      [("Earth's axial tilt causes the Sun to appear higher in summer", True), ("Earth is closer to the Sun in June", False), ("The atmosphere is thinner in summer", False), ("The Moon blocks some sunlight in winter", False)],
      "Earth's 23.5° axial tilt causes the Sun to reach a higher angle in the sky during summer, producing shorter shadows."),
    q(22, "An astronaut watches Earth from space and sees the terminator (day-night boundary). Over 24 hours, how does the terminator appear to move?",
      [("It sweeps westward across Earth's surface", True), ("It stays stationary", False), ("It moves eastward", False), ("It moves from pole to pole", False)],
      "As Earth rotates eastward, the day-night line (terminator) appears to sweep westward across the surface."),
    q(23, "A pilot flies directly north from the equator. Due to Earth's rotation, the plane drifts to the east of its intended path. What effect explains this?",
      [("Coriolis effect", True), ("Centripetal force", False), ("Tidal force", False), ("Precession", False)],
      "The Coriolis effect deflects moving objects to the right in the Northern Hemisphere (and left in the Southern), causing the drift."),
    q(24, "If Earth's axial tilt were 0°, what would happen to seasons?",
      [("There would be no seasons — temperature would depend only on latitude", True), ("Seasons would be more extreme", False), ("Only the equator would have seasons", False), ("Years would be shorter", False)],
      "Without axial tilt, sunlight distribution would not change throughout the year, eliminating seasons."),
    q(25, "A calendar shows February 29. What astronomical fact makes this extra day necessary?",
      [("Earth's orbital period is approximately 365.25 days, not exactly 365", True), ("The Moon's orbit slows down every 4 years", False), ("The Sun's luminosity changes cyclically", False), ("Mars comes close to Earth every 4 years", False)],
      "The extra ~0.25 day per year accumulates, and adding a leap day every 4 years keeps the calendar synchronized with Earth's orbit."),
    q(26, "A student sets up a Foucault pendulum at the North Pole. How would it appear to behave?",
      [("The pendulum's plane of swing would rotate 360° in 24 hours", True), ("The pendulum would not appear to rotate at all", False), ("The pendulum would rotate 180° in 24 hours", False), ("The pendulum would stop swinging quickly", False)],
      "At the North Pole, a Foucault pendulum's swing plane appears to rotate a full 360° in ~24 hours due to Earth's rotation beneath it."),
    q(27, "Astronomers measure that a star returns to the same position in the sky 4 minutes earlier each night. Why?",
      [("The difference between solar and sidereal day — Earth moves along its orbit", True), ("The star is moving toward Earth", False), ("Earth's rotation is speeding up", False), ("Light travels faster at night", False)],
      "Because Earth advances ~1° along its orbit each day, stars rise ~4 minutes earlier each night (the sidereal vs. solar day difference)."),
    q(28, "If Earth's orbit were perfectly circular instead of slightly elliptical, what would change?",
      [("There would be no perihelion or aphelion — Earth-Sun distance would be constant", True), ("Seasons would disappear", False), ("Days would be longer", False), ("The Moon would drift away", False)],
      "With a circular orbit, Earth's distance from the Sun would never vary, eliminating perihelion and aphelion."),
    q(29, "A photographer takes a picture of the Sun at the same time every day for a year and notices a figure-8 pattern. What is this called?",
      [("An analemma", True), ("A parallax", False), ("A retrograde loop", False), ("A corona", False)],
      "The figure-8 pattern formed by the Sun's position at the same time each day over a year is called an analemma."),
    q(30, "Scientists predict that in about 13,000 years, the North Celestial Pole will point near the star Vega instead of Polaris. What causes this shift?",
      [("Precession of Earth's axis", True), ("Earth's orbit changing shape", False), ("The Sun moving through the galaxy", False), ("Vega moving toward Earth", False)],
      "Precession causes Earth's axis to trace a circle in the sky over ~26,000 years, so in ~13,000 years the axis will point near Vega."),
]
write_quiz("Lesson2.1_Quiz.json", 2, "2.1", "Earth's Rotation & Revolution", L21)

# ============================================================
# Lesson 2.2: Seasons & Tilt of Axis
# ============================================================
L22 = [
    q(1, "What primarily causes the seasons on Earth?",
      [("The tilt of Earth's axis", True), ("Earth's distance from the Sun", False), ("The Moon's gravitational pull", False), ("Variations in solar energy output", False)],
      "Seasons are caused by Earth's 23.5° axial tilt, which changes the angle and duration of sunlight different hemispheres receive."),
    q(2, "During the June solstice, which hemisphere receives the most direct sunlight?",
      [("Northern Hemisphere", True), ("Southern Hemisphere", False), ("Both equally", False), ("Neither", False)],
      "During the June solstice, the Northern Hemisphere is tilted toward the Sun and receives the most direct sunlight."),
    q(3, "How many solstices occur each year?",
      [("Two", True), ("One", False), ("Four", False), ("Six", False)],
      "There are two solstices each year — the June solstice (around June 21) and the December solstice (around December 21)."),
    q(4, "What happens at an equinox?",
      [("Day and night are approximately equal in length", True), ("The Sun is at its highest point", False), ("Earth is closest to the Sun", False), ("Tides are at their strongest", False)],
      "At an equinox, the Sun is directly over the equator, making day and night approximately equal in length everywhere."),
    q(5, "In the Southern Hemisphere, summer occurs during which months?",
      [("December through February", True), ("June through August", False), ("March through May", False), ("September through November", False)],
      "The Southern Hemisphere's summer is from December to February, when it is tilted toward the Sun."),
    q(6, "At which latitude does the Sun not set during the June solstice?",
      [("Arctic Circle (66.5°N)", True), ("Tropic of Cancer (23.5°N)", False), ("Equator (0°)", False), ("Tropic of Capricorn (23.5°S)", False)],
      "Above the Arctic Circle, the Sun remains above the horizon for 24 hours during the June solstice (midnight sun)."),
    q(7, "The Tropic of Cancer is located at approximately:",
      [("23.5°N", True), ("23.5°S", False), ("66.5°N", False), ("0°", False)],
      "The Tropic of Cancer is at approximately 23.5°N, where the Sun is directly overhead on the June solstice."),
    q(8, "Which of the following has the LEAST effect on seasons?",
      [("Earth's distance from the Sun", True), ("Axial tilt", False), ("Angle of incoming sunlight", False), ("Length of daylight hours", False)],
      "Earth's distance from the Sun varies only about 3% and has minimal effect on seasons — axial tilt is the dominant factor."),
    q(9, "During the December solstice, where is the Sun directly overhead at noon?",
      [("Tropic of Capricorn (23.5°S)", True), ("Tropic of Cancer (23.5°N)", False), ("Equator", False), ("South Pole", False)],
      "On the December solstice, the Sun is directly overhead at the Tropic of Capricorn (23.5°S)."),
    q(10, "What is the term for the longest day of the year in a given hemisphere?",
      [("Summer solstice", True), ("Vernal equinox", False), ("Perihelion", False), ("Aphelion", False)],
      "The summer solstice marks the longest day and shortest night of the year for that hemisphere."),
    # Vocabulary (11-20)
    q(11, "What is a 'solstice'?",
      [("The time when the Sun reaches its highest or lowest point in the sky at noon, marking the longest or shortest day", True), ("When day and night are equal", False), ("When Earth is closest to the Sun", False), ("A lunar event", False)],
      "A solstice occurs when Earth's axial tilt is most inclined toward or away from the Sun, producing the longest or shortest day."),
    q(12, "What is an 'equinox'?",
      [("The time when the Sun crosses the celestial equator, making day and night approximately equal", True), ("The longest day of the year", False), ("When the Moon is full", False), ("Earth's closest approach to the Sun", False)],
      "An equinox occurs when the Sun is directly above the equator, and day and night are roughly equal worldwide."),
    q(13, "What does 'axial tilt' mean?",
      [("The angle between a planet's rotational axis and the perpendicular to its orbital plane", True), ("The speed of rotation", False), ("The shape of the orbit", False), ("The distance from the Sun", False)],
      "Axial tilt (obliquity) is the angle between a planet's spin axis and a line perpendicular to its orbital plane — for Earth, about 23.5°."),
    q(14, "What is the 'Tropic of Cancer'?",
      [("The latitude (23.5°N) where the Sun is directly overhead on the June solstice", True), ("The northernmost point where stars are visible", False), ("A constellation", False), ("The equator of the Sun", False)],
      "The Tropic of Cancer at 23.5°N marks the northernmost latitude where the Sun can be directly overhead."),
    q(15, "What is the 'Tropic of Capricorn'?",
      [("The latitude (23.5°S) where the Sun is directly overhead on the December solstice", True), ("The southernmost continent", False), ("A zodiac constellation path", False), ("The Antarctic Circle", False)],
      "The Tropic of Capricorn at 23.5°S marks the southernmost latitude where the Sun can be directly overhead."),
    q(16, "What is the 'Arctic Circle'?",
      [("The latitude (~66.5°N) above which the Sun does not set on the June solstice", True), ("The boundary of the North Pole ice cap", False), ("A circle drawn by the aurora", False), ("The orbit of polar satellites", False)],
      "The Arctic Circle (~66.5°N) marks the latitude above which 24-hour daylight (midnight sun) occurs at the June solstice."),
    q(17, "What does 'insolation' mean?",
      [("The amount of solar radiation received by a surface", True), ("The insulation layer of the atmosphere", False), ("A measure of temperature", False), ("Protection from solar wind", False)],
      "Insolation (incoming solar radiation) measures how much solar energy reaches a given area, varying with season and latitude."),
    q(18, "What is 'obliquity'?",
      [("Another term for a planet's axial tilt", True), ("The shape of an orbit", False), ("A type of eclipse", False), ("The brightness of a star", False)],
      "Obliquity is the technical term for the tilt of a planet's rotational axis relative to its orbital plane."),
    q(19, "What is 'photoperiod'?",
      [("The duration of daylight in a 24-hour period", True), ("The speed of light", False), ("The brightness of the Sun", False), ("A unit of astronomical distance", False)],
      "Photoperiod is the length of daylight during a day, which changes with seasons and affects plant and animal behavior."),
    q(20, "What is the 'midnight sun'?",
      [("A phenomenon where the Sun remains visible at midnight, occurring near the poles", True), ("A solar eclipse at midnight", False), ("A red-colored Moon", False), ("A reflection of the Sun on the ocean", False)],
      "The midnight sun occurs at high latitudes when the Sun does not set for extended periods around the summer solstice."),
    # Scenario (21-30)
    q(21, "A city at 45°N has about 15 hours of daylight on June 21 and only 9 hours on December 21. What explains this difference?",
      [("Earth's axial tilt changes how long each hemisphere faces the Sun throughout the year", True), ("The Sun moves closer in June", False), ("The atmosphere is thicker in December", False), ("The Moon blocks sunlight in winter", False)],
      "The 23.5° axial tilt means the Northern Hemisphere is angled toward the Sun in June (longer days) and away in December (shorter days)."),
    q(22, "A student in Australia celebrates Christmas during their summer. Why is December summer in Australia?",
      [("The Southern Hemisphere is tilted toward the Sun in December", True), ("Australia is closer to the Sun in December", False), ("Ocean currents warm Australia in December", False), ("The ozone hole lets in more heat", False)],
      "When the Northern Hemisphere has winter (December), the Southern Hemisphere is tilted toward the Sun, experiencing summer."),
    q(23, "If Earth's axial tilt increased to 45°, how would seasons change?",
      [("Seasons would become much more extreme with hotter summers and colder winters", True), ("Seasons would disappear entirely", False), ("Only the tropics would have seasons", False), ("Earth's orbit would become circular", False)],
      "A larger tilt means more extreme differences in sunlight distribution, leading to more intense summers and winters."),
    q(24, "At the equator, there is approximately 12 hours of daylight year-round. Why?",
      [("The equator remains roughly the same distance from the Sun's direct rays regardless of tilt", True), ("The equator has no atmosphere", False), ("Earth's rotation is faster at the equator", False), ("The Sun is always overhead at the equator", False)],
      "The equator is always near the boundary between the sunlit and dark halves of Earth, so day length stays close to 12 hours."),
    q(25, "A farmer plants crops based on the vernal equinox. Why is this date important for agriculture?",
      [("It marks the beginning of longer days and warming temperatures in spring", True), ("It is when Earth is closest to the Sun", False), ("It is the only day it can rain", False), ("Seeds only germinate on equinoxes", False)],
      "The vernal (spring) equinox signals increasing daylight and warmer conditions, making it a traditional marker for planting."),
    q(26, "A researcher at the North Pole experiences 24 hours of darkness on December 21. What is this phenomenon called?",
      [("Polar night", True), ("Solar eclipse", False), ("New moon", False), ("Umbral shadow", False)],
      "Polar night occurs when the Sun stays below the horizon for 24 hours, happening at polar latitudes during their winter solstice."),
    q(27, "Two cities are at the same latitude but different longitudes. Would they have different season timing?",
      [("No — seasons depend on latitude and axial tilt, not longitude", True), ("Yes — eastern cities get summer first", False), ("Yes — western cities are always warmer", False), ("Yes — longitude determines tilt angle", False)],
      "Seasons are determined by axial tilt and latitude. Cities at the same latitude experience the same seasonal pattern regardless of longitude."),
    q(28, "A student argues that Earth is closer to the Sun in summer, causing warmer weather. What is wrong with this reasoning?",
      [("Earth is actually closest to the Sun (perihelion) in January, during Northern Hemisphere winter", True), ("Nothing — this is correct", False), ("The Sun changes size during summer", False), ("Gravity doesn't affect temperature", False)],
      "Earth's perihelion occurs in January. Seasons are caused by axial tilt, not distance from the Sun."),
    q(29, "If you traveled from the equator to the Arctic Circle in June, how would daylight hours change?",
      [("Daylight hours would increase dramatically, reaching nearly 24 hours at the Arctic Circle", True), ("Daylight hours would decrease", False), ("Daylight hours would stay the same", False), ("There would be total darkness at the Arctic", False)],
      "In June, the Northern Hemisphere is tilted toward the Sun; daylight increases with latitude up to 24 hours at the Arctic Circle."),
    q(30, "A science class compares temperatures at two locations: one at 23.5°N and one at 66.5°N during the June solstice. Both receive many hours of sunlight, but the tropical location is often warmer. Why?",
      [("At 23.5°N the Sun is directly overhead, concentrating energy; at 66.5°N sunlight hits at a low angle, spreading energy over a larger area", True), ("The tropical location is closer to the Sun", False), ("The Arctic has more clouds", False), ("The Arctic has no atmosphere", False)],
      "Even though both locations get long days, the angle of sunlight matters — direct overhead sunlight delivers more energy per unit area than low-angle sunlight."),
]
write_quiz("Lesson2.2_Quiz.json", 2, "2.2", "Seasons & Tilt of Axis", L22)

# ============================================================
# Lesson 2.3: Lunar Phases
# ============================================================
L23 = [
    q(1, "How long does it take for the Moon to complete one cycle of phases?",
      [("About 29.5 days", True), ("About 14 days", False), ("About 7 days", False), ("About 365 days", False)],
      "The synodic period (full cycle of lunar phases) is approximately 29.5 days."),
    q(2, "During a new moon, the Moon is located:",
      [("Between Earth and the Sun", True), ("On the opposite side of Earth from the Sun", False), ("At a right angle to the Earth-Sun line", False), ("Behind Jupiter", False)],
      "At new moon, the Moon is roughly between Earth and the Sun, so its illuminated side faces away from us."),
    q(3, "What is a waxing crescent?",
      [("A thin sliver of illumination growing after new moon", True), ("A fully lit Moon", False), ("A Moon more than half illuminated and growing", False), ("A thin sliver before new moon", False)],
      "Waxing crescent is the phase just after new moon when a small, growing sliver of the Moon is visible."),
    q(4, "During a full moon, how much of the Moon's surface facing Earth is illuminated?",
      [("100%", True), ("50%", False), ("75%", False), ("25%", False)],
      "At full moon, the entire face of the Moon visible from Earth is illuminated by the Sun."),
    q(5, "The first quarter moon appears how illuminated?",
      [("Half illuminated (right half in Northern Hemisphere)", True), ("Fully illuminated", False), ("One-quarter illuminated", False), ("Three-quarters illuminated", False)],
      "Despite its name, the first quarter moon shows half of the Moon's visible face illuminated — it's one-quarter through the cycle."),
    q(6, "What does 'waning' mean in lunar phases?",
      [("The illuminated portion is decreasing", True), ("The illuminated portion is increasing", False), ("The Moon is closer to Earth", False), ("The Moon is in shadow", False)],
      "Waning means the lit portion of the Moon is shrinking as it moves from full moon toward new moon."),
    q(7, "The Moon shines because it:",
      [("Reflects sunlight", True), ("Produces its own light", False), ("Reflects Earth's light", False), ("Emits thermal radiation", False)],
      "The Moon has no light of its own; it shines by reflecting sunlight."),
    q(8, "Which phase comes directly after the full moon?",
      [("Waning gibbous", True), ("Waxing gibbous", False), ("Third quarter", False), ("Waning crescent", False)],
      "After the full moon, the illuminated portion begins to decrease, entering the waning gibbous phase."),
    q(9, "A gibbous moon is:",
      [("More than half but not fully illuminated", True), ("Less than half illuminated", False), ("Exactly half illuminated", False), ("Completely dark", False)],
      "Gibbous means the Moon is more than half illuminated but not yet (or no longer) full."),
    q(10, "The sidereal month (Moon's orbit relative to stars) is about:",
      [("27.3 days", True), ("29.5 days", False), ("24 days", False), ("31 days", False)],
      "The sidereal month is about 27.3 days, shorter than the synodic month because Earth moves along its orbit."),
    # Vocabulary (11-20)
    q(11, "What is a 'synodic month'?",
      [("The time between two identical lunar phases (about 29.5 days)", True), ("The time for the Moon to orbit once relative to the stars", False), ("A calendar month", False), ("The time between two eclipses", False)],
      "A synodic month measures the interval between the same phases (e.g., new moon to new moon), about 29.5 days."),
    q(12, "What does 'waxing' mean?",
      [("Growing — the illuminated portion of the Moon is increasing", True), ("Shrinking — the illuminated portion is decreasing", False), ("The Moon is rising", False), ("The Moon is moving away from Earth", False)],
      "Waxing means the Moon's visible illuminated area is growing, from new moon through first quarter to full."),
    q(13, "What is a 'gibbous' phase?",
      [("A phase where more than half but less than all of the Moon is illuminated", True), ("When the Moon is less than half lit", False), ("A crescent shape", False), ("The new moon phase", False)],
      "Gibbous (from Latin for 'hump') describes the Moon when more than half its face is illuminated."),
    q(14, "What is 'earthshine'?",
      [("Sunlight reflected off Earth that faintly illuminates the dark side of the Moon", True), ("Light from the Moon reflected off Earth", False), ("The glow of lava on the Moon", False), ("Bioluminescence in the ocean", False)],
      "Earthshine is the faint glow on the Moon's unlit side, caused by sunlight bouncing off Earth and then reflecting back."),
    q(15, "What is a 'lunar cycle'?",
      [("The complete sequence of phases from new moon to new moon", True), ("One rotation of the Moon on its axis", False), ("The Moon's journey through one zodiac sign", False), ("A 19-year eclipse pattern", False)],
      "The lunar cycle (or lunation) is the full sequence of phases, taking about 29.5 days."),
    q(16, "What does 'crescent' mean?",
      [("A phase where less than half of the Moon's face is illuminated", True), ("A phase where more than half is illuminated", False), ("A full moon", False), ("A half moon", False)],
      "A crescent phase shows a thin, curved sliver of illumination — less than half the Moon's visible face."),
    q(17, "What is 'libration'?",
      [("A slight wobble in the Moon's orientation allowing us to see slightly more than 50% of its surface over time", True), ("The Moon moving faster at perigee", False), ("The Moon's rotation period", False), ("An eclipse shadow", False)],
      "Libration is the apparent rocking of the Moon that lets us see about 59% of its surface over time."),
    q(18, "What is a 'sidereal month'?",
      [("The time for the Moon to complete one orbit relative to the stars (~27.3 days)", True), ("The time between full moons", False), ("A month in the stellar calendar", False), ("30 days exactly", False)],
      "A sidereal month measures the Moon's orbit against the background stars, about 27.3 days."),
    q(19, "What is the 'terminator' on the Moon?",
      [("The boundary line between the illuminated and dark portions of the Moon", True), ("A crater on the far side", False), ("The point where the Moon blocks the Sun", False), ("The edge of the Moon's atmosphere", False)],
      "The lunar terminator is the dividing line between the sunlit and shadowed parts of the Moon's surface."),
    q(20, "What is 'tidal locking'?",
      [("When a body's rotation period equals its orbital period, keeping one face toward its partner", True), ("When tides stop changing", False), ("When two moons orbit at the same speed", False), ("When gravity pulls the Moon apart", False)],
      "Tidal locking means the Moon rotates once per orbit, so the same face always points toward Earth."),
    # Scenario (21-30)
    q(21, "You see a thin crescent Moon just after sunset in the western sky. What phase is this?",
      [("Waxing crescent", True), ("Waning crescent", False), ("First quarter", False), ("Full moon", False)],
      "A thin crescent visible just after sunset in the west is a waxing crescent — it's growing and follows the Sun across the sky."),
    q(22, "A student notices that the Moon rises about 50 minutes later each day. Why?",
      [("The Moon moves eastward in its orbit, so Earth must rotate a bit extra each day to face it again", True), ("Earth's rotation is slowing down", False), ("The Sun's gravity pulls the Moon back", False), ("The Moon speeds up each day", False)],
      "The Moon advances ~13° eastward in its orbit each day, requiring about 50 extra minutes of Earth rotation to bring it back into view."),
    q(23, "If you could stand on the Moon and look at Earth, what would you observe when people on Earth see a new moon?",
      [("A fully illuminated Earth ('full Earth')", True), ("A dark Earth", False), ("A half-lit Earth", False), ("No Earth at all", False)],
      "When the Moon is between Earth and the Sun (new moon), an observer on the Moon would see Earth fully lit — the phases are opposite."),
    q(24, "A photographer wants to capture earthshine. When is the best time?",
      [("During a crescent moon phase, a few days before or after new moon", True), ("During a full moon", False), ("During a total lunar eclipse", False), ("At midnight when the Moon is highest", False)],
      "Earthshine is most visible during crescent phases when the dark part of the Moon can be faintly seen lit by light reflected from Earth."),
    q(25, "The same side of the Moon always faces Earth. A student says this means the Moon doesn't rotate. Is this correct?",
      [("No — the Moon rotates once per orbit (tidal locking), which is why the same face always points at Earth", True), ("Yes — the Moon does not rotate", False), ("No — the Moon rotates twice per orbit", False), ("Yes — only the Sun rotates", False)],
      "The Moon does rotate — its rotation period equals its orbital period (tidal locking), so one face always faces Earth."),
    q(26, "Ancient cultures used lunar calendars. What difficulty arises from using a purely lunar calendar?",
      [("12 lunar months total about 354 days, drifting about 11 days from the solar year each year", True), ("The Moon changes color each month", False), ("Lunar calendars have too many days", False), ("The Moon isn't visible every month", False)],
      "A 12-month lunar calendar has ~354 days, about 11 days short of a solar year, causing seasons to drift over time."),
    q(27, "During a third quarter moon, when does the Moon typically rise?",
      [("Around midnight", True), ("At sunset", False), ("At sunrise", False), ("At noon", False)],
      "The third quarter moon rises around midnight and is visible in the morning sky."),
    q(28, "A waxing gibbous Moon is visible in the sky. About how many days until the full moon?",
      [("A few days (about 3–4)", True), ("About 14 days", False), ("About 1 day", False), ("About 29 days", False)],
      "Waxing gibbous occurs between first quarter and full moon — roughly 3-4 days before full."),
    q(29, "If the Moon didn't orbit Earth but stayed fixed relative to the stars, would we still see phases?",
      [("No — without the changing Sun-Moon-Earth angle, the Moon's apparent illumination wouldn't change", True), ("Yes — the Sun would still light different parts", False), ("Yes — Earth's rotation would create phases", False), ("No — the Moon would become invisible", False)],
      "Lunar phases result from the changing angle between the Sun, Moon, and Earth as the Moon orbits. Without orbiting, the angle wouldn't change."),
    q(30, "An observer sees the Moon at first quarter high in the sky at sunset. Where in the sky will it be at midnight?",
      [("Setting on the western horizon", True), ("Rising in the east", False), ("Directly overhead", False), ("Below the horizon", False)],
      "The first quarter moon is roughly 90° east of the Sun — it's highest at sunset and sets around midnight."),
]
write_quiz("Lesson2.3_Quiz.json", 2, "2.3", "Lunar Phases", L23)

# ============================================================
# Lesson 2.4: Solar & Lunar Eclipses
# ============================================================
L24 = [
    q(1, "A solar eclipse occurs when:",
      [("The Moon passes between the Sun and Earth", True), ("Earth passes between the Sun and the Moon", False), ("The Sun passes between Earth and the Moon", False), ("Two planets align", False)],
      "A solar eclipse happens when the Moon moves directly between the Sun and Earth, casting a shadow on Earth."),
    q(2, "A lunar eclipse occurs when:",
      [("Earth is between the Sun and the Moon, casting its shadow on the Moon", True), ("The Moon is between the Sun and Earth", False), ("The Sun is between Earth and the Moon", False), ("The Moon enters a black hole's shadow", False)],
      "A lunar eclipse occurs when Earth's shadow falls on the Moon as they align Sun-Earth-Moon."),
    q(3, "During a total solar eclipse, which part of the Moon's shadow are you standing in?",
      [("The umbra", True), ("The penumbra", False), ("The antumbra", False), ("The corona", False)],
      "The umbra is the darkest, central part of the Moon's shadow where the Sun is completely blocked."),
    q(4, "Why don't eclipses happen every month?",
      [("The Moon's orbit is tilted about 5° relative to Earth's orbital plane", True), ("The Moon is too small", False), ("The Sun moves too fast", False), ("Earth's atmosphere prevents them", False)],
      "The Moon's orbital plane is inclined ~5° to the ecliptic, so perfect alignment (eclipse) only occurs occasionally."),
    q(5, "During a total lunar eclipse, the Moon often appears:",
      [("Reddish (a 'blood moon')", True), ("Blue", False), ("Completely invisible", False), ("Bright white", False)],
      "Earth's atmosphere bends red wavelengths of sunlight into the shadow, giving the Moon a reddish hue during totality."),
    q(6, "An annular solar eclipse occurs when:",
      [("The Moon is too far from Earth to completely cover the Sun, leaving a ring of light", True), ("The Moon is extra close and covers the Sun completely", False), ("Only half the Sun is covered", False), ("The eclipse happens at night", False)],
      "When the Moon is near apogee (farthest from Earth), it appears smaller and cannot fully cover the Sun, creating a 'ring of fire.'"),
    q(7, "The points where the Moon's orbit crosses the ecliptic plane are called:",
      [("Nodes", True), ("Poles", False), ("Vertices", False), ("Zeniths", False)],
      "The ascending and descending nodes are the two points where the Moon's tilted orbit crosses Earth's orbital plane."),
    q(8, "A partial solar eclipse occurs when:",
      [("Only part of the Sun is covered by the Moon", True), ("The Moon is completely hidden", False), ("The Sun goes behind Earth", False), ("Clouds block the Sun", False)],
      "In a partial solar eclipse, the Moon only covers a portion of the Sun's disc."),
    q(9, "The Saros cycle is approximately:",
      [("18 years, 11 days", True), ("12 months", False), ("29.5 days", False), ("100 years", False)],
      "The Saros cycle is ~18 years 11 days, after which nearly identical eclipses recur."),
    q(10, "Who can see a total lunar eclipse?",
      [("Anyone on the night side of Earth where the Moon is above the horizon", True), ("Only people in a narrow path", False), ("Only people at the equator", False), ("Only people at the poles", False)],
      "Unlike solar eclipses, a total lunar eclipse is visible from anywhere on Earth where the Moon is above the horizon."),
    # Vocabulary (11-20)
    q(11, "What is the 'umbra'?",
      [("The darkest, central part of a shadow where light is completely blocked", True), ("The outer, lighter part of a shadow", False), ("A type of eclipse", False), ("The Moon's surface", False)],
      "The umbra is the innermost, darkest region of a shadow where the light source is fully obscured."),
    q(12, "What is the 'penumbra'?",
      [("The outer, partial shadow where only some light is blocked", True), ("The darkest part of a shadow", False), ("A ring of light during an eclipse", False), ("The Sun's outer atmosphere", False)],
      "The penumbra is the lighter, outer region of a shadow where the light source is only partially obscured."),
    q(13, "What is an 'annular eclipse'?",
      [("A solar eclipse where a ring of sunlight remains visible around the Moon", True), ("A yearly eclipse", False), ("An eclipse that lasts one hour", False), ("A lunar eclipse that turns green", False)],
      "An annular eclipse occurs when the Moon is too far to completely cover the Sun, leaving a bright ring (annulus) visible."),
    q(14, "What is the 'corona' in the context of eclipses?",
      [("The Sun's outer atmosphere, visible during a total solar eclipse", True), ("The Moon's atmosphere", False), ("A bright ring around the Moon", False), ("A disease", False)],
      "The corona is the Sun's hot, tenuous outer atmosphere, normally invisible but spectacularly visible during total solar eclipses."),
    q(15, "What are 'eclipse nodes'?",
      [("The points where the Moon's orbit crosses the ecliptic plane", True), ("The center points of shadows", False), ("Points on Earth where eclipses are visible", False), ("The edges of the Sun", False)],
      "Eclipse nodes are where the Moon's orbital plane intersects the ecliptic; eclipses can only occur when the Moon is near a node."),
    q(16, "What is a 'Saros cycle'?",
      [("A period of approximately 18 years after which similar eclipses recur", True), ("The time between two full moons", False), ("The time for the Sun to rotate once", False), ("A 100-year eclipse pattern", False)],
      "The Saros cycle (~18 years 11 days) predicts when nearly identical eclipses will repeat."),
    q(17, "What is 'totality'?",
      [("The phase of an eclipse when the Sun or Moon is completely obscured", True), ("When all planets align", False), ("The entire moon cycle", False), ("Complete darkness at night", False)],
      "Totality is the brief period during an eclipse when the Sun (solar) or Moon (lunar) is fully within the shadow."),
    q(18, "What is the 'path of totality'?",
      [("The narrow track on Earth's surface where a total solar eclipse is visible", True), ("The orbit of the Moon", False), ("The Sun's path across the sky", False), ("The equator", False)],
      "The path of totality is the narrow band (typically 100-160 km wide) across Earth where the Moon's umbra sweeps during a total solar eclipse."),
    q(19, "What are 'Baily's beads'?",
      [("Points of sunlight shining through lunar valleys just before or after totality", True), ("Stars visible during an eclipse", False), ("Drops of rain during an eclipse", False), ("Beads of light from the corona", False)],
      "Baily's beads are caused by sunlight passing through gaps in the Moon's rugged limb, creating a string of bright points."),
    q(20, "What is the 'diamond ring effect'?",
      [("A single bright point of sunlight with the corona forming a ring, seen just before/after totality", True), ("A ring of planets around the Moon", False), ("Sunlight reflecting off Saturn's rings", False), ("A telescope lens effect", False)],
      "The diamond ring effect occurs when a single bead of sunlight shines through a lunar valley while the corona forms a bright ring."),
    # Scenario (21-30)
    q(21, "You are in the path of totality during a solar eclipse and notice the sky darkens dramatically, stars become visible, and the temperature drops. What part of the shadow are you in?",
      [("The umbra", True), ("The penumbra", False), ("The antumbra", False), ("No shadow — this is a lunar eclipse", False)],
      "Standing in the Moon's umbra during totality, the Sun is completely blocked, causing darkness, visible stars, and temperature drops."),
    q(22, "A friend 300 km away from your location reports seeing only a partial solar eclipse at the same time you see totality. Why?",
      [("They are in the penumbra, outside the narrow path of totality", True), ("They are looking through clouds", False), ("The Moon is smaller from their location", False), ("Sound waves interfere with the eclipse there", False)],
      "The path of totality is narrow; observers outside it are in the penumbra and see only a partial eclipse."),
    q(23, "During a total lunar eclipse, the Moon appears dark red. A student asks why it doesn't just disappear completely. What's the explanation?",
      [("Earth's atmosphere refracts (bends) red sunlight into the shadow, illuminating the Moon", True), ("The Moon glows on its own", False), ("Starlight illuminates the Moon", False), ("The Sun's corona lights the Moon", False)],
      "Earth's atmosphere acts like a lens, bending longer (red) wavelengths of sunlight around the planet and into the umbral shadow."),
    q(24, "Historical records show a solar eclipse occurred in 585 BCE that stopped a battle between the Lydians and Medes. How could historians verify the date?",
      [("By calculating backward using the Saros cycle and orbital mechanics", True), ("By carbon dating the battlefield", False), ("By analyzing the Moon's craters", False), ("By consulting old star maps", False)],
      "Eclipse cycles like the Saros are so predictable that astronomers can calculate exact dates of ancient eclipses."),
    q(25, "An astronomer predicts an annular eclipse. What must be true about the Moon's position in its orbit?",
      [("The Moon must be near apogee (farthest from Earth), appearing too small to fully cover the Sun", True), ("The Moon must be near perigee (closest to Earth)", False), ("The Moon must be at a node and at first quarter", False), ("The Moon must be behind Earth", False)],
      "Annular eclipses occur when the Moon is near apogee, making its apparent diameter smaller than the Sun's."),
    q(26, "If the Moon's orbit were in exactly the same plane as Earth's orbit, how often would eclipses occur?",
      [("Every new moon (solar) and every full moon (lunar) — twice a month", True), ("Never", False), ("Once a year", False), ("Every 18 years", False)],
      "If there were no orbital tilt, the Sun-Moon-Earth alignment would occur every new and full moon, producing eclipses each month."),
    q(27, "A teacher holds a small ball (the Moon) between a lamp (the Sun) and a globe (Earth). The ball's shadow on the globe is tiny. What does this demonstrate about solar eclipses?",
      [("The Moon's shadow on Earth is small, which is why only a narrow path sees totality", True), ("Solar eclipses cover the entire planet", False), ("The Moon is larger than the Sun", False), ("Eclipses last for days", False)],
      "This model shows why the path of totality is narrow — the Moon is small relative to the Sun, casting a small umbral shadow."),
    q(28, "Scientists notice that total solar eclipses won't be possible in about 600 million years. Why?",
      [("The Moon is slowly moving away from Earth, and will eventually appear too small to cover the Sun", True), ("The Sun is shrinking", False), ("Earth's orbit is changing shape", False), ("The Moon will stop orbiting", False)],
      "The Moon recedes ~3.8 cm/year from Earth; eventually its apparent size will be too small to create total solar eclipses."),
    q(29, "You observe a partial lunar eclipse. What can you infer about the Moon's position?",
      [("The Moon is near, but not exactly at, a node — only part of it enters Earth's umbra", True), ("The Moon is between Earth and the Sun", False), ("The Moon is at first quarter", False), ("It's a new moon", False)],
      "In a partial lunar eclipse, the Moon passes through only part of Earth's umbral shadow, meaning alignment is not perfectly exact."),
    q(30, "During a solar eclipse, scientists observe the Sun's corona and measure its temperature to be about 1-2 million °C — much hotter than the Sun's surface (~5,500°C). Why is this significant?",
      [("It reveals the 'coronal heating problem' — an ongoing mystery about why the corona is so much hotter than the surface", True), ("It proves the Sun is cooling down", False), ("The corona is always visible, so this isn't special", False), ("The temperature measurement is wrong", False)],
      "Eclipse observations of the corona's extreme temperature helped identify one of solar physics' biggest unsolved problems — coronal heating."),
]
write_quiz("Lesson2.4_Quiz.json", 2, "2.4", "Solar & Lunar Eclipses", L24)

# ============================================================
# Lesson 2.5: Tides & Gravitational Effects
# ============================================================
L25 = [
    q(1, "Tides on Earth are primarily caused by:",
      [("The gravitational pull of the Moon and the Sun", True), ("Wind patterns", False), ("Earth's magnetic field", False), ("Ocean currents alone", False)],
      "Tides result from the differential gravitational pull of the Moon (primarily) and the Sun on Earth's oceans."),
    q(2, "How many high tides typically occur in a 24-hour period?",
      [("Two", True), ("One", False), ("Four", False), ("Six", False)],
      "Most coastal locations experience two high tides and two low tides roughly every 24 hours and 50 minutes."),
    q(3, "Spring tides occur when:",
      [("The Sun, Moon, and Earth are aligned (new moon or full moon)", True), ("The Moon is at first quarter", False), ("Earth is at perihelion", False), ("Only during spring season", False)],
      "Spring tides happen at new and full moon when the Sun and Moon's gravitational pulls align, producing higher high tides."),
    q(4, "Neap tides occur when:",
      [("The Sun and Moon are at right angles relative to Earth (first or third quarter)", True), ("The Sun, Moon, and Earth are aligned", False), ("Earth is closest to the Sun", False), ("During a solar eclipse", False)],
      "Neap tides occur at quarter moons when the Sun and Moon pull at right angles, partially canceling each other."),
    q(5, "Which celestial body has the strongest tidal effect on Earth?",
      [("The Moon", True), ("The Sun", False), ("Jupiter", False), ("Mars", False)],
      "Despite being smaller, the Moon's proximity to Earth gives it about twice the tidal influence of the Sun."),
    q(6, "A tidal bulge forms on the side of Earth closest to the Moon because:",
      [("The Moon's gravity pulls water toward it more strongly on the near side", True), ("The Moon pushes water away", False), ("Wind blows water toward the Moon", False), ("Earth's spin flings water outward", False)],
      "Gravitational force is stronger on the near side of Earth, pulling water into a bulge toward the Moon."),
    q(7, "There is also a tidal bulge on the side of Earth OPPOSITE the Moon because:",
      [("Earth is pulled toward the Moon more than the water on the far side, creating a relative bulge", True), ("The Sun causes it", False), ("Centrifugal force from Earth's spin", False), ("Volcanic activity heats the water", False)],
      "The far-side bulge forms because Earth's center is pulled toward the Moon more than the distant water, leaving it 'behind.'"),
    q(8, "How much time passes between one high tide and the next?",
      [("About 12 hours and 25 minutes", True), ("Exactly 12 hours", False), ("About 6 hours", False), ("About 24 hours", False)],
      "Because the Moon advances in its orbit, consecutive high tides are about 12 hours and 25 minutes apart."),
    q(9, "Tidal friction is gradually causing:",
      [("Earth's rotation to slow down and the Moon to move farther away", True), ("Earth to spin faster", False), ("The Moon to move closer", False), ("The oceans to shrink", False)],
      "Tidal friction transfers rotational energy from Earth to the Moon, slowing Earth's spin and pushing the Moon farther away."),
    q(10, "The Bay of Fundy in Canada is known for:",
      [("Having the world's largest tidal range", True), ("Never having tides", False), ("Being the deepest bay", False), ("Having no marine life", False)],
      "The Bay of Fundy has tidal ranges exceeding 16 meters due to its shape, which amplifies tidal effects through resonance."),
    # Vocabulary (11-20)
    q(11, "What is a 'spring tide'?",
      [("An extra-high tide that occurs when the Sun, Moon, and Earth are aligned", True), ("A tide that only happens in spring", False), ("A freshwater tide", False), ("A tide caused by earthquakes", False)],
      "Spring tides (from 'springen,' to leap) produce the greatest tidal range, occurring at new and full moons."),
    q(12, "What is a 'neap tide'?",
      [("A moderate tide with the smallest tidal range, occurring at quarter moons", True), ("An extremely high tide", False), ("A tide during a solar eclipse", False), ("A tide with no water movement", False)],
      "Neap tides have the smallest difference between high and low water, occurring when Sun and Moon are at right angles."),
    q(13, "What is 'tidal range'?",
      [("The difference in water level between high tide and low tide", True), ("The distance the tide travels inland", False), ("The speed of tidal currents", False), ("The frequency of tides", False)],
      "Tidal range is the vertical difference between the high water mark and the low water mark."),
    q(14, "What is a 'tidal bulge'?",
      [("The elongation of the ocean surface toward (and away from) the Moon due to gravity", True), ("A tsunami wave", False), ("A mountain formed by tides", False), ("A cloud over the ocean", False)],
      "Tidal bulges are the raised areas of ocean water on the near and far sides of Earth relative to the Moon."),
    q(15, "What is 'tidal friction'?",
      [("The drag between ocean tides and the rotating Earth that gradually slows Earth's rotation", True), ("Friction between two ocean currents", False), ("Heat generated by the Moon", False), ("Friction between the atmosphere and space", False)],
      "Tidal friction converts Earth's rotational energy into heat, gradually slowing Earth's spin."),
    q(16, "What is a 'tidal bore'?",
      [("A surge of water that travels upstream in a river or narrow bay during incoming tide", True), ("A deep hole caused by tides", False), ("A boring tidal pattern", False), ("Underground tidal movement", False)],
      "A tidal bore is a wave front that rushes up certain rivers and estuaries with the incoming tide."),
    q(17, "What is the 'Roche limit'?",
      [("The minimum distance a moon can orbit before being torn apart by tidal forces", True), ("The maximum height of a tide", False), ("The farthest a moon can orbit", False), ("A limit on rocket speed", False)],
      "The Roche limit is the distance within which a celestial body held together only by gravity would be pulled apart by tidal forces."),
    q(18, "What are 'tidal forces'?",
      [("The differential gravitational pull across an extended body", True), ("The total gravity of the Moon", False), ("Ocean currents caused by wind", False), ("Magnetic forces in the ocean", False)],
      "Tidal forces arise because gravity varies in strength across an object — closer parts are pulled more than farther parts."),
    q(19, "What is 'tidal locking' in this context?",
      [("When tidal forces cause a body to always show the same face to its partner", True), ("When tides stop moving", False), ("When a harbor gate closes", False), ("When the ocean freezes", False)],
      "Tidal locking occurs when tidal forces synchronize a body's rotation with its orbital period, as with the Moon always showing one face to Earth."),
    q(20, "What is 'tidal resonance'?",
      [("When the natural period of water oscillation in a basin matches the tidal period, amplifying tides", True), ("When two tides cancel out", False), ("Sound produced by tides", False), ("Vibrations in the Moon", False)],
      "Tidal resonance occurs in bays like the Bay of Fundy where the basin's natural oscillation period enhances tidal amplitude."),
    # Scenario (21-30)
    q(21, "A sailor notices extremely high tides during a full moon. What type of tide is this?",
      [("Spring tide — the Sun and Moon are aligned, combining their gravitational pulls", True), ("Neap tide", False), ("Rip tide", False), ("Tidal bore", False)],
      "At full moon, the Sun, Earth, and Moon are aligned, producing spring tides with the largest tidal range."),
    q(22, "A week after a full moon, the tidal range noticeably decreases. Why?",
      [("The Moon is at third quarter — Sun and Moon are at right angles, producing neap tides", True), ("The Moon moved farther from Earth", False), ("Wind died down", False), ("Earth's rotation slowed", False)],
      "At quarter phases, the Sun and Moon's gravitational effects partially cancel, reducing tidal range (neap tides)."),
    q(23, "If the Moon were twice as far from Earth, how would tides be affected?",
      [("Tides would be much weaker since tidal force decreases with the cube of distance", True), ("Tides would be twice as strong", False), ("Tides would stay the same", False), ("Tides would stop entirely", False)],
      "Tidal force varies inversely with the cube of distance (1/r³), so doubling distance would reduce tidal force by a factor of 8."),
    q(24, "Ancient Romans noticed tides were connected to the Moon but couldn't explain why. Newton later provided the explanation. What was it?",
      [("His law of universal gravitation explained how differential gravity creates tidal bulges", True), ("He discovered the Moon was made of water", False), ("He invented the tide clock", False), ("He observed tides on the Moon", False)],
      "Newton's gravitational theory showed that the Moon's differential gravitational pull across Earth creates the tidal bulges."),
    q(25, "Jupiter's moon Io is the most volcanically active body in the solar system. Tidal forces from Jupiter are the cause. Why is Io so affected?",
      [("Io's orbit and Jupiter's immense gravity create enormous tidal flexing that heats Io's interior", True), ("Io has a very thick atmosphere", False), ("The Sun directly heats Io", False), ("Io has a very large iron core", False)],
      "Jupiter's massive gravity, combined with orbital resonances with other moons, flexes Io's interior, generating extreme heat and volcanism."),
    q(26, "A coastal town builds a tidal energy power station. During which phase of the Moon would it generate the most power?",
      [("During spring tides (new or full moon) when tidal range is greatest", True), ("During neap tides", False), ("During a solar eclipse", False), ("Only during storms", False)],
      "Greater tidal range during spring tides moves more water through turbines, generating more electricity."),
    q(27, "Earth's day was much shorter billions of years ago (about 6 hours). What lengthened it?",
      [("Tidal friction from the Moon gradually slowed Earth's rotation", True), ("The Sun's gravity slowed Earth", False), ("Asteroid impacts slowed Earth", False), ("Earth's core cooled down", False)],
      "Tidal friction has been transferring Earth's rotational energy to the Moon for billions of years, gradually lengthening the day."),
    q(28, "A student wonders why there are two tidal bulges (near side and far side) instead of just one on the side closest to the Moon. How would you explain?",
      [("On the far side, the ocean is left behind as Earth is pulled toward the Moon, creating a second bulge", True), ("The Sun creates the second bulge", False), ("Earth's spin throws water outward on the far side", False), ("One bulge is from high tide and one from low tide", False)],
      "Differential gravity means the near side is pulled more than Earth's center, and Earth's center is pulled more than the far-side water, creating bulges on both sides."),
    q(29, "If a moon orbits within its planet's Roche limit, what would happen to it?",
      [("Tidal forces would tear it apart, potentially forming a ring system", True), ("It would crash into the planet immediately", False), ("Nothing — the Roche limit has no real effect", False), ("It would start spinning faster", False)],
      "Inside the Roche limit, tidal forces exceed the moon's self-gravity, and it would break apart — as likely happened to form Saturn's rings."),
    q(30, "Two fishing villages are on the same coastline but 200 km apart. One has a 10-meter tidal range while the other has only 2 meters. What explains this?",
      [("Local geography (bay shape, depth, and coastline) can amplify or reduce tides through resonance and funneling", True), ("One village is closer to the Moon", False), ("One is at a higher latitude", False), ("Tides are random and unpredictable", False)],
      "Coastal features like narrow bays, underwater topography, and resonance effects dramatically influence local tidal range."),
]
write_quiz("Lesson2.5_Quiz.json", 2, "2.5", "Tides & Gravitational Effects", L25)

# ============================================================
# Lesson 2.6: Case Studies in Earth-Moon-Sun Interactions
# ============================================================
L26 = [
    q(1, "The 'Giant Impact Hypothesis' suggests the Moon formed from:",
      [("A Mars-sized body colliding with early Earth", True), ("A piece of the Sun breaking off", False), ("Jupiter's gravity capturing an asteroid", False), ("Volcanic eruptions on Earth", False)],
      "The leading theory is that a Mars-sized body (Theia) struck early Earth, and the debris coalesced to form the Moon."),
    q(2, "The Moon stabilizes Earth's axial tilt, which is important because:",
      [("Stable tilt prevents extreme climate variations over long periods", True), ("It makes the Moon visible at night", False), ("It causes earthquakes", False), ("It keeps the oceans from freezing", False)],
      "Without the Moon's stabilizing influence, Earth's tilt could vary wildly, causing extreme seasonal and climate changes."),
    q(3, "Which Apollo mission first landed humans on the Moon?",
      [("Apollo 11", True), ("Apollo 13", False), ("Apollo 1", False), ("Apollo 17", False)],
      "Apollo 11 landed Neil Armstrong and Buzz Aldrin on the Moon on July 20, 1969."),
    q(4, "Lunar retroreflectors placed by Apollo astronauts are used to:",
      [("Measure the Earth-Moon distance precisely with laser ranging", True), ("Communicate with aliens", False), ("Generate solar power", False), ("Map lunar craters", False)],
      "Scientists bounce laser beams off retroreflectors on the Moon and measure round-trip time to track the Moon's distance."),
    q(5, "The Moon is moving away from Earth at approximately:",
      [("3.8 cm per year", True), ("3.8 meters per year", False), ("3.8 km per year", False), ("It is moving closer", False)],
      "Laser ranging measurements show the Moon recedes about 3.8 cm per year due to tidal energy transfer."),
    q(6, "What was the significance of the 1919 solar eclipse for physics?",
      [("It confirmed Einstein's prediction that gravity bends light (general relativity)", True), ("It discovered the Moon has no atmosphere", False), ("It proved the Sun is a star", False), ("It measured the Sun's temperature", False)],
      "Arthur Eddington's observations during the 1919 eclipse showed starlight bending around the Sun, confirming general relativity."),
    q(7, "Earth-Moon-Sun interactions affect which of the following biological processes?",
      [("Reproductive cycles of marine organisms tied to tidal and lunar cycles", True), ("Photosynthesis in trees", False), ("DNA replication speed", False), ("Blood type determination", False)],
      "Many marine organisms (corals, horseshoe crabs) synchronize spawning with lunar and tidal cycles."),
    q(8, "The 'Saros cycle' has been used since which ancient civilization?",
      [("Babylonians", True), ("Romans", False), ("Vikings", False), ("Incas", False)],
      "The Babylonians discovered the Saros cycle and used it to predict eclipses over 2,500 years ago."),
    q(9, "What phenomenon did the study of total solar eclipses help discover about the Sun?",
      [("Helium — first detected in the Sun's spectrum during an eclipse", True), ("Oxygen in the Sun", False), ("The Sun's solid core", False), ("Water on the Sun", False)],
      "During the 1868 eclipse, a spectral line was observed that didn't match any known element — it was named helium (from 'helios,' sun)."),
    q(10, "Ancient Stonehenge is thought to have been used to:",
      [("Track solstices, equinoxes, and possibly predict eclipses", True), ("Store grain", False), ("Practice medicine", False), ("Mine metals", False)],
      "Stonehenge's alignment with solstice sunrise/sunset suggests it was an astronomical observatory and calendar."),
    # Vocabulary (11-20)
    q(11, "What is the 'Giant Impact Hypothesis'?",
      [("The theory that the Moon formed from debris after a Mars-sized object collided with early Earth", True), ("The theory that a giant meteor created the Moon's craters", False), ("The theory that Jupiter impacted the Sun", False), ("The theory that comets formed the oceans", False)],
      "The Giant Impact Hypothesis (Theia impact) is the leading explanation for the Moon's origin."),
    q(12, "What is 'laser ranging'?",
      [("Measuring distances by timing a laser beam's round trip to a retroreflector", True), ("Cutting rocks with a laser", False), ("Using lasers to communicate with the Moon", False), ("A laser light show", False)],
      "Lunar laser ranging bounces laser pulses off Moon retroreflectors to measure the Earth-Moon distance to centimeter precision."),
    q(13, "What is a 'retroreflector'?",
      [("A device that reflects light back to its source regardless of the angle of incidence", True), ("A mirror that only works at night", False), ("A telescope accessory", False), ("A type of camera lens", False)],
      "Retroreflectors (corner-cube reflectors) bounce light precisely back toward its source, enabling accurate distance measurements."),
    q(14, "What is the 'Theia' hypothesis about?",
      [("Theia is the name of the hypothetical Mars-sized body that collided with Earth to form the Moon", True), ("Theia is a distant star", False), ("Theia is an asteroid belt", False), ("Theia is a Greek telescope", False)],
      "The hypothetical planetary embryo that struck Earth is named Theia, after the Greek goddess who was the mother of Selene (the Moon)."),
    q(15, "What is 'tidal evolution'?",
      [("The long-term changes in orbits and rotations of bodies due to tidal interactions", True), ("Evolution of marine life due to tides", False), ("The change in tide height during a day", False), ("Plate tectonics driven by tides", False)],
      "Tidal evolution describes how tidal forces slowly modify the orbits and spin rates of interacting bodies over geological time."),
    q(16, "What is 'gravitational lensing'?",
      [("The bending of light by gravity, as predicted by general relativity", True), ("A lens powered by gravity", False), ("A focusing technique for telescopes", False), ("The magnification of the Moon during a eclipse", False)],
      "Gravitational lensing occurs when a massive object bends the path of light passing near it, confirmed during the 1919 eclipse."),
    q(17, "What is an 'eclipse season'?",
      [("A period (~34 days) when the Sun is near a lunar node and eclipses can occur", True), ("A season with extra eclipses", False), ("When the Sun is eclipsed every day", False), ("The summer months", False)],
      "Eclipse seasons occur about every 6 months when the Sun is near one of the Moon's orbital nodes."),
    q(18, "What is 'obliquity stabilization'?",
      [("The Moon's gravitational influence preventing large oscillations in Earth's axial tilt", True), ("Keeping the Moon's orbit stable", False), ("The Sun's role in steadying Earth's orbit", False), ("A spacecraft navigation technique", False)],
      "The Moon acts as a gravitational anchor, keeping Earth's axial tilt relatively stable at ~23.5° over long timescales."),
    q(19, "What is a 'synchronous orbit'?",
      [("An orbit where a body's orbital period matches its rotation period", True), ("An orbit that never changes", False), ("An orbit around two planets at once", False), ("A polar orbit", False)],
      "The Moon is in synchronous rotation — its rotation period equals its orbital period, so the same face always points at Earth."),
    q(20, "What are 'Milankovitch cycles'?",
      [("Long-term changes in Earth's orbit and tilt that affect climate over tens of thousands of years", True), ("Daily temperature cycles", False), ("Monthly tidal cycles", False), ("Cycles of solar flares", False)],
      "Milankovitch cycles include variations in orbital eccentricity, axial tilt, and precession that drive ice ages over tens of thousands of years."),
    # Scenario (21-30)
    q(21, "Apollo astronauts brought back lunar rocks that are chemically similar to Earth's mantle. What does this support?",
      [("The Giant Impact Hypothesis — the Moon formed from Earth's mantle material after a collision", True), ("The Moon is an old star", False), ("The Moon formed from the Sun", False), ("The Moon is made of cheese", False)],
      "The similarity of lunar and terrestrial rocks supports the idea that the Moon formed from material ejected from Earth's mantle after a giant impact."),
    q(22, "Mars has no large moon. Scientists calculate that Mars's axial tilt has varied between 15° and 35° over millions of years. What does this suggest about Earth's Moon?",
      [("The Moon stabilizes Earth's tilt — without it, Earth's tilt would vary wildly like Mars's", True), ("Mars never had an atmosphere", False), ("The Moon has no effect on Earth's tilt", False), ("Mars spins too fast for a moon", False)],
      "Mars's chaotic tilt variations show what happens without a stabilizing moon, highlighting the Moon's importance for Earth's climate stability."),
    q(23, "An astronomer uses laser ranging data to show the Moon was closer millions of years ago. What was one consequence for early Earth?",
      [("Tides were much stronger and days were shorter", True), ("It was always nighttime", False), ("Earth had no oceans", False), ("The Moon was hotter than the Sun", False)],
      "A closer Moon created much stronger tides and, through tidal friction differences, Earth was spinning faster (shorter days)."),
    q(24, "The 1919 eclipse proved a specific prediction of Einstein's. If the measurement hadn't matched, what would have happened to general relativity?",
      [("It would have been strongly challenged or disproved, as the light-bending prediction was a key test", True), ("Nothing — the theory was already proven by other means", False), ("Einstein would have won the Nobel Prize anyway", False), ("The eclipse would have been rescheduled", False)],
      "The 1919 eclipse was a crucial test — if starlight hadn't bent by the predicted amount, general relativity would have been seriously questioned."),
    q(25, "Coral growth rings show that 400 million years ago there were about 400 days in a year. What does this tell us about Earth-Moon interactions?",
      [("Earth rotated faster (shorter days), and tidal friction from the Moon has been gradually slowing it", True), ("The year was longer back then", False), ("Coral counted days wrong", False), ("The Moon was farther away", False)],
      "More days per year means shorter days — Earth's rotation has been slowing due to tidal friction, adding ~2 milliseconds per century."),
    q(26, "The discovery of helium during the 1868 eclipse was revolutionary because:",
      [("It was the first element discovered outside Earth — in the Sun's spectrum", True), ("Helium was already well known", False), ("It proved the Sun was made of hydrogen", False), ("It showed eclipses change the Sun's composition", False)],
      "Helium was identified in the solar spectrum during an eclipse before being found on Earth, a groundbreaking achievement in spectroscopy."),
    q(27, "If Earth suddenly lost the Moon, what would likely happen to Earth's seasons over millions of years?",
      [("Earth's axial tilt would become chaotic, causing extreme and unpredictable season changes", True), ("Seasons would stay exactly the same", False), ("Earth would stop spinning", False), ("The Sun would become brighter", False)],
      "Without the Moon's gravitational stabilization, Earth's obliquity would vary chaotically, causing drastic climate shifts."),
    q(28, "Horseshoe crabs spawn at high tide during full moons. How does this relate to Earth-Moon-Sun interactions?",
      [("Full moons produce spring tides with higher high tides, bringing water farther up the beach for safe egg-laying", True), ("The Moon's light helps them see", False), ("Full moons make the water warmer", False), ("Horseshoe crabs navigate by moonlight", False)],
      "Spring tides during full moons push water higher on beaches, providing ideal conditions for horseshoe crabs to lay eggs."),
    q(29, "Stonehenge's Heel Stone aligns with the rising Sun on the summer solstice. What does this reveal about its builders?",
      [("They had sophisticated understanding of astronomical cycles and solstice timing", True), ("They worshipped rocks", False), ("They had telescopes", False), ("The alignment is coincidental", False)],
      "The precise alignment shows that Neolithic people carefully tracked the Sun's position and understood the solstice cycle."),
    q(30, "A student asks: 'If the Moon keeps moving away, will it eventually escape Earth's gravity?' What is the answer?",
      [("No — the rate of recession is decreasing, and the Sun will become a red giant long before the Moon could escape", True), ("Yes — the Moon will escape in about 1 billion years", False), ("Yes — the Moon is accelerating away", False), ("The Moon will crash back into Earth", False)],
      "The Moon's recession rate slows as it moves farther out, and the Sun's evolution into a red giant (~5 billion years) will intervene first."),
]
write_quiz("Lesson2.6_Quiz.json", 2, "2.6", "Case Studies in Earth-Moon-Sun Interactions", L26)

# ============================================================
# Lesson 2.7: AP Prep: Orbital Calculations
# ============================================================
L27 = [
    q(1, "Kepler's Third Law states that the square of a planet's orbital period is proportional to:",
      [("The cube of its semi-major axis", True), ("The square of its semi-major axis", False), ("Its distance from the star", False), ("Its mass", False)],
      "Kepler's Third Law: T² ∝ a³, where T is the orbital period and a is the semi-major axis."),
    q(2, "If a planet is 4 AU from its star, and we use Kepler's Third Law (T² = a³ in appropriate units), what is T²?",
      [("64", True), ("16", False), ("8", False), ("256", False)],
      "T² = a³ = 4³ = 64, so the orbital period squared is 64 (in years² for AU)."),
    q(3, "Newton's form of Kepler's Third Law includes which additional variable compared to Kepler's original?",
      [("The masses of the orbiting bodies", True), ("The color of the star", False), ("The temperature of the planet", False), ("The number of moons", False)],
      "Newton generalized Kepler's law to T² = (4π²/G(M₁+M₂))a³, incorporating the masses of both bodies."),
    q(4, "What is the gravitational force equation?",
      [("F = GMm/r²", True), ("F = mv²/r", False), ("F = ma²", False), ("F = mc²", False)],
      "Newton's law of gravitation: F = GMm/r², where G is the gravitational constant, M and m are masses, and r is the separation distance."),
    q(5, "If the distance between two objects doubles, the gravitational force between them:",
      [("Decreases to one-quarter", True), ("Decreases to one-half", False), ("Doubles", False), ("Stays the same", False)],
      "Gravity follows an inverse-square law: doubling distance reduces force by 1/2² = 1/4."),
    q(6, "Orbital velocity of an object at distance r from mass M is given by:",
      [("v = √(GM/r)", True), ("v = GM/r", False), ("v = GMr", False), ("v = 2πr/T only", False)],
      "For circular orbits, v = √(GM/r), derived by equating gravitational force to centripetal force."),
    q(7, "The escape velocity from a planet's surface depends on:",
      [("The planet's mass and radius", True), ("The planet's color", False), ("The escaping object's mass", False), ("The planet's distance from its star", False)],
      "Escape velocity v_esc = √(2GM/R), depending only on the planet's mass M and radius R."),
    q(8, "For Earth, the escape velocity is approximately:",
      [("11.2 km/s", True), ("3.0 km/s", False), ("30 km/s", False), ("1.0 km/s", False)],
      "Earth's escape velocity is about 11.2 km/s — the minimum speed needed to leave Earth's gravitational influence."),
    q(9, "A satellite in a higher orbit compared to one in a lower orbit has:",
      [("Lower orbital velocity and longer orbital period", True), ("Higher orbital velocity and shorter period", False), ("The same velocity", False), ("No velocity", False)],
      "Higher orbits have larger r, so v = √(GM/r) is smaller, and T increases (Kepler's Third Law)."),
    q(10, "The gravitational constant G has units of:",
      [("N⋅m²/kg²", True), ("m/s²", False), ("kg⋅m/s", False), ("N/kg", False)],
      "G ≈ 6.674 × 10⁻¹¹ N⋅m²/kg² is the universal gravitational constant."),
    # Vocabulary (11-20)
    q(11, "What is the 'semi-major axis'?",
      [("Half of the longest diameter of an elliptical orbit", True), ("The shortest distance in an orbit", False), ("The focal point of an orbit", False), ("The radius of a circle", False)],
      "The semi-major axis (a) is half the longest dimension of an ellipse, used to characterize orbital size."),
    q(12, "What is 'orbital period'?",
      [("The time for one complete orbit around another body", True), ("The time for one rotation", False), ("The distance covered in one orbit", False), ("The speed of an orbit", False)],
      "The orbital period (T) is the time it takes for a body to complete one full revolution around another body."),
    q(13, "What is 'orbital velocity'?",
      [("The speed at which an object travels along its orbital path", True), ("The rotational speed of a planet", False), ("The speed of light in an orbit", False), ("The velocity of gravity", False)],
      "Orbital velocity is the speed needed to maintain a stable orbit at a given distance from the central body."),
    q(14, "What is 'escape velocity'?",
      [("The minimum speed needed to break free from a body's gravitational pull without further propulsion", True), ("The speed at which a planet rotates", False), ("The maximum speed in an orbit", False), ("The speed of light", False)],
      "Escape velocity is the minimum speed at which an object must travel to overcome a body's gravity permanently."),
    q(15, "What is 'gravitational potential energy'?",
      [("The energy stored due to an object's position in a gravitational field (U = -GMm/r)", True), ("The energy of motion", False), ("The energy of light", False), ("The heat inside a planet", False)],
      "Gravitational potential energy U = -GMm/r; it is negative because work must be done against gravity to separate the objects."),
    q(16, "What is a 'geostationary orbit'?",
      [("An orbit where a satellite's period matches Earth's rotation (24 hours), staying above the same point", True), ("An orbit at the surface of Earth", False), ("Any orbit around Earth", False), ("The Moon's orbit", False)],
      "A geostationary orbit at ~35,786 km altitude has a 24-hour period, keeping the satellite stationary relative to the ground."),
    q(17, "What is 'centripetal force' in orbital mechanics?",
      [("The inward force needed to keep an object moving in a circular path — in orbits, it's provided by gravity", True), ("An outward force pushing objects away", False), ("The force of the Sun's light", False), ("A force that only acts in straight lines", False)],
      "Centripetal force (F = mv²/r) keeps orbiting objects curved inward; gravity provides this force in orbits."),
    q(18, "What is an 'astronomical unit' (AU)?",
      [("The average distance from Earth to the Sun, about 1.496 × 10⁸ km", True), ("The distance from Earth to the Moon", False), ("The diameter of the Sun", False), ("One light-year", False)],
      "1 AU ≈ 149.6 million km, defined as the mean Earth-Sun distance and used to measure distances within the solar system."),
    q(19, "What is 'orbital eccentricity'?",
      [("A measure of how much an orbit deviates from a perfect circle (0 = circle, 1 = parabola)", True), ("The tilt of an orbit", False), ("The speed of an orbit", False), ("The number of orbits per year", False)],
      "Eccentricity (e) ranges from 0 (circle) to just under 1 (highly elongated ellipse); Earth's is ~0.017."),
    q(20, "What is 'vis-viva equation'?",
      [("The energy equation v² = GM(2/r - 1/a) relating velocity, position, and orbital parameters", True), ("The equation for light speed", False), ("A measure of a planet's size", False), ("Newton's first law", False)],
      "The vis-viva equation v² = GM(2/r - 1/a) gives the speed of an object at any point in its orbit."),
    # Scenario (21-30)
    q(21, "A planet orbits a star at 2 AU. Using Kepler's Third Law (T² = a³ in solar units), what is the orbital period?",
      [("About 2.83 years (√8)", True), ("Exactly 2 years", False), ("4 years", False), ("8 years", False)],
      "T² = a³ = 2³ = 8, so T = √8 ≈ 2.83 years."),
    q(22, "A spacecraft at Earth's orbit (1 AU) has an orbital speed of about 30 km/s. If it moves to 4 AU, estimate its new speed using v ∝ 1/√r.",
      [("About 15 km/s", True), ("About 7.5 km/s", False), ("About 30 km/s", False), ("About 60 km/s", False)],
      "v ∝ 1/√r, so at 4 AU: v = 30/√4 = 30/2 = 15 km/s."),
    q(23, "If you doubled Earth's mass but kept its radius the same, how would escape velocity change?",
      [("It would increase by a factor of √2 (about 1.41 times)", True), ("It would double", False), ("It would stay the same", False), ("It would halve", False)],
      "v_esc = √(2GM/R). Doubling M gives v_esc = √2 × original ≈ 1.41 × 11.2 ≈ 15.8 km/s."),
    q(24, "A satellite is in a circular orbit at 200 km above Earth. To move to a higher orbit at 400 km, it must:",
      [("Fire engines to increase its velocity temporarily, entering a transfer orbit", True), ("Slow down so gravity pulls it higher", False), ("Wait for the Moon to push it up", False), ("Drop mass to float up", False)],
      "To raise an orbit, a spacecraft must increase speed (Hohmann transfer), temporarily entering an elliptical transfer orbit."),
    q(25, "Two asteroids have the same orbital period but different eccentricities. Which has the same semi-major axis?",
      [("Both — Kepler's Third Law says the period depends only on the semi-major axis, not eccentricity", True), ("The one with higher eccentricity has a larger semi-major axis", False), ("The circular one has a larger semi-major axis", False), ("Neither — period depends on eccentricity", False)],
      "T² = (4π²/GM)a³ — the period is determined only by a, so equal periods mean equal semi-major axes regardless of eccentricity."),
    q(26, "Mars is about 1.52 AU from the Sun. Using Kepler's Third Law, estimate Mars's orbital period.",
      [("About 1.88 years", True), ("About 1.52 years", False), ("About 2.50 years", False), ("About 3.00 years", False)],
      "T² = a³ = 1.52³ ≈ 3.51, so T ≈ √3.51 ≈ 1.87 years. Mars's actual period is about 1.88 years."),
    q(27, "The International Space Station orbits at about 400 km altitude with a period of ~90 minutes. Why is this much shorter than 24 hours?",
      [("It's much closer to Earth than a geostationary orbit, so it travels faster and has a shorter period", True), ("It's moving slower than geostationary satellites", False), ("It orbits the Moon, not Earth", False), ("Its engines keep it going faster", False)],
      "At 400 km altitude, the ISS is much closer than geostationary orbit (35,786 km), requiring higher speed and having a shorter period."),
    q(28, "If a new planet is discovered with an orbital period of 8 years around a Sun-like star, what is its distance from the star?",
      [("4 AU", True), ("8 AU", False), ("2 AU", False), ("64 AU", False)],
      "T² = a³ → 8² = 64 = a³ → a = ∛64 = 4 AU."),
    q(29, "A comet has a very elongated orbit with a semi-major axis of 100 AU. What is its orbital period?",
      [("1000 years", True), ("100 years", False), ("10,000 years", False), ("10 years", False)],
      "T² = a³ = 100³ = 1,000,000, so T = √1,000,000 = 1000 years."),
    q(30, "An engineer needs to place a satellite in geostationary orbit (T = 24 hours). Using Kepler's Third Law, the required distance is about 42,164 km from Earth's center. Why is the answer in km from the center, not the surface?",
      [("Kepler's Third Law uses the distance from the center of mass (Earth's center), not the surface", True), ("It's easier to measure from the center", False), ("The surface distance is the same as center distance", False), ("Geostationary satellites are underground", False)],
      "Orbital mechanics use center-to-center distances. The altitude is 42,164 - 6,371 ≈ 35,786 km above Earth's surface."),
]
write_quiz("Lesson2.7_Quiz.json", 2, "2.7", "AP Prep: Orbital Calculations", L27)

print("\nUnit 2 complete!")
