#!/usr/bin/env python3
"""Integrated Science Unit 1 – Earth's Structure & Geology (9 lessons)."""
import json, os

PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "content_data", "integrated_science_lessons.json")
COURSE = "Integrated Science"

def build_lesson(unit, idx, title, summary_html, flashcards, quiz):
    key = f"u{unit}_l{unit}.{idx}"
    fc = [{"term": t, "definition": d} for t, d in flashcards]
    qs = []
    for qi, (qt, opts, exp) in enumerate(quiz, 1):
        options = []
        for o in opts:
            correct = o.startswith("*")
            options.append({"text": o.lstrip("*"), "is_correct": correct, "data_i18n": None})
        qs.append({"question_number": qi, "question_text": qt, "attempted": 2,
                    "data_i18n": None, "options": options, "explanation": exp})
    return key, {
        "unit": unit, "lesson_number": f"{unit}.{idx}", "title": title, "course": COURSE,
        "summary_sections": [{"title": f"Key Concepts: {title}", "content_html": summary_html, "data_i18n": None}],
        "flashcards": fc, "quiz_questions": qs
    }

lessons = {}

# 1.1 Layers of the Earth
k,v = build_lesson(1,1,"Layers of the Earth (Crust, Mantle, Core)",
    "<h3>Earth's Internal Structure</h3>"
    "<h4>Layers by Composition</h4>"
    "<ul><li><b>Crust:</b> Thin outermost layer. Continental crust (25-70 km, granitic) and oceanic crust (5-10 km, basaltic).</li>"
    "<li><b>Mantle:</b> Thick layer of silicate rock (2,900 km). Upper mantle contains the asthenosphere (partially molten).</li>"
    "<li><b>Core:</b> Iron-nickel. Outer core is liquid (2,200 km), inner core is solid (1,220 km radius) due to immense pressure.</li></ul>"
    "<h4>Layers by Physical Properties</h4>"
    "<ul><li><b>Lithosphere:</b> Rigid crust + uppermost mantle; broken into tectonic plates.</li>"
    "<li><b>Asthenosphere:</b> Partially molten, flows slowly; plates glide over it.</li>"
    "<li><b>Mesosphere:</b> Lower mantle, stronger but still capable of slow flow.</li></ul>",
    [("Crust","Outermost solid layer; continental (thick, granitic) and oceanic (thin, basaltic)."),
     ("Mantle","Thick silicate layer between crust and core; contains the partially molten asthenosphere."),
     ("Inner Core","Solid iron-nickel sphere at Earth's center; solid despite extreme heat due to enormous pressure."),
     ("Lithosphere","Rigid outer shell (crust + upper mantle) broken into tectonic plates."),
     ("Asthenosphere","Partially molten zone in the upper mantle that allows tectonic plates to move.")],
    [("The thinnest layer of the Earth is the:",["Mantle","Outer core","*Crust","Inner core"],"Earth's crust is 5-70 km."),
     ("Oceanic crust is primarily composed of:",["Granite","Sandstone","*Basalt","Limestone"],"Basaltic composition."),
     ("Continental crust is _____ than oceanic crust.",["Thinner","Denser","*Thicker","Younger"],"25-70 km vs 5-10 km."),
     ("The asthenosphere is important because it:",["Is solid rock","Creates earthquakes directly","*Allows tectonic plates to move by flowing slowly","Is the densest layer"],"Plate movement."),
     ("The outer core is:",["Solid iron","Silicate rock","*Liquid iron-nickel","Partially molten silicate"],"Liquid metal."),
     ("The inner core is solid despite extreme heat because:",["It's cool enough to solidify","*Extreme pressure raises the melting point above the actual temperature","It's made of rock","It recently cooled"],"Pressure effect."),
     ("Earth's magnetic field is generated by:",["The mantle","Crustal rocks","*Convection currents in the liquid outer core","The inner core alone"],"Geodynamo."),
     ("The lithosphere includes the crust and the:",["Entire mantle","Asthenosphere","*Uppermost rigid mantle","Outer core"],"Rigid shell."),
     ("Seismic waves helped scientists determine Earth's layers because:",["They can be seen","*They change speed and direction when passing through materials of different density and state","They create layers","They are constant"],"Seismic evidence."),
     ("P-waves can travel through solids and liquids, but S-waves:",["Travel through everything","Are faster","*Cannot travel through liquids (creating shadow zones that revealed the liquid outer core)","Only travel through liquids"],"Wave behavior."),
     ("The Mohorovičić discontinuity (Moho) marks the boundary between the:",["Mantle and core","*Crust and mantle","Inner and outer core","Lithosphere and mesosphere"],"Moho boundary."),
     ("Earth's core is mostly composed of:",["Silicon and oxygen","Magnesium and iron","*Iron and nickel","Carbon and hydrogen"],"Core composition."),
     ("The mantle makes up approximately _____ of Earth's volume.",["17%","50%","*84%","99%"],"Largest layer by volume."),
     ("Convection currents in the mantle are driven by:",["Gravity alone","The Moon's pull","*Heat from the core rising and cooler material sinking","Earth's rotation"],"Thermal convection."),
     ("The temperature at the inner core boundary is approximately:",["1,000°C","3,000°C","*5,000-6,000°C (comparable to the Sun's surface)","10,000°C"],"Core temperature."),
     ("Which layer is broken into tectonic plates?",["Asthenosphere","Mantle","*Lithosphere","Mesosphere"],"Plate tectonics."),
     ("Continental crust is less dense than oceanic crust, which is why continents:",["Sink","Move faster","*Float higher on the mantle (isostasy)","Are younger"],"Isostasy."),
     ("A seismologist studies Earth's interior using:",["Telescopes","Microscopes","*Seismic waves from earthquakes","Satellite images"],"Seismology."),
     ("The D″ layer at the base of the mantle is significant because it:",["Is the thickest layer","*Is a transition zone where the mantle contacts the core, influencing convection and hotspot formation","Contains water","Is part of the crust"],"Deep boundary."),
     ("If you could drill to Earth's center (6,371 km), you would pass through layers in order:",["Core → Mantle → Crust","Asthenosphere → Core → Crust","*Crust → Mantle → Outer Core → Inner Core","Mantle → Crust → Core"],"Layer sequence.")]
)
lessons[k]=v

# 1.2 Minerals
k,v = build_lesson(1,2,"Minerals (Classification, Identification Tests)",
    "<h3>Minerals</h3>"
    "<h4>What Defines a Mineral?</h4>"
    "<ul><li>Naturally occurring, inorganic, solid, definite chemical composition, and crystalline structure.</li></ul>"
    "<h4>Identification Tests</h4>"
    "<ul><li><b>Hardness:</b> Mohs scale (1-talc to 10-diamond).</li>"
    "<li><b>Luster:</b> Metallic vs. non-metallic (vitreous, pearly, earthy).</li>"
    "<li><b>Streak:</b> Color of powdered mineral on unglazed porcelain.</li>"
    "<li><b>Cleavage/Fracture:</b> How mineral breaks — along flat planes (cleavage) or irregular surfaces (fracture).</li>"
    "<li><b>Specific Gravity:</b> Density relative to water.</li></ul>",
    [("Mineral","Naturally occurring, inorganic solid with a definite chemical composition and crystalline structure."),
     ("Mohs Hardness Scale","Ranking minerals 1 (talc, softest) to 10 (diamond, hardest) based on scratch resistance."),
     ("Streak","The color of a mineral's powder when rubbed on unglazed porcelain; more reliable than surface color for ID."),
     ("Cleavage","The tendency of a mineral to break along flat, predictable planes determined by crystal structure."),
     ("Luster","How light reflects from a mineral's surface; classified as metallic or non-metallic (vitreous, pearly, earthy).")],
    [("A mineral must be all of the following EXCEPT:",["Naturally occurring","Crystalline structure","*Organic (minerals are inorganic by definition)","Definite chemical composition"],"Mineral definition."),
     ("Diamond is a 10 on the Mohs scale, meaning it:",["Is the softest","Can be scratched by quartz","*Can scratch all other minerals","Is always clear"],"Hardness."),
     ("Streak is more reliable than color for mineral ID because:",["It's faster","*The streak color is consistent even when surface color varies (e.g., hematite can look black but always streaks red)","It's prettier","All minerals streak white"],"Streak reliability."),
     ("A mineral that breaks along smooth, flat planes exhibits:",["Fracture","*Cleavage","Luster","Hardness"],"Breaking patterns."),
     ("Quartz has a hardness of 7 and _____ luster.",["Metallic","Earthy","*Vitreous (glassy)","Dull"],"Quartz properties."),
     ("Feldspar is the most abundant mineral group in Earth's crust, making up about:",["10%","30%","*~60%","90%"],"Feldspar abundance."),
     ("Silicate minerals dominate Earth's crust because:",["They're rare","*Silicon and oxygen are the two most abundant elements in the crust","They're the hardest","They form last"],"Silicate dominance."),
     ("A mineral with metallic luster and a red-brown streak is likely:",["Quartz","Calcite","*Hematite","Diamond"],"Hematite ID."),
     ("The acid test (HCl fizzing) identifies:",["Quartz","*Calcite (CaCO₃ reacts with acid to produce CO₂ bubbles)","Feldspar","Diamond"],"Acid test."),
     ("Specific gravity compares a mineral's density to:",["Air","*Water","Iron","Diamond"],"SG reference."),
     ("Halite (NaCl) can be identified by its:",["Hardness","Color","*Cubic cleavage and salty taste","Streak"],"Halite ID."),
     ("Mica minerals are characterized by:",["Conchoidal fracture","*Perfect cleavage in one direction, forming thin sheets","Hardness of 9","Metallic luster"],"Mica property."),
     ("Which is NOT a crystal system?",["Cubic","Hexagonal","Monoclinic","*Spherical (not a crystal system — crystals have flat faces and defined angles)"],"Crystal systems."),
     ("Calcite has a hardness of 3. A steel nail (hardness ~5.5) would:",["Not scratch it","Bounce off","*Scratch it easily","Dissolve it"],"Hardness comparison."),
     ("Minerals form through processes including:",["Only volcanic activity","Only evaporation","*Crystallization from magma, precipitation from solution, metamorphic recrystallization","Only weathering"],"Mineral formation."),
     ("Ore minerals are economically important because they:",["Are pretty","Are common","*Contain valuable metals or elements that can be extracted profitably","Are always rare"],"Economic geology."),
     ("Pyrite (FeS₂) is called 'fool's gold' because:",["It is gold","It's valuable","*Its metallic luster and gold color resemble real gold, but it's iron sulfide","It's dangerous"],"Pyrite."),
     ("Talc (Mohs 1) is used in baby powder because:",["It's hard","It's rare","*It's extremely soft and smooth (the softest mineral)","It's shiny"],"Talc application."),
     ("Polymorphs are minerals with the same composition but different:",["Streak","*Crystal structure (e.g., diamond and graphite are both pure carbon)","Color","Hardness only"],"Polymorphs."),
     ("Understanding minerals is fundamental to earth science because:",["Minerals are rare","*Rocks are made of minerals — understanding minerals is the foundation for understanding all geological processes","They're only for jewelry","Only geologists need to know"],"Foundation concept.")]
)
lessons[k]=v

# 1.3 Rock Cycle
k,v = build_lesson(1,3,"Rock Cycle (Igneous, Sedimentary, Metamorphic)",
    "<h3>The Rock Cycle</h3>"
    "<h4>Three Rock Types</h4>"
    "<ul><li><b>Igneous:</b> From cooled magma/lava. Intrusive (slow cooling, large crystals) vs. extrusive (fast cooling, small/no crystals).</li>"
    "<li><b>Sedimentary:</b> From compacted/cemented sediments. Clastic (broken pieces), chemical (precipitation), organic (biological remains).</li>"
    "<li><b>Metamorphic:</b> From existing rock changed by heat and/or pressure. Foliated (banded) vs. non-foliated.</li></ul>"
    "<h4>Cycle Processes</h4>"
    "<ul><li>Weathering → Erosion → Deposition → Compaction/Cementation → Uplift → Metamorphism → Melting → Crystallization</li></ul>",
    [("Igneous Rock","Formed from cooled and solidified magma (intrusive) or lava (extrusive)."),
     ("Sedimentary Rock","Formed from compacted and cemented sediments, chemical precipitation, or organic remains."),
     ("Metamorphic Rock","Existing rock transformed by heat, pressure, or chemical processes without fully melting."),
     ("Rock Cycle","The continuous process by which rocks are converted among igneous, sedimentary, and metamorphic types."),
     ("Foliation","Parallel alignment of mineral grains in metamorphic rock due to directed pressure, creating banded texture.")],
    [("Granite forms when magma cools slowly underground. It is:",["Extrusive igneous","Sedimentary","*Intrusive igneous","Metamorphic"],"Slow cooling = intrusive."),
     ("Basalt forms from rapidly cooled lava at the surface, making it:",["Intrusive and coarse","*Extrusive with fine-grained or glassy texture","Sedimentary","Metamorphic"],"Fast cooling = fine."),
     ("Sandstone is a classic example of a _____ sedimentary rock.",["Chemical","Organic","*Clastic (formed from compacted sand grains)","Metamorphic"],"Clastic sediment."),
     ("Limestone formed from accumulated shells is classified as:",["Clastic","*Organic (biochemical) sedimentary","Igneous","Metamorphic"],"Organic sedimentary."),
     ("When limestone is subjected to heat and pressure, it becomes:",["Quartzite","Slate","*Marble","Gneiss"],"Marble formation."),
     ("Shale metamorphosed by pressure becomes:",["Marble","Quartzite","*Slate","Granite"],"Shale → slate."),
     ("The rock cycle is driven primarily by:",["Gravity alone","Wind alone","*Earth's internal heat and surface energy from the Sun","Only water"],"Driving forces."),
     ("Intrusive igneous rocks have large crystals because:",["They cool quickly","They're metamorphic","*Slow cooling underground allows time for large crystal growth","They're sedimentary"],"Crystal size."),
     ("Obsidian (volcanic glass) cooled so quickly that it:",["Has large crystals","*Has no crystal structure (amorphous) — cooling was too fast for crystals to form","Is metamorphic","Is always black"],"Glassy texture."),
     ("Conglomerate is a sedimentary rock made of:",["Fine silt","Sand only","*Rounded pebbles and cobbles cemented together","Volcanic ash"],"Conglomerate."),
     ("Foliated metamorphic rocks like gneiss show:",["Random crystal arrangement","No visible texture","*Distinct banding/layering of minerals due to directed pressure","Fossils"],"Foliation."),
     ("Which process converts sediment into sedimentary rock?",["Melting","Metamorphism","*Compaction and cementation (lithification)","Crystallization"],"Lithification."),
     ("Coal forms from ancient plant material, making it a(n):",["Igneous rock","Mineral","*Organic sedimentary rock","Metamorphic rock"],"Coal classification."),
     ("Pumice floats on water because:",["It's made of ice","*It's full of gas bubbles (vesicles) making its overall density less than water","It's hollow","It's a mineral"],"Pumice property."),
     ("The rock cycle shows that:",["Rocks never change","Only igneous rocks exist","*Any rock type can be transformed into any other type given the right conditions","Metamorphic rocks are oldest"],"Cycle principle."),
     ("Quartzite forms from the metamorphism of:",["Limestone","Shale","*Sandstone (quartz sand recrystallizes into interlocking quartz grains)","Basalt"],"Quartzite origin."),
     ("Weathering is the _____ of rocks at Earth's surface.",["Movement","Deposition","*Breaking down (physical and chemical)","Formation"],"Weathering definition."),
     ("Erosion differs from weathering because erosion involves:",["No water","Chemical change only","*Transport of weathered material by water, wind, ice, or gravity","Only temperature changes"],"Erosion vs. weathering."),
     ("Sedimentary rocks are important because they:",["Are the hardest","Never contain fossils","*Often contain fossils and record Earth's surface history","Are the most common deep underground"],"Sedimentary significance."),
     ("A geologist finds a rock with interlocking crystals, no fossils, and banding. It's likely:",["Igneous","Sedimentary","*Metamorphic (interlocking crystals + banding = foliated metamorphic)","Artificial"],"Rock identification.")]
)
lessons[k]=v

# 1.4 Plate Tectonics
k,v = build_lesson(1,4,"Plate Tectonics (Continental Drift, Seafloor Spreading)",
    "<h3>Plate Tectonics</h3>"
    "<h4>Evidence for Continental Drift</h4>"
    "<ul><li>Puzzle-fit of coastlines (Africa & South America).</li>"
    "<li>Matching fossils across oceans (Mesosaurus, Glossopteris).</li>"
    "<li>Glacial striations in tropical regions.</li></ul>"
    "<h4>Seafloor Spreading</h4>"
    "<ul><li>Mid-ocean ridges produce new oceanic crust.</li>"
    "<li>Magnetic striping: symmetric reversals on either side of ridge.</li>"
    "<li>Age of ocean floor increases with distance from ridge.</li></ul>"
    "<h4>Plate Boundaries</h4>"
    "<ul><li><b>Divergent:</b> Plates move apart → new crust (mid-ocean ridges, rift valleys).</li>"
    "<li><b>Convergent:</b> Plates collide → subduction, mountains, or volcanic arcs.</li>"
    "<li><b>Transform:</b> Plates slide past each other → earthquakes (San Andreas Fault).</li></ul>",
    [("Continental Drift","Wegener's hypothesis that continents were once joined (Pangaea) and have since drifted apart."),
     ("Seafloor Spreading","New oceanic crust forms at mid-ocean ridges as magma rises, pushes plates apart, and solidifies."),
     ("Divergent Boundary","Where plates move apart; new crust forms (mid-ocean ridges) or continents rift apart."),
     ("Convergent Boundary","Where plates collide; denser plate subducts, forming trenches, volcanoes, or mountain ranges."),
     ("Transform Boundary","Where plates slide horizontally past each other; produces earthquakes (e.g., San Andreas Fault).")],
    [("Alfred Wegener proposed continental drift in 1912 but lacked a mechanism. The mechanism is now known as:",["Gravity","Erosion","*Mantle convection driving plate tectonics","Lunar tides"],"Driving force."),
     ("Pangaea was the supercontinent that existed approximately _____ million years ago.",["50","100","*250-300","1,000"],"Pangaea timing."),
     ("Matching Mesosaurus fossils on both South America and Africa support drift because:",["The animal could swim oceans","*The freshwater reptile couldn't cross oceans — the continents must have been joined","It was planted","Random chance"],"Fossil evidence."),
     ("At a divergent boundary, plates move _____ and new crust is _____.",["Together; destroyed","Past each other; unchanged","*Apart; created","Together; created"],"Divergent process."),
     ("The Mid-Atlantic Ridge is an example of a:",["Transform boundary","Convergent boundary","*Divergent boundary (separating the North American and Eurasian plates)","Hotspot"],"MAR."),
     ("When an oceanic plate converges with a continental plate:",["Nothing happens","The continent subducts","*The denser oceanic plate subducts beneath the continental plate","Both plates rise"],"Oceanic-continental."),
     ("The Himalayas formed from the collision of:",["An oceanic and continental plate","*Two continental plates (Indian and Eurasian — neither subducts easily, so rock is pushed upward)","Two oceanic plates","A transform boundary"],"Continental collision."),
     ("The San Andreas Fault is a _____ boundary.",["Divergent","Convergent","*Transform","Subduction"],"Transform fault."),
     ("Magnetic striping on the ocean floor provides evidence for seafloor spreading because:",["Stripes are colorful","*Symmetric magnetic reversals on both sides of the ridge show that new crust forms and moves outward","They're random","They indicate depth"],"Magnetic evidence."),
     ("Ocean crust near mid-ocean ridges is _____ than crust far from ridges.",["Older","Thicker","*Younger","Denser"],"Age pattern."),
     ("Subduction zones often produce:",["Deserts","Flat plains","*Volcanic arcs and deep ocean trenches","Glaciers"],"Subduction features."),
     ("The Ring of Fire encircles the _____ Ocean.",["Atlantic","Indian","*Pacific","Arctic"],"Ring of Fire."),
     ("Tectonic plates move at rates of approximately:",["Meters per day","*Centimeters per year (about as fast as fingernails grow)","Kilometers per year","They don't move"],"Plate speed."),
     ("GPS technology has confirmed plate tectonics by:",["Photographing plates","*Measuring the precise movement of locations over time (matching predicted plate velocities)","Recording earthquakes only","Mapping the ocean floor only"],"Modern evidence."),
     ("A hotspot volcano like Hawaii forms:",["At a plate boundary","*Over a stationary mantle plume as the plate moves over it (creating an island chain)","At a divergent boundary only","Randomly"],"Hotspot mechanism."),
     ("The East African Rift is an example of:",["A convergent boundary","A transform fault","*Continental rifting (a divergent boundary splitting Africa apart)","A stable region"],"Continental rift."),
     ("Convection in the mantle works by:",["Heating at the top","*Hot material rising from the core region, cooling at the surface, and sinking — creating circulation cells","Random movement","Only lateral flow"],"Convection process."),
     ("The oldest oceanic crust is about 200 million years old. Continental crust can be:",["Younger","The same age","*Over 4 billion years old (oceanic crust is recycled by subduction, continents persist)","200 million years too"],"Crust age comparison."),
     ("Plate tectonics theory unified which earlier ideas?",["Only continental drift","Only seafloor spreading","*Both continental drift AND seafloor spreading into a comprehensive theory","Neither"],"Unifying theory."),
     ("Plate tectonics is fundamental because it explains:",["Only volcanoes","Only earthquakes","Only mountain building","*The distribution of earthquakes, volcanoes, mountains, ocean basins, and even climate patterns"],"Comprehensive explanation.")]
)
lessons[k]=v

# 1.5 Earthquakes
k,v = build_lesson(1,5,"Earthquakes (Seismic Waves, Measurement, Prediction)",
    "<h3>Earthquakes</h3>"
    "<h4>Causes</h4>"
    "<p>Sudden release of energy from rock fracturing along faults. Most occur at plate boundaries.</p>"
    "<h4>Seismic Waves</h4>"
    "<ul><li><b>P-waves (Primary):</b> Fastest; compressional; travel through solids, liquids, and gases.</li>"
    "<li><b>S-waves (Secondary):</b> Slower; shear; travel only through solids.</li>"
    "<li><b>Surface waves:</b> Slowest but most destructive; Rayleigh and Love waves.</li></ul>"
    "<h4>Measurement</h4>"
    "<ul><li><b>Moment Magnitude Scale:</b> Measures total energy released. Each whole number = ~32× more energy.</li>"
    "<li><b>Seismograph:</b> Instrument that records ground motion.</li></ul>",
    [("Focus (Hypocenter)","The point underground where an earthquake originates; the actual location of rock fracture."),
     ("Epicenter","The point on Earth's surface directly above the focus; where shaking is typically strongest."),
     ("P-Waves","Primary waves; fastest seismic waves; compressional; travel through all states of matter."),
     ("S-Waves","Secondary waves; slower than P-waves; shear motion; cannot travel through liquids."),
     ("Moment Magnitude Scale","Measures total energy released by an earthquake; each whole number increase = ~32× more energy.")],
    [("The point underground where an earthquake begins is called the:",["Epicenter","*Focus (hypocenter)","Fault line","Seismic zone"],"Focus definition."),
     ("P-waves arrive first at seismic stations because they:",["Are more destructive","Travel only through rock","*Are the fastest seismic waves","Travel on the surface"],"P-wave speed."),
     ("S-waves cannot pass through Earth's outer core, revealing that it is:",["Solid","Dense","*Liquid (S-waves only travel through solids)","Hot"],"S-wave shadow zone."),
     ("Surface waves are the most destructive because they:",["Are fastest","Travel underground","*Move the ground in rolling and side-to-side motions at the surface","Reach the core"],"Surface wave damage."),
     ("The moment magnitude scale replaced the Richter scale because it:",["Is simpler","*Works for all earthquake sizes and distances (Richter saturates at high magnitudes)","Uses different instruments","Measures different things"],"MMS advantage."),
     ("A magnitude 7 earthquake releases approximately _____ times more energy than a magnitude 6.",["2","10","*~32","100"],"Energy scaling."),
     ("A magnitude 8 vs. magnitude 6 = ~32 × 32 =",["64","320","*~1,000 times more energy","10,000"],"Two-step scaling."),
     ("Earthquakes are located by measuring the time difference between:",["*P-wave and S-wave arrivals at multiple stations (triangulation)","Surface waves only","Magnitude and intensity","Day and night"],"Location method."),
     ("Minimum number of seismograph stations needed to locate an epicenter:",["1","2","*3 (triangulation requires three distance circles intersecting)","10"],"Triangulation."),
     ("The Modified Mercalli Scale measures earthquake:",["Magnitude","Energy","*Intensity (observed effects: damage, shaking felt)","Depth"],"Intensity scale."),
     ("Most earthquakes occur along:",["Random locations","Continental interiors","*Plate boundaries (especially convergent and transform)","Ocean surfaces"],"Seismic zones."),
     ("Liquefaction occurs when:",["Ice melts","Rocks melt","*Saturated, loose soil behaves like liquid during shaking (buildings can sink or tilt)","Water boils"],"Liquefaction."),
     ("A tsunami can be triggered by:",["Wind","Tides alone","*A large undersea earthquake displacing the ocean floor","River flooding"],"Tsunami cause."),
     ("The Pacific Ring of Fire produces _____ of the world's earthquakes.",["10%","50%","*~90%","100%"],"Ring seismicity."),
     ("Earthquake prediction is currently:",["Accurate to the day","Routine for scientists","*Not reliably possible — we can assess hazard probability but not predict exact timing","Unnecessary"],"Prediction limits."),
     ("Seismic hazard maps help communities by:",["Predicting earthquakes","*Showing areas most likely to experience strong shaking, guiding building codes and preparedness","Preventing earthquakes","Nothing practical"],"Hazard maps."),
     ("The elastic rebound theory explains earthquakes as:",["Gradual sliding","*Sudden release of stored elastic energy when rock along a fault snaps back after stress exceeds strength","Volcanic activity","Tidal forces"],"Elastic rebound."),
     ("Building codes in earthquake zones require:",["Taller buildings","*Flexible, reinforced structures that can absorb seismic energy without collapsing","Rigid, brittle construction","No special design"],"Engineering response."),
     ("Foreshocks are:",["Aftershocks","*Smaller earthquakes preceding the main shock (not always present and hard to identify until after the mainshock)","Surface waves","P-waves"],"Foreshocks."),
     ("Seismology provides knowledge of Earth's interior because:",["We can drill to the core","*Seismic waves change speed and direction based on the material they pass through, revealing internal structure","We can see inside","Theory alone"],"Seismology value.")]
)
lessons[k]=v

# 1.6 Volcanoes
k,v = build_lesson(1,6,"Volcanoes (Types, Eruptions, Hazards)",
    "<h3>Volcanoes</h3>"
    "<h4>Types of Volcanoes</h4>"
    "<ul><li><b>Shield:</b> Broad, gently sloping; low-viscosity basaltic lava (Mauna Loa, Hawaii).</li>"
    "<li><b>Cinder Cone:</b> Smallest; steep sides; explosive fragments (Parícutin).</li>"
    "<li><b>Composite (Stratovolcano):</b> Tall, steep; alternating lava/ash layers; explosive (Mt. St. Helens, Fuji).</li></ul>"
    "<h4>Eruption Factors</h4>"
    "<ul><li><b>Viscosity:</b> Higher silica = more viscous magma = more explosive.</li>"
    "<li><b>Gas Content:</b> More dissolved gas = more explosive eruptions.</li>"
    "<li><b>Temperature:</b> Hotter magma is less viscous, flows more easily.</li></ul>",
    [("Shield Volcano","Broad, gently sloping volcano built from fluid basaltic lava flows; relatively gentle eruptions (e.g., Mauna Loa)."),
     ("Composite Volcano","Steep-sided volcano built of alternating lava and ash layers; highly explosive eruptions (e.g., Mt. St. Helens)."),
     ("Viscosity","Resistance to flow; high-silica magma is more viscous and produces more explosive eruptions."),
     ("Pyroclastic Flow","A fast-moving, extremely hot cloud of gas, ash, and rock fragments; the most deadly volcanic hazard."),
     ("Volcanic Explosivity Index (VEI)","Scale from 0-8 measuring eruption size based on volume of ejected material.")],
    [("Shield volcanoes have gentle slopes because:",["They're small","They erupt explosively","*Their low-viscosity basaltic lava flows long distances before solidifying","They're old"],"Shield shape."),
     ("The most explosive eruptions come from _____ magma.",["Basaltic (low silica)","*Rhyolitic (high silica, high viscosity — traps gas until catastrophic release)","All types equally","Only underwater"],"Silica-explosivity link."),
     ("Mt. St. Helens (1980) is an example of a:",["Shield volcano","Cinder cone","*Composite (stratovolcano)","Hotspot volcano"],"Composite example."),
     ("Pyroclastic flows are extremely dangerous because they:",["Move slowly","Are cool","*Travel at 100+ km/h at 700°C+, incinerating everything in their path","Only occur underwater"],"Pyroclastic hazard."),
     ("Most volcanoes are found at:",["Plate interiors only","*Convergent and divergent plate boundaries (subduction zones and mid-ocean ridges)","Random locations","The poles"],"Volcano distribution."),
     ("Hawaii's volcanoes are located in the middle of a plate because of a:",["Transform fault","Convergent boundary","*Hotspot (mantle plume beneath the Pacific Plate)","Divergent boundary"],"Hotspot volcanism."),
     ("Lahar is a volcanic:",["Lava flow","Gas emission","*Mudflow (volcanic debris mixed with water — can travel far and bury communities)","Earthquake"],"Lahar hazard."),
     ("The 1815 eruption of Mt. Tambora caused the 'Year Without a Summer' because:",["It was cold naturally","*Massive amounts of ash and sulfur dioxide in the stratosphere blocked sunlight globally","It created a tsunami","It was a myth"],"Climate impact."),
     ("Magma with more dissolved gas produces more explosive eruptions because:",["Gas is heavy","Gas is inert","*Expanding gas bubbles blast magma apart when pressure is released at the surface","Gas cools magma"],"Gas-driven explosivity."),
     ("The Ring of Fire contains about _____ of the world's active volcanoes.",["25%","50%","*~75%","100%"],"Ring of Fire volcanoes."),
     ("Caldera formation occurs when:",["Lava builds up","A mountain grows","*A magma chamber empties and the volcano's top collapses inward (e.g., Yellowstone, Crater Lake)","Erosion removes the peak"],"Caldera."),
     ("Volcanic soil is often very fertile because:",["It's dry","*Volcanic ash and weathered lava are rich in minerals and nutrients","It's acidic","It's sandy"],"Fertile soil."),
     ("Volcanic eruptions can be predicted with some success by monitoring:",["Only visual observation","*Seismic activity, ground deformation (GPS/tiltmeters), gas emissions, and thermal changes","Only satellite images","Nothing works"],"Monitoring tools."),
     ("Tephra refers to:",["Lava flows","*All airborne volcanic material (ash, lapilli, bombs) ejected during an eruption","Volcanic gas","Magma underground"],"Tephra."),
     ("Obsidian and pumice both form from felsic lava. The difference is:",["Color","Weight only","*Pumice has gas bubbles (vesicles) making it frothy; obsidian cooled too quickly for bubbles to form","Chemical composition"],"Same source, different texture."),
     ("Volcanologists classify eruptions by the VEI. A VEI-8 'super-eruption' occurs roughly every:",["10 years","100 years","10,000 years","*100,000+ years (e.g., Yellowstone's last super-eruption was ~640,000 years ago)"],"VEI-8 frequency."),
     ("Volcanic gases are primarily:",["Nitrogen","Oxygen","*Water vapor (60-95%), CO₂, and SO₂","Helium"],"Volcanic gases."),
     ("Submarine volcanoes at mid-ocean ridges create:",["Mountains on land","*New oceanic crust (the most volcanically active zone on Earth, mostly hidden underwater)","Cinder cones","Calderas"],"Submarine volcanism."),
     ("The difference between magma and lava is:",["Chemical composition","Temperature","*Location: magma is molten rock underground; lava is molten rock at the surface","Viscosity only"],"Magma vs. lava."),
     ("Studying volcanoes is important because:",["They're rare","*~800 million people live within 100 km of an active volcano — understanding hazards saves lives","Only scientists care","They don't affect climate"],"Volcano significance.")]
)
lessons[k]=v

# 1.7 Mountain Building
k,v = build_lesson(1,7,"Mountain Building & Geological Structures",
    "<h3>Mountain Building (Orogeny)</h3>"
    "<h4>Types of Mountains</h4>"
    "<ul><li><b>Fold Mountains:</b> Formed by compression at convergent boundaries (Himalayas, Appalachians).</li>"
    "<li><b>Fault-Block Mountains:</b> Formed by tensional forces lifting blocks along normal faults (Sierra Nevada, Tetons).</li>"
    "<li><b>Volcanic Mountains:</b> Built by eruptions (Mt. Rainier, Mt. Fuji).</li>"
    "<li><b>Dome Mountains:</b> Uplifted by magma pushing up without erupting (Black Hills).</li></ul>"
    "<h4>Geological Structures</h4>"
    "<ul><li><b>Anticline:</b> Upward fold (arch). <b>Syncline:</b> Downward fold (trough).</li>"
    "<li><b>Fault types:</b> Normal (tension), reverse/thrust (compression), strike-slip (shear).</li></ul>",
    [("Orogeny","The process of mountain building, typically by tectonic forces (folding, faulting, and uplift)."),
     ("Fold Mountains","Mountains formed by compressional forces folding rock layers upward (e.g., Himalayas, Alps)."),
     ("Fault-Block Mountains","Mountains formed when tensional forces cause blocks of rock to be uplifted along normal faults."),
     ("Anticline","An upward (arch-shaped) fold in rock layers; oldest rocks at the center."),
     ("Syncline","A downward (trough-shaped) fold in rock layers; youngest rocks at the center.")],
    [("The Himalayas were formed by:",["Volcanic eruptions","Normal faulting","*Compression from the collision of the Indian and Eurasian plates (fold mountains)","Erosion"],"Himalayan orogeny."),
     ("Fault-block mountains form under _____ stress.",["Compressional","Shear","*Tensional (extensional forces pull crust apart, blocks drop or rise along normal faults)","No stress"],"Tensional faulting."),
     ("In a normal fault, the hanging wall moves:",["Up","Sideways","*Down (relative to the footwall — caused by tensional forces pulling apart)","Not at all"],"Normal fault motion."),
     ("In a reverse fault, the hanging wall moves:",["Down","Sideways","*Up (caused by compressional forces pushing together)","Not at all"],"Reverse fault motion."),
     ("An anticline is:",["A downward fold","A fault","*An upward arch-shaped fold in rock layers","A volcanic feature"],"Anticline."),
     ("In an anticline, the oldest rocks are found:",["At the edges","At the top only","*At the center (core) of the fold","Underneath everything"],"Anticline rock ages."),
     ("A strike-slip fault produces _____ motion.",["Up-down","*Horizontal (lateral) — plates slide past each other (e.g., San Andreas Fault)","Diagonal","Circular"],"Strike-slip."),
     ("A thrust fault is a reverse fault with a dip angle of less than:",["90°","60°","*45° (very low angle, allowing large horizontal displacement of rock sheets)","10°"],"Thrust fault."),
     ("Mt. Rainier is an example of a _____ mountain.",["Fold","Fault-block","*Volcanic (built by eruptions adding layers of lava and ash)","Dome"],"Volcanic mountain."),
     ("The Appalachian Mountains are old fold mountains that are _____ than the Himalayas.",["Taller","The same height","*Much shorter and more eroded (formed ~480-300 Ma, heavily weathered over time)","Younger"],"Old mountains."),
     ("Isostasy explains why mountains have deep 'roots' because:",["They're growing","*Thick continental crust sinks deeper into the mantle to maintain gravitational equilibrium (like an iceberg)","They're eroding","They float on water"],"Isostatic balance."),
     ("When mountains erode, the crust _____ in response (isostatic rebound).",["Sinks","Stays same","*Rises (less weight means the crust floats higher — like removing cargo from a ship)","Moves sideways"],"Rebound."),
     ("The Black Hills of South Dakota are _____ mountains.",["Fold","Fault-block","Volcanic","*Dome (magma pushed up overlying rock without erupting)"],"Dome mountains."),
     ("Geological maps use strike and dip to describe:",["Volcano locations","*The orientation and angle of tilted rock layers in the field","Earthquake epicenters","River directions"],"Strike and dip."),
     ("A graben is a:",["Mountain peak","Uplifted block","*Downdropped block between two normal faults (forms rift valleys)","Volcanic crater"],"Graben."),
     ("A horst is:",["A valley","A downdropped block","*An uplifted block between normal faults (forms mountains or plateaus)","A volcanic feature"],"Horst."),
     ("The Basin and Range Province in the western US formed from:",["Compression","Transform faulting","*Extension (tensional forces creating alternating horsts and grabens)","Volcanic activity only"],"Basin and Range."),
     ("Joint patterns in rocks differ from faults because joints involve:",["Large displacement","Melting","*Fractures with NO relative displacement (cracks without sliding)","Folding"],"Joints vs. faults."),
     ("Orogenies are linked to plate tectonics because mountain building primarily occurs at:",["Hotspots","*Convergent boundaries (collision and subduction zones)","The equator","Random locations"],"Tectonic link."),
     ("Understanding geological structures helps with:",["Only academic study","*Finding oil/gas (trapped in anticlines), water resources, assessing earthquake hazards, and construction planning","Nothing practical","Only mining"],"Practical applications.")]
)
lessons[k]=v

# 1.8 Geological Resources
k,v = build_lesson(1,8,"Geological Resources (Ores, Fossil Fuels)",
    "<h3>Geological Resources</h3>"
    "<h4>Metallic Ores</h4>"
    "<ul><li>Formed by magmatic, hydrothermal, sedimentary, and weathering processes.</li>"
    "<li>Examples: iron (hematite), copper (chalcopyrite), gold (native), aluminum (bauxite).</li></ul>"
    "<h4>Fossil Fuels</h4>"
    "<ul><li><b>Coal:</b> From ancient swamp vegetation; peat → lignite → bituminous → anthracite.</li>"
    "<li><b>Oil & Natural Gas:</b> From marine organisms buried under sediment; require source rock, migration, and trap.</li></ul>"
    "<h4>Non-Metallic Resources</h4>"
    "<ul><li>Sand, gravel, limestone (cement), gypsum (drywall), clay, phosphates (fertilizer).</li></ul>",
    [("Ore","A rock containing enough valuable mineral to be mined profitably."),
     ("Fossil Fuels","Coal, oil, and natural gas formed from ancient organisms over millions of years; non-renewable energy sources."),
     ("Hydrothermal Deposit","Mineral deposit formed when hot, mineral-rich water circulates through rock and deposits minerals in fractures."),
     ("Petroleum Trap","A geological structure that stops the upward migration of oil/gas, allowing it to accumulate (anticline, fault, stratigraphic)."),
     ("Coal Rank","The degree of metamorphism of coal: peat → lignite → bituminous → anthracite (increasing carbon content and energy).")],
    [("An ore is defined as a rock that:",["Contains any mineral","Is hard","*Contains enough valuable mineral to be extracted at a profit","Is always metallic"],"Ore definition."),
     ("Hydrothermal deposits form when:",["Rocks weather","Ice melts","*Hot, mineral-rich fluids deposit minerals in cracks and fractures as they cool","Wind erodes rock"],"Hydrothermal process."),
     ("Bauxite is the primary ore of:",["Iron","Copper","*Aluminum","Gold"],"Bauxite-aluminum."),
     ("Coal formation begins with:",["Marine organisms","Desert sand","*Accumulation of plant material in swamps (peat)","Volcanic eruptions"],"Coal origin."),
     ("The highest rank (most energy) of coal is:",["Peat","Lignite","Bituminous","*Anthracite (highest carbon content, hardest, most energy per unit)"],"Coal ranking."),
     ("Petroleum (oil) forms from:",["Land plants","*Ancient marine organisms (plankton) buried under sediment and subjected to heat and pressure over millions of years","Volcanic gas","Meteorites"],"Oil origin."),
     ("An oil trap requires:",["Only source rock","Only a reservoir","*Source rock, reservoir rock (porous), and cap rock (impermeable seal) — plus migration pathways","Only pressure"],"Trap components."),
     ("Anticline traps are common oil traps because:",["They're flat","They're deep","*Oil migrates upward through porous rock and accumulates at the top of the arch under impermeable cap rock","They're at the surface"],"Anticline trap."),
     ("Natural gas is primarily composed of:",["Oxygen","Carbon dioxide","*Methane (CH₄)","Nitrogen"],"Natural gas."),
     ("Fossil fuels are considered non-renewable because they:",["Can't be burned","*Take millions of years to form — we use them far faster than nature replaces them","Are infinite","Only exist in one place"],"Non-renewable."),
     ("Fracking (hydraulic fracturing) extracts oil and gas by:",["Drilling only","Heating rock","*Injecting high-pressure fluid to fracture rock and release trapped hydrocarbons","Mining surface rock"],"Fracking."),
     ("Sand and gravel are the most used non-metallic resources for:",["Fuel","*Construction (concrete, roads, building foundations)","Food","Electronics"],"Construction materials."),
     ("Phosphate rock is critical for:",["Building materials","Fuel","*Fertilizer production (essential for global agriculture)","Electronics"],"Phosphate."),
     ("Rare earth elements are used in:",["Only jewelry","*Electronics, magnets, batteries, wind turbines, and defense technology","Only paint","Only construction"],"REE applications."),
     ("The environmental impact of mining includes:",["No impact","*Habitat destruction, water pollution, soil contamination, and air quality issues","Only positive effects","Only noise"],"Mining impacts."),
     ("Reclamation refers to:",["Mining more","*Restoring mined land to a natural or useful state after extraction is complete","Abandoning mines","Finding new deposits"],"Reclamation."),
     ("Peak oil theory suggests that:",["Oil is infinite","*Global oil production will reach a maximum and then decline as reserves are depleted","Oil production only increases","Oil is renewable"],"Peak oil."),
     ("Conflict minerals (tantalum, tin, tungsten, gold) are called 'conflict' because:",["They fight each other","*Their mining and trade have funded armed conflicts in some regions, particularly central Africa","They're dangerous to handle","They're radioactive"],"Conflict minerals."),
     ("The geological conditions that create ore deposits include all EXCEPT:",["Hydrothermal activity","Magmatic processes","Weathering and concentration","*Biological evolution (biology doesn't create ore deposits directly; geological processes do)"],"Ore formation processes."),
     ("Geological resource management is important because:",["Resources are unlimited","*Non-renewable resources are finite — sustainable extraction, recycling, and alternatives are essential for the future","Only money matters","Technology will solve everything"],"Resource management.")]
)
lessons[k]=v

# 1.9 Case Studies in Natural Hazards
k,v = build_lesson(1,9,"Case Studies in Natural Hazards",
    "<h3>Case Studies in Natural Hazards</h3>"
    "<h4>Earthquake Case Studies</h4>"
    "<ul><li><b>2011 Tōhoku, Japan (M9.1):</b> Triggered massive tsunami; Fukushima nuclear disaster; ~20,000 deaths.</li>"
    "<li><b>2010 Haiti (M7.0):</b> Devastating due to poor construction; ~200,000+ deaths; highlighted vulnerability.</li></ul>"
    "<h4>Volcanic Case Studies</h4>"
    "<ul><li><b>1980 Mt. St. Helens:</b> Lateral blast; 57 deaths; ecosystem recovery studied.</li>"
    "<li><b>79 AD Pompeii (Vesuvius):</b> Pyroclastic flows buried city; preserved in ash.</li></ul>"
    "<h4>Lessons Learned</h4>"
    "<ul><li>Building codes, early warning systems, community preparedness, and land-use planning save lives.</li></ul>",
    [("2011 Tōhoku Earthquake","Magnitude 9.1 off Japan; triggered a devastating tsunami and the Fukushima nuclear disaster; ~20,000 deaths."),
     ("2010 Haiti Earthquake","Magnitude 7.0; catastrophic due to poor infrastructure and poverty; ~200,000+ deaths; highlighted preparedness gaps."),
     ("1980 Mt. St. Helens","Lateral blast eruption in Washington state; 57 deaths; major case study in volcanic monitoring and ecosystem recovery."),
     ("Tsunami Early Warning System","Network of ocean buoys and seismic stations that detect tsunamis and alert coastal populations to evacuate."),
     ("Disaster Preparedness","Planning, infrastructure investment, building codes, early warning systems, and education that reduce natural hazard casualties.")],
    [("The 2011 Tōhoku earthquake was magnitude:",["7.0","8.0","*9.1 (one of the most powerful ever recorded)","10.0"],"Tōhoku magnitude."),
     ("The Tōhoku earthquake caused the most deaths through:",["Building collapse","Fire","*The tsunami (waves up to 40 meters inundated coastal areas)","Ground shaking alone"],"Tsunami deaths."),
     ("The Fukushima nuclear disaster was triggered by:",["The earthquake directly","A volcanic eruption","*The tsunami flooding the plant and disabling cooling systems","Human error alone"],"Fukushima cause."),
     ("Haiti's 2010 earthquake was 'only' M7.0 but killed ~200,000+ because:",["It was deep","It was offshore","*Poor building construction, dense population, poverty, and lack of preparedness amplified the disaster","It was at a convergent boundary"],"Vulnerability factors."),
     ("Comparing Japan (M9.1, ~20K deaths) to Haiti (M7.0, ~200K deaths) shows that:",["Magnitude determines deaths","*Preparedness, infrastructure, and wealth dramatically affect outcomes — Haiti was far more vulnerable despite the weaker quake","Both had equal impact","Only location matters"],"Preparedness matters."),
     ("Mt. St. Helens erupted with a lateral blast because:",["It was a shield volcano","The summit was stable","*A massive landslide removed the north face, releasing pressure sideways in a directed blast","It was underwater"],"Lateral blast."),
     ("The eruption of Vesuvius in 79 AD preserved Pompeii because:",["Lava covered it slowly","*Pyroclastic flows and ash buried the city rapidly, preserving buildings and victims in volcanic material","It was frozen","It was underwater"],"Pompeii preservation."),
     ("Tsunami early warning systems work by:",["Predicting earthquakes","*Detecting seismic events and ocean level changes via buoys, then alerting coastal areas before waves arrive","Stopping tsunamis","Building walls only"],"Warning systems."),
     ("Japan's strict building codes saved lives during Tōhoku because:",["Buildings were underground","*Earthquake-resistant design (base isolation, flexible frames) prevented widespread building collapse despite M9.1 shaking","Buildings were short","Buildings were wooden"],"Building codes."),
     ("The Richter scale is logarithmic, meaning M9.1 releases _____ times more energy than M7.0.",["2","100","*~45,000× (each magnitude step = ~32× energy; 2.1 steps ≈ 32^2.1)","1,000,000"],"Energy comparison."),
     ("The 2004 Indian Ocean tsunami killed ~230,000 across 14 countries primarily because:",["The earthquake was too large","*There was no tsunami warning system in the Indian Ocean at the time","It was unexpected geology","The region is flat"],"Warning gap."),
     ("After 2004, the Indian Ocean Tsunami Warning System was:",["Not built","Delayed","*Established (demonstrating how disasters drive policy and preparedness improvements)","Unnecessary"],"Response to disaster."),
     ("Volcanic monitoring tools include:",["Only visual observation","*Seismographs, GPS (ground deformation), gas analyzers, satellite imagery, and thermal cameras","Only seismographs","Only satellites"],"Multiple monitoring."),
     ("Mt. St. Helens provided scientists with:",["No useful data","*A landmark case study in eruption prediction, lateral blasts, pyroclastic flows, and ecosystem recovery","Only destruction","Only photographs"],"Scientific value."),
     ("The ecosystem around Mt. St. Helens after 1980:",["Never recovered","Is still barren","*Has gradually recovered, providing invaluable data on ecological succession after volcanic disturbance","Was immediately replanted"],"Ecosystem recovery."),
     ("Land-use planning near volcanoes should:",["Ignore hazards","Build everywhere","*Restrict development in high-risk zones (lahar paths, pyroclastic flow zones, flood areas)","Only affects farmers"],"Land-use planning."),
     ("The economic cost of natural disasters is highest in:",["Poor countries","*Wealthy countries (more infrastructure value at risk), but the HUMAN cost is highest in vulnerable nations with poor preparedness","Remote areas","Small countries"],"Economic vs. human cost."),
     ("Insurance plays a role in hazard management by:",["Preventing disasters","*Providing financial recovery after events and incentivizing risk reduction (lower premiums for safer buildings)","Stopping earthquakes","Only for governments"],"Insurance role."),
     ("Climate change may increase some geological hazards by:",["Reducing earthquakes","*Increasing sea level (amplifying tsunami damage), increasing glacial melt (triggering landslides), and changing precipitation patterns","Making volcanoes dormant","Strengthening buildings"],"Climate-hazard link."),
     ("The key lesson from all natural hazard case studies is:",["We can prevent all disasters","Nature is uncontrollable","*Preparation, building codes, warning systems, and education dramatically reduce casualties — we can't prevent hazards but can reduce risk","Nothing can be done"],"Overarching lesson.")]
)
lessons[k]=v

# ── Write ──
with open(PATH, "r", encoding="utf-8") as f:
    data = json.load(f)
data.update(lessons)
with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
print(f"✅ Integrated Science Unit 1: wrote {len(lessons)} lessons")
