import json, os

def q(num, text, correct, wrong1, wrong2, wrong3, explanation):
    return {
        "question_number": num,
        "question_text": text,
        "attempted": 2,
        "data_i18n": None,
        "options": [
            {"text": correct, "is_correct": True, "data_i18n": None},
            {"text": wrong1, "is_correct": False, "data_i18n": None},
            {"text": wrong2, "is_correct": False, "data_i18n": None},
            {"text": wrong3, "is_correct": False, "data_i18n": None}
        ],
        "explanation": explanation
    }

def write_quiz(unit, lesson, title, questions):
    path = f"content_data/AstronomyLessons/Unit{unit}/Lesson{lesson}_Quiz.json"
    data = {
        "unit": unit,
        "lesson_number": lesson,
        "title": title,
        "course": "Astronomy",
        "quiz_questions": questions
    }
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  Wrote {path} ({len(questions)} questions)")

print("=== Unit 5: Stars ===")

# 5.1 Properties of Stars
write_quiz(5, "5.1", "Properties of Stars (Temperature, Luminosity, Size)", [
    q(1, "What determines the color of a star?", "Its surface temperature", "Its distance from Earth", "Its age", "Its mass alone",
      "A star's surface temperature determines its color: hotter stars are blue-white, cooler stars are red."),
    q(2, "Which star color indicates the highest surface temperature?", "Blue", "Red", "Yellow", "Orange",
      "Blue stars have surface temperatures exceeding 25,000 K, making them the hottest by color."),
    q(3, "What is the most common way to measure a star's temperature?", "Analyzing its spectrum (spectral lines and color)", "Measuring its distance", "Counting its planets", "Weighing it",
      "Stellar spectra reveal temperature through spectral line patterns and the peak wavelength of emission."),
    q(4, "Luminosity measures:", "The total energy a star emits per second", "How bright a star appears from Earth", "A star's distance from us", "A star's chemical composition",
      "Luminosity is the intrinsic power output of a star, measured in watts or compared to the Sun's luminosity."),
    q(5, "A star's apparent magnitude depends on:", "Both its luminosity and its distance from Earth", "Only its luminosity", "Only its distance", "Only its temperature",
      "Apparent magnitude measures how bright a star appears, which depends on both intrinsic brightness and distance."),
    q(6, "Which property most determines a star's lifespan?", "Mass", "Color", "Distance from other stars", "Number of planets",
      "More massive stars burn fuel faster and live shorter lives; low-mass stars can shine for trillions of years."),
    q(7, "The Sun is classified as what type of star?", "G-type main sequence (yellow dwarf)", "Red giant", "Blue supergiant", "White dwarf",
      "The Sun is a G2V star — a yellow main-sequence star with a surface temperature of about 5,800 K."),
    q(8, "Stellar parallax is used to measure:", "Distance to nearby stars", "Temperature of stars", "Mass of stars", "Age of stars",
      "Parallax uses the apparent shift of a star against background stars as Earth orbits the Sun to calculate distance."),
    q(9, "The spectral classification sequence (OBAFGKM) is ordered by:", "Decreasing temperature", "Increasing distance", "Increasing mass", "Alphabetical order",
      "O stars are hottest (>30,000 K) and M stars are coolest (<3,500 K)."),
    q(10, "A star with a large radius and low temperature would be:", "Very luminous (a giant or supergiant)", "Very dim", "A white dwarf", "A neutron star",
      "By Stefan-Boltzmann law (L ∝ R²T⁴), a large radius can compensate for low temperature, yielding high luminosity."),
    # Vocabulary (11-20)
    q(11, "What is apparent magnitude?", "A measure of how bright a star appears from Earth", "A star's true brightness", "The size of a star", "The temperature of a star",
      "Apparent magnitude depends on both intrinsic luminosity and distance; lower numbers mean brighter objects."),
    q(12, "What is absolute magnitude?", "The brightness a star would have at a standard distance of 10 parsecs", "How bright a star looks from Earth", "The maximum brightness of a star", "The magnitude of a star's magnetic field",
      "Absolute magnitude standardizes brightness to 10 parsecs, allowing fair comparison of different stars."),
    q(13, "What is stellar parallax?", "The apparent shift in a star's position due to Earth's orbital motion", "A star's rotation", "A star's pulsation", "The bending of light by gravity",
      "Parallax angle decreases with distance; 1 arcsecond of parallax corresponds to a distance of 1 parsec."),
    q(14, "What is a parsec?", "A unit of distance equal to about 3.26 light-years", "A unit of time", "A unit of mass", "A unit of temperature",
      "One parsec is the distance at which a star has a parallax angle of one arcsecond (about 3.09 × 10¹³ km)."),
    q(15, "What is spectral classification?", "Categorizing stars by their spectral characteristics, primarily temperature", "Sorting stars by distance", "Ranking stars by mass", "Grouping stars by age",
      "The OBAFGKM classification (plus L, T, Y for cooler objects) organizes stars by temperature and spectral features."),
    q(16, "What is a light-year?", "The distance light travels in one year, about 9.46 × 10¹² km", "The time it takes light to travel one year", "A unit of brightness", "A measure of stellar age",
      "A light-year is a distance unit: approximately 9.46 trillion kilometers."),
    q(17, "What is luminosity class?", "A classification indicating a star's size and evolutionary stage (e.g., dwarf, giant, supergiant)", "A measure of apparent brightness", "The number of planets a star has", "A star's age group",
      "Luminosity classes range from I (supergiants) to V (main-sequence dwarfs), indicated by Roman numerals."),
    q(18, "What is the mass-luminosity relation?", "The relationship showing that more massive main-sequence stars are much more luminous", "The relationship between mass and color", "The law that all stars have the same mass", "A relation between mass and distance",
      "For main-sequence stars, L ∝ M^(3.5 to 4), meaning a star twice the Sun's mass is roughly 10-16 times more luminous."),
    q(19, "What is effective temperature?", "The temperature of a blackbody that would emit the same total radiation as the star", "The internal temperature of a star", "The average temperature of all stars", "Room temperature for astronomers",
      "Effective temperature characterizes a star's surface emission as if it were a perfect blackbody."),
    q(20, "What is proper motion?", "The apparent angular movement of a star across the sky over time", "A star's pulsation", "A planet's orbital motion", "The Sun's rotation",
      "Proper motion reflects a star's actual movement through space relative to the Sun, measured in arcseconds per year."),
    # Scenario (21-30)
    q(21, "Two stars have the same luminosity, but Star A appears 100 times brighter than Star B. What can you conclude?", "Star A is 10 times closer to Earth", "Star A is hotter", "Star B is larger", "Star A has more planets",
      "By the inverse square law, if apparent brightness differs by 100×, the distance ratio is √100 = 10."),
    q(22, "A star has a parallax angle of 0.1 arcseconds. What is its distance?", "10 parsecs", "1 parsec", "100 parsecs", "0.1 parsecs",
      "Distance in parsecs = 1/parallax in arcseconds = 1/0.1 = 10 parsecs."),
    q(23, "You observe two main-sequence stars: one is spectral type O and the other is type M. Which lives longer and why?", "The M star lives much longer because it consumes fuel slowly", "The O star lives longer because it has more fuel", "They live the same length of time", "Neither burns fuel",
      "M-type stars are low-mass and burn hydrogen slowly, lasting trillions of years; O-type stars exhaust fuel in millions of years."),
    q(24, "A star has the same temperature as the Sun but 100 times its luminosity. What can you determine about its size?", "It must have 10 times the Sun's radius", "It must be the same size", "It must be smaller", "It must be twice the radius",
      "Since L ∝ R²T⁴ and T is the same, 100L requires R² = 100, so R = 10R☉."),
    q(25, "An astronomer measures a star's spectrum and sees strong hydrogen absorption lines and a blue color. What spectral type is likely?", "B or A type", "M type", "K type", "G type",
      "Strong hydrogen lines and blue color are characteristic of B and A type stars (10,000-30,000 K)."),
    q(26, "If you could view the Sun from a planet 100 parsecs away, it would appear as a faint star. At 10 parsecs, its apparent magnitude equals its absolute magnitude (+4.83). At 100 parsecs, how would it appear?", "5 magnitudes fainter (about +9.83)", "The same brightness", "5 magnitudes brighter", "Invisible",
      "At 10× the distance, brightness drops by 100× = 5 magnitudes on the logarithmic magnitude scale."),
    q(27, "A star is observed to shift 0.5 arcseconds over 6 months. What is its distance in light-years?", "About 6.52 light-years (2 parsecs)", "1 light-year", "100 light-years", "0.5 light-years",
      "Parallax = 0.5\" means distance = 1/0.5 = 2 parsecs = 2 × 3.26 ≈ 6.52 light-years."),
    q(28, "A red star and a blue star have the same radius. Which emits more energy and by how much?", "The blue star emits far more — up to 10,000+ times more due to the T⁴ dependence", "The red star emits more", "They emit the same", "The blue star emits only twice as much",
      "With same radius, L ∝ T⁴. If the blue star is 3× hotter, it emits 3⁴ = 81 times more energy."),
    q(29, "You discover a star that is very luminous but has a cool (red) surface. Where would it fall on the H-R diagram?", "Upper right (red giant or supergiant region)", "Lower left", "Main sequence center", "Lower right",
      "High luminosity + low temperature places the star in the red giant/supergiant region (upper right of the H-R diagram)."),
    q(30, "A binary star system allows astronomers to directly measure stellar masses. How?", "By applying Kepler's third law to the orbital periods and separations", "By measuring their colors", "By counting their planets", "By measuring spectral lines alone",
      "In binary systems, the total mass is determined from the orbital period and semi-major axis using Kepler's modified third law.")
])

# 5.2 Hertzsprung-Russell Diagram
write_quiz(5, "5.2", "Hertzsprung-Russell Diagram", [
    q(1, "What does the H-R diagram plot?", "Luminosity vs. temperature (or spectral type)", "Mass vs. age", "Distance vs. brightness", "Size vs. color",
      "The H-R diagram plots stellar luminosity (vertical) against temperature or spectral type (horizontal, decreasing left to right)."),
    q(2, "Where are main-sequence stars located on the H-R diagram?", "Along a diagonal band from upper left to lower right", "In the upper right corner", "In the lower left corner only", "Scattered randomly",
      "Main-sequence stars form a continuous band from hot, luminous stars (upper left) to cool, dim stars (lower right)."),
    q(3, "Where do red giants appear on the H-R diagram?", "Upper right (high luminosity, low temperature)", "Lower left", "Center of the main sequence", "Lower right",
      "Red giants are luminous but cool, placing them in the upper-right region of the H-R diagram."),
    q(4, "Where do white dwarfs appear on the H-R diagram?", "Lower left (low luminosity, high temperature)", "Upper right", "Center of the main sequence", "Upper left",
      "White dwarfs are hot but very small, so they have low luminosity — placing them in the lower-left region."),
    q(5, "About what percentage of stars are on the main sequence?", "About 90%", "About 10%", "About 50%", "About 1%",
      "Roughly 90% of stars are hydrogen-fusing main-sequence stars at any given time."),
    q(6, "What determines where a star sits on the main sequence?", "Its mass", "Its age", "Its distance from Earth", "Its rotation speed",
      "On the main sequence, a star's position is determined primarily by its mass — more massive = hotter and more luminous."),
    q(7, "The hottest main-sequence stars are:", "O-type stars in the upper left", "M-type stars in the lower right", "G-type stars in the middle", "White dwarfs",
      "O-type stars are the most massive, hottest, and most luminous main-sequence stars, located in the upper left."),
    q(8, "When a Sun-like star leaves the main sequence, it becomes a:", "Red giant", "Blue supergiant", "White dwarf immediately", "Neutron star",
      "When the Sun exhausts core hydrogen, it will expand and cool to become a red giant."),
    q(9, "The instability strip on the H-R diagram contains:", "Pulsating variable stars like Cepheids", "Stable main-sequence stars", "White dwarfs only", "Black holes",
      "The instability strip is a region where stars pulsate due to ionization-driven opacity changes."),
    q(10, "Who independently developed the diagram?", "Ejnar Hertzsprung and Henry Norris Russell", "Galileo and Newton", "Einstein and Bohr", "Hubble and Kepler",
      "Danish astronomer Hertzsprung and American astronomer Russell independently created this foundational diagram around 1910."),
    # Vocabulary (11-20)
    q(11, "What is the main sequence?", "The band on the H-R diagram where stars fuse hydrogen in their cores", "A sequence of star names", "The order stars are born in", "A list of the brightest stars",
      "Main-sequence stars are in the hydrogen-burning phase of their lives, the longest stage of stellar evolution."),
    q(12, "What is the red giant branch?", "The region of the H-R diagram where evolved stars expand and cool after leaving the main sequence", "A tree branch painted red", "A type of red star cluster", "The path of a comet",
      "Stars ascend the red giant branch as their cores contract and outer layers expand after core hydrogen exhaustion."),
    q(13, "What is the horizontal branch?", "A region of the H-R diagram where stars burn helium in their cores", "A horizontal line of stars in the sky", "The main sequence rotated sideways", "A type of galaxy arm",
      "After the red giant phase, some stars settle on the horizontal branch, fusing helium into carbon."),
    q(14, "What is the instability strip?", "A region on the H-R diagram where stars pulsate in brightness", "An area with no stars", "Where unstable planets form", "A gapinthe main sequence",
      "Stars in the instability strip (including Cepheids and RR Lyrae) undergo periodic brightness variations."),
    q(15, "What is a Cepheid variable?", "A pulsating star whose period of brightness variation is related to its luminosity", "A star that never changes brightness", "A binary star", "A type of nebula",
      "Cepheids follow the period-luminosity relation, making them invaluable 'standard candles' for measuring cosmic distances."),
    q(16, "What is the white dwarf cooling sequence?", "The track on the H-R diagram where white dwarfs gradually cool and fade", "A sequence of newly formed stars", "A heating process in star cores", "A type of supernova aftermath",
      "White dwarfs slowly radiate their residual heat, gradually moving downward on the H-R diagram over billions of years."),
    q(17, "What is the turnoff point?", "The point on the main sequence where a star cluster's stars begin evolving off", "The end of a star's life", "When a telescope stops working", "The lowest temperature on the diagram",
      "The main-sequence turnoff indicates the age of a star cluster — brighter turnoff means younger cluster."),
    q(18, "What is the giant branch?", "The region of the H-R diagram occupied by red and orange giant stars", "A large tree branch", "The main sequence for giants", "A branch of the Milky Way",
      "The giant branch extends from the main sequence to the upper right, representing stars in advanced evolutionary stages."),
    q(19, "What is the asymptotic giant branch (AGB)?", "A late-stage evolutionary track for post-helium-burning stars, above the horizontal branch", "The initial giant phase", "A type of main-sequence star", "A measurement tool",
      "AGB stars are approaching the end of their lives, often shedding outer layers to form planetary nebulae."),
    q(20, "What is a color-magnitude diagram?", "An observational version of the H-R diagram using color index and apparent magnitude", "A diagram showing star colors only", "A paint color chart", "A diagram of planet colors",
      "Color-magnitude diagrams are the observational counterpart to H-R diagrams, using measurable quantities directly."),
    # Scenario (21-30)
    q(21, "A star cluster's H-R diagram shows the main sequence 'turning off' at spectral type A. What does this tell you about the cluster's age?", "It is relatively young (~1 billion years), since A-type stars have just evolved off", "It is very old", "It just formed", "Nothing about age",
      "The turnoff point indicates age: A-type turnoff means more massive/shorter-lived stars have evolved away, suggesting ~1 billion years."),
    q(22, "You plot a star that is both very hot and very dim on the H-R diagram. What type of star is it most likely?", "A white dwarf", "A red giant", "A main-sequence star", "A supergiant",
      "Hot + dim means high temperature but very small radius — characteristic of white dwarfs (lower-left of H-R diagram)."),
    q(23, "Two stars on the main sequence have the same temperature but different luminosities. Is this possible?", "No — on the main sequence, temperature uniquely determines luminosity", "Yes — this is common", "Only for binary stars", "Only for pulsating stars",
      "The main sequence is essentially a one-parameter family (mass), so each temperature corresponds to one luminosity."),
    q(24, "A Cepheid variable has a period of 10 days. How would you use this to estimate its distance?", "Use the period-luminosity relation to find its luminosity, then compare with apparent brightness", "Measure its temperature", "Count its pulsations per hour", "Simply multiply the period by speed of light",
      "The period-luminosity relation gives absolute luminosity from the period; comparing with apparent brightness yields distance."),
    q(25, "An H-R diagram of a globular cluster shows no main-sequence stars above the G-type region. What does this indicate?", "The cluster is old (~10+ billion years), and all more massive stars have evolved off the main sequence", "The cluster just formed", "It only has giant stars", "There are no stars in the cluster",
      "Old clusters have only low-mass stars remaining on the main sequence; all more massive stars have already evolved."),
    q(26, "A star moves from the main sequence to the red giant branch. What physical changes occur?", "Its core contracts, outer layers expand, surface cools, and luminosity increases", "It gets hotter and smaller", "Nothing changes", "It loses all its mass",
      "As core hydrogen exhausts, the core contracts (heating) while the envelope expands (cooling but increasing surface area and luminosity)."),
    q(27, "You observe a star that periodically brightens and dims every 5 days and falls in the instability strip. What is it?", "A Cepheid variable star", "An eclipsing binary", "A nova", "A main-sequence star",
      "Regular pulsation with a period of days and location in the instability strip identifies it as a Cepheid variable."),
    q(28, "An H-R diagram shows a gap in the horizontal branch of a specific cluster. What might this 'gap' indicate?", "A range of temperatures/luminosities where the evolutionary transition is rapid, so few stars are observed there", "Missing data", "A telescope error", "Black holes in the cluster",
      "Evolutionary gaps occur where stars transition quickly, spending little time at those positions so few are observed."),
    q(29, "If you plot all nearby stars on an H-R diagram, where would most stars be found?", "Lower main sequence (cool, dim red and orange dwarfs)", "Upper main sequence", "Red giant region", "White dwarf region",
      "Most stars in the solar neighborhood are low-mass M and K dwarfs on the lower main sequence."),
    q(30, "A star's position on the H-R diagram changes over time. What drives this evolution?", "Nuclear reactions depleting fuel and changing the star's internal structure", "Collisions with asteroids", "Distance changes from Earth", "Gravitational pull from other stars",
      "As stars burn through fuel, their internal structure changes, altering temperature and luminosity — tracing evolutionary tracks on the H-R diagram.")
])

# 5.3 Star Formation (Nebulae)
write_quiz(5, "5.3", "Star Formation (Nebulae)", [
    q(1, "Stars form from:", "Collapsing clouds of gas and dust (molecular clouds)", "The cores of existing stars", "Empty space", "Rocky asteroids",
      "Stars form when dense regions within molecular clouds collapse under gravity."),
    q(2, "What triggers the collapse of a molecular cloud?", "Shockwaves from supernovae, cloud collisions, or gravitational instability", "Sunlight", "Magnetic heating", "Dark energy",
      "External perturbations like supernova shockwaves or cloud collisions can compress regions enough to initiate collapse."),
    q(3, "What is a protostar?", "A collapsing cloud core that has not yet begun hydrogen fusion", "A fully formed star", "A dead star", "A planet forming around a star",
      "A protostar is heated by gravitational contraction but hasn't reached core temperatures needed for hydrogen fusion."),
    q(4, "As a molecular cloud collapses, its temperature:", "Increases due to gravitational compression", "Decreases", "Stays the same", "Fluctuates randomly",
      "Gravitational potential energy converts to thermal energy as the cloud contracts, raising its temperature."),
    q(5, "What is the Jeans mass?", "The minimum cloud mass needed for gravitational collapse to overcome thermal pressure", "The mass of a jean fabric", "The Sun's mass", "The mass of Jupiter",
      "The Jeans mass determines whether a cloud region is massive enough for gravity to win over pressure."),
    q(6, "A protostar becomes a main-sequence star when:", "Hydrogen fusion begins in its core", "It stops spinning", "It reaches maximum size", "It cools to room temperature",
      "A protostar joins the main sequence once core temperatures reach ~10 million K and sustained hydrogen fusion starts."),
    q(7, "T Tauri stars are:", "Young, pre-main-sequence stars with strong stellar winds and variability", "Old, dying stars", "White dwarfs", "Neutron stars",
      "T Tauri stars are solar-mass protostars approaching the main sequence, known for variability and strong outflows."),
    q(8, "Protoplanetary disks are:", "Disks of gas and dust around young stars where planets may form", "Galactic disks", "Saturn's rings", "Dark matter halos",
      "As a protostar forms, surrounding material flattens into a disk from which planets can eventually coalesce."),
    q(9, "The Orion Nebula is an example of:", "A star-forming region (emission nebula)", "A planetary nebula", "A supernova remnant", "A galaxy",
      "The Orion Nebula (M42) is one of the nearest and best-studied active star-forming regions."),
    q(10, "Molecular clouds are primarily composed of:", "Molecular hydrogen (H₂) and helium", "Iron", "Carbon dioxide", "Pure oxygen",
      "Molecular clouds are >70% H₂ by mass, with helium, dust, and trace molecules making up the rest."),
    # Vocabulary (11-20)
    q(11, "What is a molecular cloud?", "A large, cold, dense cloud of gas and dust in interstellar space where stars can form", "A cloud in Earth's atmosphere", "A galaxy-sized structure", "A type of nebula that never forms stars",
      "Molecular clouds (also called dark nebulae) have temperatures of 10-50 K and densities high enough for molecules to form."),
    q(12, "What is a protostar?", "An early stage of star formation before hydrogen fusion begins", "A fully mature star", "A star that has already died", "A type of planet",
      "Protostars glow from gravitational contraction energy, gradually heating until fusion ignites."),
    q(13, "What is the Jeans criterion?", "The condition for a gas cloud to gravitationally collapse based on mass, temperature, and density", "A clothing standard", "A criterion for star death", "A measure of stellar rotation",
      "When a cloud's mass exceeds the Jeans mass (or its size exceeds the Jeans length), collapse begins."),
    q(14, "What is an accretion disk?", "A rotating disk of material spiraling onto a central object", "A disk-shaped galaxy", "A planet's ring system", "A type of star cluster",
      "Accretion disks form around protostars (and other objects) as infalling material conserves angular momentum."),
    q(15, "What is a Herbig-Haro object?", "A bright patch of nebulosity associated with jets from a young star", "A type of asteroid", "A dark matter candidate", "An old supernova remnant",
      "Herbig-Haro objects are shockwaves created where jets from protostars collide with surrounding gas."),
    q(16, "What is fragmentation?", "The process by which a collapsing cloud breaks into smaller clumps, each potentially forming a star", "A star exploding", "Breaking of stellar wind", "The splitting of light in a prism",
      "Fragmentation explains why stars often form in clusters — a single large cloud can break into many stellar seeds."),
    q(17, "What is a bipolar outflow?", "Two oppositely directed jets of material from a forming star", "A magnetic pole on the Sun", "A binary star system", "A type of galaxy",
      "Protostars often produce bipolar jets along their rotation axis, driven by magnetic fields and accretion."),
    q(18, "What is a Bok globule?", "A small, dark, dense cloud that may be a site of star formation", "A type of star", "A bright emission nebula", "A planetary ring",
      "Bok globules are compact, opaque molecular clouds typically containing enough mass to form one or a few stars."),
    q(19, "What is the zero-age main sequence (ZAMS)?", "The position on the H-R diagram where a star first begins stable hydrogen fusion", "The end of a star's life", "The oldest possible age for a star", "A star with zero luminosity",
      "ZAMS marks the starting point of main-sequence evolution, when fusion first stabilizes and the star stops contracting."),
    q(20, "What is an emission nebula?", "A cloud of ionized gas that emits light due to energy from nearby hot stars", "A nebula that absorbs all light", "A dark cloud", "A galaxy's core",
      "Emission nebulae glow because UV radiation from hot young stars ionizes the gas, which then glows as electrons recombine."),
    # Scenario (21-30)
    q(21, "A supernova shockwave passes through a molecular cloud. What happens next?", "The compressed gas may trigger gravitational collapse and new star formation", "The cloud completely disperses", "Nothing happens", "The cloud turns into a planet",
      "Supernova shockwaves compress cloud material, potentially triggering collapse — this is called triggered star formation."),
    q(22, "An astronomer observes a dark, opaque patch in front of a bright nebula. What is it likely?", "A Bok globule or dense molecular cloud", "A black hole", "An empty region of space", "A planet passing in front",
      "Dark patches against bright backgrounds are typically dense molecular clouds (or Bok globules) that absorb background light."),
    q(23, "A protostar has been shrinking for 100,000 years but hasn't started fusion. What must happen for it to become a true star?", "Its core must reach approximately 10 million K for hydrogen fusion to begin", "It must collide with another star", "It must cool down", "It needs to absorb dark matter",
      "Hydrogen fusion requires core temperatures of ~10 million K; until then, the object is a protostar."),
    q(24, "Infrared telescopes are essential for studying star formation because:", "Infrared can penetrate the dust that hides protostars from visible light", "Protostars don't emit any radiation", "Visible light is absorbed by Earth's atmosphere", "Radio waves can't reach star-forming regions",
      "Dust in molecular clouds blocks visible light but is transparent to infrared, revealing embedded protostars."),
    q(25, "A forming star is surrounded by a disk of gas and dust. What might this disk eventually become?", "A planetary system", "Another star", "A black hole", "A neutron star",
      "Protoplanetary disks are the birthplaces of planets, moons, asteroids, and comets around new stars."),
    q(26, "Two jets of material shoot out from opposite sides of a young star. What causes this?", "Magnetic fields channel accreting material into bipolar jets along the rotation axis", "The star is exploding", "Gravity from nearby stars", "Solar wind from a neighboring star",
      "Magnetic fields in the accretion disk funnel some material into high-speed jets along the star's rotation axis."),
    q(27, "A molecular cloud fragment has less than the Jeans mass. What will happen?", "It will not collapse — thermal pressure prevents gravitational collapse", "It will explode", "It will form a black hole", "It will immediately start fusion",
      "Below the Jeans mass, thermal pressure exceeds gravitational force, preventing collapse."),
    q(28, "The Eagle Nebula's 'Pillars of Creation' are famous star-forming structures. Why are they pillar-shaped?", "Intense radiation from nearby hot stars is eroding the cloud, leaving denser columns intact", "Stars carved them out physically", "They formed from straight-line gravity", "They're reflections of light",
      "Photoevaporation by UV radiation from nearby O and B stars sculpts the pillars, with denser regions resisting erosion longer."),
    q(29, "If a collapsing cloud fragments into 100 pieces, what do you expect to form?", "A star cluster with roughly 100 stars", "One single massive star", "100 planets", "A galaxy",
      "Cloud fragmentation during collapse leads to the formation of stellar clusters with many stars born together."),
    q(30, "A brown dwarf forms from a collapsing cloud core but never achieves hydrogen fusion. What went wrong?", "Its mass was too low (below ~0.08 solar masses) to generate sufficient core pressure and temperature", "It spun too fast", "It was too hot", "It contained no hydrogen",
      "Below ~0.08 M☉, the core never reaches the 10 million K needed for sustained hydrogen fusion; the result is a brown dwarf.")
])

# 5.4 Main Sequence Stars
write_quiz(5, "5.4", "Main Sequence Stars", [
    q(1, "What defines a main-sequence star?", "It is fusing hydrogen into helium in its core", "It is collapsing from a cloud", "It has exhausted all its fuel", "It is a white dwarf",
      "Main-sequence stars are in the longest phase of stellar evolution, steadily converting hydrogen to helium in the core."),
    q(2, "How long will the Sun remain on the main sequence?", "About 10 billion years total", "About 1 million years", "About 100 billion years", "Forever",
      "The Sun has been on the main sequence for ~4.6 billion years and will remain for another ~5 billion years."),
    q(3, "On the main sequence, what maintains a star's stability?", "Hydrostatic equilibrium between gravity and radiation/gas pressure", "Magnetic fields", "Rotation", "External forces",
      "The balance between inward gravity and outward pressure from fusion keeps main-sequence stars stable."),
    q(4, "More massive main-sequence stars are:", "Hotter, more luminous, and shorter-lived", "Cooler, dimmer, and longer-lived", "The same as all other stars", "Only slightly different from low-mass stars",
      "High-mass stars have higher core temperatures, fuse hydrogen faster, and exhaust their fuel more quickly."),
    q(5, "An M-type main-sequence star (red dwarf) can live for:", "Trillions of years", "A few million years", "About 10 billion years", "Less than 1 billion years",
      "Red dwarfs are so efficient with fuel that they can shine for much longer than the current age of the universe."),
    q(6, "What percentage of stars in the Milky Way are red dwarfs?", "About 70-80%", "About 5%", "About 50%", "About 30%",
      "Red dwarfs (M-type) are by far the most common type of star, making up the vast majority of stellar populations."),
    q(7, "The mass range of main-sequence stars is approximately:", "0.08 to about 150-300 solar masses", "0.001 to 10 solar masses", "1 to 1,000 solar masses", "Exactly 1 solar mass",
      "Below 0.08 M☉ hydrogen fusion can't sustain itself (brown dwarfs); the upper limit is roughly 150-300 M☉ due to radiation pressure."),
    q(8, "As a main-sequence star ages, its core gradually:", "Accumulates helium and contracts slightly, causing the star to slowly brighten", "Gets cooler", "Stays exactly the same", "Fills with iron",
      "As hydrogen converts to helium, the core slowly contracts, heating up and increasing the fusion rate — making the star gradually brighter."),
    q(9, "Energy transport in a main-sequence star depends on:", "Its mass — low-mass stars have convective envelopes, high-mass stars have convective cores", "Only radiation", "Only convection", "Only conduction",
      "Low-mass stars have radiative cores and convective envelopes; high-mass stars have convective cores and radiative envelopes."),
    q(10, "The Sun's luminosity has increased since its formation by roughly:", "About 30%", "About 300%", "About 1%", "It hasn't changed at all",
      "The 'Faint Young Sun' was about 70% as luminous as today; it has gradually brightened over 4.6 billion years."),
    # Vocabulary (11-20)
    q(11, "What is hydrostatic equilibrium?", "The balance between the inward pull of gravity and outward pressure in a star", "A state of no motion", "A type of water balance", "A telescope alignment technique",
      "Hydrostatic equilibrium maintains the star's size: if gravity increases, pressure builds to push back, and vice versa."),
    q(12, "What is the proton-proton chain?", "The dominant nuclear fusion process in Sun-like and lower-mass main-sequence stars", "A chain of atoms in a crystal", "A type of chemical bond", "A method of measuring star distance",
      "The pp chain converts four hydrogen nuclei into one helium-4 nucleus, releasing energy in multiple steps."),
    q(13, "What is the CNO cycle?", "A catalytic fusion cycle dominant in main-sequence stars more massive than ~1.3 solar masses", "A cycle of chemical reactions in nebulae", "Carbon-Nitrogen-Oxygen gas emissions", "A type of stellar wind",
      "The CNO cycle uses carbon, nitrogen, and oxygen as catalysts to fuse hydrogen into helium at higher temperatures."),
    q(14, "What is a red dwarf?", "A small, cool, low-luminosity main-sequence star of spectral type M or late K", "A dying red giant", "A large, bright star", "A type of supernova",
      "Red dwarfs are the most common and longest-lived stars, with masses between 0.08 and ~0.6 solar masses."),
    q(15, "What is a blue main-sequence star?", "A hot, massive, luminous star of spectral type O or B on the main sequence", "A star that has turned blue from age", "A main-sequence star seen through a blue filter", "A cold star",
      "Blue main-sequence stars are the most massive and luminous but short-lived, burning through hydrogen rapidly."),
    q(16, "What is the mass-luminosity relation?", "L ∝ M^3.5 to M^4 for main-sequence stars — more massive stars are much more luminous", "A relation between mass and distance", "The ratio of stellar mass to planetary mass", "A gravity measurement",
      "This power-law relation shows that a small increase in mass leads to a dramatic increase in luminosity."),
    q(17, "What is the main-sequence lifetime?", "The duration a star spends fusing hydrogen in its core", "The time to form from a cloud", "The time to collapse into a white dwarf", "The age of the universe",
      "Main-sequence lifetime ∝ M/L ∝ M^(-2.5 to -3), so massive stars have short main-sequence lives."),
    q(18, "What is convective mixing?", "The process where convection transports material and energy within a star's interior", "Mixing stars in a cluster", "Shaking a telescope", "Blending light from different stars",
      "Convective mixing brings fresh hydrogen to burning regions and carries processed material outward."),
    q(19, "What is the Eddington luminosity limit?", "The maximum luminosity at which radiation pressure balances gravity, preventing the star from blowing apart", "The minimum luminosity of a star", "The brightness of the Sun", "A measurement technique",
      "Above the Eddington limit, radiation pressure exceeds gravity, driving powerful mass loss from the star's surface."),
    q(20, "What is metallicity?", "The abundance of elements heavier than helium in a star", "How metallic a star looks", "The iron content of asteroids only", "The magnetic field strength",
      "Metallicity (denoted Z or [Fe/H]) affects a star's opacity, evolution, and planet-forming potential."),
    # Scenario (21-30)
    q(21, "A main-sequence star has 10 solar masses. Estimate its main-sequence lifetime relative to the Sun's.", "About 1/1,000th of the Sun's — roughly 10 million years", "The same as the Sun", "10 times longer", "100 times longer",
      "Lifetime ∝ M/L ∝ M/M^3.5 = M^(-2.5). For 10M☉: (10)^(-2.5) ≈ 1/316, so roughly millions of years."),
    q(22, "A star on the lower main sequence is fully convective. What does this mean for its evolution?", "It can access all its hydrogen fuel, extending its main-sequence lifetime", "It will die faster", "It cannot fuse hydrogen", "It will become a blue giant",
      "Full convection mixes the entire star, allowing all hydrogen to be cycled through the core for fusion."),
    q(23, "You observe that a main-sequence star's luminosity is 10,000 times the Sun's. What can you estimate about its mass?", "About 20-30 solar masses", "About 2 solar masses", "About 0.5 solar masses", "About 100 solar masses",
      "Using L ∝ M^3.5: M ≈ (10,000)^(1/3.5) ≈ (10^4)^(0.286) ≈ 20+ solar masses."),
    q(24, "The Sun will eventually leave the main sequence. What triggers this departure?", "Exhaustion of hydrogen in the core, leading to core contraction and shell hydrogen burning", "A nearby supernova", "Collision with Jupiter", "Running out of helium",
      "When core hydrogen is depleted, fusion shifts to a shell around the core, and the star expands off the main sequence."),
    q(25, "A red dwarf's surface shows strong absorption lines from molecules like TiO. Why?", "It's cool enough (~3,000 K) for molecules to survive in its atmosphere", "It has a polluted atmosphere", "It's next to a molecular cloud", "It's very hot",
      "At the low surface temperatures of red dwarfs, molecules like titanium oxide can form and produce distinctive absorption bands."),
    q(26, "Two stars have equal mass but different metallicities. How might they differ on the main sequence?", "The higher-metallicity star is slightly cooler and more opaque, affecting its structure", "They would be identical", "The lower-metallicity star is dimmer", "Metallicity doesn't affect main-sequence stars",
      "Higher metallicity increases opacity, which changes energy transport, making the star slightly larger and cooler."),
    q(27, "Alpha Centauri A is very similar to the Sun. If it has 1.1 solar masses, is it more or less luminous?", "More luminous — about 1.5 times the Sun's luminosity due to the mass-luminosity relation", "Less luminous", "Exactly the same", "10 times more luminous",
      "L ∝ M^3.5: (1.1)^3.5 ≈ 1.4-1.5, so Alpha Centauri A is about 1.5 L☉."),
    q(28, "If the Sun's core suddenly became fully convective (mixing all hydrogen), how would its main-sequence lifetime change?", "It would increase significantly because all hydrogen would be available for fusion", "It would decrease", "No change", "The Sun would immediately explode",
      "Currently only the core's hydrogen is used for fusion; full convection would supply vastly more fuel, extending the lifetime."),
    q(29, "An astronomer discovers a main-sequence star with 0.08 solar masses. What makes this special?", "It's at the very bottom of the main sequence — barely massive enough for sustained hydrogen fusion", "It's the most massive star known", "It's a white dwarf", "It's about to explode",
      "0.08 M☉ is the hydrogen-burning limit; below this mass, the object would be a brown dwarf."),
    q(30, "A massive O-type star has strong stellar winds losing mass at 10⁻⁶ solar masses per year. How does this affect its evolution?", "Mass loss reduces its total mass significantly, altering its evolutionary track and final fate", "It has no effect", "The star gains mass", "Only its color changes",
      "Stellar wind mass loss in massive stars can remove substantial fractions of their mass, changing how they evolve and die.")
])

# 5.5 Red Giants & White Dwarfs
write_quiz(5, "5.5", "Red Giants & White Dwarfs", [
    q(1, "What causes a star to become a red giant?", "Core hydrogen exhaustion leads to expansion of the outer layers", "It absorbs a planet", "A collision with another star", "It's simply a large red star from birth",
      "When core hydrogen runs out, the core contracts and heats, causing the outer layers to expand and cool."),
    q(2, "A red giant's surface temperature is:", "Cooler than when it was on the main sequence", "Hotter than a blue star", "The same as the Sun", "Absolute zero",
      "Red giants have surface temperatures around 3,000-5,000 K, cooler than their main-sequence temperature."),
    q(3, "What holds up a white dwarf against gravity?", "Electron degeneracy pressure", "Nuclear fusion", "Magnetic fields", "Thermal pressure",
      "White dwarfs are supported by the quantum mechanical pressure of electrons that resist being compressed further."),
    q(4, "The maximum mass of a white dwarf is:", "About 1.4 solar masses (Chandrasekhar limit)", "About 10 solar masses", "About 0.1 solar masses", "There is no limit",
      "Above 1.4 M☉, electron degeneracy pressure can't support the star, leading to further collapse."),
    q(5, "A planetary nebula is:", "The ejected outer layers of a dying red giant star", "A nebula where planets form", "A nebula shaped like a planet", "A moon of Neptune",
      "Planetary nebulae are shells of gas expelled by low-mass stars during the asymptotic giant branch phase."),
    q(6, "The helium flash occurs when:", "Helium ignites suddenly in the degenerate core of a red giant", "Hydrogen first ignites", "A star explodes as a supernova", "A white dwarf cools down",
      "In low-mass stars, the degenerate core ignites helium fusion explosively (the helium flash), though it's contained internally."),
    q(7, "White dwarfs are composed primarily of:", "Carbon and oxygen", "Hydrogen and helium", "Iron and nickel", "Pure helium",
      "Most white dwarfs are the carbon-oxygen cores left after a low-mass star expels its outer layers."),
    q(8, "A typical white dwarf is roughly the size of:", "Earth", "The Sun", "Jupiter", "The Moon",
      "White dwarfs pack about a solar mass into a volume comparable to Earth's."),
    q(9, "Over time, white dwarfs:", "Slowly cool and fade, eventually becoming black dwarfs", "Heat up and reignite", "Expand into red giants again", "Gain mass from space",
      "With no energy source, white dwarfs radiate residual heat, cooling over billions to trillions of years."),
    q(10, "The Sun will eventually become:", "A white dwarf after passing through the red giant and planetary nebula phases", "A black hole", "A neutron star", "It will live forever",
      "As a low-mass star, the Sun will shed its outer layers and leave behind a white dwarf core."),
    # Vocabulary (11-20)
    q(11, "What is a red giant?", "An evolved star that has expanded and cooled after exhausting core hydrogen", "A large red planet", "A newly formed star", "A type of nebula",
      "Red giants have radii 10-100× the Sun's, with cool surfaces but high total luminosity."),
    q(12, "What is a white dwarf?", "The hot, dense remnant core of a low- to intermediate-mass star", "A small white star on the main sequence", "A cold, dead star", "A planet made of white rock",
      "White dwarfs are stellar remnants about Earth-sized with masses up to 1.4 M☉, slowly cooling over time."),
    q(13, "What is electron degeneracy pressure?", "Quantum mechanical pressure from electrons that prevents further gravitational collapse", "Pressure from electricity", "Gas pressure in the Sun", "Magnetic field pressure",
      "The Pauli exclusion principle prevents electrons from occupying the same quantum state, creating degeneracy pressure."),
    q(14, "What is the Chandrasekhar limit?", "The maximum mass (~1.4 M☉) of a white dwarf supported by electron degeneracy pressure", "The maximum mass of the Sun", "The minimum mass for star formation", "The maximum temperature of a star",
      "Subrahmanyan Chandrasekhar calculated that beyond ~1.4 M☉, electron degeneracy pressure fails."),
    q(15, "What is a planetary nebula?", "The ejected outer layers of an AGB star, illuminated by the hot core", "A nebula containing planets", "A ring system of a planet", "A cloud where only planets form",
      "Despite the confusing name, planetary nebulae have nothing to do with planets — they're ejected stellar envelopes."),
    q(16, "What is the helium flash?", "The sudden ignition of helium fusion in the electron-degenerate core of a low-mass red giant", "A bright flash from hydrogen fusion", "A lightning strike in space", "A camera flash for telescopes",
      "The helium flash lasts seconds and releases enormous energy, but is absorbed internally — it's not visible from outside."),
    q(17, "What is the asymptotic giant branch (AGB)?", "A late evolutionary stage where a star has double shell burning (H and He) and intense mass loss", "The first giant phase", "A type of main-sequence evolution", "A measurement technique",
      "AGB stars evolve through thermal pulses and heavy mass loss, eventually shedding their envelopes."),
    q(18, "What are thermal pulses?", "Periodic helium shell flashes in AGB stars that cause brightness variations", "Heartbeats of a star", "Temperature changes in Earth's atmosphere", "Pulses of radio energy",
      "Thermal pulses result from the cyclic ignition of the helium-burning shell in AGB stars."),
    q(19, "What is a black dwarf?", "A theoretical final state of a white dwarf that has cooled to emit no significant radiation", "A very dark star", "A small black hole", "A type of neutron star",
      "No black dwarfs exist yet — the universe isn't old enough for any white dwarf to have fully cooled."),
    q(20, "What is the red giant branch?", "The evolutionary track on the H-R diagram where stars ascend in luminosity after leaving the main sequence", "A physical branch on a red giant", "A type of galaxy arm", "A tree species on Mars",
      "Stars ascend the red giant branch as their cores contract and shells expand, moving up and right on the H-R diagram."),
    # Scenario (21-30)
    q(21, "A white dwarf in a binary system accretes matter from a companion star. What could happen?", "If it reaches the Chandrasekhar limit, it could explode as a Type Ia supernova", "Nothing", "It turns back into a main-sequence star", "It forms a new planet",
      "Type Ia supernovae occur when accreting white dwarfs reach ~1.4 M☉, triggering runaway carbon fusion."),
    q(22, "An astronomer sees a glowing shell of gas expanding away from a hot central star. What is this?", "A planetary nebula", "A supernova remnant", "A protostellar disk", "A galaxy halo",
      "The hot central star (future white dwarf) ionizes the expanding shell of gas it previously expelled."),
    q(23, "You measure a white dwarf's mass at 1.3 solar masses. Is this concerning?", "It's close to the Chandrasekhar limit — it must have a mechanism preventing further mass gain", "No, it's far from any limit", "It's impossible — white dwarfs can't be that massive", "It will become a red giant again",
      "At 1.3 M☉, the white dwarf is near the 1.4 M☉ limit; if it gains more mass (e.g., from a companion), it could explode."),
    q(24, "The Sun is expected to expand to roughly the orbit of Earth when it becomes a red giant. What happens to the inner planets?", "Mercury and Venus will be engulfed; Earth's fate is uncertain", "All planets survive", "Only Pluto is affected", "The Sun will shrink instead",
      "The Sun's red giant expansion will likely engulf Mercury and Venus; Earth may be engulfed or pushed outward."),
    q(25, "A white dwarf has a surface temperature of 100,000 K but is very dim. Explain this paradox.", "Despite being very hot, its tiny size (Earth-sized) gives it a very small surface area and thus low luminosity", "It's far away", "It's behind a dust cloud", "It's not really a star",
      "L = σAT⁴: even with extreme temperature, the tiny radius (~Earth-sized) means very low total luminosity."),
    q(26, "A binary system contains a red giant and a white dwarf. Material flows from the red giant to the white dwarf. What observable phenomenon might result?", "A nova — a thermonuclear explosion on the white dwarf's surface", "A solar eclipse", "A planetary transit", "Nothing observable",
      "Accreted hydrogen on the white dwarf's surface can ignite in a nova — a bright but non-destructive surface explosion."),
    q(27, "An astronomer dates a white dwarf's cooling age at 8 billion years. What can this tell us about the star's original life?", "Adding the main-sequence lifetime gives the total age, helping date the stellar population", "Nothing useful", "The star is still forming", "The white dwarf is too young to study",
      "White dwarf cooling ages + main-sequence lifetimes provide independent age estimates for stellar populations."),
    q(28, "During the helium flash in a red giant, enormous energy is released yet the star doesn't explode. Why?", "The energy is absorbed by the degenerate core, which then lifts degeneracy and expands, containing the explosion internally", "The star does explode", "No energy is released", "The star turns off",
      "The helium flash energy goes into lifting electron degeneracy; the core expands and cools, moderating the reaction."),
    q(29, "A ring-shaped planetary nebula is observed face-on. Another appears as an hourglass shape. Why do they look different?", "Different viewing angles and ejection geometries create varied apparent shapes", "They are completely different objects", "One is a supernova remnant", "Camera lens distortion",
      "Planetary nebulae have complex 3D shapes (often bipolar or toroidal); our viewing angle determines what we observe."),
    q(30, "The white dwarf Sirius B has a mass of about 1 M☉ but a radius similar to Earth's. What is its approximate density?", "About 1 million times denser than water (~10⁶ g/cm³)", "Same as water", "Same as the Sun", "Less than air",
      "Packing ~1 solar mass into an Earth-sized volume gives extraordinary density: a teaspoon would weigh tons.")
])

# 5.6 Supernovae & Neutron Stars
write_quiz(5, "5.6", "Supernovae & Neutron Stars", [
    q(1, "What is a supernova?", "A catastrophic explosion marking the death of a massive star or a white dwarf exceeding its mass limit", "A very bright main-sequence star", "A large sunspot", "A new star being born",
      "Supernovae can outshine entire galaxies for weeks, releasing enormous energy."),
    q(2, "A Type II supernova results from:", "The core collapse of a massive star that has exhausted its nuclear fuel", "A white dwarf explosion", "Two stars merging", "A regular stellar flare",
      "Type II supernovae are core-collapse events involving massive stars (>8 M☉) that can no longer sustain fusion."),
    q(3, "A Type Ia supernova results from:", "A white dwarf exceeding the Chandrasekhar limit through accretion", "Core collapse of a massive star", "A neutron star collision only", "A solar flare",
      "Type Ia supernovae occur when white dwarfs in binary systems gain enough mass to trigger runaway carbon fusion."),
    q(4, "What element's core signals the end of fusion in a massive star?", "Iron", "Hydrogen", "Helium", "Carbon",
      "Iron fusion absorbs energy instead of releasing it, so an iron core cannot support itself — triggering core collapse."),
    q(5, "A neutron star is:", "The collapsed remnant of a massive star's core, composed primarily of neutrons", "A star made of neutrons from the Big Bang", "A dying white dwarf", "A large asteroid",
      "Neutron stars have masses of 1.4-2.1 M☉ but radii of only ~10 km, with incredible density."),
    q(6, "A pulsar is:", "A rapidly rotating neutron star emitting beams of radiation", "A pulsating red giant", "A type of quasar", "A flashing white dwarf",
      "Pulsars emit beams of radiation from their magnetic poles; as the star rotates, these beams sweep across space like a lighthouse."),
    q(7, "Neutron stars are supported against gravity by:", "Neutron degeneracy pressure", "Electron degeneracy pressure", "Nuclear fusion", "Magnetic fields alone",
      "Similar to white dwarfs with electrons, neutron stars are supported by the quantum pressure of packed neutrons."),
    q(8, "The typical diameter of a neutron star is:", "About 20 km", "About 20,000 km", "About the size of the Sun", "About 1 km",
      "Neutron stars are incredibly compact — about 20 km across but with more mass than the Sun."),
    q(9, "Supernovae are important for the universe because they:", "Distribute heavy elements created by stellar nucleosynthesis into space", "Destroy all nearby matter permanently", "Create dark matter", "Have no lasting effect",
      "Supernovae scatter elements like carbon, oxygen, iron, and gold into the interstellar medium, enriching future star-forming clouds."),
    q(10, "SN 1987A was significant because:", "It was the closest observed supernova in modern times and the first from which neutrinos were detected", "It was the biggest explosion ever", "It destroyed a galaxy", "It was the first supernova ever seen",
      "SN 1987A in the Large Magellanic Cloud allowed direct neutrino detection, confirming core-collapse theory."),
    # Vocabulary (11-20)
    q(11, "What is a supernova remnant?", "The expanding cloud of gas and debris left after a supernova explosion", "A star that survived a supernova", "An unexploded star", "A type of nebula that has nothing to do with supernovae",
      "Supernova remnants like the Crab Nebula expand for thousands of years, enriching the interstellar medium."),
    q(12, "What is core collapse?", "The rapid gravitational collapse of a massive star's iron core when fusion ceases", "The slow cooling of the Sun", "A gradual process taking millions of years", "A collapse caused by external forces",
      "Core collapse happens in seconds when the iron core exceeds ~1.4 M☉ and electron degeneracy fails."),
    q(13, "What is a pulsar?", "A magnetized, rotating neutron star emitting beams of electromagnetic radiation", "A pulsating variable star", "A type of quasar", "A radio signal from aliens",
      "Pulsars were first discovered in 1967; their incredibly regular pulses initially puzzled astronomers."),
    q(14, "What is neutron degeneracy pressure?", "The quantum mechanical pressure of neutrons that supports neutron stars against gravity", "The pressure of neutrons in a laboratory", "Pressure inside the Sun", "A type of radiation pressure",
      "Like electron degeneracy in white dwarfs, neutron degeneracy arises from the Pauli exclusion principle applied to neutrons."),
    q(15, "What is the Tolman-Oppenheimer-Volkoff limit?", "The maximum mass of a neutron star (~2-3 M☉) beyond which it collapses into a black hole", "The maximum mass of a white dwarf", "The maximum temperature of a star", "The minimum mass for a star",
      "The TOV limit is the neutron star equivalent of the Chandrasekhar limit for white dwarfs."),
    q(16, "What is nucleosynthesis?", "The process of creating new atomic nuclei through nuclear reactions in stars", "Breaking apart atoms", "Chemical bonding", "Photosynthesis in stars",
      "Stellar nucleosynthesis creates elements up to iron through fusion; supernovae create heavier elements."),
    q(17, "What is a magnetar?", "A neutron star with an extremely powerful magnetic field (10⁹-10¹¹ tesla)", "A magnetic asteroid", "A type of compass", "A magnetic main-sequence star",
      "Magnetars have the strongest magnetic fields known, capable of producing intense bursts of X-rays and gamma rays."),
    q(18, "What is the r-process?", "Rapid neutron capture — a nucleosynthesis process creating heavy elements in supernovae and neutron star mergers", "A rapid rotation process", "A red giant process", "A type of radioactive decay",
      "The r-process produces about half of all elements heavier than iron, including gold, platinum, and uranium."),
    q(19, "What is a supernova light curve?", "A plot of a supernova's brightness over time", "The path light follows during an explosion", "A type of lens", "A trajectory of debris",
      "Light curves show the rise, peak, and decline of a supernova's brightness, revealing its type and energy."),
    q(20, "What is a neutron star merger?", "The collision and coalescence of two neutron stars, releasing gravitational waves and forming heavy elements", "A neutron star joining the main sequence", "Two stars fusing hydrogen", "A supernova explosion",
      "Neutron star mergers (kilonovae) were first observed via gravitational waves in 2017 (GW170817)."),
    # Scenario (21-30)
    q(21, "A massive star has built up an iron core. Why can't it continue fusing iron to get energy?", "Iron has the highest binding energy per nucleon — fusing it absorbs energy rather than releasing it", "Iron is too heavy to fuse", "Iron melts the star", "There isn't enough iron",
      "At the peak of the binding energy curve, no energy can be extracted from iron fusion — it's the end of the line."),
    q(22, "Astronomers detect regular radio pulses every 0.033 seconds from a source in the Crab Nebula. What is it?", "The Crab Pulsar — a rapidly rotating neutron star", "An alien signal", "A quasar", "A variable red giant",
      "The Crab Pulsar rotates ~30 times per second, producing millisecond-period pulses."),
    q(23, "LIGO detects gravitational waves from a compact binary merger. The signal is followed by a kilonova. What merged?", "Two neutron stars", "Two black holes", "A star and a planet", "Two white dwarfs",
      "Kilonovae follow neutron star mergers — the ejected material glows from radioactive decay of newly formed heavy elements."),
    q(24, "Type Ia supernovae are used as 'standard candles' for measuring cosmic distances. Why?", "They all reach nearly the same peak luminosity, so apparent brightness indicates distance", "They all look the same color", "They occur at regular intervals", "They're always the same distance away",
      "The consistent peak brightness of Type Ia supernovae allows astronomers to calculate distances using the inverse square law."),
    q(25, "A tablespoon of neutron star material would weigh about 1 billion tons on Earth. What does this extreme density tell us?", "Nuclear matter is incredibly dense — the neutrons are packed as tightly as an atomic nucleus", "The measurement must be wrong", "Earth's gravity is very strong", "Neutron stars are hollow inside",
      "Neutron star density (~10¹⁴ g/cm³) is similar to nuclear density — the entire star is like one giant nucleus."),
    q(26, "The Crab Nebula is the remnant of a supernova observed by Chinese astronomers in 1054 CE. What does it contain at its center?", "A pulsar (the Crab Pulsar)", "Nothing", "A black hole", "A white dwarf",
      "The Crab Pulsar energizes the surrounding nebula with its powerful magnetic field and relativistic particle wind."),
    q(27, "Gold and platinum exist on Earth. How were these elements created?", "Through r-process nucleosynthesis in supernovae and neutron star mergers before the solar system formed", "In the Sun's core", "By chemical reactions on Earth", "From meteorite impacts",
      "Elements heavier than iron require the extreme conditions of supernovae or neutron star mergers for their creation."),
    q(28, "A supernova explosion produces a burst of neutrinos before any visible light. Why?", "Neutrinos escape immediately from the collapsing core, while light is trapped until the shockwave reaches the surface", "Neutrinos are faster than light", "Light doesn't exist in supernovae", "Neutrinos are brighter than light",
      "During core collapse, neutrinos escape in seconds while the expanding shockwave takes hours to reach the surface."),
    q(29, "If a neutron star rotates faster over time (spins up), what might be causing this?", "Accretion of material from a companion star transferring angular momentum", "It's getting colder", "Gravity is increasing", "It's losing mass",
      "Matter spiraling onto a neutron star from a companion carries angular momentum, spinning it up to millisecond periods."),
    q(30, "An astronomer notices that a pulsar's period is gradually increasing. What is this called and what causes it?", "Spin-down — the pulsar loses rotational energy through magnetic braking and radiation", "Spin-up from accretion", "Time dilation", "Equipment error",
      "Isolated pulsars gradually slow as they radiate energy via their magnetic field (`pulsar braking`).")
])

# 5.7 Black Holes
write_quiz(5, "5.7", "Black Holes", [
    q(1, "A black hole is:", "A region of spacetime where gravity is so strong that nothing, not even light, can escape", "A hole in space", "A very dark star", "An empty region of space",
      "Black holes form when matter is compressed beyond a critical density, creating inescapable gravitational curvature."),
    q(2, "The event horizon of a black hole is:", "The boundary beyond which nothing can escape", "The surface of the black hole", "The center of the black hole", "The region where light is bent slightly",
      "The event horizon is not a physical surface but a boundary of no return — crossing it means no escape."),
    q(3, "A stellar-mass black hole forms from:", "The core collapse of a very massive star (typically >25 M☉)", "A dying white dwarf", "A large planet", "A red dwarf",
      "When a massive star's core exceeds the TOV limit, neutron degeneracy fails and the core collapses into a black hole."),
    q(4, "The Schwarzschild radius is:", "The radius of the event horizon for a non-rotating black hole", "The diameter of a black hole's accretion disk", "The distance from which a black hole can be seen", "The radius of the Sun",
      "R_s = 2GM/c²; for the Sun's mass, this would be about 3 km (but the Sun won't become a black hole)."),
    q(5, "Supermassive black holes are found:", "At the centers of most large galaxies", "Only in the Milky Way", "Randomly throughout galaxies", "Between galaxies",
      "Observations suggest that most large galaxies harbor supermassive black holes (millions to billions of solar masses) at their centers."),
    q(6, "How do astronomers detect black holes if they don't emit light?", "By observing their gravitational effects on nearby matter and the radiation from accretion disks", "They can't — black holes are undetectable", "By shining a flashlight into them", "By listening for sounds",
      "Matter spiraling into a black hole heats up and emits X-rays; orbiting stars also reveal the black hole's gravity."),
    q(7, "The first image of a black hole's shadow was captured by:", "The Event Horizon Telescope in 2019 (M87's black hole)", "Hubble Space Telescope", "James Webb Space Telescope", "A smartphone",
      "EHT used a global network of radio telescopes to image the supermassive black hole in galaxy M87."),
    q(8, "Sagittarius A* is:", "The supermassive black hole at the center of the Milky Way", "A constellation", "A type of radio antenna", "A white dwarf near the Sun",
      "Sgr A* has a mass of about 4 million solar masses and was imaged by the EHT in 2022."),
    q(9, "Hawking radiation is:", "Theoretical radiation emitted by black holes due to quantum effects near the event horizon", "Light escaping from inside a black hole", "Radiation from a star near a black hole", "A type of solar radiation",
      "Stephen Hawking proposed that quantum effects cause black holes to slowly emit radiation and eventually evaporate."),
    q(10, "If the Sun were replaced by a black hole of equal mass:", "Earth's orbit would not change, but it would be dark and cold", "Earth would be sucked in immediately", "Earth would fly away", "Nothing at all would change",
      "Gravity depends on mass and distance; at Earth's orbital distance, the gravitational force would be identical."),
    # Vocabulary (11-20)
    q(11, "What is the event horizon?", "The boundary of a black hole beyond which nothing can escape", "The horizon seen from the black hole", "The edge of the universe", "Where stars can be seen",
      "The event horizon defines the point of no return; outside it, escape is possible — inside, it is not."),
    q(12, "What is the singularity?", "The point at the center of a black hole where density is theoretically infinite", "The surface of a black hole", "The edge of a black hole", "A single star",
      "Classical general relativity predicts a singularity, but quantum gravity (not yet developed) may modify this picture."),
    q(13, "What is an accretion disk?", "A rotating disk of hot matter spiraling into a black hole (or other compact object)", "A type of frisbee in space", "A galaxy shaped like a disk", "A protoplanetary disk",
      "Accretion disks convert gravitational energy to thermal energy, making them among the most luminous objects in the universe."),
    q(14, "What is gravitational lensing?", "The bending of light by a massive object's gravitational field", "A lens made of gravity", "A type of telescope", "Light reflecting off a black hole",
      "Predicted by general relativity, gravitational lensing can magnify, distort, or multiply images of background objects."),
    q(15, "What is spaghettification?", "The stretching and compression of objects due to extreme tidal forces near a black hole", "Making pasta in space", "A type of supernova", "A telescopic distortion",
      "Near a black hole, the difference in gravitational pull between near and far sides stretches objects into thin strands."),
    q(16, "What is the Schwarzschild radius?", "The radius of the event horizon of a non-rotating, uncharged black hole: R_s = 2GM/c²", "The radius of any star", "Half the diameter of the Sun", "The distance to the nearest black hole",
      "For a 3 M☉ black hole, R_s ≈ 9 km; for a supermassive black hole of 4 million M☉, R_s ≈ 12 million km."),
    q(17, "What is a quasar?", "An extremely luminous active galactic nucleus powered by accretion onto a supermassive black hole", "A quasi-stellar object that is actually a star", "A type of pulsar", "A nearby galaxy",
      "Quasars can outshine their entire host galaxy, visible across billions of light-years."),
    q(18, "What is an active galactic nucleus (AGN)?", "A compact region at a galaxy's center with unusually high luminosity from accretion onto a supermassive black hole", "Any galaxy center", "A nuclear reactor in a galaxy", "The brightest star in a galaxy",
      "AGN encompass quasars, Seyfert galaxies, and blazars — all powered by supermassive black hole accretion."),
    q(19, "What is time dilation near a black hole?", "The slowing of time in stronger gravitational fields as predicted by general relativity", "Time speeding up near a black hole", "A movie effect", "Time stopping everywhere",
      "A clock near a black hole ticks more slowly relative to a distant observer — an effect of gravitational time dilation."),
    q(20, "What are gravitational waves?", "Ripples in spacetime caused by accelerating massive objects, especially merging compact objects", "Sound waves from black holes", "Light waves bent by gravity", "Electromagnetic radiation from stars",
      "First directly detected by LIGO in 2015 from merging black holes, confirming Einstein's 1916 prediction."),
    # Scenario (21-30)
    q(21, "Two black holes spiral together and merge. What do they produce?", "Gravitational waves and a larger black hole", "A supernova", "A neutron star", "A new galaxy",
      "Binary black hole mergers emit powerful gravitational waves while producing a single, more massive black hole."),
    q(22, "An astronomer observes a star orbiting an invisible massive object with a period of 16 years near the Milky Way's center. What is the object?", "Sagittarius A* — the Milky Way's supermassive black hole", "A planet", "A white dwarf", "A dark nebula",
      "The star S2 orbits Sgr A* with a 16-year period, providing one of the best measurements of the central black hole's mass."),
    q(23, "Light from a background galaxy appears as a ring around a massive foreground galaxy cluster. What causes this?", "Gravitational lensing — the cluster's mass bends and focuses the background light into an Einstein ring", "A supernova in the cluster", "A hole in the cluster", "Reflection off the cluster",
      "Einstein rings form when a massive object perfectly aligns between us and a background source, bending light into a ring."),
    q(24, "Cygnus X-1 is a powerful X-ray source in a binary system. What produces the X-rays?", "A stellar-mass black hole accreting material from its companion star", "Nuclear explosions", "Reflected sunlight", "A neutron star only",
      "Matter from the companion forms a superheated accretion disk around the black hole, radiating X-rays."),
    q(25, "If you could watch someone fall into a black hole from a safe distance, what would you see?", "They would appear to slow down and redden, and never quite cross the event horizon from your perspective", "They would disappear instantly", "They would speed up", "They would appear unchanged",
      "Gravitational time dilation means an external observer sees the infalling person slow down and redshift endlessly."),
    q(26, "A jet of material shoots from the poles of a supermassive black hole at near light speed. What are these jets called?", "Relativistic jets", "Solar flares", "Stellar winds", "Gamma-ray bursts only",
      "Relativistic jets are powered by the black hole's accretion disk and magnetic fields, extending millions of light-years."),
    q(27, "The mass of Sgr A* is approximately 4 million solar masses. What is its Schwarzschild radius in solar radii (1 R☉ ≈ 700,000 km)?", "About 17 solar radii (12 million km)", "About 1 solar radius", "About 1,000 solar radii", "About 1 million solar radii",
      "R_s = 2GM/c² ≈ 3 km × 4 × 10⁶ = 12 × 10⁶ km ≈ 17 R☉. The event horizon would fit within Mercury's orbit."),
    q(28, "If all black holes eventually evaporate through Hawking radiation, which evaporate faster — small or large ones?", "Small black holes evaporate faster — Hawking radiation temperature is inversely proportional to mass", "Large ones evaporate faster", "All at the same rate", "None evaporate",
      "Hawking temperature T ∝ 1/M: smaller black holes are hotter and radiate faster, evaporating in shorter timescales."),
    q(29, "A quasar at the edge of the observable universe is seen as it was billions of years ago. Why?", "Its light took billions of years to reach us, so we see it in the past", "We're looking through a time machine", "The quasar moved closer", "Telescopes can see the future",
      "The finite speed of light means distant objects appear as they were when the light was emitted — look-back time."),
    q(30, "The 'no-hair theorem' states that a black hole is completely described by just three properties. What are they?", "Mass, charge, and angular momentum (spin)", "Temperature, color, and size", "Age, distance, and brightness", "Mass, luminosity, and temperature",
      "Regardless of what formed it, a black hole retains only mass, charge, and spin — all other information is 'lost.'")
])

# 5.8 Case Studies in Stellar Observation
write_quiz(5, "5.8", "Case Studies in Stellar Observation", [
    q(1, "Betelgeuse is famous for:", "Being a red supergiant that may explode as a supernova relatively soon", "Being the closest star to Earth", "Being a white dwarf", "Being a neutron star",
      "Betelgeuse in Orion's shoulder is a massive red supergiant in the late stages of stellar evolution."),
    q(2, "The Hubble Space Telescope observed the Eagle Nebula's 'Pillars of Creation,' which are:", "Columns of gas and dust where new stars are forming", "Ancient alien structures", "Black holes", "Collapsed stars",
      "The iconic Pillars of Creation are dense columns of molecular gas in the Eagle Nebula's star-forming region."),
    q(3, "Eta Carinae is notable for:", "Being one of the most massive and luminous stars known, and for its 1840s Great Eruption", "Being the smallest known star", "Being a main-sequence star like the Sun", "Having the most planets",
      "Eta Carinae is a hypergiant with ~100-150 solar masses, prone to dramatic eruptions and likely to explode as a supernova."),
    q(4, "The first pulsar (CP 1919) was discovered in 1967 by:", "Jocelyn Bell Burnell and Antony Hewish", "Albert Einstein", "Isaac Newton", "Carl Sagan",
      "Bell Burnell discovered the regular radio pulses as a graduate student; the signal was initially nicknamed 'LGM-1' (Little Green Men)."),
    q(5, "The Gaia mission is mapping:", "The positions and motions of over a billion stars in the Milky Way", "The surface of Mars", "Gamma-ray bursts", "Dark matter directly",
      "ESA's Gaia is creating the most precise 3D map of the Milky Way, with parallaxes for over a billion stars."),
    q(6, "Sirius is the brightest star in the night sky because:", "It is both relatively luminous and very close (8.6 light-years)", "It is the most luminous star in the galaxy", "It is a red supergiant", "It is the closest star to Earth",
      "Sirius appears bright due to its combination of moderate luminosity (~25 L☉) and proximity."),
    q(7, "The TRAPPIST-1 system is remarkable because:", "Seven Earth-sized planets orbit a small red dwarf, several in the habitable zone", "It has the largest star known", "It contains a black hole", "It has no planets",
      "TRAPPIST-1 demonstrates that even small red dwarfs can host multiple potentially habitable planets."),
    q(8, "Supernova 1987A was located in:", "The Large Magellanic Cloud", "The Milky Way's center", "The Andromeda Galaxy", "Our solar system",
      "SN 1987A in the LMC (~168,000 light-years away) was the closest supernova observed since Kepler's in 1604."),
    q(9, "Wolf-Rayet stars are:", "Extremely hot, massive stars with strong stellar winds stripping away their outer layers", "Cool red dwarfs", "White dwarfs", "Planets",
      "Wolf-Rayet stars have surface temperatures >25,000 K and lose mass at extreme rates through powerful winds."),
    q(10, "The Kepler Space Telescope discovered thousands of:", "Exoplanets using the transit method", "New galaxies", "Black holes", "Supernovae",
      "Kepler revolutionized exoplanet science by detecting thousands of planets via tiny dips in stellar brightness."),
    # Vocabulary (11-20)
    q(11, "What is a red supergiant?", "A massive star that has expanded enormously in its late evolutionary stages", "A large red planet", "A type of red dwarf", "A newly formed star",
      "Red supergiants like Betelgeuse have radii hundreds of times the Sun's and are nearing the ends of their lives."),
    q(12, "What is spectroscopy?", "The study of light broken into its component wavelengths to determine composition, temperature, and motion", "Looking at light through colored glass", "A method of photographing stars", "A type of telescope",
      "Spectroscopy is fundamental to astrophysics, revealing chemical composition, temperature, density, and velocity of stars."),
    q(13, "What is a binary star system?", "Two stars orbiting their common center of mass", "Two stars that appear close but are unrelated", "A star with two planets", "A star that splits in two",
      "Many stars exist in binary or multiple systems; studying their orbits allows mass determination."),
    q(14, "What is the transit method?", "Detecting exoplanets by measuring the tiny dip in a star's brightness as a planet passes in front", "A method of space travel", "A telescope technique", "Measuring a star's mass",
      "The transit method has discovered the majority of known exoplanets, providing planetary radii and orbital periods."),
    q(15, "What is an eclipsing binary?", "A binary star system where one star periodically passes in front of the other as seen from Earth", "Two stars that eclipse the Sun", "A binary with no eclipses", "A single star that blinks",
      "Eclipsing binaries allow precise measurement of stellar radii, masses, and temperatures."),
    q(16, "What is a light curve?", "A graph showing the brightness of an object over time", "The path light follows in a curve", "A curved telescope mirror", "A type of lens",
      "Light curves reveal variability patterns: pulsation periods, eclipsing binary orbits, exoplanet transits, and supernova evolution."),
    q(17, "What is proper motion?", "The angular movement of a star across the sky over time relative to distant background stars", "A star's forward motion toward Earth", "Motion described by physics equations", "The correct way a star should move",
      "Proper motion is measured in arcseconds per year and indicates how a star physically moves through space."),
    q(18, "What is radial velocity?", "The component of a star's velocity along the line of sight, measured via Doppler shift", "The velocity of a star's radius", "The rotation speed of a star", "The speed of a radio wave",
      "Radial velocity is measured through blueshifts (approaching) or redshifts (receding) of spectral lines."),
    q(19, "What is a stellar wind?", "A flow of charged particles expelled from a star's upper atmosphere", "Literal wind on a star's surface", "A type of solar flare", "A breeze felt near a star",
      "All stars produce stellar winds; massive and evolved stars can lose significant mass through strong winds."),
    q(20, "What is astrometry?", "The precise measurement of star positions and motions", "The study of asteroids", "A type of astrology", "Predicting the future from stars",
      "Astrometry has been revolutionized by Gaia, providing positions accurate to microarcseconds for over a billion stars."),
    # Scenario (21-30)
    q(21, "Betelgeuse dimmed significantly in 2019-2020, leading to speculation about an imminent supernova. What was the likely cause?", "A large dust cloud ejected from the star partially blocked its light", "It was actually exploding", "A planet passed in front", "Instrument error",
      "The 'Great Dimming' was likely caused by a surface mass ejection creating a dust cloud that cooled and obscured part of the star."),
    q(22, "Gaia data shows a stream of stars with similar velocities moving through our region of the galaxy. What might this stream represent?", "The remnant of a disrupted dwarf galaxy or star cluster absorbed by the Milky Way", "Stars moving randomly", "A coincidence", "A telescope artifact",
      "Stellar streams are tidal debris from smaller galaxies or clusters torn apart by the Milky Way's gravity."),
    q(23, "A binary system shows periodic eclipses where brightness drops by different amounts at different times. What does the variation tell you?", "The two stars have different sizes and/or luminosities", "The telescope is broken", "One star is disappearing", "The stars are identical",
      "Different eclipse depths reveal which star is being eclipsed and the relative sizes and brightnesses of the components."),
    q(24, "An astronomer finds a star with a slight periodic wobble in its radial velocity. What is the most likely cause?", "An orbiting planet is gravitationally tugging on the star", "The star is pulsating", "Instrument noise", "The star is dying",
      "The radial velocity method detects exoplanets by measuring the star's reflex motion caused by the planet's gravity."),
    q(25, "The Crab Nebula is observed to be expanding. By measuring its expansion rate and size, what can astronomers determine?", "The time since the supernova explosion (confirmed as 1054 CE)", "The nebula's temperature", "The number of stars inside", "The distance to the nearest galaxy",
      "Tracing the expansion backwards gives the explosion date, consistent with the Chinese and other historical records."),
    q(26, "Kepler observed a star with irregular, deep dips in brightness (Tabby's Star/KIC 8462852). What was unusual about it?", "The dimming pattern was aperiodic and too deep for typical planetary transits", "It was a normal eclipsing binary", "It was a known pulsar", "It was a supernova",
      "Tabby's Star showed unusual dimming that is likely caused by dust, though it initially sparked exotic hypotheses."),
    q(27, "Eta Carinae's Great Eruption in the 1840s temporarily made it the second-brightest star in the sky. What happened?", "Massive amounts of material were ejected, creating the Homunculus Nebula we see today", "It became a supernova", "It was a meteor impact", "Light from another star was reflected",
      "Eta Carinae ejected about 10 solar masses of material during the Great Eruption, forming the bipolar Homunculus Nebula."),
    q(28, "Astronomers detect X-rays from a compact object in a binary system that flickers on timescales of milliseconds. What does this tell them?", "The emitting region must be very small, suggesting a neutron star or black hole", "The star is very large", "The X-rays are from the Sun", "The detector is malfunctioning",
      "Rapid variability implies a tiny emitting region — only compact objects (neutron stars or black holes) are small enough."),
    q(29, "JWST observes infrared light from one of the first stars in the universe, shifted from ultraviolet to infrared. What causes this shift?", "The expansion of the universe stretches (redshifts) the light over billions of years", "The star is cool", "A filter was used", "The star is nearby",
      "Cosmological redshift stretches light from the early universe; originally UV/visible light arrives as infrared."),
    q(30, "A survey reveals that most stars in the solar neighborhood are M-type dwarfs, yet the brightest naked-eye stars are mostly A, B, and K giants. Why the discrepancy?", "M dwarfs are intrinsically faint and hard to see with the naked eye, despite being the most numerous", "M dwarfs don't exist nearby", "Only bright stars are real", "There are few M dwarfs in the universe",
      "Observational bias: naked-eye visibility favors luminous stars, but volume-complete surveys reveal the true dominance of faint M dwarfs.")
])

print("\n=== Unit 5 Complete ===")
