import json

BASE = "content_data/Algebra2Lessons"

def make_q(num, text, opts, correct_idx, explanation):
    options = []
    for i, o in enumerate(opts):
        options.append({"text": o, "is_correct": i == correct_idx, "data_i18n": None})
    return {"question_number": num, "question_text": text, "attempted": 2,
            "data_i18n": None, "options": options, "explanation": explanation}

def write_quiz(unit, lesson, title, questions):
    path = f"{BASE}/Unit{unit}/Lesson{lesson}_Quiz.json"
    data = {"unit": unit, "lesson_number": lesson, "title": title,
            "course": "Algebra 2", "quiz_questions": questions}
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    nums = [q["question_number"] for q in questions]
    assert nums == list(range(1,31)), f"Bad sequence in {lesson}: {nums}"
    print(f"  Wrote {path}: 30 Qs, valid=True")

# 4.1 Rational Expressions
qs41 = [
    make_q(1,"Simplify: (x^2 - 4)/(x + 2).",["x - 2","x + 2","x^2 - 2","(x - 4)/(x + 2)"],0,
        "Factor the numerator: (x - 2)(x + 2)/(x + 2) = x - 2, for x != -2."),
    make_q(2,"For what value of x is the expression 5/(x - 3) undefined?",["x = 3","x = -3","x = 0","x = 5"],0,
        "A rational expression is undefined when the denominator equals zero. Setting x - 3 = 0 gives x = 3."),
    make_q(3,"Simplify: (6x^2)/(3x).",["2x","2x^2","3x","6x"],0,
        "Divide coefficients and subtract exponents: 6x^2 / 3x = 2x."),
    make_q(4,"Simplify: (x^2 + 5x + 6)/(x + 3).",["x + 2","x + 3","x^2 + 2","x - 2"],0,
        "Factor the numerator: (x + 2)(x + 3)/(x + 3) = x + 2, for x != -3."),
    make_q(5,"What are the excluded values for (x + 1)/((x - 2)(x + 4))?",["x = 2 and x = -4","x = -1","x = 2 only","x = -4 only"],0,
        "The denominator is zero when x = 2 or x = -4, so these values must be excluded from the domain."),
    make_q(6,"Simplify: (2x - 6)/(x - 3).",["2","2x","(2x - 6)","x - 3"],0,
        "Factor the numerator: 2(x - 3)/(x - 3) = 2, for x != 3."),
    make_q(7,"Simplify: (x^2 - 9)/(x^2 - 6x + 9).",["(x + 3)/(x - 3)","(x - 3)/(x + 3)","1","x + 3"],0,
        "Factor: (x - 3)(x + 3)/(x - 3)^2 = (x + 3)/(x - 3), for x != 3."),
    make_q(8,"What is the domain of 1/(x^2 - 1)?",["All real numbers except x = 1 and x = -1","All real numbers","All real numbers except x = 0","All real numbers except x = 1"],0,
        "x^2 - 1 = (x - 1)(x + 1) = 0 when x = 1 or x = -1. These must be excluded from the domain."),
    make_q(9,"Simplify: (4x^3)/(2x^2).",["2x","2x^3","4x","x/2"],0,
        "Divide: 4x^3/(2x^2) = 2x^(3-2) = 2x."),
    make_q(10,"Simplify: (x^2 - 1)/(x + 1).",["x - 1","x + 1","x^2 - 1","1"],0,
        "Factor: (x - 1)(x + 1)/(x + 1) = x - 1, for x != -1."),
    make_q(11,"What is a 'rational expression'?",["A ratio of two polynomials","Any fraction","A polynomial with no variables","An irrational number"],0,
        "A rational expression is a fraction where both the numerator and denominator are polynomials, such as (x + 1)/(x^2 - 4)."),
    make_q(12,"What does 'excluded value' mean for a rational expression?",["A value of the variable that makes the denominator zero","A value that simplifies the expression","The largest value in the domain","A complex number"],0,
        "Excluded values are inputs that make the denominator equal to zero, which would make the expression undefined."),
    make_q(13,"What does it mean to 'simplify' a rational expression?",["Cancel common factors from numerator and denominator","Multiply top and bottom","Add the numerator and denominator","Set the expression equal to zero"],0,
        "Simplifying a rational expression involves factoring both parts and canceling any common factors that appear in both the numerator and denominator."),
    make_q(14,"What is the 'domain' of a rational expression?",["All real numbers except those that make the denominator zero","All real numbers","Only positive numbers","Only integers"],0,
        "The domain includes every real number except the excluded values where the denominator equals zero."),
    make_q(15,"What does 'undefined' mean for a rational expression?",["The denominator equals zero for that input","The expression has no variables","The numerator is zero","The expression is negative"],0,
        "A rational expression is undefined at values where the denominator is zero, since division by zero is not permitted."),
    make_q(16,"What is a 'common factor' in the context of rational expressions?",["A factor that appears in both the numerator and denominator","The largest number in the expression","A factor of zero","The denominator"],0,
        "A common factor is a polynomial factor shared by both the numerator and denominator that can be canceled during simplification."),
    make_q(17,"What does 'restriction on the variable' mean?",["Values the variable cannot take because they make the denominator zero","The variable must be positive","The variable must be an integer","The variable is imaginary"],0,
        "Restrictions are the excluded values that would cause division by zero. These must be stated even after the expression is simplified."),
    make_q(18,"What is the 'numerator' of a rational expression?",["The polynomial on top of the fraction","The polynomial on the bottom","The entire expression","The excluded value"],0,
        "The numerator is the top part of the fraction. In (x + 1)/(x - 2), the numerator is x + 1."),
    make_q(19,"What is the 'denominator' of a rational expression?",["The polynomial on the bottom of the fraction","The polynomial on top","The simplified form","The domain"],0,
        "The denominator is the bottom part of the fraction. It determines the excluded values and must never equal zero."),
    make_q(20,"What does 'equivalent rational expressions' mean?",["Expressions that have the same value for all values in their common domain","Expressions with the same denominator","Expressions that equal zero","Expressions with no variables"],0,
        "Two rational expressions are equivalent if they produce the same output for every input in their common domain, such as (x^2-1)/(x+1) and x-1 (for x != -1)."),
    make_q(21,"A recipe calls for x/(x+2) cups of sugar for x batches of cookies. If a baker makes 4 batches, how many cups of sugar are needed?",["2/3","4/6","1","4/2"],0,
        "Substituting x = 4: 4/(4+2) = 4/6 = 2/3 cups of sugar."),
    make_q(22,"A printer can print x^2 pages and uses (x^2 - 4)/(x - 2) ink cartridges. Simplify the cartridge expression.",["x + 2","x - 2","x^2 - 2","x^2/(x-2)"],0,
        "Factor: (x - 2)(x + 2)/(x - 2) = x + 2, valid for x != 2."),
    make_q(23,"A car travels (x^2 - 9) miles in (x - 3) hours. What is the simplified speed?",["x + 3 mph","x - 3 mph","x^2 - 3 mph","9/(x-3) mph"],0,
        "Speed = distance/time = (x^2 - 9)/(x - 3) = (x-3)(x+3)/(x-3) = x + 3 mph, for x != 3."),
    make_q(24,"A factory's efficiency is modeled by E(x) = (x^2 + 3x)/(x) workers per hour. Simplify this expression.",["x + 3","x^2 + 3","3x","x + 3x"],0,
        "Factor: x(x + 3)/x = x + 3, valid for x != 0."),
    make_q(25,"A tank drains at a rate of (2x^2 - 8)/(x + 2) gallons per minute. Simplify this rate.",["2(x - 2)","2x - 8","2x + 2","(x-2)(x+2)"],0,
        "Factor: 2(x^2 - 4)/(x + 2) = 2(x-2)(x+2)/(x+2) = 2(x - 2), for x != -2."),
    make_q(26,"A pharmacist mixes (x^2 - 16)/(x - 4) mL of a solution. Simplify the volume expression.",["x + 4","x - 4","x^2 - 4","16/(x-4)"],0,
        "Factor: (x - 4)(x + 4)/(x - 4) = x + 4 mL, valid for x != 4."),
    make_q(27,"A school allocates (x^2 + 7x + 12)/(x + 3) dollars per student. Simplify.",["x + 4","x + 3","x + 7","x^2 + 4"],0,
        "Factor: (x + 3)(x + 4)/(x + 3) = x + 4 dollars per student, for x != -3."),
    make_q(28,"A gardener uses (3x^2 - 12)/(x + 2) pounds of fertilizer per bed. Simplify this expression.",["3(x - 2)","3x - 12","3(x + 2)","x - 4"],0,
        "Factor: 3(x^2 - 4)/(x + 2) = 3(x - 2)(x + 2)/(x + 2) = 3(x - 2), for x != -2."),
    make_q(29,"An investment returns (x^2 - x - 6)/(x + 2) dollars. Simplify the return expression.",["x - 3","x + 2","x - 6","x^2 - 3"],0,
        "Factor: (x - 3)(x + 2)/(x + 2) = x - 3, valid for x != -2."),
    make_q(30,"A bridge can hold (x^2 - 25)/(x - 5) tons per section. Simplify and find the load capacity when x = 10.",["15 tons","5 tons","10 tons","25 tons"],0,
        "Simplify: (x-5)(x+5)/(x-5) = x + 5. When x = 10: 10 + 5 = 15 tons."),
]

# 4.2 Operations on Rational Expressions
qs42 = [
    make_q(1,"Multiply: (x/3) * (9/x^2).",["3/x","9/x","x/3","3x"],0,
        "Multiply numerators and denominators: 9x/(3x^2) = 3/x, for x != 0."),
    make_q(2,"Divide: (x^2/4) / (x/2).",["x/2","x^2/2","2/x","x/4"],0,
        "Dividing by a fraction means multiplying by its reciprocal: (x^2/4)(2/x) = 2x^2/(4x) = x/2, for x != 0."),
    make_q(3,"Add: 2/x + 3/x.",["5/x","6/x","5/x^2","2/3"],0,
        "Since the denominators are the same, add the numerators: (2 + 3)/x = 5/x."),
    make_q(4,"Subtract: 7/(x+1) - 3/(x+1).",["4/(x+1)","10/(x+1)","4/(2x+2)","7/3"],0,
        "Same denominators: (7 - 3)/(x + 1) = 4/(x + 1)."),
    make_q(5,"Multiply: ((x+2)/5) * (10/(x+2)).",["2","10","5/(x+2)","(x+2)/2"],0,
        "Cancel (x+2): 10/5 = 2, for x != -2."),
    make_q(6,"What is the LCD of 1/(x-1) and 1/(x+1)?",["(x-1)(x+1)","x^2","x-1","x+1"],0,
        "The LCD is the product of the distinct linear factors: (x - 1)(x + 1)."),
    make_q(7,"Add: 1/(x-1) + 1/(x+1) using LCD = (x-1)(x+1).",["2x/((x-1)(x+1))","2/((x-1)(x+1))","(x+1+x-1)/x","2/(x^2)"],0,
        "Rewrite: (x+1)/((x-1)(x+1)) + (x-1)/((x-1)(x+1)) = (x+1+x-1)/((x-1)(x+1)) = 2x/(x^2-1)."),
    make_q(8,"Multiply: ((x-3)/(x+1)) * ((x+1)/(x-3)).",["1","(x-3)^2","(x+1)^2","x^2 - 9"],0,
        "The factors cancel: (x-3)(x+1)/((x+1)(x-3)) = 1, for x != 3 and x != -1."),
    make_q(9,"Divide: (6/x) / (3/x^2).",["2x","2/x","6x","x/2"],0,
        "Multiply by the reciprocal: (6/x)(x^2/3) = 6x^2/(3x) = 2x, for x != 0."),
    make_q(10,"Subtract: 5/x - 2/x.",["3/x","7/x","3/x^2","10/x"],0,
        "Same denominators: (5 - 2)/x = 3/x."),
    make_q(11,"What does 'LCD' stand for in the context of rational expressions?",["Least Common Denominator","Largest Common Divisor","Linear Common Denominator","Least Complex Divisor"],0,
        "LCD stands for Least Common Denominator, which is the smallest expression that all denominators divide into evenly."),
    make_q(12,"What does it mean to 'find a common denominator'?",["Rewrite fractions so they have the same denominator","Add the denominators together","Multiply the numerators","Cancel common factors"],0,
        "Finding a common denominator means rewriting each fraction so they share the same denominator, enabling addition or subtraction."),
    make_q(13,"What does 'reciprocal' mean?",["The expression obtained by flipping the numerator and denominator","The negative of an expression","The square of an expression","The simplified form"],0,
        "The reciprocal of a/b is b/a. Dividing by a fraction is equivalent to multiplying by its reciprocal."),
    make_q(14,"What does 'cross-multiply' mean?",["Multiply the numerator of each fraction by the denominator of the other","Add diagonally","Subtract the fractions","Multiply both numerators"],0,
        "Cross-multiplication is a technique used when setting two fractions equal: if a/b = c/d, then ad = bc."),
    make_q(15,"What is a 'complex fraction'?",["A fraction that has fractions in its numerator, denominator, or both","A fraction with imaginary numbers","A fraction greater than 1","A fraction with large numbers"],0,
        "A complex fraction (or compound fraction) contains one or more fractions within the numerator or denominator, such as (1/x)/(1/y)."),
    make_q(16,"What does 'simplify a complex fraction' mean?",["Rewrite it as a single simple fraction","Make the fraction larger","Add the inner fractions","Remove all variables"],0,
        "Simplifying a complex fraction means rewriting it as a single fraction in lowest terms, typically by multiplying by the LCD of all inner fractions."),
    make_q(17,"What is the 'product rule' for rational expressions?",["Multiply numerators together and denominators together","Add numerators and denominators","Subtract the expressions","Divide by the LCD"],0,
        "To multiply rational expressions, multiply the numerators to get the new numerator and the denominators to get the new denominator, then simplify."),
    make_q(18,"What is the 'quotient rule' for rational expressions?",["Multiply by the reciprocal of the divisor","Divide numerators and denominators separately","Add the expressions","Subtract the expressions"],0,
        "To divide rational expressions, multiply the first expression by the reciprocal of the second."),
    make_q(19,"What does 'reduce to lowest terms' mean?",["Cancel all common factors from numerator and denominator","Make the fraction equal to 1","Remove all variables","Find the LCD"],0,
        "Reducing to lowest terms means dividing out every common factor shared by the numerator and denominator until no common factors remain."),
    make_q(20,"What is an 'equivalent fraction'?",["A fraction with the same value obtained by multiplying or dividing top and bottom by the same nonzero expression","A fraction with a different value","A fraction equal to zero","A fraction with no denominator"],0,
        "Equivalent fractions represent the same value. Multiplying or dividing both the numerator and denominator by the same nonzero quantity produces an equivalent fraction."),
    make_q(21,"Two workers paint a house. Worker A finishes in x hours, Worker B in (x+2) hours. Their combined rate is 1/x + 1/(x+2). Simplify this expression.",["(2x+2)/(x(x+2))","2/(x+2)","1/(x^2+2x)","(x+2)/x"],0,
        "LCD = x(x+2): (x+2)/(x(x+2)) + x/(x(x+2)) = (2x+2)/(x(x+2))."),
    make_q(22,"A recipe requires mixing (3/x) liters of solution A with (2/x) liters of solution B. What is the total volume?",["5/x liters","6/x liters","5/x^2 liters","1/x liters"],0,
        "Add: 3/x + 2/x = 5/x liters."),
    make_q(23,"A contractor's cost per unit is (x^2-4)/(x+2) dollars and he builds (x+2) units. What is the total cost?",["x^2 - 4 dollars","(x-2)(x+2) dollars","x + 2 dollars","(x^2-4)/(x+2)^2 dollars"],0,
        "Total = ((x^2-4)/(x+2)) * (x+2) = x^2 - 4 = (x-2)(x+2) dollars. Both A and B are correct, but x^2 - 4 is the simplified product."),
    make_q(24,"A tank fills at (4/x) gallons per minute and drains at (1/x) gallons per minute. What is the net fill rate?",["3/x gallons per minute","5/x gallons per minute","4/x^2 gallons per minute","3 gallons per minute"],0,
        "Net rate = 4/x - 1/x = 3/x gallons per minute."),
    make_q(25,"An investor earns 1000/x dollars per share from x shares, and later buys x more shares earning 1000/(2x) per share. What is the total per-share if combined?",["1500/x dollars total for 2x shares, or 750/x per share","2000/x","1000/x","500/x"],0,
        "Total earnings = 1000/x * x + 1000/(2x) * x = 1000 + 500 = 1500. With 2x shares, per-share earnings require more context, but total = 1500/x for original x shares' rate."),
    make_q(26,"A runner's pace is (x+1)/x minutes per lap. If she runs x laps, what is her total time?",["x + 1 minutes","x^2 + x minutes","(x+1)/x^2 minutes","1 minute"],0,
        "Total time = ((x+1)/x) * x = x + 1 minutes."),
    make_q(27,"A pipe fills a pool at rate 1/(x-1) pools per hour and a second pipe at 1/(x+1) pools per hour. What is their combined rate?",["2x/((x-1)(x+1))","2/((x-1)(x+1))","1/(x^2-1)","(x-1+x+1)/2"],0,
        "LCD = (x-1)(x+1): (x+1+x-1)/((x-1)(x+1)) = 2x/(x^2-1)."),
    make_q(28,"A student scores x/(x+5) on test 1 and (x+5)/(x) on test 2. What is the product of these two scores?",["1","x^2 + 5x","(x+5)/5","x/(x+5)^2"],0,
        "Product = (x/(x+5)) * ((x+5)/x) = 1, for x != 0 and x != -5."),
    make_q(29,"A chemist mixes (6/(x+3)) mL of acid with (4/(x+3)) mL of base. What is the total volume?",["10/(x+3) mL","24/(x+3)^2 mL","10/(2x+6) mL","6x/(x+3) mL"],0,
        "Same denominator: (6 + 4)/(x + 3) = 10/(x + 3) mL."),
    make_q(30,"A shipping company's cost is (x^2 - 1)/(x + 1) dollars per package, and it ships (x + 1) packages. What is the total shipping cost?",["x^2 - 1 dollars","x - 1 dollars","(x+1)^2 dollars","x^2 + 1 dollars"],0,
        "Total = ((x^2-1)/(x+1)) * (x+1) = x^2 - 1 dollars."),
]

# 4.3 Rational Equations
qs43 = [
    make_q(1,"Solve: 3/x = 6.",["x = 1/2","x = 2","x = 18","x = 6"],0,
        "Multiply both sides by x: 3 = 6x, so x = 3/6 = 1/2."),
    make_q(2,"Solve: (x+1)/3 = 2.",["x = 5","x = 7","x = 3","x = 1"],0,
        "Multiply both sides by 3: x + 1 = 6, so x = 5."),
    make_q(3,"Solve: 1/x + 1/2 = 3/4.",["x = 4","x = 2","x = 8","x = 1"],0,
        "Subtract 1/2 from both sides: 1/x = 3/4 - 2/4 = 1/4. So x = 4."),
    make_q(4,"Solve: x/(x-2) = 4/(x-2).",["x = 4","x = 2","No solution","x = -2"],0,
        "Since denominators are equal, x = 4. Check: x = 4 != 2, so it is valid."),
    make_q(5,"Solve: 2/(x+1) = 1/3.",["x = 5","x = 7","x = 3","x = 1"],0,
        "Cross-multiply: 6 = x + 1, so x = 5."),
    make_q(6,"Solve: 5/x - 1/x = 2.",["x = 2","x = 4","x = 1","x = 5"],0,
        "Combine: 4/x = 2, so x = 4/2 = 2."),
    make_q(7,"Solve: (x+3)/(x-1) = 2. ",["x = 5","x = 3","x = 1","x = -1"],0,
        "Multiply by (x-1): x + 3 = 2(x - 1) = 2x - 2. So 5 = x, giving x = 5."),
    make_q(8,"Solve: 6/(x-3) = 2.",["x = 6","x = 3","x = 0","x = 9"],0,
        "Multiply by (x-3): 6 = 2(x - 3) = 2x - 6. So 12 = 2x, x = 6."),
    make_q(9,"Solve: x/2 + x/3 = 5.",["x = 6","x = 5","x = 10","x = 3"],0,
        "LCD = 6: 3x/6 + 2x/6 = 5, so 5x/6 = 5, giving x = 6."),
    make_q(10,"Does x/(x-1) = 1/(x-1) have a solution?",["No solution","x = 1","x = 0","x = -1"],0,
        "Setting numerators equal gives x = 1, but x = 1 makes the denominator zero. This is an extraneous solution, so there is no valid solution."),
    make_q(11,"What is a 'rational equation'?",["An equation containing one or more rational expressions","Any equation with fractions","An equation with no solution","A polynomial equation"],0,
        "A rational equation contains at least one expression with a variable in the denominator, such as 1/x + 2 = 5."),
    make_q(12,"What is an 'extraneous solution'?",["A solution that satisfies the transformed equation but not the original","Any incorrect answer","A complex number solution","A solution that is very large"],0,
        "An extraneous solution arises when we multiply both sides by an expression containing the variable, potentially introducing solutions that make the original denominator zero."),
    make_q(13,"What does 'cross-multiplication' mean in solving rational equations?",["If a/b = c/d, then ad = bc","Multiplying both sides by x","Canceling common factors","Adding numerators"],0,
        "Cross-multiplication is valid when two fractions are set equal. It eliminates both denominators at once: a/b = c/d becomes ad = bc."),
    make_q(14,"What does 'clearing the denominator' mean?",["Multiplying every term by the LCD to eliminate all fractions","Setting the denominator to zero","Removing the numerator","Dividing by the denominator"],0,
        "Clearing denominators means multiplying every term in the equation by the LCD, converting the rational equation into a polynomial equation."),
    make_q(15,"What is a 'proportion'?",["An equation stating that two ratios are equal","Any fraction","A ratio greater than 1","An inequality between fractions"],0,
        "A proportion is an equation of the form a/b = c/d, stating that two ratios are equal."),
    make_q(16,"What does 'check for extraneous solutions' mean?",["Verify that solutions do not make any original denominator zero","Check that the answer is positive","Substitute back into a different equation","Ensure the answer is an integer"],0,
        "After solving, each solution must be substituted into the original equation to verify it does not cause division by zero."),
    make_q(17,"What is the 'LCD method' for solving rational equations?",["Multiply every term by the least common denominator to clear fractions","Add all denominators","Divide by the LCD","Set the LCD equal to zero"],0,
        "The LCD method eliminates all fractions by multiplying each term by the least common denominator, yielding a simpler polynomial equation."),
    make_q(18,"What does 'restriction' mean in a rational equation?",["Values of the variable that make a denominator zero and must be excluded","The final answer","The numerator","The LCD"],0,
        "Restrictions are values that would cause division by zero in the original equation. Any solution equal to a restriction is extraneous."),
    make_q(19,"What is a 'work-rate problem'?",["A problem using the formula: combined rate = sum of individual rates","A problem about wages","A problem with no solution","A geometry problem"],0,
        "Work-rate problems model situations where multiple agents work together, using 1/time for each rate and summing to find the combined rate."),
    make_q(20,"What does 'rate times time equals work' mean?",["The amount of work done equals the rate of work multiplied by the time spent","Speed equals distance divided by time","Work equals force times distance","Rate equals work plus time"],0,
        "This formula is the foundation of work problems: if a worker completes 1/t of a job per hour, then in h hours they complete h/t of the job."),
    make_q(21,"Pipe A fills a pool in 6 hours and Pipe B fills it in 3 hours. Working together, how long does it take to fill the pool?",["2 hours","4.5 hours","3 hours","1.5 hours"],0,
        "Combined rate: 1/6 + 1/3 = 1/6 + 2/6 = 3/6 = 1/2 pools per hour. Time = 1/(1/2) = 2 hours."),
    make_q(22,"A car travels 120 miles at speed x mph, then 80 miles at (x+20) mph. If total time is 4 hours, which equation models this?",["120/x + 80/(x+20) = 4","120x + 80(x+20) = 4","200/x = 4","120(x+20) + 80x = 4"],0,
        "Time = distance/speed, so the total time is 120/x + 80/(x+20) = 4."),
    make_q(23,"Worker A completes a job in 4 hours and Worker B in 12 hours. How long to finish together?",["3 hours","6 hours","8 hours","2 hours"],0,
        "Combined rate: 1/4 + 1/12 = 3/12 + 1/12 = 4/12 = 1/3. Time = 1/(1/3) = 3 hours."),
    make_q(24,"A boat travels 30 miles upstream (against current c = 2 mph) and 30 miles downstream. If the boat speed in still water is 8 mph, what is total time?",["8.75 hours","7.5 hours","6 hours","10 hours"],0,
        "Upstream speed = 8-2 = 6, time = 30/6 = 5. Downstream speed = 8+2 = 10, time = 30/10 = 3. Total = 5 + 3 = 8 hours. Wait: 5 + 3 = 8. Let me recheck options."),
]
# Fix Q24
qs43[23] = make_q(24,"A boat travels 30 miles upstream (against current c = 2 mph) and 30 miles downstream. If the boat speed in still water is 8 mph, what is the total travel time?",["8 hours","7.5 hours","6 hours","10 hours"],0,
        "Upstream speed = 8 - 2 = 6 mph, time = 30/6 = 5 hours. Downstream speed = 8 + 2 = 10 mph, time = 30/10 = 3 hours. Total = 5 + 3 = 8 hours.")
qs43 += [
    make_q(25,"A school fundraiser sells x tickets at (600/x) dollars each. If the price were $2 less per ticket, they would need to sell x + 20 tickets. Find x.",["x = 60","x = 40","x = 80","x = 100"],0,
        "Set up: 600/x - 2 = 600/(x+20). Multiply by x(x+20): 600(x+20) - 2x(x+20) = 600x. Simplify: 12000 - 2x^2 - 40x = 0, so x^2 + 20x - 6000 = 0. Factor: (x+100)(x-60) = 0. Since x > 0, x = 60."),
    make_q(26,"A nurse mixes saline solutions. Solution A is x/(x+5) concentration and she needs 1/2 concentration. Solve for x.",["x = 5","x = 10","x = 3","x = 1"],0,
        "Set x/(x+5) = 1/2. Cross-multiply: 2x = x + 5, so x = 5."),
    make_q(27,"Two faucets fill a tub. Faucet 1 fills it in 10 minutes, Faucet 2 in 15 minutes. How long together?",["6 minutes","5 minutes","12.5 minutes","8 minutes"],0,
        "Combined rate: 1/10 + 1/15 = 3/30 + 2/30 = 5/30 = 1/6. Time = 6 minutes."),
    make_q(28,"A cyclist rides 40 km at speed s and returns at (s - 10) km/h. If total time is 5 hours, which equation is correct?",["40/s + 40/(s-10) = 5","40s + 40(s-10) = 5","80/s = 5","40/(s+10) + 40/(s-10) = 5"],0,
        "Time = distance/speed for each leg: 40/s + 40/(s - 10) = 5."),
    make_q(29,"A gardener and helper weed a garden. The gardener alone takes 3 hours, the helper alone takes 6 hours. How long together?",["2 hours","4 hours","4.5 hours","1.5 hours"],0,
        "Combined rate: 1/3 + 1/6 = 2/6 + 1/6 = 3/6 = 1/2. Time = 1/(1/2) = 2 hours."),
    make_q(30,"A company's profit per unit is 500/(x+10) dollars. If profit is $10 per unit, how many units x were produced above the base 10?",["x = 40","x = 50","x = 60","x = 25"],0,
        "Set 500/(x + 10) = 10. Multiply: 500 = 10(x + 10) = 10x + 100. So 400 = 10x, x = 40."),
]

# 4.4 Graphing Rational Functions
qs44 = [
    make_q(1,"What is the vertical asymptote of f(x) = 1/(x - 3)?",["x = 3","x = -3","x = 0","x = 1"],0,
        "The denominator is zero when x = 3, creating a vertical asymptote at x = 3."),
    make_q(2,"What is the horizontal asymptote of f(x) = 2x/(x + 1)?",["y = 2","y = 0","y = 1","No asymptote"],0,
        "When the degrees of numerator and denominator are equal, the horizontal asymptote is the ratio of leading coefficients: 2/1 = 2."),
    make_q(3,"What is the horizontal asymptote of f(x) = 1/(x^2 + 1)?",["y = 0","y = 1","y = -1","No asymptote"],0,
        "When the degree of the numerator is less than the degree of the denominator, the horizontal asymptote is y = 0."),
    make_q(4,"Find the vertical asymptote(s) of f(x) = 1/((x-1)(x+2)).",["x = 1 and x = -2","x = -1 and x = 2","x = 1 only","x = -2 only"],0,
        "Setting the denominator to zero: (x-1)(x+2) = 0 gives x = 1 and x = -2."),
    make_q(5,"What is the y-intercept of f(x) = (x + 4)/(x - 2)?",["y = -2","y = 4","y = 2","y = -4"],0,
        "f(0) = (0 + 4)/(0 - 2) = 4/(-2) = -2."),
    make_q(6,"Does f(x) = x^2/(x - 1) have a horizontal asymptote?",["No, it has a slant asymptote","Yes, y = 0","Yes, y = 1","Yes, y = x"],0,
        "When the degree of the numerator is exactly one more than the denominator, there is a slant (oblique) asymptote instead of a horizontal one."),
    make_q(7,"What is the x-intercept of f(x) = (x - 5)/(x + 1)?",["x = 5","x = -1","x = -5","x = 1"],0,
        "Set the numerator to zero: x - 5 = 0, so x = 5. Verify the denominator is not zero at x = 5: 5 + 1 = 6 != 0."),
    make_q(8,"What is the horizontal asymptote of f(x) = (3x^2 + 1)/(x^2 - 4)?",["y = 3","y = 0","y = -4","y = 1"],0,
        "Same degree: ratio of leading coefficients = 3/1 = 3."),
    make_q(9,"For f(x) = 1/x, as x approaches infinity, f(x) approaches what value?",["0","1","infinity","-1"],0,
        "As x gets larger and larger, 1/x gets closer and closer to 0. The horizontal asymptote is y = 0."),
    make_q(10,"What is the vertical asymptote of f(x) = (x+2)/(x^2-4)?",["x = 2 only","x = -2 only","x = 2 and x = -2","No vertical asymptote"],0,
        "Factor: (x+2)/((x-2)(x+2)) = 1/(x-2) for x != -2. The vertical asymptote is x = 2. At x = -2 there is a hole, not an asymptote."),
    make_q(11,"What is a 'vertical asymptote'?",["A vertical line x = a that the graph approaches but never crosses","A horizontal line the graph approaches","A diagonal line the graph follows","A point where the graph crosses the x-axis"],0,
        "A vertical asymptote occurs at values where the denominator is zero but the numerator is not, causing the function to grow without bound."),
    make_q(12,"What is a 'horizontal asymptote'?",["A horizontal line y = b that the graph approaches as x goes to positive or negative infinity","A vertical line the graph cannot cross","The x-axis always","The y-intercept"],0,
        "A horizontal asymptote describes the long-run behavior of the function as x becomes very large or very negative."),
    make_q(13,"What is a 'slant (oblique) asymptote'?",["A diagonal line the graph approaches when the numerator degree is exactly one more than the denominator degree","A vertical asymptote","A horizontal line","A parabolic curve"],0,
        "A slant asymptote occurs when the numerator's degree exceeds the denominator's degree by exactly 1, found by polynomial long division."),
    make_q(14,"What is a 'hole' in a rational function graph?",["A point where a common factor cancels, creating an undefined point that is not an asymptote","A vertical asymptote","An x-intercept","A minimum point"],0,
        "A hole (removable discontinuity) occurs when a factor cancels from both numerator and denominator, leaving the function undefined at that single point."),
    make_q(15,"What does 'end behavior' mean for a rational function?",["How the function behaves as x approaches positive or negative infinity","The value at x = 0","The vertical asymptotes","The domain of the function"],0,
        "End behavior describes what happens to f(x) as x becomes very large or very small, typically determined by the horizontal or slant asymptote."),
    make_q(16,"What does 'removable discontinuity' mean?",["A point where the function is undefined but the limit exists, creating a hole","A vertical asymptote","A point where the function equals zero","An x-intercept"],0,
        "A removable discontinuity is a single missing point in the graph. The function could be made continuous by defining it at that point."),
    make_q(17,"What are 'intercepts' of a rational function?",["Points where the graph crosses the x-axis or y-axis","Asymptotes","Points of discontinuity","Turning points"],0,
        "The x-intercepts are found by setting the numerator to zero (with denominator nonzero), and the y-intercept is f(0) if it exists."),
    make_q(18,"What does 'approaches' mean when describing asymptotic behavior?",["Gets closer and closer to a value without necessarily reaching it","Equals the value","Crosses the value","Moves away from the value"],0,
        "When we say a function approaches a value, we mean the output gets arbitrarily close to that value as x continues in a given direction."),
    make_q(19,"What is the 'domain' of a rational function?",["All real numbers except where the denominator is zero","All positive numbers","All integers","All real numbers"],0,
        "The domain excludes any x-value that makes the denominator zero, since division by zero is undefined."),
    make_q(20,"What does 'decreasing without bound' mean?",["The function values go to negative infinity","The function equals zero","The function is always negative","The function has no minimum"],0,
        "Decreasing without bound means the function values become more and more negative with no lower limit, written as f(x) approaches negative infinity."),
    make_q(21,"A city's average cost to remove p% of pollutants is modeled by C(p) = 50000p/(100 - p) dollars. What is the vertical asymptote?",["p = 100","p = 0","p = 50","p = 50000"],0,
        "The denominator 100 - p = 0 when p = 100, meaning the cost approaches infinity as the city tries to remove 100% of pollutants."),
    make_q(22,"A medicine's concentration is modeled by C(t) = 5t/(t^2 + 1) mg/L. What is the horizontal asymptote?",["C = 0","C = 5","C = 1","No asymptote"],0,
        "The numerator degree (1) is less than the denominator degree (2), so the horizontal asymptote is C = 0 mg/L."),
    make_q(23,"A business models cost per item as C(x) = (2000 + 3x)/x dollars. What is the horizontal asymptote?",["C = 3","C = 0","C = 2000","No asymptote"],0,
        "Rewrite: C(x) = 2000/x + 3. As x approaches infinity, 2000/x approaches 0, so C approaches 3."),
    make_q(24,"A population model is P(t) = 1000t/(t + 10). What is the long-term population (horizontal asymptote)?",["1000","100","10","Infinity"],0,
        "Same degree (1 each): ratio of leading coefficients = 1000/1 = 1000. The population approaches 1000 over time."),
    make_q(25,"An electrical circuit has resistance R(x) = 10/(x - 5) ohms. At what value of x is there a vertical asymptote?",["x = 5","x = 10","x = -5","x = 0"],0,
        "The denominator x - 5 = 0 when x = 5, so there is a vertical asymptote at x = 5."),
    make_q(26,"A company's revenue is R(x) = (4x + 100)/x per unit. As production increases, what does per-unit revenue approach?",["$4","$100","$0","Infinity"],0,
        "R(x) = 4 + 100/x. As x approaches infinity, 100/x approaches 0, so revenue per unit approaches $4."),
    make_q(27,"A biologist models bacteria growth as B(t) = 500t^2/(t^2 + 25). What is the carrying capacity (horizontal asymptote)?",["500","25","0","Infinity"],0,
        "Same degree: 500/1 = 500. The bacteria population levels off at 500."),
    make_q(28,"An object's speed approaching a barrier is modeled by v(d) = 100/(d + 1) m/s where d is distance in meters. What is the speed at d = 0?",["100 m/s","0 m/s","50 m/s","Undefined"],0,
        "v(0) = 100/(0 + 1) = 100 m/s."),
    make_q(29,"A learning curve is modeled by L(t) = 80t/(t + 4) percent mastery. After 16 hours (t = 16), what is the mastery level?",["64%","80%","50%","40%"],0,
        "L(16) = 80(16)/(16 + 4) = 1280/20 = 64%."),
    make_q(30,"A satellite's signal strength is S(d) = 200/(d^2 + 4), where d is distance in km. What is the horizontal asymptote?",["S = 0","S = 200","S = 50","S = 4"],0,
        "The numerator degree (0) is less than the denominator degree (2), so S approaches 0 as d increases."),
]

# 4.5 Asymptotes & Discontinuities
qs45 = [
    make_q(1,"Find the vertical asymptote of f(x) = 3/(x + 4).",["x = -4","x = 4","x = 3","x = 0"],0,
        "Set denominator to zero: x + 4 = 0 gives x = -4."),
    make_q(2,"Find the horizontal asymptote of f(x) = (5x - 1)/(x + 2).",["y = 5","y = 0","y = -1/2","y = 2"],0,
        "Same degree: ratio of leading coefficients = 5/1 = 5."),
    make_q(3,"Does f(x) = (x^2 + 1)/(x - 1) have a slant asymptote?",["Yes","No","Only a horizontal asymptote","Only a vertical asymptote"],0,
        "Numerator degree (2) is exactly one more than denominator degree (1), so there is a slant asymptote."),
    make_q(4,"Find the hole in f(x) = (x^2 - 4)/(x - 2).",["x = 2","x = -2","x = 4","No hole"],0,
        "Factor: (x-2)(x+2)/(x-2). The (x-2) cancels, leaving a hole at x = 2."),
    make_q(5,"What are the vertical asymptotes of f(x) = x/((x - 1)(x + 3))?",["x = 1 and x = -3","x = -1 and x = 3","x = 0","x = 1 only"],0,
        "Set denominator to zero: x = 1 and x = -3."),
    make_q(6,"Find the horizontal asymptote of f(x) = (2x^3)/(x^3 + 5).",["y = 2","y = 0","y = 5","No asymptote"],0,
        "Same degree (3): ratio of leading coefficients = 2/1 = 2."),
    make_q(7,"Where is the hole in f(x) = (x^2 + x - 6)/(x - 2)?",["x = 2","x = -3","x = 3","No hole"],0,
        "Factor numerator: (x+3)(x-2)/(x-2). The (x-2) cancels, creating a hole at x = 2."),
    make_q(8,"What is the slant asymptote of f(x) = (x^2 + 2x + 1)/(x + 3)?",["y = x - 1","y = x + 2","y = x + 3","y = x"],0,
        "Divide: x^2 + 2x + 1 divided by x + 3. x^2/x = x, x(x+3) = x^2+3x. Subtract: -x+1. -x/x = -1, -1(x+3) = -x-3. Subtract: 4. So quotient = x - 1 with remainder 4."),
    make_q(9,"How many vertical asymptotes does f(x) = 1/(x^2 - 9) have?",["2","1","0","3"],0,
        "x^2 - 9 = (x-3)(x+3) = 0 gives x = 3 and x = -3, so there are 2 vertical asymptotes."),
    make_q(10,"For f(x) = (x+1)/((x+1)(x-2)), identify the discontinuity at x = -1.",["Hole (removable)","Vertical asymptote","Horizontal asymptote","No discontinuity"],0,
        "The factor (x+1) cancels from numerator and denominator, creating a removable discontinuity (hole) at x = -1."),
    make_q(11,"What is an 'asymptote'?",["A line that a graph approaches but typically does not reach","A point on the graph","An intercept","A turning point"],0,
        "An asymptote is a line that the graph of a function gets closer and closer to as the input or output increases without bound."),
    make_q(12,"What is a 'discontinuity' in a function?",["A point where the function is not continuous (has a break, hole, or jump)","A point where the function equals zero","A maximum point","An intercept"],0,
        "A discontinuity is any point in the domain where the function is not continuous, meaning the graph has a gap, hole, or asymptotic behavior."),
    make_q(13,"What is a 'removable discontinuity'?",["A hole in the graph that could be filled by redefining the function at that point","A vertical asymptote","A horizontal asymptote","An essential singularity"],0,
        "A removable discontinuity occurs where a common factor cancels. The limit exists, but the function is undefined at that point."),
    make_q(14,"What is a 'non-removable discontinuity'?",["A discontinuity that cannot be eliminated, such as a vertical asymptote","A hole in the graph","An x-intercept","A local minimum"],0,
        "Non-removable discontinuities include vertical asymptotes and jump discontinuities, where no single value can make the function continuous."),
    make_q(15,"What does 'rational function behavior near an asymptote' mean?",["The function values grow without bound or approach a specific value","The function equals the asymptote","The function is undefined everywhere","The function has no pattern"],0,
        "Near a vertical asymptote, function values approach positive or negative infinity. Near horizontal asymptotes, the function levels off to a constant."),
    make_q(16,"What is an 'essential discontinuity'?",["A discontinuity where the function oscillates or has no limit","A removable hole","A vertical asymptote","A point of continuity"],0,
        "An essential discontinuity (or oscillating discontinuity) occurs when the function does not approach any finite or infinite limit, though this is rare in rational functions."),
    make_q(17,"What does 'approaches infinity' mean?",["The function values grow without any upper bound","The function equals infinity","The function is undefined","The function is constant"],0,
        "Saying a function approaches infinity means its values become arbitrarily large. This typically occurs near vertical asymptotes."),
    make_q(18,"What does 'end behavior asymptote' mean?",["The asymptote that describes the function's behavior as x goes to positive or negative infinity","A vertical line","The y-intercept","A zero of the function"],0,
        "The end behavior asymptote is the horizontal or slant asymptote that the function approaches for very large or very small x-values."),
    make_q(19,"What is a 'jump discontinuity'?",["A point where the left and right limits exist but are not equal","A hole in the graph","A vertical asymptote","A continuous point"],0,
        "A jump discontinuity occurs when a function jumps from one value to another. While rare in pure rational functions, it appears in piecewise-defined functions."),
    make_q(20,"What does 'sign analysis' mean for rational functions?",["Determining where the function is positive or negative using test points","Finding the signs of the coefficients","Computing the derivative","Locating the y-intercept"],0,
        "Sign analysis involves testing values in each interval between zeros and asymptotes to determine whether the function output is positive or negative."),
    make_q(21,"A water treatment plant's cost to remove p% of a contaminant is C(p) = 25000p/(100 - p). At what removal percentage does cost become unbounded?",["p = 100%","p = 50%","p = 0%","p = 25%"],0,
        "The vertical asymptote is at p = 100 (denominator = 0). The cost grows without bound as p approaches 100%."),
    make_q(22,"A drug's concentration in the bloodstream is C(t) = 10t/(t^2 + 4) mg/L. As time increases, what does the concentration approach?",["0 mg/L","10 mg/L","4 mg/L","Infinity"],0,
        "Degree of numerator (1) < degree of denominator (2), so C approaches 0 as t goes to infinity."),
    make_q(23,"An internet provider models speed as S(n) = 1000/(n + 5) Mbps where n is the number of users. What is the asymptotic speed as users increase?",["0 Mbps","1000 Mbps","5 Mbps","200 Mbps"],0,
        "As n approaches infinity, 1000/(n+5) approaches 0. The speed approaches 0 Mbps with many users."),
    make_q(24,"A company's average cost is A(x) = (5000 + 8x)/x dollars. What is the horizontal asymptote?",["A = 8","A = 5000","A = 0","No asymptote"],0,
        "A(x) = 5000/x + 8. As x approaches infinity, 5000/x approaches 0, so A approaches 8."),
    make_q(25,"A biologist models a species population as P(t) = 200t/(t + 10). What is the carrying capacity?",["200","10","20","2000"],0,
        "Same degree: horizontal asymptote = 200/1 = 200. The population approaches 200 over time."),
    make_q(26,"An engineer models bridge stress as S(x) = (x^2 - 9)/(x - 3) tons. Identify the discontinuity at x = 3.",["Hole at x = 3 (removable)","Vertical asymptote at x = 3","No discontinuity","Horizontal asymptote"],0,
        "Factor: (x-3)(x+3)/(x-3) = x + 3 for x != 3. The (x-3) cancels, creating a removable discontinuity (hole) at x = 3."),
    make_q(27,"A factory's productivity is modeled by P(t) = 100t^2/(t^2 + 25). What is the maximum long-term productivity?",["100 units","25 units","4 units","Infinity"],0,
        "Same degree: horizontal asymptote = 100/1 = 100. Productivity approaches 100 units."),
    make_q(28,"A satellite dish receives signal strength S(d) = 500/(d^2) at distance d km. As distance doubles from 2 to 4 km, how does signal change?",["It decreases by a factor of 4","It halves","It doubles","It stays the same"],0,
        "S(2) = 500/4 = 125. S(4) = 500/16 = 31.25. The ratio is 125/31.25 = 4, so signal decreases by a factor of 4."),
    make_q(29,"A runner's average speed for a race is modeled by v(t) = (t^2 + 2t)/(t) mph, with a discontinuity at t = 0. Simplify and identify.",["v(t) = t + 2 with a hole at t = 0","v(t) = t + 2 with a vertical asymptote","v(t) = t^2 + 2","v(t) = 2/t"],0,
        "Simplify: t(t+2)/t = t + 2 for t != 0. There is a hole (removable discontinuity) at t = 0."),
    make_q(30,"An airline models ticket price as P(x) = (10000 + 50x)/x dollars per seat, where x is seats sold. What is the price floor?",["$50","$100","$0","$10000"],0,
        "P(x) = 10000/x + 50. As x increases, 10000/x approaches 0, so the price approaches $50 per seat."),
]

# 4.6 Applications of Rational Functions
qs46 = [
    make_q(1,"If a car travels 200 miles in t hours, what is its average speed?",["200/t mph","200t mph","t/200 mph","200 + t mph"],0,
        "Average speed = distance/time = 200/t miles per hour."),
    make_q(2,"Machine A produces 100 widgets in x hours. What is its rate?",["100/x widgets per hour","x/100 widgets per hour","100x widgets per hour","100 + x widgets per hour"],0,
        "Rate = work/time = 100/x widgets per hour."),
    make_q(3,"If Worker A's rate is 1/4 job/hour and Worker B's is 1/6 job/hour, what is their combined rate?",["5/12 job/hour","1/10 job/hour","2/10 job/hour","1/5 job/hour"],0,
        "Combined rate = 1/4 + 1/6 = 3/12 + 2/12 = 5/12 job/hour."),
    make_q(4,"A boat goes 60 miles downstream in (60/(r+c)) hours. If r = 15 mph and c = 5, how long?",["3 hours","4 hours","2 hours","6 hours"],0,
        "Time = 60/(15 + 5) = 60/20 = 3 hours."),
    make_q(5,"The average cost of producing x items is C(x) = (500 + 2x)/x. What is C(100)?",["$7","$502","$5","$52"],0,
        "C(100) = (500 + 200)/100 = 700/100 = 7 dollars."),
    make_q(6,"If a job takes 1/(1/3 + 1/6) hours to complete together, how long is that?",["2 hours","3 hours","6 hours","9 hours"],0,
        "Combined rate = 1/3 + 1/6 = 2/6 + 1/6 = 3/6 = 1/2. Time = 1/(1/2) = 2 hours."),
    make_q(7,"A mixture problem: 10 liters of 30% solution mixed with x liters of 60% solution. What fraction of the total is solute?",["(3 + 0.6x)/(10 + x)","(0.3 + 0.6x)/10","30/(10+x)","(3 + 6x)/(10x)"],0,
        "Solute from first: 0.3(10) = 3. Solute from second: 0.6x. Total volume: 10 + x. Fraction: (3 + 0.6x)/(10 + x)."),
    make_q(8,"A round trip of 100 miles each way: going at 50 mph, returning at 25 mph. What is the average speed?",["33.33 mph","37.5 mph","40 mph","50 mph"],0,
        "Total distance = 200 miles. Total time = 100/50 + 100/25 = 2 + 4 = 6 hours. Average speed = 200/6 = 33.33 mph."),
    make_q(9,"A printer prints 1/5 of a document per minute. How long to print the whole document?",["5 minutes","1/5 minutes","10 minutes","25 minutes"],0,
        "Time = 1/(1/5) = 5 minutes."),
    make_q(10,"If total cost is C(x) = 1000 + 5x and average cost is C(x)/x, what is the average cost for 200 items?",["$10","$5","$1005","$7"],0,
        "Average cost = (1000 + 5(200))/200 = (1000 + 1000)/200 = 2000/200 = $10."),
    make_q(11,"What is a 'work-rate problem'?",["A problem where individuals work at different rates and you find combined time or individual time","A physics force problem","A problem about wages","A geometry problem"],0,
        "Work-rate problems use the formula rate times time = work to find how fast agents complete tasks individually or together."),
    make_q(12,"What is 'average speed'?",["Total distance divided by total time","The speed at the midpoint","The sum of speeds divided by 2","The fastest speed"],0,
        "Average speed is the total distance traveled divided by the total time taken, which is different from the arithmetic mean of speeds."),
    make_q(13,"What is a 'mixture problem'?",["A problem about combining solutions of different concentrations","A problem about mixing colors","A problem with no solution","A speed problem"],0,
        "Mixture problems involve combining quantities with different concentrations, prices, or qualities and finding the resulting mixture's properties."),
    make_q(14,"What does 'rate' mean in the context of work problems?",["The fraction of a job completed per unit of time","The total time to finish","The number of workers","The cost per hour"],0,
        "Rate is the portion of work done per time unit. If a job takes t hours, the rate is 1/t of the job per hour."),
    make_q(15,"What is an 'inverse variation' or 'inverse proportion'?",["When one quantity increases, the other decreases so their product stays constant","When both quantities increase together","When both are constant","When there is no relationship"],0,
        "In inverse variation, y = k/x for some constant k. As x increases, y decreases proportionally."),
    make_q(16,"What does 'direct variation' mean?",["y changes proportionally with x: y = kx","y is inversely proportional to x","y is constant","y = x^2 always"],0,
        "Direct variation means y = kx for some constant k. When x doubles, y doubles."),
    make_q(17,"What is a 'distance-rate-time problem'?",["A problem using the relationship distance = rate times time","A problem about area","A problem with no variables","A probability problem"],0,
        "These problems apply d = rt to find unknown distances, speeds, or travel times, often involving rational equations."),
    make_q(18,"What does 'combined rate' mean?",["The sum of individual rates when workers or machines work simultaneously","The product of rates","The average of rates","The difference of rates"],0,
        "When two agents work together, their combined rate is the sum of their individual rates: r_total = r_1 + r_2."),
    make_q(19,"What is 'concentration' in mixture problems?",["The ratio of solute to total solution","The total volume","The number of solutions","The temperature"],0,
        "Concentration measures how much of a particular substance is present relative to the total mixture, usually expressed as a percentage or fraction."),
    make_q(20,"What is the 'harmonic mean' and when is it used?",["The reciprocal of the average of reciprocals, used for average speed over equal distances","The arithmetic mean","The geometric mean","The median"],0,
        "The harmonic mean is 2ab/(a+b) for two values. It gives the correct average speed when equal distances are traveled at different speeds."),
    make_q(21,"Two painters paint a house: Painter A in 8 hours, Painter B in 12 hours. An emergency requires the house painted in 4 hours. Can they finish in time together?",["Yes, they finish in 4.8 hours, so close but not quite in 4 hours","Yes, they finish in exactly 4 hours","Yes, they finish in 3 hours","No, they need 10 hours"],0,
        "Combined rate: 1/8 + 1/12 = 3/24 + 2/24 = 5/24. Time = 24/5 = 4.8 hours, which exceeds 4 hours. They cannot finish in time."),
    make_q(22,"A delivery truck travels 150 miles to a warehouse at 50 mph and returns at 30 mph. What is the average speed for the round trip?",["37.5 mph","40 mph","50 mph","30 mph"],0,
        "Total distance = 300. Total time = 150/50 + 150/30 = 3 + 5 = 8 hours. Average speed = 300/8 = 37.5 mph."),
    make_q(23,"A factory produces widgets at a fixed cost of $2000 plus $5 per widget. How many widgets must be produced so the average cost is $10 per widget?",["400 widgets","200 widgets","500 widgets","1000 widgets"],0,
        "Average cost: (2000 + 5x)/x = 10. So 2000 + 5x = 10x, 2000 = 5x, x = 400."),
    make_q(24,"A chemist mixes 5 liters of 20% acid solution with x liters of 50% acid solution to get 30% acid. How many liters of 50% solution are needed?",["x = 5/2 or 2.5 liters","x = 5 liters","x = 10 liters","x = 3 liters"],0,
        "Equation: 0.2(5) + 0.5x = 0.3(5 + x). So 1 + 0.5x = 1.5 + 0.3x. Then 0.2x = 0.5, x = 2.5 liters."),
    make_q(25,"A kayaker paddles 12 miles upstream in a river with 2 mph current, then 12 miles back downstream. Her still-water speed is 6 mph. What is the total time?",["6 hours","4 hours","3 hours","5 hours"],0,
        "Upstream: 12/(6-2) = 12/4 = 3 hours. Downstream: 12/(6+2) = 12/8 = 1.5 hours. Total = 4.5. Hmm, that's not 6."),
]
# Fix Q25
qs46[24] = make_q(25,"A kayaker paddles 12 miles upstream in a river with 2 mph current, then 12 miles back downstream. Her still-water speed is 6 mph. What is the total time?",["4.5 hours","4 hours","3 hours","5 hours"],0,
        "Upstream speed: 6 - 2 = 4 mph, time = 12/4 = 3 hours. Downstream speed: 6 + 2 = 8 mph, time = 12/8 = 1.5 hours. Total = 3 + 1.5 = 4.5 hours.")
qs46 += [
    make_q(26,"A school orders t-shirts at a total cost of $600. If 10 more students join, the cost per shirt drops by $2. How many students originally?",["20 students","30 students","25 students","15 students"],0,
        "Let x = original students. 600/x - 600/(x+10) = 2. Multiply by x(x+10): 600(x+10) - 600x = 2x(x+10). 6000 = 2x^2 + 20x. x^2 + 10x - 3000 = 0. (x+60)(x-50) has discriminant check: actually (x-20) doesn't factor simply. Let me try: 600/x - 2 = 600/(x+10). So 600 - 2x = 600x/(x+10). (600-2x)(x+10) = 600x. 600x + 6000 - 2x^2 - 20x = 600x. 6000 - 2x^2 - 20x = 0. x^2 + 10x - 3000 = 0. Discriminant: 100 + 12000 = 12100. sqrt(12100) = 110. x = (-10+110)/2 = 50."),
]
# Fix Q26
qs46[25] = make_q(26,"A club orders pizzas costing $300 total. If 5 more members join and split the cost, each person pays $2 less. How many original members?",["25 members","20 members","30 members","15 members"],0,
        "Let x = original members: 300/x - 300/(x+5) = 2. Multiply by x(x+5): 300(x+5) - 300x = 2x(x+5). 1500 = 2x^2 + 10x. x^2 + 5x - 750 = 0. (x+30)(x-25) = 0. Since x > 0, x = 25.")
qs46 += [
    make_q(27,"A pump fills a tank in 10 hours. A drain empties it in 15 hours. If both are open, how long to fill the tank?",["30 hours","25 hours","12 hours","5 hours"],0,
        "Net rate: 1/10 - 1/15 = 3/30 - 2/30 = 1/30. Time = 30 hours."),
    make_q(28,"A plane flies 600 miles with a 50 mph tailwind in the same time it takes to fly 400 miles against the wind. What is the plane's speed in still air?",["250 mph","200 mph","300 mph","150 mph"],0,
        "Let s = still air speed. 600/(s+50) = 400/(s-50). Cross-multiply: 600(s-50) = 400(s+50). 600s - 30000 = 400s + 20000. 200s = 50000. s = 250 mph."),
    make_q(29,"An office has a copier that prints a report in 6 minutes and a newer copier that prints it in 4 minutes. Together, how long?",["2.4 minutes","5 minutes","3 minutes","10 minutes"],0,
        "Combined rate: 1/6 + 1/4 = 2/12 + 3/12 = 5/12. Time = 12/5 = 2.4 minutes."),
    make_q(30,"A farmer mixes 40 gallons of 25% fertilizer with pure water to get 10% solution. How many gallons of water should be added?",["60 gallons","40 gallons","80 gallons","100 gallons"],0,
        "Fertilizer amount: 0.25(40) = 10 gallons. Final: 10/(40 + w) = 0.10. So 40 + w = 100, w = 60 gallons."),
]

print("Writing Unit 4 files...")
write_quiz(4, "4.1", "Rational Expressions", qs41)
write_quiz(4, "4.2", "Operations on Rational Expressions", qs42)
write_quiz(4, "4.3", "Rational Equations", qs43)
write_quiz(4, "4.4", "Graphing Rational Functions", qs44)
write_quiz(4, "4.5", "Asymptotes & Discontinuities", qs45)
write_quiz(4, "4.6", "Applications of Rational Functions", qs46)
print("Unit 4 complete!")
