import json, os

BASE = r"c:\Users\Peter\pkang6689-pixel.github.io\content_data\AstronomyLessons\Unit3"

def q(num, text, options, explanation):
    opts = []
    for o in options:
        if isinstance(o, tuple):
            opts.append({"text": o[0], "is_correct": o[1], "data_i18n": None})
        else:
            opts.append({"text": o, "is_correct": False, "data_i18n": None})
    return {
        "question_number": num,
        "question_text": text,
        "attempted": 2,
        "data_i18n": None,
        "options": opts,
        "explanation": explanation
    }

def write_quiz(filename, unit, lesson_num, title, questions):
    data = {
        "unit": unit,
        "lesson_number": lesson_num,
        "title": title,
        "course": "Astronomy",
        "quiz_questions": questions
    }
    path = os.path.join(BASE, filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Wrote {path} with {len(questions)} questions")

# ============================================================
# Lesson 3.1: Formation of the Solar System
# ============================================================
L31 = [
    q(1, "The solar system formed from a collapsing cloud of gas and dust called a:",
      [("Solar nebula", True), ("Black hole", False), ("Red giant", False), ("White dwarf", False)],
      "The solar nebula hypothesis states our solar system formed from a rotating cloud of gas and dust about 4.6 billion years ago."),
    q(2, "Approximately how old is our solar system?",
      [("4.6 billion years", True), ("1 billion years", False), ("13.8 billion years", False), ("100 million years", False)],
      "Radiometric dating of meteorites gives a solar system age of approximately 4.6 billion years."),
    q(3, "As the solar nebula collapsed, it began to spin faster due to:",
      [("Conservation of angular momentum", True), ("Magnetic fields", False), ("Solar wind", False), ("Dark energy", False)],
      "As the cloud contracted, conservation of angular momentum caused it to spin faster, like a figure skater pulling in her arms."),
    q(4, "The flat disk shape of the solar nebula explains why:",
      [("Planets orbit roughly in the same plane", True), ("The Sun is round", False), ("Stars twinkle", False), ("Comets have tails", False)],
      "The collapsing nebula flattened into a protoplanetary disk, and planets formed within this disk, so they orbit in nearly the same plane."),
    q(5, "Which process built up planets from small particles colliding and sticking together?",
      [("Accretion", True), ("Fission", False), ("Evaporation", False), ("Radiation", False)],
      "Accretion is the gradual growth of bodies as particles collide and stick, eventually forming planetesimals and planets."),
    q(6, "The 'frost line' in the solar nebula is the distance beyond which:",
      [("Water and other volatiles could condense into ice", True), ("Metals could melt", False), ("The Sun's light could not reach", False), ("Planets could not form", False)],
      "Beyond the frost line (~3 AU), temperatures were low enough for water, ammonia, and methane to freeze, enabling gas giant formation."),
    q(7, "Rocky (terrestrial) planets formed closer to the Sun because:",
      [("Only metals and rocks could condense at the high temperatures near the Sun", True), ("They were pushed inward by gravity", False), ("The Sun attracted rocks more than gas", False), ("Gas giants formed first and pushed them in", False)],
      "Near the Sun, temperatures were too high for volatile ices to condense, so only refractory materials (rock, metal) could accumulate."),
    q(8, "Gas giants formed farther from the Sun because:",
      [("Icy materials could condense beyond the frost line, creating massive cores that captured gas", True), ("They formed from the Sun's atmosphere", False), ("They migrated from near the Sun outward", False), ("The Sun pushed gas outward", False)],
      "Beyond the frost line, large icy/rocky cores formed quickly and were massive enough to gravitationally capture hydrogen and helium gas."),
    q(9, "The early Sun went through a phase of strong solar wind called the:",
      [("T Tauri phase", True), ("Red giant phase", False), ("Supernova phase", False), ("Main sequence phase", False)],
      "The T Tauri phase was a period of intense solar wind that swept away remaining gas from the inner solar system."),
    q(10, "Planetesimals are best described as:",
      [("Small rocky or icy bodies (1-10 km) that were building blocks of planets", True), ("Fully formed planets", False), ("Stars that failed to ignite", False), ("Pieces of the Sun", False)],
      "Planetesimals were kilometer-sized objects that accumulated through accretion to form protoplanets and eventually planets."),
    # Vocabulary (11-20)
    q(11, "What is a 'solar nebula'?",
      [("The rotating cloud of gas and dust from which the Sun and solar system formed", True), ("A nebula near the Sun today", False), ("The Sun's atmosphere", False), ("A type of star", False)],
      "The solar nebula was the primordial cloud that collapsed under gravity to form our solar system ~4.6 billion years ago."),
    q(12, "What is 'accretion'?",
      [("The process of growth by gravitational attraction and collision of smaller bodies", True), ("The explosion of a star", False), ("The cooling of lava", False), ("The evaporation of water", False)],
      "Accretion is how dust grains → pebbles → boulders → planetesimals → planets gradually built up through collisions."),
    q(13, "What is a 'protoplanetary disk'?",
      [("A rotating disk of gas and dust around a young star from which planets form", True), ("A disk-shaped planet", False), ("A galaxy in formation", False), ("A ring around Saturn", False)],
      "A protoplanetary disk is the flattened disk of material orbiting a newborn star, where planets eventually coalesce."),
    q(14, "What is a 'planetesimal'?",
      [("A small body (1-10 km) formed by accretion in the early solar system that is a building block of planets", True), ("A dwarf planet", False), ("A small star", False), ("An asteroid near Earth", False)],
      "Planetesimals are intermediate-sized objects that formed early and merged to create planets."),
    q(15, "What is the 'frost line'?",
      [("The distance from the Sun beyond which volatile compounds like water can condense into ice", True), ("The coldest point in the solar system", False), ("The edge of Pluto's orbit", False), ("Where frost forms on Earth", False)],
      "The frost line (~3 AU from the Sun) marks where temperatures were cool enough for ices to form in the solar nebula."),
    q(16, "What are 'refractory materials'?",
      [("Materials like rock and metal that can withstand high temperatures without vaporizing", True), ("Materials that easily evaporate", False), ("Gases like hydrogen and helium", False), ("Ice and water", False)],
      "Refractory materials (silicates, iron) have high melting points and could condense close to the Sun."),
    q(17, "What are 'volatiles'?",
      [("Substances like water, methane, and ammonia that easily vaporize at low temperatures", True), ("Heavy metals", False), ("Radioactive elements", False), ("Solid rocks", False)],
      "Volatiles are compounds with low boiling points that could only condense as solids far from the Sun in the cool outer nebula."),
    q(18, "What is 'differentiation' in planetary science?",
      [("The separation of a planet's interior into layers (core, mantle, crust) based on density", True), ("The splitting of a planet into two", False), ("Erosion of a planet's surface", False), ("The difference between planets and stars", False)],
      "Differentiation occurs when a planet is hot enough for dense materials to sink to the center and lighter materials to rise, forming layers."),
    q(19, "What is a 'protoplanet'?",
      [("A large body formed from planetesimals that is on its way to becoming a full planet", True), ("A failed star", False), ("An asteroid", False), ("A moon in formation", False)],
      "Protoplanets are large embryonic planets — bigger than planetesimals but not yet full-sized planets."),
    q(20, "What is 'angular momentum'?",
      [("The rotational equivalent of linear momentum — the tendency of a spinning object to keep spinning", True), ("The angle at which planets orbit", False), ("The speed of light around a corner", False), ("The energy of an atom", False)],
      "Angular momentum (L = mvr for orbits) is conserved, which is why the solar nebula spun faster as it contracted."),
    # Scenario (21-30)
    q(21, "A young star system is observed with a protoplanetary disk. Inside the frost line, mainly rocky chunks are accreting. Beyond it, icy bodies are growing rapidly. What does this match?",
      [("Our solar system's formation model — terrestrial planets inside the frost line, gas giants outside", True), ("A system forming only gas giants", False), ("A system with no planets", False), ("A binary star formation", False)],
      "This mirrors the solar nebula model: rocky accretion inside the frost line, icy+gas accretion outside."),
    q(22, "A meteorite is radiometrically dated to 4.56 billion years. What does this tell us?",
      [("It formed at the very beginning of the solar system and helps date its age", True), ("It came from another star system", False), ("It's younger than Earth", False), ("Radiometric dating doesn't work on meteorites", False)],
      "The oldest meteorites (chondrites) date to ~4.56 billion years, establishing the solar system's age."),
    q(23, "All planets orbit the Sun in the same direction and roughly the same plane. A student asks why. What is the explanation?",
      [("They all formed from the same rotating protoplanetary disk", True), ("The Sun's magnetic field aligns them", False), ("Gravity pulls everything into a plane over time", False), ("It's a coincidence", False)],
      "The uniform direction and near-planar orbits reflect the original rotation and flattened shape of the protoplanetary disk."),
    q(24, "Jupiter is mostly hydrogen and helium. Why couldn't Earth accumulate these gases?",
      [("Earth's core was too small and too close to the Sun — it couldn't attract and retain light gases in the hot inner nebula", True), ("Earth formed after all the gas was used up", False), ("Hydrogen doesn't exist near Earth", False), ("Earth's magnetic field repels gas", False)],
      "In the hot inner nebula, light gases didn't condense, and small rocky protoplanets lacked the gravity to capture them."),
    q(25, "A scientist finds that a meteorite contains tiny mineral grains older than the solar system (pre-solar grains). What does this suggest?",
      [("Some material in our solar system predates it, originating from earlier generations of stars", True), ("The meteorite is fake", False), ("The solar system is older than we think", False), ("Minerals cannot survive that long", False)],
      "Pre-solar grains from older stars were incorporated into the solar nebula, surviving the formation process."),
    q(26, "In the solar nebula, most of the mass concentrated at the center to form the Sun. How much of the total mass is in the Sun?",
      [("About 99.8%", True), ("About 50%", False), ("About 75%", False), ("About 90%", False)],
      "The Sun contains approximately 99.8% of the solar system's total mass."),
    q(27, "A young protoplanet experiences heavy bombardment from remaining planetesimals. What effects would this produce?",
      [("Heating of the surface, delivery of volatiles, and craters — contributing to differentiation", True), ("Cooling of the planet", False), ("Immediate formation of oceans", False), ("Removal of the atmosphere", False)],
      "Impacts released kinetic energy as heat, helping melt the interior (enabling differentiation) and delivering water and other volatiles."),
    q(28, "Why does the solar system have an asteroid belt between Mars and Jupiter instead of a planet?",
      [("Jupiter's strong gravity prevented material from accreting into a single planet", True), ("A planet exploded there", False), ("That area had no material", False), ("The Sun's light prevented formation there", False)],
      "Jupiter's gravitational influence stirred up planetesimals in that region, increasing collision velocities and preventing accretion into a planet."),
    q(29, "The Nice model proposes that the gas giants migrated from their original positions. What evidence supports this?",
      [("The Late Heavy Bombardment and the current distribution of small bodies in the outer solar system", True), ("The gas giants are all the same size", False), ("The Sun rotates very fast", False), ("Mercury has ice at its poles", False)],
      "The Nice model explains the Late Heavy Bombardment (~3.9 Ga) and the orbital structure of Kuiper Belt objects through giant planet migration."),
    q(30, "If the solar nebula had been much colder throughout, how might the solar system be different?",
      [("Ices could condense closer to the Sun, potentially allowing gas giants to form nearer in", True), ("No planets would form", False), ("The Sun would be larger", False), ("Only rocky planets would exist", False)],
      "A cooler nebula would move the frost line inward, allowing icy materials to accumulate closer to the Sun, favoring gas giant formation there."),
]
write_quiz("Lesson3.1_Quiz.json", 3, "3.1", "Formation of the Solar System", L31)

# ============================================================
# Lesson 3.2: Terrestrial Planets
# ============================================================
L32 = [
    q(1, "Which planets are classified as terrestrial?",
      [("Mercury, Venus, Earth, Mars", True), ("Jupiter, Saturn, Uranus, Neptune", False), ("Earth, Mars, Jupiter, Saturn", False), ("Mercury, Pluto, Earth, Venus", False)],
      "The four terrestrial (rocky) planets are Mercury, Venus, Earth, and Mars — small, dense worlds with solid surfaces."),
    q(2, "Terrestrial planets are primarily composed of:",
      [("Rock and metal", True), ("Hydrogen and helium", False), ("Water and ice", False), ("Nitrogen and methane", False)],
      "Terrestrial planets are made mainly of silicate rocks and metals like iron, giving them high densities."),
    q(3, "Which terrestrial planet is the largest?",
      [("Earth", True), ("Venus", False), ("Mars", False), ("Mercury", False)],
      "Earth is the largest terrestrial planet, with a diameter of about 12,742 km."),
    q(4, "Which terrestrial planet has the thickest atmosphere?",
      [("Venus", True), ("Earth", False), ("Mars", False), ("Mercury", False)],
      "Venus has an extremely thick CO₂ atmosphere with surface pressure about 92 times Earth's."),
    q(5, "Mercury is notable for having:",
      [("Virtually no atmosphere and extreme temperature variations", True), ("The thickest atmosphere of all terrestrial planets", False), ("Liquid water on its surface", False), ("Active volcanoes today", False)],
      "Mercury has almost no atmosphere, so temperatures swing from ~430°C (day) to -180°C (night)."),
    q(6, "Mars appears red because:",
      [("Iron oxide (rust) on its surface", True), ("It reflects the Sun's red light", False), ("Its atmosphere filters out blue light", False), ("Volcanic lava covers it", False)],
      "Mars's reddish color comes from iron oxide (Fe₂O₃) in its soil and dust."),
    q(7, "Which terrestrial planet has a strong magnetic field?",
      [("Earth", True), ("Venus", False), ("Mars", False), ("Mercury", False)],
      "Earth's rotating liquid iron outer core generates a strong magnetic field that protects the atmosphere from solar wind."),
    q(8, "Venus rotates in the opposite direction from most planets. This is called:",
      [("Retrograde rotation", True), ("Prograde rotation", False), ("Synchronous rotation", False), ("Precession", False)],
      "Venus has retrograde rotation — it spins clockwise when viewed from above the north pole, opposite to most planets."),
    q(9, "The largest volcano in the solar system, Olympus Mons, is on:",
      [("Mars", True), ("Venus", False), ("Earth", False), ("Mercury", False)],
      "Olympus Mons on Mars is ~21 km high and ~600 km across, the largest known volcano in the solar system."),
    q(10, "Which terrestrial planet has evidence of past liquid water on its surface?",
      [("Mars", True), ("Mercury", False), ("Venus", False), ("All of them equally", False)],
      "Mars shows extensive evidence of ancient riverbeds, lake basins, and mineral deposits that formed in water."),
    # Vocabulary (11-20)
    q(11, "What does 'terrestrial planet' mean?",
      [("A rocky planet with a solid surface, similar in composition to Earth", True), ("Any planet with life", False), ("A planet with rings", False), ("A gas-dominated planet", False)],
      "Terrestrial planets (from Latin 'terra' = earth) are small, dense, rocky worlds with solid surfaces."),
    q(12, "What is a 'magnetosphere'?",
      [("The region around a planet controlled by its magnetic field that deflects solar wind", True), ("The atmosphere of a planet", False), ("A magnetic rock on a planet's surface", False), ("The core of a planet", False)],
      "A magnetosphere is the magnetic 'bubble' around a planet that shields it from charged particles in the solar wind."),
    q(13, "What is the 'greenhouse effect'?",
      [("When atmospheric gases trap heat, warming a planet's surface beyond what sunlight alone would produce", True), ("When plants grow in a greenhouse", False), ("When a planet turns green", False), ("When ice reflects sunlight", False)],
      "The greenhouse effect occurs when CO₂, water vapor, and other gases absorb and re-emit infrared radiation, warming the surface."),
    q(14, "What is 'volcanism'?",
      [("The eruption of molten rock (lava) and gases from a planet's interior to its surface", True), ("Erosion by wind", False), ("Tectonic plate movement only", False), ("Lightning storms on a planet", False)],
      "Volcanism releases internal heat and materials, shaping planetary surfaces with lava flows, mountains, and craters."),
    q(15, "What is 'plate tectonics'?",
      [("The movement of large rigid pieces of a planet's crust driven by convection in the mantle", True), ("The breaking of plates in an earthquake", False), ("Mountain formation only", False), ("A process unique to the Moon", False)],
      "Plate tectonics is Earth's unique (among planets) process of crustal plates moving, colliding, and separating."),
    q(16, "What is a 'runaway greenhouse effect'?",
      [("An extreme greenhouse effect where rising temperatures cause more greenhouse gas release in a feedback loop", True), ("A greenhouse that runs away", False), ("Normal seasonal warming", False), ("Cooling caused by too many clouds", False)],
      "Venus likely experienced a runaway greenhouse effect where evaporating water increased heating, which evaporated more water, in a vicious cycle."),
    q(17, "What is 'regolith'?",
      [("The layer of loose, broken rock and dust covering a solid rocky surface", True), ("A type of mineral", False), ("Underground water", False), ("A volcanic rock", False)],
      "Regolith covers the Moon, Mars, and other bodies — it's fragmented surface material created by impacts and weathering."),
    q(18, "What is 'albedo'?",
      [("The fraction of incoming light that a surface reflects", True), ("The color of a planet", False), ("The temperature of a planet", False), ("The density of an atmosphere", False)],
      "Albedo ranges from 0 (absorbs all light) to 1 (reflects all light). Venus has a high albedo (~0.7) due to its thick clouds."),
    q(19, "What is 'outgassing'?",
      [("The release of gases from a planet's interior through volcanic activity", True), ("Gas escaping from outer space", False), ("The cooling of gas into liquid", False), ("Wind erosion", False)],
      "Outgassing from volcanic activity built up the early atmospheres of terrestrial planets."),
    q(20, "What is a 'shield volcano'?",
      [("A broad, gently sloping volcano built by successive lava flows, like Olympus Mons", True), ("A volcano that protects a city", False), ("An explosive conical volcano", False), ("An underwater volcano", False)],
      "Shield volcanoes have gentle slopes formed by fluid lava spreading widely — Olympus Mons is the largest example."),
    # Scenario (21-30)
    q(21, "Venus and Earth are similar in size and mass, yet Venus's surface is ~460°C while Earth's averages ~15°C. What is the primary reason?",
      [("Venus has a massive CO₂ atmosphere causing an extreme greenhouse effect", True), ("Venus is much closer to the Sun", False), ("Venus has more volcanoes", False), ("Earth's Moon cools it down", False)],
      "Venus's thick CO₂ atmosphere traps enormous amounts of heat. While Venus is closer to the Sun, the greenhouse effect is the dominant factor."),
    q(22, "Mars once had a thicker atmosphere and liquid water. What likely caused it to lose its atmosphere?",
      [("Without a strong magnetic field, solar wind stripped away atmospheric particles over time", True), ("A giant asteroid destroyed it", False), ("Plants consumed all the CO₂", False), ("Mars moved farther from the Sun", False)],
      "Mars lost its global magnetic field early in its history, leaving the atmosphere unprotected against erosion by solar wind."),
    q(23, "Mercury has a thin exosphere but no proper atmosphere. A student asks why. What do you explain?",
      [("Mercury's weak gravity and proximity to the Sun's heat and solar wind prevent it from holding gases", True), ("Mercury never had volcanic activity", False), ("Mercury's magnetic field blocks gas", False), ("Mercury is too young", False)],
      "Mercury's low mass (weak gravity), high temperatures, and intense solar wind prevent it from retaining a significant atmosphere."),
    q(24, "Scientists discover clay minerals on Mars that only form in the presence of water. What does this imply?",
      [("Mars had liquid water on its surface long enough for these minerals to form", True), ("Water was delivered recently by comets", False), ("The minerals formed from dry chemical reactions", False), ("Humans previously visited Mars", False)],
      "Clay (phyllosilicate) minerals require sustained liquid water contact, indicating Mars had a wet environment in its past."),
    q(25, "Earth is the only terrestrial planet with active plate tectonics. How does this benefit life?",
      [("It recycles carbon, regulates atmospheric CO₂, and maintains a habitable climate over geological time", True), ("It creates beautiful mountains for tourists", False), ("It produces gold and diamonds", False), ("It has no benefit — plate tectonics is dangerous", False)],
      "Plate tectonics drives the carbon-silicate cycle, regulating CO₂ and climate — a key factor in maintaining habitable conditions."),
    q(26, "Venus rotates extremely slowly and in the opposite direction. If you lived on Venus, how would the Sun appear to move?",
      [("It would rise in the west and set in the east, and a solar day would last about 117 Earth days", True), ("It would rise in the east like on Earth", False), ("The Sun would never move", False), ("The Sun would be invisible due to clouds", False)],
      "Venus's retrograde rotation means the Sun would appear to move opposite to Earth, and extreme slowness means very long solar days."),
    q(27, "A probe measures Mercury's density at 5.43 g/cm³ — almost as high as Earth's despite being much smaller. What does this suggest?",
      [("Mercury has an unusually large iron core relative to its size", True), ("Mercury is made of gold", False), ("Mercury has a thick atmosphere compressing it", False), ("The measurement is wrong", False)],
      "Mercury's high density indicates a proportionally enormous iron core — about 60% of the planet by mass."),
    q(28, "Mars has two small, irregular moons (Phobos and Deimos). Their shapes suggest they are:",
      [("Captured asteroids", True), ("Pieces of Mars broken off by an impact", False), ("Former comets", False), ("Perfectly spherical like Earth's Moon", False)],
      "Phobos and Deimos are small, irregularly shaped, and resemble asteroids — likely captured from the nearby asteroid belt."),
    q(29, "A researcher proposes terraforming Mars by increasing its greenhouse effect. What challenge would they face?",
      [("Mars has low gravity and no magnetic field, so added gases would gradually be stripped away by solar wind", True), ("Mars is too close to the Sun", False), ("Mars has too much water", False), ("Mars's soil is too fertile", False)],
      "Without a magnetic field, any new atmosphere would be slowly eroded. Mars's weaker gravity also makes gas retention harder."),
    q(30, "Earth, Venus, and Mars all had early volcanism releasing CO₂. Only Earth maintained a moderate CO₂ level. Why?",
      [("Earth has plate tectonics and liquid water that cycle CO₂ through rock weathering and subduction", True), ("Earth has more volcanoes", False), ("Earth is farther from the Sun so CO₂ freezes", False), ("Plants removed all CO₂ immediately", False)],
      "Earth's unique combination of liquid water and plate tectonics enables the carbon-silicate cycle, which stabilizes CO₂ levels."),
]
write_quiz("Lesson3.2_Quiz.json", 3, "3.2", "Terrestrial Planets", L32)

# ============================================================
# Lesson 3.3: Gas Giants
# ============================================================
L33 = [
    q(1, "The gas giants of our solar system are:",
      [("Jupiter and Saturn", True), ("Uranus and Neptune", False), ("Jupiter, Saturn, Uranus, and Neptune", False), ("Mars and Venus", False)],
      "Jupiter and Saturn are classified as gas giants, primarily composed of hydrogen and helium. Uranus and Neptune are ice giants."),
    q(2, "Jupiter's Great Red Spot is:",
      [("A massive, long-lived storm larger than Earth", True), ("A volcano on Jupiter's surface", False), ("A red-colored crater", False), ("A moon of Jupiter", False)],
      "The Great Red Spot is an anticyclonic storm that has raged for at least 350 years and is larger than Earth."),
    q(3, "Saturn is best known for its:",
      [("Spectacular ring system", True), ("Large number of volcanoes", False), ("Blue color", False), ("Solid surface", False)],
      "Saturn's extensive and visible ring system, made of ice and rock particles, is the most prominent in the solar system."),
    q(4, "Jupiter's density is approximately:",
      [("1.33 g/cm³ — only slightly denser than water", True), ("5.5 g/cm³ — like Earth", False), ("0.1 g/cm³ — lighter than air", False), ("10 g/cm³ — very dense", False)],
      "Despite being massive, Jupiter's hydrogen/helium composition gives it a low bulk density of about 1.33 g/cm³."),
    q(5, "How many confirmed moons does Jupiter have (approximately)?",
      [("Over 90", True), ("2", False), ("16", False), ("5", False)],
      "Jupiter has over 90 confirmed moons, with the four Galilean moons (Io, Europa, Ganymede, Callisto) being the largest."),
    q(6, "Saturn's rings are primarily composed of:",
      [("Ice particles and rocky debris", True), ("Gas clouds", False), ("Liquid metal", False), ("Dust only", False)],
      "Saturn's rings are made of countless particles of ice (mostly water ice) and rock, ranging from tiny grains to house-sized chunks."),
    q(7, "Jupiter's magnetic field is:",
      [("The strongest of any planet, about 20,000 times Earth's", True), ("Weaker than Earth's", False), ("Nonexistent", False), ("The same as Earth's", False)],
      "Jupiter has the solar system's most powerful planetary magnetic field, created by currents in its metallic hydrogen interior."),
    q(8, "What is metallic hydrogen?",
      [("Hydrogen compressed so much it behaves like a liquid metal, conducting electricity", True), ("A metal alloy containing hydrogen", False), ("Frozen hydrogen", False), ("Hydrogen gas at low pressure", False)],
      "Deep inside Jupiter, extreme pressure compresses hydrogen until electrons are freed, creating metallic hydrogen."),
    q(9, "Saturn's average density is about:",
      [("0.69 g/cm³ — less than water", True), ("1.33 g/cm³", False), ("5.5 g/cm³", False), ("2.0 g/cm³", False)],
      "Saturn's density (~0.69 g/cm³) is the lowest of any planet — theoretically, it would float in water if there were a big enough pool."),
    q(10, "Jupiter's Galilean moons include all of the following EXCEPT:",
      [("Titan", True), ("Io", False), ("Europa", False), ("Ganymede", False)],
      "The four Galilean moons are Io, Europa, Ganymede, and Callisto. Titan is Saturn's largest moon."),
    # Vocabulary (11-20)
    q(11, "What is a 'gas giant'?",
      [("A large planet mainly composed of hydrogen and helium without a well-defined solid surface", True), ("Any planet larger than Earth", False), ("A planet made of toxic gas", False), ("A star that didn't ignite", False)],
      "Gas giants (Jupiter, Saturn) are massive planets dominated by hydrogen and helium with deep gaseous atmospheres."),
    q(12, "What is 'metallic hydrogen'?",
      [("A state of hydrogen under extreme pressure where it conducts electricity like a metal", True), ("Hydrogen mixed with metals", False), ("Solid ice of hydrogen", False), ("Hydrogen in a magnetic field", False)],
      "At millions of atmospheres of pressure, hydrogen's electrons become delocalized, making it an electrically conducting fluid."),
    q(13, "What is a 'Galilean moon'?",
      [("One of the four largest moons of Jupiter, discovered by Galileo: Io, Europa, Ganymede, Callisto", True), ("Any moon discovered by Galileo", False), ("A moon of Saturn", False), ("A small asteroid", False)],
      "The Galilean moons are Jupiter's four major satellites, first observed by Galileo in 1610 through his telescope."),
    q(14, "What is the 'Roche limit' in the context of ring formation?",
      [("The distance inside which tidal forces prevent moons from forming, leading to rings instead", True), ("The maximum size of a ring particle", False), ("The outer edge of a ring system", False), ("A moon's orbit speed limit", False)],
      "Saturn's rings exist within its Roche limit, where tidal forces would tear apart any moon that ventured too close."),
    q(15, "What is an 'anticyclone'?",
      [("A large area of high pressure with winds spiraling outward — like Jupiter's Great Red Spot", True), ("A low-pressure storm like a hurricane", False), ("A tornado", False), ("A tidal wave", False)],
      "An anticyclone rotates opposite to cyclones; Jupiter's Great Red Spot is a massive, long-lived anticyclonic storm."),
    q(16, "What are 'zonal winds'?",
      [("Alternating bands of east-west winds at different latitudes on gas giants", True), ("Winds in the ozone layer", False), ("Winds on Earth only", False), ("Vertical winds in a storm", False)],
      "Gas giants display prominent zonal wind patterns — alternating jet streams flowing east and west at different latitudes."),
    q(17, "What is the 'Cassini Division'?",
      [("A prominent gap in Saturn's ring system, caused by orbital resonance with the moon Mimas", True), ("A method for dividing astronomical data", False), ("A crack in Jupiter's surface", False), ("A space between Uranus's moons", False)],
      "The Cassini Division is a ~4,800 km gap in Saturn's rings, maintained by the gravitational influence of the moon Mimas."),
    q(18, "What is 'orbital resonance'?",
      [("When two orbiting bodies exert regular, periodic gravitational influence on each other due to their orbital periods being in simple ratios", True), ("When orbits are perfectly circular", False), ("The sound of a planet orbiting", False), ("When two planets collide", False)],
      "Orbital resonance (e.g., 2:1) means one body orbits exactly twice while another orbits once, amplifying gravitational effects."),
    q(19, "What is a 'magnetopause'?",
      [("The boundary where a planet's magnetic field meets and balances the solar wind pressure", True), ("A pause in magnetic activity", False), ("The center of a planet's core", False), ("A type of aurora", False)],
      "The magnetopause defines the outer edge of a magnetosphere, where magnetic pressure equals solar wind pressure."),
    q(20, "What are 'shepherd moons'?",
      [("Small moons whose gravity keeps ring particles confined in narrow rings", True), ("Moons that herd other moons", False), ("The largest moons of a planet", False), ("Moons that follow each other", False)],
      "Shepherd moons (like Pandora and Prometheus for Saturn's F ring) gravitationally constrain ring edges."),
    # Scenario (21-30)
    q(21, "Europa has a smooth, icy surface with few craters. Beneath the ice, scientists suspect a liquid water ocean. What evidence supports this?",
      [("Magnetic field measurements from Galileo suggest a subsurface conducting layer (salt water), and the surface shows fresh cracks and ice rafts", True), ("Europa has visible lakes", False), ("Fish have been detected", False), ("Europa has volcanoes like Earth", False)],
      "The Galileo spacecraft detected induced magnetic fields consistent with a subsurface ocean, and Europa's surface features suggest active resurfacing."),
    q(22, "Io is the most volcanically active body in the solar system. What powers this activity?",
      [("Tidal heating from Jupiter's gravity and orbital resonance with Europa and Ganymede", True), ("Radioactive decay in its core", False), ("Solar radiation", False), ("Io has a nuclear reactor", False)],
      "Io's orbital resonance with Europa and Ganymede keeps its orbit slightly eccentric, causing Jupiter's tidal forces to flex and heat Io's interior."),
    q(23, "If Saturn were placed in a giant pool of water, what would theoretically happen?",
      [("It would float — its average density (0.69 g/cm³) is less than water (1.0 g/cm³)", True), ("It would sink immediately", False), ("It would dissolve", False), ("Nothing special", False)],
      "Saturn's bulk density is about 0.69 g/cm³, making it the only planet less dense than water."),
    q(24, "Jupiter emits more heat than it receives from the Sun. What is the most likely source of this excess heat?",
      [("Slow gravitational contraction (Kelvin-Helmholtz mechanism) releasing stored energy", True), ("Nuclear fusion in Jupiter's core", False), ("Chemical reactions in the atmosphere", False), ("Heat from its moons", False)],
      "Jupiter radiates ~1.7 times the energy it receives from the Sun, mostly from continued slow gravitational compression."),
    q(25, "An astronomer discovers an exoplanet called a 'hot Jupiter' — a gas giant orbiting very close to its star. How might it have gotten there?",
      [("It likely formed farther out and migrated inward through interactions with the protoplanetary disk or other planets", True), ("It formed right where it is", False), ("The star captured it from another system", False), ("It's not really a gas giant", False)],
      "Hot Jupiters are thought to have migrated inward from formation sites beyond the frost line through disk interaction or gravitational scattering."),
    q(26, "Saturn's moon Enceladus shoots geysers of water into space. What does this imply?",
      [("Enceladus likely has a subsurface liquid water ocean, heated by tidal forces", True), ("Enceladus is evaporating", False), ("Saturn's heat melts Enceladus", False), ("The geysers are volcanic lava", False)],
      "The Cassini spacecraft detected water-rich plumes from Enceladus, suggesting a liquid water reservoir maintained by tidal heating."),
    q(27, "Voyager discovered that Jupiter's faint ring system exists. Unlike Saturn's bright rings, Jupiter's are very dark. Why?",
      [("Jupiter's rings are made mostly of tiny dark dust particles kicked up by meteoroid impacts on small inner moons", True), ("Jupiter's rings are new", False), ("Jupiter's gravity crushes the particles", False), ("Jupiter's magnetic field hides them", False)],
      "Jupiter's rings are composed of fine, dark dust from micrometeoroid impacts on small inner moons like Metis and Adrastea."),
    q(28, "A student says 'Jupiter is a failed star.' Is this accurate?",
      [("Partially — Jupiter has a similar composition to stars but is about 75-80 times too small to sustain hydrogen fusion", True), ("Yes — Jupiter almost became a star", False), ("No — Jupiter has nothing in common with stars", False), ("Yes — Jupiter will ignite later", False)],
      "While Jupiter is made of hydrogen and helium like a star, it would need ~75-80 times more mass to achieve hydrogen fusion."),
    q(29, "Saturn's hexagonal cloud pattern at its north pole puzzled scientists. What creates it?",
      [("A standing wave pattern in the jet stream at that latitude, maintained by wind speed differences", True), ("Aliens constructed it", False), ("Magnetic fields shape the clouds", False), ("It's an optical illusion", False)],
      "Saturn's hexagon is a persistent wave pattern in atmospheric jet streams, reproduced in laboratory fluid dynamics experiments."),
    q(30, "The Galileo probe descended into Jupiter's atmosphere in 1995. It found less water than expected. What did this suggest?",
      [("The probe may have entered an unusually dry downdraft region, not representative of Jupiter's overall composition", True), ("Jupiter has no water at all", False), ("The probe malfunctioned", False), ("Water doesn't exist on gas giants", False)],
      "The Galileo probe likely entered a dry 'hot spot' with strong downdrafts; later observations confirmed Jupiter has more water overall."),
]
write_quiz("Lesson3.3_Quiz.json", 3, "3.3", "Gas Giants", L33)

# ============================================================
# Lesson 3.4: Dwarf Planets & Asteroids
# ============================================================
L34 = [
    q(1, "Pluto was reclassified from planet to dwarf planet in:",
      [("2006", True), ("1930", False), ("1990", False), ("2015", False)],
      "The International Astronomical Union reclassified Pluto as a dwarf planet in 2006 because it hasn't cleared its orbital neighborhood."),
    q(2, "A dwarf planet differs from a planet because it:",
      [("Has not cleared its orbital neighborhood of other debris", True), ("Is too small to have gravity", False), ("Does not orbit the Sun", False), ("Has no atmosphere", False)],
      "A dwarf planet orbits the Sun and has enough gravity for a round shape, but has not cleared its orbital zone."),
    q(3, "The asteroid belt is located between the orbits of:",
      [("Mars and Jupiter", True), ("Earth and Mars", False), ("Jupiter and Saturn", False), ("Venus and Earth", False)],
      "The main asteroid belt occupies the region between Mars (~1.5 AU) and Jupiter (~5.2 AU)."),
    q(4, "The largest object in the asteroid belt is:",
      [("Ceres (a dwarf planet)", True), ("Pluto", False), ("Vesta", False), ("The Moon", False)],
      "Ceres, at ~940 km diameter, is the largest object in the asteroid belt and is classified as a dwarf planet."),
    q(5, "Which dwarf planet has a heart-shaped nitrogen ice plain?",
      [("Pluto", True), ("Ceres", False), ("Eris", False), ("Makemake", False)],
      "New Horizons revealed Pluto's Sputnik Planitia — a heart-shaped plain of nitrogen ice — in 2015."),
    q(6, "Eris is a dwarf planet located in:",
      [("The scattered disc / Kuiper Belt region, beyond Neptune", True), ("The asteroid belt", False), ("Earth's orbit", False), ("The Oort Cloud", False)],
      "Eris orbits in the scattered disc beyond Neptune and was the discovery that prompted Pluto's reclassification."),
    q(7, "Most asteroids are composed of:",
      [("Rock and metal", True), ("Ice and gas", False), ("Pure iron", False), ("Water", False)],
      "Asteroids are primarily rocky and metallic bodies — remnants of the early solar system that never formed a planet."),
    q(8, "The total mass of all asteroids in the belt is:",
      [("About 4% of the Moon's mass", True), ("Greater than Jupiter's mass", False), ("Equal to Earth's mass", False), ("About half the Sun's mass", False)],
      "Despite spanning a huge region, the total mass of the asteroid belt is only about 4% of the Moon's mass."),
    q(9, "Trojan asteroids share an orbit with a planet, located at:",
      [("Lagrange points L4 and L5 (60° ahead and behind the planet)", True), ("Directly behind the planet", False), ("At the planet's poles", False), ("Inside the planet's atmosphere", False)],
      "Trojan asteroids orbit at gravitationally stable Lagrange points, 60° ahead of and behind a planet (especially Jupiter)."),
    q(10, "The New Horizons mission that visited Pluto was launched by:",
      [("NASA", True), ("ESA", False), ("SpaceX", False), ("JAXA", False)],
      "NASA's New Horizons launched in 2006 and flew by Pluto in July 2015, providing the first close-up images."),
    # Vocabulary (11-20)
    q(11, "What is a 'dwarf planet'?",
      [("A celestial body that orbits the Sun, has enough mass for a round shape, but has not cleared its orbital neighborhood", True), ("A very small planet like Mercury", False), ("A moon of a giant planet", False), ("An asteroid larger than 100 km", False)],
      "The IAU defined dwarf planets in 2006 as bodies that meet two of three planet criteria — the third (clearing the orbit) is not met."),
    q(12, "What is an 'asteroid'?",
      [("A small rocky body orbiting the Sun, mostly found in the belt between Mars and Jupiter", True), ("A shooting star", False), ("A small planet", False), ("A piece of a comet", False)],
      "Asteroids are rocky/metallic remnants from the solar system's formation that never accreted into a planet."),
    q(13, "What is the 'Kuiper Belt'?",
      [("A region of icy bodies beyond Neptune's orbit, from about 30-50 AU", True), ("A belt of asteroids between Mars and Jupiter", False), ("A ring around Saturn", False), ("A dust cloud around the Sun", False)],
      "The Kuiper Belt is a vast ring of icy objects beyond Neptune, home to Pluto, Eris, Makemake, and Haumea."),
    q(14, "What is a 'near-Earth object' (NEO)?",
      [("An asteroid or comet with an orbit that brings it close to Earth's orbit", True), ("Any satellite orbiting Earth", False), ("The Moon", False), ("Space debris from rockets", False)],
      "NEOs are asteroids or comets whose orbits bring them within 1.3 AU of the Sun, posing potential impact risks."),
    q(15, "What is a 'Lagrange point'?",
      [("A position in space where the gravitational forces of two large bodies balance the centripetal force needed for a small body to orbit with them", True), ("The center of an orbit", False), ("A point where gravity is zero", False), ("The farthest point from the Sun", False)],
      "Lagrange points (L1-L5) are equilibrium positions where a small body can maintain a stable position relative to two larger bodies."),
    q(16, "What is the 'scattered disc'?",
      [("A distant region of icy bodies with highly eccentric orbits, beyond the Kuiper Belt", True), ("Debris from a destroyed planet", False), ("The inner asteroid belt", False), ("Saturn's ring material", False)],
      "The scattered disc contains icy objects (like Eris) with tilted, elongated orbits, scattered by Neptune's gravity."),
    q(17, "What is 'albedo' in the context of asteroids?",
      [("The reflectivity of an asteroid's surface — used to estimate size and composition", True), ("The speed of an asteroid", False), ("The shape of an asteroid", False), ("The age of an asteroid", False)],
      "Asteroid albedo helps determine composition: metallic asteroids are more reflective than carbon-rich ones."),
    q(18, "What is 'orbital clearing'?",
      [("A planet's ability to gravitationally dominate its orbital zone, removing or capturing smaller bodies", True), ("When an orbit becomes perfectly circular", False), ("Cleaning debris from a spacecraft's path", False), ("When clouds clear in orbit", False)],
      "Orbital clearing is the third criterion for planet classification — planets must dominate their orbit gravitationally."),
    q(19, "What is a 'carbonaceous asteroid' (C-type)?",
      [("A dark, carbon-rich asteroid that is the most common type in the outer asteroid belt", True), ("An asteroid made of diamonds", False), ("A metallic asteroid", False), ("An asteroid from outside the solar system", False)],
      "C-type asteroids are dark, carbon-rich objects making up about 75% of known asteroids, common in the outer belt."),
    q(20, "What is a 'binary asteroid'?",
      [("A system of two asteroids orbiting their common center of gravity", True), ("An asteroid split in half", False), ("Two asteroids colliding", False), ("An asteroid with two names", False)],
      "Binary asteroids are pairs of asteroids gravitationally bound and orbiting each other — about 15% of NEOs are binaries."),
    # Scenario (21-30)
    q(21, "An astronomer discovers a round object orbiting the Sun at 40 AU with many other icy bodies nearby. Should this be classified as a planet or dwarf planet?",
      [("Dwarf planet — it hasn't cleared its orbital neighborhood despite being round and orbiting the Sun", True), ("Planet — it orbits the Sun and is round", False), ("Asteroid — it's too far from the Sun", False), ("Comet — icy objects are always comets", False)],
      "Even if round and Sun-orbiting, sharing its zone with many other bodies means it hasn't cleared its orbit — so it's a dwarf planet."),
    q(22, "NASA's DART mission intentionally crashed into asteroid Dimorphos in 2022. What was the purpose?",
      [("To test whether a kinetic impactor could change an asteroid's orbit, as a planetary defense technique", True), ("To collect rock samples", False), ("To search for alien life", False), ("To mine metals", False)],
      "DART was the first planetary defense test, successfully altering Dimorphos's orbit around Didymos by 33 minutes."),
    q(23, "Jupiter's gravity prevents asteroid belt material from forming a planet. If Jupiter didn't exist, would a planet have formed?",
      [("Possibly a small rocky planet, but the total mass of the belt is very small — only ~4% of the Moon's mass", True), ("A gas giant would have formed", False), ("A planet larger than Earth", False), ("Definitely not — there's not enough material", False)],
      "Without Jupiter's perturbations, material might have accreted, but the belt's total mass is so low that only a very small body could form."),
    q(24, "The Dawn mission visited both Vesta and Ceres. It found that Vesta is dry and rocky while Ceres has water ice and organic molecules. What explains this difference?",
      [("Vesta formed closer to the Sun where it was too hot for ice; Ceres formed farther out where ice could condense", True), ("Ceres captured a comet", False), ("Vesta lost its ice during a collision", False), ("They formed at the same location", False)],
      "Vesta and Ceres represent different formation zones: Vesta near the inner belt (dry) and Ceres in the outer belt (ice-rich)."),
    q(25, "Pluto has a large moon, Charon, that is about half its size. The pair are sometimes called a 'double dwarf planet.' Why?",
      [("Charon is so large relative to Pluto that their center of mass (barycenter) lies outside Pluto's surface", True), ("They are the same color", False), ("They were discovered together", False), ("Both were once planets", False)],
      "The Pluto-Charon barycenter is in the space between them, making them more like a binary system than a planet-moon pair."),
    q(26, "A metallic asteroid is discovered with high concentrations of platinum and gold. A company proposes mining it. What makes metallic asteroids especially valuable?",
      [("They contain concentrated precious and industrial metals that are rare on Earth's surface", True), ("They are closer to Earth", False), ("They are easier to land on", False), ("They have breathable atmospheres", False)],
      "M-type (metallic) asteroids are essentially exposed planetary cores, rich in iron, nickel, platinum-group metals, and other valuable elements."),
    q(27, "Haumea, a dwarf planet in the Kuiper Belt, has an elongated (egg-like) shape and two small moons. What causes its unusual shape?",
      [("Rapid rotation (about 4 hours) stretches it into an ellipsoid", True), ("A recent collision flattened it", False), ("It hasn't achieved hydrostatic equilibrium", False), ("Its moons pull it into that shape", False)],
      "Haumea rotates extremely rapidly (~3.9 hours), causing centrifugal forces to deform it into a triaxial ellipsoid."),
    q(28, "An asteroid is tracked and found to have a 1-in-1000 chance of hitting Earth in 50 years. What type of asteroid is it classified as?",
      [("A potentially hazardous asteroid (PHA)", True), ("A Trojan asteroid", False), ("A main-belt asteroid", False), ("A trans-Neptunian object", False)],
      "PHAs are near-Earth asteroids with orbits that come within 0.05 AU of Earth's orbit and are large enough to cause damage."),
    q(29, "The asteroid Bennu was sampled by NASA's OSIRIS-REx mission. The sample contained amino acids and water-bearing minerals. Why is this significant?",
      [("It suggests asteroids may have delivered building blocks of life and water to early Earth", True), ("It proves aliens exist", False), ("It means Bennu is alive", False), ("It shows asteroids are from another galaxy", False)],
      "Finding organic molecules and hydrated minerals on Bennu supports the theory that asteroids seeded early Earth with water and life precursors."),
    q(30, "If Pluto were placed in Mars's orbit, would it be reclassified as a planet?",
      [("Likely no — Pluto still wouldn't have enough mass to gravitationally clear Mars's orbital neighborhood", True), ("Yes — being inside the asteroid belt makes it a planet", False), ("Yes — proximity to the Sun would make it a planet", False), ("No — once a dwarf planet, always a dwarf planet", False)],
      "Planet classification depends on clearing the orbit. Pluto's small mass (0.2% of Earth's) likely couldn't dominate even Mars's zone."),
]
write_quiz("Lesson3.4_Quiz.json", 3, "3.4", "Dwarf Planets & Asteroids", L34)

# ============================================================
# Lesson 3.5: Comets & Meteoroids
# ============================================================
L35 = [
    q(1, "Comets are primarily composed of:",
      [("Ice, dust, and rocky particles — often called 'dirty snowballs'", True), ("Pure rock", False), ("Liquid water", False), ("Metallic iron", False)],
      "Comets are mixtures of frozen gases (water, CO₂, methane), dust, and small rocky particles."),
    q(2, "A comet's tail always points:",
      [("Away from the Sun, regardless of the comet's direction of travel", True), ("Toward the Sun", False), ("In the direction the comet is moving", False), ("Toward Earth", False)],
      "Solar radiation pressure and solar wind push a comet's gas and dust tails away from the Sun."),
    q(3, "Most short-period comets originate from:",
      [("The Kuiper Belt", True), ("The asteroid belt", False), ("The Sun", False), ("Mars", False)],
      "Short-period comets (orbital periods < 200 years) typically originate from the Kuiper Belt beyond Neptune."),
    q(4, "Long-period comets are thought to originate from:",
      [("The Oort Cloud", True), ("The Kuiper Belt", False), ("The asteroid belt", False), ("Jupiter's moons", False)],
      "The Oort Cloud, a distant spherical shell of icy bodies extending ~50,000 AU, is the source of long-period comets."),
    q(5, "A meteor is:",
      [("A streak of light caused by a small particle burning up in Earth's atmosphere", True), ("A rock in space", False), ("A rock that lands on Earth", False), ("A comet passing nearby", False)],
      "A meteor (shooting star) is the visible streak of light when a meteoroid enters and burns up in the atmosphere."),
    q(6, "A meteorite is:",
      [("A piece of space rock that survives passage through the atmosphere and reaches Earth's surface", True), ("A rock in space", False), ("A streak of light in the sky", False), ("A small asteroid", False)],
      "Meteorites are meteoroids that survive atmospheric entry and land on Earth's surface."),
    q(7, "Meteor showers occur when Earth passes through:",
      [("The debris trail left by a comet", True), ("A cloud of asteroids", False), ("The asteroid belt", False), ("The Sun's corona", False)],
      "Comets leave trails of dust along their orbits; when Earth crosses these trails, we see predictable meteor showers."),
    q(8, "The Perseid meteor shower in August is associated with which comet?",
      [("Comet Swift-Tuttle", True), ("Halley's Comet", False), ("Comet Hale-Bopp", False), ("Comet NEOWISE", False)],
      "The Perseids are caused by debris from Comet Swift-Tuttle, which orbits the Sun every ~133 years."),
    q(9, "Halley's Comet has an orbital period of approximately:",
      [("76 years", True), ("12 years", False), ("200 years", False), ("5 years", False)],
      "Halley's Comet returns to the inner solar system approximately every 75-76 years; it last appeared in 1986."),
    q(10, "Comets typically have two tails. What are they?",
      [("A dust tail and an ion (gas) tail", True), ("A fire tail and an ice tail", False), ("A magnetic tail and a gravity tail", False), ("A visible tail and an invisible tail", False)],
      "The dust tail is curved (pushed by radiation pressure) and the ion tail is straight (pushed by solar wind along magnetic field lines)."),
    # Vocabulary (11-20)
    q(11, "What is a 'comet nucleus'?",
      [("The solid, central part of a comet made of ice, dust, and rock", True), ("The tail of a comet", False), ("The bright glow around a comet", False), ("A comet's orbit", False)],
      "The nucleus is the solid body of a comet, typically a few km across, composed of frozen gases, dust, and rock."),
    q(12, "What is a 'coma'?",
      [("The fuzzy, glowing cloud of gas and dust surrounding a comet's nucleus", True), ("A comet's tail", False), ("A dark region on the Sun", False), ("An unconscious state", False)],
      "As a comet approaches the Sun, heat vaporizes surface ices, creating the coma — a diffuse cloud around the nucleus."),
    q(13, "What is a 'meteoroid'?",
      [("A small rock or particle in space, before it enters Earth's atmosphere", True), ("A meteor that hits the ground", False), ("A type of asteroid", False), ("A piece of the Moon", False)],
      "A meteoroid is defined as a small body (from dust-grain to ~1 m) traveling through space."),
    q(14, "What is the 'Oort Cloud'?",
      [("A hypothetical spherical shell of icy bodies surrounding the solar system at ~50,000 AU", True), ("A visible cloud near Jupiter", False), ("A type of nebula", False), ("A cloud on Mars", False)],
      "The Oort Cloud is theorized to contain trillions of icy objects at the outermost boundary of the Sun's gravitational influence."),
    q(15, "What is 'sublimation' in comet science?",
      [("The transition of ice directly to gas without passing through a liquid phase", True), ("The melting of ice into water", False), ("The freezing of gas", False), ("The combustion of a comet", False)],
      "In the vacuum of space, comet ices sublimate (go directly from solid to gas) when heated by the Sun, forming the coma and tails."),
    q(16, "What is a 'bolide'?",
      [("An extremely bright meteor, often exploding in the atmosphere (fireball)", True), ("A type of asteroid", False), ("A volcanic eruption on a moon", False), ("A comet fragment", False)],
      "A bolide is a very bright fireball meteor, sometimes producing sonic booms and fragmenting explosively."),
    q(17, "What is a 'meteor shower radiant'?",
      [("The point in the sky from which shower meteors appear to originate", True), ("The brightest meteor in a shower", False), ("The comet that causes the shower", False), ("The time of peak activity", False)],
      "Due to perspective, parallel meteor trails seem to radiate from one point — the radiant. Showers are named for the constellation containing this point."),
    q(18, "What is 'outgassing' in comets?",
      [("The release of gas from a comet's nucleus as ices sublimate near the Sun", True), ("Gas produced by a comet's engine", False), ("Gas trapped inside meteorites", False), ("The exhaust from a rocket", False)],
      "Outgassing produces jets of gas from a comet's nucleus, driving the formation of the coma and tails."),
    q(19, "What is 'perihelion' for a comet?",
      [("The point in its orbit closest to the Sun, where comets are most active", True), ("The farthest point from the Sun", False), ("When a comet splits apart", False), ("The comet's birthplace", False)],
      "At perihelion, a comet receives maximum solar heating, producing the most spectacular coma and tail."),
    q(20, "What is a 'sungrazing comet'?",
      [("A comet that passes extremely close to the Sun, sometimes within the corona", True), ("A comet that orbits inside Mercury", False), ("A comet made of solar material", False), ("A comet that hits the Sun", False)],
      "Sungrazing comets pass within a few solar radii of the Sun; many disintegrate due to extreme heat and tidal forces."),
    # Scenario (21-30)
    q(21, "You observe a comet in the evening sky with its tail pointing upward (away from the horizon where the Sun set). Why does the tail point this way?",
      [("The tail always points away from the Sun, so after sunset it points upward/away from the Sun below the horizon", True), ("Wind blows the tail upward", False), ("Earth's gravity pulls the tail up", False), ("The comet is moving upward", False)],
      "Solar radiation and wind always push comet tails anti-sunward, so the tail points away from the direction of the Sun."),
    q(22, "In February 2013, a ~20-meter asteroid exploded over Chelyabinsk, Russia, injuring over 1,500 people. Why wasn't it detected in advance?",
      [("It approached from the Sun's direction, making it invisible to ground-based surveys", True), ("It was too far away to see", False), ("Russia doesn't have telescopes", False), ("It appeared overnight", False)],
      "The Chelyabinsk meteor came from the Sun's direction, where the Sun's glare prevents detection — a known blind spot."),
    q(23, "A comet is observed to have a straight, blue ion tail and a broader, curved yellowish dust tail. What causes the difference?",
      [("The ion tail is pushed by solar wind (straight); the dust tail is pushed by radiation pressure and curves due to orbital motion", True), ("One tail is hotter than the other", False), ("The blue tail reflects the sky", False), ("The yellow tail is from sulfur", False)],
      "Solar wind pushes ions straight back at high speed; heavier dust particles lag behind, curving with the comet's orbital motion."),
    q(24, "65 million years ago, an asteroid impact contributed to the extinction of the dinosaurs. What evidence supports this?",
      [("A worldwide layer of iridium (rare on Earth, common in asteroids) at the K-Pg boundary, plus the Chicxulub crater", True), ("Dinosaur fossils show burn marks", False), ("The Moon has a matching crater", False), ("Volcanoes were more active then", False)],
      "The iridium anomaly and the 180-km Chicxulub crater in Mexico provide strong evidence for the impact hypothesis."),
    q(25, "A scientist argues that comets delivered much of Earth's water. What supports this idea?",
      [("Some comets have water ice with hydrogen isotope ratios similar to Earth's oceans", True), ("Comets are pure liquid water", False), ("Earth has no other source of water", False), ("Comets orbit through Earth's oceans", False)],
      "Measurements of deuterium/hydrogen ratios in some comets match Earth's ocean water, supporting cometary delivery."),
    q(26, "You see a bright meteor during the Geminid shower in December. Unlike most showers, the Geminids come from an asteroid (3200 Phaethon), not a comet. How is this possible?",
      [("Phaethon may be an extinct comet or a rocky body that sheds particles due to thermal stress near the Sun", True), ("Asteroids always produce meteor showers", False), ("It's actually a comet disguised as an asteroid", False), ("The Geminids come from the Moon", False)],
      "Phaethon is likely a 'rock comet' — a body that sheds particles through thermal fracturing during its close solar passes."),
    q(27, "Rosetta mission orbited Comet 67P and landed the Philae probe on its surface. It found organic molecules. Why is this important?",
      [("It suggests comets could have delivered organic building blocks of life to early Earth", True), ("It proves life exists on comets", False), ("It means comets are alive", False), ("It has no scientific significance", False)],
      "Finding amino acids and other organics on 67P supports the idea that comets seeded early Earth with prebiotic molecules."),
    q(28, "A comet's nucleus is only a few kilometers wide, yet its coma can be larger than Jupiter. How?",
      [("Outgassing jets release gas that expands freely in the vacuum of space, forming an enormous diffuse cloud", True), ("The nucleus grows as it approaches the Sun", False), ("The coma is solid", False), ("Sunlight makes the nucleus look bigger", False)],
      "In space's near-vacuum, sublimated gases expand without resistance, creating a coma that can exceed 100,000 km across."),
    q(29, "If a large comet were headed for Earth, what method could potentially deflect it?",
      [("Sending a spacecraft to land on it and use thrusters, or a gravity tractor, changing its orbit years in advance", True), ("Blowing it up with a nuclear bomb at the last minute", False), ("Building a giant shield", False), ("Ignoring it — comets always miss", False)],
      "With enough lead time, gentle nudges (ion engines, gravity tractor) can accumulate into significant orbit changes. Blowing up a comet would create dangerous fragments."),
    q(30, "The Tunguska event of 1908 flattened 2,000 km² of Siberian forest with no crater. Scientists believe it was:",
      [("An asteroid or comet fragment that exploded in the atmosphere (airburst) before reaching the ground", True), ("A volcanic eruption", False), ("A lightning strike", False), ("An earthquake", False)],
      "The Tunguska event was an atmospheric airburst — the body disintegrated and released energy (~15 megatons TNT) above the surface."),
]
write_quiz("Lesson3.5_Quiz.json", 3, "3.5", "Comets & Meteoroids", L35)

# ============================================================
# Lesson 3.6: Planetary Atmospheres
# ============================================================
L36 = [
    q(1, "Earth's atmosphere is primarily composed of:",
      [("Nitrogen (~78%) and oxygen (~21%)", True), ("Oxygen (~78%) and nitrogen (~21%)", False), ("Carbon dioxide (~96%)", False), ("Hydrogen and helium", False)],
      "Earth's atmosphere is about 78% nitrogen (N₂) and 21% oxygen (O₂), with trace amounts of other gases."),
    q(2, "Venus's atmosphere is mostly:",
      [("Carbon dioxide (~96.5%)", True), ("Nitrogen (~78%)", False), ("Oxygen (~21%)", False), ("Methane (~90%)", False)],
      "Venus has a thick CO₂ atmosphere that drives an extreme greenhouse effect, heating the surface to ~460°C."),
    q(3, "Mars's atmosphere is very thin, with surface pressure about:",
      [("1% of Earth's", True), ("50% of Earth's", False), ("Equal to Earth's", False), ("10 times Earth's", False)],
      "Mars's atmospheric pressure at the surface is about 6 mbar — roughly 0.6% of Earth's sea-level pressure."),
    q(4, "Which planet has a significant ozone layer that protects life from UV radiation?",
      [("Earth", True), ("Venus", False), ("Mars", False), ("Mercury", False)],
      "Earth's ozone (O₃) layer in the stratosphere absorbs most of the Sun's harmful ultraviolet radiation."),
    q(5, "Titan (Saturn's moon) is remarkable because it has:",
      [("A thick nitrogen atmosphere with methane rain and hydrocarbon lakes", True), ("An oxygen-rich atmosphere", False), ("A water-vapor atmosphere", False), ("No atmosphere", False)],
      "Titan has a dense nitrogen atmosphere (~1.5× Earth's surface pressure) with methane acting like water does on Earth."),
    q(6, "The primary greenhouse gas on Venus is:",
      [("Carbon dioxide", True), ("Water vapor", False), ("Methane", False), ("Ozone", False)],
      "CO₂ makes up ~96.5% of Venus's atmosphere and is responsible for its extreme greenhouse effect."),
    q(7, "Jupiter's atmosphere contains colorful bands because of:",
      [("Different chemical compounds and temperature differences at different altitudes and latitudes", True), ("Reflected light from its moons", False), ("Magnetic field lines", False), ("Surface features showing through", False)],
      "Jupiter's bands are zones (light, rising) and belts (dark, sinking) of clouds with different compositions and temperatures."),
    q(8, "Which atmospheric gas on Earth is most important for absorbing the Sun's UV radiation?",
      [("Ozone (O₃)", True), ("Carbon dioxide (CO₂)", False), ("Nitrogen (N₂)", False), ("Water vapor (H₂O)", False)],
      "The ozone layer in the stratosphere absorbs ~97-99% of the Sun's medium-frequency ultraviolet light."),
    q(9, "Mars's atmosphere is mostly:",
      [("Carbon dioxide (~95%)", True), ("Nitrogen", False), ("Oxygen", False), ("Methane", False)],
      "Mars's thin atmosphere is about 95.3% CO₂, with small amounts of nitrogen and argon."),
    q(10, "Neptune's blue color is caused by:",
      [("Methane in its atmosphere absorbing red light", True), ("Liquid water oceans", False), ("Blue clouds", False), ("Reflected light from Uranus", False)],
      "Methane (CH₄) in Neptune's upper atmosphere absorbs red wavelengths and reflects blue, giving the planet its distinctive color."),
    # Vocabulary (11-20)
    q(11, "What is the 'troposphere'?",
      [("The lowest layer of a planet's atmosphere, where weather occurs", True), ("The highest layer of the atmosphere", False), ("The region of space above the atmosphere", False), ("A tropical region of a planet", False)],
      "The troposphere extends from the surface up to about 12 km on Earth and is where nearly all weather phenomena occur."),
    q(12, "What is the 'stratosphere'?",
      [("The atmospheric layer above the troposphere, containing the ozone layer", True), ("The lowest atmospheric layer", False), ("The outermost atmospheric layer", False), ("A layer in the ocean", False)],
      "The stratosphere extends from ~12-50 km and contains the ozone layer; temperature increases with altitude due to UV absorption."),
    q(13, "What is 'atmospheric escape'?",
      [("The process by which atmospheric gases are lost to space over time", True), ("Air leaking from a spacecraft", False), ("Gases moving from the surface to the upper atmosphere", False), ("The formation of an atmosphere", False)],
      "Atmospheric escape occurs through thermal escape, solar wind stripping, and other processes — Mars lost much of its atmosphere this way."),
    q(14, "What is 'escape velocity' in the context of atmospheres?",
      [("The minimum speed a gas molecule needs to escape a planet's gravity", True), ("The speed of wind in the atmosphere", False), ("The speed at which an atmosphere forms", False), ("The speed of a rocket leaving a planet", False)],
      "If gas molecules gain enough thermal speed to exceed escape velocity, they leave the planet permanently — lighter molecules escape more easily."),
    q(15, "What is 'atmospheric pressure'?",
      [("The force exerted by the weight of atmospheric gases on a surface", True), ("The speed of atmospheric winds", False), ("The temperature of the atmosphere", False), ("The amount of oxygen in the air", False)],
      "Atmospheric pressure at Earth's surface averages ~101.3 kPa (1 atm), created by the weight of the atmosphere above."),
    q(16, "What is an 'exosphere'?",
      [("The outermost layer of a planet's atmosphere, where gas molecules can escape to space", True), ("The innermost atmospheric layer", False), ("An atmosphere on an exoplanet", False), ("A layer of ozone", False)],
      "The exosphere is where the atmosphere is so thin that molecules can travel without collisions and potentially escape."),
    q(17, "What is 'adiabatic lapse rate'?",
      [("The rate at which temperature decreases with altitude in a rising air parcel", True), ("The rate at which a planet cools over time", False), ("The speed of wind change with altitude", False), ("The increase of pressure with depth", False)],
      "The adiabatic lapse rate is typically ~6.5°C/km on Earth — rising air expands and cools at this predictable rate."),
    q(18, "What is 'thermal inversion'?",
      [("A layer where temperature increases with altitude, trapping pollutants and weather below", True), ("When a planet's temperature drops to zero", False), ("When the atmosphere gets hotter at night", False), ("The warmest day of the year", False)],
      "Temperature inversions occur when warm air sits above cooler air, preventing vertical mixing — common in the stratosphere."),
    q(19, "What is 'sputtering' in atmospheric science?",
      [("Atmospheric atoms being knocked away by energetic particles (like solar wind ions)", True), ("Volcanic eruptions releasing gas", False), ("Rapid evaporation of oceans", False), ("Wind erosion of rocks", False)],
      "Sputtering occurs when high-energy solar wind particles impact atmospheric atoms, giving them enough energy to escape."),
    q(20, "What is 'Rayleigh scattering'?",
      [("The scattering of light by particles much smaller than the wavelength, responsible for blue skies", True), ("The reflection of light off water", False), ("The bending of light by gravity", False), ("The absorption of light by clouds", False)],
      "Rayleigh scattering preferentially scatters shorter (blue) wavelengths of light, making Earth's sky appear blue."),
    # Scenario (21-30)
    q(21, "Venus and Mars both have CO₂-dominated atmospheres, yet Venus is incredibly hot while Mars is cold. What makes the key difference?",
      [("Venus's atmosphere is ~100× thicker than Mars's, trapping far more heat via the greenhouse effect", True), ("Venus has more volcanoes", False), ("Mars has ice caps that cool it", False), ("Mars is closer to Jupiter", False)],
      "Venus's surface pressure is ~92 atm vs Mars's ~0.006 atm — the massive atmospheric density creates Venus's extreme greenhouse."),
    q(22, "Earth is slowly losing hydrogen to space. Why doesn't this worry scientists about losing our atmosphere?",
      [("Hydrogen is very light and escapes easily, but heavier gases like N₂ and O₂ are too massive to escape at Earth's temperatures", True), ("Earth doesn't lose any gases", False), ("New hydrogen is created constantly", False), ("The Moon prevents gas loss", False)],
      "At Earth's temperatures, heavy molecules (N₂, O₂) don't reach escape velocity, so only the lightest gases (H, He) slowly leak away."),
    q(23, "Titan's atmosphere is denser than Earth's despite Titan being much smaller. How is this possible?",
      [("Titan is very cold (-179°C), so gas molecules move slowly and are easier to retain, and Saturn's distance from the Sun reduces solar wind stripping", True), ("Titan has stronger gravity than Earth", False), ("Saturn provides extra atmosphere", False), ("Titan generates its own gas", False)],
      "Titan's extremely low temperature means gas molecules move slowly, allowing even its modest gravity to retain a thick atmosphere."),
    q(24, "Mars has seasonal dust storms that can engulf the entire planet. How does this affect surface temperature?",
      [("Dust absorbs sunlight and warms the upper atmosphere but blocks sunlight from reaching the surface, cooling it", True), ("It always warms the surface", False), ("Dust storms have no temperature effect", False), ("It makes Mars wetter", False)],
      "Global dust storms create a complex effect: warming the upper atmosphere while cooling the surface by blocking incoming sunlight."),
    q(25, "An exoplanet is found with a thick hydrogen-helium atmosphere but orbiting in its star's habitable zone. Could it support life as we know it?",
      [("Unlikely on the surface — extreme pressure and lack of oxygen would make conditions inhospitable for Earth-like life", True), ("Yes — any planet in the habitable zone has life", False), ("Yes — hydrogen is fuel for life", False), ("No — because there's no nitrogen", False)],
      "While in the habitable zone, a thick H₂/He atmosphere creates extreme surface pressures and no free oxygen, hostile to life as we know it."),
    q(26, "The discovery that Earth's ozone layer was being depleted by CFCs led to the 1987 Montreal Protocol. What lesson does this hold for planetary atmospheres?",
      [("Human activities can alter atmospheric composition, and international action can reverse the damage", True), ("Ozone naturally disappears and returns", False), ("Only Earth has ozone", False), ("The Montreal Protocol banned all chemicals", False)],
      "The ozone crisis showed how fragile atmospheres are and how policy interventions can protect vital atmospheric components."),
    q(27, "Uranus and Neptune appear blue-green. If methane absorbs red light, what color would a planet appear if its atmosphere absorbed blue light instead?",
      [("It would appear reddish or orange", True), ("It would appear green", False), ("It would appear white", False), ("It would be invisible", False)],
      "If blue light is absorbed, the remaining reflected light would be dominated by longer wavelengths — red and orange."),
    q(28, "Early Earth's atmosphere had little to no oxygen. What changed?",
      [("Cyanobacteria evolved photosynthesis, gradually producing the oxygen we have today (the Great Oxygenation Event)", True), ("Oxygen was delivered by comets", False), ("The Sun started producing oxygen", False), ("Volcanos released oxygen", False)],
      "The Great Oxygenation Event (~2.4 Ga) was caused by photosynthetic cyanobacteria releasing O₂, transforming Earth's atmosphere."),
    q(29, "A planet with no atmosphere would have extreme day-night temperature differences. Mercury shows this effect. What are its temperature extremes?",
      [("About 430°C during the day and -180°C at night", True), ("About 100°C day and 0°C night", False), ("About 0°C day and -50°C night", False), ("No temperature variation", False)],
      "Without an atmosphere to retain or redistribute heat, Mercury experiences ~610°C temperature swings between day and night."),
    q(30, "Scientists studying Venus suggest it may have once had liquid water oceans. If so, what likely triggered the loss of water?",
      [("A runaway greenhouse effect evaporated the oceans, and UV radiation then split water vapor into hydrogen (which escaped) and oxygen", True), ("Venus's water was absorbed by rocks", False), ("The Moon stole Venus's water", False), ("Venus never had water", False)],
      "As temperatures rose, water evaporated, UV photodissociation split H₂O, light hydrogen escaped to space, and oxygen reacted with surface rocks."),
]
write_quiz("Lesson3.6_Quiz.json", 3, "3.6", "Planetary Atmospheres", L36)

# ============================================================
# Lesson 3.7: Case Studies in Space Exploration
# ============================================================
L37 = [
    q(1, "The first successful flyby of another planet was:",
      [("Mariner 2 to Venus in 1962", True), ("Voyager 1 to Jupiter in 1979", False), ("Apollo 11 to the Moon in 1969", False), ("Pioneer 10 to Mars in 1971", False)],
      "Mariner 2 passed by Venus on December 14, 1962, confirming its extreme surface temperatures."),
    q(2, "The Voyager missions revealed active volcanoes on which moon?",
      [("Io (Jupiter's moon)", True), ("Europa", False), ("Titan", False), ("Enceladus", False)],
      "Voyager 1's 1979 flyby of Jupiter discovered active volcanic eruptions on Io — the first active extraterrestrial volcanoes found."),
    q(3, "The Cassini-Huygens mission primarily studied:",
      [("Saturn and its moons", True), ("Jupiter and its rings", False), ("Mars and its poles", False), ("Mercury and its craters", False)],
      "Cassini orbited Saturn from 2004-2017 while the Huygens probe landed on Titan in 2005."),
    q(4, "The Mars rovers Curiosity and Perseverance are searching for:",
      [("Signs of past habitability and biosignatures", True), ("Gold and diamonds", False), ("Alien cities", False), ("Water for drinking", False)],
      "Both rovers analyze rocks, soil, and atmosphere for evidence that Mars once had conditions suitable for microbial life."),
    q(5, "Which spacecraft was the first to orbit an outer planet?",
      [("Galileo (Jupiter, 1995)", True), ("Voyager 1", False), ("Pioneer 10", False), ("New Horizons", False)],
      "Galileo entered Jupiter orbit in December 1995, becoming the first spacecraft to orbit a gas giant."),
    q(6, "The Hubble Space Telescope orbits:",
      [("Earth, in low Earth orbit", True), ("The Sun", False), ("The Moon", False), ("Mars", False)],
      "Hubble has been in low Earth orbit (~547 km) since 1990, providing groundbreaking observations across the universe."),
    q(7, "Viking 1 in 1976 was the first spacecraft to:",
      [("Successfully land on Mars and send back surface photos", True), ("Land on Venus", False), ("Orbit Jupiter", False), ("Visit Pluto", False)],
      "Viking 1 landed on Mars on July 20, 1976, sending back the first photos from the Martian surface."),
    q(8, "The Juno mission is studying Jupiter's:",
      [("Internal structure, magnetic field, and atmosphere", True), ("Rings only", False), ("Moons only", False), ("Surface geology", False)],
      "Juno has been orbiting Jupiter since 2016, using instruments to probe beneath the cloud tops."),
    q(9, "Which probe was the first human-made object to enter interstellar space?",
      [("Voyager 1", True), ("Voyager 2", False), ("Pioneer 10", False), ("New Horizons", False)],
      "Voyager 1 crossed the heliopause into interstellar space in August 2012, confirmed by its plasma instruments."),
    q(10, "The James Webb Space Telescope is positioned at:",
      [("The Sun-Earth L2 Lagrange point, about 1.5 million km from Earth", True), ("Low Earth orbit like Hubble", False), ("On the Moon", False), ("Orbiting Mars", False)],
      "JWST orbits the L2 point, always keeping the Sun and Earth behind it, ideal for infrared observations."),
    # Vocabulary (11-20)
    q(11, "What is a 'flyby' mission?",
      [("A spacecraft that passes close to a body without entering orbit, gathering data during the encounter", True), ("A mission that flies above a planet's atmosphere", False), ("A plane flight over a launch site", False), ("A canceled mission", False)],
      "Flyby missions use gravity assists and pass through a target's vicinity, collecting data during the brief encounter."),
    q(12, "What is an 'orbiter'?",
      [("A spacecraft designed to enter and maintain orbit around a celestial body", True), ("A satellite that stays on the ground", False), ("A type of telescope", False), ("A rocket booster", False)],
      "Orbiters like Cassini and Juno circle their targets for extended periods, providing long-term study."),
    q(13, "What is a 'lander'?",
      [("A spacecraft designed to touch down on the surface of a celestial body", True), ("A spacecraft that only orbits", False), ("A type of telescope", False), ("A parachute", False)],
      "Landers (like Viking, InSight, Huygens) are designed to survive touchdown and operate on a body's surface."),
    q(14, "What is a 'rover'?",
      [("A mobile vehicle designed to move across the surface of a celestial body", True), ("A type of satellite", False), ("A space telescope", False), ("A rocket engine", False)],
      "Rovers (Curiosity, Perseverance, Zhurong) can traverse terrain, reaching multiple study sites."),
    q(15, "What is a 'gravity assist'?",
      [("Using a planet's gravity to change a spacecraft's speed and direction without using fuel", True), ("A helper rocket on a spacecraft", False), ("The force that keeps satellites in orbit", False), ("A type of engine", False)],
      "Gravity assists (slingshots) allow spacecraft to gain or lose speed by flying close to a planet, conserving fuel."),
    q(16, "What is 'aerobraking'?",
      [("Using a planet's atmosphere to gradually slow down and reduce orbit altitude", True), ("Braking with rocket engines", False), ("Stopping in midair", False), ("Using solar wind to slow down", False)],
      "Aerobraking passes through the upper atmosphere to create drag, gradually lowering and circularizing an orbit."),
    q(17, "What is a 'sample return mission'?",
      [("A mission that collects material from another world and brings it back to Earth for analysis", True), ("A mission that tests soil on location", False), ("Returning a broken spacecraft to Earth", False), ("A mission that returns astronauts", False)],
      "Sample return missions (e.g., OSIRIS-REx, Stardust, Hayabusa) bring extraterrestrial material to Earth's laboratories."),
    q(18, "What is 'telemetry'?",
      [("The transmission of data from a spacecraft to ground stations", True), ("The study of distant planets", False), ("A type of telescope", False), ("The temperature of space", False)],
      "Telemetry provides mission controllers with spacecraft status, science data, and health information via radio signals."),
    q(19, "What is the 'Deep Space Network' (DSN)?",
      [("NASA's worldwide system of large radio antennas for communicating with interplanetary spacecraft", True), ("A social media network for astronomers", False), ("A cable TV channel about space", False), ("A satellite internet service", False)],
      "The DSN has three complexes (Goldstone, Madrid, Canberra) spaced ~120° apart to maintain 24/7 contact with distant missions."),
    q(20, "What is 'in situ' analysis?",
      [("Measurements and experiments performed at the site, on the surface of another world", True), ("Analysis done back on Earth", False), ("Analysis from orbit only", False), ("Analysis done in a laboratory", False)],
      "In situ (Latin: 'in place') analysis means studying materials right where they are, rather than returning samples."),
    # Scenario (21-30)
    q(21, "Voyager 1 and 2 carry golden records with sounds and images of Earth. Why was this included?",
      [("As a message to any extraterrestrial civilization that might find the spacecraft", True), ("For entertainment during the flight", False), ("To test sound in space", False), ("To record data about space", False)],
      "Carl Sagan led the effort to include a cultural snapshot of Earth, understanding the craft might travel for millions of years."),
    q(22, "The Huygens probe transmitted data for only ~72 minutes after landing on Titan. Why so briefly?",
      [("Battery life was limited and signal relay through Cassini was only possible for a short window", True), ("Titan's atmosphere crushed it", False), ("The data was deleted", False), ("72 minutes is standard for all missions", False)],
      "Huygens had limited battery power and could only transmit while Cassini was overhead to relay the signal to Earth."),
    q(23, "Mars has a 3-22 minute one-way communication delay with Earth. How does this affect rover operations?",
      [("Rovers must operate semi-autonomously — commands are planned in advance since real-time control is impossible", True), ("It doesn't affect anything", False), ("Rovers only work when delay is short", False), ("Operators shout louder to compensate", False)],
      "Communication delay means drivers pre-plan each day's movements and the rover must make some decisions autonomously."),
    q(24, "Perseverance carried a small helicopter called Ingenuity. Why was flying on Mars challenging?",
      [("Mars's atmosphere is ~1% of Earth's density, requiring extremely fast rotor speeds for lift", True), ("Mars has too much wind", False), ("Mars has no gravity", False), ("Helicopters can't fly in CO₂", False)],
      "Ingenuity's rotors spin at ~2,400 RPM (vs ~500 for Earth helicopters) to generate lift in Mars's thin atmosphere."),
    q(25, "JWST observes in infrared rather than visible light like Hubble. Why infrared?",
      [("Infrared can see through dust clouds, detect cool objects, and observe highly redshifted light from the earliest galaxies", True), ("Infrared is brighter", False), ("Visible light doesn't exist in space", False), ("Infrared cameras are cheaper", False)],
      "Infrared penetrates dust, reveals forming stars and planets, and captures light from the most distant (redshifted) objects in the universe."),
    q(26, "The Cassini mission ended by intentionally diving into Saturn's atmosphere. Why?",
      [("To prevent possible contamination of potentially habitable moons (Enceladus, Titan) when fuel ran out", True), ("The mission failed", False), ("They wanted to study Saturn's core", False), ("It was an accident", False)],
      "Planetary protection protocols required destroying Cassini rather than risking it crashing into and contaminating a potentially life-bearing moon."),
    q(27, "Pioneer 10 and 11 carry plaques showing humans, the Sun's position, and Earth's location. Scientists later realized a potential problem. What was it?",
      [("The plaque might give hostile aliens our location — a concern raised about messaging extraterrestrial intelligence", True), ("The plaque was too small to read", False), ("The plaque was inaccurate", False), ("The plaque melted", False)],
      "Some scientists worried that broadcasting humanity's location could be dangerous if contacted by hostile intelligence."),
    q(28, "The New Horizons flyby of Pluto in 2015 took over 16 months to transmit all the data back to Earth. Why so long?",
      [("At Pluto's enormous distance, the signal is very weak and data rates are extremely low (~1-2 kilobits per second)", True), ("The spacecraft had limited storage", False), ("They had to wait for good weather on Earth", False), ("The data was classified", False)],
      "At ~33 AU away, New Horizons transmitted at very low data rates due to the faint signal reaching Earth."),
    q(29, "India's Chandrayaan mission discovered water molecules on the Moon's surface. Why was this unexpected?",
      [("The Moon was thought to be completely dry — water on the surface challenged decades of understanding", True), ("We always knew there was water there", False), ("India was the first country to the Moon", False), ("Water is common on all moons", False)],
      "Before Chandrayaan and other missions confirmed it, the Moon was believed to be anhydrous (completely waterless)."),
    q(30, "SpaceX's Starship is being developed for Mars missions. What makes the reusable design important for Mars exploration?",
      [("Reusability dramatically reduces launch costs, making frequent Mars missions economically feasible", True), ("Reusable rockets are faster", False), ("Reusable rockets are safer", False), ("NASA requires reusable rockets", False)],
      "Reuse reduces per-launch cost by orders of magnitude, essential for the many launches needed to transport humans and cargo to Mars."),
]
write_quiz("Lesson3.7_Quiz.json", 3, "3.7", "Case Studies in Space Exploration", L37)

# ============================================================
# Lesson 3.8: AP Prep: Kepler's Laws
# ============================================================
L38 = [
    q(1, "Kepler's First Law states that planetary orbits are:",
      [("Ellipses with the Sun at one focus", True), ("Perfect circles with the Sun at the center", False), ("Parabolas with the Sun at the vertex", False), ("Straight lines through the Sun", False)],
      "Kepler's First Law: The orbit of a planet is an ellipse with the Sun at one of the two foci."),
    q(2, "Kepler's Second Law (Law of Equal Areas) means that a planet:",
      [("Moves faster when closer to the Sun and slower when farther", True), ("Moves at constant speed", False), ("Moves faster when farther from the Sun", False), ("Always faces the Sun", False)],
      "A line from planet to Sun sweeps equal areas in equal times — the planet must move faster at perihelion."),
    q(3, "In Kepler's Third Law, T² = ka³, what does 'a' represent?",
      [("The semi-major axis of the orbit", True), ("The acceleration of the planet", False), ("The area of the orbit", False), ("The planet's mass", False)],
      "In T² = a³ (using AU and years), 'a' is the semi-major axis — half the longest diameter of the ellipse."),
    q(4, "An ellipse has two special points called:",
      [("Foci", True), ("Centers", False), ("Vertices", False), ("Poles", False)],
      "The two foci (singular: focus) are the defining points of an ellipse. The sum of distances from any point on the ellipse to both foci is constant."),
    q(5, "For a planet with a semi-major axis of 9 AU, what is its orbital period (using T² = a³)?",
      [("27 years", True), ("9 years", False), ("81 years", False), ("3 years", False)],
      "T² = 9³ = 729, so T = √729 = 27 years."),
    q(6, "Which planet's orbit was Kepler primarily analyzing to derive his laws?",
      [("Mars", True), ("Venus", False), ("Earth", False), ("Jupiter", False)],
      "Kepler used Tycho Brahe's precise observations of Mars to deduce that its orbit was elliptical, not circular."),
    q(7, "In an elliptical orbit, the point closest to the Sun is called:",
      [("Perihelion", True), ("Aphelion", False), ("Perigee", False), ("Apogee", False)],
      "Perihelion is the closest point to the Sun; aphelion is the farthest."),
    q(8, "Kepler's laws were later explained by Newton using:",
      [("The law of universal gravitation and calculus", True), ("Magnetism", False), ("Quantum mechanics", False), ("Thermodynamics", False)],
      "Newton showed that his gravitational law F = GMm/r² naturally produces elliptical orbits as described by Kepler."),
    q(9, "The eccentricity of a perfect circle is:",
      [("0", True), ("1", False), ("0.5", False), ("Infinity", False)],
      "Eccentricity = 0 means a perfect circle; as e approaches 1, the ellipse becomes increasingly elongated."),
    q(10, "When a planet is at aphelion, it moves at its:",
      [("Slowest speed", True), ("Fastest speed", False), ("Average speed", False), ("Escape velocity", False)],
      "Kepler's Second Law: at aphelion (farthest), the planet moves slowest; at perihelion (nearest), fastest."),
    # Vocabulary (11-20)
    q(11, "What is an 'ellipse'?",
      [("A closed oval curve defined as the set of points where the sum of distances to two foci is constant", True), ("A perfect circle", False), ("An open curve like a parabola", False), ("A straight line", False)],
      "An ellipse is the geometric shape of all planetary orbits — a stretched circle with two focal points."),
    q(12, "What is a 'focus' of an ellipse?",
      [("One of two fixed points inside the ellipse; the Sun sits at one focus in Kepler's First Law", True), ("The center of the ellipse", False), ("A point on the ellipse's edge", False), ("The widest point of the ellipse", False)],
      "The two foci define the ellipse's shape. In a planetary orbit, the star occupies one focus; the other is empty."),
    q(13, "What is 'eccentricity'?",
      [("A number between 0 and 1 that measures how elongated an ellipse is", True), ("The tilt of an orbit", False), ("The size of an orbit", False), ("The speed of a planet", False)],
      "Eccentricity e = c/a, where c is the distance from center to focus and a is the semi-major axis."),
    q(14, "What is 'aphelion'?",
      [("The point in a planet's orbit farthest from the Sun", True), ("The closest point to the Sun", False), ("The center of the orbit", False), ("The point of maximum speed", False)],
      "At aphelion, a planet is at its maximum distance from the Sun and moves at its minimum orbital speed."),
    q(15, "What is the 'areal velocity'?",
      [("The rate at which a line from the Sun to a planet sweeps out area — constant by Kepler's Second Law", True), ("The speed of a planet", False), ("The area of an orbit", False), ("The density of a planet", False)],
      "Kepler's Second Law states that areal velocity (dA/dt) is constant throughout the orbit."),
    q(16, "What is the 'harmonic law'?",
      [("Another name for Kepler's Third Law: T² ∝ a³", True), ("The law of musical instruments", False), ("Newton's first law", False), ("The law of electromagnetic radiation", False)],
      "The harmonic law relates orbital period (T) to semi-major axis (a), providing a universal relationship."),
    q(17, "What is 'angular momentum' in orbit?",
      [("L = mvr for circular orbits; it is conserved, causing the equal-areas behavior in Kepler's Second Law", True), ("The angle of the orbit", False), ("The rotation rate of a planet", False), ("The tilt of an axis", False)],
      "Conservation of angular momentum in a central force field (gravity) directly produces Kepler's Second Law."),
    q(18, "What is a 'conic section'?",
      [("A curve formed by intersecting a cone with a plane — ellipse, parabola, hyperbola, or circle", True), ("A section of a cone used in cooking", False), ("A straight line through a circle", False), ("A type of telescope mirror", False)],
      "Orbits under gravity are always conic sections. Bound orbits are ellipses (or circles); unbound paths are parabolas or hyperbolas."),
    q(19, "What is 'orbital mechanics'?",
      [("The branch of physics studying the motion of objects under gravitational influence", True), ("Repairing satellites in orbit", False), ("Machine tools used in space", False), ("The construction of rockets", False)],
      "Orbital mechanics (celestial mechanics) uses Kepler's and Newton's laws to predict and plan spacecraft trajectories."),
    q(20, "What is a 'Hohmann transfer orbit'?",
      [("An energy-efficient elliptical orbit used to transfer between two circular orbits", True), ("A circular orbit at constant altitude", False), ("A hyperbolic escape trajectory", False), ("An orbit that goes through the Sun", False)],
      "A Hohmann transfer uses two engine burns to move between orbits along an ellipse tangent to both — the most fuel-efficient two-impulse method."),
    # Scenario (21-30)
    q(21, "A student measures that a planet's period is 8 years. Using Kepler's Third Law, what is its semi-major axis?",
      [("4 AU (since a = ∛(T²) = ∛(64) = 4)", True), ("8 AU", False), ("2 AU", False), ("64 AU", False)],
      "T² = a³ → 8² = 64 → a = ∛64 = 4 AU."),
    q(22, "An asteroid has an eccentricity of 0.9. Another has e = 0.1. Which orbit is more elongated?",
      [("The one with e = 0.9 — higher eccentricity means a more elongated orbit", True), ("The one with e = 0.1", False), ("They are equally elongated", False), ("Eccentricity doesn't affect shape", False)],
      "Eccentricity near 0 is nearly circular; near 1 is highly elongated. The e = 0.9 orbit is much more stretched."),
    q(23, "Using Kepler's Second Law, if Earth is at perihelion in January, how does its speed compare to July (aphelion)?",
      [("Earth moves faster in January (perihelion) than in July (aphelion)", True), ("Earth moves slower in January", False), ("Earth's speed doesn't change", False), ("Earth moves fastest in March", False)],
      "Kepler's Second Law: equal areas in equal times means faster speed at perihelion (closer) and slower at aphelion (farther)."),
    q(24, "A spacecraft enters orbit around Mars. Its orbit is a very elongated ellipse. An engineer wants to convert it to a nearly circular orbit. What must be done?",
      [("Fire engines at the periapsis to add velocity, raising the apoapsis and reducing eccentricity", True), ("Turn off the engines entirely", False), ("Use Kepler's First Law to make it circular automatically", False), ("Wait for gravity to circularize it", False)],
      "Adding speed at periapsis raises the opposite side of the orbit. Multiple burns can gradually circularize the orbit."),
    q(25, "Two planets orbit the same star. Planet A is at 1 AU with period 1 year. Planet B is at 8 AU. What is Planet B's period?",
      [("About 22.6 years (T = √(8³) = √512 ≈ 22.6)", True), ("8 years", False), ("64 years", False), ("16 years", False)],
      "T² = a³ = 8³ = 512, so T = √512 ≈ 22.6 years."),
    q(26, "An astronomer studying a binary star system uses a modified form of Kepler's Third Law to determine the stars' masses. How is this possible?",
      [("Newton's generalized form includes both masses: T² = (4π²/G(M₁+M₂))a³, so measuring T and a gives M₁+M₂", True), ("Kepler's law doesn't work for binary stars", False), ("You can only measure distance, not mass", False), ("Binary stars don't follow Kepler's laws", False)],
      "Newton's version includes the total mass, so measuring the orbital period and semi-major axis reveals the combined stellar masses."),
    q(27, "Halley's Comet has a semi-major axis of about 17.8 AU. Verify that Kepler's Third Law predicts its ~76-year period.",
      [("T² = 17.8³ ≈ 5640, T = √5640 ≈ 75.1 years — matches well!", True), ("T² = 17.8, T ≈ 4.2 years", False), ("T = 17.8 years", False), ("The law doesn't work for comets", False)],
      "17.8³ ≈ 5640, √5640 ≈ 75.1 years, very close to the observed ~76 years. Kepler's Third Law works for any Sun-orbiting body."),
    q(28, "A hypothetical planet orbits at 0.5 AU. Is its period more or less than 1 year?",
      [("Less — it's closer to the Sun so it orbits faster (T² = 0.5³ = 0.125, T ≈ 0.35 years ≈ 129 days)", True), ("More — it takes longer because it's smaller", False), ("Exactly 1 year", False), ("Exactly 0.5 years", False)],
      "T² = 0.5³ = 0.125, so T = √0.125 ≈ 0.354 years ≈ 129 days."),
    q(29, "Kepler's laws describe HOW planets move but not WHY. Who provided the WHY?",
      [("Newton, with his theory of universal gravitation", True), ("Galileo, with his telescope", False), ("Einstein, with relativity", False), ("Copernicus, with heliocentrism", False)],
      "Newton's gravitational theory explained the physical cause behind Kepler's empirical laws."),
    q(30, "A spacecraft in a circular orbit at 2 AU around the Sun has a speed of ~21 km/s. Using v ∝ 1/√r, estimate the speed at 8 AU.",
      [("About 10.5 km/s (21/√4 = 21/2 = 10.5)", True), ("About 5.25 km/s", False), ("About 42 km/s", False), ("About 21 km/s", False)],
      "The ratio of distances is 8/2 = 4, so v₂ = v₁/√(r₂/r₁) = 21/√4 = 21/2 = 10.5 km/s."),
]
write_quiz("Lesson3.8_Quiz.json", 3, "3.8", "AP Prep: Kepler's Laws", L38)

print("\nUnit 3 complete!")
