import json, os

def q(num, text, correct, wrong1, wrong2, wrong3, explanation):
    return {
        "question_number": num,
        "question_text": text,
        "attempted": 2,
        "data_i18n": None,
        "options": [
            {"text": correct, "is_correct": True, "data_i18n": None},
            {"text": wrong1, "is_correct": False, "data_i18n": None},
            {"text": wrong2, "is_correct": False, "data_i18n": None},
            {"text": wrong3, "is_correct": False, "data_i18n": None}
        ],
        "explanation": explanation
    }

def write_quiz(unit, lesson, title, questions):
    path = f"content_data/AstronomyLessons/Unit{unit}/Lesson{lesson}_Quiz.json"
    data = {
        "unit": unit,
        "lesson_number": lesson,
        "title": title,
        "course": "Astronomy",
        "quiz_questions": questions
    }
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  Wrote {path} ({len(questions)} questions)")

print("=== Unit 6: Galaxies & Cosmology ===")

# 6.1 Types of Galaxies
write_quiz(6, "6.1", "Types of Galaxies (Spiral, Elliptical, Irregular)", [
    q(1, "Who created the galaxy classification system known as the 'tuning fork' diagram?", "Edwin Hubble", "Albert Einstein", "Galileo Galilei", "Isaac Newton",
      "Hubble developed his classification scheme in the 1920s-30s, organizing galaxies by morphology."),
    q(2, "Spiral galaxies are characterized by:", "A central bulge with spiral arms containing gas, dust, and young stars", "No defined structure", "Only old red stars", "Being the smallest galaxies",
      "Spiral galaxies like the Milky Way have distinct arms winding outward from a central bulge."),
    q(3, "Elliptical galaxies are:", "Smooth, round to elongated systems with mostly old stars and little gas or dust", "Spiral-shaped with active star formation", "Always very small", "Full of young blue stars",
      "Elliptical galaxies range from nearly spherical (E0) to elongated (E7), dominated by old stellar populations."),
    q(4, "Irregular galaxies are:", "Galaxies without a well-defined shape, often rich in gas and actively forming stars", "Always very large", "Old and dead", "Perfectly spherical",
      "Irregular galaxies like the Large and Small Magellanic Clouds have chaotic structures, often from interactions."),
    q(5, "The Milky Way is classified as a:", "Barred spiral galaxy (SBb/SBc)", "Elliptical galaxy", "Irregular galaxy", "Lenticular galaxy",
      "The Milky Way has a central bar and spiral arms, classifying it as a barred spiral (SBb or SBc type)."),
    q(6, "Lenticular galaxies (S0) are:", "Disk-shaped galaxies with a bulge but no spiral arms, intermediate between spiral and elliptical", "Lens-shaped magnifying glasses", "The smallest galaxies", "Always blue",
      "Lenticular galaxies have used up most of their gas, so they have a disk but no ongoing spiral arm star formation."),
    q(7, "Which type of galaxy is most common in the universe?", "Dwarf galaxies (mostly dwarf irregular and dwarf elliptical)", "Giant spiral galaxies", "Giant elliptical galaxies", "Quasars",
      "Dwarf galaxies are by far the most numerous, though they're hard to detect due to their low luminosity."),
    q(8, "The Andromeda Galaxy (M31) is:", "The nearest large spiral galaxy to the Milky Way", "An irregular galaxy", "The farthest known galaxy", "A star cluster in our galaxy",
      "Andromeda is about 2.5 million light-years away and is approaching the Milky Way for a future merger."),
    q(9, "Galaxy mergers can:", "Transform spiral galaxies into elliptical galaxies", "Create new elements", "Destroy stars completely", "Have no effect on galaxy structure",
      "Major mergers disrupt spiral structures, and the resulting system often relaxes into an elliptical galaxy."),
    q(10, "The Hubble tuning fork diagram branches into:", "Normal spirals (Sa-Sd) and barred spirals (SBa-SBd)", "Hot and cold galaxies", "Large and small galaxies", "Young and old galaxies",
      "The tuning fork splits into two parallel sequences: normal spirals and barred spirals, both ranging from tightly to loosely wound."),
    # Vocabulary (11-20)
    q(11, "What is a spiral galaxy?", "A galaxy with a rotating disk of stars and gas, with spiral arms extending from a central region", "A galaxy spinning in circles", "Any galaxy that is round", "A galaxy with no stars",
      "Spiral galaxies have active star formation in their arms, with young blue stars and pink emission nebulae."),
    q(12, "What is an elliptical galaxy?", "A galaxy with a smooth, ellipsoidal shape, dominated by old stars with little gas or dust", "A galaxy with an elliptical orbit", "A flat disk galaxy", "A galaxy filled with young stars",
      "Elliptical galaxies range from giant (trillions of stars) to dwarf (millions of stars) and show little ongoing star formation."),
    q(13, "What is an irregular galaxy?", "A galaxy that lacks a regular or symmetrical structure", "A galaxy that follows no physical laws", "A perfectly round galaxy", "A galaxy that emits no light",
      "Irregular galaxies often result from gravitational interactions or are small galaxies that never developed regular form."),
    q(14, "What is a galactic bulge?", "The central, dense, roughly spherical concentration of stars in a galaxy", "A bump on a galaxy's edge", "A nebula at a galaxy's center", "A type of satellite galaxy",
      "The bulge contains primarily old stars and, in many cases, a supermassive black hole at its center."),
    q(15, "What is a spiral arm?", "A region of a spiral galaxy with higher density of stars, gas, and dust extending from the center", "A tentacle from an octopus galaxy", "A straight line of stars", "The edge of a galaxy",
      "Spiral arms are density waves where gas compresses and triggers star formation, producing bright young stars."),
    q(16, "What is a bar (in barred spiral galaxies)?", "An elongated structure of stars passing through the center of the galaxy", "A cosmic obstacle", "A dark matter structure", "An asteroidbelt",
      "The bar funnels gas inward toward the center, potentially fueling star formation and the central black hole."),
    q(17, "What is the Hubble sequence?", "The classification of galaxies by morphological type arranged in a tuning-fork diagram", "The order in which Hubble discovered galaxies", "A sequence of distances", "A timeline of the universe",
      "The Hubble sequence arranges galaxies from elliptical (left) through lenticular to spiral/barred spiral (right branches)."),
    q(18, "What is a dwarf galaxy?", "A small galaxy with a few billion stars or fewer, often orbiting a larger galaxy", "A galaxy that is slightly below average size", "A newly formed galaxy", "A galaxy with only one star",
      "Dwarf galaxies include the Magellanic Clouds and dozens of small satellites around the Milky Way."),
    q(19, "What is galaxy morphology?", "The study and classification of the shapes and structures of galaxies", "The study of galaxy colors only", "The study of galaxy sounds", "The theory of galaxy destruction",
      "Galaxy morphology helps astronomers understand the physical processes shaping galaxies, from formation to evolution."),
    q(20, "What is a starburst galaxy?", "A galaxy undergoing an exceptionally high rate of star formation", "A galaxy that exploded", "A galaxy with no stars forming", "A galaxy made entirely of gas",
      "Starburst galaxies form stars at rates 10-100× higher than normal, often triggered by interactions or mergers."),
    # Scenario (21-30)
    q(21, "The Milky Way and Andromeda are expected to collide in about 4-5 billion years. What will the result likely be?", "A larger elliptical galaxy (sometimes called 'Milkomeda')", "Both galaxies will be destroyed", "Nothing will happen", "A giant spiral galaxy",
      "Simulations show the merger will scramble both spiral structures into a giant elliptical galaxy over billions of years."),
    q(22, "An astronomer views a galaxy that is smooth, red in color, and has no visible spiral arms or blue regions. What type is it likely?", "An elliptical galaxy", "A spiral galaxy", "An irregular galaxy", "A newly forming galaxy",
      "Smooth, red color and no blue star-forming regions are hallmarks of elliptical galaxies dominated by old stars."),
    q(23, "A small galaxy passes near a large spiral, and the small galaxy becomes distorted and stretched. What is happening?", "Tidal interaction — the larger galaxy's gravity is disrupting the smaller one", "The small galaxy is exploding", "Nothing unusual", "The large galaxy is shrinking",
      "Gravitational tidal forces during close encounters can strip stars and gas from smaller galaxies."),
    q(24, "You observe a galaxy with very active star formation but no clear structure. What type might this be?", "An irregular galaxy or a starburst galaxy", "An elliptical galaxy", "A lenticular galaxy", "A dead galaxy",
      "Active star formation with chaotic structure suggests an irregular galaxy, possibly triggered by an interaction."),
    q(25, "Two spiral galaxies are in the process of merging. What would you expect to see?", "Tidal tails, enhanced star formation, and distorted structures", "Nothing unusual", "Both galaxies becoming perfectly elliptical immediately", "The galaxies passing through each other with no interaction",
      "Merging galaxies develop tidal tails, trigger starbursts, and show heavily distorted morphologies."),
    q(26, "A galaxy cluster is observed to contain mostly elliptical and lenticular galaxies near its center. What does this suggest?", "Dense environments process galaxies through interactions, stripping gas and converting spirals to earlier types", "Elliptical galaxies form only in clusters", "Spirals avoid clusters", "It's a random arrangement",
      "The morphology-density relation shows that denser environments favor elliptical and lenticular galaxies over spirals."),
    q(27, "An astronomer discovers a galaxy that has a disk but no spiral arms, and contains very little gas. It's between elliptical and spiral. What is it?", "A lenticular galaxy (S0)", "A quasar", "An irregular galaxy", "A dwarf spheroidal",
      "Lenticular galaxies bridge the gap between spirals (which have arms and gas) and ellipticals (which have neither)."),
    q(28, "The Large Magellanic Cloud is visible from the southern hemisphere. Its irregular shape may be partly due to:", "Tidal interaction with the Milky Way", "Being newly formed", "Having too many stars", "Being located too far away",
      "The LMC's structure is distorted by its gravitational interaction with the Milky Way as it orbits our galaxy."),
    q(29, "If two elliptical galaxies merge, what type of galaxy would result?", "A larger elliptical galaxy", "A spiral galaxy", "An irregular galaxy", "The galaxies would annihilate each other",
      "Elliptical + elliptical mergers produce bigger elliptical galaxies, as there's little gas to form a new disk."),
    q(30, "A barred spiral galaxy has a strong bar funneling gas inward. What effect might this have on its central region?", "Enhanced star formation and potentially feeding the central supermassive black hole", "The center becomes empty", "The bar prevents all gas movement", "Nothing — bars are purely decorative",
      "Bars efficiently transport gas inward, potentially fueling nuclear starbursts and AGN activity in the galaxy's center.")
])

# 6.2 Milky Way Structure
write_quiz(6, "6.2", "Milky Way Structure", [
    q(1, "The Milky Way has approximately how many stars?", "100–400 billion", "A few million", "About 1 trillion", "About 10,000",
      "Current estimates place the Milky Way's stellar population at 100-400 billion stars."),
    q(2, "The Sun is located in the Milky Way's:", "Orion Arm (or Orion Spur), about 26,000 light-years from the center", "Center", "Outer edge", "Above the disk",
      "We reside in a minor spiral arm roughly halfway between the center and the edge of the disk."),
    q(3, "The Milky Way's disk is approximately:", "100,000–180,000 light-years in diameter", "1,000 light-years in diameter", "1 million light-years in diameter", "10 light-years in diameter",
      "The stellar disk spans roughly 100,000-180,000 light-years, though the dark matter halo extends much farther."),
    q(4, "The Milky Way's central bar is:", "An elongated structure of stars passing through the galactic center", "A chocolate bar floating in space", "A dark cloud blocking the center", "A ring of planets",
      "The central bar is estimated to be about 27,000 light-years long, composed primarily of older, redder stars."),
    q(5, "Globular clusters in the Milky Way are found:", "In a spherical halo surrounding the galaxy, containing some of the oldest stars", "Only in spiral arms", "Only at the center", "Between galaxies",
      "Globular clusters orbit in the galactic halo and contain ancient stars (10-13 billion years old)."),
    q(6, "The galactic halo contains:", "Old stars, globular clusters, and dark matter", "Young blue stars", "Most of the galaxy's gas", "Active star-forming regions",
      "The halo is a roughly spherical region extending far beyond the disk, dominated by dark matter."),
    q(7, "The Milky Way completes one rotation at the Sun's location in about:", "225–250 million years", "1 million years", "1 billion years", "24 hours",
      "The Sun's orbital period around the galactic center (one 'galactic year') is about 225-250 million years."),
    q(8, "We cannot easily see the Milky Way's center in visible light because:", "Interstellar dust in the disk absorbs and scatters visible light", "The center is invisible", "There's nothing there", "We're too far away",
      "Dust along the galactic plane blocks visible light; infrared and radio observations can penetrate the dust."),
    q(9, "The Milky Way's thin disk is approximately:", "1,000–2,000 light-years thick", "100,000 light-years thick", "1 light-year thick", "50,000 light-years thick",
      "The thin disk containing most stars and gas is remarkably thin compared to the galaxy's diameter."),
    q(10, "The Milky Way has at least how many known satellite galaxies?", "About 50-60", "Just 2", "About 1,000", "None",
      "Dozens of satellite galaxies orbit the Milky Way, including the LMC, SMC, and many dwarf galaxies."),
    # Vocabulary (11-20)
    q(11, "What is the galactic disk?", "The flat, rotating component of the Milky Way containing most stars, gas, and dust", "A frisbee in space", "A dark matter structure", "The galaxy's core",
      "The disk is where spiral arms, star formation, and most of the visible galaxy resides."),
    q(12, "What is the galactic bulge?", "The dense, roughly spherical central region of the Milky Way", "A bump in the disk", "An empty region", "A satellite galaxy",
      "The bulge contains a mix of old and intermediate-age stars and surrounds Sagittarius A*."),
    q(13, "What is the galactic halo?", "The extended spherical region surrounding the disk, containing old stars, globular clusters, and dark matter", "A ring of light around the galaxy", "The galaxy's atmosphere", "A protective shield",
      "The halo extends hundreds of thousands of light-years and is mostly dark matter."),
    q(14, "What is the galactic center?", "The rotational center of the Milky Way, containing Sgr A* and dense stellar populations", "The center of the universe", "The middle of the galactic disk in height", "The oldest star",
      "The galactic center region is extremely dense with stars and hosts the 4-million solar mass black hole Sgr A*."),
    q(15, "What is the Orion Arm?", "The minor spiral arm of the Milky Way where our solar system is located", "A constellation", "A weapon in space", "The main spiral arm of the galaxy",
      "Also called the Orion Spur, it sits between the larger Perseus and Sagittarius arms."),
    q(16, "What is a globular cluster?", "A dense, spherical collection of hundreds of thousands to millions of old stars", "A cluster of galaxies", "A group of planets", "A type of nebula",
      "Globular clusters are ancient (10-13 Gyr) and orbit in the galactic halo; the Milky Way has about 150-200."),
    q(17, "What is the rotation curve?", "A plot showing the orbital velocity of objects at different distances from the galactic center", "A curve in the spiral arms", "The path the galaxy takes through space", "The spin of individual stars",
      "Milky Way rotation curves remain flat at large radii, providing key evidence for dark matter."),
    q(18, "What is interstellar medium (ISM)?", "The gas and dust occupying the space between stars within a galaxy", "Empty space between stars", "The surface of a star", "Air in the Milky Way",
      "The ISM includes molecular clouds, atomic hydrogen, ionized gas, and dust — the raw material for star formation."),
    q(19, "What are open clusters?", "Loose groupings of young stars found in the galactic disk", "Tight spherical clusters of old stars", "Clusters of galaxies", "Groups of black holes",
      "Open clusters contain tens to thousands of stars born from the same molecular cloud, typically found in spiral arms."),
    q(20, "What is the zone of avoidance?", "The area along the galactic plane where dust obscures distant extragalactic objects in visible light", "A region astronauts can't enter", "An empty part of the galaxy", "The Sun's exclusion zone",
      "The zone of avoidance makes it difficult to survey galaxies behind the Milky Way's dusty disk in optical wavelengths."),
    # Scenario (21-30)
    q(21, "The Milky Way's rotation curve is flat rather than declining at large radii. What does this imply?", "There is much more mass than visible matter accounts for — dark matter", "The galaxy is not rotating", "All stars orbit at the same speed regardless", "Newton's laws don't apply to galaxies",
      "Flat rotation curves require additional unseen mass; dark matter halos provide this missing gravitational pull."),
    q(22, "An astronomer wants to observe the galactic center. What wavelength should they use?", "Infrared or radio, which can penetrate interstellar dust", "Visible light", "UV light", "Gamma rays only",
      "Dust blocks visible and UV light; infrared and radio waves pass through, revealing the galactic center."),
    q(23, "Gaia maps reveal that many stars in the Milky Way's halo have different chemical compositions than disk stars. What does this suggest?", "Many halo stars were captured from smaller galaxies that merged with the Milky Way", "Halo stars formed from different elements", "Disk stars are artificial", "All stars have identical compositions",
      "Different metallicities and abundance patterns indicate distinct origins — many halo stars are from accreted dwarf galaxies."),
    q(24, "The Sagittarius Dwarf Elliptical Galaxy is currently being absorbed by the Milky Way. What evidence supports this?", "Streams of its stars are found wrapping around the Milky Way", "It's getting brighter", "It's growing larger", "The Milky Way is shrinking",
      "Tidal streams from the Sagittarius dwarf stretch across the sky, showing its ongoing disruption by the Milky Way."),
    q(25, "If you could view the Milky Way from above, you would see:", "A barred spiral galaxy with multiple spiral arms", "A perfectly circular disk", "An elliptical shape", "An irregular blob",
      "Face-on, the Milky Way would appear as a classic barred spiral, with gas-rich arms spiraling from a central bar."),
    q(26, "Astronomers find that the Milky Way's disk appears warped at its outer edges. What might cause this?", "Tidal interactions with satellite galaxies like the Magellanic Clouds", "The galaxy is flat everywhere", "Internal stellar explosions", "Dark energy pulling the edges",
      "Gravitational influence from satellite galaxies, especially the LMC, can warp the outer disk."),
    q(27, "The thick disk of the Milky Way contains older stars than the thin disk. What does this tell us about the galaxy's history?", "The Milky Way's disk formed in stages, with the thick disk forming earlier and later settling into the thin disk", "Both disks formed simultaneously", "The thick disk is younger", "Stars don't age differently",
      "The thick disk likely formed during an earlier, more turbulent era, while the thin disk represents later, calmer growth."),
    q(28, "A new satellite galaxy is discovered orbiting the Milky Way at 300,000 light-years. Why is discovering these objects difficult?", "They are small, faint, and spread across large sky areas, requiring deep surveys to detect", "They move too fast", "They're blocked by the Sun", "Satellite galaxies don't exist",
      "Ultra-faint dwarf galaxies have very low surface brightness and are found through careful analysis of survey data."),
    q(29, "The Sun orbits the Milky Way at about 220 km/s. Why don't we feel this motion?", "We and everything around us are moving together — there's no relative acceleration to detect", "We are not actually moving", "Earth's atmosphere shields us", "The speed is too slow to notice",
      "Without a change in velocity (acceleration), uniform motion is undetectable — consistent with Galilean relativity."),
    q(30, "Spiral density wave theory explains that spiral arms are:", "Regions of compression that trigger star formation as material orbits through them, not fixed collections of the same stars", "Permanent structures of the same stars", "Optical illusions", "Magnetic field lines made visible",
      "Stars and gas move through spiral density waves like cars through a traffic jam — the pattern persists while individual components pass through.")
])

# 6.3 Galaxy Clusters
write_quiz(6, "6.3", "Galaxy Clusters", [
    q(1, "A galaxy cluster typically contains:", "Hundreds to thousands of galaxies bound by gravity", "Only 2-3 galaxies", "Just one very large galaxy", "Billions of separate galaxies",
      "Galaxy clusters are the largest gravitationally bound structures, containing hundreds to thousands of members."),
    q(2, "The Local Group is:", "The galaxy cluster containing the Milky Way, Andromeda, and about 80+ smaller galaxies", "The nearest star cluster", "A group of local astronomers", "The entire observable universe",
      "The Local Group spans about 10 million light-years, dominated by the Milky Way and Andromeda."),
    q(3, "The Virgo Cluster is:", "A large galaxy cluster about 54 million light-years away containing ~1,500+ galaxies", "A star cluster in the Milky Way", "A constellation", "A globular cluster",
      "The Virgo Cluster is the nearest large galaxy cluster and the center of the Virgo Supercluster."),
    q(4, "Most of the baryonic (ordinary) matter in galaxy clusters is in the form of:", "Hot, X-ray-emitting gas between galaxies (intracluster medium)", "Stars in galaxies", "Cold dark matter", "Planets",
      "The hot intracluster medium (10-100 million K) far outweighs the stellar mass in galaxy clusters."),
    q(5, "What holds a galaxy cluster together?", "Gravity, primarily from dark matter", "Magnetic fields", "Light pressure", "The expansion of the universe",
      "Dark matter provides most of the gravitational binding in clusters; visible matter alone would be insufficient."),
    q(6, "A supercluster is:", "A large group of galaxy clusters and groups linked by gravity, stretching hundreds of millions of light-years", "A very large star", "A single massive galaxy", "A type of nebula",
      "Superclusters like the Laniakea Supercluster are among the largest known structures in the universe."),
    q(7, "The Milky Way belongs to which supercluster?", "The Laniakea Supercluster", "The Virgo Cluster only", "The Perseus Supercluster", "No supercluster",
      "Laniakea was mapped in 2014 and contains ~100,000 galaxies spanning 500+ million light-years."),
    q(8, "Cosmic voids are:", "Vast regions of space with very few galaxies, hundreds of millions of light-years across", "Black holes", "Dense galaxy clusters", "Dark nebulae",
      "Voids make up most of the universe's volume, with galaxies concentrated on the filaments and walls between them."),
    q(9, "The cosmic web refers to:", "The large-scale structure of the universe — filaments, walls, clusters, and voids", "The internet for aliens", "A spider web in space", "A galaxy's spiral pattern",
      "Galaxies and clusters are arranged in a foam-like cosmic web of filaments surrounding vast voids."),
    q(10, "Galaxy clusters were first recognized as physical systems by:", "Fritz Zwicky in the 1930s, who also discovered 'missing mass' (dark matter evidence)", "Galileo", "Isaac Newton", "Modern astronomers in 2020",
      "Zwicky found that cluster galaxies moved too fast for the visible mass alone — first evidence for dark matter."),
    # Vocabulary (11-20)
    q(11, "What is a galaxy cluster?", "A gravitationally bound collection of hundreds to thousands of galaxies, plus hot gas and dark matter", "A cluster of stars within a galaxy", "A group of planets", "A type of nebula",
      "Galaxy clusters are the largest gravitationally bound structures in the universe."),
    q(12, "What is the Local Group?", "The galaxy group containing the Milky Way and its nearest galactic neighbors", "The nearest star system", "A group of local planets", "All galaxies in the observable universe",
      "The Local Group contains the Milky Way, Andromeda, Triangulum, and approximately 80+ smaller galaxies."),
    q(13, "What is a supercluster?", "A large-scale structure containing multiple galaxy clusters and groups", "A very large galaxy cluster", "A cluster of stars", "A single galaxy with many stars",
      "Superclusters span hundreds of millions of light-years but are not necessarily gravitationally bound."),
    q(14, "What is the intracluster medium (ICM)?", "The hot, diffuse gas between galaxies within a cluster", "The space between stars", "The interior of a galaxy", "Cold dark matter",
      "The ICM is heated to tens of millions of degrees and emits X-rays, containing more baryonic mass than the galaxies themselves."),
    q(15, "What are cosmic filaments?", "Thread-like structures of galaxies and gas connecting galaxy clusters in the cosmic web", "Threads inside stars", "Magnetic field lines in space", "Solar system debris trails",
      "Filaments are the 'highways' of the cosmic web, along which matter flows toward clusters."),
    q(16, "What is a cosmic void?", "A vast, nearly empty region of space between filaments and clusters", "A black hole", "The inside of a star", "A galaxy without stars",
      "Voids are the universe's most underdense regions, typically 30-300+ million light-years across."),
    q(17, "What is the Sunyaev-Zel'dovich effect?", "The distortion of cosmic microwave background radiation by hot electrons in galaxy clusters", "A type of gravitational lensing", "Sound waves in the CMB", "A quantum effect",
      "CMB photons passing through hot cluster gas get a small energy boost, creating a detectable signature."),
    q(18, "What is the virial theorem?", "A relationship between kinetic and potential energy in a gravitationally bound system", "A theory about viral transmission", "A measure of temperature", "A law of optics",
      "The virial theorem allows astronomers to estimate the total mass of a cluster from the velocities of member galaxies."),
    q(19, "What is ram pressure stripping?", "The removal of gas from a galaxy as it moves through the dense intracluster medium", "A ram hitting a galaxy", "Stripping mining in space", "Removing stars from a galaxy",
      "Galaxies plowing through the ICM can have their gas stripped away, quenching star formation."),
    q(20, "What is gravitational lensing by clusters?", "The bending and magnification of background light by a cluster's gravity acting as a cosmic lens", "Telescopes using gravity", "A lens made of glass in space", "A telescope technique",
      "Massive clusters can create dramatic arcs and multiple images of more distant galaxies, revealing both cluster mass and background sources."),
    # Scenario (21-30)
    q(21, "X-ray telescopes reveal that a galaxy cluster is filled with hot gas at 100 million K. What prevents this gas from escaping?", "The cluster's deep gravitational potential well, primarily from dark matter", "Magnetic fields", "The gas is frozen", "Light pressure holds it in",
      "Only the total gravitational mass (dominated by dark matter) is sufficient to contain gas at such extreme temperatures."),
    q(22, "A galaxy falling into a cluster loses its gas tail behind it. What is this process?", "Ram pressure stripping", "Tidal stripping", "Gravitational lensing", "Spaghettification",
      "The galaxy's gas is swept away by the pressure of the intracluster medium, like wind removing water from a car."),
    q(23, "Fritz Zwicky measured galaxy velocities in the Coma Cluster and found they were too fast for the visible mass. What did he conclude?", "There must be unseen 'dark matter' providing additional gravitational pull", "His measurements were wrong", "Galaxies don't follow Newton's laws", "The cluster was about to fly apart",
      "Zwicky's 1933 observation was the first strong evidence for dark matter in the universe."),
    q(24, "A background galaxy appears as a long, thin arc behind a massive cluster. What is causing this?", "Strong gravitational lensing by the cluster's mass", "The galaxy is naturally arc-shaped", "An optical illusion", "Light reflection off the cluster",
      "The cluster's gravity bends light from the background galaxy, distorting it into an arc (or even a full Einstein ring)."),
    q(25, "Two galaxy clusters are colliding. What happens to the their galaxies, gas, and dark matter?", "Galaxies pass through, gas collides and heats, dark matter passes through — separating them", "Everything merges immediately", "Nothing happens", "All components bounce back",
      "The Bullet Cluster shows this: galaxies and dark matter pass through each other, while gas collides and gets left behind."),
    q(26, "The Bullet Cluster provides evidence for dark matter because:", "The gravitational lensing map shows mass is separated from the visible gas, indicating invisible mass", "It's the largest cluster", "It has no dark matter", "It destroyed dark matter",
      "In the Bullet Cluster, most baryonic mass (gas) is offset from the gravitational center — direct evidence for dark matter."),
    q(27, "Astronomers notice that spiral galaxies are rare near the centers of rich clusters. Why?", "Frequent gravitational interactions and ram pressure stripping transform spirals into elliptical or S0 galaxies", "Spirals can't survive near centers", "Only ellipticals form in clusters", "Spirals are hidden by dust",
      "Cluster environments process galaxies through various mechanisms, removing gas and disrupting spiral structure."),
    q(28, "A supercluster appears to span 500 million light-years. Is it gravitationally bound?", "Not necessarily — superclusters are generally not bound and will be torn apart by the universe's expansion", "Yes, all superclusters are fully bound", "It depends only on size", "Superclusters don't exist",
      "Unlike clusters, superclusters are typically not fully bound and represent structures in the process of formation."),
    q(29, "The nearest galaxy cluster to the Local Group is the Virgo Cluster. How does it affect us?", "Its gravity is pulling the Local Group toward it (the Virgocentric flow)", "It has no effect", "It is pushing us away", "It blocks our view of half the sky",
      "The Virgo Cluster's gravity creates a measurable peculiar velocity of the Local Group toward it (~200 km/s)."),
    q(30, "If you could map all visible matter in a massive cluster vs. its total gravitational mass, what would you find?", "Visible matter accounts for only about 15-20% of the total mass; the rest is dark matter", "They would be equal", "Visible matter would dominate", "There would be no gravitational mass",
      "In galaxy clusters, baryonic matter (galaxies + hot gas) is only ~15-20% of total mass; ~80-85% is dark matter.")
])

# 6.4 Dark Matter & Dark Energy
write_quiz(6, "6.4", "Dark Matter & Dark Energy", [
    q(1, "Dark matter is called 'dark' because:", "It does not emit, absorb, or reflect light", "It is black in color", "It exists only at night", "It destroys light",
      "Dark matter interacts gravitationally but not electromagnetically, making it invisible to telescopes."),
    q(2, "Evidence for dark matter comes from:", "Galaxy rotation curves, gravitational lensing, galaxy cluster dynamics, and the CMB", "Direct photographs", "Laboratory experiments only", "There is no evidence",
      "Multiple independent lines of evidence point to the existence of dark matter."),
    q(3, "Dark energy is thought to be responsible for:", "The accelerating expansion of the universe", "Holding galaxies together", "Creating stars", "Causing solar flares",
      "Discovered in 1998, the accelerating expansion implies a repulsive force — dark energy — dominating the universe's energy budget."),
    q(4, "Approximately what fraction of the universe's total energy content is dark energy?", "About 68%", "About 5%", "About 27%", "About 0.1%",
      "The cosmic energy budget: ~68% dark energy, ~27% dark matter, ~5% ordinary (baryonic) matter."),
    q(5, "Approximately what fraction of the universe's total energy content is dark matter?", "About 27%", "About 68%", "About 5%", "About 50%",
      "Dark matter outweighs ordinary matter about 5:1."),
    q(6, "Ordinary (baryonic) matter makes up about what fraction of the universe?", "About 5%", "About 50%", "About 95%", "About 27%",
      "All visible matter — stars, planets, gas, dust — is only about 5% of the total energy content."),
    q(7, "Galaxy rotation curves provided early evidence for dark matter because:", "Stars at the edge orbit much faster than expected from visible mass alone", "Stars at the edge move too slowly", "All stars orbit at the same speed", "Galaxies don't rotate",
      "Vera Rubin and others found flat rotation curves, implying massive, invisible dark matter halos."),
    q(8, "WIMPs are:", "Weakly Interacting Massive Particles — a leading dark matter candidate", "A type of telescope", "Visible matter particles", "A measurement unit",
      "WIMPs would interact through gravity and the weak force, making them very hard to detect directly."),
    q(9, "The accelerating expansion of the universe was discovered by:", "Observations of distant Type Ia supernovae in 1998", "Hubble in the 1920s", "Newton in the 1600s", "CERN experiments",
      "Saul Perlmutter, Brian Schmidt, and Adam Riess won the 2011 Nobel Prize for this discovery."),
    q(10, "MACHOs (Massive Astrophysical Compact Halo Objects) are:", "A dark matter candidate consisting of faint ordinary objects like brown dwarfs or black holes", "A type of galaxy", "Dark energy particles", "Bright visible stars",
      "MACHOs are baryonic dark matter candidates, but observations show they cannot account for most dark matter."),
    # Vocabulary (11-20)
    q(11, "What is dark matter?", "A form of matter that does not interact with light but exerts gravitational influence", "Matter that is simply not illuminated", "Black holes", "Invisible planets",
      "Dark matter makes up ~27% of the universe and is detected only through its gravitational effects."),
    q(12, "What is dark energy?", "A mysterious form of energy driving the accelerating expansion of the universe", "Energy from dark places", "Energy from black holes", "The absence of energy",
      "Dark energy is the dominant component of the universe (~68%), but its nature remains one of physics' greatest mysteries."),
    q(13, "What is the cosmological constant (Λ)?", "A term in Einstein's equations representing a constant energy density filling space uniformly", "The speed of light", "Hubble's constant", "The age of the universe",
      "Einstein originally introduced Λ for a static universe; it was later reinterpreted as dark energy."),
    q(14, "What is a galaxy rotation curve?", "A plot of orbital velocity vs. distance from the galactic center", "A curve showing how many galaxies rotate", "The shape of a rotating galaxy", "A spiral arm pattern",
      "Flat rotation curves at large radii are among the strongest evidence for dark matter halos around galaxies."),
    q(15, "What is gravitational lensing?", "The bending of light from background objects by the gravity of foreground mass", "Using gravity as a telescope lens", "Lensing of gravitational waves", "A lens made of dark matter",
      "Gravitational lensing maps the total mass distribution, including invisible dark matter."),
    q(16, "What is baryonic matter?", "Ordinary matter made of protons, neutrons, and electrons", "Dark matter", "Dark energy", "Antimatter",
      "Baryonic matter includes all visible and familiar matter — stars, planets, gas, animals, humans."),
    q(17, "What is the cosmic microwave background (CMB)?", "Relic radiation from the early universe, ~380,000 years after the Big Bang", "Microwave radiation from cell towers", "Background noise in telescopes", "Radiation from the Sun",
      "The CMB is a nearly uniform glow at 2.725 K, with tiny fluctuations revealing early universe structure."),
    q(18, "What is modified Newtonian dynamics (MOND)?", "An alternative theory that modifies gravity at low accelerations instead of invoking dark matter", "A video game", "The standard theory of dark matter", "A type of telescope",
      "MOND can explain some galaxy rotation curves but struggles with galaxy clusters and the CMB."),
    q(19, "What is the fate of the universe if dark energy continues to dominate?", "The 'Big Freeze' — eternal accelerating expansion leading to isolated, dying galaxies", "The Big Crunch — collapse back to a singularity", "The Big Bounce — cyclic expansion and contraction", "Immediate destruction",
      "With dark energy driving acceleration, distant galaxies will become unreachable and the universe will cool eternally."),
    q(20, "What are axions?", "Hypothetical lightweight particles that are candidates for dark matter", "A type of dark energy", "Very heavy particles", "A star classification",
      "Axions were originally proposed to solve a problem in particle physics; if they exist, they could constitute dark matter."),
    # Scenario (21-30)
    q(21, "Vera Rubin measured that stars at the edge of a galaxy orbit at nearly the same speed as those closer to the center. What shocked astronomers?", "Visible mass alone predicted speeds should decrease with distance, implying vast amounts of unseen mass", "Stars should orbit faster at the edge", "The galaxy wasn't rotating", "The telescope was misaligned",
      "Keplerian decline predicts v ∝ 1/√r; flat curves require additional invisible mass beyond the visible galaxy."),
    q(22, "If dark matter could suddenly become visible, what would you see around the Milky Way?", "A massive, roughly spherical halo extending far beyond the visible disk", "Nothing different", "A thin disk", "A bright ring around the galaxy",
      "Dark matter halos are roughly spherical and extend much farther than the visible stellar disk of a galaxy."),
    q(23, "Two identical Type Ia supernovae are observed; one is much dimmer than expected for its redshift. What does this imply?", "It is farther away than expected — the universe's expansion is accelerating", "It is closer than expected", "Type Ia supernovae vary in brightness", "The observation is wrong",
      "Dimmer-than-expected distant supernovae revealed that the expansion is speeding up, not slowing down."),
    q(24, "A particle physics experiment deep underground detects a possible WIMP collision. Why is the experiment underground?", "To shield it from cosmic rays and other background radiation that could mimic dark matter signals", "WIMPs live underground", "It's closer to the Earth's core", "Underground is warmer",
      "Deep underground locations reduce cosmic ray backgrounds, making it possible to detect rare, faint WIMP interactions."),
    q(25, "The CMB shows tiny temperature fluctuations (~1 part in 100,000). What do these fluctuations represent?", "Density variations in the early universe that grew into today's galaxies and large-scale structure", "Noise in the detectors", "Temperature of nearby stars", "Artifacts from the telescope",
      "These primordial fluctuations, amplified by gravity over billions of years, seeded all cosmic structure."),
    q(26, "If dark energy's density increases over time (phantom energy), what extreme fate could await the universe?", "The Big Rip — all matter, down to atoms, is eventually torn apart by accelerating expansion", "All matter compresses into a singularity", "Nothing would change", "The universe would stop expanding",
      "Phantom energy would cause expansion to accelerate without limit, eventually overcoming all binding forces."),
    q(27, "Astronomers use gravitational lensing to map dark matter in a galaxy cluster. What do they find?", "Dark matter is distributed in a large halo around and between the visible galaxies", "Dark matter is only at the center", "There is no dark matter in clusters", "Dark matter forms a thin disk",
      "Lensing mass maps reveal that dark matter halos are extended and smooth, surrounding the visible cluster components."),
    q(28, "If dark matter interacts only gravitationally, why can't it form 'dark stars' or 'dark planets'?", "Without electromagnetic interactions, dark matter can't radiate energy, cool, and collapse into dense objects", "It does form dark stars", "Gravity doesn't affect dark matter", "Dark matter is too heavy",
      "Baryonic matter cools by emitting photons, allowing it to collapse; dark matter can't radiate, so it remains in diffuse halos."),
    q(29, "The ratio of dark matter to baryonic matter in the universe is about 5:1. How was this ratio determined?", "From the pattern of acoustic peaks in the CMB power spectrum", "By counting visible stars", "By measuring dark energy", "By theoretical prediction alone",
      "The heights and positions of CMB acoustic peaks precisely constrain the amounts of baryonic and dark matter."),
    q(30, "A scientist proposes that dark energy might be a new quantum field called quintessence. How does this differ from the cosmological constant?", "Quintessence can vary in space and time, while the cosmological constant is fixed", "They are identical", "Quintessence only applies to the early universe", "The cosmological constant is variable",
      "If quintessence is real, dark energy's strength could change over time, affecting the universe's ultimate fate.")
])

# 6.5 Expansion of the Universe
write_quiz(6, "6.5", "Expansion of the Universe", [
    q(1, "Who discovered that the universe is expanding?", "Edwin Hubble (confirming work by Vesto Slipher and Georges Lemaître)", "Albert Einstein", "Isaac Newton", "Galileo Galilei",
      "Hubble's 1929 observations of galaxy redshifts vs. distances established that the universe is expanding."),
    q(2, "Hubble's Law states that:", "A galaxy's recession velocity is proportional to its distance (v = H₀d)", "All galaxies move at the same speed", "Closer galaxies move faster", "The universe is static",
      "Hubble's Law: v = H₀d, where H₀ is the Hubble constant and d is distance."),
    q(3, "The Hubble constant (H₀) is currently estimated at roughly:", "67–73 km/s/Mpc", "1 km/s/Mpc", "1,000 km/s/Mpc", "100,000 km/s/Mpc",
      "There is ongoing tension between different measurements: CMB-based (~67) vs. local (~73) km/s/Mpc."),
    q(4, "Cosmological redshift is caused by:", "The stretching of light wavelengths as space itself expands", "Stars moving away from us", "Earth's atmosphere", "Gravity bending light",
      "As space expands, photon wavelengths stretch proportionally, shifting spectral lines toward the red."),
    q(5, "The Big Bang theory describes:", "The origin and evolution of the universe from an extremely hot, dense initial state", "A literal explosion in pre-existing space", "The formation of the Sun", "The eventual end of the universe",
      "The Big Bang was not an explosion in space but the rapid expansion of space itself from a hot, dense state."),
    q(6, "The age of the universe is estimated at:", "About 13.8 billion years", "About 1 billion years", "About 100 billion years", "About 6,000 years",
      "Multiple independent measurements (CMB, stellar ages, nucleosynthesis) converge on ~13.8 billion years."),
    q(7, "The cosmic microwave background (CMB) is evidence for:", "A hot, dense early universe that has since cooled as space expanded", "The Sun's energy reaching the edge of the universe", "Light from the first stars", "An infinite, eternal universe",
      "The CMB is the cooled afterglow of the Big Bang, predicted by theory and discovered in 1965."),
    q(8, "Arno Penzias and Robert Wilson accidentally discovered the CMB in:", "1965", "1929", "2000", "1543",
      "They detected unexplained microwave noise in their antenna, which turned out to be the CMB."),
    q(9, "If the universe is expanding, what is NOT expanding?", "Gravitationally bound systems like galaxies and galaxy clusters", "The space between distant galaxies", "Light wavelengths", "Nothing — everything expands",
      "Local gravity overcomes the expansion; galaxies, the solar system, and atoms do not expand."),
    q(10, "The observable universe has a radius of approximately:", "46 billion light-years", "13.8 billion light-years", "1 billion light-years", "100 billion light-years",
      "Due to expansion, the most distant objects we see are now about 46 billion light-years away, despite the universe being 13.8 billion years old."),
    # Vocabulary (11-20)
    q(11, "What is Hubble's Law?", "The relationship v = H₀d, showing that recession velocity is proportional to distance", "A law about telescopes", "A law about star formation", "A law about planetary orbits",
      "Hubble's Law is the observational foundation of expanding universe cosmology."),
    q(12, "What is the Hubble constant (H₀)?", "The current rate of expansion of the universe, in km/s/Mpc", "The speed of light", "The age of the universe", "The mass of the universe",
      "H₀ quantifies how fast distant galaxies are receding: ~70 km/s/Mpc means a galaxy at 1 Mpc recedes at ~70 km/s."),
    q(13, "What is cosmological redshift?", "The stretching of light wavelengths due to the expansion of space", "Red light from distant stars", "A telescope calibration error", "The Doppler effect from galaxies moving through space",
      "Cosmological redshift differs from the Doppler effect: it's caused by space expanding, not objects moving through space."),
    q(14, "What is the Big Bang?", "The origin event of the universe from an extremely hot, dense state about 13.8 billion years ago", "A large explosion in existing space", "The collision of two universes", "The birth of the Sun",
      "The Big Bang describes the beginning of space, time, matter, and energy — not an explosion within space."),
    q(15, "What is cosmic inflation?", "A brief period of exponentially rapid expansion in the very early universe", "The rising price of space travel", "The expansion of individual galaxies", "The growth of stars",
      "Inflation (proposed by Alan Guth) explains the universe's uniformity and flatness — space expanded faster than light for a tiny fraction of a second."),
    q(16, "What is the observable universe?", "The part of the universe from which light has had time to reach us since the Big Bang", "The entire universe", "Only nearby galaxies", "What we can see with the naked eye",
      "The observable universe is finite because light travels at finite speed; beyond the horizon, there may be more universe we can't yet see."),
    q(17, "What is the cosmic microwave background (CMB)?", "Relic thermal radiation from the early universe when atoms first formed (~380,000 years after the Big Bang)", "Microwave oven radiation", "Radio from distant galaxies", "Solar radiation reflected by planets",
      "The CMB was emitted when the universe cooled enough for electrons and protons to combine, releasing photons."),
    q(18, "What is redshift (z)?", "A measure of how much a galaxy's light has been stretched by expansion: z = Δλ/λ₀", "The shift of all light to red", "The speed of a galaxy", "A type of telescope filter",
      "Higher redshift means greater distance and look-back time; z=1 means the wavelength has doubled."),
    q(19, "What is the Hubble tension?", "The discrepancy between different measurements of the Hubble constant", "The stress Hubble felt about his work", "A force between galaxies", "The tension in telescope cables",
      "CMB-based measurements give ~67 km/s/Mpc while local distance ladder measurements give ~73 km/s/Mpc — a significant disagreement."),
    q(20, "What is the scale factor?", "A function a(t) describing how distances in the universe change with time due to expansion", "The zoom on a telescope", "The size of a galaxy", "A measurement of temperature",
      "The scale factor a(t) is normalized to 1 today; at the CMB epoch, a ≈ 1/1100."),
    # Scenario (21-30)
    q(21, "You observe a galaxy with a redshift of z = 1. What does this mean?", "Its light has been stretched so wavelengths are doubled; the universe was half its current size when the light was emitted", "The galaxy is moving at the speed of light", "The galaxy is blue", "The galaxy is 1 light-year away",
      "At z=1, the universe has expanded by a factor of 2 since the light left that galaxy."),
    q(22, "A student asks: 'Where is the center of the Big Bang expansion?' What is the correct answer?", "There is no center — every point in space is equally the 'center' of expansion", "Earth is the center", "The Milky Way is the center", "A specific point in space",
      "The expansion of space is uniform; every galaxy sees all others receding, as if each point is the center."),
    q(23, "The CMB has a temperature of about 2.725 K today. In the early universe, it was much hotter. Why did it cool?", "The expansion of the universe stretched the CMB photon wavelengths, reducing their energy and apparent temperature", "The photons ran out of energy", "They were absorbed by dark matter", "The universe's heater turned off",
      "As space expands, photon wavelengths stretch (cool) proportionally: T ∝ 1/a(t)."),
    q(24, "If the Hubble constant is 70 km/s/Mpc, what is the approximate recession velocity of a galaxy 100 Mpc away?", "7,000 km/s", "70 km/s", "700 km/s", "70,000 km/s",
      "v = H₀d = 70 × 100 = 7,000 km/s."),
    q(25, "Very distant galaxies appear to recede faster than light. Does this violate special relativity?", "No — special relativity limits motion through space, not the expansion rate of space itself", "Yes, it violates relativity", "Faster-than-light recession is impossible", "Only dark matter can exceed light speed",
      "The expansion of space itself is not bound by the speed of light limit, which applies to motion through space."),
    q(26, "The 'Hubble tension' suggests the universe may be expanding at 67 km/s/Mpc (from CMB) or 73 km/s/Mpc (from local measurements). Why is this important?", "It may indicate new physics beyond the standard cosmological model", "It's a rounding error", "Only one measurement matters", "The difference is negligible",
      "If the discrepancy is real, it could point to unknown properties of dark energy, dark matter, or new particles."),
    q(27, "If the universe's expansion were decelerating (no dark energy), what would the fate of the universe be?", "It could eventually stop expanding and collapse (Big Crunch) or coast to a halt", "It would expand forever at the same rate", "It would accelerate", "It would remain perfectly static",
      "Without dark energy, gravity would slow expansion; enough matter could reverse it entirely."),
    q(28, "A balloon analogy is used to explain expansion: dots on an inflating balloon move apart. What does the balloon surface represent?", "The fabric of space — all points move apart uniformly without any center on the surface", "The atmosphere", "The Milky Way", "The Big Bang explosion",
      "The balloon surface analogy illustrates how expansion works: no point on the surface is the center; all points see others recede."),
    q(29, "Light from the farthest objects we see was emitted 13.4 billion years ago. Yet they are now ~46 billion light-years away. How?", "Space has been expanding while the light traveled, moving the source much farther away than the light travel distance", "The light traveled faster than light", "We measured it wrong", "Time runs differently there",
      "During the ~13 billion years the light traveled, space expanded, carrying the source much farther away."),
    q(30, "The universe appears to be geometrically flat. What does this mean for its total energy density?", "The total density equals the critical density — the universe is right at the balance point", "The universe is literally flat", "There is no energy in the universe", "The universe is curved like a sphere",
      "A flat universe means the total energy density (matter + dark energy) equals the critical density predicted by inflation.")
])

# 6.6 Case Studies in Cosmology
write_quiz(6, "6.6", "Case Studies in Cosmology", [
    q(1, "The COBE satellite was significant because it:", "First detected the tiny temperature fluctuations in the CMB", "Discovered Pluto", "Found the first exoplanet", "Mapped the Milky Way in visible light",
      "COBE (1989-1993) confirmed the CMB's blackbody spectrum and detected anisotropies — earning Mather and Smoot a Nobel Prize."),
    q(2, "WMAP improved on COBE by:", "Providing a much more detailed map of CMB temperature fluctuations", "Discovering dark energy", "Landing on the Moon", "Photographing black holes",
      "WMAP (2001-2010) provided precise measurements of cosmological parameters from the CMB."),
    q(3, "The Planck satellite provided:", "The most precise full-sky CMB map, tightly constraining cosmological parameters", "The first photograph of a star", "Evidence that the Earth is flat", "A new theory of gravity",
      "ESA's Planck mission (2009-2013) measured the CMB with unprecedented precision."),
    q(4, "The Hubble Deep Field image revealed:", "Thousands of galaxies in a tiny patch of seemingly empty sky, many billions of light-years away", "A close-up of the Sun", "No galaxies at all", "Only nearby stars",
      "The 1995 Hubble Deep Field showed that even the 'emptiest' sky is filled with distant galaxies."),
    q(5, "The discovery of the accelerating expansion in 1998 used:", "Distant Type Ia supernovae as standard candles", "Radar measurements", "Star positions", "Radio waves from pulsars",
      "Two teams (Supernova Cosmology Project and High-z SN Search Team) independently discovered the acceleration."),
    q(6, "Gravitational wave detection by LIGO confirmed:", "Einstein's general relativity prediction of spacetime ripples from merging massive objects", "Newton's theory of gravity", "The existence of dark energy directly", "That space is empty",
      "LIGO's 2015 detection of merging black holes opened a new window on the universe and confirmed a key GR prediction."),
    q(7, "The James Webb Space Telescope (JWST) is designed to:", "Observe the earliest galaxies in infrared and study planet formation", "Replace GPS satellites", "Map Earth's surface", "Study the Sun's core",
      "JWST's infrared capabilities allow it to see the most distant, redshifted galaxies and peer through dust."),
    q(8, "Baryon acoustic oscillations (BAOs) are:", "A 'standard ruler' in the distribution of galaxies, tracing sound waves from the early universe", "Musical sounds from the Big Bang", "Vibrations in individual atoms", "Earthquake-like events in space",
      "BAOs left a characteristic ~500 million light-year imprint in galaxy distributions, useful for measuring cosmic expansion."),
    q(9, "The discovery of cosmic neutrino background is:", "Predicted but not yet directly detected from the Big Bang (though supernova neutrinos have been detected)", "Already confirmed", "Proven impossible", "Not predicted by any theory",
      "A cosmic neutrino background similar to the CMB should exist from ~1 second after the Big Bang, but it's incredibly hard to detect."),
    q(10, "The Vera C. Rubin Observatory will:", "Survey the entire visible sky repeatedly, discovering billions of objects and mapping dark matter/energy", "Only observe the Sun", "Replace JWST", "Map Earth's oceans",
      "Named after the dark matter pioneer, the Rubin Observatory will enable unprecedented time-domain and cosmological surveys."),
    # Vocabulary (11-20)
    q(11, "What is the CMB power spectrum?", "A plot showing the intensity of CMB temperature fluctuations at different angular scales", "A power plant in space", "The brightness of the CMB at different times", "A radio frequency chart",
      "The CMB power spectrum reveals the contributions of baryonic matter, dark matter, and dark energy through acoustic peak patterns."),
    q(12, "What is a standard candle?", "An astronomical object with a known intrinsic luminosity, used for distance measurement", "A regular candle used in observatories", "A star of standard size", "A calibration tool for telescopes",
      "Type Ia supernovae and Cepheid variables are standard candles — their known luminosities enable distance estimation."),
    q(13, "What is the cosmic distance ladder?", "A series of overlapping distance measurement methods, from nearby (parallax) to distant (supernovae)", "A physical ladder to the stars", "A single measurement technique", "A ranking of galaxies by distance",
      "Each rung of the distance ladder calibrates the next: parallax → Cepheids → Type Ia SNe → Hubble's Law."),
    q(14, "What is Big Bang nucleosynthesis?", "The formation of light elements (H, He, Li) in the first few minutes after the Big Bang", "Nuclear reactions in modern stars", "The creation of heavy elements in supernovae", "Building atoms from scratch",
      "BBN correctly predicts the abundances of hydrogen (~75%), helium (~25%), and trace lithium in the universe."),
    q(15, "What are baryon acoustic oscillations (BAOs)?", "Periodic fluctuations in the density of visible matter left by sound waves in the early universe", "Sounds made by baryons today", "Oscillations of violin strings", "Vibrations in dark matter",
      "BAOs provide a cosmic 'standard ruler' for measuring the expansion history of the universe."),
    q(16, "What is the cosmological principle?", "The assumption that on large scales, the universe is homogeneous and isotropic", "That the cosmos must have planets", "That Earth is the center of everything", "A principle of telescope design",
      "The cosmological principle is supported by the CMB's uniformity and the large-scale distribution of galaxies."),
    q(17, "What is the ΛCDM model?", "The standard model of cosmology incorporating dark energy (Λ), cold dark matter (CDM), and ordinary matter", "A type of LED light", "A telescope model", "A particle accelerator experiment",
      "ΛCDM successfully explains the CMB, large-scale structure, expansion history, and element abundances."),
    q(18, "What is look-back time?", "The time it took light from a distant object to reach us", "The time since the Big Bang", "The age of a star", "How far back a telescope can zoom",
      "A galaxy at a look-back time of 10 billion years is seen as it was 10 billion years ago."),
    q(19, "What is recombination?", "The epoch ~380,000 years after the Big Bang when electrons combined with nuclei, releasing the CMB", "Combining two galaxies", "A chemical laboratory process", "Recycling matter in space",
      "Despite the name, this was the first time atoms formed; the universe became transparent to light, releasing the CMB."),
    q(20, "What is the dark ages?", "The period between the CMB release and the formation of the first stars, when no visible light sources existed", "Nighttime on Earth", "The absence of dark matter", "A medieval period in astronomy history",
      "The cosmic dark ages ended with the epoch of reionization, when the first stars and galaxies lit up."),
    # Scenario (21-30)
    q(21, "CMB data shows a specific pattern of peaks in its power spectrum. What do the positions of these peaks reveal?", "The geometry of the universe (flat, open, or closed) and the density of various components", "The number of galaxies", "The temperature of the Sun", "The age of Earth",
      "The first peak position confirms a flat universe; peak heights constrain dark matter and baryonic matter densities."),
    q(22, "JWST discovers galaxies at z > 10 that appear surprisingly well-formed. Why is this significant?", "It suggests galaxy formation began earlier than some models predicted", "It's not significant", "Galaxies can't exist at z > 10", "JWST can't observe that far",
      "Early, massive galaxies challenge some structure formation models and constrain the conditions of the very early universe."),
    q(23, "A supernova survey finds that 1998's accelerating expansion result holds up after 25+ years of data. What has this confirmed?", "Dark energy is a robust cosmological component, not a measurement artifact", "Dark energy doesn't exist", "The universe is static", "The measurements were wrong all along",
      "Consistent results from multiple independent teams and methods have firmly established dark energy's reality."),
    q(24, "Gravitational waves from a neutron star merger are detected simultaneously with electromagnetic signals. What is this called?", "Multi-messenger astronomy", "Double detection", "A false alarm", "Dual-wave theory",
      "GW170817 inaugurated multi-messenger astronomy, using both gravitational waves and light to study the same event."),
    q(25, "If the CMB were perfectly uniform (no fluctuations), what would this imply about cosmic structure?", "Galaxies and large-scale structure could not have formed through gravitational growth", "The universe would be the same as we see it", "Dark matter wouldn't exist", "Stars would still form easily",
      "Without density fluctuations, gravity would have nothing to amplify into the galaxies and clusters we see."),
    q(26, "BAO measurements at different redshifts map the expansion rate over time. What do these measurements constrain?", "The equation of state of dark energy (whether it is constant or changing)", "Only the current Hubble constant", "The number of stars", "The age of the Sun",
      "Comparing BAO scales at different redshifts reveals how the expansion rate changed, constraining dark energy properties."),
    q(27, "The Hubble Deep Field was observed by pointing at a seemingly empty region. Why was this approach chosen?", "To avoid bright nearby objects and reveal the ultra-faint, distant galaxy population", "It was a mistake", "There was nothing else to observe", "Bright regions are boring",
      "The empty region maximized sensitivity to the most distant, faintest galaxies without contamination from nearby bright sources."),
    q(28, "Predicted elemental abundances from Big Bang nucleosynthesis match observations of primordial gas clouds. Why is this test powerful?", "It independently confirms the Big Bang model's predictions about the first 20 minutes of the universe", "It tests telescope accuracy", "It's not powerful at all", "It only applies to one element",
      "BBN predicts specific H/He/Li ratios; their agreement with observations is a pillar of Big Bang cosmology."),
    q(29, "The first direct image of a black hole's shadow was taken by the EHT in 2019. How was this achieved?", "By linking radio telescopes worldwide to create an Earth-sized virtual telescope", "By pointing Hubble at M87", "By flying a camera into the black hole", "With a single large radio dish",
      "Very Long Baseline Interferometry (VLBI) combined signals from globally distributed telescopes to achieve the needed resolution."),
    q(30, "If the universe is only 13.8 billion years old, why can we see objects 46 billion light-years away?", "Space has been expanding while light traveled, carrying distant objects far beyond 13.8 billion light-years", "We can't actually see that far", "Light travels faster than we think", "Time moves differently at the edge of the universe",
      "The expansion of space during the light's journey means objects are now much farther than the light-travel distance.")
])

# 6.7 AP Prep: Hubble's Law
write_quiz(6, "6.7", "AP Prep: Hubble's Law", [
    q(1, "Hubble's Law is written as:", "v = H₀d", "F = ma", "E = mc²", "PV = nRT",
      "v (recession velocity) = H₀ (Hubble constant) × d (distance)."),
    q(2, "The units of the Hubble constant are:", "km/s/Mpc", "m/s²", "kg·m/s", "light-years/second",
      "km/s per megaparsec means: for every Mpc of distance, the recession velocity increases by H₀ km/s."),
    q(3, "If H₀ = 70 km/s/Mpc, a galaxy at 200 Mpc has a recession velocity of:", "14,000 km/s", "7,000 km/s", "140 km/s", "70,000 km/s",
      "v = 70 × 200 = 14,000 km/s."),
    q(4, "Redshift z is defined as:", "z = Δλ/λ₀ = (λ_observed - λ_emitted)/λ_emitted", "z = v/c² ", "z = d/t", "z = m/v",
      "Redshift measures how much wavelengths have been stretched by expansion."),
    q(5, "For low velocities (v << c), redshift relates to velocity by:", "z ≈ v/c", "z = v × c", "z = c/v", "z = v²/c²",
      "At low redshifts, z is approximately equal to the recession velocity divided by the speed of light."),
    q(6, "A galaxy has a redshift of z = 0.01. Using Hubble's Law with H₀ = 70 km/s/Mpc, how far away is it?", "About 43 Mpc", "About 70 Mpc", "About 100 Mpc", "About 10 Mpc",
      "v = zc = 0.01 × 300,000 = 3,000 km/s. d = v/H₀ = 3,000/70 ≈ 43 Mpc."),
    q(7, "The inverse of H₀ gives an approximate:", "Age of the universe (the Hubble time)", "Size of the universe", "Mass of the universe", "Temperature of the CMB",
      "1/H₀ ≈ 14 billion years, close to the actual age of 13.8 billion years (exact value depends on expansion history)."),
    q(8, "Peculiar velocities are:", "Galaxy velocities that deviate from pure Hubble flow due to local gravitational effects", "Velocities of unusually shaped galaxies", "Velocities faster than light", "Velocities of only spiral galaxies",
      "Nearby galaxies have significant peculiar velocities that add noise to Hubble's Law."),
    q(9, "Hubble's Law works best for:", "Distant galaxies where peculiar velocities are small compared to cosmological recession", "Nearby planets", "Stars within the Milky Way", "Objects within the solar system",
      "At large distances, the cosmological recession (H₀d) dominates over local (peculiar) velocities."),
    q(10, "1 Mpc (megaparsec) equals approximately:", "3.26 million light-years", "3.26 light-years", "1 million miles", "3.26 billion light-years",
      "1 parsec = 3.26 light-years; 1 megaparsec = 10⁶ parsecs = 3.26 million light-years."),
    # Vocabulary (11-20)
    q(11, "What is recession velocity?", "The speed at which a galaxy moves away from us due to the expansion of space", "The orbiting speed of a galaxy", "The rotation speed of a galaxy", "The speed of light in a galaxy",
      "Recession velocity increases with distance according to Hubble's Law: more distant = faster recession."),
    q(12, "What is the Hubble flow?", "The overall expansion of the universe as described by Hubble's Law", "A river on the Hubble telescope", "The Milky Way's rotation", "Gas flowing in the Sun",
      "Hubble flow is the smooth, large-scale recession of galaxies following v = H₀d."),
    q(13, "What is a megaparsec (Mpc)?", "A unit of distance equal to one million parsecs (~3.26 million light-years)", "A unit of time", "A unit of mass", "A measurement of temperature",
      "Megaparsecs are the standard distance unit in cosmology, convenient for Hubble's Law calculations."),
    q(14, "What is the Doppler effect?", "The change in frequency/wavelength of a wave due to relative motion between source and observer", "An effect that only works with sound", "A telescope design feature", "The effect of gravity on light",
      "While cosmological redshift is not strictly Doppler, the low-z approximation z ≈ v/c resembles the Doppler formula."),
    q(15, "What is the Hubble time?", "The reciprocal of the Hubble constant (1/H₀), giving an approximate age of the universe", "The time Hubble spent observing", "24 hours on the Hubble telescope", "The time since the last CMB measurement",
      "The Hubble time 1/H₀ ≈ 1/70 km/s/Mpc ≈ 14 billion years, a rough estimate of the universe's age."),
    q(16, "What is peculiar velocity?", "A galaxy's motion relative to the Hubble flow, caused by local gravitational influences", "An unusually fast galaxy", "The velocity of dark matter", "The rotation of the Milky Way",
      "The Milky Way has a peculiar velocity of ~600 km/s relative to the CMB rest frame."),
    q(17, "What is a standard candle?", "An object of known luminosity used to determine distance via the brightness-distance relationship", "A regulation candle for ceremonies", "A fixed-brightness star", "A telescope calibration star",
      "Standard candles (Cepheids, Type Ia SNe) are crucial for building the cosmic distance ladder."),
    q(18, "What is the distance modulus?", "m - M = 5 log₁₀(d/10), relating apparent magnitude, absolute magnitude, and distance", "The distance between two stars", "A correction for atmospheric distortion", "The speed-distance relationship",
      "The distance modulus connects the distance ladder to magnitude measurements."),
    q(19, "What is the critical density?", "The density at which the universe is geometrically flat (~9.5 × 10⁻²⁷ kg/m³)", "The density of Earth", "The maximum possible density", "The density of the Sun",
      "The universe's actual density matches the critical density, confirming a flat geometry."),
    q(20, "What is the deceleration parameter (q₀)?", "A parameter measuring whether the expansion is accelerating (q₀ < 0) or decelerating (q₀ > 0)", "The rate at which galaxies slow down", "How fast the universe will stop", "A measure of dark matter density",
      "The measured q₀ < 0 indicates the expansion is accelerating — consistent with dark energy domination."),
    # Scenario (21-30)
    q(21, "A galaxy has a recession velocity of 21,000 km/s. Using H₀ = 70 km/s/Mpc, how far away is it?", "300 Mpc", "210 Mpc", "3,000 Mpc", "30 Mpc",
      "d = v/H₀ = 21,000/70 = 300 Mpc."),
    q(22, "A galaxy's hydrogen emission line (normally 656.3 nm) is observed at 669.4 nm. What is its redshift?", "z = (669.4 - 656.3)/656.3 ≈ 0.020", "z = 656.3/669.4 ≈ 0.98", "z = 13.1", "z = 1.0",
      "z = Δλ/λ₀ = (669.4 - 656.3)/656.3 = 13.1/656.3 ≈ 0.020."),
    q(23, "Using the redshift from the previous question, estimate the galaxy's distance (H₀ = 70 km/s/Mpc).", "About 86 Mpc", "About 860 Mpc", "About 8.6 Mpc", "About 0.86 Mpc",
      "v = zc = 0.020 × 300,000 = 6,000 km/s. d = v/H₀ = 6,000/70 ≈ 86 Mpc."),
    q(24, "If you measure H₀ = 70 km/s/Mpc, what is the Hubble time?", "Approximately 14 billion years", "Approximately 70 billion years", "Approximately 1 billion years", "Approximately 140 billion years",
      "1/H₀ = 1/(70 km/s/Mpc) = 1 Mpc/(70 km/s) ≈ 4.4 × 10¹⁷ s ≈ 14 × 10⁹ years."),
    q(25, "A nearby galaxy has a blueshift instead of a redshift. Does this violate Hubble's Law?", "No — its peculiar velocity (gravitational attraction toward us) exceeds its recession velocity at that close distance", "Yes — all galaxies must be redshifted", "Blueshifts are impossible", "The measurement must be wrong",
      "The Andromeda Galaxy is blueshifted because its peculiar velocity toward the Milky Way exceeds the Hubble flow at 2.5 Mly."),
    q(26, "You measure two galaxies: Galaxy A at 10 Mpc with v = 700 km/s, and Galaxy B at 50 Mpc with v = 3,500 km/s. Do both obey Hubble's Law?", "Yes — both give H₀ = 70 km/s/Mpc", "No — their velocities are different", "Only Galaxy A obeys", "Neither obeys",
      "A: 700/10 = 70; B: 3,500/50 = 70. Both give H₀ = 70 km/s/Mpc, consistent with Hubble's Law."),
    q(27, "A Cepheid variable in a galaxy has a period that corresponds to an absolute magnitude of -5. Its apparent magnitude is +15. How far is the galaxy?", "10,000 parsecs (10 kpc) — wait, let's use the formula: d = 10^((m-M+5)/5) = 10^((15-(-5)+5)/5) = 10^5 = 100,000 pc = 100 kpc", "1,000 pc", "10 pc", "1 Mpc",
      "Distance modulus: m - M = 5 log₁₀(d/10). 15 - (-5) = 20. 20/5 = 4. d = 10^(4+1) = 100,000 pc = 100 kpc."),
    q(28, "If the Hubble constant were larger (say 140 km/s/Mpc instead of 70), the estimated age of the universe would be:", "Roughly halved (~7 billion years)", "Roughly doubled", "Unchanged", "Zero",
      "Hubble time = 1/H₀; doubling H₀ halves the estimated age."),
    q(29, "You want to use Hubble's Law to measure a galaxy's distance. What must you first measure?", "The galaxy's redshift (from its spectrum) to calculate its recession velocity", "Its mass", "Its temperature", "Its size on the sky",
      "Spectroscopic redshift gives recession velocity; then d = v/H₀ provides the Hubble distance."),
    q(30, "A galaxy at z = 2 appears to be receding at ~180,000 km/s using the relativistic formula. But its 'proper distance' is much larger. Why is the simple v = H₀d not exact here?", "At high redshifts, the simple linear Hubble's Law breaks down; the full cosmological model with expansion history is needed", "It always works exactly", "The galaxy is too close", "High redshifts are impossible",
      "Hubble's Law v = H₀d is only accurate for nearby galaxies (z << 1); at high z, cosmological models must be used.")
])

print("\n=== Unit 6 Complete ===")
