import json, os

BASE = "content_data/Algebra2Lessons"

def make_q(num, text, opts, correct_idx, explanation):
    options = []
    for i, o in enumerate(opts):
        options.append({"text": o, "is_correct": i == correct_idx, "data_i18n": None})
    return {"question_number": num, "question_text": text, "attempted": 2,
            "data_i18n": None, "options": options, "explanation": explanation}

def write_quiz(unit, lesson, title, questions):
    path = f"{BASE}/Unit{unit}/Lesson{lesson}_Quiz.json"
    data = {"unit": unit, "lesson_number": lesson, "title": title,
            "course": "Algebra 2", "quiz_questions": questions}
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    nums = [q["question_number"] for q in questions]
    assert nums == list(range(1,31)), f"Bad sequence in {lesson}: {nums}"
    print(f"  Wrote {path}: 30 Qs, valid=True")

# Lesson 3.4  Polynomial Graphs & Zeros
qs34 = [
    make_q(1,"What are the zeros of f(x) = (x - 1)(x + 3)(x - 5)?",["1, -3, 5","1, 3, 5","-1, -3, -5","0, 1, 3"],0,
        "Setting each factor equal to zero gives x = 1, x = -3, and x = 5. These are the x-values where the graph crosses the x-axis."),
    make_q(2,"How many turning points can a degree-4 polynomial have at most?",["3","4","5","2"],0,
        "A polynomial of degree n can have at most n - 1 turning points. For degree 4, that is 4 - 1 = 3."),
    make_q(3,"What is the end behavior of f(x) = -x^3 + 2x?",["Falls left, rises right","Rises left, falls right","Rises both ends","Falls both ends"],1,
        "A cubic with a negative leading coefficient rises to the left and falls to the right, since odd-degree polynomials have opposite end behaviors."),
    make_q(4,"Find the zeros of f(x) = x^2 - 9.",["3 and -3","9 and -9","0 and 9","3 and 0"],0,
        "Factoring gives (x - 3)(x + 3) = 0, so x = 3 and x = -3. This is a difference of squares."),
    make_q(5,"What is the degree of f(x) = 4x^5 - x^3 + 7?",["5","3","4","7"],0,
        "The degree of a polynomial is the highest power of x. Here the highest power is x^5, so the degree is 5."),
    make_q(6,"Which polynomial has zeros at x = 0 and x = 4?",["x(x - 4)","x(x + 4)","(x - 4)^2","x^2 + 4x"],0,
        "Substituting: x(x - 4) equals zero when x = 0 or x = 4, matching both zeros exactly."),
    make_q(7,"What is the y-intercept of f(x) = 2x^3 - x^2 + 5?",["5","0","-1","2"],0,
        "The y-intercept is f(0) = 2(0)^3 - (0)^2 + 5 = 5."),
    make_q(8,"How many zeros does f(x) = x^4 + 1 have over the real numbers?",["0","1","2","4"],0,
        "Since x^4 >= 0 for all real x, we have x^4 + 1 >= 1 > 0. The polynomial has no real zeros."),
    make_q(9,"What is the leading coefficient of f(x) = -3x^6 + x^4 - 2?",[ "-3","1","-2","6"],0,
        "The leading coefficient is the coefficient of the highest-degree term. The highest-degree term is -3x^6, so the leading coefficient is -3."),
    make_q(10,"The graph of f(x) = x^2(x - 2) touches the x-axis at which zero?",["x = 0","x = 2","x = -2","x = 1"],0,
        "The zero at x = 0 has multiplicity 2 (even), so the graph touches but does not cross the x-axis there. At x = 2 (multiplicity 1), it crosses."),
    make_q(11,"What does the term 'zero of a polynomial' mean?",["An x-value where the polynomial equals zero","The constant term of the polynomial","The leading coefficient","The degree of the polynomial"],0,
        "A zero (or root) of a polynomial is an input value x for which f(x) = 0. It corresponds to an x-intercept on the graph."),
    make_q(12,"What does 'multiplicity' of a zero refer to?",["The number of times a factor is repeated","The value of the zero","The degree of the polynomial","The y-intercept"],0,
        "Multiplicity is the number of times a particular factor appears in the factored form. For example, in (x - 2)^3, the zero x = 2 has multiplicity 3."),
    make_q(13,"What is 'end behavior' of a polynomial?",["How the graph behaves as x approaches positive or negative infinity","The value at x = 0","The slope at the origin","The maximum value of the function"],0,
        "End behavior describes the direction the graph heads as x goes to positive infinity or negative infinity, determined by the degree and leading coefficient."),
    make_q(14,"What does 'turning point' mean on a polynomial graph?",["A point where the graph changes from increasing to decreasing or vice versa","A zero of the polynomial","The y-intercept","A point of discontinuity"],0,
        "A turning point is a local maximum or minimum where the graph reverses direction. A degree-n polynomial has at most n - 1 turning points."),
    make_q(15,"What is the 'Fundamental Theorem of Algebra'?",["Every non-constant polynomial has at least one complex root","Every polynomial has only real roots","Polynomials of even degree have no zeros","The degree equals the number of real zeros"],0,
        "The Fundamental Theorem of Algebra states that every polynomial of degree n >= 1 has at least one root in the complex numbers, guaranteeing n roots when counted with multiplicity."),
    make_q(16,"What does it mean for a polynomial to have 'even degree'?",["Its highest exponent is an even number","It has an even number of terms","All coefficients are even","It has an even number of zeros"],0,
        "A polynomial has even degree when the highest power of the variable is an even number, such as 2, 4, or 6. This affects end behavior: both ends go in the same direction."),
    make_q(17,"What is a 'local maximum' of a polynomial?",["A point where the function value is greater than nearby values","The highest value the function ever takes","A zero of the function","The y-intercept"],0,
        "A local maximum is a point where the function value is higher than at all nearby points, though it may not be the absolute highest value of the function."),
    make_q(18,"What does 'continuous function' mean in the context of polynomials?",["The graph has no breaks, holes, or jumps","The function is always increasing","The function has no zeros","The function is linear"],0,
        "A continuous function has no gaps or breaks in its graph. All polynomials are continuous over the entire real number line."),
    make_q(19,"What is the 'leading term' of a polynomial?",["The term with the highest degree","The constant term","The first term written","The term with the smallest coefficient"],0,
        "The leading term is the term with the highest exponent. It determines the end behavior and the degree of the polynomial."),
    make_q(20,"What does it mean for a zero to have 'odd multiplicity'?",["The graph crosses the x-axis at that zero","The graph touches but does not cross the x-axis","The zero is negative","The zero is imaginary"],0,
        "When a zero has odd multiplicity, the graph crosses through the x-axis at that point. When the multiplicity is even, the graph merely touches and turns around."),
    make_q(21,"A ball is thrown upward and its height in feet is modeled by h(t) = -t^3 + 6t^2 - 9t, where t is in seconds. At what times is the ball at ground level?",["t = 0 and t = 3","t = 0 and t = 9","t = 1 and t = 3","t = 3 and t = 6"],0,
        "Setting h(t) = 0: -t(t^2 - 6t + 9) = -t(t - 3)^2 = 0 gives t = 0 and t = 3."),
    make_q(22,"A box manufacturer models the volume of a box as V(x) = x(10 - 2x)(8 - 2x), where x is the height of the cut corners in inches. What is the degree of this polynomial?",["3","2","4","6"],0,
        "Expanding: x(10 - 2x)(8 - 2x) = x(80 - 36x + 4x^2) = 4x^3 - 36x^2 + 80x. The highest power is x^3, so degree 3."),
    make_q(23,"A company's profit in thousands of dollars is modeled by P(x) = -2x^3 + 12x^2 - 18x, where x is units sold in hundreds. For which values of x is profit zero?",["x = 0 and x = 3","x = 0, 2, and 3","x = 1 and x = 6","x = 0 and x = 6"],0,
        "Factor: -2x(x^2 - 6x + 9) = -2x(x - 3)^2 = 0 gives x = 0 and x = 3."),
    make_q(24,"An engineer models a beam's deflection as d(x) = x^4 - 10x^2 + 9, where x is in meters. What are the points where deflection is zero?",["x = 1, -1, 3, -3","x = 1, 3","x = 9, 1","x = 0, 3"],0,
        "Factor: x^4 - 10x^2 + 9 = (x^2 - 1)(x^2 - 9) = (x-1)(x+1)(x-3)(x+3), giving zeros at x = 1, -1, 3, -3."),
    make_q(25,"A roller coaster's height in feet is modeled by h(x) = -x^3 + 9x where x is horizontal distance in hundreds of feet. Where does the coaster reach ground level (h = 0)?",["x = 0, 3, and -3","x = 0 and 9","x = 3 only","x = 0 and 3"],0,
        "Setting h(x) = 0: -x(x^2 - 9) = -x(x - 3)(x + 3) = 0 gives x = 0, x = 3, and x = -3."),
    make_q(26,"A population of bacteria is modeled by P(t) = t^3 - 7t^2 + 14t - 8, where t is days. On which days is the population exactly zero?",["t = 1, 2, and 4","t = 1, 3, and 4","t = 2, 4, and 8","t = 1 and 8"],0,
        "Testing t = 1: 1 - 7 + 14 - 8 = 0. Factoring gives (t - 1)(t^2 - 6t + 8) = (t - 1)(t - 2)(t - 4) = 0, so t = 1, 2, and 4."),
    make_q(27,"A river's depth in feet is modeled by d(x) = -x^4 + 5x^2 - 4, where x is distance from center in yards. At what distances from center is the depth zero?",["x = 1, -1, 2, -2","x = 1, 4","x = 0, 2, 4","x = 2, -2"],0,
        "Factor: -(x^4 - 5x^2 + 4) = -(x^2 - 1)(x^2 - 4) = -(x-1)(x+1)(x-2)(x+2) = 0 gives x = 1, -1, 2, -2."),
    make_q(28,"A farmer's crop yield in bushels is modeled by Y(x) = -x^2(x - 6) where x is fertilizer in pounds. At what amounts of fertilizer is the yield zero?",["x = 0 and x = 6","x = 0 only","x = 6 only","x = 2 and x = 3"],0,
        "Setting Y(x) = 0: -x^2(x - 6) = 0 gives x = 0 (multiplicity 2) and x = 6. The yield is zero with no fertilizer or with 6 pounds."),
    make_q(29,"A firework's height in meters is modeled by h(t) = -t^4 + 10t^2 - 9, where t is in seconds. At what times does the firework reach ground level?",["t = 1, -1, 3, -3","t = 1 and 3","t = 3 and 9","t = 0 and 1"],0,
        "Factor: -(t^4 - 10t^2 + 9) = -(t^2 - 1)(t^2 - 9) = -(t-1)(t+1)(t-3)(t+3) = 0. Since time must be positive, t = 1 and t = 3 are meaningful, but the zeros are t = 1, -1, 3, -3."),
    make_q(30,"An architect designs an arch whose height in feet is modeled by h(x) = -x^3 + 4x^2 + x - 4, where x is horizontal distance in feet. Where does the arch meet the ground?",["x = 1, -1, and 4","x = 1 and 4","x = -1 and 4","x = 2 and 4"],0,
        "Testing x = 1: -1 + 4 + 1 - 4 = 0. Factoring: (x - 1)(-x^2 + 3x + 4) = -(x - 1)(x^2 - 3x - 4) = -(x - 1)(x - 4)(x + 1) = 0, giving x = 1, 4, and -1."),
]

# Lesson 3.5  Remainder & Factor Theorems
qs35 = [
    make_q(1,"Using the Remainder Theorem, what is the remainder when f(x) = x^3 + 2x - 5 is divided by (x - 1)?",[ "-2","0","1","5"],0,
        "By the Remainder Theorem, the remainder is f(1) = 1 + 2 - 5 = -2."),
    make_q(2,"Is (x - 2) a factor of f(x) = x^3 - 3x^2 + 4?",["Yes","No","Only if divided by x + 2","Cannot be determined"],0,
        "f(2) = 8 - 12 + 4 = 0. Since the remainder is 0, (x - 2) is a factor by the Factor Theorem."),
    make_q(3,"What is the remainder when f(x) = 2x^2 + 3x - 1 is divided by (x + 1)?",[ "-2","0","4","2"],0,
        "f(-1) = 2(1) + 3(-1) - 1 = 2 - 3 - 1 = -2."),
    make_q(4,"What is the remainder when f(x) = x^4 - 1 is divided by (x - 1)?",["0","1","-1","2"],0,
        "f(1) = 1 - 1 = 0. So (x - 1) is a factor of x^4 - 1."),
    make_q(5,"What is the remainder when f(x) = x^3 - 4x + 2 is divided by (x - 3)?",["17","2","5","11"],0,
        "f(3) = 27 - 12 + 2 = 17."),
    make_q(6,"Is (x + 3) a factor of f(x) = x^3 + 27?",["Yes","No","Only if degree is 2","Cannot determine"],0,
        "f(-3) = -27 + 27 = 0. Since the remainder is 0, (x + 3) is a factor."),
    make_q(7,"What is the remainder when f(x) = 3x^2 - x + 4 is divided by (x - 2)?",["14","10","8","6"],0,
        "f(2) = 3(4) - 2 + 4 = 12 - 2 + 4 = 14."),
    make_q(8,"If f(x) divided by (x - a) gives remainder 0, what can you conclude?",["(x - a) is a factor of f(x)","f(x) has no zeros","a is the y-intercept","f(x) is linear"],0,
        "By the Factor Theorem, if f(a) = 0, then (x - a) is a factor of f(x)."),
    make_q(9,"What is the remainder when f(x) = x^5 - 1 is divided by (x - 1)?",["0","1","-1","5"],0,
        "f(1) = 1 - 1 = 0. So (x - 1) is a factor of x^5 - 1."),
    make_q(10,"What is the remainder when f(x) = 2x^3 + x^2 - 3x + 1 is divided by (x + 2)?",[ "-5","5","1","-9"],0,
        "By the Remainder Theorem, f(-2) = 2(-8) + 4 + 6 + 1 = -5. The remainder is -5."),
    make_q(11,"What does the Remainder Theorem state?",["When f(x) is divided by (x - a), the remainder equals f(a)","The remainder is always zero","Polynomials cannot have remainders","The quotient equals f(a)"],0,
        "The Remainder Theorem says that dividing polynomial f(x) by (x - a) yields a remainder equal to f(a), which can be found by direct substitution."),
    make_q(12,"What does the Factor Theorem state?",["(x - a) is a factor of f(x) if and only if f(a) = 0","Every polynomial has at least one factor","Factors always come in pairs","The factor equals the remainder"],0,
        "The Factor Theorem is a special case of the Remainder Theorem: if the remainder f(a) is zero, then (x - a) divides f(x) evenly."),
    make_q(13,"What is a 'divisor' in polynomial division?",["The polynomial you are dividing by","The result of the division","The polynomial being divided","The remainder"],0,
        "In polynomial division, the divisor is the polynomial by which you divide. For example, when dividing f(x) by (x - 3), the divisor is (x - 3)."),
    make_q(14,"What is the 'quotient' in polynomial division?",["The result of the division before the remainder","The remainder","The original polynomial","The divisor"],0,
        "The quotient is the polynomial result you get when dividing, before accounting for any remainder. It satisfies: dividend = divisor times quotient + remainder."),
    make_q(15,"What does 'synthetic substitution' mean?",["Using synthetic division to evaluate f(a) quickly","Replacing variables with symbols","A type of factoring","Graphing a polynomial"],0,
        "Synthetic substitution is the process of using the synthetic division algorithm to quickly compute f(a) for a polynomial, which equals the remainder."),
    make_q(16,"What is a 'depressed polynomial'?",["The quotient obtained after dividing out one factor","A polynomial with negative coefficients","A polynomial of degree zero","A polynomial with no real roots"],0,
        "After dividing a polynomial by one of its factors, the resulting quotient is called the depressed polynomial. Its degree is one less than the original."),
    make_q(17,"What does 'factor completely' mean?",["Write the polynomial as a product of irreducible factors","Find one factor","Compute the remainder","Evaluate at a given point"],0,
        "Factoring completely means expressing the polynomial as a product of factors that cannot be factored further over the given number system."),
    make_q(18,"What is the 'dividend' in polynomial division?",["The polynomial being divided","The polynomial you divide by","The remainder","The quotient"],0,
        "The dividend is the polynomial that is being divided. In f(x) divided by (x - a), f(x) is the dividend."),
    make_q(19,"What does it mean for a polynomial to be 'divisible' by (x - a)?",["The remainder when dividing by (x - a) is zero","The polynomial has degree a","The leading coefficient is a","The polynomial has a terms"],0,
        "A polynomial is divisible by (x - a) when dividing yields a remainder of zero, meaning f(a) = 0 and (x - a) is a factor."),
    make_q(20,"What is 'polynomial long division'?",["An algorithm for dividing one polynomial by another, similar to numerical long division","Multiplying two polynomials","Adding polynomials of different degrees","Finding the GCF of polynomials"],0,
        "Polynomial long division is a step-by-step algorithm that divides polynomials in a manner analogous to long division of integers, producing a quotient and remainder."),
    make_q(21,"A box company models its cost as C(x) = x^3 - 6x^2 + 11x - 6 dollars, where x is units produced in hundreds. Verify that producing 1 hundred units results in zero cost.",["Yes, because C(1) = 1 - 6 + 11 - 6 = 0","No, C(1) = 2","No, C(1) = -2","Yes, because C(1) = 6"],0,
        "C(1) = 1 - 6 + 11 - 6 = 0. By the Factor Theorem, (x - 1) is a factor, confirming that cost is zero at x = 1."),
    make_q(22,"A scientist models a reaction rate as R(t) = 2t^3 - 5t^2 - t + 6, where t is time in minutes. Is (t - 2) a factor?",["No, because R(2) = 0 is false","Yes, because R(2) = 0","Yes, because the coefficient is 2","Cannot determine"],1,
        "R(2) = 2(8) - 5(4) - 2 + 6 = 16 - 20 - 2 + 6 = 0. Since the remainder is 0, (t - 2) is indeed a factor."),
    make_q(23,"An engineer uses f(x) = x^3 - 2x^2 - 5x + 6 to model stress. She needs to find the remainder when divided by (x - 3). What is it?",["0","6","3","-6"],0,
        "f(3) = 27 - 18 - 15 + 6 = 0. The remainder is 0, so (x - 3) is a factor of the stress polynomial."),
    make_q(24,"A store's revenue is modeled by R(x) = x^3 + x^2 - 10x + 8. The manager checks whether selling 2 units yields zero revenue. What is R(2)?",["0","4","8","2"],0,
        "R(2) = 8 + 4 - 20 + 8 = 0. So x = 2 is a zero of the revenue function, and (x - 2) is a factor."),
    make_q(25,"A chemist models concentration as C(t) = t^3 - 4t^2 + t + 6, where t is in hours. She tests whether t = 3 gives zero concentration. What is C(3)?",["0","6","3","-6"],0,
        "C(3) = 27 - 36 + 3 + 6 = 0. The concentration is zero at t = 3, confirming (t - 3) is a factor."),
    make_q(26,"A ball's height is h(t) = t^3 - 7t + 6. A physicist uses the Remainder Theorem to find h(2). What is the value?",["0","2","6","4"],0,
        "h(2) = 8 - 14 + 6 = 0. The ball is at ground level at t = 2 seconds."),
    make_q(27,"A factory's waste output is modeled by W(x) = 2x^3 - 3x^2 - 8x + 12. Management checks if (x - 2) is a factor. What is W(2)?",["0","4","8","-4"],0,
        "W(2) = 16 - 12 - 16 + 12 = 0. Since W(2) = 0, (x - 2) is a factor and x = 2 is a zero."),
    make_q(28,"A park designer models a path's elevation as E(x) = x^3 + 2x^2 - x - 2. She finds the remainder when dividing by (x + 2). What is it?",["0","-2","4","2"],0,
        "E(-2) = -8 + 8 + 2 - 2 = 0. The remainder is 0, so (x + 2) is a factor."),
    make_q(29,"A population model is P(t) = t^3 - 3t^2 + 3t - 1. An ecologist checks P(1). What is the result?",["0","1","-1","2"],0,
        "P(1) = 1 - 3 + 3 - 1 = 0. Notice this is (t - 1)^3, so t = 1 is a zero with multiplicity 3."),
    make_q(30,"A rocket's distance is modeled by d(t) = t^4 - 5t^2 + 4. An engineer wants the remainder when divided by (t - 2). What is d(2)?",["0","4","8","2"],0,
        "d(2) = 16 - 20 + 4 = 0. Since d(2) = 0, (t - 2) is a factor of the distance polynomial."),
]

# Lesson 3.6  Complex Numbers & Polynomial Roots
qs36 = [
    make_q(1,"What is the value of i^2?",[ "-1","1","i","-i"],0,
        "By definition, i is the imaginary unit where i^2 = -1."),
    make_q(2,"Simplify (3 + 2i) + (1 - 4i).",["4 - 2i","4 + 6i","2 + 2i","3 - 2i"],0,
        "Add real parts: 3 + 1 = 4. Add imaginary parts: 2i + (-4i) = -2i. Result: 4 - 2i."),
    make_q(3,"Simplify (2 + 3i)(1 - i).",["5 + i","5 - i","-1 + 5i","2 - 3i"],0,
        "Using FOIL: 2(1) + 2(-i) + 3i(1) + 3i(-i) = 2 - 2i + 3i - 3i^2 = 2 + i + 3 = 5 + i."),
    make_q(4,"What is the conjugate of 4 - 5i?",["4 + 5i","-4 + 5i","-4 - 5i","5 - 4i"],0,
        "The conjugate of a + bi is a - bi. So the conjugate of 4 - 5i is 4 + 5i."),
    make_q(5,"Find the modulus of 3 + 4i.",["5","7","25","1"],0,
        "The modulus is sqrt(3^2 + 4^2) = sqrt(9 + 16) = sqrt(25) = 5."),
    make_q(6,"What are the roots of x^2 + 4 = 0?",["2i and -2i","2 and -2","4i and -4i","No roots"],0,
        "x^2 = -4, so x = +-sqrt(-4) = +-2i. The roots are 2i and -2i."),
    make_q(7,"Simplify i^3.",[ "-i","i","1","-1"],0,
        "i^3 = i^2 * i = (-1)(i) = -i."),
    make_q(8,"If f(x) = x^2 + 1, what are its roots?",["i and -i","1 and -1","0 and 1","No roots"],0,
        "Setting x^2 + 1 = 0 gives x^2 = -1, so x = i and x = -i."),
    make_q(9,"Simplify (1 + i)^2.",["2i","2","1 + 2i","0"],0,
        "(1 + i)^2 = 1 + 2i + i^2 = 1 + 2i - 1 = 2i."),
    make_q(10,"What is the product (2 + i)(2 - i)?",["5","3","4 - i","4 + i"],0,
        "Using the difference of squares pattern: (2 + i)(2 - i) = 4 - i^2 = 4 - (-1) = 5."),
    make_q(11,"What is an 'imaginary number'?",["A number of the form bi where b is real and i = sqrt(-1)","A number that does not exist","A very large number","A fraction"],0,
        "An imaginary number has the form bi, where b is a nonzero real number and i is the imaginary unit defined as sqrt(-1)."),
    make_q(12,"What is a 'complex number'?",["A number of the form a + bi where a and b are real","Any irrational number","A number greater than 100","A negative number"],0,
        "A complex number combines a real part (a) and an imaginary part (bi) in the form a + bi, where a and b are real numbers."),
    make_q(13,"What is the 'complex conjugate' of a number?",["The number with the sign of the imaginary part reversed","The reciprocal of the number","The negative of the number","The absolute value"],0,
        "The complex conjugate of a + bi is a - bi. Multiplying a complex number by its conjugate yields a real number: (a + bi)(a - bi) = a^2 + b^2."),
    make_q(14,"What does the 'Complex Conjugate Root Theorem' state?",["If a + bi is a root of a polynomial with real coefficients, then a - bi is also a root","All roots are conjugates","Complex roots come in triples","Polynomials with complex roots have no real roots"],0,
        "The Complex Conjugate Root Theorem guarantees that non-real complex roots of polynomials with real coefficients always appear in conjugate pairs."),
    make_q(15,"What is the 'imaginary unit'?",["The number i, defined as sqrt(-1)","The number 0","The number 1","The number pi"],0,
        "The imaginary unit i is defined by the property that i^2 = -1. It allows us to take square roots of negative numbers."),
    make_q(16,"What does 'modulus' of a complex number mean?",["The distance from the origin to the point (a, b) in the complex plane","The real part of the number","The imaginary part","The conjugate"],0,
        "The modulus (or absolute value) of a + bi is sqrt(a^2 + b^2), representing its distance from the origin in the complex plane."),
    make_q(17,"What is the 'complex plane'?",["A coordinate plane where the x-axis is real and y-axis is imaginary","A 3D coordinate system","A plane with only real numbers","A plane with only imaginary numbers"],0,
        "The complex plane (or Argand diagram) is a two-dimensional plane where the horizontal axis represents real parts and the vertical axis represents imaginary parts."),
    make_q(18,"What does 'irreducible over the reals' mean for a quadratic?",["It cannot be factored into linear factors with real coefficients","It has real roots","It can be factored easily","It equals zero"],0,
        "A quadratic is irreducible over the reals when its discriminant is negative, meaning it has no real roots and cannot be factored using only real numbers."),
    make_q(19,"What is a 'pure imaginary number'?",["A complex number with zero real part, like 3i","Any complex number","A real number","A number with zero imaginary part"],0,
        "A pure imaginary number has the form bi where b is nonzero and the real part is zero. Examples include 2i, -5i, and i."),
    make_q(20,"What does 'standard form' of a complex number mean?",["Written as a + bi where a is the real part and b is the imaginary coefficient","Written as bi + a","Written as a fraction","Written in polar form"],0,
        "Standard form of a complex number is a + bi, clearly separating the real part a from the imaginary part bi."),
    make_q(21,"An electrical engineer works with impedance Z = 3 + 4i ohms. What is the magnitude (modulus) of this impedance?",["5 ohms","7 ohms","25 ohms","1 ohm"],0,
        "|Z| = sqrt(3^2 + 4^2) = sqrt(9 + 16) = sqrt(25) = 5 ohms."),
    make_q(22,"A circuit has two impedances Z1 = 2 + 3i and Z2 = 4 - i in series. What is the total impedance?",["6 + 2i","6 - 2i","2 + 4i","8 + 2i"],0,
        "Total impedance in series is the sum: (2 + 3i) + (4 - i) = 6 + 2i ohms."),
    make_q(23,"A physicist solves x^2 + 2x + 5 = 0 for a vibration model. What are the roots?",[ "-1 + 2i and -1 - 2i","1 + 2i and 1 - 2i","-2 + i and -2 - i","No solution"],0,
        "Using the quadratic formula: x = (-2 +- sqrt(4 - 20))/2 = (-2 +- sqrt(-16))/2 = (-2 +- 4i)/2 = -1 +- 2i."),
    make_q(24,"A signal processing engineer multiplies two signals represented by (1 + 2i) and (3 - i). What is the product?",["5 + 5i","3 - 2i","5 - 5i","1 + 6i"],0,
        "(1 + 2i)(3 - i) = 3 - i + 6i - 2i^2 = 3 + 5i + 2 = 5 + 5i."),
    make_q(25,"A polynomial equation for a control system is x^3 - x^2 + x - 1 = 0. One root is x = 1. What are the other two roots?",["i and -i","1 and -1","2i and -2i","No other roots"],0,
        "Dividing by (x - 1): x^2 + 1 = 0 gives x = i and x = -i. The three roots are 1, i, and -i."),
    make_q(26,"An engineer finds the conjugate of impedance Z = 5 - 7i for a circuit calculation. What is the conjugate?",["5 + 7i","-5 + 7i","-5 - 7i","7 - 5i"],0,
        "The conjugate of a + bi is a - bi. So the conjugate of 5 - 7i is 5 + 7i."),
    make_q(27,"A mathematician is finding all roots of x^4 - 1 = 0. How many complex roots (including real) are there?",["4","2","1","8"],0,
        "x^4 - 1 = (x^2 - 1)(x^2 + 1) = (x-1)(x+1)(x-i)(x+i). There are 4 roots: 1, -1, i, -i."),
    make_q(28,"A physicist solves x^2 + 9 = 0 in a wave equation model. What are the solutions?",["3i and -3i","3 and -3","9i and -9i","No solutions"],0,
        "x^2 = -9, so x = +-sqrt(-9) = +-3i. The solutions are 3i and -3i."),
    make_q(29,"A control system polynomial is x^3 + x = 0. What are all the roots?",["0, i, and -i","0 only","i and -i only","0 and 1"],0,
        "Factor: x(x^2 + 1) = 0 gives x = 0 and x^2 = -1, so x = i and x = -i. Three roots total: 0, i, -i."),
    make_q(30,"A vibration analyst solves x^2 - 6x + 13 = 0 for natural frequencies. What are the roots?",["3 + 2i and 3 - 2i","6 + i and 6 - i","3 + 4i and 3 - 4i","2 + 3i and 2 - 3i"],0,
        "Using the quadratic formula: x = (6 +- sqrt(36 - 52))/2 = (6 +- sqrt(-16))/2 = (6 +- 4i)/2 = 3 +- 2i."),
]

# Lesson 3.7  Higher-Degree Polynomials
qs37 = [
    make_q(1,"What is the degree of f(x) = x^5 - 3x^3 + x - 7?",["5","3","7","1"],0,
        "The degree is the highest power of x, which is 5."),
    make_q(2,"How many complex roots (counting multiplicity) does a degree-6 polynomial have?",["6","5","12","3"],0,
        "By the Fundamental Theorem of Algebra, a degree-n polynomial has exactly n complex roots when counted with multiplicity."),
    make_q(3,"Factor x^4 - 16 completely over the reals.",["(x^2 + 4)(x - 2)(x + 2)","(x^2 - 4)(x^2 + 4)","(x - 2)^4","(x + 4)(x - 4)"],0,
        "x^4 - 16 = (x^2 - 4)(x^2 + 4) = (x - 2)(x + 2)(x^2 + 4). The factor x^2 + 4 is irreducible over the reals."),
    make_q(4,"What are the rational roots of f(x) = x^3 - 6x^2 + 11x - 6?",["1, 2, and 3","1, -2, and 3","-1, -2, and -3","1 and 6"],0,
        "Testing x = 1: 1 - 6 + 11 - 6 = 0. Factoring: (x-1)(x^2-5x+6) = (x-1)(x-2)(x-3). Roots are 1, 2, and 3."),
    make_q(5,"What is the maximum number of real roots a degree-5 polynomial can have?",["5","4","6","10"],0,
        "A polynomial of degree n can have at most n real roots. For degree 5, the maximum is 5."),
    make_q(6,"What are the possible rational roots of f(x) = x^3 + 2x^2 - x - 2 according to the Rational Root Theorem?",["+-1, +-2","+-1, +-2, +-3","+-2, +-4","+-1 only"],0,
        "Possible rational roots are +-p/q where p divides the constant term (2) and q divides the leading coefficient (1). So candidates are +-1 and +-2."),
    make_q(7,"Factor x^3 + 2x^2 - x - 2.",["(x + 2)(x - 1)(x + 1)","(x + 2)(x^2 + 1)","(x - 2)(x + 1)^2","(x + 2)^2(x - 1)"],0,
        "Testing x = 1: 1 + 2 - 1 - 2 = 0. Dividing gives (x - 1)(x^2 + 3x + 2) = (x - 1)(x + 1)(x + 2)."),
    make_q(8,"What is the end behavior of f(x) = 2x^6 - x^3 + 1?",["Rises on both ends","Falls on both ends","Rises left, falls right","Falls left, rises right"],0,
        "The leading term is 2x^6. Since the degree is even and the leading coefficient is positive, the graph rises on both ends."),
    make_q(9,"How many turning points does f(x) = x^5 have?",["0","4","5","1"],0,
        "f(x) = x^5 is a strictly increasing function with no local maxima or minima, so it has 0 turning points."),
    make_q(10,"Find all real roots of x^4 - 5x^2 + 4 = 0.",["1, -1, 2, -2","1, 2","2, -2","4, 1"],0,
        "Let u = x^2: u^2 - 5u + 4 = (u - 1)(u - 4) = 0. So x^2 = 1 or x^2 = 4, giving x = +-1, +-2."),
    make_q(11,"What does 'degree of a polynomial' mean?",["The highest power of the variable in the polynomial","The number of terms","The leading coefficient","The constant term"],0,
        "The degree is the largest exponent on the variable. It determines the polynomial's end behavior and the maximum number of roots."),
    make_q(12,"What is the 'Rational Root Theorem'?",["A theorem that lists all possible rational roots of a polynomial with integer coefficients","A theorem that finds all roots","A theorem about irrational numbers","A method for graphing"],0,
        "The Rational Root Theorem states that any rational root p/q of a polynomial with integer coefficients must have p dividing the constant term and q dividing the leading coefficient."),
    make_q(13,"What does 'Descartes' Rule of Signs' determine?",["The possible number of positive and negative real roots","The exact roots of a polynomial","The degree of a polynomial","The end behavior"],0,
        "Descartes' Rule of Signs uses the number of sign changes in f(x) and f(-x) to determine the possible number of positive and negative real roots."),
    make_q(14,"What is a 'higher-degree polynomial'?",["A polynomial of degree 3 or greater","A polynomial of degree 2","A linear polynomial","A constant polynomial"],0,
        "Higher-degree polynomials typically refer to those of degree 3 (cubic) or higher, which can have more complex behavior than quadratics."),
    make_q(15,"What does 'irreducible polynomial' mean?",["A polynomial that cannot be factored into polynomials of lower degree over the given number system","A polynomial with no terms","A polynomial equal to zero","A polynomial of degree 1"],0,
        "An irreducible polynomial cannot be written as a product of two non-constant polynomials over the specified number system (e.g., reals or rationals)."),
    make_q(16,"What is 'synthetic division'?",["A shortcut method for dividing a polynomial by a linear binomial (x - a)","A method for multiplying polynomials","A graphing technique","A way to find the degree"],0,
        "Synthetic division is an efficient algorithm for dividing a polynomial by (x - a) using only the coefficients, avoiding the full long division process."),
    make_q(17,"What does 'multiplicity' of a root mean?",["The number of times a root appears as a factor","The size of the root","The sign of the root","The degree of the polynomial"],0,
        "If (x - r)^k is a factor of a polynomial, then r is a root with multiplicity k. Multiplicity affects whether the graph crosses or touches the x-axis at that root."),
    make_q(18,"What is 'polynomial long division'?",["A method of dividing polynomials similar to long division of numbers","A way to multiply polynomials","A graphing method","A method for finding the degree"],0,
        "Polynomial long division systematically divides one polynomial by another, producing a quotient and remainder, analogous to integer long division."),
    make_q(19,"What are 'complex roots'?",["Roots that involve the imaginary unit i","Only real number roots","Roots that are very large","Roots of linear polynomials"],0,
        "Complex roots are solutions of the form a + bi where b is nonzero. They always occur in conjugate pairs for polynomials with real coefficients."),
    make_q(20,"What does 'factor theorem' state?",["(x - a) is a factor of f(x) if and only if f(a) = 0","All polynomials can be factored","Factoring is impossible for degree > 4","The factor equals the degree"],0,
        "The Factor Theorem connects roots and factors: (x - a) divides f(x) exactly when substituting x = a gives zero."),
    make_q(21,"A company models its revenue as R(x) = x^4 - 10x^3 + 35x^2 - 50x + 24 in thousands, where x is years. The Rational Root Theorem suggests testing x = 1, 2, 3, 4, 6, etc. Which of these is a root?",["x = 1","x = 5","x = 6","x = 10"],0,
        "R(1) = 1 - 10 + 35 - 50 + 24 = 0. So x = 1 is a root. The polynomial factors as (x-1)(x-2)(x-3)(x-4)."),
    make_q(22,"A biologist models a population as P(t) = t^5 - t. She factors this to find when the population is zero. What are the real roots?",["t = 0, 1, and -1","t = 0 and 1","t = 0 only","t = 1 and -1"],0,
        "Factor: t(t^4 - 1) = t(t^2 - 1)(t^2 + 1) = t(t - 1)(t + 1)(t^2 + 1). Real roots are 0, 1, and -1."),
    make_q(23,"An engineer models vibration as V(x) = x^4 - 13x^2 + 36. What are the real values of x where vibration is zero?",["x = 2, -2, 3, -3","x = 4, 9","x = 6, -6","x = 2, 3"],0,
        "Let u = x^2: u^2 - 13u + 36 = (u - 4)(u - 9) = 0. So x^2 = 4 or x^2 = 9, giving x = +-2 and x = +-3."),
    make_q(24,"A drug's concentration is modeled by C(t) = t^3 - 9t^2 + 26t - 24 mg/L, where t is hours. Using the Rational Root Theorem, find one root.",["t = 2","t = 5","t = 7","t = 12"],0,
        "C(2) = 8 - 36 + 52 - 24 = 0. So t = 2 is a root. Factoring gives (t-2)(t-3)(t-4), so all roots are 2, 3, and 4."),
    make_q(25,"A storage tank's volume function is V(x) = x^3 - 3x^2 - 4x + 12 cubic meters, where x is a dimension in meters. Factor this polynomial completely.",["(x - 3)(x - 2)(x + 2)","(x - 3)(x + 2)^2","(x + 3)(x - 2)(x + 2)","(x - 6)(x - 2)"],0,
        "V(3) = 27 - 27 - 12 + 12 = 0. Dividing by (x - 3): x^2 - 4 = (x - 2)(x + 2). So V(x) = (x - 3)(x - 2)(x + 2)."),
    make_q(26,"A projectile's path is modeled by h(t) = -t^4 + 5t^2 - 4. When does the projectile hit the ground (h = 0)?",["t = 1, -1, 2, -2","t = 1 and 2","t = 4 and 1","t = 0 and 5"],0,
        "-(t^4 - 5t^2 + 4) = -(t^2 - 1)(t^2 - 4) = -(t-1)(t+1)(t-2)(t+2) = 0. The zeros are t = +-1 and +-2."),
    make_q(27,"A financial model uses P(x) = x^3 - x^2 - 4x + 4. An analyst tests x = 1. Is it a root, and what are all the roots?",["Yes; roots are 1, 2, -2","Yes; roots are 1 and 4","No; x = 1 is not a root","Yes; roots are 1, -1, 4"],0,
        "P(1) = 1 - 1 - 4 + 4 = 0. Factoring: (x-1)(x^2-4) = (x-1)(x-2)(x+2). Roots are 1, 2, and -2."),
    make_q(28,"A bridge load function is L(x) = x^4 - 17x^2 + 16. What are the real roots?",["x = 1, -1, 4, -4","x = 1, 16","x = 4, -4","x = 2, 8"],0,
        "Let u = x^2: u^2 - 17u + 16 = (u - 1)(u - 16) = 0. So x^2 = 1 or x^2 = 16, giving x = +-1 and x = +-4."),
    make_q(29,"A chemical process is modeled by C(t) = t^3 + 6t^2 + 11t + 6. Using rational root testing, find all roots.",["t = -1, -2, -3","t = 1, 2, 3","t = -1, -6","t = -2, -3"],0,
        "C(-1) = -1 + 6 - 11 + 6 = 0. Dividing: (t + 1)(t^2 + 5t + 6) = (t + 1)(t + 2)(t + 3). Roots are -1, -2, -3."),
    make_q(30,"An architect models a curved roof as f(x) = x^4 - 10x^2 + 9. Where does the roof meet the base (f = 0)?",["x = 1, -1, 3, -3","x = 1, 9","x = 3, -3","x = 9, -9"],0,
        "Factor: (x^2 - 1)(x^2 - 9) = (x-1)(x+1)(x-3)(x+3) = 0. The roof meets the base at x = +-1 and x = +-3."),
]

print("Writing Unit 3 files...")
write_quiz(3, "3.4", "Polynomial Graphs & Zeros", qs34)
write_quiz(3, "3.5", "Remainder & Factor Theorems", qs35)
write_quiz(3, "3.6", "Complex Numbers & Polynomial Roots", qs36)
write_quiz(3, "3.7", "Higher-Degree Polynomials", qs37)
print("Unit 3 complete!")
