"""Add flashcards to all 98 Geometry lessons."""
import json, os

PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "content_data", "geometry_lessons.json")

FC = {
    # ── Unit 1: Foundations ──────────────────────────────────────────
    "u1_l1.1": [
        ("Point", "A location in space with no size or dimension; represented by a dot."),
        ("Line", "An infinite set of points extending in two directions; no width or thickness."),
        ("Plane", "A flat surface extending infinitely in all directions; defined by three non-collinear points."),
        ("Collinear", "Points that lie on the same line."),
        ("Coplanar", "Points or lines that lie in the same plane."),
    ],
    "u1_l1.2": [
        ("Segment", "A part of a line with two endpoints and a definite length."),
        ("Ray", "A part of a line with one endpoint extending infinitely in one direction."),
        ("Precision", "The degree of exactness of a measurement; depends on the measuring tool."),
        ("Betweenness", "Point B is between A and C if A, B, C are collinear and AB + BC = AC."),
        ("Congruent Segments", "Segments with equal lengths; denoted by ≅."),
    ],
    "u1_l1.3": [
        ("Distance Formula", "d = √[(x₂−x₁)² + (y₂−y₁)²]; finds the distance between two points on a coordinate plane."),
        ("Midpoint Formula", "M = ((x₁+x₂)/2, (y₁+y₂)/2); the point exactly halfway between two endpoints."),
        ("Segment Bisector", "A point, line, or ray that divides a segment into two congruent parts."),
        ("Absolute Value", "Used in the ruler postulate: AB = |a − b| where a and b are coordinates on a number line."),
        ("Number Line Distance", "Distance = |coordinate₁ − coordinate₂|."),
    ],
    "u1_l1.4": [
        ("Angle", "A figure formed by two rays sharing a common endpoint (vertex)."),
        ("Vertex", "The common endpoint of two rays forming an angle."),
        ("Acute Angle", "An angle measuring between 0° and 90°."),
        ("Right Angle", "An angle measuring exactly 90°."),
        ("Obtuse Angle", "An angle measuring between 90° and 180°."),
    ],
    "u1_l1.5": [
        ("Complementary Angles", "Two angles whose measures sum to 90°."),
        ("Supplementary Angles", "Two angles whose measures sum to 180°."),
        ("Vertical Angles", "Opposite angles formed by two intersecting lines; always congruent."),
        ("Linear Pair", "Two adjacent angles that form a straight line; supplementary (sum = 180°)."),
        ("Adjacent Angles", "Angles that share a common vertex and side but don't overlap."),
    ],
    "u1_l1.6": [
        ("Polygon", "A closed plane figure formed by three or more line segments (sides)."),
        ("Regular Polygon", "A polygon with all sides and angles congruent."),
        ("Convex Polygon", "All interior angles are less than 180°; no sides 'cave in.'"),
        ("Concave Polygon", "At least one interior angle is greater than 180°."),
        ("Perimeter", "The total distance around a polygon; sum of all side lengths."),
    ],
    "u1_l1.7": [
        ("Polyhedron", "A three-dimensional figure with flat polygonal faces."),
        ("Prism", "A polyhedron with two parallel, congruent bases connected by rectangles."),
        ("Pyramid", "A polyhedron with one polygonal base and triangular lateral faces meeting at an apex."),
        ("Cylinder", "A 3D figure with two parallel circular bases connected by a curved surface."),
        ("Sphere", "The set of all points equidistant from a center point in 3D space."),
    ],

    # ── Unit 2: Reasoning & Proof ───────────────────────────────────
    "u2_l2.1": [
        ("Inductive Reasoning", "Drawing general conclusions from specific observations or patterns."),
        ("Conjecture", "An unproven statement based on observations."),
        ("Counterexample", "A single example that disproves a conjecture."),
        ("Pattern Recognition", "Identifying a consistent rule from repeated observations."),
        ("Sequence", "An ordered list of numbers following a pattern."),
    ],
    "u2_l2.2": [
        ("Statement", "A sentence that is either true or false, but not both."),
        ("Negation", "The opposite of a statement; denoted ¬p or ~p."),
        ("Conjunction", "A compound statement using 'and' (p ∧ q); true only if both parts are true."),
        ("Disjunction", "A compound statement using 'or' (p ∨ q); true if at least one part is true."),
        ("Truth Table", "A table showing all possible truth values for a logical expression."),
    ],
    "u2_l2.3": [
        ("Conditional Statement", "An 'if-then' statement: p → q (hypothesis → conclusion)."),
        ("Converse", "Formed by switching the hypothesis and conclusion: q → p."),
        ("Inverse", "Negating both parts: ¬p → ¬q."),
        ("Contrapositive", "Negating and switching: ¬q → ¬p. Always has the same truth value as the original."),
        ("Biconditional", "'If and only if' (p ↔ q); true when both parts have the same truth value."),
    ],
    "u2_l2.4": [
        ("Deductive Reasoning", "Using logic and established facts to reach a specific conclusion."),
        ("Law of Detachment", "If p → q is true and p is true, then q is true."),
        ("Law of Syllogism", "If p → q and q → r, then p → r."),
        ("Valid Argument", "A logical argument where the conclusion follows necessarily from the premises."),
        ("Theorem", "A statement that has been proven true using deductive reasoning."),
    ],
    "u2_l2.5": [
        ("Postulate", "A statement accepted as true without proof (axiom)."),
        ("Paragraph Proof", "A proof written as a logical paragraph, citing postulates, definitions, and theorems."),
        ("Given", "The information provided at the start of a proof — the known facts."),
        ("Prove", "The statement you must demonstrate to be true at the end of the proof."),
        ("Definitions as Biconditionals", "Definitions can always be written as 'if and only if' statements."),
    ],
    "u2_l2.6": [
        ("Algebraic Proof", "A proof using algebraic properties (addition, subtraction, substitution, etc.)."),
        ("Reflexive Property", "a = a; any quantity is equal to itself."),
        ("Symmetric Property", "If a = b, then b = a."),
        ("Transitive Property", "If a = b and b = c, then a = c."),
        ("Substitution Property", "If a = b, then a can replace b in any expression."),
    ],
    "u2_l2.7": [
        ("Segment Addition Postulate", "If B is between A and C, then AB + BC = AC."),
        ("Midpoint Theorem", "If M is the midpoint of AB, then AM = MB."),
        ("Two-Column Proof", "A proof with numbered statements in one column and reasons in another."),
        ("Definition of Congruence", "Segments are congruent if and only if they have equal measures."),
        ("Ruler Postulate", "Points on a line can be paired with real numbers, and distance = |a − b|."),
    ],
    "u2_l2.8": [
        ("Angle Addition Postulate", "If D is in the interior of ∠ABC, then m∠ABD + m∠DBC = m∠ABC."),
        ("Congruent Supplements Theorem", "If two angles are supplementary to the same angle, they're congruent."),
        ("Congruent Complements Theorem", "If two angles are complementary to the same angle, they're congruent."),
        ("Vertical Angles Theorem", "Vertical angles are congruent."),
        ("Right Angle Congruence", "All right angles are congruent."),
    ],
    "u2_l2.9": [
        ("Coordinate Proof", "A proof using the coordinate plane, placing figures on axes and using formulas."),
        ("Placing Figures", "Strategically place shapes at the origin or along axes to simplify proofs."),
        ("Distance Formula in Proofs", "Used to show segments are congruent (equal length)."),
        ("Slope in Proofs", "Used to show lines are parallel (equal slopes) or perpendicular (negative reciprocal slopes)."),
        ("Midpoint in Proofs", "Used to show a point bisects a segment."),
    ],

    # ── Unit 3: Parallel & Perpendicular Lines ─────────────────────
    "u3_l3.1": [
        ("Transversal", "A line that intersects two or more lines at different points."),
        ("Corresponding Angles", "Angles in the same position at each intersection; congruent if lines are parallel."),
        ("Alternate Interior Angles", "Angles between the lines on opposite sides of the transversal; congruent if parallel."),
        ("Alternate Exterior Angles", "Angles outside the lines on opposite sides of the transversal; congruent if parallel."),
        ("Co-interior (Same-Side) Angles", "Angles between the lines on the same side; supplementary if parallel."),
    ],
    "u3_l3.2": [
        ("Parallel Lines", "Coplanar lines that never intersect; have equal slopes."),
        ("Corresponding Angles Postulate", "If a transversal cuts parallel lines, corresponding angles are congruent."),
        ("Alternate Interior Angles Theorem", "If a transversal cuts parallel lines, alternate interior angles are congruent."),
        ("Consecutive Interior Angles Theorem", "If a transversal cuts parallel lines, same-side interior angles are supplementary."),
        ("Perpendicular Transversal Theorem", "If a transversal is perpendicular to one parallel line, it's perpendicular to the other."),
    ],
    "u3_l3.3": [
        ("Slope", "Rise over run: m = (y₂ − y₁)/(x₂ − x₁)."),
        ("Parallel Slopes", "Parallel lines have identical slopes (m₁ = m₂)."),
        ("Perpendicular Slopes", "Perpendicular lines have slopes that are negative reciprocals (m₁ · m₂ = −1)."),
        ("Zero Slope", "A horizontal line has slope 0."),
        ("Undefined Slope", "A vertical line has undefined slope."),
    ],
    "u3_l3.4": [
        ("Slope-Intercept Form", "y = mx + b; m = slope, b = y-intercept."),
        ("Point-Slope Form", "y − y₁ = m(x − x₁); used when slope and one point are known."),
        ("Standard Form", "Ax + By = C; where A, B, C are integers and A > 0."),
        ("Y-Intercept", "The point where a line crosses the y-axis (0, b)."),
        ("X-Intercept", "The point where a line crosses the x-axis (x, 0)."),
    ],
    "u3_l3.5": [
        ("Converse of Corresponding Angles", "If corresponding angles are congruent, then the lines are parallel."),
        ("Converse of Alternate Interior", "If alternate interior angles are congruent, the lines are parallel."),
        ("Converse of Co-interior", "If co-interior angles are supplementary, the lines are parallel."),
        ("Proving Lines Parallel", "Show that angle pairs formed by a transversal satisfy parallel line theorems."),
        ("Flow Proof", "A proof that uses arrows to show the logical flow from given to conclusion."),
    ],
    "u3_l3.6": [
        ("Perpendicular Lines", "Lines that intersect at 90° angles."),
        ("Distance from Point to Line", "The length of the perpendicular segment from the point to the line."),
        ("Perpendicular Bisector", "A line perpendicular to a segment at its midpoint."),
        ("Distance Between Parallel Lines", "Measured along a perpendicular to both lines; constant everywhere."),
        ("Construction", "Using compass and straightedge to draw a perpendicular from a point to a line."),
    ],
    "u3_l3.7": [
        ("Analytic Geometry", "Using coordinates and algebra to prove geometric properties."),
        ("Coordinate Proof for Parallel Lines", "Show two lines have equal slopes to prove they're parallel."),
        ("Coordinate Proof for Perpendicular", "Show slopes are negative reciprocals to prove perpendicularity."),
        ("Application", "Verify properties of geometric figures placed on the coordinate plane."),
        ("Equation of a Perpendicular Bisector", "Find the midpoint and negative reciprocal slope, then write the equation."),
    ],

    # ── Unit 4: Congruent Triangles ─────────────────────────────────
    "u4_l4.1": [
        ("Scalene Triangle", "No sides congruent."),
        ("Isosceles Triangle", "At least two sides congruent."),
        ("Equilateral Triangle", "All three sides congruent (also equiangular: all angles 60°)."),
        ("Acute Triangle", "All angles are less than 90°."),
        ("Obtuse Triangle", "One angle is greater than 90°."),
    ],
    "u4_l4.2": [
        ("Triangle Angle Sum", "The sum of interior angles of any triangle is 180°."),
        ("Exterior Angle Theorem", "An exterior angle of a triangle equals the sum of the two non-adjacent interior angles."),
        ("Exterior Angle", "An angle formed by one side and the extension of an adjacent side."),
        ("Remote Interior Angles", "The two interior angles not adjacent to a given exterior angle."),
        ("Corollary", "The acute angles of a right triangle are complementary."),
    ],
    "u4_l4.3": [
        ("Congruent Triangles", "Triangles with all corresponding sides and angles congruent."),
        ("CPCTC", "Corresponding Parts of Congruent Triangles are Congruent."),
        ("Corresponding Parts", "Sides and angles in the same relative position in congruent figures."),
        ("Congruence Statement", "△ABC ≅ △DEF means A↔D, B↔E, C↔F for both angles and sides."),
        ("Third Angles Theorem", "If two angles of one triangle are congruent to two of another, the third angles are congruent."),
    ],
    "u4_l4.4": [
        ("SSS Postulate", "If three sides of one triangle are congruent to three sides of another, the triangles are congruent."),
        ("SAS Postulate", "If two sides and the included angle are congruent, the triangles are congruent."),
        ("Included Angle", "The angle formed between two given sides of a triangle."),
        ("Rigid Motion", "A transformation (translation, rotation, reflection) that preserves size and shape."),
        ("Triangle Rigidity", "A triangle is the only polygon determined by its side lengths."),
    ],
    "u4_l4.5": [
        ("ASA Postulate", "If two angles and the included side are congruent, the triangles are congruent."),
        ("AAS Theorem", "If two angles and a non-included side are congruent, the triangles are congruent."),
        ("Included Side", "The side between two given angles of a triangle."),
        ("HL Theorem", "For right triangles: if hypotenuse and one leg are congruent, the triangles are congruent."),
        ("Non-Congruence: SSA", "Two sides and a non-included angle do NOT guarantee congruence (ambiguous case)."),
    ],
    "u4_l4.6": [
        ("Isosceles Triangle Theorem", "If two sides of a triangle are congruent, the base angles are congruent."),
        ("Converse of Isosceles Theorem", "If two angles are congruent, the sides opposite them are congruent."),
        ("Equilateral = Equiangular", "A triangle is equilateral if and only if it is equiangular (each 60°)."),
        ("Base Angles", "The two angles adjacent to the base of an isosceles triangle."),
        ("Vertex Angle", "The angle opposite the base in an isosceles triangle."),
    ],
    "u4_l4.7": [
        ("Congruence Transformation", "A rigid motion that maps one figure onto a congruent figure."),
        ("Translation", "Slides a figure without rotating or reflecting it."),
        ("Rotation", "Turns a figure around a fixed point (center of rotation)."),
        ("Reflection", "Flips a figure over a line (line of reflection)."),
        ("Composition", "Performing two or more transformations in sequence."),
    ],
    "u4_l4.8": [
        ("Coordinate Proof for Triangles", "Placing a triangle on the coordinate plane and using formulas to prove properties."),
        ("Placing at Origin", "Set one vertex at the origin and one side along an axis to simplify calculations."),
        ("Using Variables", "Use variables (a, b) for coordinates to prove general statements."),
        ("Midpoint in Triangle Proofs", "Show a segment connects midpoints or bisects another."),
        ("Distance in Triangle Proofs", "Show sides are congruent by computing distances."),
    ],

    # ── Unit 5: Triangle Relationships ──────────────────────────────
    "u5_l5.1": [
        ("Perpendicular Bisector of a Triangle", "A segment perpendicular to a side at its midpoint."),
        ("Circumcenter", "The point where the three perpendicular bisectors meet; equidistant from all three vertices."),
        ("Angle Bisector", "A ray that divides an angle into two congruent angles."),
        ("Incenter", "The point where the three angle bisectors meet; equidistant from all three sides."),
        ("Circumscribed Circle", "A circle passing through all three vertices of a triangle; center = circumcenter."),
    ],
    "u5_l5.2": [
        ("Median", "A segment from a vertex to the midpoint of the opposite side."),
        ("Centroid", "The point where the three medians meet; divides each median in a 2:1 ratio."),
        ("Altitude", "A perpendicular segment from a vertex to the line containing the opposite side."),
        ("Orthocenter", "The point where the three altitudes meet."),
        ("Euler Line", "A line through the circumcenter, centroid, and orthocenter of a triangle."),
    ],
    "u5_l5.3": [
        ("Angle-Side Inequality", "In a triangle, the longer side is opposite the larger angle."),
        ("Side-Angle Inequality", "In a triangle, the larger angle is opposite the longer side."),
        ("Exterior Angle Inequality", "An exterior angle is greater than either non-adjacent interior angle."),
        ("Ordering Sides/Angles", "Compare angle measures to rank sides, or compare sides to rank angles."),
        ("Longest Side", "Opposite the largest angle."),
    ],
    "u5_l5.4": [
        ("Indirect Proof", "Proof by contradiction: assume the negation, derive a contradiction, conclude the original is true."),
        ("Proof by Contradiction", "Another name for indirect proof."),
        ("Negation", "The opposite of the statement to be proven."),
        ("Contradiction", "A logical impossibility that arises from the false assumption."),
        ("When to Use", "When a direct proof is hard — especially for 'not' or inequality statements."),
    ],
    "u5_l5.5": [
        ("Triangle Inequality Theorem", "The sum of any two sides must be greater than the third side."),
        ("Testing Triangle Formation", "Check all three pairs: a + b > c, a + c > b, b + c > a."),
        ("Shortest Distance", "A straight line — the triangle inequality in action."),
        ("Degenerate Triangle", "If a + b = c exactly, the 'triangle' is a straight line (not a valid triangle)."),
        ("Application", "Determine whether three given lengths can form a triangle."),
    ],
    "u5_l5.6": [
        ("Hinge Theorem (SAS Inequality)", "If two sides of one △ are ≅ to two sides of another, the larger included angle → longer third side."),
        ("Converse of Hinge Theorem", "If two sides of one △ are ≅ to two sides of another and the third sides differ, the larger third side → larger included angle."),
        ("Comparing Triangles", "Two triangles with two pairs of congruent sides; compare third side or included angle."),
        ("Application", "Determine which triangle has the longer side or larger angle."),
        ("Proof Structure", "Often uses indirect proof or the properties of isosceles triangles."),
    ],

    # ── Unit 6: Quadrilaterals ──────────────────────────────────────
    "u6_l6.1": [
        ("Interior Angle Sum", "(n − 2) × 180°; the sum of interior angles of an n-sided polygon."),
        ("Exterior Angle Sum", "Always 360° for any convex polygon."),
        ("Regular Polygon Interior Angle", "Each angle = (n − 2) × 180° / n."),
        ("Diagonal", "A segment connecting two non-adjacent vertices."),
        ("Number of Diagonals", "n(n − 3)/2 diagonals in an n-sided polygon."),
    ],
    "u6_l6.2": [
        ("Parallelogram", "A quadrilateral with both pairs of opposite sides parallel."),
        ("Opposite Sides Theorem", "Opposite sides of a parallelogram are congruent."),
        ("Opposite Angles Theorem", "Opposite angles of a parallelogram are congruent."),
        ("Consecutive Angles", "Consecutive angles of a parallelogram are supplementary."),
        ("Diagonals Bisect", "The diagonals of a parallelogram bisect each other."),
    ],
    "u6_l6.3": [
        ("Test for Parallelogram", "If both pairs of opposite sides are congruent, the quad is a parallelogram."),
        ("Diagonal Test", "If the diagonals bisect each other, the quad is a parallelogram."),
        ("One Pair Parallel & Congruent", "If one pair of sides is both parallel and congruent, it's a parallelogram."),
        ("Opposite Angles Test", "If both pairs of opposite angles are congruent, it's a parallelogram."),
        ("Coordinate Test", "Show both pairs of opposite sides have equal slopes and equal lengths."),
    ],
    "u6_l6.4": [
        ("Rectangle", "A parallelogram with four right angles."),
        ("Rectangle Diagonals", "Diagonals of a rectangle are congruent (and bisect each other)."),
        ("Test for Rectangle", "A parallelogram with one right angle is a rectangle."),
        ("Diagonal Test for Rectangle", "A parallelogram with congruent diagonals is a rectangle."),
        ("Properties of Rectangle", "Opposite sides ≅, opposite angles ≅, diagonals ≅ and bisect each other."),
    ],
    "u6_l6.5": [
        ("Rhombus", "A parallelogram with all four sides congruent."),
        ("Rhombus Diagonals", "Diagonals of a rhombus are perpendicular and bisect each other."),
        ("Square", "A rectangle AND a rhombus — all sides ≅, all angles 90°, diagonals ≅ and ⊥."),
        ("Diagonal Bisects Angles", "Each diagonal of a rhombus bisects a pair of opposite angles."),
        ("Test for Rhombus", "A parallelogram with one pair of consecutive sides congruent is a rhombus."),
    ],
    "u6_l6.6": [
        ("Trapezoid", "A quadrilateral with exactly one pair of parallel sides (bases)."),
        ("Isosceles Trapezoid", "A trapezoid with congruent legs; base angles are congruent, diagonals are congruent."),
        ("Midsegment of Trapezoid", "Connects the midpoints of the legs; parallel to bases and length = (b₁ + b₂)/2."),
        ("Kite", "A quadrilateral with two pairs of consecutive congruent sides (no pair of opposite sides ≅)."),
        ("Kite Diagonals", "Perpendicular; one diagonal bisects the other."),
    ],
    "u6_l6.7": [
        ("Regular Polygon", "All sides and all angles are congruent; both equilateral and equiangular."),
        ("Line Symmetry", "A regular n-gon has n lines of symmetry."),
        ("Rotational Symmetry", "A regular n-gon has rotational symmetry of 360°/n."),
        ("Apothem", "The perpendicular distance from the center to the midpoint of a side."),
        ("Center of Regular Polygon", "Equidistant from all vertices and all sides."),
    ],

    # ── Unit 7: Similarity ──────────────────────────────────────────
    "u7_l7.1": [
        ("Ratio", "A comparison of two quantities: a/b or a:b."),
        ("Proportion", "An equation stating two ratios are equal: a/b = c/d."),
        ("Cross Products", "In a proportion a/b = c/d, ad = bc."),
        ("Means and Extremes", "In a:b = c:d, b and c are means; a and d are extremes."),
        ("Properties of Proportions", "If a/b = c/d, then ad = bc, a/c = b/d, and (a+b)/b = (c+d)/d."),
    ],
    "u7_l7.2": [
        ("Similar Polygons", "Polygons with the same shape: corresponding angles ≅ and corresponding sides proportional."),
        ("Scale Factor", "The ratio of corresponding side lengths of similar polygons."),
        ("Similarity Statement", "△ABC ~ △DEF; order indicates corresponding vertices."),
        ("Perimeters of Similar Polygons", "The ratio of perimeters equals the scale factor."),
        ("Similarity vs Congruence", "Similar = same shape, possibly different size. Congruent = same shape AND size."),
    ],
    "u7_l7.3": [
        ("AA Similarity", "If two angles of one triangle are congruent to two of another, the triangles are similar."),
        ("SSS Similarity", "If all three pairs of corresponding sides are proportional, the triangles are similar."),
        ("SAS Similarity", "If two pairs of sides are proportional and the included angles are congruent, similar."),
        ("Indirect Measurement", "Using similar triangles to calculate distances that can't be measured directly."),
        ("Shadow Method", "Using similar triangles formed by shadows to find heights."),
    ],
    "u7_l7.4": [
        ("Triangle Proportionality Theorem", "If a line parallel to one side of a triangle intersects the other two sides, it divides them proportionally."),
        ("Converse of Triangle Proportionality", "If a line divides two sides proportionally, it's parallel to the third side."),
        ("Midsegment Theorem", "A midsegment is parallel to the third side and half its length."),
        ("Three Parallel Lines", "If three parallels cut two transversals, they divide them proportionally."),
        ("Proportional Parts", "Parallel lines create proportional segments on transversals."),
    ],
    "u7_l7.5": [
        ("Angle Bisector Proportion Theorem", "An angle bisector divides the opposite side proportionally to the adjacent sides."),
        ("Altitude to Hypotenuse", "In a right triangle, the altitude to the hypotenuse creates two similar triangles."),
        ("Geometric Mean (in triangles)", "In a right triangle with altitude h to hypotenuse c: h² = (segment₁)(segment₂)."),
        ("Similar Triangle Altitudes", "Corresponding altitudes of similar triangles have the same ratio as corresponding sides."),
        ("Similar Triangle Medians", "Medians of similar triangles are proportional to corresponding sides."),
    ],
    "u7_l7.6": [
        ("Dilation", "A transformation that enlarges or reduces a figure by a scale factor from a center point."),
        ("Similarity Transformation", "A combination of rigid motions and a dilation."),
        ("Center of Dilation", "The fixed point from which a dilation is performed."),
        ("Scale Factor > 1", "Enlargement — the image is larger than the pre-image."),
        ("Scale Factor < 1", "Reduction — the image is smaller than the pre-image."),
    ],
    "u7_l7.7": [
        ("Scale Drawing", "A drawing in which all dimensions are proportional to the actual object."),
        ("Scale", "The ratio of a length in the drawing to the actual length (e.g., 1 cm : 10 m)."),
        ("Scale Model", "A three-dimensional representation at a consistent scale."),
        ("Application", "Architects, engineers, and mapmakers use scale drawings."),
        ("Converting Scale", "Multiply drawing measurement by the scale factor to find actual dimension."),
    ],
    "u7_l7.8": [
        ("Fractal", "A geometric figure where each part is a reduced-scale copy of the whole."),
        ("Self-Similarity", "A property where parts of a figure are similar to the whole."),
        ("Iteration", "The process of repeating a set of rules to generate a fractal."),
        ("Sierpinski Triangle", "A fractal made by repeatedly removing the center triangle from equilateral triangles."),
        ("Koch Snowflake", "A fractal made by adding equilateral triangles to each side of a figure, infinitely."),
    ],

    # ── Unit 8: Right Triangles & Trigonometry ──────────────────────
    "u8_l8.1": [
        ("Geometric Mean", "For a and b: GM = √(ab); used in right triangle altitude relationships."),
        ("Altitude on Hypotenuse Theorem", "The altitude to the hypotenuse creates two triangles similar to each other and to the original."),
        ("Leg as Geometric Mean", "Each leg is the geometric mean of the hypotenuse and its adjacent segment."),
        ("Altitude as Geometric Mean", "The altitude is the geometric mean of the two segments of the hypotenuse."),
        ("Application", "Finding missing lengths in right triangles using proportions."),
    ],
    "u8_l8.2": [
        ("Pythagorean Theorem", "a² + b² = c²; relates the legs and hypotenuse of a right triangle."),
        ("Hypotenuse", "The longest side of a right triangle, opposite the right angle."),
        ("Pythagorean Triple", "Three positive integers a, b, c where a² + b² = c² (e.g., 3-4-5, 5-12-13)."),
        ("Converse of Pythagorean Theorem", "If a² + b² = c², the triangle is right. If a² + b² > c², acute. If <, obtuse."),
        ("Distance Formula Origin", "Derived from the Pythagorean Theorem applied to coordinate geometry."),
    ],
    "u8_l8.3": [
        ("45-45-90 Triangle", "Legs are congruent; hypotenuse = leg × √2."),
        ("30-60-90 Triangle", "Sides in ratio 1 : √3 : 2 (short leg : long leg : hypotenuse)."),
        ("Short Leg (30-60-90)", "Opposite the 30° angle; hypotenuse = 2 × short leg."),
        ("Long Leg (30-60-90)", "Opposite the 60° angle; long leg = short leg × √3."),
        ("Application", "These triangles appear in equilateral triangle splits and square diagonal cuts."),
    ],
    "u8_l8.4": [
        ("Sine", "sin θ = opposite / hypotenuse."),
        ("Cosine", "cos θ = adjacent / hypotenuse."),
        ("Tangent", "tan θ = opposite / adjacent."),
        ("SOH-CAH-TOA", "Mnemonic: Sine = Opposite/Hypotenuse, Cosine = Adjacent/Hypotenuse, Tangent = Opposite/Adjacent."),
        ("Inverse Trig Functions", "sin⁻¹, cos⁻¹, tan⁻¹ find the angle given a ratio."),
    ],
    "u8_l8.5": [
        ("Angle of Elevation", "The angle formed from the horizontal looking upward to an object."),
        ("Angle of Depression", "The angle formed from the horizontal looking downward to an object."),
        ("Application", "Use trig ratios to find heights or distances from angles of elevation/depression."),
        ("Equal Angles", "Angle of elevation from one point equals angle of depression from the other (alternate interior)."),
        ("Horizontal Line", "The reference line from which elevation and depression are measured."),
    ],
    "u8_l8.6": [
        ("Law of Sines", "a/sin A = b/sin B = c/sin C; used for non-right triangles."),
        ("Law of Cosines", "c² = a² + b² − 2ab cos C; generalizes the Pythagorean theorem."),
        ("Ambiguous Case (SSA)", "May have 0, 1, or 2 triangle solutions when using Law of Sines."),
        ("Solving Oblique Triangles", "Use Law of Sines (AAS, ASA) or Law of Cosines (SAS, SSS)."),
        ("Area with Sine", "Area = ½ ab sin C; uses two sides and the included angle."),
    ],
    "u8_l8.7": [
        ("Vector", "A quantity with both magnitude (size) and direction."),
        ("Magnitude", "The length of a vector; |v| = √(x² + y²)."),
        ("Direction", "The angle a vector makes with the positive x-axis."),
        ("Component Form", "A vector written as ⟨x, y⟩."),
        ("Vector Addition", "⟨a, b⟩ + ⟨c, d⟩ = ⟨a+c, b+d⟩; graphically: tip-to-tail method."),
    ],
    "u8_l8.8": [
        ("Polar Coordinates", "(r, θ) where r is distance from origin and θ is angle from positive x-axis."),
        ("Converting Polar to Rectangular", "x = r cos θ, y = r sin θ."),
        ("Converting Rectangular to Polar", "r = √(x² + y²), θ = arctan(y/x)."),
        ("Complex Number", "a + bi; plotted on the complex plane (real axis, imaginary axis)."),
        ("Polar Form of Complex Numbers", "z = r(cos θ + i sin θ) = r cis θ."),
    ],

    # ── Unit 9: Transformations ─────────────────────────────────────
    "u9_l9.1": [
        ("Reflection", "A transformation that flips a figure over a line of reflection."),
        ("Line of Reflection", "The 'mirror line'; every point and its image are equidistant from this line."),
        ("Reflection over x-axis", "(x, y) → (x, −y)."),
        ("Reflection over y-axis", "(x, y) → (−x, y)."),
        ("Reflection over y = x", "(x, y) → (y, x)."),
    ],
    "u9_l9.2": [
        ("Translation", "A transformation that slides every point the same distance and direction."),
        ("Translation Rule", "(x, y) → (x + a, y + b)."),
        ("Translation Vector", "⟨a, b⟩ describes the horizontal and vertical shift."),
        ("Isometry", "A transformation that preserves distance (reflections, translations, rotations)."),
        ("Image vs Pre-image", "Pre-image: the original figure. Image: the transformed figure (prime notation: A')."),
    ],
    "u9_l9.3": [
        ("Rotation", "A transformation that turns a figure around a center point."),
        ("Center of Rotation", "The fixed point around which the figure rotates."),
        ("90° Rotation (CCW)", "(x, y) → (−y, x)."),
        ("180° Rotation", "(x, y) → (−x, −y)."),
        ("270° Rotation (CCW)", "(x, y) → (y, −x)."),
    ],
    "u9_l9.4": [
        ("Composition of Transformations", "Performing two or more transformations in sequence."),
        ("Glide Reflection", "A translation followed by a reflection along the direction of translation."),
        ("Two Reflections over Parallel Lines", "Equivalent to a single translation."),
        ("Two Reflections over Intersecting Lines", "Equivalent to a single rotation."),
        ("Order Matters", "The order of transformations can affect the final image."),
    ],
    "u9_l9.5": [
        ("Line Symmetry", "A figure has line symmetry if a line can divide it into two mirror-image halves."),
        ("Rotational Symmetry", "A figure maps onto itself after a rotation of less than 360°."),
        ("Order of Symmetry", "The number of times a figure maps onto itself during a 360° rotation."),
        ("Point Symmetry", "Rotational symmetry of order 2 (180° rotation maps figure to itself)."),
        ("Axis of Symmetry", "The line of reflection for line symmetry."),
    ],
    "u9_l9.6": [
        ("Dilation", "A transformation that resizes a figure by a scale factor from a center."),
        ("Scale Factor (k)", "k > 1: enlargement. 0 < k < 1: reduction. k = 1: congruent."),
        ("Center of Dilation", "The fixed point from which distances are measured and scaled."),
        ("Coordinate Rule", "(x, y) → (kx, ky) for dilation centered at the origin."),
        ("Similar Figures", "Dilations produce similar figures (same shape, proportional sides)."),
    ],
    "u9_l9.7": [
        ("Transformation Notation", "T: (x, y) → (x', y'); describes the rule mapping each point."),
        ("Coordinate Plane Transformations", "All transformations can be described with coordinate rules."),
        ("Matrix Representation", "Transformations can be expressed as matrix multiplications."),
        ("Preserving Orientation", "Translations and rotations preserve orientation; reflections reverse it."),
        ("Mapping", "Pairing each point of the pre-image with its corresponding image point."),
    ],

    # ── Unit 10: Circles ────────────────────────────────────────────
    "u10_l10.1": [
        ("Circle", "The set of all points equidistant from a center point; distance = radius."),
        ("Radius", "A segment from the center to any point on the circle."),
        ("Diameter", "A chord passing through the center; d = 2r."),
        ("Circumference", "C = 2πr = πd; the distance around a circle."),
        ("Chord", "A segment with both endpoints on the circle."),
    ],
    "u10_l10.2": [
        ("Central Angle", "An angle with its vertex at the center of the circle."),
        ("Arc", "A portion of the circle between two points."),
        ("Minor Arc", "An arc less than 180°; named by two letters."),
        ("Major Arc", "An arc greater than 180°; named by three letters."),
        ("Arc Measure", "The measure of a minor arc equals the measure of its central angle."),
    ],
    "u10_l10.3": [
        ("Arc Length", "The distance along an arc; s = (θ/360°) × 2πr."),
        ("Congruent Arcs", "Arcs with equal measures in the same or congruent circles."),
        ("Chord-Arc Relationship", "Congruent chords have congruent arcs, and vice versa."),
        ("Equidistant Chords", "Chords equidistant from the center are congruent."),
        ("Perpendicular from Center to Chord", "Bisects the chord and its arc."),
    ],
    "u10_l10.4": [
        ("Inscribed Angle", "An angle with its vertex on the circle; formed by two chords."),
        ("Inscribed Angle Theorem", "An inscribed angle is half the measure of its intercepted arc."),
        ("Intercepted Arc", "The arc that lies in the interior of an inscribed angle."),
        ("Semicircle Inscribed Angle", "An angle inscribed in a semicircle is 90°."),
        ("Inscribed Quadrilateral", "Opposite angles of a quadrilateral inscribed in a circle are supplementary."),
    ],
    "u10_l10.5": [
        ("Tangent", "A line that touches the circle at exactly one point."),
        ("Point of Tangency", "The point where a tangent meets the circle."),
        ("Tangent-Radius Relationship", "A tangent is perpendicular to the radius at the point of tangency."),
        ("Tangent from External Point", "Two tangent segments from the same external point are congruent."),
        ("Common Tangent", "A line tangent to two circles (external or internal)."),
    ],
    "u10_l10.6": [
        ("Secant", "A line that intersects a circle at two points."),
        ("Secant-Secant Angle", "Angle = ½|arc₁ − arc₂| when vertex is outside the circle."),
        ("Secant-Tangent Angle", "Angle = ½|arc₁ − arc₂| with vertex outside."),
        ("Two Tangents Angle", "Angle = ½|major arc − minor arc|."),
        ("Chord-Chord Angle", "Angle = ½(arc₁ + arc₂) when two chords intersect inside the circle."),
    ],
    "u10_l10.7": [
        ("Chord-Chord Product", "If two chords intersect inside: (seg₁)(seg₂) = (seg₃)(seg₄)."),
        ("Secant-Secant Product", "From outside: (whole₁)(external₁) = (whole₂)(external₂)."),
        ("Secant-Tangent Product", "(whole secant)(external) = (tangent)²."),
        ("Power of a Point", "The common value of these products for a given point."),
        ("Application", "Finding unknown segment lengths using these relationships."),
    ],
    "u10_l10.8": [
        ("Standard Form of Circle Equation", "(x − h)² + (y − k)² = r²; center (h, k), radius r."),
        ("General Form", "x² + y² + Dx + Ey + F = 0; convert by completing the square."),
        ("Completing the Square", "Technique to rewrite general form into standard form."),
        ("Center and Radius from Equation", "Read directly from standard form: center = (h, k), radius = √(r²)."),
        ("Graphing a Circle", "Plot center, mark radius in all directions, draw smooth curve."),
    ],
    "u10_l10.9": [
        ("Conic Sections", "Curves formed by a plane intersecting a cone: circle, ellipse, parabola, hyperbola."),
        ("Ellipse", "An oval shape defined by two foci; sum of distances from any point to foci is constant."),
        ("Parabola", "The set of points equidistant from a focus and a directrix."),
        ("Hyperbola", "Two open curves; difference of distances from any point to two foci is constant."),
        ("Degenerate Conics", "Point, line, or intersecting lines formed when the plane passes through the apex."),
    ],

    # ── Unit 11: Area ───────────────────────────────────────────────
    "u11_l11.1": [
        ("Area of Parallelogram", "A = bh; base × height."),
        ("Area of Triangle", "A = ½bh; half base × height."),
        ("Base and Height", "Height is always perpendicular to the base."),
        ("Altitude", "The perpendicular distance from the base to the opposite vertex (= height)."),
        ("Units of Area", "Area is measured in square units (cm², m², in², ft²)."),
    ],
    "u11_l11.2": [
        ("Area of Trapezoid", "A = ½(b₁ + b₂)h; average of bases × height."),
        ("Area of Rhombus", "A = ½d₁d₂; half the product of the diagonals."),
        ("Area of Kite", "A = ½d₁d₂; same formula as rhombus."),
        ("Height of a Trapezoid", "The perpendicular distance between the two parallel bases."),
        ("Bases of a Trapezoid", "The two parallel sides."),
    ],
    "u11_l11.3": [
        ("Area of Circle", "A = πr²."),
        ("Sector", "A 'pie slice' of a circle bounded by two radii and an arc."),
        ("Area of Sector", "A = (θ/360°) × πr²."),
        ("Segment of a Circle", "Region between a chord and its arc; area = sector area − triangle area."),
        ("Annulus", "The region between two concentric circles; area = π(R² − r²)."),
    ],
    "u11_l11.4": [
        ("Area of Regular Polygon", "A = ½ap; apothem × perimeter / 2."),
        ("Apothem", "The perpendicular distance from the center to the midpoint of a side."),
        ("Composite Figure", "A figure made up of two or more basic shapes."),
        ("Area of Composite Figure", "Break into basic shapes, find each area, then add (or subtract)."),
        ("Perimeter of Regular Polygon", "p = n × s; number of sides × side length."),
    ],
    "u11_l11.5": [
        ("Area Ratio of Similar Figures", "If scale factor is k, area ratio is k²."),
        ("Perimeter Ratio", "If scale factor is k, perimeter ratio is k."),
        ("Finding Missing Areas", "If two figures are similar with known scale factor, A₂ = k² × A₁."),
        ("Similar Figures", "Same shape, proportional sides — areas scale by the square of the side ratio."),
        ("Application", "Scaling models: double the dimensions → quadruple the area."),
    ],
    "u11_l11.6": [
        ("Integration Concept", "Area under a curve found by summing infinitely thin rectangles."),
        ("Approximation with Rectangles", "Estimate curved areas using inscribed or circumscribed rectangles."),
        ("Riemann Sum", "Approximation: Σ f(xᵢ)Δx."),
        ("More Rectangles = Better", "Increasing the number of rectangles improves the approximation."),
        ("Connection to Calculus", "The definite integral gives the exact area under a curve."),
    ],

    # ── Unit 12: Surface Area & Volume ──────────────────────────────
    "u12_l12.1": [
        ("Net", "A 2D pattern that folds into a 3D figure."),
        ("Orthographic Drawing", "Views of a 3D object from the front, top, and side."),
        ("Isometric View", "A 3D representation on a flat surface showing three faces."),
        ("Cross Section", "The shape formed when a plane intersects a solid."),
        ("Euler's Formula", "V − E + F = 2; relates vertices, edges, and faces of polyhedra."),
    ],
    "u12_l12.2": [
        ("Surface Area of Prism", "SA = 2B + Ph; two bases + lateral area."),
        ("Lateral Area of Prism", "LA = Ph; perimeter of base × height."),
        ("Surface Area of Cylinder", "SA = 2πr² + 2πrh."),
        ("Lateral Area of Cylinder", "LA = 2πrh; the curved surface 'unrolled' is a rectangle."),
        ("Right vs Oblique", "In a right prism/cylinder, the lateral faces are perpendicular to the bases."),
    ],
    "u12_l12.3": [
        ("Surface Area of Pyramid", "SA = B + ½Pl; base area + half perimeter × slant height."),
        ("Slant Height", "The distance from the apex to the midpoint of a base edge (along a face)."),
        ("Surface Area of Cone", "SA = πr² + πrl; base + lateral."),
        ("Lateral Area of Cone", "LA = πrl; where l is the slant height."),
        ("Slant Height of Cone", "l = √(r² + h²); related by the Pythagorean theorem."),
    ],
    "u12_l12.4": [
        ("Volume of Prism", "V = Bh; base area × height."),
        ("Volume of Cylinder", "V = πr²h."),
        ("Base Area (B)", "The area of the base shape (rectangle, triangle, circle, etc.)."),
        ("Height", "The perpendicular distance between the two bases."),
        ("Units of Volume", "Measured in cubic units (cm³, m³, in³, ft³)."),
    ],
    "u12_l12.5": [
        ("Volume of Pyramid", "V = ⅓Bh; one-third base area × height."),
        ("Volume of Cone", "V = ⅓πr²h."),
        ("Relationship to Prism/Cylinder", "A pyramid/cone has ⅓ the volume of a prism/cylinder with the same base and height."),
        ("Oblique Cone/Pyramid", "Same volume formula applies — Cavalieri's Principle."),
        ("Application", "Calculating volumes of roofs, ice cream cones, pyramids."),
    ],
    "u12_l12.6": [
        ("Surface Area of Sphere", "SA = 4πr²."),
        ("Volume of Sphere", "V = ⁴⁄₃πr³."),
        ("Great Circle", "The cross section with the largest area; passes through the center. A = πr²."),
        ("Hemisphere", "Half a sphere; V = ⅔πr³, SA = 3πr²."),
        ("Application", "Calculating volumes of balls, globes, tanks."),
    ],
    "u12_l12.7": [
        ("Spherical Geometry", "Geometry on the surface of a sphere; 'lines' are great circles."),
        ("Geodesic", "The shortest path between two points on a sphere (arc of a great circle)."),
        ("Spherical Triangle", "A triangle on a sphere bounded by arcs of great circles; angle sum > 180°."),
        ("Non-Euclidean", "Spherical geometry violates Euclid's parallel postulate (no parallel lines exist)."),
        ("Application", "Navigation, air travel routes, GPS systems."),
    ],
    "u12_l12.8": [
        ("Congruent Solids", "Solids with the same shape and size — all corresponding dimensions are equal."),
        ("Similar Solids", "Solids with the same shape but possibly different size; corresponding ratios are equal."),
        ("Surface Area Ratio", "If scale factor is k, SA ratio is k²."),
        ("Volume Ratio", "If scale factor is k, volume ratio is k³."),
        ("Application", "Doubling all dimensions: SA × 4, Volume × 8."),
    ],
    "u12_l12.9": [
        ("Cavalieri's Principle", "If two solids have equal cross-sectional areas at every height, they have equal volumes."),
        ("Cross-Sectional Area", "The area of the shape formed when a plane cuts through a solid."),
        ("Oblique Prism/Cylinder", "Same volume as right prism/cylinder with same base and height (Cavalieri)."),
        ("Application", "Justifies volume formulas for oblique figures."),
        ("Comparison Method", "Compare cross sections of two solids at each height to prove equal volumes."),
    ],

    # ── Unit 13: Probability ────────────────────────────────────────
    "u13_l13.1": [
        ("Sample Space", "The set of all possible outcomes of an experiment."),
        ("Event", "A subset of the sample space — a specific outcome or set of outcomes."),
        ("Outcome", "A single possible result of an experiment."),
        ("Tree Diagram", "A visual showing all possible outcomes using branching paths."),
        ("Fundamental Counting Principle", "If event A has m outcomes and event B has n, there are m × n total outcomes."),
    ],
    "u13_l13.2": [
        ("Permutation", "An arrangement where order matters: P(n, r) = n!/(n−r)!"),
        ("Combination", "A selection where order does NOT matter: C(n, r) = n!/[r!(n−r)!]."),
        ("Factorial", "n! = n × (n−1) × … × 1; 0! = 1."),
        ("When to Use Permutations", "When the ORDER of selection matters (rankings, passwords)."),
        ("When to Use Combinations", "When only the GROUP matters, not the order (committees, lottery)."),
    ],
    "u13_l13.3": [
        ("Geometric Probability", "Probability based on areas, lengths, or volumes rather than counting outcomes."),
        ("Length Probability", "P = favorable length / total length."),
        ("Area Probability", "P = favorable area / total area."),
        ("Random Point", "A point chosen randomly, with equal likelihood anywhere in the region."),
        ("Application", "Dart boards, landing zones, spinner problems."),
    ],
    "u13_l13.4": [
        ("Simulation", "A model of a real-world situation used to estimate probabilities."),
        ("Random Number Generator", "A tool that produces unpredictable numbers for simulations."),
        ("Trial", "One complete run of a simulation."),
        ("Experimental Probability", "P = (# times event occurs) / (total # of trials)."),
        ("Theoretical vs Experimental", "Theoretical is calculated; experimental is observed from data."),
    ],
    "u13_l13.5": [
        ("Independent Events", "The outcome of one event does NOT affect the other; P(A and B) = P(A) × P(B)."),
        ("Dependent Events", "The outcome of one affects the other; P(A and B) = P(A) × P(B|A)."),
        ("Conditional Probability", "P(B|A): the probability of B given that A has occurred."),
        ("With Replacement", "After drawing, the item is returned — events are independent."),
        ("Without Replacement", "After drawing, the item is NOT returned — events are dependent."),
    ],
    "u13_l13.6": [
        ("Mutually Exclusive Events", "Events that cannot happen at the same time; P(A and B) = 0."),
        ("Addition Rule (Mutually Exclusive)", "P(A or B) = P(A) + P(B)."),
        ("General Addition Rule", "P(A or B) = P(A) + P(B) − P(A and B)."),
        ("Non-Mutually Exclusive", "Events that CAN occur simultaneously; must subtract the overlap."),
        ("Complement", "P(A') = 1 − P(A); the probability of 'not A.'"),
    ],
    "u13_l13.7": [
        ("Monte Carlo Method", "Using random sampling to estimate mathematical results."),
        ("Estimating π", "Inscribe circle in square; ratio of hits inside circle ≈ π/4."),
        ("Area Estimation", "Randomly scatter points; ratio of favorable points ≈ ratio of areas."),
        ("Large Number of Trials", "More trials give estimates closer to the true value (Law of Large Numbers)."),
        ("Application", "Used in physics, finance, and computer science for complex probability problems."),
    ],
}

# ── Write ──
with open(PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

count = 0
for key, cards in FC.items():
    if key in data:
        data[key]["flashcards"] = [{"term": t, "definition": d} for t, d in cards]
        count += 1

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"✅ Added flashcards to {count} Geometry lessons")
