import json, os

def q(num, text, correct, wrong1, wrong2, wrong3, explanation):
    return {
        "question_number": num,
        "question_text": text,
        "attempted": 2,
        "data_i18n": None,
        "options": [
            {"text": correct, "is_correct": True, "data_i18n": None},
            {"text": wrong1, "is_correct": False, "data_i18n": None},
            {"text": wrong2, "is_correct": False, "data_i18n": None},
            {"text": wrong3, "is_correct": False, "data_i18n": None}
        ],
        "explanation": explanation
    }

def write_quiz(unit, lesson, title, questions):
    path = f"content_data/AstronomyLessons/Unit{unit}/Lesson{lesson}_Quiz.json"
    data = {
        "unit": unit,
        "lesson_number": lesson,
        "title": title,
        "course": "Astronomy",
        "quiz_questions": questions
    }
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  Wrote {path} ({len(questions)} questions)")

# ============================================================
# UNIT 4: THE SUN
# ============================================================
print("=== Unit 4 ===")

# 4.1 Structure of the Sun
write_quiz(4, "4.1", "Structure of the Sun", [
    # Easy (1-10)
    q(1, "What is the innermost layer of the Sun called?", "Core", "Photosphere", "Corona", "Chromosphere",
      "The core is the Sun's central region where nuclear fusion occurs."),
    q(2, "Which layer of the Sun do we actually see?", "Photosphere", "Core", "Corona", "Radiative zone",
      "The photosphere is the visible surface of the Sun."),
    q(3, "The Sun's core temperature is approximately:", "~15 million K", "5,800 K", "100,000 K", "1 billion K",
      "The core reaches about 15 million Kelvin, hot enough for hydrogen fusion."),
    q(4, "Which layer lies between the core and the convective zone?", "Radiative zone", "Photosphere", "Chromosphere", "Corona",
      "Energy travels outward through the radiative zone by radiation before reaching the convective zone."),
    q(5, "What process transports energy in the convective zone?", "Convection", "Radiation", "Conduction", "Fission",
      "Hot plasma rises and cooler plasma sinks in convection cells within the convective zone."),
    q(6, "The chromosphere is located:", "Between the photosphere and corona", "Below the core", "Inside the radiative zone", "Beyond the corona",
      "The chromosphere is a thin layer between the photosphere and the outer corona."),
    q(7, "What color does the chromosphere appear during a total solar eclipse?", "Reddish-pink", "Bright white", "Blue", "Green",
      "The chromosphere emits a reddish-pink glow visible during total eclipses due to hydrogen-alpha emission."),
    q(8, "The corona is the Sun's:", "Outermost atmospheric layer", "Central core", "Visible surface", "Inner atmosphere",
      "The corona is the Sun's outermost atmosphere, extending millions of kilometers into space."),
    q(9, "Which part of the Sun is the coolest?", "Photosphere", "Core", "Corona", "Radiative zone",
      "The photosphere at ~5,800 K is the coolest layer compared to the core and corona."),
    q(10, "What is the Sun primarily composed of?", "Hydrogen and helium", "Iron and nickel", "Oxygen and nitrogen", "Carbon and silicon",
      "The Sun is about 73% hydrogen and 25% helium by mass."),
    # Vocabulary (11-20)
    q(11, "What is the photosphere?", "The visible surface layer of the Sun", "The Sun's magnetic field region", "The hottest part of the Sun", "The outermost layer of the Sun",
      "The photosphere is the layer of the Sun that emits visible light and appears as the solar 'surface.'"),
    q(12, "What is the radiative zone?", "The layer where energy moves outward by photon absorption and re-emission", "The region where convection occurs", "The visible surface", "The outermost atmosphere",
      "In the radiative zone, energy slowly moves outward as photons are repeatedly absorbed and re-emitted."),
    q(13, "What is the convective zone?", "The layer where energy is transported by rising and sinking plasma", "The innermost layer of the Sun", "The magnetic field boundary", "A layer only visible during eclipses",
      "In the convective zone, hot plasma rises to the surface and cooler plasma sinks, carrying energy outward."),
    q(14, "What is the corona?", "The Sun's extremely hot outer atmosphere", "The nuclear fusion region", "The visible surface of the Sun", "A layer between the core and radiative zone",
      "The corona is the Sun's outermost atmosphere with temperatures exceeding 1 million K."),
    q(15, "What is the chromosphere?", "A thin atmospheric layer between the photosphere and corona", "The core of the Sun", "The convective interior", "The region where solar wind originates",
      "The chromosphere is a thin, reddish layer above the photosphere, visible during eclipses."),
    q(16, "What is granulation?", "A pattern of convection cells visible on the Sun's surface", "A type of solar flare", "The texture of the corona", "A process in nuclear fusion",
      "Granulation refers to the cell-like pattern on the photosphere caused by convection below the surface."),
    q(17, "What does 'helioseismology' study?", "Oscillations and waves in the Sun to probe its interior", "Solar magnetic field reversals", "The chemical composition of the corona", "Sunspot formation cycles",
      "Helioseismology uses sound waves traveling through the Sun to map its internal structure."),
    q(18, "What is the tachocline?", "The boundary between the radiative and convective zones", "The outermost layer of the corona", "The center of the Sun's core", "A type of solar prominence",
      "The tachocline is the transition region where the Sun's rotation changes from uniform to differential."),
    q(19, "What are spicules?", "Jet-like features extending from the chromosphere", "Bright spots on the photosphere", "Dark regions in the corona", "Waves in the radiative zone",
      "Spicules are dynamic, jet-like structures of plasma shooting up from the chromosphere into the corona."),
    q(20, "What is differential rotation?", "The phenomenon where different parts of the Sun rotate at different speeds", "The Sun orbiting the galaxy", "Earth's rotation affecting solar observations", "The rotation of sunspots only",
      "Because the Sun is gaseous, its equator rotates faster (~25 days) than its poles (~35 days)."),
    # Scenario (21-30)
    q(21, "A scientist measures the Sun's surface temperature at 5,800 K but finds the corona exceeds 1 million K. What is this mystery called?", "The coronal heating problem", "Solar wind paradox", "Photospheric anomaly", "Nuclear temperature inversion",
      "The coronal heating problem is one of solar physics' biggest puzzles — why the corona is hundreds of times hotter than the surface."),
    q(22, "During a total solar eclipse, you observe a faint white glow around the blocked Sun. What are you seeing?", "The corona", "The chromosphere", "The photosphere", "The radiative zone",
      "The corona becomes visible as a pearly white halo during total solar eclipses when the bright photosphere is blocked."),
    q(23, "A solar observatory detects that sound waves travel faster through one region of the Sun. What can scientists infer?", "That region is hotter or denser", "That region has no magnetic field", "The Sun is shrinking", "A solar flare is imminent",
      "Sound wave speed depends on temperature and density, so faster waves indicate hotter or denser material — a key principle of helioseismology."),
    q(24, "If the convective zone suddenly stopped transporting energy, what would happen to the Sun's surface?", "It would gradually cool and dim", "It would instantly explode", "Nothing would change", "It would become hotter",
      "Without convection bringing hot material to the surface, the photosphere would lose its energy source and cool."),
    q(25, "Astronomers notice that granules on the Sun's surface are about 1,000 km across and last about 20 minutes. What process causes them?", "Convection cells rising from below the photosphere", "Magnetic field oscillations", "Nuclear reactions at the surface", "Tidal forces from planets",
      "Granules are the tops of convection cells where hot plasma rises, spreads, cools, and sinks at the edges."),
    q(26, "A spacecraft measures the Sun's rotation period as 25 days at the equator and 35 days at the poles. What does this demonstrate?", "Differential rotation", "Uniform rotation", "Precession", "Retrograde motion",
      "This difference in rotation rate at different latitudes is called differential rotation, possible because the Sun is not solid."),
    q(27, "A researcher analyzing solar spectra notices absorption lines in the photosphere's light. What do these lines reveal?", "The chemical composition of the photosphere", "The temperature of the core", "The speed of solar wind", "The age of the Sun",
      "Absorption lines (Fraunhofer lines) in the photosphere's spectrum reveal which elements are present in the solar atmosphere."),
    q(28, "You observe the Sun through a special H-alpha filter and see red features shooting upward. What layer and features are you observing?", "Chromosphere and spicules", "Corona and flares", "Photosphere and granules", "Core and fusion reactions",
      "H-alpha filters reveal the chromosphere, where reddish spicules — jet-like plasma features — extend upward."),
    q(29, "If the Sun's core temperature dropped below 10 million K, what process would slow or stop?", "Hydrogen fusion", "Convection", "Solar wind emission", "Photospheric granulation",
      "Hydrogen fusion (the proton-proton chain) requires temperatures above about 10 million K to overcome electrostatic repulsion."),
    q(30, "A new satellite detects waves propagating through the Sun's interior. Scientists use this data to map the Sun's inner structure. What technique is this?", "Helioseismology", "Spectroscopy", "Photometry", "Astrometry",
      "Helioseismology uses oscillation data to probe the Sun's interior, similar to how seismology maps Earth's interior.")
])

# 4.2 Nuclear Fusion
write_quiz(4, "4.2", "Nuclear Fusion", [
    q(1, "What is the primary nuclear reaction occurring in the Sun's core?", "Hydrogen fusion (proton-proton chain)", "Uranium fission", "Helium fusion", "Carbon-nitrogen-oxygen cycle only",
      "The Sun primarily fuses hydrogen into helium via the proton-proton (pp) chain."),
    q(2, "What is the net product of the proton-proton chain?", "Helium-4", "Carbon-12", "Iron-56", "Lithium-7",
      "Four hydrogen nuclei fuse to produce one helium-4 nucleus, plus energy and neutrinos."),
    q(3, "What provides the energy released in nuclear fusion?", "Mass converted to energy (E=mc²)", "Chemical bonds breaking", "Gravitational collapse", "Magnetic field energy",
      "A small amount of mass is lost during fusion and converted to energy according to Einstein's E=mc²."),
    q(4, "What particle is released during the proton-proton chain that barely interacts with matter?", "Neutrino", "Neutron", "Electron", "Photon",
      "Neutrinos are produced during fusion and pass through matter almost unimpeded."),
    q(5, "Why does fusion require extremely high temperatures?", "To overcome the electrostatic repulsion between protons", "To melt hydrogen into liquid", "To ionize helium", "To create magnetic fields",
      "Protons are positively charged and repel each other; extreme heat gives them enough kinetic energy to overcome this repulsion."),
    q(6, "About how long does it take a photon produced in the core to reach the Sun's surface?", "Thousands to hundreds of thousands of years", "A few seconds", "One day", "About one year",
      "Photons are absorbed and re-emitted countless times in the radiative zone, taking a very long time to reach the surface."),
    q(7, "What keeps the Sun from collapsing under its own gravity?", "Outward radiation pressure from fusion", "Magnetic fields", "Rotation", "Dark energy",
      "The outward pressure from fusion energy balances against gravitational collapse — this is hydrostatic equilibrium."),
    q(8, "In more massive stars, what fusion cycle becomes dominant over the pp chain?", "CNO cycle", "Triple-alpha process", "R-process", "S-process",
      "In stars more massive than the Sun, the carbon-nitrogen-oxygen (CNO) cycle is the dominant hydrogen fusion pathway."),
    q(9, "How much mass does the Sun convert to energy every second?", "About 4 million tonnes", "About 400 kg", "About 1 billion tonnes", "About 100 tonnes",
      "The Sun converts roughly 4 million tonnes of mass into energy every second through fusion."),
    q(10, "What will the Sun eventually fuse after it exhausts its hydrogen core?", "Helium", "Carbon", "Iron", "Uranium",
      "After hydrogen core fusion ends, the Sun will fuse helium into carbon in its red giant phase."),
    # Vocabulary (11-20)
    q(11, "What is nuclear fusion?", "The process of combining lighter atomic nuclei to form heavier ones, releasing energy", "Splitting heavy atoms into lighter ones", "Chemical burning of hydrogen", "Radioactive decay of elements",
      "Nuclear fusion joins lighter nuclei (like hydrogen) into heavier nuclei (like helium), releasing enormous energy."),
    q(12, "What is the proton-proton chain?", "A series of fusion reactions converting hydrogen into helium in the Sun's core", "A chain of protons orbiting the Sun", "A magnetic field pattern", "A type of solar wind particle stream",
      "The proton-proton chain is the dominant fusion process in the Sun, converting four protons into one helium-4 nucleus."),
    q(13, "What is hydrostatic equilibrium?", "The balance between inward gravitational force and outward pressure in a star", "The state when a star stops rotating", "Chemical equilibrium in the solar atmosphere", "The balance of positive and negative charges",
      "Hydrostatic equilibrium keeps the Sun stable: gravity pulls inward while radiation and gas pressure push outward."),
    q(14, "What is a positron?", "The antimatter counterpart of an electron", "A proton with extra charge", "A neutral particle", "A heavy hydrogen isotope",
      "A positron (e⁺) is produced during fusion; it immediately annihilates with an electron, releasing energy."),
    q(15, "What is the mass defect?", "The difference in mass between reactants and products in a nuclear reaction", "A flaw in the Sun's structure", "The mass of a neutrino", "The loss of mass due to solar wind",
      "The mass defect is the 'missing' mass converted into energy during fusion, as described by E=mc²."),
    q(16, "What is the CNO cycle?", "A fusion process using carbon, nitrogen, and oxygen as catalysts to convert hydrogen to helium", "A cycle of coronal mass ejections", "The orbital cycle of carbon-rich asteroids", "A type of nuclear fission",
      "The CNO cycle uses C, N, and O as catalysts; they are not consumed but facilitate hydrogen-to-helium fusion."),
    q(17, "What is luminosity?", "The total amount of energy a star emits per unit time", "The brightness as seen from Earth", "The color of a star", "The size of a star's core",
      "Luminosity is the intrinsic total power output of a star, measured in watts or solar luminosities."),
    q(18, "What is quantum tunneling?", "The phenomenon where particles pass through energy barriers they classically couldn't overcome", "A tunnel dug by neutrinos", "Light bending around a star", "Sound waves in the Sun's core",
      "Quantum tunneling allows protons to fuse at temperatures lower than classical physics would predict by 'tunneling' through the Coulomb barrier."),
    q(19, "What is a neutrino?", "A nearly massless, electrically neutral subatomic particle produced in fusion", "A small neutron star", "A photon emitted by the chromosphere", "A fragment of helium",
      "Neutrinos are elusive particles produced in fusion reactions that rarely interact with matter."),
    q(20, "What is binding energy?", "The energy required to disassemble a nucleus into its component protons and neutrons", "The energy holding electrons in orbit", "Gravitational energy of a star", "Magnetic energy in sunspots",
      "Binding energy per nucleon determines whether fusion or fission releases energy; iron-56 has the highest binding energy per nucleon."),
    # Scenario (21-30)
    q(21, "If the Sun's core temperature were to double, what would happen to the fusion rate?", "It would increase dramatically", "It would stay the same", "It would decrease", "Fusion would stop",
      "The fusion rate is extremely sensitive to temperature — even small increases lead to dramatically higher rates."),
    q(22, "Scientists detect fewer neutrinos from the Sun than predicted. What was the resolution to this 'solar neutrino problem'?", "Neutrinos oscillate between three types during travel", "The Sun is not fusing hydrogen", "Neutrinos are absorbed by Earth", "The detectors were broken",
      "Neutrino oscillation — the ability of neutrinos to change 'flavor' — explained why fewer electron neutrinos were detected than expected."),
    q(23, "A star 10 times the Sun's mass fuses hydrogen much faster. What is the main consequence?", "It has a much shorter lifespan", "It lives longer than the Sun", "It never leaves the main sequence", "It becomes a white dwarf immediately",
      "More massive stars burn through their fuel much faster due to higher core temperatures and pressures, living millions (not billions) of years."),
    q(24, "If fusion in the Sun's core suddenly stopped, how long before the surface showed changes?", "Thousands to millions of years", "Immediately", "A few hours", "About one week",
      "It takes a very long time for energy changes in the core to propagate to the surface through the radiative and convective zones."),
    q(25, "Engineers want to replicate the Sun's fusion on Earth. Why is this extremely difficult?", "Containing plasma at millions of degrees is an enormous engineering challenge", "Hydrogen is too rare on Earth", "Fusion produces dangerous radiation", "Gravity is too strong on Earth",
      "Achieving and containing the extreme temperatures and pressures needed for sustained fusion is the primary challenge for fusion reactors."),
    q(26, "You calculate that 0.7% of the hydrogen mass is converted to energy during fusion in the Sun. Using E=mc², if 600 million tonnes of hydrogen fuse per second, how much energy is released?", "About 3.8 × 10²⁶ watts", "About 100 watts", "About 1 million watts", "About 10²⁰ watts",
      "0.7% of 600 million tonnes × c² gives approximately 3.8 × 10²⁶ W, which is the Sun's luminosity."),
    q(27, "A researcher proposes fusing iron nuclei to produce energy. Why won't this work?", "Iron has the highest binding energy per nucleon; fusing it absorbs energy", "Iron is too heavy to exist in stars", "Iron fusion produces neutrinos", "Iron cannot be heated enough",
      "Iron-56 sits at the peak of the binding energy curve. Fusing elements heavier than iron requires energy input rather than releasing it."),
    q(28, "The Sun loses 4 million tonnes of mass each second to fusion. At this rate, how has this affected the Sun over 4.6 billion years?", "It has lost less than 0.1% of its total mass", "It has lost half its mass", "It has lost 10% of its mass", "The mass loss is negligible — less than a millionth",
      "Even at 4 million tonnes/second over billions of years, the total mass lost is only a tiny fraction of the Sun's enormous mass."),
    q(29, "A star begins fusing helium into carbon. What process is this?", "Triple-alpha process", "Proton-proton chain", "CNO cycle", "Beta decay",
      "The triple-alpha process combines three helium-4 nuclei (alpha particles) into one carbon-12 nucleus."),
    q(30, "If you could somehow observe the neutrinos coming from the Sun's core, what would they tell you about conditions there right now?", "Current core fusion rates and conditions, since neutrinos escape almost immediately", "Conditions from thousands of years ago", "Only surface temperature", "Nothing — neutrinos carry no information",
      "Unlike photons, neutrinos escape the core in seconds, providing a real-time window into current fusion conditions.")
])

# 4.3 Solar Activity
write_quiz(4, "4.3", "Solar Activity (Sunspots, Flares, Prominences)", [
    q(1, "What are sunspots?", "Dark, cooler regions on the Sun's photosphere caused by magnetic activity", "Holes in the Sun", "Volcanic eruptions on the Sun", "Shadows cast by planets",
      "Sunspots appear dark because they are cooler (~3,500-4,500 K) than the surrounding photosphere due to intense magnetic fields."),
    q(2, "How long is the typical solar cycle?", "About 11 years", "About 1 year", "About 100 years", "About 50 years",
      "The solar activity cycle, including sunspot number variation, averages about 11 years from minimum to minimum."),
    q(3, "What is a solar flare?", "A sudden, intense burst of radiation from the Sun's surface", "A dark spot on the Sun", "A slow-moving prominence", "A shadow on the chromosphere",
      "Solar flares are sudden releases of magnetic energy that produce intense radiation across the electromagnetic spectrum."),
    q(4, "What is a solar prominence?", "A large, bright loop of plasma extending from the Sun's surface", "A type of sunspot", "A comet near the Sun", "A dark region in the corona",
      "Prominences are large, arching structures of plasma held above the Sun's surface by magnetic fields."),
    q(5, "What causes sunspots to appear dark?", "They are cooler than surrounding regions due to strong magnetic fields", "They are holes in the Sun", "They reflect less light", "They are farther from the core",
      "Strong magnetic fields in sunspots inhibit convection, making them ~1,500 K cooler and thus darker than the surrounding photosphere."),
    q(6, "What is a coronal mass ejection (CME)?", "A massive burst of solar wind and magnetic fields from the corona", "A sunspot disappearing", "Light emitted by the corona", "A solar eclipse",
      "CMEs are large expulsions of plasma and magnetic field from the Sun's corona into interplanetary space."),
    q(7, "During solar maximum, what happens to sunspot numbers?", "They increase significantly", "They decrease to zero", "They remain constant", "They appear only at the poles",
      "Solar maximum is the phase with the highest number of sunspots, flares, and CMEs."),
    q(8, "The Maunder Minimum refers to:", "A period of very few sunspots from ~1645-1715", "The minimum temperature of the Sun", "The smallest known solar flare", "The closest distance between Earth and Sun",
      "The Maunder Minimum was a 70-year period of unusually low sunspot activity, coinciding with the 'Little Ice Age.'"),
    q(9, "Solar flares can disrupt:", "Radio communications and GPS on Earth", "The Moon's orbit", "Jupiter's magnetic field", "The Sun's core temperature",
      "Solar flares produce radiation that can interfere with radio signals, GPS accuracy, and satellite electronics."),
    q(10, "Sunspots typically appear in pairs because:", "They mark where magnetic field lines exit and re-enter the photosphere", "They always form at the equator", "They are caused by planet alignments", "The Sun has two cores",
      "Sunspot pairs represent the two ends of a magnetic flux tube — one with north polarity and one with south."),
    # Vocabulary (11-20)
    q(11, "What is the solar cycle?", "The approximately 11-year cycle of solar magnetic activity and sunspot frequency", "The Sun's daily rotation", "The Sun's orbit around the galaxy", "The cycle of solar eclipses",
      "The solar cycle is the periodic variation in the Sun's activity (sunspots, flares, CMEs) with an ~11 year period."),
    q(12, "What is a coronal mass ejection (CME)?", "A large release of plasma and magnetic field from the Sun's corona", "A small solar flare", "A type of sunspot", "Visible light from the corona",
      "CMEs eject billions of tons of magnetized plasma into space, potentially causing geomagnetic storms at Earth."),
    q(13, "What is solar maximum?", "The phase of the solar cycle with the most sunspots and activity", "When the Sun is closest to Earth", "The hottest recorded solar temperature", "A period of no solar flares",
      "Solar maximum features peak sunspot numbers, frequent flares, and elevated CME activity."),
    q(14, "What is solar minimum?", "The phase of the solar cycle with the fewest sunspots and lowest activity", "When the Sun is farthest from Earth", "The coldest the Sun can get", "A total solar eclipse",
      "Solar minimum is the quiet phase with few sunspots and reduced solar activity."),
    q(15, "What are magnetic field lines?", "Imaginary lines representing the direction and strength of a magnetic field", "Visible lines on the Sun's surface", "Streams of neutrinos", "Lines connecting sunspots to planets",
      "Magnetic field lines map the magnetic field's direction; on the Sun, they drive sunspot formation and solar activity."),
    q(16, "What is a solar prominence?", "A large loop of plasma anchored in the photosphere and extending into the corona", "A bright spot on the photosphere", "A type of comet", "A dark coronal hole",
      "Prominences are plasma structures supported by magnetic fields, visible as bright arches above the solar limb."),
    q(17, "What is a coronal hole?", "A region of the corona with lower density and open magnetic field lines", "A hole in the Sun's core", "A dark sunspot", "A region with no solar wind",
      "Coronal holes have open magnetic field lines allowing fast solar wind to escape, appearing dark in X-ray images."),
    q(18, "What is the Carrington Event?", "A massive solar storm in 1859 that caused widespread telegraph failures", "The first sunspot observation", "A comet impact on the Sun", "The discovery of nuclear fusion",
      "The Carrington Event was one of the most powerful geomagnetic storms ever recorded, caused by a massive CME."),
    q(19, "What does 'magnetic reconnection' mean?", "The breaking and reconnecting of magnetic field lines, releasing energy", "Magnets connecting to the Sun", "Earth's magnetic field connecting to the Moon", "Two sunspots merging",
      "Magnetic reconnection occurs when opposing magnetic field lines break and rejoin, explosively releasing stored energy — powering flares and CMEs."),
    q(20, "What is space weather?", "Conditions in space driven by solar activity that affect Earth and technology", "Weather on other planets", "The temperature of outer space", "Rain inside spacecraft",
      "Space weather encompasses solar wind, CMEs, flares, and their effects on Earth's magnetosphere, satellites, and communications."),
    # Scenario (21-30)
    q(21, "A large CME is heading toward Earth. What protective action might power grid operators take?", "Reduce load on vulnerable transformers and prepare for potential shutdowns", "Turn off all satellites", "Move power lines underground immediately", "Do nothing since CMEs can't affect Earth",
      "Geomagnetically induced currents from CMEs can damage transformers, so operators may preemptively reduce loads."),
    q(22, "An astronomer notices sunspots migrating from high latitudes toward the equator over several years. What pattern is this?", "Spörer's law (butterfly diagram)", "Random walk", "Polar migration", "Coronal hole movement",
      "Over a solar cycle, sunspots first appear at higher latitudes and gradually appear closer to the equator — Spörer's Law, visualized as a butterfly diagram."),
    q(23, "During solar maximum, astronauts on the ISS are advised to shelter in protected areas. Why?", "Increased solar particle radiation poses health risks", "The ISS orbit decays faster", "The Sun appears too bright", "Solar wind pushes the ISS",
      "Solar maximum brings more frequent flares and CMEs, increasing radiation levels that can be dangerous to astronauts."),
    q(24, "A compass needle fluctuates wildly during a geomagnetic storm. What solar event likely caused this?", "A coronal mass ejection impacting Earth's magnetosphere", "A sunspot appearing", "A solar eclipse", "The Moon blocking solar wind",
      "CME-driven geomagnetic storms disturb Earth's magnetic field, causing compass variations and beautiful auroras."),
    q(25, "Scientists find that a period of very low sunspot activity correlates with colder temperatures in Europe. What historical event does this resemble?", "The Maunder Minimum and the Little Ice Age", "The Carrington Event", "The formation of the Sun", "A recent solar maximum",
      "The Maunder Minimum (1645-1715) had very few sunspots and coincided with unusually cold European temperatures."),
    q(26, "You observe a solar prominence that suddenly erupts outward. What might it become?", "A coronal mass ejection", "A new sunspot", "A solar flare", "A comet",
      "When prominences become unstable and erupt, the ejected plasma can form a CME."),
    q(27, "A satellite's electronics suddenly malfunction during a solar flare. What type of radiation likely caused the damage?", "High-energy X-rays and charged particles", "Visible light", "Infrared radiation", "Radio waves",
      "Solar flares emit X-rays and energetic particles that can damage satellite electronics and disrupt operations."),
    q(28, "An aurora is observed as far south as Florida. What does this indicate?", "An unusually powerful geomagnetic storm from a large CME", "The Sun is closer to Earth", "Earth's magnetic field has disappeared", "A normal solar minimum event",
      "Auroras at low latitudes indicate an extremely strong geomagnetic storm pushing the aurora oval far from the poles."),
    q(29, "If the Sun's magnetic field suddenly reversed polarity, what would change about the sunspot cycle?", "This normally happens every ~11 years as part of the full ~22-year magnetic cycle", "Sunspots would permanently disappear", "The Sun would explode", "Nothing — polarity doesn't affect sunspots",
      "The Sun's magnetic field reverses every ~11 years at solar maximum, making the full magnetic cycle ~22 years."),
    q(30, "A new space telescope detects a coronal hole sending fast solar wind toward Earth. When might the effects be felt?", "In about 2-4 days", "Immediately", "In about 1 year", "Never — solar wind can't reach Earth",
      "Fast solar wind from coronal holes travels at 600-800 km/s, reaching Earth in roughly 2-4 days.")
])

# 4.4 Solar Wind & Magnetic Fields
write_quiz(4, "4.4", "Solar Wind & Magnetic Fields", [
    q(1, "What is the solar wind?", "A stream of charged particles (plasma) flowing from the Sun", "Wind on the Sun's surface", "A breeze felt in space", "Light emitted from the Sun",
      "The solar wind is a continuous flow of charged particles (mostly protons and electrons) from the Sun's corona."),
    q(2, "What is the typical speed of the slow solar wind?", "~400 km/s", "~10 km/s", "~1,000 km/s", "~3,000 km/s",
      "The slow solar wind travels at roughly 400 km/s, while the fast solar wind can reach 600-800 km/s."),
    q(3, "Where does the fast solar wind primarily originate?", "Coronal holes", "Sunspots", "The core", "The photosphere",
      "Fast solar wind streams originate from coronal holes where magnetic field lines are open to interplanetary space."),
    q(4, "What protects Earth from the solar wind?", "Earth's magnetic field (magnetosphere)", "The atmosphere alone", "The ozone layer", "The Moon",
      "Earth's magnetosphere deflects most solar wind particles, protecting the atmosphere and surface."),
    q(5, "What causes auroras?", "Solar wind particles interacting with Earth's magnetic field and atmosphere", "Reflected sunlight from ice crystals", "Lightning in the upper atmosphere", "Moonlight refracting",
      "Charged particles from the solar wind are channeled by Earth's magnetic field to the poles, where they excite atmospheric gases."),
    q(6, "The heliosphere is:", "The region of space dominated by the solar wind", "The Sun's visible surface", "A layer inside the Sun", "The orbit of Neptune",
      "The heliosphere is the vast bubble of space influenced by the solar wind, extending far beyond Pluto."),
    q(7, "What is the boundary of the heliosphere called?", "Heliopause", "Heliocenter", "Corona", "Magnetopause",
      "The heliopause is where the solar wind's outward pressure is balanced by interstellar medium pressure."),
    q(8, "Which spacecraft first crossed the heliopause?", "Voyager 1", "Voyager 2", "Pioneer 10", "New Horizons",
      "Voyager 1 crossed the heliopause in 2012, becoming the first human-made object to enter interstellar space."),
    q(9, "The Sun's magnetic field is generated by:", "Dynamo processes in the convective zone", "Nuclear fusion", "Solar wind interactions", "External cosmic forces",
      "The solar dynamo generates the Sun's magnetic field through the motion of electrically conducting plasma in the convective zone."),
    q(10, "What shape does the interplanetary magnetic field take?", "A Parker spiral", "A straight line from the Sun", "A series of rings", "Random patterns",
      "Because the Sun rotates while emitting solar wind, the magnetic field lines form an Archimedean (Parker) spiral."),
    # Vocabulary (11-20)
    q(11, "What is the magnetosphere?", "The region around a planet dominated by its magnetic field", "The Sun's magnetic field", "A layer of the atmosphere", "The space between planets",
      "Earth's magnetosphere is the magnetic 'shield' that deflects solar wind and protects the planet."),
    q(12, "What is the heliosphere?", "The bubble of space filled with the Sun's solar wind", "The visible disk of the Sun", "A type of telescope", "The Sun's core region",
      "The heliosphere extends beyond the orbits of all planets, enclosing the entire solar system in solar wind."),
    q(13, "What is the heliopause?", "The boundary where solar wind pressure equals interstellar medium pressure", "The surface of the Sun", "The edge of the Milky Way", "A type of solar eclipse",
      "The heliopause marks where the Sun's influence ends and interstellar space begins."),
    q(14, "What is the Parker spiral?", "The spiral shape of the interplanetary magnetic field due to the Sun's rotation", "A galaxy shape", "A type of solar flare pattern", "A comet's orbit",
      "Named after Eugene Parker, this spiral pattern results from the Sun's rotation winding the magnetic field lines."),
    q(15, "What are Van Allen radiation belts?", "Zones of trapped charged particles held by Earth's magnetic field", "Belts of asteroids", "Layers of the Sun's atmosphere", "Magnetic field lines on the Sun",
      "The Van Allen belts are regions where energetic charged particles are trapped by Earth's magnetosphere."),
    q(16, "What is a geomagnetic storm?", "A disturbance of Earth's magnetic field caused by solar wind impacts", "An earthquake caused by magnets", "A storm on the Sun", "A change in Earth's rotation",
      "Geomagnetic storms occur when CMEs or fast solar wind streams disturb Earth's magnetosphere."),
    q(17, "What is the bow shock?", "The boundary where solar wind first decelerates upon encountering a planet's magnetosphere", "A type of sound wave in space", "The shape of a comet's tail", "A shockwave from a supernova",
      "The bow shock is analogous to the wave in front of a boat — it's where supersonic solar wind abruptly slows."),
    q(18, "What is the magnetopause?", "The boundary between a planet's magnetosphere and the solar wind", "The center of a planet's magnetic field", "A pause in magnetic activity", "The heliopause",
      "The magnetopause is the outer edge of the magnetosphere where the magnetic field balances solar wind pressure."),
    q(19, "What is the magnetotail?", "The elongated portion of a planet's magnetosphere stretched by solar wind", "A comet's tail", "The Sun's magnetic pole", "A type of aurora",
      "Solar wind pressure compresses the magnetosphere on the dayside and stretches it into a long tail on the nightside."),
    q(20, "What is the solar dynamo?", "The process generating the Sun's magnetic field through convective plasma motion", "A type of solar panel", "A generator on a spacecraft", "The Sun's gravitational pull",
      "The solar dynamo converts kinetic energy of plasma motion into magnetic field energy through electromagnetic induction."),
    # Scenario (21-30)
    q(21, "Voyager 1 detected a sharp increase in cosmic rays and a decrease in solar particles. What boundary did it cross?", "The heliopause", "Earth's magnetopause", "The asteroid belt", "Jupiter's magnetosphere",
      "Increased cosmic rays and decreased solar particles indicated Voyager 1 had left the heliosphere and entered interstellar space."),
    q(22, "During a strong geomagnetic storm, airline routes over the poles are diverted. Why?", "Increased radiation exposure and communication blackouts at high latitudes", "The poles are too cold", "Aircraft can't fly over ice", "Magnetic fields interfere with jet engines",
      "Polar routes expose aircraft to higher radiation during geomagnetic storms, and HF radio communications often fail at high latitudes."),
    q(23, "You notice auroras are visible much farther south than usual. What can you infer about the solar wind conditions?", "A powerful CME or fast solar wind stream is compressing Earth's magnetosphere", "The solar wind has stopped", "Earth's magnetic field has strengthened", "It's solar minimum",
      "Auroras at lower latitudes indicate the magnetosphere is being compressed by strong solar wind, pushing the aurora oval equatorward."),
    q(24, "A spacecraft traveling to Mars encounters the solar wind. How does the solar wind intensity compare to what it is at Earth?", "It is weaker because solar wind density decreases with distance squared", "It is stronger at Mars", "It is exactly the same", "There is no solar wind at Mars",
      "Solar wind density and pressure decrease roughly as the inverse square of distance from the Sun."),
    q(25, "Scientists discover that Mars has a very thin atmosphere compared to Earth. How does the absence of a global magnetic field explain this?", "Without a magnetosphere, solar wind directly strips away atmospheric particles", "Magnetic fields trap atmosphere", "Mars is too cold for atmosphere", "Mars's gravity is too weak alone",
      "Mars lost its global magnetic field billions of years ago, allowing solar wind to erode its atmosphere over time."),
    q(26, "During a solar particle event, astronauts on a Moon mission need to protect themselves. What is the best approach?", "Shelter behind shielding material or in a protected habitat", "Wear sunglasses", "Go outside to observe", "Turn off all electronics",
      "Without Earth's magnetosphere, lunar astronauts must rely on physical shielding to protect against energetic solar particles."),
    q(27, "A comet's ion tail always points away from the Sun regardless of its direction of travel. What causes this?", "The solar wind pushes ionized gas away from the Sun", "Gravity from the Sun", "The comet's rotation", "Light pressure only",
      "The solar wind exerts a force on the comet's ionized gases, sweeping the ion tail radially away from the Sun."),
    q(28, "If the Sun suddenly stopped emitting solar wind, what would eventually happen to the heliosphere?", "It would shrink and collapse as interstellar medium pressure pushed inward", "Nothing would change", "It would expand", "It would become hotter",
      "Without solar wind to maintain outward pressure, the interstellar medium would compress the heliosphere until it disappeared."),
    q(29, "A satellite in geostationary orbit experiences a sudden increase in energetic particle flux. What likely caused this?", "A solar energetic particle event from a flare or CME", "A passing asteroid", "Earth's magnetic field reversing", "Lunar gravitational effects",
      "Solar energetic particles accelerated by flares or CME shocks can reach geostationary orbit and damage satellites."),
    q(30, "The Parker Solar Probe is designed to fly closer to the Sun than any previous spacecraft. What key mystery is it investigating?", "Why the corona is hotter than the surface and how solar wind accelerates", "Whether the Sun has a solid core", "If life exists on the Sun", "How to land on the Sun",
      "The Parker Solar Probe studies coronal heating and solar wind acceleration by sampling the Sun's near environment directly.")
])

# 4.5 Impact on Earth's Climate & Technology
write_quiz(4, "4.5", "Impact on Earth's Climate & Technology", [
    q(1, "How does the Sun primarily influence Earth's climate?", "Through variations in solar irradiance and energy output", "By changing Earth's orbit", "Through gravitational tides only", "By altering atmospheric composition directly",
      "Changes in the Sun's energy output, though small, can influence Earth's climate over time."),
    q(2, "What is the total solar irradiance (TSI)?", "The total amount of solar energy received per unit area at Earth's distance", "The temperature of the Sun's surface", "The brightness of the Sun as seen from the Moon", "The amount of UV light only",
      "TSI measures the Sun's total power per square meter at the top of Earth's atmosphere, about 1,361 W/m²."),
    q(3, "By how much does TSI vary over a solar cycle?", "About 0.1%", "About 10%", "About 50%", "It doesn't vary at all",
      "TSI varies by only about 0.1% between solar minimum and maximum, a small but measurable change."),
    q(4, "Solar flares can cause:", "Radio communication disruptions on Earth", "Earthquakes", "Volcanic eruptions", "Changes in ocean salinity",
      "Solar flares produce X-rays and energetic particles that disturb Earth's ionosphere, disrupting radio communications."),
    q(5, "What technology is most vulnerable to geomagnetic storms?", "Power grids and satellites", "Bicycles", "Submarines", "Underground cables only",
      "Geomagnetically induced currents can overload transformers in power grids, and radiation can damage satellite electronics."),
    q(6, "The ozone layer can be temporarily depleted by:", "Energetic solar particle events", "Visible sunlight", "Solar wind alone", "Lunar eclipses",
      "Energetic particles from major solar events can trigger chemical reactions that temporarily reduce stratospheric ozone."),
    q(7, "GPS accuracy can be affected by solar activity because:", "Solar radiation disturbs the ionosphere, delaying GPS signals", "The Sun blocks GPS satellites", "Solar wind moves satellites", "GPS satellites use solar power",
      "Ionospheric disturbances from solar activity cause delays in GPS signals, reducing positioning accuracy."),
    q(8, "The Carrington Event of 1859 caused:", "Telegraph systems to spark and operators to receive shocks", "A global blackout of electric lights", "An asteroid impact", "A tsunami",
      "The Carrington Event produced such intense geomagnetic activity that telegraph systems operated without batteries and some caught fire."),
    q(9, "Milankovitch cycles refer to:", "Variations in Earth's orbital parameters that affect climate", "Cycles of solar flares", "Changes in the Sun's luminosity", "Monthly tidal cycles",
      "Milankovitch cycles describe periodic changes in Earth's eccentricity, obliquity, and precession that influence climate over millennia."),
    q(10, "During solar minimum, cosmic rays reaching Earth:", "Increase because the weaker solar wind provides less shielding", "Decrease significantly", "Stay the same", "Are blocked by the Moon",
      "Weaker solar wind during solar minimum allows more galactic cosmic rays to penetrate the heliosphere and reach Earth."),
    # Vocabulary (11-20)
    q(11, "What is total solar irradiance (TSI)?", "The total solar power per unit area at Earth's orbital distance", "The temperature of the photosphere", "The Sun's luminosity at its surface", "The amount of visible light from the Sun",
      "TSI measures the Sun's total energy output per square meter striking the top of Earth's atmosphere."),
    q(12, "What is a Carrington-class event?", "An extremely powerful geomagnetic storm comparable to the 1859 Carrington Event", "A routine solar flare", "A type of sunspot", "A mild geomagnetic disturbance",
      "A Carrington-class event would cause massive disruptions to modern technology, power grids, and communications."),
    q(13, "What is the ionosphere?", "A layer of Earth's atmosphere ionized by solar radiation", "The Sun's atmosphere", "A layer of the Sun's interior", "The space between Earth and the Moon",
      "The ionosphere (60-1,000 km altitude) contains ions created by solar UV and X-ray radiation, affecting radio propagation."),
    q(14, "What are geomagnetically induced currents (GICs)?", "Electric currents induced in long conductors by geomagnetic disturbances", "Currents in the Sun's core", "Ocean currents driven by magnetism", "Electric currents in the ionosphere only",
      "GICs flow through power lines, pipelines, and cables during geomagnetic storms, potentially damaging transformers."),
    q(15, "What is the solar constant?", "Another term for the average total solar irradiance (~1,361 W/m²)", "The Sun's fixed temperature", "The unchanging number of sunspots", "The speed of the solar wind",
      "Despite its name, the 'solar constant' actually varies slightly; modern usage prefers 'total solar irradiance.'"),
    q(16, "What is a solar proton event?", "A burst of high-energy protons from the Sun, usually associated with flares", "A normal proton emission", "A proton leaving the Sun's core", "A proton hitting a sunspot",
      "Solar proton events are dangerous for astronauts and can increase radiation levels at aircraft altitudes."),
    q(17, "What is space weather forecasting?", "Predicting solar activity and its effects on Earth's technology and environment", "Weather forecasting on other planets", "Predicting meteor showers", "Forecasting eclipses",
      "Space weather forecasting helps prepare for solar events that could disrupt power, communications, and navigation systems."),
    q(18, "What is the Forbush decrease?", "A rapid decrease in galactic cosmic rays following a CME arrival at Earth", "A decrease in the Sun's temperature", "A drop in sunspot numbers", "A reduction in solar wind speed",
      "The magnetic field of a CME can temporarily shield Earth from galactic cosmic rays, causing a Forbush decrease."),
    q(19, "What are Milankovitch cycles?", "Long-term variations in Earth's orbital parameters affecting climate", "Cycles of the Sun's luminosity", "Periodic changes in the solar wind", "Monthly lunar tidal cycles",
      "Milankovitch cycles (eccentricity, obliquity, precession) operate on timescales of tens to hundreds of thousands of years."),
    q(20, "What is solar forcing?", "The influence of the Sun's energy output on Earth's climate system", "Forcing the Sun to produce more energy", "Using solar panels to generate electricity", "Gravitational force of the Sun",
      "Solar forcing refers to changes in the Sun's output that can affect Earth's energy balance and climate."),
    # Scenario (21-30)
    q(21, "A Carrington-class event strikes Earth today. What is the most likely catastrophic consequence?", "Widespread, long-duration power grid failures", "Immediate loss of Earth's atmosphere", "Global flooding", "Instant communication with aliens",
      "A modern Carrington event could knock out power grids worldwide, potentially taking months to fully repair."),
    q(22, "During a major solar particle event, airlines reroute flights from polar routes. What are they protecting against?", "Increased radiation exposure for passengers and crew", "Turbulence from solar wind", "Engine failure from magnetic fields", "Ice formation from cosmic rays",
      "Polar routes have less geomagnetic shielding; during solar events, radiation levels can exceed safety limits for aircrew."),
    q(23, "A farmer notices unusual radio static during a solar flare that disrupts their weather forecast reception. What part of the atmosphere is affected?", "The ionosphere", "The troposphere", "The stratosphere", "The mesosphere",
      "Solar flares enhance ionization in the ionosphere, causing absorption of HF radio waves (radio blackouts)."),
    q(24, "Climate scientists calculate that a 0.1% change in TSI equates to about 0.1°C temperature change. Is this the main driver of current global warming?", "No — current warming is primarily driven by greenhouse gas increases, not solar variability", "Yes — solar changes drive all climate change", "TSI changes are the only climate factor", "The Sun has suddenly brightened by 10%",
      "While solar variability contributes to climate, the ~0.1% TSI change is too small to explain the observed warming trend."),
    q(25, "A power company installs GIC-blocking devices on transformers after a near-miss from a CME. What do these devices do?", "They prevent geomagnetically induced currents from flowing through transformer windings", "They block sunlight from reaching transformers", "They cool transformers during solar flares", "They increase power output during storms",
      "GIC-blocking devices interrupt the flow of quasi-DC currents induced by geomagnetic storms, protecting transformers."),
    q(26, "An astronaut on a spacewalk receives an alert about an incoming solar proton event. What should they do?", "Return to the spacecraft and shelter in a shielded area immediately", "Continue working but put on sunscreen", "Face away from the Sun", "Ignore it since space suits provide full protection",
      "Solar proton events can deliver dangerous radiation doses; spacewalks are halted and astronauts take shelter."),
    q(27, "Scientists notice that tree ring widths correlate with the solar cycle over centuries. What does this suggest?", "Solar activity variations influence terrestrial climate and growing conditions", "Trees can detect sunspots", "Solar wind directly fertilizes trees", "Tree rings are made of solar material",
      "Tree ring data (dendrochronology) shows climate-related growth patterns that correlate with solar activity levels."),
    q(28, "A satellite operator notices that their spacecraft's orbit is decaying faster during solar maximum. Why?", "Solar heating expands Earth's upper atmosphere, increasing drag on the satellite", "Solar wind pushes the satellite down", "Earth's gravity increases during solar maximum", "The Sun's gravity becomes stronger",
      "Increased solar EUV during solar maximum heats and expands the thermosphere, creating more drag on low-orbit satellites."),
    q(29, "Insurance companies want to estimate the cost of a major geomagnetic storm. Which historical event would they study?", "The 1989 Quebec blackout and the 1859 Carrington Event", "The 2004 Indian Ocean tsunami", "The 1906 San Francisco earthquake", "Hurricane Katrina",
      "The 1989 Quebec blackout (9-hour outage, $2B+ damage) and the Carrington Event are key reference points for estimating impacts."),
    q(30, "Researchers propose placing a magnetic shield at the Sun-Earth L1 Lagrange point. What would it do?", "Deflect solar wind and protect Earth during severe space weather events", "Block all sunlight from reaching Earth", "Create artificial gravity", "Generate power from solar wind",
      "A magnetic shield at L1 could theoretically deflect harmful solar particles before they reach Earth's magnetosphere.")
])

# 4.6 Case Studies in Solar Observation
write_quiz(4, "4.6", "Case Studies in Solar Observation", [
    q(1, "Which spacecraft continuously monitors the Sun from the L1 Lagrange point?", "SOHO (Solar and Heliospheric Observatory)", "Hubble Space Telescope", "James Webb Space Telescope", "Voyager 1",
      "SOHO has been observing the Sun from the Sun-Earth L1 point since 1995."),
    q(2, "What mission launched in 2018 to fly through the Sun's corona?", "Parker Solar Probe", "Juno", "Cassini", "SOHO",
      "NASA's Parker Solar Probe is the first spacecraft to fly into the Sun's corona, getting closer than any previous mission."),
    q(3, "The Solar Dynamics Observatory (SDO) primarily observes:", "The Sun in multiple wavelengths to study solar activity", "Distant galaxies", "Asteroids", "The Moon's surface",
      "SDO provides continuous, high-resolution, multi-wavelength observations of the Sun."),
    q(4, "Galileo observed sunspots using:", "A telescope with a projection method", "The naked eye", "X-ray detectors", "Radio antennas",
      "Galileo projected the Sun's image through his telescope onto a surface to safely observe and record sunspots."),
    q(5, "The STEREO mission uses two spacecraft to:", "Provide 3D views of the Sun and track CMEs", "Land on the Sun", "Orbit Mercury", "Study the Moon",
      "STEREO's twin spacecraft view the Sun from different angles, enabling stereoscopic imaging of solar events."),
    q(6, "Spectroheliographs allow astronomers to:", "Image the Sun at a single specific wavelength", "See the Sun's core directly", "Photograph the dark side of the Sun", "Detect neutrinos",
      "Spectroheliographs isolate a specific wavelength to image solar features like prominences and chromospheric details."),
    q(7, "The Daniel K. Inouye Solar Telescope is notable for:", "Being the world's largest solar telescope", "Being located in space", "Observing only at night", "Using radio waves exclusively",
      "Located in Hawaii, the DKIST has a 4-meter mirror, making it the largest and most powerful solar telescope."),
    q(8, "Solar Orbiter, launched in 2020, aims to:", "Study the Sun's polar regions and inner heliosphere", "Land on Mars", "Photograph Pluto", "Study black holes",
      "ESA's Solar Orbiter will provide the first direct images of the Sun's polar regions."),
    q(9, "Early Chinese astronomers recorded sunspots:", "Over 2,000 years ago with naked-eye observations", "With telescopes in 1600 AD", "Never", "Only 100 years ago",
      "Chinese records of sunspot observations date back to at least 364 BCE."),
    q(10, "The Ulysses spacecraft was unique because it:", "Orbited the Sun over its poles rather than in the ecliptic plane", "Landed on the Sun", "Was the fastest spacecraft ever", "Carried humans closest to the Sun",
      "Ulysses used a Jupiter gravity assist to achieve a solar polar orbit, studying the solar wind from above and below."),
    # Vocabulary (11-20)
    q(11, "What is a coronagraph?", "An instrument that blocks the Sun's disk to observe the faint corona", "A graph showing coronal temperature", "A camera for photographing coronas", "A telescope that sees through the Sun",
      "A coronagraph uses an occulting disk to block direct sunlight, allowing observation of the much dimmer corona."),
    q(12, "What is a spectroheliograph?", "An instrument for imaging the Sun at a single wavelength of light", "A device that splits sunlight into sounds", "A telescope for nighttime use", "A thermometer for measuring solar heat",
      "Spectroheliographs can image solar features like prominences by isolating specific spectral lines."),
    q(13, "What is the L1 Lagrange point?", "A gravitational balance point between the Sun and Earth where spacecraft can maintain a stable position", "The center of the Sun", "Earth's magnetic pole", "The edge of the solar system",
      "L1 is about 1.5 million km sunward of Earth, ideal for continuous solar monitoring."),
    q(14, "What is extreme ultraviolet (EUV) imaging?", "Observing the Sun in ultraviolet wavelengths to see hot coronal structures", "Taking photos with a UV flashlight", "Infrared imaging of the Sun", "Visible light photography",
      "EUV imaging reveals hot plasma structures in the corona and transition region that are invisible in white light."),
    q(15, "What is a magnetogram?", "An image showing the magnetic field strength and polarity on the Sun's surface", "A telegram about magnets", "A type of sunspot", "A graph of Earth's magnetic field only",
      "Magnetograms map the Sun's surface magnetic field, revealing the complex magnetic structures driving solar activity."),
    q(16, "What is helioseismology?", "The study of wave oscillations in the Sun to probe its interior structure", "The study of earthquakes caused by the Sun", "A method of communicating with the Sun", "The study of helium in the Sun",
      "Helioseismology uses solar oscillation modes to determine the Sun's internal density, temperature, and rotation."),
    q(17, "What is a solar sail?", "A spacecraft propulsion system that uses radiation pressure from sunlight", "A sail used to cross the Sun's surface", "A solar panel on a boat", "A type of solar prominence",
      "Solar sails use the momentum of photons for propulsion, enabling fuel-free navigation through the solar system."),
    q(18, "What is the ecliptic plane?", "The plane of Earth's orbit around the Sun", "The plane of the Sun's equator", "A vertical plane through the solar system", "The plane of the Milky Way",
      "Most planets orbit close to the ecliptic plane; studying the Sun from above or below requires special orbits."),
    q(19, "What is adaptive optics?", "Technology that corrects for atmospheric distortion in telescope images", "Optics that adapt to darkness", "Lenses that change color", "Self-focusing telescopes",
      "Adaptive optics use deformable mirrors to correct atmospheric turbulence in real time, sharpening solar images."),
    q(20, "What is white-light coronagraphy?", "Observing the corona by blocking the Sun's disk and viewing scattered white light", "Photographing the Sun with a white filter", "Observing white dwarfs", "A type of solar flare imaging",
      "White-light coronagraphs reveal the corona's structure by imaging sunlight scattered by coronal electrons."),
    # Scenario (21-30)
    q(21, "The Parker Solar Probe measures surprisingly strong magnetic field fluctuations near the Sun. What are these called?", "Switchbacks", "Flares", "Prominences", "Coronal holes",
      "Switchbacks are sudden reversals in the magnetic field direction discovered by the Parker Solar Probe near the Sun."),
    q(22, "SOHO has accidentally discovered over 4,000 comets. How?", "Its LASCO coronagraph reveals comets near the Sun that are otherwise invisible", "It was redesigned as a comet hunter", "Comets collide with it", "It scans the entire sky",
      "SOHO's coronagraph blocks the Sun's glare, revealing faint 'sungrazing' comets in the near-Sun environment."),
    q(23, "If you were designing a new solar telescope on Earth, what technology would be critical for sharp images?", "Adaptive optics", "Larger rocket engines", "Nuclear power", "Cryogenic cooling",
      "Adaptive optics compensate for atmospheric turbulence, enabling ground-based telescopes to achieve near-space-quality images."),
    q(24, "A team wants to forecast space weather 24+ hours in advance. Which observing strategy would help most?", "Monitoring the Sun from spacecraft positioned ahead of Earth in its orbit", "Only using ground-based telescopes", "Observing once per month", "Waiting for CMEs to arrive",
      "Spacecraft ahead of Earth (like STEREO-A) can see CMEs heading toward Earth before they arrive."),
    q(25, "During a total solar eclipse, you photograph the corona. Your image shows streamers extending outward. What do these indicate?", "The magnetic field structure of the corona", "Rain on the Sun", "The Sun's core becoming visible", "Reflections from the Moon",
      "Coronal streamers trace the Sun's magnetic field, typically extending outward from active regions in helmet-like shapes."),
    q(26, "The DKIST telescope can resolve features on the Sun as small as 25 km. Why is this scientifically important?", "It allows study of the fundamental processes driving solar magnetic activity", "It can see individual atoms on the Sun", "It detects planets inside the Sun", "It photographs the Sun's core",
      "Resolving small-scale features helps scientists understand the magnetic processes that build up to flares and CMEs."),
    q(27, "Solar Orbiter will tilt its orbit to view the Sun's poles. Why haven't we imaged the poles before?", "Earth and most spacecraft orbit near the ecliptic plane, viewing the Sun's equatorial region", "The poles are invisible", "The poles don't exist", "Telescopes can't point upward",
      "Viewing the Sun's poles requires leaving the ecliptic plane, which demands significant orbital energy (via gravity assists)."),
    q(28, "A citizen scientist discovers a comet in SOHO images using free online data. What does this demonstrate?", "That open data access enables public participation in scientific discovery", "That professional astronomers are unnecessary", "That SOHO is broken", "That comets are common near Earth",
      "Many SOHO comet discoveries have been made by citizen scientists using publicly available coronagraph data."),
    q(29, "Galileo's sunspot observations were controversial. What fundamental idea did they challenge?", "The Aristotelian view that celestial bodies are perfect and unchanging", "The idea that the Earth is round", "Newton's laws of gravity", "The existence of the Moon",
      "Sunspots showed the Sun was imperfect and changing, contradicting the prevailing Aristotelian view of celestial perfection."),
    q(30, "A researcher compares solar images from SDO in 171 Å and 304 Å wavelengths. Why use different wavelengths?", "Different wavelengths reveal plasma at different temperatures, showing different layers and features", "To make colorful pictures", "One wavelength is for daytime, one for nighttime", "To detect different planets",
      "EUV images at 171 Å show ~1 MK coronal loops, while 304 Å shows ~80,000 K chromospheric/transition region features.")
])

# 4.7 AP Prep: Energy Calculations
write_quiz(4, "4.7", "AP Prep: Energy Calculations", [
    q(1, "The equation E = mc² relates:", "Mass and energy equivalence", "Force and acceleration", "Wavelength and frequency", "Pressure and volume",
      "Einstein's E=mc² shows that mass can be converted to energy and vice versa."),
    q(2, "In the proton-proton chain, what fraction of hydrogen mass is converted to energy?", "About 0.7%", "About 50%", "About 10%", "About 99%",
      "The mass defect in hydrogen fusion is about 0.7% — this small fraction yields enormous energy due to c²."),
    q(3, "The Sun's luminosity is approximately:", "3.8 × 10²⁶ watts", "3.8 × 10²⁰ watts", "3.8 × 10¹⁰ watts", "3.8 × 10³⁶ watts",
      "The Sun radiates about 3.8 × 10²⁶ watts of power continuously."),
    q(4, "The inverse square law states that intensity decreases proportional to:", "1/r²", "1/r", "r²", "r³",
      "Light intensity falls off as the square of the distance from the source."),
    q(5, "Stefan-Boltzmann law relates luminosity to:", "Surface area and temperature to the fourth power", "Mass and velocity", "Distance and time", "Pressure and volume",
      "L = σAT⁴ — luminosity depends on the star's surface area and temperature to the fourth power."),
    q(6, "Wien's displacement law relates:", "Peak wavelength of emission to temperature", "Luminosity to mass", "Distance to brightness", "Gravity to orbital period",
      "Wien's law: λmax = b/T, where hotter objects emit at shorter (bluer) wavelengths."),
    q(7, "The flux (apparent brightness) of a star is measured in:", "W/m²", "Kelvin", "Light-years", "Kilograms",
      "Flux measures the power received per unit area, in watts per square meter."),
    q(8, "If you double the temperature of a blackbody, its luminosity increases by a factor of:", "16", "2", "4", "8",
      "Since L ∝ T⁴, doubling T gives (2)⁴ = 16 times the luminosity."),
    q(9, "The mass-energy equivalence of 1 kg of matter is approximately:", "9 × 10¹⁶ joules", "9 × 10⁸ joules", "9 × 10⁴ joules", "9 × 10²⁴ joules",
      "E = mc² = 1 kg × (3 × 10⁸ m/s)² = 9 × 10¹⁶ J, an enormous amount of energy."),
    q(10, "The Sun's surface temperature is approximately:", "5,800 K", "15 million K", "1,000 K", "100,000 K",
      "The photosphere temperature is about 5,800 K, determining the Sun's color and peak emission wavelength."),
    # Vocabulary (11-20)
    q(11, "What is luminosity?", "The total energy radiated by a star per second", "The brightness as seen from Earth", "The temperature of a star", "The mass of a star",
      "Luminosity is the intrinsic total power output, independent of distance, measured in watts or solar luminosities."),
    q(12, "What is the Stefan-Boltzmann law?", "L = σAT⁴ — luminosity equals the Stefan-Boltzmann constant times area times temperature to the fourth power", "F = ma", "E = mc²", "PV = nRT",
      "The Stefan-Boltzmann law connects a star's luminosity to its surface area and the fourth power of its temperature."),
    q(13, "What is Wien's displacement law?", "λmax = b/T — the peak emission wavelength is inversely proportional to temperature", "The law of displacement of planets", "A law about the speed of light", "A rule for measuring distance",
      "Wien's law explains why hotter stars are blue and cooler stars are red — higher temperature shifts peak emission to shorter wavelengths."),
    q(14, "What is the inverse square law?", "The principle that intensity decreases as the square of the distance from the source", "Light intensity doubles with distance", "Gravity increases with distance", "Sound gets louder farther away",
      "The inverse square law: I = L/(4πr²), applies to light, gravity, and other phenomena radiating from a point source."),
    q(15, "What is a blackbody?", "An idealized object that absorbs and re-emits all radiation, with emission depending only on temperature", "A dark star", "A black hole", "A cold planet",
      "A blackbody is a theoretical perfect emitter/absorber; stars approximate blackbodies, and their spectra follow Planck's law."),
    q(16, "What is flux?", "The power received per unit area from a radiating source", "The temperature of a surface", "The speed of light", "The mass of a photon",
      "Flux (F = L/4πr²) measures how much energy from a star reaches each square meter at a given distance."),
    q(17, "What is the mass defect?", "The difference between the mass of components and the mass of the resulting nucleus", "A flaw in measuring mass", "The mass of a black hole", "The weight of a photon",
      "The mass defect represents the binding energy: the 'missing' mass has been converted to energy holding the nucleus together."),
    q(18, "What is the Kelvin temperature scale?", "An absolute temperature scale starting at absolute zero (0 K = -273.15°C)", "A scale that measures brightness", "A relative scale starting at room temperature", "A scale only used for the Sun",
      "Kelvin is the SI unit of temperature, essential in astrophysics because many laws use absolute temperature."),
    q(19, "What is energy conservation?", "The principle that energy cannot be created or destroyed, only converted between forms", "Saving energy by turning off lights", "Energy decreasing over time", "Energy only existing as light",
      "In stellar physics, energy conservation means fusion energy equals the sum of radiation, neutrino energy, and kinetic energy."),
    q(20, "What is a joule?", "The SI unit of energy, equal to one watt-second", "A unit of temperature", "A unit of distance", "A unit of mass",
      "One joule = 1 kg⋅m²/s². The Sun's luminosity is about 3.8 × 10²⁶ joules per second."),
    # Scenario (21-30)
    q(21, "Calculate the energy released when 4 kg of hydrogen is converted to 3.972 kg of helium in the Sun's core.", "E = 0.028 kg × (3 × 10⁸)² = 2.52 × 10¹⁵ J", "E = 4 × 10⁸ J", "E = 28 J", "E = 3.972 × 10⁸ J",
      "Mass defect = 4 - 3.972 = 0.028 kg. E = Δm × c² = 0.028 × (3 × 10⁸)² = 2.52 × 10¹⁵ joules."),
    q(22, "If the Sun were twice as hot but the same size, how much more luminous would it be?", "16 times more luminous", "2 times", "4 times", "8 times",
      "By Stefan-Boltzmann law, L ∝ T⁴. Doubling T gives 2⁴ = 16 times the luminosity."),
    q(23, "Mars is about 1.52 times farther from the Sun than Earth. What fraction of Earth's solar flux does Mars receive?", "About 1/2.31 or ~43%", "About 1/1.52 or ~66%", "About 1/4 or 25%", "About 75%",
      "By the inverse square law: flux ∝ 1/r². So Mars receives 1/(1.52)² = 1/2.31 ≈ 43% of Earth's solar flux."),
    q(24, "Using Wien's law (b = 2.898 × 10⁻³ m·K), what is the peak wavelength of the Sun's emission at 5,800 K?", "About 500 nm (green-yellow light)", "About 100 nm (ultraviolet)", "About 1,000 nm (infrared)", "About 10 nm (X-ray)",
      "λmax = 2.898 × 10⁻³ / 5,800 = 4.996 × 10⁻⁷ m ≈ 500 nm, in the green-yellow part of the visible spectrum."),
    q(25, "A star has a surface temperature of 11,600 K (twice the Sun's). At what wavelength does it peak?", "About 250 nm (ultraviolet)", "About 500 nm", "About 1,000 nm", "About 50 nm",
      "λmax = 2.898 × 10⁻³ / 11,600 ≈ 250 nm, in the ultraviolet — twice as hot means half the peak wavelength."),
    q(26, "If you move a satellite from 1 AU to 3 AU from the Sun, by what factor does the solar flux decrease?", "By a factor of 9", "By a factor of 3", "By a factor of 6", "By a factor of 27",
      "Inverse square law: flux at 3 AU = flux at 1 AU / (3)² = 1/9 of the original flux."),
    q(27, "The Sun converts about 4 × 10⁹ kg of mass to energy per second. How much energy is this?", "About 3.6 × 10²⁶ J (close to the Sun's luminosity)", "About 4 × 10⁹ J", "About 1.2 × 10¹⁸ J", "About 10⁴⁰ J",
      "E = mc² = 4 × 10⁹ × (3 × 10⁸)² = 3.6 × 10²⁶ J/s, matching the Sun's luminosity."),
    q(28, "A planet at 2 AU needs to collect 1,361 W/m² (Earth's TSI) for a solar power station. What area collector is needed relative to one at 1 AU?", "4 times the area", "2 times the area", "The same area", "Half the area",
      "At 2 AU, flux is 1/4 of Earth's TSI. To collect the same total power, you need 4 times the collector area."),
    q(29, "A star has radius 2R☉ and temperature 2T☉. What is its luminosity relative to the Sun?", "64 L☉", "16 L☉", "4 L☉", "8 L☉",
      "L = σ(4πR²)T⁴. Relative: (2)² × (2)⁴ = 4 × 16 = 64 times solar luminosity."),
    q(30, "If the Sun's luminosity suddenly doubled but Earth stayed at 1 AU, what would happen to Earth's equilibrium temperature?", "It would increase by a factor of 2^(1/4) ≈ 1.19, or about a 19% increase in Kelvin", "It would double", "It would stay the same", "It would halve",
      "Equilibrium temperature scales as L^(1/4). Doubling L gives T_new = T_old × 2^0.25 ≈ 1.19 × T_old.")
])

print("\n=== Unit 4 Complete ===")
