"""Generate 30-question Physics quizzes for Unit 2 lessons 2.3-2.6."""
import json, os

def make_quiz(unit, lesson, title, questions, base_dir="content_data/PhysicsLessons"):
    quiz_questions = []
    for i, q in enumerate(questions):
        q_text, correct, w1, w2, w3, explanation = q
        quiz_questions.append({
            "question_number": i + 1,
            "question_text": q_text,
            "attempted": 2,
            "data_i18n": None,
            "options": [
                {"text": correct, "is_correct": True, "data_i18n": None},
                {"text": w1, "is_correct": False, "data_i18n": None},
                {"text": w2, "is_correct": False, "data_i18n": None},
                {"text": w3, "is_correct": False, "data_i18n": None},
            ],
            "explanation": explanation
        })
    data = {"unit": int(unit), "lesson_number": lesson, "title": title, "course": "Physics", "quiz_questions": quiz_questions}
    path = os.path.join(base_dir, f"Unit{unit}", f"Lesson{lesson}_Quiz.json")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  Written: {path} ({len(questions)} questions)")

LESSONS = {}

# ============================================================
# LESSON 2.3: Graphical Analysis of Motion
# ============================================================
LESSONS[("2", "2.3", "Graphical Analysis of Motion")] = [
    # EASY (1-10)
    ("On a position-time graph, what does a horizontal line represent?", "The object is at rest", "The object has constant velocity", "The object is accelerating", "The object has zero position", "A horizontal line on a position-time graph means the position is not changing over time, which indicates the object is stationary."),
    ("On a velocity-time graph, what does the slope represent?", "Acceleration", "Velocity", "Displacement", "Speed", "The slope of a velocity-time graph equals the rate of change of velocity, which by definition is acceleration."),
    ("On a position-time graph, what does the slope represent?", "Velocity", "Acceleration", "Distance", "Force", "The slope of a position-time graph equals Δx/Δt, which is the definition of velocity."),
    ("On a velocity-time graph, what does the area under the curve represent?", "Displacement", "Acceleration", "Velocity", "Force", "The area under a velocity-time graph equals ∫v dt, which gives displacement. This follows directly from the definition of velocity as dx/dt."),
    ("A straight line with a positive slope on a position-time graph indicates:", "Constant positive velocity", "Increasing acceleration", "Decreasing velocity", "The object is at rest", "A straight line means constant slope, which means constant velocity. A positive slope means the object moves in the positive direction."),
    ("A curved line on a position-time graph indicates:", "The object is accelerating", "The object has constant velocity", "The object is at rest", "The object has negative velocity", "A curve means the slope (velocity) is changing over time, which is the definition of acceleration."),
    ("What does a straight line passing through the origin on a velocity-time graph represent?", "Constant acceleration from rest", "Constant velocity", "Decreasing speed", "Zero acceleration", "A straight line through the origin on a v-t graph has the form v = at (where a is constant), meaning constant acceleration starting from rest (v₀ = 0)."),
    ("On a velocity-time graph, a line below the time axis indicates:", "Motion in the negative direction", "The object is at rest", "Positive acceleration", "The object has stopped", "Negative velocity values on a v-t graph mean the object is moving in the negative direction (opposite to the chosen positive direction)."),
    ("On an acceleration-time graph, a horizontal line at a = 0 means:", "The object has constant velocity (zero acceleration)", "The object is at rest", "The object is speeding up", "The object has infinite speed", "Zero acceleration on an a-t graph means velocity is not changing — the object moves at constant velocity (which could be zero or nonzero)."),
    ("How do you find the instantaneous velocity from a position-time graph?", "Draw a tangent line at that point and find its slope", "Find the area under the curve", "Read the y-value directly", "Calculate the total distance traveled", "Instantaneous velocity equals the slope of the tangent line to a position-time graph at a specific point, representing the derivative dx/dt at that instant."),
    # VOCABULARY (11-20)
    ("Which definition BEST describes a position-time graph?", "A graph that plots an object's position along the vertical axis against time along the horizontal axis, showing how location changes over time", "A graph showing the speed of an object over distance", "A graph that only works for objects at rest", "A chart comparing position to acceleration", "A position-time (x-t) graph has time on the horizontal axis and position on the vertical axis. Its slope gives velocity, and its curvature indicates acceleration."),
    ("Which definition BEST describes a velocity-time graph?", "A graph that plots velocity on the vertical axis against time on the horizontal axis, where the slope gives acceleration and the area gives displacement", "A graph that shows only speed, not direction", "A graph where the y-axis represents position", "A graph that can only show constant motion", "A velocity-time (v-t) graph displays how velocity changes with time. The slope at any point gives acceleration, and the area between the curve and time axis gives displacement."),
    ("Which definition BEST describes instantaneous velocity?", "The velocity of an object at a single specific moment in time, found as the slope of the tangent to the position-time curve at that instant", "The total distance divided by total time", "The velocity at the start of motion only", "The fastest speed an object reaches", "Instantaneous velocity is the limit of Δx/Δt as Δt approaches zero — it is the derivative of position with respect to time at a particular instant."),
    ("Which definition BEST describes average velocity?", "The total displacement divided by the total time interval, represented by the slope of the secant line between two points on a position-time graph", "The speed at the midpoint of a journey", "The highest velocity reached during a trip", "The area under a velocity-time graph", "Average velocity = Δx/Δt. On a position-time graph, it equals the slope of the straight line (secant) connecting the initial and final points."),
    ("Which definition BEST describes the tangent line on a graph?", "A straight line that touches a curve at exactly one point and has the same slope as the curve at that point", "A line that crosses through a curve at two points", "A horizontal line at the peak of a curve", "The x-axis of any graph", "The tangent line at a point on a curve represents the instantaneous rate of change (slope) of the function at that point. In physics, it gives instantaneous velocity or acceleration."),
    ("Which definition BEST describes a secant line on a graph?", "A straight line that intersects a curve at two points, with its slope representing the average rate of change between those points", "A line parallel to the x-axis", "A line tangent to the curve at one point", "A vertical line on a graph", "A secant line connects two points on a curve. Its slope gives the average rate of change between those two points — for a position-time graph, this is the average velocity."),
    ("Which definition BEST describes the area under a curve (in kinematics)?", "The integral of the graphed quantity over time, which gives the next kinematic variable — area under v-t gives displacement, area under a-t gives change in velocity", "The total energy of the system", "The maximum value on the graph", "A measure of how curved the line is", "In kinematics graphs, the area under the curve relates consecutive variables: area under v-t = displacement, area under a-t = Δv. This is the graphical interpretation of integration."),
    ("Which definition BEST describes uniform motion on a graph?", "Motion represented by a straight line on a position-time graph and a horizontal line on a velocity-time graph, indicating constant velocity and zero acceleration", "Any motion shown on a graph", "Motion with a curved position-time graph", "Motion where the object always returns to its starting point", "Uniform motion means constant velocity. On an x-t graph this appears as a straight line (constant slope), and on a v-t graph as a horizontal line (constant value, zero slope = zero acceleration)."),
    ("Which definition BEST describes non-uniform motion on a graph?", "Motion represented by a curved line on a position-time graph and a non-horizontal line on a velocity-time graph, indicating changing velocity", "Motion in a straight line at constant speed", "Motion that cannot be represented on a graph", "Motion where the acceleration is always constant", "Non-uniform motion involves changing velocity. On an x-t graph the line curves (changing slope), and on a v-t graph the line is not horizontal (acceleration ≠ 0)."),
    ("Which definition BEST describes an acceleration-time graph?", "A graph that plots acceleration on the vertical axis against time on the horizontal axis, where the area under the curve gives the change in velocity", "A graph that only shows constant acceleration", "A graph where the slope gives position", "A graph identical to a velocity-time graph", "An acceleration-time (a-t) graph shows how acceleration varies with time. The area under the curve between two times gives the change in velocity (Δv) during that interval."),
    # SCENARIO (21-30)
    ("A student has a position-time graph showing a straight line from (0 s, 0 m) to (5 s, 20 m). What is the velocity?", "4 m/s — the slope of the line is Δx/Δt = (20 − 0)/(5 − 0) = 4 m/s", "20 m/s", "5 m/s", "100 m/s", "Velocity = slope of the x-t graph = Δx/Δt = 20 m / 5 s = 4 m/s. The constant slope indicates uniform velocity."),
    ("A velocity-time graph shows a horizontal line at v = 8 m/s from t = 0 to t = 6 s. What is the displacement?", "48 m — displacement = area = base × height = 6 × 8 = 48 m", "8 m", "6 m", "14 m", "Displacement = area under v-t graph = rectangle area = v × t = 8 m/s × 6 s = 48 m."),
    ("A velocity-time graph shows a straight line from (0 s, 0 m/s) to (4 s, 12 m/s). What is the acceleration and displacement?", "Acceleration = 3 m/s², displacement = 24 m — slope = 12/4 = 3 m/s², area of triangle = ½ × 4 × 12 = 24 m", "Acceleration = 12 m/s², displacement = 48 m", "Acceleration = 4 m/s², displacement = 12 m", "Acceleration = 3 m/s², displacement = 48 m", "Acceleration = slope = 12/4 = 3 m/s². Displacement = area of triangle = ½ × base × height = ½ × 4 × 12 = 24 m."),
    ("A position-time graph shows a parabolic curve opening upward. At t = 3 s, the tangent line has a slope of 6 m/s. What can you determine?", "The instantaneous velocity at t = 3 s is 6 m/s, and the object is accelerating because the graph is curved", "The average velocity is 6 m/s", "The acceleration is 6 m/s²", "The object is decelerating", "The slope of the tangent to an x-t graph at a point gives the instantaneous velocity at that time. The parabolic shape (changing slope) indicates non-zero acceleration."),
    ("A car's velocity-time graph shows v = 10 m/s from t = 0 to t = 3 s, then v increases linearly from 10 m/s to 25 m/s between t = 3 s and t = 8 s. What is the total displacement?", "117.5 m — Phase 1: 10 × 3 = 30 m; Phase 2: trapezoid area = ½(10 + 25)(5) = 87.5 m; Total = 30 + 87.5 = 117.5 m", "75 m", "105 m", "150 m", "Phase 1 (rectangle): 10 × 3 = 30 m. Phase 2 (trapezoid): ½(10 + 25) × 5 = 87.5 m. Total = 30 + 87.5 = 117.5 m."),
    ("Two cars have different position-time graphs. Car A has a steeper straight line than Car B. What does this tell you?", "Car A has a greater constant velocity than Car B — a steeper slope on a position-time graph means faster movement", "Car A is accelerating more than Car B", "Car B will eventually pass Car A", "Car A has greater acceleration", "On a position-time graph, the slope gives velocity. A steeper slope means a larger velocity. Since both are straight lines, both have constant velocities, with Car A moving faster."),
    ("An object's velocity-time graph is a straight line from (0 s, 20 m/s) to (5 s, 0 m/s). Describe the motion.", "The object decelerates uniformly at 4 m/s² from 20 m/s to rest, covering 50 m — acceleration = (0 − 20)/5 = −4 m/s², displacement = ½(20 + 0)(5) = 50 m", "The object accelerates from rest to 20 m/s", "The object moves at constant velocity of 20 m/s", "The object reverses direction at t = 5 s", "Slope = (0 − 20)/5 = −4 m/s² (deceleration). Displacement = area of triangle = ½ × 5 × 20 = 50 m. The object uniformly decelerates from 20 m/s to rest in 5 seconds."),
    ("A velocity-time graph shows a line going from +10 m/s at t = 0 to −10 m/s at t = 4 s. At what time does the object momentarily stop, and what is the total displacement?", "The object stops at t = 2 s when the line crosses zero; displacement = 0 m because the positive and negative areas cancel", "It stops at t = 4 s; displacement = 40 m", "It never stops; displacement = 20 m", "It stops at t = 2 s; displacement = 20 m", "The line crosses v = 0 at t = 2 s (by symmetry or linear interpolation). Positive area (0 to 2 s): ½ × 2 × 10 = 10 m. Negative area (2 to 4 s): ½ × 2 × (−10) = −10 m. Net displacement = 10 + (−10) = 0 m."),
    ("A physics teacher draws an acceleration-time graph showing a constant value of 3 m/s² from t = 0 to t = 6 s. If the initial velocity is 2 m/s, what is the final velocity?", "20 m/s — the area under the a-t graph gives Δv = 3 × 6 = 18 m/s, so v = 2 + 18 = 20 m/s", "18 m/s", "6 m/s", "3 m/s", "Area under a-t graph = Δv. Area = 3 m/s² × 6 s = 18 m/s. Final velocity = v₀ + Δv = 2 + 18 = 20 m/s."),
    ("A student plots a position-time graph and observes the line curves steeply, then flattens. The student concludes the object accelerated then moved at constant velocity. A classmate says the object accelerated then decelerated. Who can determine who is correct from the graph?", "The student — a steep curve flattening to a straight line (constant slope) indicates acceleration followed by constant velocity, while a curve flattening to horizontal would indicate deceleration to rest", "The classmate, because all curves represent deceleration", "Neither — you need a velocity-time graph to tell", "Both are wrong — curves only show constant velocity", "If the x-t curve transitions from increasing slope to constant (nonzero) slope, velocity went from changing to constant — acceleration then constant velocity. If it flattens to zero slope (horizontal), the object decelerated to rest. The shape of the curve distinguishes the two interpretations."),
]

# ============================================================
# LESSON 2.4: Equations of Motion (constant acceleration)
# ============================================================
LESSONS[("2", "2.4", "Equations of Motion (constant acceleration)")] = [
    # EASY (1-10)
    ("Which kinematic equation relates velocity, initial velocity, acceleration, and time?", "v = u + at", "s = ut + ½at²", "v² = u² + 2as", "s = ½(u + v)t", "The first equation of motion v = u + at directly links final velocity (v) to initial velocity (u), acceleration (a), and time (t)."),
    ("Which kinematic equation is used to find displacement when you know initial velocity, time, and acceleration?", "s = ut + ½at²", "v = u + at", "v² = u² + 2as", "a = Δv/Δt", "s = ut + ½at² gives displacement as a function of initial velocity, acceleration, and time. It is derived by integrating v = u + at with respect to time."),
    ("Which kinematic equation relates final velocity, initial velocity, acceleration, and displacement without time?", "v² = u² + 2as", "v = u + at", "s = ut + ½at²", "s = vt − ½at²", "v² = u² + 2as eliminates time and directly connects velocity and displacement. It is obtained by combining v = u + at with s = ½(u + v)t."),
    ("An object starts from rest and accelerates at 4 m/s² for 3 seconds. What is its final velocity?", "12 m/s", "7 m/s", "4 m/s", "36 m/s", "Using v = u + at with u = 0: v = 0 + 4(3) = 12 m/s."),
    ("An object starts from rest and accelerates at 2 m/s² for 5 seconds. What displacement does it cover?", "25 m", "10 m", "50 m", "5 m", "Using s = ut + ½at² with u = 0: s = 0 + ½(2)(25) = 25 m."),
    ("A car traveling at 20 m/s brakes and stops in 4 seconds. What is the acceleration?", "−5 m/s²", "5 m/s²", "−4 m/s²", "−20 m/s²", "Using v = u + at: 0 = 20 + a(4) → a = −20/4 = −5 m/s². The negative sign indicates deceleration."),
    ("What does the variable 'u' represent in the kinematic equations?", "Initial velocity", "Final velocity", "Acceleration", "Displacement", "In the standard kinematic equations (v = u + at, s = ut + ½at², v² = u² + 2as), u represents the initial velocity at time t = 0."),
    ("The kinematic equations apply only when which condition is met?", "Acceleration is constant", "Velocity is constant", "The object moves in a circle", "There is no friction", "The standard kinematic equations (SUVAT equations) are derived assuming constant (uniform) acceleration. They do not apply when acceleration changes with time."),
    ("An object has initial velocity 10 m/s and accelerates at 3 m/s² for 4 seconds. What is the displacement?", "64 m — s = 10(4) + ½(3)(16) = 40 + 24 = 64 m", "40 m", "52 m", "124 m", "s = ut + ½at² = 10(4) + ½(3)(4²) = 40 + 24 = 64 m."),
    ("How many standard kinematic equations are there for constant acceleration in one dimension?", "Four (sometimes listed as three main equations plus one auxiliary)", "One", "Two", "Ten", "There are typically four kinematic equations: v = u + at, s = ut + ½at², v² = u² + 2as, and s = ½(u + v)t. Any one can be derived from the other three."),
    # VOCABULARY (11-20)
    ("Which definition BEST describes the equations of motion?", "A set of mathematical relationships that connect displacement, initial velocity, final velocity, acceleration, and time for an object under constant acceleration", "Equations that describe the forces acting on an object", "Formulas that only apply to objects in free fall", "Any equation used in physics", "The equations of motion (kinematic equations) relate five variables (s, u, v, a, t) for uniformly accelerated motion. Each equation omits one variable."),
    ("Which definition BEST describes constant (uniform) acceleration?", "Acceleration that remains the same in both magnitude and direction throughout the entire motion", "Acceleration that increases steadily over time", "Acceleration that is always equal to gravity", "Any acceleration in a straight line", "Constant acceleration means the rate of change of velocity does not vary with time — the velocity increases (or decreases) by equal amounts in equal time intervals."),
    ("Which definition BEST describes initial velocity?", "The velocity of an object at the start of the time interval being analyzed, often denoted u or v₀", "The velocity at the exact midpoint of a journey", "The maximum velocity reached", "The velocity when acceleration becomes zero", "Initial velocity (u or v₀) is the velocity at time t = 0 for the interval under consideration. It serves as a starting condition for the kinematic equations."),
    ("Which definition BEST describes final velocity?", "The velocity of an object at the end of the time interval being analyzed, denoted v", "The velocity just before the object stops permanently", "The fastest speed achieved during motion", "The velocity at the midpoint of the journey", "Final velocity (v) is the velocity at the end of the chosen time interval. In v = u + at, it represents the velocity after time t has elapsed."),
    ("Which definition BEST describes displacement in the context of kinematic equations?", "The straight-line distance and direction from the initial position to the final position of an object, denoted s", "The total path length traveled by an object", "The speed multiplied by acceleration", "The change in acceleration over time", "Displacement (s) is a vector quantity representing the change in position. In uniform acceleration, s = ut + ½at² or s = ½(u + v)t."),
    ("Which definition BEST describes a SUVAT equation?", "One of the kinematic equations named after the five variables they relate: displacement (s), initial velocity (u), final velocity (v), acceleration (a), and time (t)", "An acronym for a type of force equation", "Equations used only in the UK physics curriculum", "A special equation for circular motion", "SUVAT stands for the five kinematic variables. Each SUVAT equation relates four of these five variables, making it possible to solve for any unknown given three knowns."),
    ("Which definition BEST describes deceleration?", "Acceleration that acts opposite to the direction of motion, causing the object to slow down — represented by a negative value of a when velocity is positive", "Any negative number in a physics equation", "The absence of acceleration", "Acceleration in the downward direction", "Deceleration is not a separate physical quantity — it is acceleration directed opposite to motion. When an object with positive velocity has negative acceleration, it slows down (decelerates)."),
    ("Which definition BEST describes free fall in the context of kinematic equations?", "Motion under the sole influence of gravity with constant acceleration g ≈ 9.8 m/s² directed downward, with no air resistance", "Any downward motion of an object", "Motion where the object has zero velocity", "Falling at a speed exactly equal to g", "Free fall is a special case of constant acceleration where the only influence is gravity. In this case a = g ≈ 9.8 m/s² downward. The kinematic equations apply directly with a = ±g."),
    ("Which definition BEST describes the time of flight?", "The total time an object remains in motion from launch to landing, calculable from the kinematic equations by setting final displacement to zero", "The time for one complete revolution", "The time for an object to reach maximum speed", "The time an object spends at its highest point", "Time of flight is the total duration of a projectile's or thrown object's trip. For vertical motion returning to the same height: T = 2u/g."),
    ("Which definition BEST describes uniform motion?", "Motion at constant velocity (zero acceleration), where the kinematic equations simplify to s = vt", "Motion in a perfect circle", "Any motion described by Newton's laws", "Motion that is uniform in color and shape", "Uniform motion means a = 0. The kinematic equations reduce to v = u (velocity doesn't change) and s = ut (displacement increases linearly with time)."),
    # SCENARIO (21-30)
    ("A sprinter starts from rest and accelerates at 3 m/s² for 4 seconds. How far does she run in that time?", "24 m — s = ut + ½at² = 0 + ½(3)(16) = 24 m", "12 m", "48 m", "6 m", "s = ut + ½at² = 0 + ½(3)(4²) = 0 + 24 = 24 m."),
    ("A car is traveling at 25 m/s and brakes uniformly to a stop over a distance of 62.5 m. What is the deceleration?", "−5 m/s² — using v² = u² + 2as: 0 = 625 + 2a(62.5) → a = −625/125 = −5 m/s²", "−2.5 m/s²", "−10 m/s²", "−25 m/s²", "v² = u² + 2as → 0 = 625 + 125a → a = −625/125 = −5 m/s². The negative sign correctly indicates deceleration."),
    ("A stone is thrown vertically upward at 15 m/s. Using g = 10 m/s², how long does it take to reach its highest point?", "1.5 s — at the top v = 0, so 0 = 15 − 10t → t = 1.5 s", "3.0 s", "0.75 s", "15 s", "At the highest point, v = 0. Using v = u + at: 0 = 15 + (−10)t → t = 15/10 = 1.5 s."),
    ("A motorcycle accelerates from 10 m/s to 30 m/s over a distance of 200 m. What is the acceleration?", "2 m/s² — v² = u² + 2as: 900 = 100 + 400a → a = 800/400 = 2 m/s²", "1 m/s²", "4 m/s²", "0.1 m/s²", "v² = u² + 2as: 30² = 10² + 2a(200) → 900 = 100 + 400a → a = 800/400 = 2 m/s²."),
    ("Two students solve the same problem. Student A uses v = u + at and Student B uses v² = u² + 2as. Both get the same final velocity. Is this expected?", "Yes — all kinematic equations are derived from the same assumptions and are mathematically equivalent; they must give consistent answers for the same physical situation", "No — different equations give different answers", "Only if acceleration is zero", "Only if initial velocity is zero", "All SUVAT equations are derived from the same two fundamental relationships (v = u + at and s = ½(u + v)t) under constant acceleration. They are algebraically consistent and always give the same results."),
    ("A ball rolling on a flat surface at 12 m/s decelerates at 2 m/s² due to friction. When the ball stops, a student calculates the distance as s = v² − u² / 2a = (0 − 144) / (2 × −2) = 36 m. Is this correct?", "Yes — using v² = u² + 2as rearranged: s = (v² − u²)/(2a) = (0 − 144)/(−4) = 36 m", "No — the formula should give 72 m", "No — you cannot use this equation for deceleration", "No — the answer should be negative", "s = (v² − u²)/(2a) = (0 − 144)/(2 × −2) = (−144)/(−4) = 36 m. The two negatives cancel, giving a positive displacement as expected for forward motion while braking."),
    ("A rocket accelerates at 15 m/s² from rest for 10 seconds, then its engines cut out and it decelerates at 10 m/s² until it stops. What is the total distance traveled?", "1875 m — Phase 1: s₁ = ½(15)(100) = 750 m, v₁ = 150 m/s. Phase 2: s₂ = (0 − 150²) / (2 × −10) = 1125 m. Total = 750 + 1125 = 1875 m", "750 m", "1500 m", "2250 m", "Phase 1: v₁ = 0 + 15(10) = 150 m/s; s₁ = ½(15)(10²) = 750 m. Phase 2: s₂ = (0 − 22500)/(−20) = 1125 m. Total = 750 + 1125 = 1875 m."),
    ("An elevator starts from rest, accelerates upward at 1.5 m/s² for 4 s, moves at constant velocity for 8 s, then decelerates at 1.5 m/s² for 4 s. What is the total distance?", "60 m — Phase 1: s₁ = ½(1.5)(16) = 12 m (reaches 6 m/s); Phase 2: s₂ = 6 × 8 = 48 m; Phase 3: s₃ = 6(4) − ½(1.5)(16) = 12 m; Total = 12 + 48 + 12 = 72 m", "72 m — Phase 1: 12 m; Phase 2: 48 m; Phase 3: 12 m", "48 m", "36 m", "Phase 1: v = 1.5(4) = 6 m/s, s₁ = ½(1.5)(16) = 12 m. Phase 2: s₂ = 6(8) = 48 m. Phase 3: s₃ = 6(4) − ½(1.5)(16) = 24 − 12 = 12 m. Total = 72 m."),
    ("A police car starts from rest and accelerates at 4 m/s². A speeding car passes it at a constant 20 m/s. How long until the police car catches the speeding car?", "10 s — set distances equal: ½(4)t² = 20t → 2t² = 20t → t = 10 s (ignoring t = 0)", "5 s", "20 s", "4 s", "Police: s₁ = ½(4)t² = 2t². Speeder: s₂ = 20t. Setting equal: 2t² = 20t → t(2t − 20) = 0 → t = 10 s (t = 0 is the starting point)."),
    ("A student writes s = ut + ½at² and substitutes u = 0, a = 9.8, t = 3 to calculate how far an object falls from rest in 3 seconds. She gets 44.1 m. Her friend says the answer is wrong because she didn't include a negative sign. Who is correct?", "Both can be correct depending on the coordinate system — if downward is positive, s = +44.1 m is the distance fallen; if upward is positive, s = −44.1 m but the distance is still 44.1 m", "The friend is always correct — acceleration due to gravity must be negative", "The student is always correct — distance cannot be negative", "Neither — the calculation itself is wrong", "The sign of g depends on the chosen coordinate system. With downward positive, a = +9.8 m/s² and s = +44.1 m. With upward positive, a = −9.8 m/s² and s = −44.1 m. Both give 44.1 m fallen."),
]

# ============================================================
# LESSON 2.5: Free Fall & Projectile Motion
# ============================================================
LESSONS[("2", "2.5", "Free Fall & Projectile Motion")] = [
    # EASY (1-10)
    ("What is the acceleration due to gravity near Earth's surface?", "Approximately 9.8 m/s² downward", "Approximately 9.8 m/s² upward", "Exactly 10 m/s² upward", "It depends on the mass of the object", "Near Earth's surface, all objects in free fall accelerate at g ≈ 9.8 m/s² directed downward, regardless of their mass (ignoring air resistance)."),
    ("In free fall (no air resistance), does a heavier object fall faster than a lighter one?", "No — all objects fall at the same rate regardless of mass", "Yes — heavier objects always fall faster", "Yes — but only for short distances", "It depends on the shape", "In the absence of air resistance, all objects experience the same gravitational acceleration g. Mass does not affect the rate of free fall — this was demonstrated by Galileo."),
    ("What is the vertical acceleration of a projectile at the top of its trajectory?", "9.8 m/s² downward — gravity never stops acting", "Zero — the object momentarily stops", "9.8 m/s² upward", "It changes direction at the top", "At the peak, the vertical velocity is zero, but the acceleration is still g = 9.8 m/s² downward. Gravity acts continuously throughout the entire trajectory."),
    ("In projectile motion, what is the horizontal acceleration (ignoring air resistance)?", "Zero — no horizontal force acts on the projectile", "9.8 m/s² in the direction of motion", "It equals the vertical acceleration", "It depends on the launch angle", "In ideal projectile motion, the only force is gravity (vertical). With no horizontal force, horizontal acceleration is zero, and horizontal velocity remains constant."),
    ("A ball is dropped from rest. After 2 seconds, what is its velocity? (Use g = 10 m/s²)", "20 m/s downward", "10 m/s downward", "40 m/s downward", "2 m/s downward", "v = u + gt = 0 + 10(2) = 20 m/s downward."),
    ("A ball is dropped from rest. How far does it fall in 3 seconds? (Use g = 10 m/s²)", "45 m", "30 m", "90 m", "15 m", "s = ut + ½gt² = 0 + ½(10)(9) = 45 m."),
    ("A projectile is launched horizontally from a cliff. What determines how long it stays in the air?", "Only the height of the cliff and gravity — horizontal velocity does not affect time in the air", "The horizontal velocity", "The mass of the projectile", "The wind speed", "For a horizontally launched projectile, the time of flight depends only on the vertical motion: t = √(2h/g). Horizontal velocity has no effect on the time to fall a given height."),
    ("At what launch angle does a projectile achieve maximum range on level ground (no air resistance)?", "45°", "30°", "60°", "90°", "The range formula R = u²sin(2θ)/g is maximized when sin(2θ) = 1, giving 2θ = 90° or θ = 45°."),
    ("A ball is thrown straight up. What is its velocity at the highest point?", "Zero — it momentarily stops before falling back down", "9.8 m/s upward", "9.8 m/s downward", "It depends on the throw speed", "At the peak of vertical motion, the ball's velocity is instantaneously zero. It then begins falling back down under gravity."),
    ("Two identical balls are released simultaneously from the same height — one is dropped and the other is thrown horizontally. Which hits the ground first?", "They hit at the same time — both have the same vertical motion", "The dropped ball hits first", "The horizontally thrown ball hits first", "It depends on how fast the horizontal ball is thrown", "Both balls start with zero vertical velocity and fall the same height under the same gravitational acceleration. The horizontal velocity of the thrown ball does not affect its vertical motion."),
    # VOCABULARY (11-20)
    ("Which definition BEST describes free fall?", "Motion of an object under the sole influence of gravity, with no air resistance or other forces acting on it", "Any downward motion of an object", "Falling at a speed greater than terminal velocity", "Motion where the object has no velocity", "Free fall occurs when gravity is the only force acting on an object. In free fall, all objects accelerate at g ≈ 9.8 m/s² regardless of mass, shape, or size."),
    ("Which definition BEST describes a projectile?", "An object that has been launched or thrown and moves under the influence of gravity alone, following a curved path", "Any object that is moving through the air", "An object pushed by a constant force", "A ball rolling on a surface", "A projectile is an object in flight with no propulsion — after launch, only gravity acts on it (ignoring air resistance). It follows a parabolic trajectory."),
    ("Which definition BEST describes trajectory?", "The curved path that a projectile follows through space, which is a parabola for ideal projectile motion near Earth's surface", "A straight line from start to finish", "The total distance traveled by an object", "The speed at which an object moves", "In ideal projectile motion (constant g, no air resistance), the trajectory is a parabola. It results from combining constant horizontal velocity with uniformly accelerated vertical motion."),
    ("Which definition BEST describes range in projectile motion?", "The horizontal distance traveled by a projectile from its launch point to the point where it returns to the same height", "The maximum height reached", "The total path length of the projectile", "The time the projectile spends in the air", "Range is the horizontal displacement of a projectile. On level ground, R = u²sin(2θ)/g, where u is the launch speed and θ is the launch angle."),
    ("Which definition BEST describes the time of flight in projectile motion?", "The total time from when the projectile is launched to when it returns to the launch height (or hits the ground)", "The time to reach maximum height only", "The time the projectile spends moving horizontally", "The time it takes to stop", "Time of flight is the total duration of the projectile's journey. For level ground: T = 2u sinθ / g. It depends on the vertical component of the initial velocity."),
    ("Which definition BEST describes maximum height in projectile motion?", "The greatest vertical distance above the launch point reached by the projectile, occurring when the vertical velocity becomes zero", "The horizontal distance at the midpoint", "The height at which air resistance equals gravity", "The launch height of the projectile", "Maximum height H = u²sin²θ / (2g) occurs when v_y = 0. At this point, only horizontal velocity remains (if launched at an angle)."),
    ("Which definition BEST describes terminal velocity?", "The constant maximum velocity reached by a falling object when the drag force equals the gravitational force, resulting in zero net force and zero acceleration", "The velocity at which an object hits the ground", "The initial velocity of a dropped object", "The speed of light", "Terminal velocity occurs when air drag equals weight. At this point, net force = 0, acceleration = 0, and the object falls at constant speed. It depends on mass, shape, and air density."),
    ("Which definition BEST describes the launch angle?", "The angle between the initial velocity vector of a projectile and the horizontal", "The angle of the ground relative to horizontal", "The angle at which the projectile hits the ground", "The angle between the projectile and the vertical", "Launch angle θ is measured from the horizontal to the initial velocity vector. It determines the split between horizontal and vertical velocity components: vₓ = u cosθ, v_y = u sinθ."),
    ("Which definition BEST describes the vertical component of velocity?", "The part of the velocity vector directed perpendicular to the ground, equal to v sinθ for a launch at angle θ, which changes due to gravity", "The total speed of the projectile", "The horizontal part of the velocity", "The velocity at maximum height", "The vertical component v_y = u sinθ − gt changes with time due to gravitational acceleration. It determines time of flight and maximum height."),
    ("Which definition BEST describes the horizontal component of velocity?", "The part of the velocity vector directed parallel to the ground, equal to v cosθ for a launch at angle θ, which remains constant in ideal projectile motion", "The velocity at maximum height", "The velocity when the projectile lands", "The rate of change of the vertical velocity", "The horizontal component vₓ = u cosθ remains constant throughout ideal projectile motion because there is no horizontal acceleration (no air resistance)."),
    # SCENARIO (21-30)
    ("A stone is dropped from a bridge 80 m above a river. How long does it take to hit the water? (Use g = 10 m/s²)", "4 s — using s = ½gt²: 80 = ½(10)t² → t² = 16 → t = 4 s", "8 s", "2 s", "16 s", "s = ½gt²: 80 = 5t² → t² = 16 → t = 4 s."),
    ("A ball is thrown horizontally at 15 m/s from a cliff 45 m high. How far from the base of the cliff does it land? (Use g = 10 m/s²)", "45 m — time to fall: t = √(2h/g) = √(90/10) = 3 s; horizontal distance = 15 × 3 = 45 m", "30 m", "15 m", "60 m", "Time to fall: t = √(2 × 45/10) = √9 = 3 s. Horizontal distance = vₓ × t = 15 × 3 = 45 m."),
    ("A cannonball is fired at 50 m/s at an angle of 30° above horizontal. What is its horizontal range? (Use g = 10 m/s²)", "216.5 m — R = u²sin(2θ)/g = 2500 × sin(60°)/10 = 2500 × 0.866/10 ≈ 216.5 m", "125 m", "250 m", "433 m", "R = u²sin(2θ)/g = 50² × sin(60°)/10 = 2500 × 0.866/10 ≈ 216.5 m."),
    ("A ball is thrown upward at 30 m/s. A second ball is thrown upward at 30 m/s at a 60° angle. Which reaches a greater maximum height?", "The vertically thrown ball — its entire velocity is vertical (v_y = 30 m/s), while the angled ball has v_y = 30 sin60° ≈ 26 m/s", "The ball at 60° because it travels farther", "Both reach the same height because they have the same speed", "The ball at 60° because the angle gives it lift", "Maximum height depends on vertical velocity: H = v_y²/(2g). Ball 1: v_y = 30, H = 900/20 = 45 m. Ball 2: v_y = 30sin60° ≈ 26, H ≈ 676/20 ≈ 33.8 m. The vertical throw wins."),
    ("A package is dropped from a plane flying horizontally at 100 m/s at an altitude of 500 m. Describe the path of the package as seen from the ground.", "The package follows a parabolic trajectory, moving forward at 100 m/s horizontally while accelerating downward at g — it lands far ahead of the drop point", "The package falls straight down directly below the drop point", "The package curves backward due to air", "The package follows a circular path", "The package retains the plane's horizontal velocity (100 m/s) and gains vertical velocity from gravity. The combination of constant horizontal v and accelerating vertical v produces a parabolic trajectory."),
    ("Two projectiles are launched at the same speed but at angles of 25° and 65°. How do their ranges compare on level ground?", "They have the same range — sin(2 × 25°) = sin(50°) and sin(2 × 65°) = sin(130°) = sin(50°), so R is the same", "The 65° projectile goes farther", "The 25° projectile goes farther", "Cannot determine without knowing the speed", "Complementary angles (θ and 90° − θ) give the same range because sin(2θ) = sin(2(90° − θ)) = sin(180° − 2θ) = sin(2θ). So 25° and 65° have identical ranges."),
    ("An astronaut on the Moon (g = 1.6 m/s²) drops a hammer from 2 m. How long does it take to hit the lunar surface compared to Earth (g = 9.8 m/s²)?", "About 2.5 times longer on the Moon — t_Moon = √(2×2/1.6) ≈ 1.58 s vs t_Earth = √(2×2/9.8) ≈ 0.64 s", "The same time on both", "About 6 times longer on the Moon", "Shorter on the Moon because it's lighter", "t = √(2h/g). Moon: √(4/1.6) = √2.5 ≈ 1.58 s. Earth: √(4/9.8) ≈ 0.64 s. Ratio: 1.58/0.64 ≈ 2.47, so about 2.5 times longer on the Moon."),
    ("A soccer ball is kicked at 20 m/s at 45° on level ground. What is the maximum height and total time of flight? (Use g = 10 m/s²)", "H = 10 m, T = 2√2 ≈ 2.83 s — v_y = 20sin45° ≈ 14.14 m/s; H = v_y²/(2g) = 200/20 = 10 m; T = 2v_y/g ≈ 2.83 s", "H = 20 m, T = 4 s", "H = 5 m, T = 2 s", "H = 10 m, T = 2 s", "v_y = 20sin45° = 10√2 ≈ 14.14 m/s. H = v_y²/(2g) = 200/20 = 10 m. T = 2v_y/g = 2(14.14)/10 ≈ 2.83 s."),
    ("A firefighter aims a hose horizontally from the top of a 20 m building. The water exits at 10 m/s. How far from the base does the water land? (Use g = 10 m/s²)", "20 m — fall time: t = √(2 × 20/10) = 2 s; horizontal distance = 10 × 2 = 20 m", "10 m", "40 m", "5 m", "t = √(2h/g) = √(40/10) = 2 s. Horizontal distance = vₓ × t = 10 × 2 = 20 m."),
    ("During a physics lab, a student launches a marble at 5 m/s at 60° above horizontal from a table 1.2 m high. The marble lands on the floor. Will the range formula R = u²sin(2θ)/g give the correct landing distance?", "No — the range formula only applies when launch and landing heights are the same. Since the marble launches from a table and lands on the floor, the full kinematic equations must be used", "Yes — the range formula always works", "Yes — just add the table height to the range", "No — the range formula only works at 45°", "R = u²sin(2θ)/g assumes the projectile lands at the same height it was launched. Since the table is 1.2 m above the floor, the landing height differs from the launch height, requiring the complete projectile motion equations."),
]

# ============================================================
# LESSON 2.6: Relative Motion & Reference Frames
# ============================================================
LESSONS[("2", "2.6", "Relative Motion & Reference Frames")] = [
    # EASY (1-10)
    ("What is a reference frame?", "A coordinate system used to describe the position and motion of objects", "A type of picture frame used in physics labs", "The boundary of an experimental setup", "A frame that is always at rest", "A reference frame is a coordinate system (with an origin and axes) relative to which we measure positions, velocities, and accelerations of objects."),
    ("If you are sitting on a moving train, what is your velocity relative to the train?", "Zero — you are at rest relative to the train", "Equal to the train's speed", "Depends on the direction you face", "Equal to the speed of sound", "In the reference frame of the train, you are not moving — your velocity relative to the train is zero. You are at rest in that frame."),
    ("A car moves east at 60 km/h and a truck moves east at 40 km/h. What is the velocity of the car relative to the truck?", "20 km/h east", "100 km/h east", "60 km/h east", "40 km/h west", "v_car relative to truck = v_car − v_truck = 60 − 40 = 20 km/h east. From the truck's perspective, the car moves ahead at 20 km/h."),
    ("Two cars approach each other, each moving at 50 km/h. What is their relative velocity?", "100 km/h — they approach each other at the sum of their speeds", "50 km/h", "0 km/h", "25 km/h", "When objects move toward each other, relative speed = sum of speeds. If car A moves east at 50 and car B west at 50, v_A relative to B = 50 − (−50) = 100 km/h."),
    ("A person walks at 1 m/s on a conveyor belt moving at 2 m/s in the same direction. What is their speed relative to the ground?", "3 m/s", "2 m/s", "1 m/s", "1.5 m/s", "When moving in the same direction, velocities add: v_person/ground = v_person/belt + v_belt/ground = 1 + 2 = 3 m/s."),
    ("What is an inertial reference frame?", "A reference frame that is not accelerating — it moves at constant velocity or is at rest", "Any frame attached to the Earth", "A frame that rotates with the Earth", "A frame where all objects are at rest", "An inertial reference frame is one in which Newton's first law holds — objects at rest stay at rest and moving objects maintain constant velocity unless acted upon by a force. It is non-accelerating."),
    ("A boat crosses a river at 5 m/s relative to the water. The river flows at 3 m/s. What is the boat's speed relative to the ground?", "√(5² + 3²) = √34 ≈ 5.83 m/s — the velocities add as perpendicular vectors", "8 m/s", "2 m/s", "5 m/s", "Since the boat moves perpendicular to the river flow, the velocities add as vectors: v = √(5² + 3²) = √34 ≈ 5.83 m/s."),
    ("If you throw a ball forward at 10 m/s while riding in a car moving at 20 m/s, what is the ball's speed relative to the ground?", "30 m/s — velocities add when in the same direction", "10 m/s", "20 m/s", "15 m/s", "v_ball/ground = v_ball/car + v_car/ground = 10 + 20 = 30 m/s (when thrown in the direction of motion)."),
    ("Is the Earth an inertial reference frame?", "Approximately yes for most everyday situations, though technically it rotates and orbits", "Yes — it is perfectly inertial", "No — it can never be treated as inertial", "Only at the equator", "The Earth rotates and orbits the Sun, making it technically non-inertial. However, for most everyday physics problems, the effects of Earth's rotation are negligible, so it is treated as approximately inertial."),
    ("A passenger in a car throws a ball straight up. From the passenger's perspective, the ball goes straight up and down. What does a person standing on the roadside see?", "The ball follows a parabolic path — it has horizontal velocity from the car and vertical velocity from the throw", "The ball goes straight up and down", "The ball moves backward", "The ball moves only horizontally", "In the car's frame, the ball goes straight up and down. From the ground frame, the ball has both the car's horizontal velocity and the vertical throw velocity, creating a parabolic trajectory."),
    # VOCABULARY (11-20)
    ("Which definition BEST describes a reference frame?", "A coordinate system and associated time standard attached to an observer, used to measure positions, velocities, and other physical quantities", "A wooden frame holding lab equipment", "The boundary of an experiment", "A unit of measurement", "A reference frame provides the axes and origin from which an observer measures physical quantities. Different observers in different frames may measure different values for the same event."),
    ("Which definition BEST describes relative velocity?", "The velocity of one object as measured by or with respect to another object's reference frame, calculated by vector subtraction of their velocities", "The velocity of an object relative to the ground only", "The average of two objects' velocities", "The maximum speed of an object", "Relative velocity v_A/B = v_A − v_B gives how fast A appears to move from B's perspective. It is a vector quantity that depends on the chosen reference frame."),
    ("Which definition BEST describes an inertial reference frame?", "A reference frame in which Newton's laws of motion hold in their simplest form — one that is not accelerating or rotating", "Any frame at rest", "A frame centered at the Sun", "A frame where objects always accelerate", "In an inertial frame, an object with no net force has zero acceleration (Newton's first law). Any frame moving at constant velocity relative to an inertial frame is also inertial."),
    ("Which definition BEST describes a non-inertial reference frame?", "A reference frame that is accelerating or rotating, in which fictitious forces must be introduced for Newton's laws to appear valid", "A frame where no objects are moving", "A frame that is always at rest", "A frame used only in space", "In a non-inertial (accelerating) frame, objects appear to experience forces that have no physical source — these are called fictitious or pseudo-forces (e.g., centrifugal force, Coriolis force)."),
    ("Which definition BEST describes Galilean transformation?", "The set of equations that relate position, velocity, and time measurements between two inertial reference frames moving at constant velocity relative to each other", "A transformation used only by Galileo in the 17th century", "The conversion from Celsius to Fahrenheit", "A method of rotating coordinate axes", "Galilean transformations: x' = x − vt, t' = t. They assume absolute time and are accurate at low speeds. At speeds near light, they are replaced by Lorentz transformations."),
    ("Which definition BEST describes a fictitious force?", "An apparent force that appears in a non-inertial reference frame to account for the frame's acceleration — it has no physical agent or source", "A force that is imaginary and has no effects", "A force measured incorrectly by a scientist", "Any force that is very small", "Fictitious (pseudo) forces like centrifugal force, Coriolis force, and the force you feel when a car brakes are real in their effects within the non-inertial frame but have no physical cause — they arise from the frame's acceleration."),
    ("Which definition BEST describes the Galilean velocity addition formula?", "The equation v_AC = v_AB + v_BC, which states that the velocity of A relative to C equals the velocity of A relative to B plus the velocity of B relative to C", "An equation for adding positions", "A formula only valid for rotating frames", "The equation for gravitational velocity", "Galilean velocity addition is a chain rule for velocities: v_AC = v_AB + v_BC. This works well at everyday speeds but breaks down near the speed of light."),
    ("Which definition BEST describes an observer in physics?", "A person or measuring device in a specific reference frame that records positions, times, and other physical quantities of events", "Only a human watching an experiment", "A scientist who does not participate in experiments", "A camera pointed at a moving object", "In physics, an 'observer' is anyone (or any device) that measures physical quantities from a given reference frame. Different observers in different frames may record different measurements."),
    ("Which definition BEST describes the principle of Galilean relativity?", "The principle that the laws of mechanics are the same in all inertial reference frames — no mechanical experiment can distinguish between uniform motion and rest", "The principle that everything is relative", "The idea that only Earth's frame is valid", "A principle applicable only to light", "Galilean relativity states that no experiment within a closed, uniformly moving room can determine whether the room is at rest or in uniform motion. The laws of mechanics are identical in all inertial frames."),
    ("Which definition BEST describes velocity composition?", "The process of combining velocity vectors from different reference frames to find an object's velocity in a third frame", "Adding the speeds of two objects together", "Finding the average velocity of a group", "Decomposing velocity into components", "Velocity composition (addition) allows us to find velocities across reference frames. For three frames A, B, C: v_AC = v_AB + v_BC. At relativistic speeds, the formula changes."),
    # SCENARIO (21-30)
    ("A plane flies north at 200 km/h relative to the air. A wind blows east at 50 km/h. What is the plane's speed relative to the ground?", "√(200² + 50²) = √42500 ≈ 206.2 km/h — the perpendicular velocities combine by the Pythagorean theorem", "250 km/h", "150 km/h", "200 km/h", "Ground velocity = vector sum of airplane velocity and wind velocity. Since they are perpendicular: v = √(200² + 50²) = √42500 ≈ 206.2 km/h."),
    ("A swimmer swims at 2 m/s in still water. She tries to swim straight across a river flowing at 1.5 m/s. At what angle downstream from her intended path does she actually travel?", "arctan(1.5/2) ≈ 36.9° downstream — the river pushes her sideways", "arctan(2/1.5) ≈ 53.1° downstream", "0° — she goes straight across", "90° — she goes entirely downstream", "tan(θ) = v_river/v_swimmer = 1.5/2 = 0.75, so θ = arctan(0.75) ≈ 36.9° downstream from her intended perpendicular path."),
    ("Train A moves east at 80 km/h and Train B moves west at 60 km/h on parallel tracks. What is the velocity of Train A as observed from Train B?", "140 km/h east — v_A/B = v_A − v_B = 80 − (−60) = 140 km/h east", "20 km/h east", "140 km/h west", "80 km/h east", "Taking east as positive: v_A = +80, v_B = −60. v_A/B = v_A − v_B = 80 − (−60) = 140 km/h east."),
    ("You run at 3 m/s on a moving walkway that moves at 2 m/s in the same direction. Then you turn around and run back at 3 m/s relative to the walkway. What are your ground speeds in each case?", "5 m/s forward and 1 m/s forward — going with: 3 + 2 = 5; going against: 2 − 3 = −1 m/s (actually 3 − 2 = 1 m/s backward relative to your original direction... but the walkway still carries you at 2 m/s forward, so net is 2 − 3 = −1 m/s, meaning 1 m/s backward)", "Going with: 5 m/s forward; Running back: 1 m/s backward relative to the ground (net: −3 + 2 = −1 m/s, i.e., 1 m/s opposite to walkway direction)", "5 m/s and 5 m/s", "3 m/s and 3 m/s", "Forward: v = 3 + 2 = 5 m/s. Backward (running against walkway): v = −3 + 2 = −1 m/s, meaning 1 m/s in the backward direction relative to the ground. The walkway partially cancels your backward running."),
    ("Two boats leave from the same point. Boat A goes north at 4 m/s and Boat B goes east at 3 m/s. What is the velocity of Boat A relative to Boat B?", "5 m/s in a direction 53.1° west of north — v_A/B = v_A − v_B, giving a vector pointing north and west with magnitude √(4² + 3²) = 5 m/s", "7 m/s north", "1 m/s northeast", "5 m/s northeast", "v_A/B = v_A − v_B = (0, 4) − (3, 0) = (−3, 4). Magnitude = √(9 + 16) = 5 m/s. Direction: arctan(3/4) ≈ 36.9° west of north."),
    ("Raindrops fall vertically at 8 m/s. You run horizontally at 6 m/s. At what angle should you tilt your umbrella from vertical to stay dry?", "arctan(6/8) ≈ 36.9° toward the direction you're running — the rain appears to come at you from an angle", "Straight up — rain falls vertically", "arctan(8/6) ≈ 53.1° from vertical", "45° from vertical", "In your (moving) frame, rain has a horizontal component of 6 m/s and vertical component of 8 m/s. Angle from vertical: θ = arctan(6/8) = arctan(0.75) ≈ 36.9°."),
    ("A child sitting in a train moving at constant velocity drops a ball. According to Galilean relativity, in the train's frame the ball falls straight down. What does an observer on the platform see?", "The ball follows a parabolic path — it has the train's horizontal velocity plus downward gravitational acceleration", "The ball falls straight down", "The ball moves only horizontally", "The ball curves backward relative to the train", "In the ground frame, the ball has the train's constant horizontal velocity and accelerates vertically due to gravity, producing a parabolic trajectory — just like any horizontal projectile."),
    ("A helicopter flies at 40 m/s east relative to the ground. A package is dropped from the helicopter. What is the package's initial velocity relative to the ground?", "40 m/s east — the package inherits the helicopter's horizontal velocity at the moment of release", "0 m/s — it was dropped, not thrown", "40 m/s downward", "40 m/s west", "When released, the package has the helicopter's velocity (40 m/s east). 'Dropped' means no extra velocity was added, but the package retains its existing motion — Galilean velocity addition applies."),
    ("Car A moves north at 30 m/s. Car B moves south at 20 m/s. Car C is parked. Rank the speed of Car A as measured by each observer (C's frame, B's frame).", "C measures 30 m/s, B measures 50 m/s — Car A appears fastest from the approaching Car B's frame", "Both measure 30 m/s", "C measures 50 m/s, B measures 30 m/s", "C measures 30 m/s, B measures 10 m/s", "From C (parked): v_A/C = 30 m/s. From B (approaching): v_A/B = 30 − (−20) = 50 m/s. Objects approaching each other have higher relative speeds."),
    ("An espionage movie shows a car chase where the hero's car goes 50 m/s east and the villain's car goes 45 m/s east. The hero fires a projectile backward at 30 m/s relative to his car. What speed does the villain's driver see the projectile approaching?", "25 m/s — projectile's ground speed = 50 − 30 = 20 m/s east; relative to villain: 20 − 45 = −25 m/s, so it approaches at 25 m/s", "30 m/s", "80 m/s", "5 m/s", "Projectile ground velocity = 50 − 30 = 20 m/s east. Villain's velocity = 45 m/s east. v_projectile/villain = 20 − 45 = −25 m/s (25 m/s approaching, since the villain is faster than the projectile's ground speed)."),
]

if __name__ == "__main__":
    count = 0
    for (unit, lesson, title), questions in LESSONS.items():
        if len(questions) == 30:
            make_quiz(unit, lesson, title, questions)
            count += 1
        else:
            print(f"  SKIPPED: {lesson} has {len(questions)} questions (need 30)")
    print(f"\nTotal quizzes written: {count}")
