import json
import os

base = "C:/Users/Peter/pkang6689-pixel.github.io/content_data/APLessons/AP Human Geography"

def write_quiz(unit, lesson, title, questions):
    data = {
        "unit": unit,
        "lesson_number": lesson,
        "title": title,
        "course": "AP Human Geography",
        "quiz_questions": questions
    }
    unit_dir = f"Unit{unit}"
    filename = f"Lesson{lesson}_Quiz.json"
    filepath = os.path.join(base, unit_dir, filename)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  Written: {filepath} ({len(questions)} questions)")

def q(num, text, opts, correct_idx, expl):
    options = []
    for i, o in enumerate(opts):
        options.append({"text": o, "is_correct": i == correct_idx, "data_i18n": None})
    return {
        "question_number": num,
        "question_text": text,
        "attempted": 2,
        "data_i18n": None,
        "options": options,
        "explanation": expl
    }

# ========== 3.2 Language Branches and Families ==========
print("3.2 Language Branches and Families")
write_quiz(3, "3.2", "Language Branches and Families", [
    q(1,"What is a language branch?",["A regional dialect of a single language","A collection of languages within a family sharing a more recent common ancestor","A dead language that split from a living one","A language spoken on tree-lined streets"],1,"A language branch is a subset of a language family whose languages share a more recent common ancestor than the family as a whole. For example, Germanic is a branch of Indo-European."),
    q(2,"Which branch of the Indo-European family includes English, German, and Dutch?",["Romance","Slavic","Germanic","Indo-Iranian"],2,"The Germanic branch includes English, German, Dutch, Swedish, Norwegian, and Danish. These languages share common roots in Proto-Germanic, spoken around 500 BCE in Scandinavia."),
    q(3,"Which branch of Indo-European includes Spanish, French, Italian, and Portuguese?",["Germanic","Romance","Celtic","Balto-Slavic"],1,"The Romance languages descended from Latin, the language of the Roman Empire. As the empire fragmented, regional varieties of Latin evolved into distinct languages."),
    q(4,"What is the hypothesized ancestral language of the Indo-European family?",["Latin","Proto-Indo-European","Sanskrit","Ancient Greek"],1,"Proto-Indo-European (PIE) is the reconstructed common ancestor of all Indo-European languages, believed to have been spoken around 4500-2500 BCE, likely in the Pontic-Caspian steppe."),
    q(5,"Which language family includes Arabic, Hebrew, and Amharic?",["Indo-European","Sino-Tibetan","Afro-Asiatic","Austronesian"],2,"The Afro-Asiatic family includes the Semitic branch (Arabic, Hebrew, Amharic), Berber, Chadic (Hausa), and others spread across North Africa and the Middle East."),
    q(6,"What is the Sino-Tibetan language family?",["Languages of South America","The second-largest language family, including Chinese languages and Tibeto-Burman languages","Languages of the Pacific Islands","Ancient Mediterranean languages"],1,"Sino-Tibetan is the world's second-largest language family by speakers, including Mandarin, Cantonese, and other Chinese varieties, plus Tibetan, Burmese, and hundreds of smaller languages."),
    q(7,"What evidence do linguists use to classify languages into families?",["Geographic proximity only","Similar writing systems","Systematic similarities in vocabulary, grammar, and sound patterns suggesting common descent","Government declarations"],2,"Linguists compare core vocabulary (basic words like numbers, body parts), grammatical structures, and sound correspondences. Systematic patterns of similarity indicate common descent from a shared ancestor."),
    q(8,"What is the Niger-Congo language family known for?",["Being the smallest language family","Being the largest language family by number of languages, dominant in Sub-Saharan Africa","Including only two languages","Being spoken exclusively in Asia"],1,"Niger-Congo is the largest language family by number of languages (approximately 1,500+), spoken across most of Sub-Saharan Africa. It includes the Bantu sub-group with widely spoken languages like Swahili and Zulu."),
    q(9,"What is the Austronesian language family?",["Languages of Austria","A family spanning from Madagascar to Hawaii, including Malay, Tagalog, and Polynesian languages","Languages of Australia","Ancient European languages"],1,"Austronesian is one of the most geographically widespread families, spread by seafaring peoples from Taiwan across the Pacific and Indian Oceans, including Malay, Indonesian, Tagalog, Hawaiian, and Malagasy."),
    q(10,"Which language is a language isolate with no known relatives?",["Finnish","Japanese","Basque","Turkish"],2,"Basque, spoken in the Pyrenees region between Spain and France, is a language isolate with no proven relationship to any other known language. It likely predates Indo-European migration into Europe."),
    q(11,"What is a 'language branch'?",["The physical location where a language originated","A subdivision of a language family sharing a more recent common ancestor than the family as a whole","A dying language that has split into dialects","The study of tree-shaped language charts"],1,"A language branch is a more specific grouping within a language family. Languages in the same branch are more closely related to each other than to languages in other branches of the same family."),
    q(12,"What does 'proto-language' mean?",["A very simple language","The reconstructed ancestral language from which a language family descended","A language used in scientific experiments","The first language a child learns"],1,"A proto-language is a hypothetical ancestral language reconstructed by linguists through systematic comparison of descendant languages. Proto-Indo-European is the reconstructed ancestor of all Indo-European languages."),
    q(13,"What is a 'language group'?",["A collection of languages within a branch that are closely related","A conversation circle","Languages spoken in the same country","A group of people discussing linguistics"],0,"A language group (or sub-branch) is a more refined classification within a branch. For example, within the Germanic branch, there are West Germanic (English, German, Dutch) and North Germanic (Swedish, Norwegian, Danish) groups."),
    q(14,"What does 'mutual intelligibility' mean?",["Two languages sharing the same alphabet","The ability of speakers of different but related languages to understand each other without special study","Two people who speak the same language","A trade agreement between language groups"],1,"Mutual intelligibility is the degree to which speakers of one language can understand speakers of another without prior study. It is a key criterion (though not the only one) for distinguishing languages from dialects."),
    q(15,"What is a 'tonal language'?",["A language with a pleasant sound","A language with no written form","A language where pitch or tone changes alter word meaning","A musical language used in songs"],2,"In tonal languages like Mandarin Chinese, Thai, and many African languages, the pitch pattern used to pronounce a syllable changes its meaning. Mandarin has four tones that distinguish otherwise identical syllables."),
    q(16,"What does 'language convergence' mean?",["Languages becoming more similar due to prolonged contact and borrowing","Two people agreeing on a topic","Languages merging into one worldwide language","The gathering of linguists at a conference"],0,"Language convergence occurs when languages in prolonged contact become more similar through borrowing vocabulary, grammar, and pronunciation features, sometimes forming a sprachbund (language area)."),
    q(17,"What does 'language divergence' mean?",["A disagreement about grammar rules","The process by which a single language splits into multiple distinct languages over time as speakers become separated","The intentional creation of a new language","Translation errors between languages"],1,"Language divergence occurs when groups of speakers become separated (by migration, geography, or political boundaries) and their speech gradually changes in different directions, eventually becoming mutually unintelligible."),
    q(18,"What is a 'literary tradition'?",["A tradition of reading before bed","A language that has a long history of written works, which helps preserve and standardize it","A library tradition","Oral storytelling only"],1,"A literary tradition means a language has an established body of written literature. Languages with literary traditions (like Chinese, Arabic, English) tend to be more standardized and resistant to extinction than purely oral languages."),
    q(19,"What is the 'Uralic language family'?",["A family including only African languages","A family including Finnish, Hungarian, and Estonian, spread across northern Eurasia","A family of languages spoken in the Ural Mountains only","A family related to Indo-European"],1,"The Uralic family includes Finnish, Estonian, and Hungarian, among others. Despite geographic distance, Finnish and Hungarian share structural features tracing back to a common ancestor in the Ural Mountain region."),
    q(20,"What is a 'Dravidian language'?",["A language spoken by dragons in mythology","A member of a language family predominant in southern India, including Tamil, Telugu, Kannada, and Malayalam","Any language spoken in India","A language that has died out"],1,"Dravidian languages are spoken primarily in southern India and parts of Sri Lanka. They are unrelated to the Indo-European languages (like Hindi) spoken in northern India, representing a distinct and ancient linguistic tradition."),
    q(21,"English and Hindi are both Indo-European languages, yet they sound and look completely different. However, linguists can trace systematic sound correspondences between them (for example, English 'father' relates to Sanskrit 'pitar'). What does this demonstrate about language classification?",["Hindi and English are not actually related","Languages in the same family can diverge dramatically over thousands of years while retaining systematic evidence of their shared ancestry in core vocabulary and grammar","All languages eventually become the same","Sound correspondences are coincidental"],1,"Despite surface differences, English and Hindi share hundreds of cognates (related words) and grammatical structures traceable to Proto-Indo-European. Thousands of years of divergence created very different-sounding languages from the same ancestor."),
    q(22,"The Bantu migration, beginning around 1000 BCE, spread Bantu-speaking peoples from West Africa across central, eastern, and southern Africa over millennia. Today, over 500 Bantu languages are spoken across half the continent. What type of language diffusion does this represent?",["Hierarchical diffusion through cities","Relocation diffusion as migrating peoples carried their language across the continent, with local divergence creating hundreds of related languages","Stimulus diffusion of writing systems","Contagious diffusion through trade only"],1,"The Bantu migration is a classic case of relocation diffusion: as Bantu speakers migrated and settled across Africa over millennia, their language diverged into hundreds of distinct but related languages, demonstrating language divergence through geographic spread."),
    q(23,"Korean and Japanese share similar grammatical structures (subject-object-verb order, postpositions, honorific systems) but have very different vocabularies. Some linguists propose they share a distant common ancestor, while others argue the similarities result from prolonged contact. What challenge in language classification does this illustrate?",["All Asian languages are the same","It can be difficult to distinguish between languages that are genuinely related (genetic relationship) and those that have become similar through prolonged contact (areal features)","Japanese and Korean are definitely in the same family","Grammar is irrelevant to language classification"],1,"This illustrates the challenge of distinguishing genetic relationships (shared ancestry) from areal features (similarities due to geographic proximity and contact). Structural similarities alone are insufficient to prove common descent."),
    q(24,"Arabic spread from the Arabian Peninsula across North Africa and the Middle East after the 7th-century Islamic conquests. Today, spoken Arabic has diverged into varieties (Egyptian, Moroccan, Iraqi) that are often mutually unintelligible, yet all Arabs consider themselves to speak 'Arabic.' What linguistic concept does this illustrate?",["All Arabic speakers understand each other perfectly","The distinction between language and dialect is influenced by political, religious, and cultural identity, not just mutual intelligibility","Arabic is not a real language","Dialects always become separate languages"],1,"Arabic illustrates how cultural and religious identity (shared written Classical Arabic, Quranic tradition) can maintain the perception of a single language even when spoken varieties have diverged beyond mutual intelligibility."),
    q(25,"Hungarian is a Uralic language surrounded entirely by Indo-European languages (German, Romanian, Slavic languages). Its presence in central Europe is explained by the Magyar migration from the Ural region around 896 CE. What does Hungary's linguistic situation demonstrate?",["All European languages are Indo-European","Migration can create linguistic enclaves where an unrelated language persists within a dominant language family's territory","Hungarian is actually Indo-European","Language families are determined by geography"],1,"Hungary demonstrates how migration creates linguistic islands. The Magyars brought their Uralic language into the heart of Indo-European-speaking Europe, where it has persisted for over 1,100 years despite being surrounded by unrelated languages."),
    q(26,"Turkey switched from the Arabic script to the Latin alphabet in 1928 as part of Ataturk's modernization reforms, despite Turkish being an Altaic/Turkic language unrelated to European languages. What does this reveal about the relationship between writing systems and language families?",["Writing systems always match language families","Writing systems are independent of language families and can be adopted for political, cultural, or practical reasons regardless of linguistic relationships","Turkish became a European language by changing its script","All Muslim countries use Arabic script"],1,"Turkey shows that writing systems are cultural technologies independent of language genetics. Turkish is unrelated to Latin-script European languages, yet adopted their alphabet for modernization. Similarly, many unrelated languages use Arabic or Cyrillic scripts."),
    q(27,"The Rosetta Stone, discovered in 1799, contained the same text in Egyptian hieroglyphics, Demotic script, and Ancient Greek. This allowed scholars to decipher hieroglyphics. How does this illustrate the importance of multilingual evidence in understanding language families?",["Ancient Egyptians spoke Greek","Parallel texts in known and unknown languages provide the key to deciphering extinct writing systems and understanding historical language relationships","The Rosetta Stone was a translation dictionary","Only Greek is useful for understanding ancient languages"],1,"The Rosetta Stone demonstrates how multilingual texts allow scholars to decode unknown languages by comparing them to known ones. Similar comparative methods enable linguists to reconstruct proto-languages and establish family relationships."),
    q(28,"Swahili, spoken by over 100 million people in East Africa, is a Bantu language that has borrowed extensively from Arabic (about 20% of vocabulary) due to centuries of Indian Ocean trade. Despite this borrowing, linguists classify it as Bantu, not Afro-Asiatic. Why?",["Swahili has more Arabic words than Bantu words","Language classification is based on core grammar and basic vocabulary, not borrowed words, and Swahili's grammatical structure is fundamentally Bantu","Linguists made an error","Arabic and Bantu are the same family"],1,"Language family classification relies on core grammatical structures and basic vocabulary (body parts, numbers, kinship terms), not borrowed words. Swahili's noun class system, verb morphology, and basic vocabulary are clearly Bantu despite extensive Arabic loanwords."),
    q(29,"The Sapir-Whorf hypothesis suggests that the language you speak influences how you think and perceive the world. For example, some languages have dozens of words for snow or lack tense markers. If true, what would language extinction mean beyond the loss of a communication system?",["Nothing beyond practical inconvenience","The loss of unique ways of perceiving and understanding reality, as each language encodes different conceptual frameworks and environmental knowledge","Languages do not affect thought in any way","Extinct languages had no unique features"],1,"If language shapes thought (even partially), then language extinction means losing unique cognitive frameworks, environmental knowledge, and ways of categorizing reality that have developed over millennia, representing an irreplaceable intellectual and cultural loss."),
    q(30,"China officially recognizes one language called 'Chinese' with regional dialects, but Mandarin, Cantonese, Shanghainese, and Hokkien are mutually unintelligible. Meanwhile, Norwegian and Swedish are called separate languages despite being largely mutually intelligible. What does this comparison reveal?",["Chinese dialects are all the same","The classification of speech varieties as languages or dialects is heavily influenced by political boundaries and national identity rather than purely linguistic criteria","Scandinavian languages are actually the same as Chinese","Mutual intelligibility is the only criterion for language classification"],1,"This reveals that language vs. dialect classification is fundamentally political. Chinese varieties are called dialects to maintain national unity, while Scandinavian varieties are called languages to reinforce national identities, regardless of actual intelligibility."),
])

# ========== 3.3 Religion: Distributions and Beliefs ==========
print("3.3 Religion: Distributions and Beliefs")
write_quiz(3, "3.3", "Religion: Distributions and Beliefs", [
    q(1,"Which religion has the most followers worldwide?",["Islam","Hinduism","Christianity","Buddhism"],2,"Christianity is the world's largest religion with approximately 2.4 billion adherents (about 31% of the global population), spread across every continent through centuries of missionary work and colonialism."),
    q(2,"Which religion is the world's second-largest by number of followers?",["Buddhism","Hinduism","Islam","Judaism"],2,"Islam is the world's second-largest religion with approximately 1.9 billion followers (about 25% of the global population), concentrated in the Middle East, North Africa, Central and Southeast Asia."),
    q(3,"In which region did all three Abrahamic religions (Judaism, Christianity, Islam) originate?",["East Asia","South Asia","The Middle East/Southwest Asia","Europe"],2,"Judaism, Christianity, and Islam all originated in the Middle East (Southwest Asia), specifically in the area around modern Israel/Palestine and the Arabian Peninsula. They share common roots including the patriarch Abraham."),
    q(4,"Which religion is predominantly concentrated in South Asia (India and Nepal)?",["Islam","Christianity","Buddhism","Hinduism"],3,"Hinduism is the world's third-largest religion with about 1.2 billion followers, overwhelmingly concentrated in India (80% of the population) and Nepal. Unlike Christianity and Islam, Hinduism did not spread widely through missionary activity."),
    q(5,"What is the difference between a universalizing and an ethnic religion?",["Universalizing religions are older than ethnic religions","Universalizing religions actively seek converts worldwide while ethnic religions are tied to particular ethnic groups or places","Ethnic religions have more followers","Universalizing religions have no sacred texts"],1,"Universalizing religions (Christianity, Islam, Buddhism) seek to appeal to all people regardless of ethnicity and actively proselytize. Ethnic religions (Hinduism, Judaism, Shinto) are closely tied to a specific people, place, or culture."),
    q(6,"What type of religion is Buddhism classified as?",["Ethnic religion","Animistic religion","Universalizing religion","Folk religion"],2,"Buddhism is a universalizing religion that seeks converts from all backgrounds. Founded by Siddhartha Gautama in India around 500 BCE, it spread throughout East and Southeast Asia through missionaries and trade routes."),
    q(7,"Where is Shinto primarily practiced?",["China","Korea","Japan","India"],2,"Shinto is an ethnic religion indigenous to Japan, focused on spirits of nature (kami) and ancestor veneration. It is closely tied to Japanese national identity and cultural practices."),
    q(8,"What is animism?",["Worship of animals only","The belief that natural objects, phenomena, and the universe itself possess souls or spiritual essence","A type of Christianity","The study of animal behavior"],1,"Animism is the belief that spirits inhabit natural objects like rivers, mountains, trees, and animals. It is found in many indigenous and folk religions worldwide, particularly in Africa, Southeast Asia, and among indigenous peoples globally."),
    q(9,"Which branch of Christianity has the most followers worldwide?",["Protestantism","Eastern Orthodox","Roman Catholicism","Mormonism"],2,"Roman Catholicism is the largest Christian denomination with approximately 1.3 billion members, led by the Pope in Vatican City. It is dominant in Latin America, southern Europe, the Philippines, and parts of Africa."),
    q(10,"What are the two main branches of Islam?",["Catholic and Protestant","Mahayana and Theravada","Sunni and Shia","Orthodox and Reform"],2,"Sunni Islam (approximately 85-90% of Muslims) and Shia Islam (10-15%) divided after the death of Prophet Muhammad over the question of his successor. This split has profound geographic and political consequences."),
    q(11,"What is a 'universalizing religion'?",["A religion practiced in universities","A religion that appeals to all people, actively seeks converts, and is not tied to one particular location or ethnicity","A new religion","A religion practiced everywhere equally"],1,"Universalizing religions attempt to be global and appeal to all peoples. Christianity, Islam, and Buddhism are the three major universalizing religions, each with active missionary traditions seeking new converts."),
    q(12,"What is an 'ethnic religion'?",["A religion that discriminates by ethnicity","A religion closely identified with a particular ethnic group or geographic area, generally not seeking converts","A primitive religion","Any non-Christian religion"],1,"Ethnic religions are tied to particular peoples or places rather than seeking universal appeal. Hinduism, Judaism, and Shinto are ethnic religions closely connected to the cultural identity of specific groups."),
    q(13,"What does 'monotheism' mean?",["Worship of many gods","Belief in one God","Rejection of all religion","Worship of nature"],1,"Monotheism is the belief in a single, all-powerful God. Judaism, Christianity, and Islam are the three major monotheistic religions, all sharing roots in the Abrahamic tradition."),
    q(14,"What does 'polytheism' mean?",["Belief in one God","The belief in and worship of multiple gods or deities","Belief in no gods","The study of politics and religion"],1,"Polytheism is the belief in multiple deities, each typically associated with different aspects of life or nature. Hinduism is the largest polytheistic religion, with millions of deities, though some Hindus view them as manifestations of one supreme being."),
    q(15,"What is 'secularism'?",["A type of religion","The principle of separating religion from government and public affairs, or the decline of religious influence in society","Anti-religious activism","A branch of Christianity"],1,"Secularism can refer to the political principle of church-state separation or the broader sociological trend of declining religious influence. Many Western European countries have become increasingly secular."),
    q(16,"What does 'syncretic religion' mean?",["A religion that rejects all other faiths","A religion that blends elements from two or more different religious traditions","A very old religion","A religion with no rituals"],1,"Syncretic religions combine elements from different religious traditions. Examples include Vodou (blending West African religions with Catholicism), Sikhism (elements of Hinduism and Islam), and Baha'i."),
    q(17,"What is a 'sacred site'?",["Any building with a roof","A place of special religious significance, often associated with divine events, pilgrimages, or holy figures","A government building","A tourist attraction"],1,"Sacred sites are locations imbued with religious meaning, such as Mecca (Islam), Jerusalem (Judaism, Christianity, Islam), Varanasi (Hinduism), and Bodh Gaya (Buddhism). They often attract millions of pilgrims."),
    q(18,"What does 'denomination' mean in religion?",["The value of religious currency","A subgroup within a religion that shares distinct beliefs, practices, or organizational structures","A type of prayer","The process of leaving a religion"],1,"A denomination is a recognized branch within a larger religion. Christianity has hundreds of denominations including Catholic, Baptist, Methodist, and Lutheran. Islam's main denominations are Sunni and Shia."),
    q(19,"What is a 'theocracy'?",["A government led by elected officials","A form of government where religious leaders rule and religious law is the law of the state","A country with no religion","A democracy with religious freedom"],1,"A theocracy is governed by religious authorities according to religious law. Iran (ruled by Shia clerics) and Vatican City (ruled by the Pope) are contemporary examples of theocratic governance."),
    q(20,"What does 'pilgrimage' mean?",["A vacation to a tropical destination","A journey to a sacred place for religious purposes","Migration to a new country","A walking exercise routine"],1,"A pilgrimage is a devotional journey to a holy site. The Hajj to Mecca (required of all able Muslims), pilgrimages to Jerusalem, and visits to the Ganges River in Hinduism are major examples."),
    q(21,"Jerusalem is sacred to Judaism (Western Wall, Temple Mount), Christianity (Church of the Holy Sepulchre), and Islam (Al-Aqsa Mosque, Dome of the Rock). This overlapping significance has made the city a flashpoint for conflict for millennia. What does Jerusalem illustrate about the geography of religion?",["Sacred sites are always peaceful","When multiple religions claim the same sacred space, religious geography can become a source of intense and enduring geopolitical conflict","Only one religion can be correct about Jerusalem","Sacred sites have no political significance"],1,"Jerusalem demonstrates how sacred sites create competing territorial claims with deep emotional significance. Control of holy sites becomes inseparable from religious identity, making compromise extraordinarily difficult."),
    q(22,"The Sunni-Shia divide in Islam originated as a political dispute over succession after Muhammad's death in 632 CE but has become a major geographic fault line. Shia Islam dominates Iran, Iraq, Bahrain, and parts of Lebanon, while Sunni Islam dominates most other Muslim regions. How does this religious division affect modern geopolitics?",["The Sunni-Shia divide has no modern relevance","The geographic concentration of Sunni and Shia populations creates regional power rivalries, particularly between Sunni Saudi Arabia and Shia Iran, fueling proxy conflicts across the Middle East","All Muslims agree on political matters","The divide only matters within Iran"],1,"The Sunni-Shia geographic divide underlies major geopolitical rivalries. Saudi Arabia (Sunni) and Iran (Shia) compete for regional influence, supporting opposing sides in conflicts in Yemen, Syria, Iraq, and Lebanon."),
    q(23,"Hinduism is practiced by over 1 billion people but remains overwhelmingly concentrated in India. By contrast, Buddhism originated in India but has almost no followers there today, instead spreading to East and Southeast Asia. Why did these two religions follow such different geographic paths?",["Hinduism is newer than Buddhism","Buddhism is a universalizing religion that actively spread through missionaries along trade routes, while Hinduism is an ethnic religion tied to Indian culture and caste system that did not actively seek converts","Hinduism actively tried to spread but failed","Buddhism was forced on people by armies"],1,"Buddhism's universalizing nature and monastic missionary tradition allowed it to spread along the Silk Road and sea routes to China, Japan, Korea, and Southeast Asia. Hinduism's ethnic character and connection to Indian social structures kept it largely within South Asia."),
    q(24,"In Western Europe, church attendance has declined dramatically since the mid-20th century. In the Netherlands, more than 50% of people identify as non-religious. Meanwhile, Christianity is growing rapidly in Sub-Saharan Africa and parts of Asia. What geographic shift does this represent?",["Religion is dying worldwide","The geographic center of Christianity is shifting from Europe to the Global South as secularization advances in developed countries while religious growth continues in developing regions","Europeans never practiced Christianity","Africa will become non-religious soon"],1,"Christianity's geographic center is shifting southward as European secularization contrasts with rapid growth in Africa, Latin America, and Asia. By 2050, the majority of Christians will live in the Global South."),
    q(25,"India's 1947 partition divided British India into Hindu-majority India and Muslim-majority Pakistan, triggering the largest mass migration in history (15 million people) and killing 1-2 million. What does the partition of India illustrate about religion and political geography?",["Religion has no connection to political boundaries","Religious identity can become the primary basis for drawing political boundaries, with devastating human consequences when populations are intermixed","India and Pakistan have always been separate","Partition solved all religious conflicts in South Asia"],1,"India's partition shows how religion can become the basis for territorial division. When political boundaries are drawn along religious lines through mixed populations, mass displacement, violence, and enduring conflict often result."),
    q(26,"A growing number of Americans (about 30%) identify as religiously unaffiliated ('nones'), yet the U.S. remains far more religious than comparable Western nations. Within the U.S., religiosity varies dramatically by region, with the 'Bible Belt' in the Southeast being far more religious than the Pacific Northwest. What does this internal variation suggest?",["Religion is uniform within countries","Religious geography operates at multiple scales, with significant regional variation within countries reflecting historical settlement patterns, cultural traditions, and migration","The Bible Belt and Pacific Northwest have similar religious profiles","Only national-level religious data matters"],1,"Religious geography varies dramatically at sub-national scales. The U.S. Bible Belt reflects historical evangelical Protestant culture, while the Pacific Northwest's secular character reflects different settlement patterns and cultural traditions."),
    q(27,"The caste system in Hinduism traditionally organized Indian society into hierarchical groups based on birth. Despite being legally abolished, it continues to influence where people live, whom they marry, and their economic opportunities. What does this show about religion's influence on social geography?",["Religion only affects spiritual matters","Religious belief systems can create enduring social hierarchies and spatial patterns that persist even after formal legal changes","The caste system was not related to Hinduism","All religions have caste systems"],1,"Hinduism's caste system demonstrates how religious social structures create lasting geographic patterns. Caste influences residential segregation, marriage patterns, occupation, and access to resources in ways that persist despite legal reforms."),
    q(28,"Saudi Arabia requires all citizens to be Muslim and prohibits public worship by other religions. Meanwhile, the United States constitutionally separates church and state and protects religious freedom. How do these contrasting approaches reflect different relationships between religion and the state?",["There is only one correct model","Saudi Arabia represents a theocratic model where religion defines state identity, while the U.S. represents a secular model where religious pluralism is protected by separating religion from government","The U.S. has no religion","Saudi Arabia has complete religious freedom"],1,"These contrasting models show the spectrum of state-religion relationships: from theocracy (state enforces religious law) to secularism (state protects religious freedom by maintaining neutrality). Most countries fall somewhere between these extremes."),
    q(29,"Islam prohibits alcohol consumption and pork, which shapes land use, agriculture, and commercial geography in Muslim-majority countries. Halal food requirements have created a global halal industry worth over $2 trillion. How does religious dietary law influence economic geography?",["Religious practices have no economic impact","Religious dietary requirements shape agricultural production, food processing industries, trade patterns, and retail landscapes, creating distinct economic geographies","Only Muslim countries have food industries","Halal food is only sold in mosques"],1,"Religious dietary laws create distinct economic geographies: halal certification industries, specialized slaughterhouses, trade networks, and retail sections. These requirements shape agricultural production, international trade, and commercial landscapes globally."),
    q(30,"After China's communist revolution in 1949, the government actively suppressed religion, destroying temples and persecuting believers. However, since the 1980s, Buddhism, Christianity, and folk religions have experienced massive revivals. What does China's experience suggest about the relationship between political power and religious geography?",["Governments can permanently eliminate religion","Political suppression can temporarily alter religious geography, but deeply held beliefs often persist underground and resurge when conditions change","Religion only exists in democratic countries","China has never had any religions"],1,"China shows that political suppression can alter but rarely eliminate religious practice. Religious geography reflects not just government policy but deep cultural patterns that persist and reassert themselves, sometimes in unexpected forms and locations."),
])

# ========== 3.4 Religion: Diffusion and Cultural Landscape ==========
print("3.4 Religion: Diffusion and Cultural Landscape")
write_quiz(3, "3.4", "Religion: Diffusion and Cultural Landscape", [
    q(1,"Through what mechanism did Christianity primarily spread during the Roman Empire?",["Military conquest only","Relocation and contagious diffusion along Roman roads and trade networks, aided by missionaries","Stimulus diffusion of ideas only","It did not spread during the Roman Empire"],1,"Christianity spread through the Roman Empire via relocation diffusion (missionaries traveling along roads) and contagious diffusion (person-to-person contact). Roman infrastructure and common language (Greek, then Latin) facilitated rapid spread."),
    q(2,"What role did the Silk Road play in religious diffusion?",["It had no effect on religion","It served as a major corridor for the spread of Buddhism, Islam, Christianity, and other religions across Asia","It only carried physical goods, not ideas","It was used only by Hindus"],1,"The Silk Road was a conduit for religious diffusion: Buddhism spread from India to Central and East Asia, Islam spread along trade routes to Southeast Asia, and Nestorian Christianity reached China, all following commercial networks."),
    q(3,"How did Islam primarily spread to Southeast Asia?",["Military conquest by Arab armies","Through Arab and Indian Muslim traders who established commercial networks in port cities","Roman missionaries","Buddhist monks converting to Islam"],1,"Islam spread to Southeast Asia primarily through trade networks. Arab and Indian Muslim merchants established trading posts in port cities, and their commercial success and cultural practices attracted local populations to convert peacefully."),
    q(4,"What is a mosque?",["A Hindu temple","The Islamic place of communal worship, typically featuring a minaret and prayer hall oriented toward Mecca","A Buddhist monastery","A Christian church in the Middle East"],1,"A mosque (masjid) is the Islamic place of worship. Its key architectural features include a prayer hall oriented toward Mecca (qibla direction), a minaret (tower for the call to prayer), and often a dome and courtyard."),
    q(5,"What architectural feature is distinctive to Christian churches in the European tradition?",["Minarets","Steeples, bell towers, and cruciform (cross-shaped) floor plans","Pagoda-style roofs","No windows"],1,"Traditional European Christian architecture features steeples or bell towers, cruciform floor plans, stained glass windows, and altars. Gothic cathedrals with flying buttresses and pointed arches represent the pinnacle of this tradition."),
    q(6,"What is a cultural landscape in the context of religion?",["A natural landscape untouched by humans","The visible imprint of religion on the physical environment, including sacred architecture, cemeteries, shrines, and land use patterns","A painting of a landscape","A landscape used only for farming"],1,"Religious cultural landscapes include churches, temples, mosques, cemeteries, shrines, pilgrimage routes, and religiously influenced land-use patterns. These visible markers reveal the religious history and identity of a place."),
    q(7,"How did European colonialism affect religious geography?",["It had no effect on religion","Colonizers imposed Christianity on indigenous populations worldwide, fundamentally reshaping the religious map","European colonizers adopted indigenous religions","Colonialism only affected Asia"],1,"European colonialism dramatically reshaped religious geography by spreading Christianity to the Americas, Africa, Asia, and Oceania through missionaries, colonial education, and sometimes forced conversion, displacing indigenous beliefs."),
    q(8,"What is a pagoda?",["A Christian church in Asia","A tiered tower associated with Buddhism found throughout East and Southeast Asia","An Islamic prayer tower","A Hindu shrine"],1,"A pagoda is a multi-tiered tower structure associated with Buddhist temples, found throughout East and Southeast Asia. Originating from the Indian stupa, pagodas evolved distinctive regional styles in China, Japan, and Korea."),
    q(9,"What type of diffusion best describes how Islam spread from Arabia to North Africa?",["Stimulus diffusion","Contagious and expansion diffusion through military conquest and subsequent cultural conversion","Hierarchical diffusion through universities","Relocation diffusion through refugees"],1,"Islam spread westward across North Africa through expansion diffusion: Arab armies conquered the region in the 7th-8th centuries, and Islam subsequently spread through cultural influence, intermarriage, and the appeal of Islamic civilization."),
    q(10,"How has religion influenced burial practices and cemetery landscapes?",["Religion has no effect on burial practices","Different religions prescribe different burial practices that create distinctive cemetery landscapes (Christian cemeteries, Muslim graves facing Mecca, Hindu cremation ghats)","All religions bury their dead the same way","Cemeteries are entirely secular spaces"],1,"Religious burial practices create distinctive landscapes: Christian cemeteries with headstones, Muslim graves oriented toward Mecca, Jewish cemeteries with simple markers, Hindu cremation ghats along rivers, and Zoroastrian Towers of Silence."),
    q(11,"What does 'hierarchical diffusion' mean in the context of religion?",["Spreading religion through social hierarchies, where leaders and elites adopt a religion first, then it filters down to the general population","Building churches on hilltops","Organizing religion into ranks","Reading religious texts in order"],0,"Hierarchical diffusion in religion occurs when a faith spreads first to important people or places, then trickles down. Christianity's adoption by Roman Emperor Constantine or Islam's spread through ruling elites exemplify this pattern."),
    q(12,"What does 'relocation diffusion' mean for religion?",["Moving a church building to a new location","The spread of a religion through the physical movement of its followers to new areas","Changing a religion's headquarters","Relocating sacred texts"],1,"Relocation diffusion occurs when adherents physically move to new areas, bringing their religion with them. European colonists brought Christianity to the Americas, and South Asian immigrants bring Hinduism and Sikhism to Western countries."),
    q(13,"What is a 'sacred space'?",["Any indoor area","A place set apart from ordinary space and imbued with religious meaning and special rules of behavior","A government building","A university library"],1,"Sacred spaces are areas imbued with divine presence or religious significance, governed by special rules. They range from grand structures (cathedrals, temples) to natural features (sacred mountains, rivers) to small household shrines."),
    q(14,"What does 'missionary work' mean?",["Working in a hospital","The organized effort to spread a religion to non-believers through preaching, education, healthcare, and social services","Any charitable work","Government propaganda"],1,"Missionary work is the deliberate effort to spread a religion to new populations. Christian missionaries have been particularly active, establishing churches, schools, and hospitals worldwide, while Islamic da'wah and Buddhist missions also have long histories."),
    q(15,"What is 'religious architecture'?",["Any old building","Buildings designed for religious purposes whose style reflects theological beliefs, cultural traditions, and the religion's worldview","Architecture studied by religious people","Government buildings in theocracies"],1,"Religious architecture serves both functional and symbolic purposes. Gothic cathedrals express the glory of God through height and light, Islamic mosques reflect geometric perfection, and Hindu temples represent cosmic mountains connecting earth to heaven."),
    q(16,"What does 'religious landscape' mean?",["A painting of religious scenes","The visible expression of religious beliefs and practices on the physical environment, including buildings, symbols, land use, and spatial organization","A garden in a monastery","Any rural landscape"],1,"The religious landscape encompasses all visible religious features in an area: places of worship, religious schools, cemeteries, street names, statues, festivals, dietary businesses, and the overall spatial organization reflecting religious values."),
    q(17,"What is 'contagious diffusion' in religion?",["Spreading disease through religious gatherings","The rapid, widespread spread of a religion through direct contact between believers and non-believers in nearby areas","A religion that is 'contagious' like a virus","Forced conversion"],1,"Contagious diffusion in religion occurs when a faith spreads through everyday contact between believers and neighbors, spreading outward like ripples in a pond. Early Christianity and Islam spread partly through this person-to-person mechanism."),
    q(18,"What does 'interfaith dialogue' mean?",["Arguments between religions","Organized conversations and cooperation between different religious traditions to promote understanding and address shared concerns","Converting between religions","Studying religion academically"],1,"Interfaith dialogue involves structured communication between different religious groups aimed at mutual understanding, respect, and cooperation on shared issues. It has become increasingly important in our interconnected, religiously diverse world."),
    q(19,"What is 'religious fundamentalism'?",["A return to the literal interpretation of sacred texts and strict adherence to basic religious principles, often as a reaction against modernization and secularism","Any strong religious belief","A type of architecture","A religion without fundamentals"],0,"Religious fundamentalism is a movement within various religions that advocates return to foundational scriptures and practices, often opposing secularism and modernization. It exists in Christianity, Islam, Judaism, Hinduism, and other religions."),
    q(20,"What does 'syncretism' mean in religion?",["The rejection of all religious mixing","The blending of elements from two or more religious traditions into a new belief system or practice","Converting from one religion to another","Studying multiple religions academically"],1,"Religious syncretism occurs when different religious traditions merge, creating hybrid beliefs and practices. Examples include Santeria (Yoruba and Catholic elements), Cao Dai in Vietnam, and many folk religious practices worldwide."),
    q(21,"When Spanish colonizers arrived in Mexico in the 16th century, they imposed Catholicism on indigenous populations. However, many indigenous beliefs survived by merging with Catholic practices. The Day of the Dead (Dia de los Muertos) combines Aztec ancestor worship with Catholic All Saints' Day. What concept does this illustrate?",["Complete destruction of indigenous culture","Religious syncretism, where indigenous and imposed religious traditions blend to create hybrid practices that preserve elements of both","Indigenous people fully accepted Catholicism","Spanish colonizers adopted Aztec religion"],1,"Mexico's Day of the Dead exemplifies religious syncretism: rather than completely replacing indigenous beliefs, Catholicism blended with Aztec traditions. The resulting hybrid practices preserve pre-Columbian elements within a Catholic framework."),
    q(22,"The Golden Temple in Amritsar (Sikhism), the Hagia Sophia in Istanbul (originally Christian, then mosque, now museum/mosque), and the Western Wall in Jerusalem each attract millions of visitors annually. How do major religious structures function beyond their spiritual purpose?",["They have no function beyond prayer","Major religious structures serve as symbols of cultural identity, tourist attractions generating economic activity, political symbols, and focal points for community gathering and national pride","They only matter to believers","Religious buildings have no economic impact"],1,"Major religious structures function as multidimensional landmarks: spiritual centers, cultural identity symbols, economic engines through tourism, political symbols, and community gathering spaces that shape the identity and geography of their cities."),
    q(23,"Protestant Christianity spread to North America primarily through English, Dutch, and German colonization. Catholic Christianity spread to Latin America through Spanish and Portuguese colonization. This created a religious divide that roughly mirrors colonial linguistic boundaries. What does this pattern demonstrate?",["Religions spread randomly","Colonial powers served as vehicles for religious diffusion, creating lasting religious geographic patterns that mirror colonial linguistic and political boundaries","All of the Americas practice the same religion","Religion and colonialism are unrelated"],1,"The Americas' Protestant-Catholic divide demonstrates how colonial diffusion shaped religious geography. The religion of the colonizing power became dominant in each colony, creating enduring religious-linguistic-cultural regions."),
    q(24,"In Bali, Indonesia, Hinduism survived despite the surrounding islands becoming overwhelmingly Muslim. Balinese Hinduism has developed unique characteristics blending Hindu, Buddhist, and indigenous animist elements. Temples, offerings, and ceremonies permeate daily life and landscape. What does Bali illustrate?",["Hinduism and Islam are the same","Religious islands can persist within larger religious regions, developing distinctive syncretic forms, and religion can profoundly shape every aspect of a cultural landscape","Indonesia is entirely Hindu","Bali has no religious character"],1,"Bali illustrates both religious persistence (Hindu enclave in Muslim Indonesia) and syncretism (blending Hindu, Buddhist, and animist elements). The island's intensely religious landscape demonstrates how thoroughly religion can shape a cultural environment."),
    q(25,"Mormon (LDS Church) migration to Utah in the 1840s created a distinctive cultural landscape: grid-pattern towns centered on temples, wide streets, irrigation systems, and conservative social norms. The LDS influence remains visible throughout Utah and parts of neighboring states. What type of diffusion created this religious landscape?",["Contagious diffusion","Relocation diffusion, where a religious community physically moved to create a new homeland and imprinted their beliefs on the landscape","Hierarchical diffusion from universities","Stimulus diffusion of architecture only"],1,"Mormon settlement in Utah is a classic example of relocation diffusion creating a religious landscape. The community's planned migration produced a distinctive built environment reflecting their religious values, community organization, and agricultural practices."),
    q(26,"Megachurches (congregations exceeding 2,000 weekly attendees) have proliferated in American suburbs since the 1980s, often resembling shopping malls or concert venues rather than traditional churches. They are typically located near highways with vast parking lots. What does this phenomenon reveal about the intersection of religion and modern geography?",["Religion is unchanging","Religious institutions adapt to contemporary geographic patterns, with megachurches reflecting car-dependent suburban landscapes, consumer culture, and the scale of American commercial development","Megachurches replace all traditional churches","Suburban areas have no religion"],1,"Megachurches demonstrate how religious institutions adapt to modern geography: they locate near highways for accessibility, provide parking for car-dependent suburbanites, and adopt commercial design aesthetics, showing religion's responsiveness to spatial and cultural context."),
    q(27,"The Camino de Santiago pilgrimage route in Spain has been walked by millions of Christians for over 1,000 years. In recent decades, it has experienced a massive revival, with many non-religious walkers also undertaking the journey. Towns along the route depend economically on pilgrim traffic. How does this pilgrimage route function as a cultural landscape feature?",["It is just a hiking trail","The Camino is a layered cultural landscape where religious pilgrimage, historical heritage, economic activity, and personal spiritual seeking intersect, shaping the identity and economy of an entire region","Pilgrimage routes have no geographic significance","Only devout Catholics walk the Camino"],1,"The Camino demonstrates how religious routes create enduring cultural landscapes: physical infrastructure (hostels, churches, markers), economic systems (pilgrim tourism), cultural identity, and evolving spiritual meaning that transcends its original religious purpose."),
    q(28,"In many Indian cities, Hindu temples, Muslim mosques, Sikh gurdwaras, and Christian churches exist within blocks of each other, each with distinctive architecture. During festivals, the sounds of bells, calls to prayer, and music overlap. What does this religious landscape pattern reveal?",["Religious conflict is inevitable","India's religiously pluralistic landscape reflects centuries of coexistence where multiple faith traditions have left their architectural and cultural imprint on shared urban spaces","India has only one religion","Religious diversity has no visible landscape impact"],1,"India's multi-faith urban landscapes reflect centuries of religious pluralism. The visible coexistence of diverse religious architecture in shared space represents a distinctive cultural landscape pattern different from more religiously homogeneous regions."),
    q(29,"Saudi Arabia restricts non-Muslim access to Mecca and Medina, while the Vatican is open to visitors of all faiths. Israel manages access to Jerusalem's holy sites through complex arrangements among Jewish, Christian, and Muslim authorities. How do these three approaches illustrate different strategies for managing sacred spaces?",["All sacred spaces are managed the same way","Different societies adopt different governance models for sacred spaces, ranging from exclusive religious control to interfaith sharing, reflecting varying political, theological, and historical contexts","Sacred space management has no political dimension","Only Saudi Arabia manages sacred spaces correctly"],1,"These three cases illustrate the spectrum of sacred space governance: exclusive religious control (Mecca), sovereign interfaith management (Jerusalem's Status Quo), and open access (Vatican). Each reflects specific theological positions and political realities."),
    q(30,"South Korea has experienced one of the most rapid religious transformations in modern history: from predominantly Buddhist and shamanist in 1950 to approximately 30% Christian, 25% Buddhist, and 45% non-religious today. Christianity spread rapidly through association with modernization, education, and opposition to Japanese colonial rule. What does South Korea demonstrate about religious diffusion in the modern era?",["Religion never changes in modern societies","Rapid religious change can occur when a religion becomes associated with modernity, education, social mobility, and political identity, demonstrating that religious diffusion continues as a dynamic force","South Korea has always been Christian","Modernization always eliminates religion"],1,"South Korea shows that religious landscapes can transform rapidly in the modern era. Christianity's association with education, modernization, and anti-colonial nationalism facilitated its explosive growth, demonstrating ongoing religious diffusion dynamics."),
])

print("Done with 3.3 and 3.4!")
