import json
import os

base = "C:/Users/Peter/pkang6689-pixel.github.io/content_data/APLessons/AP Human Geography"

def write_quiz(unit, lesson, title, questions):
    data = {"unit": unit, "lesson_number": lesson, "title": title, "course": "AP Human Geography", "quiz_questions": questions}
    filepath = os.path.join(base, f"Unit{unit}", f"Lesson{lesson}_Quiz.json")
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  Written: Lesson{lesson} ({len(questions)} questions)")

def q(num, text, opts, ci, expl):
    return {"question_number":num,"question_text":text,"attempted":2,"data_i18n":None,"options":[{"text":o,"is_correct":i==ci,"data_i18n":None} for i,o in enumerate(opts)],"explanation":expl}

# ===== 3.5 Ethnic and National Identity =====
print("3.5")
write_quiz(3,"3.5","Ethnic and National Identity",[
    q(1,"What is the difference between ethnicity and race?",["They are identical concepts","Ethnicity refers to shared cultural characteristics (language, religion, customs) while race is a social construct based on perceived physical characteristics",
    "Race is cultural while ethnicity is biological","Neither concept is used in geography"],1,"Ethnicity is based on shared cultural traits like language, religion, and traditions, while race is a social construct based on perceived physical characteristics. Both influence spatial patterns and human geography."),
    q(2,"What is a nation?",["Any country with a government","A group of people sharing a common culture, history, language, and identity who see themselves as a distinct political community","A continent","A group of countries in an alliance"],1,"A nation is a cultural concept referring to a group united by shared identity, history, language, or culture. It differs from a state (political entity) and may or may not have its own sovereign territory."),
    q(3,"What is a nation-state?",["Any large country","A state whose territory corresponds to that occupied by a single nation or ethnic group","A state with multiple nations","A country with no government"],1,"A nation-state is the ideal where political boundaries align perfectly with the territory of a single national group. Japan and Iceland come close, but perfectly homogeneous nation-states are rare."),
    q(4,"What is nationalism?",["Tourism within one's country","A strong identification with and loyalty to one's nation, often promoting its interests above all others","International cooperation","Opposition to all government"],1,"Nationalism is the belief that a nation deserves its own sovereign state and that loyalty to the nation should be paramount. It has been both a unifying force (independence movements) and a divisive one (ethnic conflict)."),
    q(5,"What is a stateless nation?",["A nation without any culture","An ethnic or national group that desires its own state but does not have sovereign territory","A country without laws","A nation that has given up its independence"],1,"Stateless nations are peoples with shared national identity who lack their own sovereign state. The Kurds (spread across Turkey, Iraq, Iran, Syria) are the world's largest stateless nation with approximately 30 million people."),
    q(6,"What is a multiethnic state?",["A state with only one ethnic group","A state containing multiple distinct ethnic groups within its borders","A state that prohibits ethnic diversity","An international organization"],1,"Multiethnic states contain multiple ethnic groups within their borders. Most countries are multiethnic, including the United States, India, Nigeria, and Russia. Managing ethnic diversity is a key governance challenge."),
    q(7,"What is ethnic cleansing?",["Cleaning up ethnic neighborhoods","The deliberate forced removal or killing of an ethnic group from a territory to create ethnic homogeneity","Immigration policy","Census data collection"],1,"Ethnic cleansing is the systematic forced removal of an ethnic or religious group from a territory through expulsion, violence, or murder. Examples include the Bosnian War (1990s) and the Rohingya crisis in Myanmar."),
    q(8,"What is genocide?",["A type of government","The deliberate and systematic destruction of a racial, ethnic, religious, or national group","A census category","A natural disaster"],1,"Genocide is the most extreme form of ethnic violence, involving deliberate mass killing aimed at destroying a group. The Holocaust, Rwandan genocide (1994), and Armenian genocide (1915) are recognized examples."),
    q(9,"What is self-determination?",["Personal decision-making","The principle that a nation or people has the right to determine its own political status and governance","Economic independence","Individual freedom"],1,"Self-determination is the right of peoples to choose their own political status. Enshrined in the UN Charter, it has driven decolonization and independence movements but can conflict with existing state sovereignty."),
    q(10,"What is irredentism?",["A form of art","A policy of claiming and seeking to annex territory in another state based on ethnic or historical connections","Immigration reform","International trade"],1,"Irredentism occurs when a state claims territory in another country based on shared ethnicity or historical control. Russia's annexation of Crimea (2014), citing its Russian-speaking population, is a contemporary example."),
    q(11,"What does 'ethnicity' mean?",["A person's nationality","A shared cultural identity based on common ancestry, language, religion, and traditions that distinguishes one group from others","A person's race","A type of food"],1,"Ethnicity refers to shared cultural characteristics that define a group's identity, including language, religion, customs, historical experience, and ancestry. It is fundamentally a cultural rather than biological concept."),
    q(12,"What does 'nationalism' mean?",["Traveling within your own country","A political ideology based on strong identification with a nation, promoting its interests and often seeking political sovereignty","International cooperation","Opposition to all borders"],1,"Nationalism is the belief that the nation is the fundamental unit for human social life and that each nation deserves self-governance. It can be civic (based on shared values) or ethnic (based on shared heritage)."),
    q(13,"What is a 'multinational state'?",["A state owned by multiple corporations","A state that contains two or more distinct nations or ethnic groups with significant political autonomy or self-governance aspirations","Any large country","A state with many embassies"],1,"A multinational state contains multiple national groups, some of which may seek greater autonomy or independence. The United Kingdom (English, Scottish, Welsh, Irish) and Russia (over 100 ethnic groups) are examples."),
    q(14,"What does 'centripetal force' mean in political geography?",["A force pushing outward from a center","An attitude, force, or institution that unifies a state and promotes national cohesion","A type of earthquake","A military strategy"],1,"Centripetal forces bind a state together and promote unity. Examples include shared national identity, a common language, unifying institutions (constitution, monarchy), effective infrastructure, and external threats that rally citizens."),
    q(15,"What does 'centrifugal force' mean in political geography?",["A force pulling inward toward a center","An attitude, force, or factor that divides a state and threatens its unity and cohesion","Gravity","A type of hurricane"],1,"Centrifugal forces pull a state apart and weaken unity. Examples include ethnic or religious divisions, regional economic disparities, linguistic differences, separatist movements, and institutional discrimination."),
    q(16,"What is 'ethnonationalism'?",["Studying different ethnicities","A form of nationalism that defines the nation in terms of shared ethnicity, often excluding minorities who do not share the dominant ethnic identity","International ethnic cooperation","Cultural exchange programs"],1,"Ethnonationalism bases national identity on ethnic heritage rather than civic values. It can lead to exclusionary policies, discrimination against minorities, ethnic cleansing, or genocide when taken to extremes."),
    q(17,"What does 'diaspora' mean?",["A type of musical instrument","The dispersion of a people from their original homeland to multiple locations while maintaining cultural ties to their origin","A diplomatic meeting","A natural disaster"],1,"A diaspora is a scattered population sharing a common origin. The Jewish diaspora, Armenian diaspora, and African diaspora are major historical examples where communities maintained cultural identity across vast distances."),
    q(18,"What is 'assimilation' in the context of ethnic identity?",["Preserving all original cultural practices","The process by which members of an ethnic group adopt the culture and identity of the dominant society, potentially losing their distinctive characteristics","Forced deportation","Learning a new skill"],1,"Assimilation occurs when ethnic minorities gradually adopt the language, customs, and identity of the dominant culture. It can be voluntary or coerced, and ranges from partial acculturation to complete loss of distinctive ethnic identity."),
    q(19,"What is 'cultural pluralism'?",["Having only one culture in a society","A societal model in which multiple ethnic and cultural groups coexist while maintaining their distinct identities and practices","Cultural extinction","Isolation of ethnic groups"],1,"Cultural pluralism (multiculturalism) is a model where diverse ethnic groups maintain their distinctive cultures within a shared political framework. Canada and Singapore officially promote multicultural policies."),
    q(20,"What does 'indigenous people' mean?",["Recent immigrants to an area","The original inhabitants of a region who were present before colonization and maintain distinct cultural identities","Any rural population","Government officials"],1,"Indigenous peoples are the earliest known inhabitants of a region, often marginalized by later colonizers. They include Native Americans, Aboriginal Australians, Maori, Sami, and hundreds of other groups worldwide."),
    q(21,"The Kurds are a nation of approximately 30 million people spread across Turkey, Iraq, Iran, and Syria but have never achieved their own sovereign state. Despite a shared language, culture, and identity, international borders divide them. What concept do the Kurds best exemplify?",["A nation-state with secure borders","A stateless nation whose national territory spans multiple existing states, illustrating the mismatch between political boundaries and national identity","A diaspora community","A failed state"],1,"The Kurds are the world's largest stateless nation. Their situation illustrates how colonial-era and post-WWI boundaries can divide a nation across multiple states, creating ongoing tensions between national aspiration and existing state sovereignty."),
    q(22,"Rwanda's 1994 genocide killed approximately 800,000 Tutsis in 100 days. Belgian colonial authorities had intensified ethnic divisions between Hutus and Tutsis by issuing ethnic identity cards. After independence, political leaders manipulated these divisions. What does Rwanda illustrate about ethnic identity and conflict?",["Ethnic conflict is always inevitable","Colonial manipulation of ethnic categories and post-colonial political exploitation of those divisions can create conditions for genocide, even between groups that previously coexisted","Ethnic identity is purely natural and unchanging","Colonialism had no effect on ethnic relations"],1,"Rwanda shows how colonial powers created rigid ethnic categories that were later weaponized by political leaders. The genocide was not an inevitable result of ancient hatreds but a politically orchestrated manipulation of colonial-era ethnic classifications."),
    q(23,"Quebec's francophone population has pursued sovereignty through two referendums (1980, 1995), the second nearly succeeding with 49.4% voting for independence. Quebec's distinct language and culture create a strong national identity within Canada. What type of force does Quebec's separatism represent?",["A centripetal force strengthening Canadian unity","A centrifugal force threatening Canada's territorial integrity, driven by linguistic and cultural nationalism","An external threat to Canada","A purely economic movement"],1,"Quebec separatism is a centrifugal force driven by ethno-linguistic nationalism. The French-speaking majority's distinct identity creates aspirations for sovereignty that challenge Canadian unity, demonstrating how internal nations can destabilize multinational states."),
    q(24,"After Yugoslavia's breakup in the 1990s, the region experienced devastating ethnic conflicts between Serbs, Croats, and Bosniaks. The Dayton Accords (1995) divided Bosnia into ethnic entities. Why did a multiethnic state fragment so violently?",["Yugoslavia was always destined to fail","When central authority weakened, political leaders mobilized ethnic nationalism for power, transforming coexisting identities into irreconcilable competing claims for territory","All multiethnic states inevitably collapse","Yugoslavia's ethnic groups never interacted"],1,"Yugoslavia's breakup shows how ethnonationalism can be politically mobilized. Under Tito, ethnic groups coexisted, but as communism weakened, leaders like Milosevic exploited ethnic fears, converting diversity into deadly territorial competition."),
    q(25,"Israel defines itself as a Jewish state, yet approximately 20% of its citizens are Palestinian Arabs. This creates tension between Israel's identity as a nation-state for the Jewish people and democratic principles of equal citizenship for all. What fundamental tension does this represent?",["There is no tension","The tension between ethno-national state identity (a state for one people) and civic democratic principles (equal rights for all citizens regardless of ethnicity)","Arab citizens have full equality in every way","Israel is purely a civic state with no ethnic character"],1,"Israel illustrates the fundamental tension between ethnic nationalism (a state embodying one people's national aspirations) and civic democracy (equal citizenship regardless of ethnicity). This tension affects policies on land, language, and citizenship."),
    q(26,"China's Han ethnic group comprises about 92% of the population, but the remaining 8% includes 55 recognized minority groups occupying approximately 60% of China's territory. Tibetans and Uyghurs have distinct languages, religions, and cultures, and some seek independence. What geographic pattern does this illustrate?",["Ethnic minorities occupy little territory","Even in states dominated by one ethnic group, minorities often inhabit strategically important peripheral regions, creating tensions between central authority and regional ethnic identity","China has no ethnic diversity","Minorities have no geographic concentration"],1,"China shows how ethnic minorities often concentrate in peripheral but strategically important border regions. This creates tension between the central government's desire for territorial control and minorities' aspirations for cultural preservation or autonomy."),
    q(27,"Scotland held an independence referendum in 2014 (55% voted to remain in the UK) and has continued to push for another after Brexit. Scottish nationalism is based on distinct legal, educational, and cultural traditions rather than ethnic differences from the English. What type of nationalism is this?",["Ethnic nationalism based on racial differences","Civic nationalism based on shared institutions, values, and political traditions rather than ethnic or racial identity","Religious nationalism","Economic nationalism only"],1,"Scottish nationalism is primarily civic: based on shared political traditions, institutions, and cultural identity rather than ethnic or racial distinctiveness. Scots and English are ethnically similar, but Scotland's distinct institutions create a national identity."),
    q(28,"The Rohingya, a Muslim minority in Buddhist-majority Myanmar, have been denied citizenship, confined to camps, and subjected to military campaigns that the UN has described as genocide. Over 700,000 fled to Bangladesh in 2017. What does the Rohingya crisis illustrate?",["Religious and ethnic harmony in Myanmar","How the intersection of ethnic exclusion, religious difference, and statelessness can produce humanitarian catastrophe when a government defines citizenship in ethno-religious terms","The Rohingya chose to leave voluntarily","This is a purely economic migration"],1,"The Rohingya crisis demonstrates how defining citizenship by ethnicity and religion can produce statelessness and persecution. When the state excludes an ethnic group from the national community, the consequences can be catastrophic."),
    q(29,"The European Union was partly created to overcome the destructive nationalism that caused two World Wars. By creating shared institutions, a common market, and free movement, it aimed to make war between member states unthinkable. However, rising nationalist movements (Brexit, populist parties) challenge this project. What does this tension represent?",["The EU successfully eliminated nationalism","An ongoing tension between supranational integration that reduces national sovereignty and nationalist movements that seek to reclaim it","Nationalism is only a historical phenomenon","The EU has no connection to identity questions"],1,"The EU embodies the tension between supranational cooperation (pooling sovereignty for shared benefits) and national identity (desire for self-governance and cultural preservation). Rising nationalism reflects this unresolved tension."),
    q(30,"Indigenous peoples worldwide, from Aboriginal Australians to Native Americans to the Sami of Scandinavia, share common experiences of colonization, dispossession, and cultural suppression, yet are reclaiming languages, land rights, and cultural practices. The UN Declaration on the Rights of Indigenous Peoples (2007) recognized their collective rights. What geographic significance does this global movement have?",["Indigenous rights have no geographic dimension","Indigenous movements challenge colonial-era territorial arrangements by asserting prior claims to land, water, and resources, fundamentally questioning how political boundaries and sovereignty were established","Indigenous peoples have no connection to land","This is purely a cultural movement with no spatial implications"],1,"Indigenous rights movements have profound geographic implications: they challenge the legitimacy of colonial land seizures, assert sovereignty over ancestral territories, demand resource rights, and question the foundations of existing political boundaries."),
])

# ===== 3.6 Cultural Landscapes and Identity =====
print("3.6")
write_quiz(3,"3.6","Cultural Landscapes and Identity",[
    q(1,"Who coined the term 'cultural landscape' in geography?",["Alexander von Humboldt","Carl Sauer","Thomas Malthus","Immanuel Kant"],1,"Carl Sauer defined the cultural landscape in 1925 as the forms superimposed on the physical landscape by human activity. He argued that culture is the agent, the natural area is the medium, and the cultural landscape is the result."),
    q(2,"What is a cultural landscape?",["A landscape painting","The visible imprint of human activity on the natural environment, including buildings, roads, farms, and other modifications","A national park untouched by humans","A map of cultural regions"],1,"A cultural landscape is the natural landscape as modified by human activities. It includes agricultural patterns, buildings, transportation networks, and all other visible evidence of human occupation and modification of the environment."),
    q(3,"What is sequent occupance?",["A sequence of military occupations","The concept that successive societies leave their cultural imprint on a landscape, creating layers of human modification","Occupying a seat in sequence","Sequential land purchases"],1,"Sequent occupance describes how each society that occupies a place modifies it, leaving traces that blend with those of previous and subsequent occupants. Rome, for example, shows layers from ancient, medieval, Renaissance, and modern periods."),
    q(4,"What is a cultural hearth?",["A fireplace in a cultural center","A place of origin of a major cultural trait, innovation, or civilization","A cultural museum","A type of traditional cooking method"],1,"Cultural hearths are places where key cultural innovations originated and from which they diffused. Major hearths include Mesopotamia, the Nile Valley, the Indus Valley, the Yellow River Valley, and Mesoamerica."),
    q(5,"How does agriculture shape cultural landscapes?",["Agriculture has no visible effect on landscapes","Different agricultural systems create distinctive landscape patterns such as terraced hillsides, irrigated fields, plantation rows, and pastoral grasslands","Only industrial agriculture changes landscapes","Agricultural landscapes are always natural"],1,"Agricultural practices create some of the most extensive cultural landscapes: rice paddies in Southeast Asia, circular pivot irrigation in the American West, vineyard terraces in Europe, and ranching landscapes in Argentina."),
    q(6,"What are placelessness and sense of place?",["They are identical concepts","Sense of place is the unique character of a location, while placelessness describes standardized landscapes that could be anywhere","They refer to map coordinates","Terms for lost and found locations"],1,"Sense of place refers to the unique character that makes a location distinctive. Placelessness describes the loss of distinctive local character due to globalization, chain stores, and standardized architecture that makes places look identical."),
    q(7,"How does language appear in cultural landscapes?",["Language is invisible in landscapes","Through street signs, business names, advertisements, graffiti, and the linguistic character of neighborhoods","Language only appears in books","Language does not affect physical spaces"],1,"Language visibly marks cultural landscapes through signage, business names, street names, graffiti, and the overall linguistic atmosphere of neighborhoods. Chinatowns, Little Italys, and Spanish-language commercial districts show this clearly."),
    q(8,"What is a folk culture landscape?",["A landscape featuring folk music venues","Traditional cultural landscape reflecting local customs, materials, and building techniques specific to a particular group or region","Any rural landscape","A primitive landscape"],1,"Folk culture landscapes reflect traditional, locally-based practices: log cabins, stone walls, thatched roofs, terraced fields, and distinctive building styles that developed over generations using local materials and techniques."),
    q(9,"What is a popular culture landscape?",["A landscape featuring celebrities' homes","A landscape dominated by mass-produced, globally distributed cultural elements like chain stores, fast food restaurants, and standardized housing","Any urban landscape","A landscape with popular attractions"],1,"Popular culture landscapes feature globally standardized commercial elements: fast food franchises, shopping malls, suburban subdivisions, and billboards that look similar worldwide, often replacing distinctive local cultural landscapes."),
    q(10,"What is heritage tourism?",["Any form of tourism","Tourism centered on historical sites, cultural traditions, and architectural heritage of a region","Business travel","Adventure tourism"],1,"Heritage tourism involves visiting places of historical, cultural, or architectural significance. It can preserve cultural landscapes by providing economic incentives for conservation but may also commodify and distort the cultures it celebrates."),
    q(11,"What does 'cultural landscape' mean?",["A beautiful natural area","The visible expression of human activity and values imprinted on the physical environment","A map of different cultures","A painting of cultural scenes"],1,"Cultural landscape is the physical environment as modified by human action, reflecting the beliefs, practices, technologies, and social structures of the cultures that shaped it. It includes everything from building styles to agricultural patterns."),
    q(12,"What does 'sense of place' mean?",["A GPS system","The subjective feeling and character associated with a location, shaped by its physical features, history, and human experiences","A compass direction","A type of map"],1,"Sense of place is the emotional and experiential quality that makes a location feel distinctive and meaningful. It combines physical characteristics, cultural associations, personal memories, and community identity."),
    q(13,"What does 'placelessness' mean?",["A place with no name","The loss of unique local character as standardized, homogeneous landscapes replace distinctive local environments","Being lost","A place with no population"],1,"Placelessness describes locations that lack distinctive character, where chain restaurants, big-box stores, and standardized architecture create landscapes that could be anywhere, undermining local identity and sense of place."),
    q(14,"What is 'built environment'?",["A bodybuilder's gym","The human-made surroundings that provide the setting for human activity, including buildings, parks, roads, and infrastructure","A natural forest","A mountain range"],1,"The built environment encompasses all human-made structures and spaces: buildings, roads, bridges, parks, utilities, and other infrastructure. It contrasts with the natural environment and reveals cultural values, economic systems, and social priorities."),
    q(15,"What does 'gentrification' mean?",["The gentle renovation of old buildings","The transformation of lower-income neighborhoods through investment and influx of wealthier residents, often displacing existing communities","Rural development","Building new cities from scratch"],1,"Gentrification involves the renovation of deteriorated urban areas by middle-class or affluent people, raising property values and often displacing lower-income residents. It transforms the cultural landscape while creating social equity concerns."),
    q(16,"What is 'commodification of culture'?",["Buying cultural artifacts","The process of transforming cultural practices, traditions, and places into marketable products for economic gain","Sharing culture freely","Teaching culture in schools"],1,"Cultural commodification occurs when cultural practices, traditions, or identities are packaged and sold as consumer products. This can include heritage tourism, selling traditional crafts for tourists, or marketing ethnic food and music."),
    q(17,"What is a 'cultural region'?",["A country","An area defined by one or more shared cultural traits such as language, religion, ethnicity, or customs","A museum district","A trade zone"],1,"A cultural region is an area where people share common cultural characteristics. The 'Bible Belt' in the American South, the Arab World, and Latin America are examples of cultural regions defined by shared traits."),
    q(18,"What does 'vernacular architecture' mean?",["Architecture designed by famous architects","Traditional building styles using local materials and reflecting local cultural practices and environmental conditions","Modern skyscraper design","Government building standards"],1,"Vernacular architecture refers to building traditions that have evolved locally in response to climate, available materials, and cultural practices rather than formal architectural training. Examples include adobe in the American Southwest and stilt houses in Southeast Asia."),
    q(19,"What does 'toponym' mean?",["A type of map symbol","A place name that often reflects the cultural history, language, and identity of the people who named it","A topographic feature","A type of soil"],1,"Toponyms (place names) reveal cultural history: English place names ending in '-burgh' reflect Scottish influence, Spanish-named cities in the U.S. Southwest reflect colonial history, and renamed cities (Bombay to Mumbai) reflect political identity shifts."),
    q(20,"What is 'cultural diffusion'?",["The spread of cultural practices, ideas, and innovations from one place or group to another","Cultural isolation","The decline of culture","Cultural conflict"],0,"Cultural diffusion is the spread of cultural elements (ideas, technologies, food, music, fashion) from one society to another through migration, trade, media, or other forms of contact. It is one of the most fundamental processes in human geography."),
    q(21,"Times Square in New York City is dominated by massive digital billboards, global brand logos, and tourist-oriented entertainment. Despite being uniquely identifiable, critics argue it exemplifies globalized commercial culture rather than local New York identity. What concept does this tension illustrate?",["Times Square has no cultural significance","The paradox of placelessness within distinctiveness: a globally recognizable place whose character is defined by global commercial culture rather than local cultural identity","Times Square represents authentic local culture","All cities look like Times Square"],1,"Times Square illustrates a complex form of placelessness: while instantly recognizable, its character is defined by global brands and commercial spectacle rather than local community. It is a distinctive place whose distinctiveness comes from global rather than local culture."),
    q(22,"The French Quarter in New Orleans features Spanish colonial architecture (despite its name), Creole influences, jazz clubs, and restaurants serving Cajun cuisine. After Hurricane Katrina, debates arose about whether reconstruction should prioritize historical preservation or modern development. What does this case reveal?",["Historical buildings are not worth preserving","Cultural landscapes embody layered identity and heritage, and their preservation involves difficult choices between historical authenticity, economic development, and community needs","Only new buildings matter","Natural disasters have no effect on cultural landscapes"],1,"New Orleans' French Quarter demonstrates how cultural landscapes embody layered history (French, Spanish, Creole, American). Post-Katrina reconstruction debates highlight tensions between heritage preservation, economic viability, and community displacement."),
    q(23,"Dubai has constructed an entirely new skyline in a single generation, featuring the world's tallest building, artificial islands, and spectacular architecture. Critics say it represents a placeless spectacle with no organic cultural roots, while supporters argue it creates a new cultural identity. What does Dubai illustrate about cultural landscapes?",["Cultural landscapes must always be old","Cultural landscapes can be deliberately constructed to project a desired identity, raising questions about authenticity, sustainability, and the relationship between built environment and cultural meaning","Dubai has no cultural landscape","Only Western cities have cultural landscapes"],1,"Dubai shows that cultural landscapes can be intentionally manufactured. Its skyline projects wealth, modernity, and ambition as a new form of cultural identity, challenging assumptions that authentic cultural landscapes must emerge organically over centuries."),
    q(24,"Across the American Midwest, the landscape is organized in a grid pattern of square fields, straight roads, and evenly spaced towns, reflecting the Township and Range survey system established by the U.S. government in 1785. What does this landscape pattern reveal?",["Midwestern farmers chose this pattern spontaneously","Government land division policies can permanently shape cultural landscapes, as the geometric survey grid determined settlement patterns, road networks, and agricultural organization for centuries","The Midwest has no cultural landscape","Grid patterns are natural formations"],1,"The Midwestern grid landscape demonstrates how government policy shapes cultural landscapes. The Township and Range system imposed a geometric order on the land that still determines property boundaries, road layouts, and settlement patterns over 200 years later."),
    q(25,"In many former Soviet cities, massive concrete apartment blocks (Khrushchyovkas) built in the 1960s still dominate the urban landscape, alongside grandiose Stalinist architecture and newer Western-style commercial buildings. The Soviet-era buildings reflect centralized planning and collective ideology. What concept does this layered urban landscape illustrate?",["Soviet architecture was purely functional","Sequent occupance, where successive political systems (Tsarist, Soviet, post-Soviet) leave distinct architectural layers on the landscape, creating visible evidence of political and ideological change","All cities look the same","Only the newest buildings matter"],1,"Former Soviet cities perfectly illustrate sequent occupance: each political era left distinctive architectural marks, from Tsarist churches to Stalinist grandeur to Khrushchev-era mass housing to post-Soviet commercial development."),
    q(26,"Bali's rice terrace landscape has been maintained for over 1,000 years through a cooperative water management system (subak) coordinated by Hindu temples. UNESCO designated it a cultural landscape because the agricultural, religious, and social systems are inseparable. What does this demonstrate?",["Agriculture and religion are always separate","Cultural landscapes can be living systems where agricultural practices, religious beliefs, and social organization are deeply intertwined and mutually dependent","Rice terraces are purely natural","UNESCO designations are meaningless"],1,"Bali's rice terraces demonstrate that cultural landscapes can be integrated systems where agriculture, religion, and social organization function as an inseparable whole. The temple-managed water system shows how spiritual and practical landscape uses can be unified."),
    q(27,"When Starbucks, McDonald's, and H&M open locations in historic European city centers, local residents often protest the loss of distinctive local character. Some cities (Paris, Rome) have enacted regulations restricting chain store signage and design in historic areas. What geographic tension does this represent?",["Global chains always improve local character","The tension between economic globalization driving standardized commercial landscapes and local efforts to preserve distinctive place identity and cultural heritage","No one cares about local character","Chain stores have no effect on cultural landscapes"],1,"This tension between globalization and local identity plays out in cultural landscapes worldwide. Chain stores bring economic efficiency but can erode the distinctive character that makes places unique and valuable for both residents and tourists."),
    q(28,"The Berlin Wall (1961-1989) physically divided the city into capitalist West and communist East. After its fall, the former wall's path remained visible in differences between building styles, street widths, and development patterns. Even today, satellite imagery can identify the former border by streetlight color differences. What does this demonstrate?",["Political boundaries leave no traces","Political divisions can permanently alter cultural landscapes, creating visible differences that persist long after the political boundary itself is removed","The Berlin Wall was unimportant","East and West Berlin were identical"],1,"Berlin demonstrates how political boundaries shape cultural landscapes in lasting ways. Decades of different political systems created divergent architectural styles, urban planning philosophies, and infrastructure that remain visible over 30 years after reunification."),
    q(29,"Heritage tourism has transformed places like Machu Picchu, Angkor Wat, and Venice into global tourist destinations. While tourism provides economic benefits, overcrowding threatens the physical integrity of these sites and displaces local residents. What dilemma does heritage tourism create?",["Tourism always benefits heritage sites","Tourism can simultaneously fund preservation and threaten destruction, creating a paradox where the economic value of cultural landscapes depends on visitor access that may degrade them","Tourism has no effect on heritage sites","All heritage sites should be closed to visitors"],1,"Heritage tourism creates a fundamental paradox: visitor revenue funds preservation, but excessive tourism erodes the physical sites and displaces the local communities whose living culture gives these places meaning."),
    q(30,"A suburban development in Texas features houses combining elements of Mediterranean villas, Colonial New England, and Southwestern adobe styles, all built with modern materials. This architectural mishmash has been called 'geography of nowhere.' What does this represent in cultural landscape terms?",["Authentic regional architecture","Placelessness and cultural homogenization, where mass-produced housing applies borrowed architectural elements without connection to local climate, materials, culture, or history","Innovative architectural design","Respect for multiple cultures"],1,"This architectural pastiche exemplifies placelessness: borrowed styles applied without connection to local geography, climate, or cultural history create landscapes lacking authentic identity. The result is a standardized suburban landscape that could exist anywhere."),
])

# ===== 4.1 Territorial Organization =====
print("4.1")
write_quiz(4,"4.1","Territorial Organization",[
    q(1,"What is a state in political geography?",["A subdivision of a country like Texas or California","A politically organized territory with a permanent population, defined territory, government, and sovereignty","Any area on a map","A cultural region"],1,"In political geography, a state is a sovereign political entity with a permanent population, defined territory, effective government, and capacity to enter relations with other states, as defined by the Montevideo Convention (1933)."),
    q(2,"How many sovereign states are recognized by the United Nations?",["About 50","About 100","About 193","About 300"],2,"The United Nations currently recognizes 193 member states, plus 2 observer states (Vatican City and Palestine). The exact number of sovereign states is debated because some entities claim sovereignty without universal recognition."),
    q(3,"What is sovereignty?",["The power of a king or queen","The supreme authority of a state to govern itself without external interference","International cooperation","A type of government"],1,"Sovereignty is the principle that a state has supreme authority over its territory and domestic affairs, free from external interference. It is the foundational concept of the modern international system established by the Peace of Westphalia (1648)."),
    q(4,"What is a federal state?",["A state with no subdivisions","A state where power is divided between a central government and regional units (states, provinces, cantons)","A state controlled by the military","A state with only one level of government"],1,"A federal state divides power between national and subnational governments. The United States, Germany, Canada, India, and Brazil are federal states where provinces or states have their own legislatures and significant autonomy."),
    q(5,"What is a unitary state?",["A state with only one city","A state with a single, centralized government that holds all power, with any local authority delegated from the center","A state with multiple governments","A united group of states"],1,"In a unitary state, the central government holds supreme authority and any local or regional governments derive their power from the center. France, Japan, and the United Kingdom are examples of unitary states."),
    q(6,"What is a territory in political geography?",["Any area of land","An area under the jurisdiction of a state but not having the full status of a state, often with limited self-governance","A country","A continent"],1,"Territories are areas under a state's control that lack full sovereignty or statehood. Examples include Puerto Rico (U.S. territory), French Polynesia (French territory), and the British Virgin Islands."),
    q(7,"What is the concept of territorial integrity?",["Building walls around a country","The principle that a state's borders should be respected and its territory should not be violated or annexed by another state","Maintaining clean borders","Having a large military"],1,"Territorial integrity is the international norm that states should not have their borders violated or territory seized by other states. It is a fundamental principle of the UN Charter and international law."),
    q(8,"What was the Peace of Westphalia (1648)?",["A peace treaty ending World War I","Treaties ending the Thirty Years War that established the modern concept of state sovereignty and territorial governance","A trade agreement","A religious document"],1,"The Peace of Westphalia ended the Thirty Years War and established principles of state sovereignty and non-interference that form the foundation of the modern international political system."),
    q(9,"What is devolution?",["The opposite of evolution","The transfer of power from a central government to regional or local authorities","The centralization of power","A revolution"],1,"Devolution transfers power from national to subnational levels. Scotland, Wales, and Northern Ireland have devolved governments within the UK, and Spain has granted significant autonomy to regions like Catalonia and the Basque Country."),
    q(10,"What is a capital city?",["The largest city in a country","The city where a country's government is located and from which the state is administered","The wealthiest city","Any major city"],1,"A capital city is the seat of government. Some countries have purpose-built capitals (Brasilia, Canberra, Abuja) separate from their largest city, while others have capitals that are also their primate cities (London, Paris, Tokyo)."),
    q(11,"What does 'sovereignty' mean?",["Having a monarch","The principle that a state has supreme and independent authority over its territory and people, free from external control","International authority over all states","Military power"],1,"Sovereignty means a state has the final authority over its territory and affairs. It encompasses both internal sovereignty (governing without internal challenge) and external sovereignty (recognition by other states)."),
    q(12,"What does 'self-determination' mean?",["Making personal choices","The right of a people or nation to determine their own form of government and political status without external coercion","Automation in industry","Self-guided learning"],1,"Self-determination is the principle that peoples have the right to freely determine their political status and pursue their economic, social, and cultural development. It has driven decolonization and independence movements globally."),
    q(13,"What is a 'buffer state'?",["A state that manufactures buffers","A small neutral state located between two larger, potentially hostile powers, reducing the risk of direct conflict","An island state","A state with no military"],1,"A buffer state is positioned between rival powers, reducing the chance of direct conflict. Historical examples include Thailand between British and French colonial empires, and Mongolia between Russia and China."),
    q(14,"What does 'enclave' mean?",["A large country","A territory entirely surrounded by another state's territory","A coastal territory","An island"],1,"An enclave is completely surrounded by another state. Lesotho (surrounded by South Africa) and Vatican City (surrounded by Italy) are enclaves. The term can also apply to ethnic or cultural enclaves within cities."),
    q(15,"What does 'exclave' mean?",["A former cave","A portion of a state's territory that is separated from the main body by another state's territory","An underground territory","A territory with no government"],1,"An exclave is a piece of a state geographically separated from the main territory by intervening foreign territory. Alaska is a U.S. exclave separated by Canada, and Kaliningrad is a Russian exclave between Lithuania and Poland."),
    q(16,"What is a 'landlocked state'?",["A state that has been invaded","A state entirely surrounded by land with no direct access to the ocean","An island state","A state with many lakes"],1,"Landlocked states lack ocean coastlines, which historically limited trade access. Examples include Bolivia, Switzerland, Mongolia, and many African states. Being landlocked is generally considered an economic disadvantage."),
    q(17,"What does 'compact state' mean?",["A very small state","A state whose territory is roughly circular or square, with all areas relatively close to the center","A densely populated state","A state with few natural resources"],1,"A compact state has a roughly circular or square shape where no point is far from the center, making governance and communication relatively efficient. Poland and Cambodia are examples of relatively compact states."),
    q(18,"What is a 'prorupted state'?",["A state that erupted from a volcano","A state with a compact core but an extension of territory projecting outward","A state that has been divided","A state with no coastline"],1,"A prorupted state has a compact core with an elongated extension. Thailand has a proruption extending southward, and the Democratic Republic of Congo has a proruption reaching the Atlantic coast. Proruptions often exist for strategic access."),
    q(19,"What does 'fragmented state' mean?",["A broken state","A state whose territory is composed of multiple non-contiguous pieces, often islands or territories separated by water or other states","A state with many political parties","A state undergoing civil war"],1,"A fragmented state consists of several separate territorial pieces. Indonesia (over 17,000 islands), the Philippines, and Malaysia are fragmented states. Managing a fragmented territory presents unique governance and communication challenges."),
    q(20,"What is an 'elongated state'?",["A state that takes a long time to cross","A state that is notably long and narrow, creating challenges for transportation, communication, and national integration","Any long country","A state with a long coastline"],1,"An elongated state is significantly longer than it is wide. Chile, stretching 4,300 km north to south but averaging only 177 km wide, is the classic example. Elongation creates challenges for infrastructure and governance."),
    q(21,"After World War II, Korea was divided at the 38th parallel into a Soviet-backed North and American-backed South. The Korean War (1950-53) solidified this division, creating two states from one nation with a heavily militarized border. What does the Korean Peninsula illustrate about territorial organization?",["Division of a nation is always permanent","External powers can impose territorial divisions that split nations, creating enduring geopolitical conflicts where the same people live under vastly different political systems","Korea was always two separate nations","Territorial divisions have no human consequences"],1,"Korea illustrates how external powers can impose territorial divisions that split a single nation into hostile states. The 38th parallel is an arbitrary line that divided families and created two radically different political systems from one people."),
    q(22,"Belgium is a federal state divided into Flemish-speaking Flanders, French-speaking Wallonia, and bilingual Brussels. Power is extensively devolved to linguistic communities and regions, with each having their own parliaments. Some argue Belgium is so devolved it barely functions as a unified state. What does Belgium demonstrate about federalism?",["Federalism always strengthens national unity","Federalism can accommodate deep cultural divisions but may also institutionalize those divisions, potentially weakening rather than strengthening national cohesion","Belgium is a unitary state","Federalism has no effect on national identity"],1,"Belgium demonstrates that federalism is a double-edged sword: it accommodates linguistic divisions by granting autonomy, but institutionalizing those divisions can make it harder to govern nationally, as separate institutions reinforce separate identities."),
    q(23,"Brasilia was built in the 1960s as a new capital in Brazil's interior, replacing coastal Rio de Janeiro. The goal was to promote development of the interior, create a neutral capital away from regional rivalries, and symbolize a modern Brazil. What does the creation of purpose-built capitals reveal?",["Capital location has no political significance","Capital city location is a deliberate political choice that can be used to promote territorial integration, project national identity, and balance regional power","All capitals are built from scratch","Rio de Janeiro was a poor capital"],1,"Purpose-built capitals (Brasilia, Canberra, Abuja, Naypyidaw) demonstrate that capital location is a strategic political decision. Moving a capital can promote territorial integration, reduce the dominance of one region, and signal a new national direction."),
    q(24,"Switzerland is a federal state with 26 cantons, four official languages, and a tradition of direct democracy. Despite its diversity, it has avoided the ethnic conflicts that plague many multilingual states. What factors explain Switzerland's successful territorial organization?",["Switzerland has no diversity","Strong cantonal autonomy within a federal system, combined with direct democracy and economic prosperity, allows diverse communities to govern themselves while sharing national institutions","Switzerland is actually a unitary state","Only small countries can be stable"],1,"Switzerland succeeds through radical decentralization: cantons have extensive autonomy in language, education, and culture, while shared national institutions, military service, and economic prosperity create centripetal forces. Its success model is often cited but rarely replicated."),
    q(25,"After decolonization, many African states inherited borders drawn by European powers at the Berlin Conference (1884-85) that divided ethnic groups and combined rival ones. Nigeria alone contains over 250 ethnic groups forced into one state. What long-term consequence has this had?",["African borders perfectly match ethnic territories","Colonial-era boundaries that ignored ethnic geography have created multiethnic states prone to ethnic tension, civil conflict, and governance challenges","African borders should never change","Colonialism had no effect on African territorial organization"],1,"Africa's colonial-era borders create ongoing challenges by forcing diverse and sometimes rival ethnic groups into single states while splitting others across borders. This mismatch between political and ethnic geography contributes to many of the continent's governance challenges."),
    q(26,"China governs Hong Kong and Macau as Special Administrative Regions (SARs) under the principle of 'one country, two systems,' allowing them to maintain separate legal, economic, and political systems from mainland China until 2047. What does this arrangement illustrate?",["All of China has the same system","States can accommodate territorial complexity through differentiated governance arrangements that give certain regions distinct political and economic status","SARs are independent countries","China has no territorial complexity"],1,"China's SARs demonstrate that states can use creative governance arrangements to manage territorial complexity. 'One country, two systems' allows capitalist Hong Kong and Macau to coexist within communist China, though tensions have grown."),
    q(27,"The European Union has created a supranational governance structure where member states voluntarily pool sovereignty on certain issues (trade, currency, movement of people) while retaining sovereignty on others (military, taxation). What does the EU represent in terms of territorial organization?",["The EU is a single country","A novel form of territorial organization between a traditional alliance and a federal state, where sovereignty is shared across multiple levels","The EU has replaced all member state governments","The EU has no effect on sovereignty"],1,"The EU represents a unique experiment in shared sovereignty that does not fit traditional categories. Member states retain their sovereignty but voluntarily delegate authority on specific matters, creating a multi-level governance system unprecedented in scope."),
    q(28,"Singapore is a city-state: an independent sovereign state consisting of a single city and its immediate surroundings. It has no natural resources, no hinterland, and a population of under 6 million, yet has one of the world's highest GDPs per capita. What does Singapore demonstrate about state viability?",["Small states cannot survive","A state's success depends on governance, human capital, strategic location, and trade policy rather than territorial size or natural resources","Only large countries can be wealthy","Natural resources are necessary for statehood"],1,"Singapore demonstrates that territorial size and natural resources are not prerequisites for state success. Strategic location, effective governance, investment in education, and integration into global trade networks can compensate for territorial limitations."),
    q(29,"The Antarctic Treaty System (1959) designates Antarctica as a continent devoted to peace and science, with no sovereign state having recognized territorial claims. Seven countries maintain overlapping claims, but these are frozen by the treaty. What unique territorial situation does Antarctica represent?",["Antarctica belongs to no one and nothing happens there","Antarctica represents a unique situation where territorial claims are suspended by international agreement, creating a governed but unsovereign space devoted to scientific cooperation","All of Antarctica belongs to Russia","The Antarctic Treaty has expired"],1,"Antarctica is unique in territorial organization: it is governed by international treaty rather than state sovereignty. Multiple overlapping claims are frozen, creating a space where international cooperation supersedes traditional territorial politics."),
    q(30,"After the Soviet Union dissolved in 1991, 15 new sovereign states emerged from one. Some transitions were peaceful (Baltic states), while others produced violent conflicts (Chechnya, Nagorno-Karabakh, Georgia). What does the Soviet dissolution illustrate about the relationship between internal territorial organization and state survival?",["The Soviet Union was not organized into territories","Federal structures designed to accommodate ethnic diversity can become frameworks for secession when central authority collapses, as internal boundaries become potential international borders","The Soviet dissolution was entirely peaceful","Territorial organization has no effect on state stability"],1,"The Soviet dissolution shows how internal territorial boundaries (Soviet republics) can become international borders when a state collapses. Federal structures that once managed diversity provided the institutional framework for new states, but mismatches between ethnic and republic boundaries created violent conflicts."),
])

print("Done with 3.5, 3.6, 4.1!")
