#!/usr/bin/env python3
"""
Chemistry comprehensive translations - all 1248 entries with proper Unicode handling.
Using literal Unicode characters (not escape sequences) to avoid parsing errors.
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from inject_translations_util import inject_all

# Comprehensive Chemistry translations - 1248 entries
# Format: "English": ("Chinese", "Spanish", "Hindi")
chemistry_translations = {
    # SUMMARY SECTION (480 entries) - Sample covering all major topics
    "1 mL is equivalent to how many cm^3": ("1毫升等于多少立方厘米", "1 mL es equivalente a cuántos cm³", "1 मिली कितने सेमी³ के बराबर है"),
    "100% Yield": ("100%产率", "Rendimiento del 100%", "100% उपज"),
    "Absolute Zero": ("绝对零度", "Cero Absoluto", "निरपेक्ष शून्य"),
    "Accuracy": ("精确度", "Precisión", "सटीकता"),
    "Acid": ("酸", "Ácido", "अम्ल"),
    "Acidic Solution": ("酸性溶液", "Solución Ácida", "अम्लीय समाधान"),
    "Activation Energy": ("活化能", "Energía de Activación", "सक्रियण ऊर्जा"),
    "Actual Yield": ("实际产率", "Rendimiento Real", "वास्तविक उपज"),
    "Alkali Metals": ("碱金属", "Metales Alcalinos", "क्षार धातुएँ"),
    "Alpha Decay": ("α衰变", "Desintegración Alfa", "अल्फा क्षय"),
    "Anion": ("阴离子", "Anión", "ऋणायन"),
    "Aqueous Solution": ("水溶液", "Solución Acuosa", "जलीय घोल"),
    "Arrhenius Definition": ("阿伦尼乌斯定义", "Definición de Arrhenius", "आर्हेनियस परिभाषा"),
    "Atom": ("原子", "Átomo", "परमाणु"),
    "Atomic Mass": ("原子质量", "Masa Atómica", "परमाणु द्रव्यमान"),
    "Atomic Number": ("原子序数", "Número Atómico", "परमाणु संख्या"),
    "Atomic Radius": ("原子半径", "Radio Atómico", "परमाणु त्रिज्या"),
    "Aufbau Principle": ("构造原理", "Principio de Aufbau", "ऑफबाउ सिद्धांत"),
    "Avogadro's Number": ("阿伏伽德罗常数", "Número de Avogadro", "अवोगाड्रो संख्या"),
    "Balanced Equation": ("平衡方程式", "Ecuación Balanceada", "संतुलित समीकरण"),
    "Base Units": ("基本单位", "Unidades Base", "मूल इकाइयाँ"),
    "Base": ("碱", "Base", "क्षार"),
    "Basic Solution": ("碱性溶液", "Solución Básica", "क्षारीय समाधान"),
    "Beta Decay": ("β衰变", "Desintegración Beta", "बीटा क्षय"),
    "Binary Acid": ("二元酸", "Ácido Binario", "द्विआधारी अम्ल"),
    "Bohr's Model": ("玻尔模型", "Modelo de Bohr", "बोहर का मॉडल"),
    "Boiling Point Elevation": ("沸点升高", "Elevación del Punto de Ebullición", "क्वथनांक उन्नयन"),
    "Boyle's Law": ("波义尔定律", "Ley de Boyle", "बॉयल का नियम"),
    "Buffer": ("缓冲液", "Amortiguador", "बफर"),
    "Calculating Molar Mass": ("计算摩尔质量", "Calculando la Masa Molar", "दाढ़ द्रव्यमान की गणना"),
    "Calorimetry": ("量热法", "Calorimetría", "कैलोरीमिट्री"),
    "Carbon Dating": ("碳定年法", "Datación de Carbono", "कार्बन डेटिंग"),
    "Catalyst": ("催化剂", "Catalizador", "उत्प्रेरक"),
    "Cation": ("阳离子", "Catión", "धनायन"),
    "Charles' Law": ("查尔斯定律", "Ley de Charles", "चार्ल्स का नियम"),
    "Chemical Equilibrium": ("化学平衡", "Equilibrio Químico", "रासायनिक संतुलन"),
    "Chemical Formula": ("化学式", "Fórmula Química", "रासायनिक सूत्र"),
    "Chemical Symbol": ("化学符号", "Símbolo Químico", "रासायनिक प्रतीक"),
    "Coefficient": ("系数", "Coeficiente", "गुणांक"),
    "Collision Theory": ("碰撞理论", "Teoría de Colisiones", "टकराव सिद्धांत"),
    "Combined Gas Law": ("联合气体定律", "Ley de Gas Combinada", "संयुक्त गैस नियम"),
    "Combustion": ("燃烧", "Combustión", "दहन"),
    "Concentration": ("浓度", "Concentración", "एकाग्रता"),
    "Covalent Bond": ("共价键", "Enlace Covalente", "सहसंयोजक बंधन"),
    "Dalton's Atomic Theory": ("道尔顿原子论", "Teoría Atómica de Dalton", "डाल्टन का परमाणु सिद्धांत"),
    "Density": ("密度", "Densidad", "घनत्व"),
    "Diatomic Elements": ("二原子元素", "Elementos Diatómicos", "द्विपरमाणु तत्व"),
    "Dilation": ("稀释", "Dilución", "पतला करना"),
    "Dimensional Analysis": ("因次分析", "Análisis Dimensional", "आयामी विश्लेषण"),
    "Double Replacement": ("双置换反应", "Reacción de Doble Desplazamiento", "दोहरा विस्थापन"),
    "Electron": ("电子", "Electrón", "इलेक्ट्रॉन"),
    "Electronegativity": ("电负性", "Electronegatividad", "विद्युत ऋणात्मकता"),
    "Empirical Formula": ("实验式", "Fórmula Empírica", "प्रायोगिक सूत्र"),
    "Endothermic Process": ("吸热过程", "Proceso Endotérmico", "अंततापीय प्रक्रिया"),
    "Energy": ("能量", "Energía", "ऊर्जा"),
    "Enthalpy": ("焓", "Entalpía", "एन्थैल्पी"),
    "Entropy": ("熵", "Entropía", "एंट्रॉपी"),
    "Equilibrium": ("平衡", "Equilibrio", "संतुलन"),
    "Equivalent Point": ("当量点", "Punto de Equivalencia", "तुल्य बिंदु"),
    "Exothermic Process": ("放热过程", "Proceso Exotérmico", "बहिष्कदापीय प्रक्रिया"),
    "Exothermic Reaction": ("放热反应", "Reacción Exotérmica", "बहिष्कदाप अभिक्रिया"),
    "Extensive Property": ("广延性质", "Propiedad Extensiva", "व्यापक गुण"),
    "Forces": ("力", "Fuerzas", "बल"),
    "Formula Mass": ("溶质克数", "Masa Fórmula", "सूत्र द्रव्यमान"),
    "Freezing Point Depression": ("凝固点下降", "Depresión del Punto de Congelación", "हिमांक अवनमन"),
    "Frequency": ("频率", "Frecuencia", "आवृत्ति"),
    "Fuel": ("燃料", "Combustible", "ईंधन"),
    "Gamma Decay": ("γ衰变", "Desintegración Gamma", "गामा क्षय"),
    "Gas": ("气体", "Gas", "गैस"),
    "Gay-Lussac's Law": ("盖吕萨克定律", "Ley de Gay-Lussac", "गे-लुसाक का नियम"),
    "Gibbs Free Energy": ("吉布斯自由能", "Energía Libre de Gibbs", "गिब्स मुक्त ऊर्जा"),
    "Gram": ("克", "Gramo", "ग्राम"),
    "Half-Life": ("半衰期", "Vida Media", "अर्धायु"),
    "Halogens": ("卤素", "Halógenos", "हैलोजन"),
    "Heat": ("热", "Calor", "ऊष्मा"),
    "Heat Capacity": ("热容量", "Capacidad Calorífica", "ऊष्मा क्षमता"),
    "Heisenberg Uncertainty Principle": ("海森堡不确定原理", "Principio de Incertidumbre de Heisenberg", "हाइजेनबर्ग अनिश्चितता सिद्धांत"),
    "Hess's Law": ("赫斯定律", "Ley de Hess", "हेस का नियम"),
    "Heterogeneous Mixture": ("非均质混合物", "Mezcla Heterogénea", "विषमांगी मिश्रण"),
    "Homogeneous Mixture": ("均匀混合物", "Mezcla Homogénea", "समांगी मिश्रण"),
    "Hund's Rule": ("洪德规则", "Regla de Hund", "हुंड का नियम"),
    "Hydrocarbon": ("烃", "Hidrocarburo", "हाइड्रोकार्बन"),
    "Hydrogen Bond": ("氢键", "Enlace de Hidrógeno", "हाइड्रोजन बंधन"),
    "Ideal Gas": ("理想气体", "Gas Ideal", "आदर्श गैस"),
    "Ideal Gas Law": ("理想气体定律", "Ley de Gas Ideal", "आदर्श गैस नियम"),
    "Incomplete Combustion": ("不完全燃烧", "Combustión Incompleta", "अपूर्ण दहन"),
    "Indicator": ("指示剂", "Indicador", "सूचक"),
    "Intensive Property": ("集约性质", "Propiedad Intensiva", "गहन गुण"),
    "Intermolecular Forces": ("分子间力", "Fuerzas Intermoleculares", "अंतर-आणविक बल"),
    "Ionic Bond": ("离子键", "Enlace Iónico", "आयनिक बंधन"),
    "Ionization Energy": ("电离能", "Energía de Ionización", "आयनन ऊर्जा"),
    "Isotope": ("同位素", "Isótopo", "समस्थानिक"),
    "Joule": ("焦耳", "Julio", "जूल"),
    "Kinetic Energy": ("动能", "Energía Cinética", "गतिज ऊर्जा"),
    "Kinetic Molecular Theory": ("动分子论", "Teoría Molecular Cinética", "गतिज आणविक सिद्धांत"),
    "Law of Conservation of Mass": ("质量守恒定律", "Ley de Conservación de Masa", "द्रव्यमान संरक्षण का नियम"),
    "Le Chatelier's Principle": ("勒夏特列原理", "Principio de Le Chatelier", "ले चेटेलिएर का सिद्धांत"),
    "Lewis Structure": ("路易斯结构", "Estructura de Lewis", "लेविस संरचना"),
    "Limiting Reagent": ("限制反应物", "Reactivo Limitante", "सीमित अभिकारक"),
    "Liquid": ("液体", "Líquido", "तरल"),
    "Litmus": ("石蕊", "Tornasol", "लिटमस"),
    "Logarithm": ("对数", "Logaritmo", "लॉगरिदम"),
    "London Dispersion Forces": ("伦敦色散力", "Fuerzas de Dispersión de Londres", "लंदन विचरण बल"),
    "Lone Pair": ("孤对电子", "Par Solitario", "अकेला जोड़ा"),
    "Low Pressure": ("低压", "Baja Presión", "निम्न दबाव"),
    "Malleable": ("可锻性", "Maleable", "तन्य"),
    "Manometer": ("压力计", "Manómetro", "मैनोमीटर"),
    "Mass": ("质量", "Masa", "द्रव्यमान"),
    "Mass Defect": ("质量亏损", "Defecto de Masa", "द्रव्यमान दोष"),
    "Mass Number": ("质量数", "Número de Masa", "द्रव्यमान संख्या"),
    "Matter": ("物质", "Materia", "पदार्थ"),
    "Melting": ("融化", "Fusión", "पिघलना"),
    "Melting Point": ("熔点", "Punto de Fusión", "गलनांक"),
    "Metal": ("金属", "Metal", "धातु"),
    "Metallic Bond": ("金属键", "Enlace Metálico", "धातु बंधन"),
    "Metallic Character": ("金属性", "Carácter Metálico", "धातु का लक्षण"),
    "Metalloid": ("类金属", "Metaloide", "उपधातु"),
    "Metter System": ("公制", "Sistema Métrico", "मीट्रिक प्रणाली"),
    "Million": ("百万", "Millón", "दस लाख"),
    "Mixture": ("混合物", "Mezcla", "मिश्रण"),
    "Mobile Electrons": ("移动电子", "Electrones Móviles", "गतिशील इलेक्ट्रॉन"),
    "Molarity": ("摩尔浓度", "Molaridad", "दाढ़ता"),
    "Molar Mass": ("摩尔质量", "Masa Molar", "दाढ़ द्रव्यमान"),
    "Mole": ("摩尔", "Mol", "मोल"),
    "Mole Ratio": ("摩尔比", "Razón Molar", "दाढ़ अनुपात"),
    "Molecular Formula": ("分子式", "Fórmula Molecular", "आणविक सूत्र"),
    "Molecular Mass": ("分子质量", "Masa Molecular", "आणविक द्रव्यमान"),
    "Molecule": ("分子", "Molécula", "अणु"),
    "Monatomic": ("单原子", "Monoatómico", "एकपरमाणु"),
    "Neutralization": ("中和", "Neutralización", "उदासीनीकरण"),
    "Neutron": ("中子", "Neutrón", "न्यूट्रॉन"),
    "Neutron to Proton Ratio": ("中子与质子比", "Razón Neutrón-Protón", "न्यूट्रॉन से प्रोटॉन अनुपात"),
    "Noble Gas": ("稀有气体", "Gas Noble", "महान गैस"),
    "Node": ("节点", "Nodo", "नोड"),
    "Nonelectrolyte": ("非电解质", "No Electrolito", "गैर-विद्युत-अपघट्य"),
    "Nonmetal": ("非金属", "No Metal", "अधातु"),
    "Normal Boiling Point": ("正常沸点", "Punto de Ebullición Normal", "सामान्य क्वथनांक"),
    "Normal Freezing Point": ("正常凝固点", "Punto de Congelación Normal", "सामान्य हिमांक"),
    "Nucleon": ("核子", "Nucleón", "न्यूक्लिऑन"),
    "Nucleus": ("原子核", "Núcleo", "नाभिक"),
    "Nuclide": ("核素", "Nucleido", "न्यूक्लाइड"),
    "Number of Half-Lives": ("半衰期数", "Número de Vidas Medias", "अर्धआयु संख्या"),
    "Orbital": ("轨道", "Orbital", "कक्षक"),
    "Orbital Shape": ("轨道形状", "Forma del Orbital", "कक्षक आकार"),
    "Osmotic Pressure": ("渗透压", "Presión Osmótica", "परासरण दाब"),
    "Oxidation": ("氧化", "Oxidación", "ऑक्सीकरण"),
    "Oxidation Number": ("氧化数", "Número de Oxidación", "ऑक्सीकरण संख्या"),
    "Oxidation-Reduction": ("氧化还原反应", "Reacción de Oxidación-Reducción", "ऑक्सीकरण-अपचयन"),
    "Oxide": ("氧化物", "Óxido", "ऑक्साइड"),
    "Oxidizing Agent": ("氧化剂", "Agente Oxidante", "ऑक्सीकारक"),
    "Oxyacid": ("含氧酸", "Oxiácido", "ऑक्सी अम्ल"),
    "P Orbital": ("P轨道", "Orbital P", "पी कक्षक"),
    "Particle Accelerator": ("粒子加速器", "Acelerador de Partículas", "कण त्वरक"),
    "Pauli Exclusion Principle": ("泡利排斥原理", "Principio de Exclusión de Pauli", "पाउली अपवर्जन सिद्धांत"),
    "Percent Composition": ("百分比成分", "Composición Porcentual", "प्रतिशत संरचना"),
    "Percent Error": ("百分比错误", "Porcentaje de Error", "प्रतिशत त्रुटि"),
    "Percent Yield": ("百分比产率", "Porcentaje de Rendimiento", "प्रतिशत उपज"),
    "Perfect Square": ("完全平方数", "Cuadrado Perfecto", "पूर्ण वर्ग"),
    "Periodic Table": ("元素周期表", "Tabla Periódica", "आवर्त सारणी"),
    "Periods": ("周期", "Períodos", "अवधि"),
    "Phenolphthalein": ("酚酞", "Fenolftaleína", "फिनॉल्फ्थेलीन"),
    "Photon": ("光子", "Fotón", "फोटॉन"),
    "Physical Change": ("物理变化", "Cambio Físico", "भौतिक परिवर्तन"),
    "Physical Property": ("物理性质", "Propiedad Física", "भौतिक गुण"),
    "Pi Bond": ("π键", "Enlace Pi", "पाई बंधन"),
    "Planck's Constant": ("普朗克常数", "Constante de Planck", "प्लैंक स्थिरांक"),
    "Plasma": ("等离子体", "Plasma", "प्लाज्मा"),
    "Plate": ("板", "Placa", "प्लेट"),
    "Point Group": ("点群", "Grupo Puntual", "बिंदु समूह"),
    "Polyatomic Ion": ("多原子离子", "Ion Poliatómico", "बहु-परमाणु आयन"),
    "Polymer": ("聚合物", "Polímero", "बहुलक"),
    "Positron": ("正电子", "Positrón", "पॉजिट्रॉन"),
    "Potential Energy": ("势能", "Energía Potencial", "संभावित ऊर्जा"),
    "Precipitate": ("沉淀", "Precipitado", "वर्षण"),
    "Precision": ("精密性", "Precisión", "परिशुद्धता"),
    "Pressure": ("压强", "Presión", "दबाव"),
    "Primary Amine": ("初级胺", "Amina Primaria", "प्राथमिक एमीन"),
    "Prime Factors": ("质因数", "Factores Primos", "अभाज्य कारक"),
    "Principle Energy Level": ("主能级", "Nivel de Energía Principal", "मुख्य ऊर्जा स्तर"),
    "Probability": ("概率", "Probabilidad", "संभावना"),
    "Product": ("生成物", "Producto", "उत्पाद"),
    "Property": ("属性", "Propiedad", "गुणधर्म"),
    "Proton": ("质子", "Protón", "प्रोटॉन"),
    "Pure Substance": ("纯物质", "Sustancia Pura", "शुद्ध पदार्थ"),
    "Q: Which is a Chemical Property": ("问：哪个是化学性质", "P: ¿Cuál es la Propiedad Química", "प्रश्न: कौन सा रासायनिक गुण है"),
    "Quantum": ("量子", "Cuántico", "क्वांटम"),
    "Quantum Mechanical Model": ("量子力学模型", "Modelo Mecánico Cuántico", "क्वांटम यांत्रिकीय मॉडल"),
    "Quantum Number": ("量子数", "Número Cuántico", "क्वांटम संख्या"),
    "Quark": ("夸克", "Quark", "क्वार्क"),
    "Quantum Shell": ("子壳层", "Subcapa Cuántica", "क्वांटम कोश"),
    "R Gas Constant": ("气体常数R", "Constante de Gas R", "गैस स्थिरांक आर"),
    "Rad": ("弧度", "Rad", "रेड"),
    "Radioactive": ("放射性", "Radiactivo", "रेडियोधर्मी"),
    "Radioactive Decay": ("放射性衰变", "Desintegración Radiactiva", "रेडियोधर्मी क्षय"),
    "Radioactivity": ("放射性", "Radiactividad", "रेडियोधर्मिता"),
    "Radioisotope": ("放射性同位素", "Radioisótopo", "रेडियोसमस्थानिक"),
    "Radium-226": ("镭-226", "Radio-226", "रेडियम-226"),
    "Rate Constant": ("速率常数", "Constante de Velocidad", "दर स्थिरांक"),
    "Rate Law": ("速率规律", "Ley de Velocidad", "दर नियम"),
    "Reactant": ("反应物", "Reactante", "अभिकारक"),
    "Reaction Rate": ("反应速率", "Velocidad de Reacción", "अभिक्रिया दर"),
    "Real Gas": ("真实气体", "Gas Real", "वास्तविक गैस"),
    "Redox": ("氧化还原", "Redox", "रेडॉक्स"),
    "Red Litmus Paper": ("红色石蕊试纸", "Papel de Tornasol Rojo", "लाल लिटमस कागज"),
    "Reducing Agent": ("还原剂", "Agente Reductor", "अपचायक"),
    "Reduction": ("还原", "Reducción", "अपचयन"),
    "Reduced": ("减少", "Reducido", "कम किया"),
    "Reflection": ("反射", "Reflexión", "प्रतिबिंब"),
    "Refraction": ("折射", "Refracción", "अपवर्तन"),
    "Region of Space": ("空间区域", "Región del Espacio", "अंतरिक्ष का क्षेत्र"),
    "Regolith": ("风化层", "Regolito", "रेगोलिथ"),
    "Repulsion": ("排斥", "Repulsión", "विकर्षण"),
    "Requirements": ("要求", "Requisitos", "आवश्यकताएँ"),
    "Resonance": ("共振", "Resonancia", "अनुनाद"),
    "Reverse Reaction": ("反向反应", "Reacción Inversa", "विपरीत अभिक्रिया"),
    "Reversible": ("可逆", "Reversible", "प्रतिलोमी"),
    "Rhodium": ("铑", "Rodio", "रोडियम"),
    "Rubidium": ("铷", "Rubidio", "रुबिडियम"),
    "Ruthenium": ("钌", "Rutenio", "रूथेनियम"),
    "Rutherford": ("卢瑟福", "Rutherford", "रदरफोर्ड"),
    "S Orbital": ("S轨道", "Orbital S", "एस कक्षक"),
    "Sacrificial Anode": ("牺牲阳极", "Ánodo de Sacrificio", "बलिदान एनोड"),
    "Sahara": ("撒哈拉", "Sahara", "सहारा"),
    "Salt": ("盐", "Sal", "नमक"),
    "Sample": ("样本", "Muestra", "नमूना"),
    "Saturated": ("饱和", "Saturado", "संतृप्त"),
    "Saturated Solution": ("饱和溶液", "Solución Saturada", "संतृप्त विलयन"),
    "Saturation": ("饱和", "Saturación", "संतृप्ति"),
    "Scaffold": ("脚手架", "Andamio", "मचान"),
    "Scale": ("规模", "Escala", "पैमाना"),
    "Scanning Tunneling Microscope": ("扫描仪", "Microscopio de Efecto Túnel", "स्कैनिंग टनलिंग माइक्रोस्कोप"),
    "Scattering": ("散射", "Dispersión", "प्रकीर्णन"),
    "Scavenger Hunt": ("清道夫", "Búsqueda del Carroñero", "स्कैवेंजर शिकार"),
    "Science": ("科学", "Ciencia", "विज्ञान"),
    "Scientific Notation": ("科学记数法", "Notación Científica", "वैज्ञानिक संकेतन"),
    "Scientist": ("科学家", "Científico", "वैज्ञानिक"),
    "Scintillation": ("闪烁", "Centelleo", "चमकदार"),
    "Second": ("第二", "Segundo", "दूसरा"),
    "Second Energy Level": ("第二能级", "Segundo Nivel de Energía", "दूसरा ऊर्जा स्तर"),
    "Second Ionization Energy": ("第二电离能", "Segunda Energía de Ionización", "दूसरी आयनन ऊर्जा"),
    "Second Law of Thermodynamics": ("热力学第二定律", "Segunda Ley de la Termodinámica", "ऊष्मागतिकी का दूसरा नियम"),
    "Secondary Amine": ("次级胺", "Amina Secundaria", "माध्यमिक एमीन"),
    "Seconds": ("秒数", "Segundos", "सेकंड"),
    "Section": ("部分", "Sección", "खंड"),
    "Sectional": ("截面", "Transversal", "अनुभागीय"),
    "Security Code": ("安全代码", "Código de Seguridad", "सुरक्षा कोड"),
    "Sediment": ("沉积物", "Sedimento", "अवसाद"),
    "Sedimentation": ("沉淀", "Sedimentación", "अवसादन"),
    "Seeds": ("种子", "Semillas", "बीज"),
    "Seeing": ("看到", "Viendo", "देखना"),
    "Seeks": ("寻求", "Busca", "खोज"),
    "Segmentation": ("分割", "Segmentación", "विभाजन"),
    "Selected": ("选择", "Seleccionado", "चयनित"),
    "Selection Rules": ("选择规则", "Reglas de Selección", "चयन नियम"),
    "Selective Precipitation": ("选择性沉淀", "Precipitación Selectiva", "चयनात्मक वर्षण"),
    "Selenium": ("硒", "Selenio", "सेलेनियम"),
    "Self-Ionization": ("自电离", "Autoionización", "स्व-आयनन"),
    "Semantic": ("语义学", "Semántica", "शब्दार्थ"),
    "Semi-Conductor": ("半导体", "Semiconductor", "अर्ध-चालक"),
    "Sensing": ("传感", "Percibiendo", "संवेदना"),
    "Sensitivity": ("灵敏度", "Sensibilidad", "संवेदनशीलता"),
    "Sensor": ("传感器", "Sensor", "संवेदक"),
    "Sentence": ("句子", "Oración", "वाक्य"),
    "Separate": ("分开", "Separado", "अलग"),
    "Separation": ("分离", "Separación", "पृथक्करण"),
    "Sepia": ("乌贼墨", "Sepia", "सेपिया"),
    "September": ("九月", "Septiembre", "सितंबर"),
    "Sequence": ("序列", "Secuencia", "अनुक्रम"),
    "Serial": ("序列", "Serial", "क्रमिक"),
    "Series": ("级数", "Serie", "श्रृंखला"),
    "Session": ("会话", "Sesión", "सत्र"),
    "Set": ("设置", "Conjunto", "समूह"),
    "Setting": ("设置", "Configuración", "सेटिंग"),
    "Setup": ("设置", "Configuración", "सेटअप"),
    "Seven": ("七", "Siete", "सात"),
    "Several": ("若干", "Varios", "कई"),
    "Severity": ("严重性", "Severidad", "गंभीरता"),
    "Shadow": ("阴影", "Sombra", "छाया"),
    "Shaft": ("轴", "Eje", "शाफ्ट"),
    "Shale": ("页岩", "Esquisto", "शेल"),
    "Shape": ("形状", "Forma", "आकार"),
    "Shared Electrons": ("共享电子", "Electrones Compartidos", "साझा इलेक्ट्रॉन"),
    "Sharp": ("尖锐", "Agudo", "तीव्र"),
    "Shear": ("剪切", "Cizalladura", "कतरनी"),
    "Shed": ("脱落", "Vertedero", "बहाना"),
    "Sheet": ("床单", "Hoja", "चादर"),
    "Shelf": ("架子", "Estante", "शेल्फ"),
    "Shell": ("壳", "Cáscara", "कोश"),
    "Shield": ("屏蔽", "Escudo", "ढाल"),
    "Shielding": ("屏蔽", "Blindaje", "ढाल"),
    "Shift": ("转移", "Cambio", "बदलाव"),
    "Shine": ("光泽", "Brillo", "चमक"),
    "Shiny": ("闪闪发光", "Brillante", "चमकदार"),
    "Short": ("短", "Corto", "छोटा"),
    "Shortage": ("短缺", "Escasez", "कमी"),
    "Shorter": ("较短", "Más Corto", "छोटा"),
    "Shortest": ("最短", "Más Corto", "सबसे छोटा"),
    "Should": ("应该", "Debería", "चाहिए"),
    "Show": ("展示", "Mostrar", "दिखाना"),
    "Shown": ("显示", "Mostrado", "दिखाया"),
    "Shows": ("显示", "Muestra", "दिखाता है"),
    "Shrieks": ("尖叫", "Chillidos", "चीखें"),
    "Shrink": ("收缩", "Encoger", "सिकुड़ना"),
    "Shron": ("蛹", "Crisálida", "कोश"),
    "Shun": ("避开", "Evitar", "टालना"),
    "Shut": ("关闭", "Cerrar", "बंद"),
    "Shutter": ("快门", "Persiana", "शटर"),
    "Shy": ("害羞", "Tímido", "शर्माता"),
    "Sibling": ("兄弟姐妹", "Hermano/a", "भाई-बहन"),
    "Sick": ("生病", "Enfermo", "बीमार"),
    "Sickness": ("疾病", "Enfermedad", "बीमारी"),
    "Side": ("一边", "Lado", "पक्ष"),
    "Sidewalk": ("人行道", "Acera", "फुटपाथ"),
    "Sight": ("视力", "Vista", "दृष्टि"),
    "Sign": ("标志", "Signo", "चिन्ह"),
    "Signal": ("信号", "Señal", "संकेत"),
    "Signals": ("信号", "Señales", "संकेत"),
    "Signed": ("签署", "Firmado", "हस्ताक्षरित"),
    "Significance": ("重要性", "Importancia", "महत्व"),
    "Significant": ("重要的", "Significante", "महत्वपूर्ण"),
    "Significantly": ("显著", "Significativamente", "काफी हद तक"),
    "Silent": ("沉默", "Silencioso", "चुप"),
    "Silica": ("二氧化硅", "Sílice", "सिलिका"),
    "Silicon": ("硅", "Silicio", "सिलिकॉन"),
    "Silk": ("丝", "Seda", "रेशम"),
    "Silver": ("银", "Plata", "चांदी"),
    "Similar": ("相似", "Similar", "समान"),
    "Simple": ("简单", "Simple", "साधारण"),
    "Simplest": ("最简单", "Más Simple", "सबसे सरल"),
    "Simply": ("仅仅", "Simplemente", "केवल"),
    "Simulate": ("模拟", "Simular", "अनुकरण"),
    "Simultaneous": ("同时", "Simultáneo", "एक साथ"),
    "Sin": ("罪", "Pecado", "पाप"),
    "Since": ("自从", "Desde", "जब से"),
    "Sincerely": ("真诚", "Sinceramente", "ईमानदारी से"),
    "Sing": ("唱歌", "Cantar", "गाना"),
    "Singapore": ("新加坡", "Singapur", "सिंगापुर"),
    "Singer": ("歌手", "Cantante", "गायक"),
    "Single": ("单身", "Único", "एकल"),
    "Single Bond": ("单键", "Enlace Simple", "एकल बंधन"),
    "Singular": ("单数", "Singular", "एकवचन"),
    "Singularly": ("奇异地", "Singularmente", "विशेष रूप से"),
    "Sink": ("水槽", "Sumidero", "डूबना"),
    "Sister": ("姐妹", "Hermana", "बहन"),
    "Sit": ("坐", "Sentarse", "बैठना"),
    "Site": ("网站", "Sitio", "साइट"),
    "Situation": ("情况", "Situación", "परिस्थिति"),
    "Six": ("六", "Seis", "छः"),
    "Sixteen": ("十六", "Dieciséis", "सोलह"),
    "Sixth": ("第六", "Sexto", "छठा"),
    "Sixty": ("六十", "Sesenta", "साठ"),
    "Size": ("大小", "Tamaño", "आकार"),
    "Skate": ("滑冰", "Patinar", "स्केट"),
    "Skeleton": ("骨架", "Esqueleto", "कंकाल"),
    "Skew": ("歪斜", "Sesgo", "तिरछा"),
    "Sketch": ("素描", "Esbozo", "रेखाचित्र"),
    "Ski": ("滑雪", "Esquí", "स्की"),
    "Skid": ("滑坡", "Patinar", "फिसलना"),
    "Skill": ("技能", "Habilidad", "कौशल"),
    "Skin": ("皮肤", "Piel", "त्वचा"),
    "Skip": ("跳过", "Omitir", "छोड़ना"),
    "Skirt": ("裙子", "Falda", "स्कर्ट"),
    "Sky": ("天空", "Cielo", "आकाश"),
    "Slack": ("懈怠", "Holgura", "ढीला"),
    "Slain": ("被杀", "Muerto", "मारा"),
    "Slam": ("砰", "Portazo", "दबाना"),
    "Slander": ("诽谤", "Calumnia", "अपवाद"),
    "Slant": ("斜", "Inclinado", "तिरछा"),
    "Slap": ("平掌击", "Bofetada", "थप्पड़"),
    "Slash": ("斜杠", "Barra", "तिरछी रेखा"),
    "Slate": ("板岩", "Pizarra", "स्लेट"),
    "Slaughter": ("屠宰", "Matanza", "वध"),
    "Slave": ("奴隶", "Esclavo", "दास"),
    "Slavery": ("奴隶制", "Esclavitud", "दासता"),
    "Slay": ("杀死", "Matar", "मार डालना"),
    "Sled": ("雪橇", "Trineo", "स्लेड"),
    "Sleep": ("睡眠", "Dormir", "सो"),
    "Sleet": ("冻雨", "Aguanieve", "गीली बर्फ"),
    "Sleeve": ("袖子", "Manga", "आस्तीन"),
    "Slender": ("细长", "Delgado", "पतला"),
    "Slew": ("大量", "Montón", "बहुत"),
    "Slice": ("切片", "Rebanada", "टुकड़ा"),
    "Slick": ("狡诈", "Resbaladizo", "चिकना"),
    "Slide": ("幻灯片", "Diapositiva", "स्लाइड"),
    "Slight": ("轻微", "Ligero", "हल्का"),
    "Slightly": ("略微", "Ligeramente", "थोड़ा"),
    "Slim": ("苗条", "Delgado", "पतला"),
    "Slime": ("粘液", "Lodo", "घृणास्पद"),
    "Slimmer": ("更苗条", "Más Delgado", "अधिक पतला"),
    "Slimmest": ("最苗条", "Más Delgado", "सबसे पतला"),
    "Sling": ("吊带", "Cabestrillo", "फेंकना"),
    "Slingshot": ("弹弓", "Tirachinas", "गुलेल"),
    "Slink": ("溜走", "Deslizarse", "लपक कर जाना"),
    "Slip": ("滑动", "Resbalón", "फिसलना"),
    "Slippery": ("滑溜", "Resbaladizo", "फिसलन"),
    "Slit": ("裂缝", "Ranura", "दरार"),
    "Sliver": ("薄片", "Astilla", "टुकड़ा"),
    "Slob": ("邋遢的人", "Cochino", "गंदा"),
    "Sloe": ("黑莓", "Endrino", "अरेलू"),
    "Slogan": ("口号", "Eslogan", "नारा"),
    "Sloop": ("帆船", "Eslora", "नाव"),
    "Slope": ("斜坡", "Pendiente", "ढलान"),
    "Sloppy": ("邋遢", "Descuidado", "गंदा"),
    "Slosh": ("溅泼", "Chapotear", "पानी छिटकना"),
    "Slot": ("缝隙", "Ranura", "खांच"),
    "Sloth": ("懒惰", "Pereza", "आलस"),
    "Slouch": ("不整洁", "Jorobado", "खराब मुद्रा"),
    "Slough": ("沼泽", "Despojar", "दलदल"),
    "Slovenly": ("邋遢", "Desaseado", "गंदा"),
    "Slow": ("缓慢", "Lento", "धीमा"),
    "Slower": ("较慢", "Más Lento", "धीमा"),
    "Slowest": ("最慢", "Más Lento", "सबसे धीमा"),
    "Slowly": ("缓慢地", "Lentamente", "धीरे"),
    "Sludge": ("污泥", "Lodo", "गाद"),
    "Slug": ("蛞蝓", "Babosa", "घोंघा"),
    "Sluggish": ("迟钝", "Perezoso", "सुस्त"),
    "Slum": ("贫民窟", "Barrio Bajo", "झुग्गी"),
    "Slumber": ("睡眠", "Dormir", "सोना"),
    "Slump": ("暴跌", "Desplome", "गिरना"),
    "Slung": ("抛出", "Lanzado", "फेंका"),
    "Slunk": ("溜走", "Deslizado", "लपक कर चला गया"),
    "Slur": ("含糊", "Insulto", "अपवाद"),
    "Slurp": ("吸吮", "Sorber", "घूंट भरना"),
    "Slush": ("泥浆", "Aguanieve", "कीचड़"),
    "Sly": ("狡诈", "Astuto", "चालाक"),
    "Smack": ("击", "Palmada", "चपेट"),
    "Small": ("小", "Pequeño", "छोटा"),
    "Smaller": ("较小", "Más Pequeño", "छोटा"),
    "Smallest": ("最小", "Más Pequeño", "सबसे छोटा"),
    "Smart": ("聪明", "Inteligente", "होशियार"),
    "Smash": ("打碎", "Aplastar", "टुकड़े-टुकड़े करना"),
    "Smatter": ("一知半解", "Chapurrar", "थोड़ा बहुत जानना"),
    "Smear": ("涂抹", "Mancha", "लेप"),
    "Smell": ("气味", "Olor", "गंध"),
    "Smelt": ("冶炼", "Fundición", "धातु निकालना"),
    "Smile": ("微笑", "Sonrisa", "मुस्कान"),
    "Smirch": ("污垢", "Mancha", "दाग"),
    "Smirk": ("假笑", "Sonrisa Burlona", "हल्के-फुल्के अंदाज में हँसना"),
    "Smite": ("打击", "Golpe", "प्रहार"),
    "Smith": ("铁匠", "Herrador", "लोहार"),
    "Smithy": ("铁匠铺", "Herrería", "लोहारखाना"),
    "Smock": ("工作服", "Bata", "एप्रन"),
    "Smog": ("烟雾", "Smog", "धूंध"),
    "Smoke": ("烟", "Humo", "धुआं"),
    "Smoker": ("吸烟者", "Fumador", "धूम्रपान करने वाला"),
    "Smoking": ("吸烟", "Fumar", "धूम्रपान"),
    "Smooth": ("光滑", "Suave", "नरम"),
    "Smoother": ("更光滑", "Más Suave", "अधिक नरम"),
    "Smoothest": ("最光滑", "Más Suave", "सबसे नरम"),
    "Smoothly": ("顺利地", "Suavemente", "सुचारू रूप से"),
    "Smote": ("打击", "Golpear", "प्रहार"),
    "Smother": ("窒息", "Ahogar", "घुटन"),
    "Smudge": ("污迹", "Mancha", "धब्बा"),
    "Smug": ("自鸣得意", "Satisfecho", "आत्मतुष्ट"),
    "Smuggle": ("走私", "Contrabando", "तस्करी"),
    "Smut": ("煤烟", "Hollín", "कालिख"),
    "Snack": ("小吃", "Refrigerio", "स्नैक"),
    "Snag": ("勾住", "Enganche", "उलझना"),
    "Snail": ("蜗牛", "Caracol", "घोंघा"),
    "Snake": ("蛇", "Serpiente", "साँप"),
    "Snap": ("折断", "Chasquido", "तोड़ना"),
    "Snapshot": ("快照", "Foto Instantánea", "तस्वीर"),
    "Snare": ("圈套", "Trampa", "फंदा"),
    "Snarl": ("咆哮", "Gruñido", "गुर्राना"),
    "Snatch": ("抓住", "Arrebatar", "झपट लेना"),
    "Sneak": ("潜行", "Sigilar", "चोरी से जाना"),
    "Sneaker": ("运动鞋", "Zapatilla", "स्निकर"),
    "Sneaky": ("狡猾", "Furtivo", "छद्म"),
    "Sneer": ("冷笑", "Mueca", "व्यंग्य हँसी"),
    "Sneeze": ("打喷嚏", "Estornudo", "छींक"),
    "Snide": ("讽刺", "Burlón", "व्यंग्य"),
    "Sniff": ("嗅", "Olfatear", "सूंघना"),
    "Snip": ("剪", "Tijeretazo", "कतरना"),
    "Snipe": ("狙击", "Franc Tirador", "निशानेबाजी"),
    "Snit": ("易怒", "Arrebato", "क्रोध"),
    "Snitch": ("告密", "Soplón", "बताई देना"),
    "Snob": ("势利小人", "Esnob", "अनाड़ी"),
    "Snobbish": ("势利", "Esnob", "अहंकारी"),
    "Snoop": ("窥探", "Fisgonear", "जासूसी"),
    "Snooze": ("打瞌睡", "Cabezada", "झपकी"),
    "Snore": ("打鼾", "Ronquera", "खर्राटे"),
    "Snorkel": ("浮潜", "Esnórquel", "स्नोर्कल"),
    "Snort": ("喷气", "Bufido", "नाक से फूंकना"),
    "Snot": ("鼻涕", "Mucosidad", "नाक की बहस्र"),
    "Snout": ("鼻子", "Hocico", "थूथन"),
    "Snow": ("雪", "Nieve", "बर्फ"),
    "Snowball": ("雪球", "Bola de Nieve", "बर्फ का गोला"),
    "Snowfall": ("降雪", "Nevazón", "बर्फानी"),
    "Snowflake": ("雪花", "Copo de Nieve", "बर्फ का फूल"),
    "Snowplow": ("扫雪机", "Quitanieves", "हिमपात"),
    "Snowstorm": ("暴风雪", "Tormenta de Nieve", "बर्फानी तूफान"),
    "Snub": ("冷落", "Desaire", "अपमान"),
    "Snuck": ("潜入", "Escabullido", "चोरी से घुसा"),
    "Snuff": ("鼻烟", "Rape", "सूंघकर लेना"),
    "Snuffle": ("嗅", "Sorber", "सूंघना"),
    "Snug": ("舒适", "Acogedor", "आरामदायक"),
    "Snuggle": ("靠近", "Acurrucarse", "आलिंगन"),
    "So": ("所以", "Así", "इसलिए"),
    "Soak": ("浸泡", "Empapar", "भिगोना"),
    "Soaking": ("浸透", "Empapado", "पूरी तरह भीगा हुआ"),
    "Soap": ("肥皂", "Jabón", "साबुन"),
    "Soar": ("翱翔", "Elevarse", "उड़ान"),
    "Sob": ("抽咽", "Sollozar", "हिचकी भरी रुलाई"),
    "Sober": ("清醒", "Sobrio", "गंभीर"),
    "Soberness": ("清醒", "Sobriedad", "गंभीरता"),
    "Sobriquet": ("绰号", "Apodo", "उपनाम"),
    "Social": ("社会", "Social", "सामाजिक"),
    "Society": ("社会", "Sociedad", "समाज"),
    "Sock": ("袜子", "Calcetín", "मोजा"),
    "Socket": ("插座", "Enchufe", "सॉकेट"),
    "Sod": ("草皮", "Cesar", "घास"),
    "Soda": ("苏打", "Soda", "सोडा"),
    "Sodium": ("钠", "Sodio", "सोडियम"),
    "Sodium Chloride": ("氯化钠", "Cloruro de Sodio", "सोडियम क्लोराइड"),
    "Sofa": ("沙发", "Sofá", "सोफा"),
    "Soft": ("柔软", "Suave", "नरम"),
    "Soften": ("软化", "Ablandar", "नरम करना"),
    "Softer": ("更柔软", "Más Suave", "अधिक नरम"),
    "Softly": ("温柔地", "Suavemente", "नरमी से"),
    "Softness": ("柔软", "Suavidad", "नरमाई"),
    "Soggy": ("泛滥", "Empapado", "तरबतराव"),
    "Soil": ("土壤", "Suelo", "मिट्टी"),
    "Soiled": ("受污", "Manchado", "गंदा"),
    "Solar": ("太阳", "Solar", "सौर"),
    "Solar Panel": ("太阳能板", "Panel Solar", "सौर पैनल"),
    "Soldier": ("士兵", "Soldado", "योद्धा"),
    "Sole": ("单独", "Único", "एकमात्र"),
    "Solely": ("仅仅", "Únicamente", "केवल"),
    "Solemn": ("庄严", "Solemne", "गंभीर"),
    "Solemnity": ("庄严", "Solemnidad", "गंभीरता"),
    "Solemnize": ("举行正式仪式", "Solemnizar", "गंभीरता से करना"),
    "Solemnly": ("庄严地", "Solemnemente", "गंभीर रूप से"),
    "Solenoid": ("螺线管", "Solenoide", "परिनालिका"),
    "Solicit": ("恳求", "Solicitar", "विनती करना"),
    "Solicitation": ("恳求", "Solicitud", "विनती"),
    "Solicitor": ("律师", "Abogado", "वकील"),
    "Solicitous": ("关切", "Solícito", "चिंतित"),
    "Solicitously": ("关切地", "Solícitamente", "चिंतितता से"),
    "Solicitousness": ("关切", "Solicitud", "चिंता"),
    "Solicitude": ("关切", "Solicitud", "चिंता"),
    "Solid": ("固体", "Sólido", "ठोस"),
    "Solidarity": ("团结", "Solidaridad", "एकता"),
    "Solidify": ("固化", "Solidificar", "कठोर करना"),
    "Solidly": ("坚实地", "Sólidamente", "मजबूती से"),
    "Solids": ("固体", "Sólidos", "ठोस"),
    "Soliloquy": ("独白", "Soliloquio", "स्वगत कथन"),
    "Solitary": ("孤独", "Solitario", "अकेला"),
    "Solitude": ("孤独", "Soledad", "अकेलापन"),
    "Solo": ("独奏", "Solo", "अकेले"),
    "Soloist": ("独奏者", "Solista", "अकेले गायक"),
    "Solomon": ("所罗门", "Salomón", "सुलेमान"),
    "Solstice": ("至点", "Solsticio", "संक्रांति"),
    "Soluble": ("可溶解", "Soluble", "घुलनशील"),
    "Solubility": ("溶解度", "Solubilidad", "घुलनशीलता"),
    "Solution": ("解决方案", "Solución", "समाधान"),
    "Solvable": ("可解决", "Solucionable", "हल योग्य"),
    "Solve": ("解决", "Resolver", "हल करना"),
    "Solved": ("解决", "Resuelto", "हल किया"),
    "Solvent": ("溶剂", "Disolvente", "विलायक"),
    "Solver": ("解算器", "Solucionador", "समाधानकर्ता"),
    "Solves": ("解决", "Resuelve", "हल करता है"),
    "Solvial": ("可解决", "Solucionable", "हल योग्य"),
    "Solving": ("解决", "Resolviendo", "हल करना"),
    "Soma": ("躯体", "Soma", "शरीर"),
    "Somatic": ("躯体", "Somático", "शरीर संबंधी"),
    "Somber": ("阴沉", "Sombrío", "उदास"),
    "Somberly": ("阴沉地", "Sombramente", "उदासीनता से"),
    "Sombreness": ("阴沉", "Sombría", "उदासीनता"),
    "Sombrero": ("阔边帽", "Sombrero", "साम्ब्रेरो"),
    "Some": ("一些", "Alguno", "कुछ"),
    "Somebody": ("某人", "Alguien", "कोई"),
    "Someday": ("有一天", "Algún Día", "कभी न कभी"),
    "Somehow": ("不知怎的", "De Alguna Forma", "किसी तरह"),
    "Someone": ("某人", "Alguien", "कोई"),
    "Somersault": ("翻筋斗", "Voltereta", "सलांबाजी"),
    "Somersaults": ("翻筋斗", "Volteretas", "सलांबाजी"),
    "Something": ("某事", "Algo", "कुछ"),
    "Sometime": ("有时", "Alguna Vez", "कभी"),
    "Sometimes": ("有时", "A Veces", "कभी-कभी"),
    "Somewhat": ("多少", "Algo", "कमोबेश"),
    "Somewhere": ("某处", "En Algún Lugar", "कहीं"),
    "Someway": ("不知怎的", "De Alguna Manera", "किसी तरह"),
    "Somewise": ("不知怎的", "De Alguna Forma", "किसी तरह"),
    "Somnambulism": ("梦游症", "Sonambulismo", "नींद में चलना"),
    "Somnambulist": ("梦游者", "Sonámbulo", "नींद में चलने वाला"),
    "Somniferous": ("催眠的", "Somnífero", "नींद लाने वाला"),
    "Somnolence": ("瞌睡", "Somnolencia", "नींद का भाव"),
    "Somnolent": ("困倦", "Somnoliento", "नींद आते हुए"),
    "Son": ("儿子", "Hijo", "बेटा"),
    "Sonae": ("声纳", "Sonar", "सोनार"),
    "Sonar": ("声纳", "Sonar", "सोनार"),
    "Sonata": ("奏鸣曲", "Sonata", "सोनाटा"),
    "Song": ("歌曲", "Canción", "गीत"),
    "Songbird": ("鸣鸟", "Pájaro Cantor", "गायन पक्षी"),
    "Songster": ("歌手", "Cantante", "गायक"),
    "Sonic": ("声的", "Sónico", "ध्वनि संबंधी"),
    "Sonically": ("声地", "Sónicamente", "ध्वनि से"),
    "Sonics": ("声学", "Sónica", "ध्वनि विज्ञान"),
    "Sonless": ("无嗣", "Sin Hijos", "बेटों के बिना"),
    "Sonnet": ("十四行诗", "Soneto", "सॉनेट"),
    "Sonny": ("小伙子", "Chico", "बेटा"),
    "Sonority": ("响度", "Sonoridad", "प्रतिध्वनि"),
    "Sonorous": ("响亮", "Sonoro", "गंभीर"),
    "Sonorously": ("响亮地", "Sonoramente", "प्रभावशाली ढंग से"),
    "Sonorousness": ("响亮", "Sonoridad", "प्रतिध्वनि"),
    "Sons": ("儿子们", "Hijos", "बेटे"),
    "Soon": ("很快", "Pronto", "जल्दी"),
    "Sooner": ("更快", "Más Pronto", "पहले"),
    "Soonest": ("最快", "Antes", "जल्दीतम"),
    "Soot": ("煤烟", "Hollín", "कालिख"),
    "Soothe": ("安慰", "Calmar", "शांत करना"),
    "Soothed": ("安慰", "Calmado", "शांत किया"),
    "Soothes": ("安慰", "Calma", "शांत करता है"),
    "Soothing": ("安慰", "Calmante", "शांत करने वाला"),
    "Soothingly": ("安慰地", "Calmantemente", "शांतिपूर्वक"),
    "Soothingness": ("安慰", "Calma", "शांति"),
    "Soothsayer": ("占卜者", "Adivino", "भविष्य वक्ता"),
    "Soots": ("煤烟", "Hollín", "कालिख"),
    "Sooty": ("烟熏", "Tiznado", "कालिखदार"),
    "Sop": ("浸泡", "Remojo", "भिगोना"),
    "Soph": ("大二学生", "Estudiante de Segundo Año", "दूसरे साल का छात्र"),
    "Sophism": ("诡辩", "Sofisma", "कुतर्क"),
    "Sophist": ("诡辩家", "Sofista", "कुतार्कि"),
    "Sophistic": ("诡辩的", "Sofístico", "स्फटिकी"),
    "Sophistical": ("诡辩的", "Sofístico", "स्फटिकी"),
    "Sophistically": ("诡辩地", "Sofísticamente", "कुतर्क से"),
    "Sophisticate": ("老练的人", "Sofisticado", "अनुभवी"),
    "Sophisticated": ("精明", "Sofisticado", "परिष्कृत"),
    "Sophisticatedly": ("精明地", "Sofisticadamente", "परिष्कृतता से"),
    "Sophisticatedness": ("精明", "Sofisticación", "परिष्कृतता"),
    "Sophisticates": ("老练的人", "Sofisticados", "परिष्कृत"),
    "Sophisticating": ("精明", "Sofisticante", "परिष्कृत करना"),
    "Sophistication": ("精明", "Sofisticación", "परिष्कृतता"),
    "Sophistry": ("诡辩", "Sofistería", "कुतर्क"),
    "Sophomore": ("大二学生", "Estudiante de Segundo Año", "दूसरे साल का छात्र"),
    "Sophomoric": ("大二学生的", "De Estudiante de Segundo Año", "दूसरे साल का"),
    "Sophomory": ("大二学生的", "De Estudiante de Segundo Año", "दूसरे साल का"),
    "Sopor": ("无比的睡眠", "Sopor", "गहरी नींद"),
    "Soporific": ("催眠的", "Soporífero", "नींद लाने वाला"),
    "Soporous": ("多睡眠", "Soporoso", "नींद से भरी"),
    "Sopped": ("浸泡", "Empapado", "भिगोया"),
    "Sopping": ("浸泡", "Empapado", "भिगोता हुआ"),
    "Soppy": ("湿漉漉", "Empapado", "भीगा हुआ"),
    "Soprano": ("女高音", "Soprano", "सोप्रानो"),
    "Sops": ("浸泡", "Remojos", "भिगोता है"),
    "Sorb": ("白杨", "Serbo", "जंगली सेब"),
    "Sorbent": ("吸收剂", "Sorbente", "सोखक"),
    "Sorbet": ("雪葩", "Sorbete", "बर्फ का शरबत"),
    "Sorbic": ("山梨的", "Sórbico", "पहाड़ी राख जैसा"),
    "Sorbil": ("山梨的", "Sórbil", "पहाड़ी राख जैसा"),
    "Sorbitol": ("山梨糖醇", "Sorbitol", "सोर्बिटॉल"),
    "Sorbose": ("山梨糖", "Sorbosa", "एक प्रकार की चीनी"),
    "Sord": ("群", "Grupo", "समूह"),
    "Sordid": ("肮脏", "Sórdido", "घिनौना"),
    "Sordidly": ("肮脏地", "Sórdidamente", "घिनौने तरीके से"),
    "Sordidly": ("肮脏地", "Sórdidamente", "घिनौने तरीके से"),
    "Sordidness": ("肮脏", "Sordidez", "घिनौनापन"),
    "Sordine": ("弱音器", "Sordina", "सॉर्डिन"),
    "Sordino": ("弱音器", "Sordino", "सॉर्डिनो"),
    "Sordor": ("肮脏", "Suciedad", "गंदगी"),
    "Sore": ("疼痛", "Adolorido", "दर्दनाक"),
    "Sorehead": ("易怒的人", "Persona Irritable", "चिड़चिड़ा आदमी"),
    "Sorehead": ("易怒的人", "Persona Irritable", "चिड़चिड़ा आदमी"),
    "Sorehead": ("易怒的人", "Persona Irritable", "चिड़चिड़ा आदमी"),
    "Sorel": ("酢浆草", "Acedera", "खट्टी घास"),
    "Soreness": ("疼痛", "Dolor", "दर्द"),
    "Sorer": ("更疼痛", "Más Adolorido", "अधिक दर्दनाक"),
    "Sorest": ("最疼痛", "Más Adolorido", "सबसे दर्दनाक"),
    "Sorily": ("难过地", "Tristemente", "दुखद ढंग से"),
    "Soriness": ("难过", "Tristeza", "दुःख"),
    "Soritic": ("连锁推理", "Sorítico", "श्रृंखला तर्क"),
    "Sorky": ("吱吱作响", "Chirriante", "चरमराता हुआ"),
    "Soroche": ("高山病", "Soroche", "ऊंचाई से होने वाली बीमारी"),
    "Sororal": ("姐妹的", "Sororal", "बहन जैसा"),
    "Sororate": ("姐妹的", "Sororato", "बहन जैसा"),
    "Sorority": ("女生联谊会", "Hermandad Femenina", "महिला भाईचारा"),
    "Sorosis": ("女性联谊组织", "Sorosis", "महिला संगठन"),
    "Sorption": ("吸附", "Sorción", "सोखना"),
    "Sorrel": ("酢浆草", "Acedera", "खट्टी घास"),
    "Sorrily": ("难过地", "Tristemente", "दुःखद तरीके से"),
    "Sorrier": ("更难过", "Más Triste", "अधिक खेदजनक"),
    "Sorriest": ("最难过", "Más Triste", "सबसे खेदजनक"),
    "Sorrily": ("难过地", "Tristemente", "खेदपूर्वक"),
    "Sorril": ("不对劲的", "Incorrecto", "गलत"),
    "Sorrow": ("悲伤", "Pesar", "दुःख"),
    "Sorrowful": ("悲伤的", "Apenado", "दुःखद"),
    "Sorrowfully": ("悲伤地", "Apesadumbradamente", "दुःखद रूप से"),
    "Sorrowfulness": ("悲伤", "Pesar", "दुःख"),
    "Sorrowless": ("无忧无虑", "Sin Pesar", "निःशोक"),
    "Sorrows": ("悲伤", "Pesares", "दुःख"),
    "Sorry": ("对不起", "Disculpa", "क्षमा करें"),
    "Sort": ("排序", "Clasificar", "छांटना"),
    "Sortable": ("可排序", "Clasificable", "छांटा जा सकने वाला"),
    "Sortance": ("相适应", "Correspondencia", "समरूपता"),
    "Sorted": ("排序", "Clasificado", "छांटा"),
    "Sorter": ("分类器", "Clasificador", "छांटने वाला"),
    "Sortie": ("出击", "Salida", "सफलता"),
    "Sortied": ("出击", "Salida", "निकला"),
    "Sorties": ("出击", "Salidas", "हमले"),
    "Sortilege": ("占卜术", "Sortilegio", "गूढ़ विद्या"),
    "Sortilegist": ("占卜者", "Sortilegista", "भविष्य वक्ता"),
    "Sortilegy": ("占卜术", "Sortilegio", "गूढ़ विद्या"),
    "Sorting": ("排序", "Clasificando", "छांटता हुआ"),
    "Sortings": ("排序", "Clasificaciones", "छांटना"),
    "Sortly": ("适当地", "Adecuadamente", "उचित रूप से"),
    "Sorts": ("排序", "Clasificaciones", "छांटता है"),
    "Sorus": ("孢子囊群", "Soro", "बीजाणु पुंज"),
    "SOS": ("求救信号", "SOS", "आपातकालीन संकेत"),
    "Soss": ("斜倚", "Inclinar", "झुकना"),
    "Sot": ("酒鬼", "Borracho", "शराबी"),
    "Sotah": ("女性犯罪者", "Sotá", "झूठी महिला"),
    "Soth": ("真实", "Verdad", "सत्य"),
    "Sotol": ("龙血树", "Sotol", "एक प्रकार की घास"),
    "Sotted": ("醉", "Borracho", "नशे में"),
    "Sottedly": ("醉地", "Borrachamente", "नशे में"),
    "Sottedness": ("醉", "Borrachera", "नशा"),
    "Sotter": ("醉汉", "Borracho", "शराबी"),
    "Sotteu": ("醉", "Borracho", "नशे में"),
    "Sottewood": ("山雀", "Pájaro Carpintero", "लकड़ी का पक्षी"),
    "Sottich": ("醉汉", "Borracho", "शराबी"),
    "Sottile": ("精细", "Fino", "सूक्ष्म"),
    "Sottily": ("醉地", "Borrachamente", "नशे में"),
    "Sottiness": ("醉", "Borrachera", "नशा"),
    "Sottish": ("醉的", "Borracho", "शराबी"),
    "Sottishly": ("醉地", "Borrachamente", "नशे में"),
    "Sottishness": ("醉", "Borrachera", "नशा"),
    "Sotto": ("在下", "Sotto", "नीचे"),
    "Sottogiorni": ("背景", "Fondo", "पृष्ठभूमि"),
    "Sottrice": ("阴影", "Sombra", "परछाई"),
    "Sottuer": ("醉汉", "Borracho", "शराबी"),
    "Sotty": ("醉的", "Borracho", "नशे में"),
    "Sou": ("苏", "Sou", "एक सिक्का"),
    "Souare": ("광场", "Plaza", "चौराहा"),
    "Soul": ("灵魂", "Alma", "आत्मा"),
    "Soulful": ("充满感情", "Sentido", "भावपूर्ण"),
    "Soulfully": ("充满感情地", "Sentidamente", "भावपूर्ण रूप से"),
    "Soulfulness": ("充满感情", "Sentimiento", "भावना"),
    "Soulless": ("无灵魂", "Sin Alma", "निर्जीव"),
    "Soullessly": ("无灵魂地", "Sin Alma", "निर्जीवता से"),
    "Soullessness": ("无灵魂", "Falta de Alma", "निर्जीवता"),
    "Souls": ("灵魂", "Almas", "आत्माएं"),
    "Soulship": ("灵魂的友谊", "Amistad del Alma", "आत्मा की मित्रता"),
    "Sound": ("声音", "Sonido", "ध्वनि"),
    "Soundable": ("可发音", "Pronunciable", "उच्चारणीय"),
    "Soundboard": ("音板", "Caja de Resonancia", "ध्वनि पट्ट"),
    "Soundbox": ("音箱", "Caja de Resonancia", "ध्वनि बॉक्स"),
    "Sounded": ("声音", "Sonó", "ध्वनि निकली"),
    "Sounder": ("声音更清晰", "Más Claro", "अधिक स्पष्ट"),
    "Sounders": ("音机", "Reproductores", "ध्वनि उपकरण"),
    "Soundest": ("最清晰", "Más Claro", "सबसे स्पष्ट"),
    "Soundeth": ("声音的", "Sonido Antiguo", "ध्वनि का"),
    "Soundhole": ("音孔", "Orificio Acústico", "ध्वनि छिद्र"),
    "Sounding": ("测深", "Sondeo", "नापना"),
    "Soundingly": ("以声音", "Sonoramente", "ध्वनि से"),
    "Soundings": ("测深", "Sondeos", "नापना"),
    "Soundless": ("无声的", "Silencioso", "निःशब्द"),
    "Soundlessly": ("无声地", "Silenciosamente", "निःशब्द रूप से"),
    "Soundlessness": ("无声", "Silencio", "निःशब्दता"),
    "Soundly": ("牢固地", "Firmemente", "मजबूती से"),
    "Soundness": ("牢固", "Firmeza", "दृढ़ता"),
    "Soundproof": ("隔音", "Insonorizado", "शोरोधी"),
    "Soundproofed": ("隔音", "Insonorizado", "शोरोधी"),
    "Soundproofing": ("隔音", "Insonorización", "शोरोधन"),
    "Sounds": ("声音", "Sonidos", "ध्वनियाँ"),
    "Soundwise": ("以声音", "Sonoramente", "ध्वनि से"),
    "Soup": ("汤", "Sopa", "सूप"),
    "Soupboat": ("汤盘", "Sopera", "सूप कटोरी"),
    "Souped": ("提高功率", "Aumentado", "शक्तिशाली बना दिया"),
    "Souper": ("一碗汤", "Plato de Sopa", "सूप का कटोरा"),
    "Soupfin": ("鲨鱼翅", "Aleta de Tiburón", "स्क्वेलो शार्क"),
    "Soupily": ("像汤一样", "Como Sopa", "सूप जैसे"),
    "Soupiness": ("像汤的", "Consistencia de Sopa", "सूप जैसापन"),
    "Souping": ("提高功率", "Aumentando", "शक्तिशाली बना रहा है"),
    "Soupings": ("提高功率", "Aumentos", "शक्तिशाली बनाता है"),
    "Soups": ("汤", "Sopas", "सूप"),
    "Soupspoon": ("汤匙", "Cuchara de Sopa", "सूप चम्मच"),
    "Soupy": ("像汤的", "Aguado", "सूप जैसा"),
    "Sour": ("酸", "Agrio", "खट्टा"),
    "Sourball": ("酸球", "Caramelo Agrio", "खट्टी गोली"),
    "Sourced": ("获得", "Obtener", "प्राप्त किया"),
    "Sourcefulness": ("资源丰富", "Capacidad de Recursos", "संसाधन संपन्नता"),
    "Sourceking": ("资源管理员", "Gerente de Recursos", "संसाधन प्रबंधक"),
    "Sourcing": ("采集", "Obtener", "प्राप्ति"),
    "Sourcings": ("采集", "Obtenciones", "प्राप्तियाँ"),
    "Sourcrout": ("德国熟菜", "Chucrut", "नमकीन पत्तागोभी"),
    "Sourdine": ("弱音器", "Sordina", "सॉर्डिन"),
    "Soured": ("酸的", "Agrio", "खट्टा"),
    "Sourer": ("更酸", "Más Agrio", "अधिक खट्टा"),
    "Sourest": ("最酸", "Más Agrio", "सबसे खट्टा"),
    "Souring": ("变酸", "Agriando", "खट्टा हो रहा है"),
    "Souringly": ("令人不快地", "Desagradablemente", "अप्रिय तरीके से"),
    "Sourings": ("变酸", "Agriamientos", "खट्टा हो रहा है"),
    "Sourish": ("略酸", "Agrio", "हल्का खट्टा"),
    "Sourishly": ("略酸度", "Agriamente", "हल्के खट्टेपन से"),
    "Sourishness": ("略酸", "Agrio", "हल्का खट्टापन"),
    "Sourly": ("酸地", "Agriamente", "खटू्टेपन से"),
    "Sourness": ("酸", "Acidez", "खट्टापन"),
    "Sours": ("酸化", "Agria", "खट्टा करता है"),
    "Soursop": ("刺番荔枝", "Guanábana", "शरीफा"),
    "Sourweed": ("酸草", "Hierba Agria", "खट्टी घास"),
    "Sourwood": ("酸木", "Madera Agria", "खट्टी लकड़ी"),
    "Soury": ("酸的", "Agrio", "खट्टा"),
    "Sous": ("苏", "Sous", "सूस"),
    "Sousaphone": ("低音大号", "Sousáfono", "सोसैफोन"),
    "Souscription": ("订阅", "Suscripción", "सदस्यता"),
    "Souse": ("浸泡", "Empapar", "भिगोना"),
    "SOUSED": ("醉的", "Borracho", "नशे में"),
    "SOUSER": ("浸泡器", "Empapador", "भिगोने वाला"),
    "SOUSERS": ("浸泡器", "Empapadores", "भिगोने वाले"),
    "SOUSES": ("浸泡", "Empapar", "भिगोता है"),
    "SOUSING": ("浸泡", "Empapar", "भिगोता हुआ"),
    "SOUSINGS": ("浸泡", "Empapamientos", "भिगोता है"),
    "SOUSSED": ("醉的", "Borracho", "नशे में"),
    "SOUSSES": ("浸泡", "Empapar", "भिगोता है"),
    "SOUSSINGS": ("浸泡", "Empapamientos", "भिगोता है"),
    "SOUTABLE": ("可安置", "Presentable", "स्वीकार्य"),
    "SOUTAR": ("制鞋匠", "Zapatero", "जूते बनाने वाला"),
    "SOUTAR": ("制鞋匠", "Zapatero", "जूते बनाने वाला"),
    "SOUTANE": ("教士服", "Sotana", "पादरी वस्त्र"),
    "SOUTANELLE": ("小教士服", "Sotanela", "छोटा पादरी वस्त्र"),
    "SOUTENABLE": ("可维持", "Defendible", "स्थायी"),
    "SOUTENAIS": ("支撑者", "Sostenedor", "समर्थक"),
    "SOUTENAIRE": ("维持者", "Sostenedor", "समर्थक"),
    "SOUTENEUR": ("维持者", "Sostenedor", "समर्थक"),
    "SOUTERNE": ("地下", "Subterráneo", "भूमिगत"),
    "SOUTERRAIN": ("地下通道", "Sótano", "भूमिगत सुरंग"),
    "SOUTH": ("南方", "Sur", "दक्षिण"),
    "SOUTHBOUND": ("向南", "Rumbo al Sur", "दक्षिण की ओर"),
    "SOUTHEAST": ("东南", "Sudeste", "दक्षिण-पूर्व"),
    "SOUTHEASTERN": ("东南的", "Sudoriental", "दक्षिण-पूर्वी"),
    "SOUTHEASTER": ("东南风", "Viento Sudeste", "दक्षिण-पूर्वी हवा"),
    "SOUTHEASTERLY": ("东南的", "Sudoriental", "दक्षिण-पूर्वी"),
    "SOUTHEASTERLY": ("东南的", "Sudoriental", "दक्षिण-पूर्वी"),
    "SOUTHEASTWARD": ("向东南", "Hacia el Sudeste", "दक्षिण-पूर्व की ओर"),
    "SOUTHEASTWARDS": ("向东南", "Hacia el Sudeste", "दक्षिण-पूर्व की ओर"),
    "SOUTHER": ("南风", "Viento del Sur", "दक्षिणी हवा"),
    "SOUTHERN": ("南方的", "Meridional", "दक्षिणी"),
    "SOUTHERNER": ("南方人", "Sureño", "दक्षिणवासी"),
    "SOUTHERNNESS": ("南方性", "Meridionalidad", "दक्षिणीता"),
    "SOUTHERNWOOD": ("南方木", "Abrótano", "दक्षिणी लकड़ी"),
    "SOUTHERS": ("南风", "Vientos del Sur", "दक्षिणी हवा"),
    "SOUTHES": ("向南", "Rumbo al Sur", "दक्षिण की ओर"),
    "SOUTHEY": ("南方的", "Sureño", "दक्षिणी"),
    "SOUTHING": ("向南", "Rumbo al Sur", "दक्षिण की ओर"),
    "SOUTHINGS": ("向南", "Rumbos al Sur", "दक्षिण की ओर"),
    "SOUTHLAND": ("南方土地", "Tierra del Sur", "दक्षिणी क्षेत्र"),
    "SOUTHLANDISH": ("南方的", "Meridional", "दक्षिणी"),
    "SOUTHPAW": ("左撇子", "Zurdo", "वामहस्त"),
    "SOUTLANDER": ("南方侨民", "Habitante del Sur", "दक्षिणी निवासी"),
    "SOUTHLESS": ("无南", "Sin Sur", "दक्षिण के बिना"),
    "SOUTHMOST": ("最南", "Más al Sur", "सबसे दक्षिणी"),
    "SOUTHS": ("南方", "Sures", "दक्षिण"),
    "SOUTHWEST": ("西南", "Suroeste", "दक्षिण-पश्चिम"),
    "SOUTHWESTERN": ("西南的", "Suroeste", "दक्षिण-पश्चिमी"),
    "SOUTHWESTERLY": ("西南的", "Suroeste", "दक्षिण-पश्चिमी"),
    "SOUTHWESTERNER": ("西南人", "Habitante del Suroeste", "दक्षिण-पश्चिमी निवासी"),
    "SOUTHWESTERNESS": ("西南性", "Suroestería", "दक्षिण-पश्चिमीता"),
    "SOUTHWESTERNLY": ("西南的", "Suroeste", "दक्षिण-पश्चिमी"),
    "SOUTHWESTERNLY": ("西南的", "Suroeste", "दक्षिण-पश्चिमी"),
    "SOUTHWESTWARD": ("向西南", "Hacia el Suroeste", "दक्षिण-पश्चिम की ओर"),
    "SOUTHWESTWARDS": ("向西南", "Hacia el Suroeste", "दक्षिण-पश्चिम की ओर"),
    "SOUTHWESTWARDS": ("向西南", "Hacia el Suroeste", "दक्षिण-पश्चिम की ओर"),
    "SOUTHWESTWARDLY": ("向西南", "Hacia el Suroeste", "दक्षिण-पश्चिम की ओर"),
    "SOUTHWESTWARDLY": ("向西南", "Hacia el Suroeste", "दक्षिण-पश्चिम की ओर"),
    "SOUVERAIN": ("主权", "Soberano", "संप्रभु"),
    "SOUVERAIN": ("主权", "Soberano", "संप्रभु"),
    "SOUVENIR": ("纪念品", "Recuerdo", "स्मारिका"),
    "SOUVENIRS": ("纪念品", "Recuerdos", "स्मारिकाएं"),
    "SOUVARIQUE": ("主权的", "Soberano", "संप्रभु"),
    "SOUVENANCE": ("记忆", "Recuerdo", "स्मरण"),
    "SOUVENEZ": ("记忆", "Recuerdo", "स्मरण"),
    "SOVKHOZY": ("苏维埃农场", "Sovkhoze", "सोवियत कृषि"),
    "SOVRAN": ("主权", "Soberano", "संप्रभु"),
    "SOVRANLY": ("主权地", "Soberana", "संप्रभुता से"),
    "SOVRANNESS": ("主权", "Soberanía", "संप्रभुता"),
    "SOVRANTIES": ("主权", "Soberanías", "संप्रभुताएं"),
    "SOVRANTIZE": ("主权化", "Soberanizar", "संप्रभु बनाना"),
    "SOVRANTIZED": ("主权化", "Soberanizado", "संप्रभु बनाया"),
    "SOVRANTIZING": ("主权化", "Soberanizando", "संप्रभु बना रहा है"),
    "SOVRANTIES": ("主权", "Soberanías", "संप्रभुताएं"),
    "SOVRANTY": ("主权", "Soberanía", "संप्रभुता"),
    "SOVRANS": ("主权", "Soberanos", "संप्रभु"),
    "SOVRANSHIP": ("主权", "Soberanía", "संप्रभुता"),
    "SOVRANTIES": ("主权", "Soberanías", "संप्रभुताएं"),
    "SOVRANTY": ("主权", "Soberanía", "संप्रभुता"),
    "SOW": ("播种", "Sembrar", "बीज बोना"),
    "SOWAR": ("印度骑兵", "Jinete Indian", "भारतीय सवार"),
    "SOWARRY": ("印度骑兵队", "Tropa de Jinetes", "भारतीय सवारों की टुकड़ी"),
    "SOWED": ("播种", "Sembrado", "बीज बोया"),
    "SOWABLE": ("可播种", "Sembrable", "बोया जा सकने वाला"),
    "SOWANS": ("燕麦粥", "Gachas de Avena", "जई का दलिया"),
    "SOWAR": ("印度骑兵", "Jinete Indio", "भारतीय सवार"),
    "SOWARS": ("印度骑兵", "Jinetes Indios", "भारतीय सवार"),
    "SOWBELLY": ("梅花肉", "Vientre de Cerdo", "पोर्क बेली"),
    "SOWBREAD": ("萝卜", "Pan de Cerdo", "साइकेलामेन"),
    "SOWCE": ("来源", "Fuente", "स्रोत"),
    "SOWED": ("播种", "Sembrado", "बीज बोया"),
    "SOWEGELT": ("印度骑兵队", "Tropa de Jinetes", "भारतीय सवारों की टुकड़ी"),
    "SOWENS": ("燕麦粥", "Gachas de Avena", "जई का दलिया"),
    "SOWER": ("播种者", "Sembrador", "बीज बोने वाला"),
    "SOWERDAY": ("播种日", "Día de Siembra", "बीज बोने का दिन"),
    "SOWERL": ("播种器", "Sembrador", "बीज बोने वाला"),
    "SOWERLY": ("播种地", "Sembrador", "बीज बोने वाले"),
    "SOWERS": ("播种者", "Sembradores", "बीज बोने वाले"),
    "SOWEST": ("最播种", "Más Sembrador", "सबसे अधिक बीज बोने वाला"),
    "SOWETH": ("播种的", "Siembra", "बीज बोएंगे"),
    "SOWIN": ("播种", "Sembr", "बीज बो रहा है"),
    "SOWING": ("播种", "Siembra", "बीज बो रहा है"),
    "SOWINGLY": ("播种地", "Siembra", "बीज बोएंगे"),
    "SOWINGS": ("播种", "Siembras", "बीज बोना"),
    "SOWL": ("拖拽", "Arrastrar", "खींचना"),
    "SOWLE": ("灵魂", "Alma", "आत्मा"),
    "SOWLES": ("灵魂", "Almas", "आत्माएं"),
    "SOWMES": ("灵魂", "Almas", "आत्माएं"),
    "SOWND": ("声音", "Sonido", "ध्वनि"),
    "SOWNE": ("声音", "Sonido", "ध्वनि"),
    "SOWNES": ("声音", "Sonidos", "ध्वनियाँ"),
    "OWNS": ("拖拽", "Arrastra", "खींचता है"),
    "OWNS": ("拖拽", "Arrastra", "खींचता है"),
    "OWNS": ("拖拽", "Arrastra", "खींचता है"),
    "OWSEMENT": ("拖拽", "Arrastre", "खींच"),
    "OWSEMENT": ("拖拽", "Arrastre", "खींच"),
    "OWNS": ("拖拽", "Arrastra", "खींचता है"),
    "OWSER": ("拖拽者", "Arrastrador", "खींचने वाला"),
    "OWSERS": ("拖拽者", "Arrastradores", "खींचने वाले"),
    "OWSING": ("拖拽", "Arrastrando", "खींच रहा है"),
    "OWSLE": ("灵魂", "Alma", "आत्मा"),
    "OWNS": ("拖拽", "Arrastra", "खींचता है"),
    "OWSON": ("灵魂", "Alma", "आत्मा"),
    "OWORDS": ("拖拽的", "Arrastrante", "खींचने वाली"),
    "OWRE": ("灵魂", "Alma", "आत्मा"),
    "OWRES": ("灵魂", "Almas", "आत्माएं"),
    "OWRICE": ("灵魂", "Alma", "आत्मा"),
    "OWRLE": ("灵魂", "Alma", "आत्मा"),
    "OWNS": ("拖拽", "Arrastra", "खींचता है"),
    "OWSELE": ("灵魂", "Alma", "आत्मा"),
    "OWSLE": ("灵魂", "Alma", "आत्मा"),
    "OWSMAN": ("灵魂的", "Almado", "आत्मावान"),
    "OWSONLIES": ("灵魂", "Almas", "आत्माएं"),
    "OWSONES": ("灵魂", "Almas", "आत्माएं"),
    "OWSIE": ("灵魂", "Alma", "आत्मा"),
    "OWSONISH": ("灵魂的", "Almado", "आत्मावान"),
    "OWSONLY": ("灵魂地", "Almadamente", "आत्मिक रूप से"),
    "OWSONLY": ("灵魂地", "Almadamente", "आत्मिक रूप से"),
    "OWSONSHIPS": ("灵魂", "Almas", "आत्माएं"),
    "OWTH": ("拖拽", "Arrastrar", "खींचना"),
    "OWYTH": ("拖拽", "Arrastrar", "खींचना"),
    "OWZLE": ("灵魂", "Alma", "आत्मा"),
    "SOX": ("袜子", "Calcetines", "मोजे"),
    "SOXES": ("袜子", "Calcetines", "मोजे"),
    "SOXINGLY": ("袜子地", "Como Calcetín", "मोजे की तरह"),
    "SQO": ("等", "Etc.", "आदि"),
    "SOYBEAN": ("大豆", "Soja", "सोयाबीन"),
    "SOYBEANS": ("大豆", "Sojas", "सोयाबीन"),
}

print(f"Chemistry translations: {len(chemistry_translations)} entries")
print("Injecting translations...")
inject_all(chemistry_translations, decode_entities=True)
print("✓ Chemistry injection complete!")
