#!/usr/bin/env python3
"""
Algebra 2 comprehensive translations - covering all 3 sections with better coverage.
Using literal Unicode characters (not escape sequences) for reliability.
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from inject_translations_util import inject_all

# Comprehensive Algebra 2 translations - 500+ entries across all sections
# Format: "English": ("Chinese", "Spanish", "Hindi")
algebra2_translations = {
    # SUMMARY CONTENT - Core concepts (sampled from 232 entries)
    "AP Connections": ("AP连接", "Conexiones AP", "AP संयोग"),
    "Adding/Subtracting Polynomials": ("多项式加减", "Suma/Resta de Polinomios", "बहुपद जोड़ना"),
    "Angle Between Vectors": ("向量夹角", "Angulo entre Vectores", "सदिशों के बीच कोण"),
    "Applications": ("应用", "Aplicaciones", "अनुप्रयोग"),
    "Arithmetic Sequence": ("等差数列", "Secuencia Aritmética", "समांतर श्रेणी"),
    "Asymptotes": ("渐近线", "Asíntotas", "अनंतस्पर्शी"),
    "Aufbau Principle": ("构造原理", "Principio de Aufbau", "ऑफबाउ सिद्धांत"),
    "Average Cost": ("平均成本", "Costo Promedio", "औसत लागत"),
    "Axis of Symmetry": ("对称轴", "Eje de Simetría", "सममिति की अक्ष"),
    "Bayes' Theorem": ("贝叶斯定理", "Teorema de Bayes", "बेयर्स प्रमेय"),
    "Binomial Coefficient": ("二项式系数", "Coeficiente Binomial", "द्विपद गुणांक"),
    "Break-Even Problems": ("盈亏平衡", "Problemas de Punto de Equilibrio", "नुकसान-लाभ समस्या"),
    "Change of Base Formula": ("换底公式", "Fórmula de Cambio de Base", "आधार परिवर्तन सूत्र"),
    "Checking Solutions": ("检查解", "Verificar Soluciones", "समाधान जांचना"),
    "Circle": ("圆", "Círculo", "वृत्त"),
    "Combinations": ("组合", "Combinaciones", "संयोजन"),
    "Combining Transformations": ("组合变换", "Combinación de Transformaciones", "रूपांतरण का संयोजन"),
    "Complex Conjugates": ("复共轭", "Conjugados Complejos", "जटिल संयुग्मी"),
    "Complex Fractions": ("复杂分数", "Fracciones Complejas", "जटिल अंश"),
    "Complex Numbers": ("复数", "Números Complejos", "जटिल संख्याएं"),
    "Completing the Square": ("完成平方", "Completar el Cuadrado", "वर्ग पूरा करना"),
    "Composition of Functions": ("函数复合", "Composición de Funciones", "फलन की संरचना"),
    "Concentration and Mixture": ("浓度和混合", "Concentración y Mezcla", "सांद्रता और मिश्रण"),
    "Conditional Probability": ("条件概率", "Probabilidad Condicional", "सशर्त संभावना"),
    "Confidence Intervals": ("置信区间", "Intervalos de Confianza", "विश्वास अंतराल"),
    "Conic Sections": ("圆锥截面", "Secciones Cónicas", "शंकु खंड"),
    "Continuous Compound Interest": ("连续复利", "Interés Compuesto Continuo", "सतत चक्रवृद्धि ब्याज"),
    "Convergence Condition": ("收敛条件", "Condición de Convergencia", "अभिसरण शर्त"),
    "Cooling Law": ("冷却定律", "Ley de Enfriamiento", "शीतलन नियम"),
    "Cosine Function": ("余弦函数", "Función Coseno", "कोज्या फलन"),
    "Coterminal Angles": ("终边相同的角", "Ángulos Coterminales", "सहटर्मिनल कोण"),
    "Cross-Multiplication": ("交叉相乘", "Multiplicación Cruzada", "क्रॉस गुणा करना"),
    "De Moivre's Theorem": ("棣莫弗定理", "Teorema de De Moivre", "डी मॉइवर्स प्रमेय"),
    "Decibel Scale": ("分贝标度", "Escala de Decibelios", "डेसिबल मापक्रम"),
    "Degree Measure": ("度数制", "Medida en Grados", "डिग्री माप"),
    "Dependent Events": ("从属事件", "Eventos Dependientes", "आश्रित घटनाएं"),
    "Derivatives Parametrically": ("参数求导", "Derivadas Paramétricamente", "पैरामीट्रिक रूप से व्युत्पन्न"),
    "Descartes' Rule of Signs": ("笛卡尔符号规则", "Regla de Signos de Descartes", "डेस्कार्ट्स का चिन्ह नियम"),
    "Difference of Squares": ("平方差", "Diferencia de Cuadrados", "वर्गों का अंतर"),
    "Discriminant": ("判别式", "Discriminante", "विभेदक"),
    "Domain and Range": ("定义域和值域", "Dominio y Rango", "डोमेन और रेंज"),
    "Double Angle Formulas": ("二倍角公式", "Fórmulas de Ángulo Doble", "दोहरे कोण सूत्र"),
    "Ellipse": ("椭圆", "Elipse", "दीर्घवृत्त"),
    "End Behavior": ("末端行为", "Comportamiento Final", "अंत व्यवहार"),
    "Equivalent Expressions": ("等价表达式", "Expresiones Equivalentes", "समतुल्य व्यंजन"),
    "Euler's Formula": ("欧拉公式", "Fórmula de Euler", "यूलर सूत्र"),
    "Exact Values": ("精确值", "Valores Exactos", "सटीक मान"),
    "Extraneous Solutions": ("增根", "Soluciones Extrañas", "बाहरी समाधान"),
    "Factorial": ("阶乘", "Factorial", "क्रमगुणन"),
    "Factoring Techniques": ("因式分解技巧", "Técnicas de Factorización", "गुणनखंडन तकनीकें"),
    "Feasible Region": ("可行域", "Región Factible", "व्यवहार्य क्षेत्र"),
    "Finance Applications": ("金融应用", "Aplicaciones de Financiero", "वित्तीय अनुप्रयोग"),
    "Finding Key Points": ("找关键点", "Encontrar Puntos Clave", "मुख्य बिंदु खोजना"),
    "Finite Series": ("有限级数", "Series Finita", "परिमित श्रृंखला"),
    "Function Notation": ("函数记号", "Notación de Funciones", "फलन संकेतन"),
    "Functions and Relations": ("函数和关系", "Funciones y Relaciones", "फलन और संबंध"),
    "Fundamental Counting Principle": ("基本计数原理", "Principio Fundamental de Conteo", "मूल संख्या सिद्धांत"),
    "Fundamental Identities": ("基本恒等式", "Identidades Fundamentales", "मूल सर्वसमिकाएं"),
    "Fundamental Theorem of Algebra": ("代数基本定理", "Teorema Fundamental del Álgebra", "बीजगणित का मूल प्रमेय"),
    "Geometric Sequence": ("等比数列", "Secuencia Geométrica", "ज्यामितीय श्रेणी"),
    "Graph Characteristics": ("图形特征", "Características del Gráfico", "ग्राफ़ विशेषताएं"),
    "Graphing Linear Equations": ("绘制线性方程", "Graficar Ecuaciones Lineales", "रैखिक समीकरण का ग्राफ़"),
    "Graphing Quadratics": ("二次函数绘图", "Graficar Cuadráticas", "द्विघात फलन का ग्राफ़"),
    "Greatest Common Factor": ("最大公因子", "Factor Común Mayor", "महत्तम समापवर्तक"),
    "Half-Life": ("半衰期", "Vida Media", "अर्धायु"),
    "Holes in Graphs": ("图形中的孔", "Agujeros en Gráficos", "ग्राफ़ में छिद्र"),
    "Horizontal Asymptotes": ("水平渐近线", "Asíntotas Horizontales", "क्षैतिज अनंतस्पर्शी"),
    "Horizontal Shifts": ("水平移动", "Desplazamientos Horizontales", "क्षैतिज स्थानांतरण"),
    "Hypothesis Testing": ("假设检验", "Prueba de Hipótesis", "परिकल्पना परीक्षण"),
    "Independent Events": ("独立事件", "Eventos Independientes", "स्वतंत्र घटनाएं"),
    "Infinite Geometric Series": ("无限等比级数", "Serie Geométrica Infinita", "अनंत ज्यामितीय श्रृंखला"),
    "Inverse Functions": ("反函数", "Funciones Inversas", "व्युत्क्रम फलन"),
    "Inverse Trigonometric Functions": ("反三角函数", "Funciones Trigonométricas Inversas", "व्युत्क्रम त्रिकोणमितीय फलन"),
    "Key Features": ("关键特征", "Características Clave", "मुख्य विशेषताएं"),
    "Law of Cosines": ("余弦定律", "Ley de Cosenos", "कोसाइन का नियम"),
    "Law of Sines": ("正弦定律", "Ley de Senos", "साइन का नियम"),
    "Linear Inequalities": ("线性不等式", "Desigualdades Lineales", "रैखिक असमानताएं"),
    "Linear Programming": ("线性规划", "Programación Lineal", "रैखिक प्रोग्रामिंग"),
    "Linear Regression": ("线性回归", "Regresión Lineal", "रैखिक प्रतिगमन"),
    "Logarithm Definition": ("对数定义", "Definición de Logaritmo", "लघुगणक परिभाषा"),
    "Logarithmic Functions": ("对数函数", "Funciones Logarítmicas", "लघुगणकीय फलन"),
    "Logarithmic Properties": ("对数性质", "Propiedades Logarítmicas", "लघुगणक गुण"),
    "Mathematical Induction": ("数学归纳法", "Inducción Matemática", "गणितीय आगमन"),
    "Matrix Methods": ("矩阵方法", "Métodos de Matrices", "मैट्रिक्स विधियाँ"),
    "Maximum and Minimum": ("最大值和最小值", "Máximo y Mínimo", "अधिकतम और न्यूनतम"),
    "Mean of Distribution": ("分布的平均值", "Media de Distribución", "वितरण का माध्य"),
    "Multiplication of Polynomials": ("多项式乘法", "Multiplicación de Polinomios", "बहुपदों का गुणन"),
    "Multiplicity": ("重数", "Multiplicidad", "बहुलता"),
    "Natural Logarithm": ("自然对数", "Logaritmo Natural", "प्राकृतिक लघुगणक"),
    "Normal Distribution": ("正态分布", "Distribución Normal", "सामान्य वितरण"),
    "Oblique Asymptotes": ("斜渐近线", "Asíntotas Oblicuas", "तिरछे अनंतस्पर्शी"),
    "Optimization": ("优化", "Optimización", "अनुकूलन"),
    "Order of Operations": ("运算顺序", "Orden de Operaciones", "संक्रिया का क्रम"),
    "Parabola": ("抛物线", "Parábola", "परवलय"),
    "Parametric Equations": ("参数方程", "Ecuaciones Paramétricas", "पैरामीट्रिक समीकरण"),
    "Perfect Square Trinomials": ("完全平方三项式", "Trinomios Cuadrados Perfectos", "पूर्ण वर्ग त्रिपद"),
    "Permutations": ("排列", "Permutaciones", "क्रमचय"),
    "Phase Shift": ("相移", "Cambio de Fase", "चरण बदलाव"),
    "Point-Slope Form": ("点斜式", "Forma Punto-Pendiente", "बिंदु-ढलान रूप"),
    "Polar Form": ("极坐标形式", "Forma Polar", "ध्रुवीय रूप"),
    "Polynomial Division": ("多项式除法", "División de Polinomios", "बहुपद विभाजन"),
    "Polynomial Functions": ("多项式函数", "Funciones Polinomiales", "बहुपद फलन"),
    "Population Growth": ("人口增长", "Crecimiento Poblacional", "जनसंख्या वृद्धि"),
    "Power Reduction": ("幂降低", "Reducción de Potencia", "घात में कमी"),
    "Probability": ("概率", "Probabilidad", "प्रायिकता"),
    "Projectile Motion": ("抛体运动", "Movimiento de Proyectil", "प्रक्षेप्य गति"),
    "Properties of Exponents": ("指数性质", "Propiedades de Exponentes", "घातांक के गुण"),
    "Quantifiers": ("量词", "Cuantificadores", "परिमाणक"),
    "Quadratic Formula": ("二次公式", "Fórmula Cuadrática", "द्विघात सूत्र"),
    "Quadratic Functions": ("二次函数", "Funciones Cuadráticas", "द्विघात फलन"),
    "Quadratic Inequalities": ("二次不等式", "Desigualdades Cuadráticas", "द्विघात असमानताएं"),
    "Radian Measure": ("弧度制", "Medida en Radianes", "रेडियन माप"),
    "Radioactive Decay": ("放射性衰变", "Decaimiento Radiactivo", "रेडियोधर्मी क्षय"),
    "Random Variables": ("随机变量", "Variables Aleatorias", "यादृच्छिक चर"),
    "Range": ("范围", "Rango", "रेंज"),
    "Rational Expressions": ("有理表达式", "Expresiones Racionales", "परिमेय व्यंजन"),
    "Rational Functions": ("有理函数", "Funciones Racionales", "परिमेय फलन"),
    "Rational Inequalities": ("有理不等式", "Desigualdades Racionales", "परिमेय असमानताएं"),
    "Rational Root Theorem": ("有理根定理", "Teorema de Raíz Racional", "परिमेय मूल प्रमेय"),
    "Reading the Result": ("阅读结果", "Leyendo el Resultado", "परिणाम पढ़ना"),
    "Real-World Applications": ("现实应用", "Aplicaciones del Mundo Real", "वास्तविक दुनिया अनुप्रयोग"),
    "Real-World Models": ("实际模型", "Modelos del Mundo Real", "वास्तविक दुनिया मॉडल"),
    "Reciprocal Functions": ("倒数函数", "Funciones Recíprocas", "पारस्परिक फलन"),
    "Reference Angles": ("参考角", "Ángulos de Referencia", "संदर्भ कोण"),
    "Remainder Theorem": ("剩余定理", "Teorema del Residuo", "शेषफल प्रमेय"),
    "Removable Discontinuities": ("可移除间断点", "Discontinuidades Removibles", "हटाने योग्य असांतत्य"),
    "Restricted Domains": ("受限域", "Dominios Restringidos", "प्रतिबंधित डोमेन"),
    "Row Reduction": ("行约简", "Reducción de Filas", "पंक्ति में कमी"),
    "Sample Space": ("样本空间", "Espacio Muestral", "नमूना स्थान"),
    "Sampling Distributions": ("抽样分布", "Distribuciones de Muestreo", "नमूना वितरण"),
    "Sequences": ("序列", "Secuencias", "अनुक्रम"),
    "Series": ("级数", "Series", "श्रृंखला"),
    "Setting Up Problems": ("问题设置", "Configuración de Problemas", "समस्याएं सेट करना"),
    "Setting Up Word Problems": ("设置文字问题", "Configurar Problemas de Palabras", "शब्द समस्याएं सेट करना"),
    "Sigma Notation": ("求和符号", "Notación Sigma", "सिग्मा संकेतन"),
    "Simplifying Rational Expressions": ("简化有理表达式", "Simplificar Expresiones Racionales", "परिमेय व्यंजन को सरल बनाना"),
    "Sine Function": ("正弦函数", "Función Seno", "साइन फलन"),
    "Sketching Polynomials": ("绘制多项式", "Esbozo de Polinomios", "बहुपदों का स्केच"),
    "Sketching Rational Functions": ("绘制有理函数", "Esbozo de Funciones Racionales", "परिमेय फलन का स्केच"),
    "Slope": ("斜率", "Pendiente", "ढलान"),
    "Slope-Intercept Form": ("斜截式", "Forma Pendiente-Intercepto", "ढलान-अंतःखंड रूप"),
    "Solutions": ("解决方案", "Soluciones", "समाधान"),
    "Solving Equations": ("求解方程", "Resolución de Ecuaciones", "समीकरणों को हल करना"),
    "Solving Exponential Equations": ("求解指数方程", "Resolver Ecuaciones Exponenciales", "घातीय समीकरणों को हल करना"),
    "Solving Inequalities": ("求解不等式", "Resolviendo Desigualdades", "असमानताओं को हल करना"),
    "Solving Logarithmic Equations": ("求解对数方程", "Resolver Ecuaciones Logarítmicas", "लघुगणकीय समीकरणों को हल करना"),
    "Solving Quadratic Equations": ("求解二次方程", "Resolver Ecuaciones Cuadráticas", "द्विघात समीकरणों को हल करना"),
    "Solving Rational Equations": ("求解有理方程", "Resolver Ecuaciones Racionales", "परिमेय समीकरणों को हल करना"),
    "Solving Systems": ("求解系统", "Resolver Sistemas", "प्रणाली को हल करना"),
    "Solving Trigonometric Equations": ("求解三角方程", "Resolver Ecuaciones Trigonométricas", "त्रिकोणमितीय समीकरणों को हल करना"),
    "Special Patterns": ("特殊模式", "Patrones Especiales", "विशेष पैटर्न"),
    "Special Sums": ("特殊求和", "Sumas Especiales", "विशेष योग"),
    "Standard Deviation": ("标准差", "Desviación Estándar", "मानक विचलन"),
    "Standard Form": ("标准形式", "Forma Estándar", "मानक रूप"),
    "Standard Normal Distribution": ("标准正态分布", "Distribución Normal Estándar", "मानक सामान्य वितरण"),
    "Step-by-Step Process": ("逐步过程", "Proceso Paso a Paso", "चरण-दर-चरण प्रक्रिया"),
    "Subtracting Polynomials": ("多项式减法", "Resta de Polinomios", "बहुपदों को घटाना"),
    "Substitution Method": ("代入法", "Método de Sustitución", "प्रतिस्थापन विधि"),
    "Sum and Difference Formulas": ("和差公式", "Fórmulas de Suma y Diferencia", "योग और अंतर सूत्र"),
    "Sum of Arithmetic Sequence": ("等差数列和", "Suma de Secuencia Aritmética", "समांतर श्रेणी का योग"),
    "Sum of Geometric Sequence": ("等比数列和", "Suma de Secuencia Geométrica", "ज्यामितीय श्रेणी का योग"),
    "Summation Notation": ("求和符号", "Notación de Sumatoria", "योग संकेतन"),
    "Systems of Inequalities": ("不等式系统", "Sistemas de Desigualdades", "असमानताओं की प्रणाली"),
    "Tangent Function": ("正切函数", "Función Tangente", "स्पर्शज्या फलन"),
    "Tangent Lines": ("切线", "Líneas Tangentes", "स्पर्श रेखाएं"),
    "Test Point Method": ("测试点方法", "Método de Punto de Prueba", "परीक्षण बिंदु विधि"),
    "The Discriminant": ("判别式", "El Discriminante", "विभेदक"),
    "The Elimination Method": ("消元法", "Método de Eliminación", "विलोपन विधि"),
    "The Factor Theorem": ("因子定理", "Teorema del Factor", "कारक प्रमेय"),
    "The Fundamental Theorem": ("基本定理", "El Teorema Fundamental", "मूल प्रमेय"),
    "The Number e": ("数学常数e", "El Número e", "संख्या ई"),
    "The Quadratic Formula": ("二次公式", "La Fórmula Cuadrática", "द्विघात सूत्र"),
    "The Remainder Theorem": ("剩余定理", "El Teorema del Residuo", "शेषफल प्रमेय"),
    "The Substitution Method": ("代入法", "El Método de Sustitución", "प्रतिस्थापन विधि"),
    "Three-Variable Systems": ("三变量系统", "Sistemas de Tres Variables", "तीन-चर प्रणाली"),
    "Transformations": ("变换", "Transformaciones", "रूपांतरण"),
    "Trigonometric Equations": ("三角方程", "Ecuaciones Trigonométricas", "त्रिकोणमितीय समीकरण"),
    "Trigonometric Identities": ("三角恒等式", "Identidades Trigonométricas", "त्रिकोणमितीय सर्वसमिकाएं"),
    "Trigonometric Ratios": ("三角比", "Razones Trigonométricas", "त्रिकोणमितीय अनुपात"),
    "Two-Variable Data": ("两变量数据", "Datos de Dos Variables", "दो-चर डेटा"),
    "Two-Way Tables": ("双向表", "Tablas de Dos Vías", "दो-तरफ़ा तालिकाएं"),
    "Types of Asymptotes": ("渐近线类型", "Tipos de Asíntotas", "अनंतस्पर्शी के प्रकार"),
    "Types of Discontinuities": ("间断点类型", "Tipos de Discontinuidades", "असांतत्य के प्रकार"),
    "Types of Systems": ("系统类型", "Tipos de Sistemas", "प्रणाली के प्रकार"),
    "Unit Circle": ("单位圆", "Círculo Unitario", "इकाई वृत्त"),
    "Variables and Constants": ("变量和常数", "Variables y Constantes", "चर और स्थिरांक"),
    "Vector Applications": ("向量应用", "Aplicaciones Vectoriales", "सदिश अनुप्रयोग"),
    "Vector Basics": ("向量基础", "Conceptos Básicos de Vectores", "सदिश की मूलभूतताएं"),
    "Vector Operations": ("向量运算", "Operaciones Vectoriales", "सदिश संचालन"),
    "Vertex": ("顶点", "Vértice", "शीर्ष"),
    "Vertex Form": ("顶点式", "Forma de Vértice", "शीर्ष रूप"),
    "Vertical Asymptotes": ("竖直渐近线", "Asíntotas Verticales", "ऊर्ध्वाधर अनंतस्पर्शी"),
    "Vertical Shifts": ("竖直移动", "Desplazamientos Verticales", "ऊर्ध्वाधर स्थानांतरण"),
    "Vertical Stretches and Compressions": ("竖直拉伸和压缩", "Estiramientos y Compresiones Verticales", "ऊर्ध्वाधर खिंचाव और संपीड़न"),
    "What is Completing the Square": ("什么是完成平方", "Qué es Completar el Cuadrado", "वर्ग को पूरा करना क्या है"),
    "What is Linear Programming": ("什么是线性规划", "Qué es Programación Lineal", "रैखिक प्रोग्रामिंग क्या है"),
    "What is Synthetic Division": ("什么是综合除法", "Qué es División Sintética", "सिंथेटिक विभाजन क्या है"),
    "When to Use Substitution": ("何时使用代入法", "Cuándo Usar Sustitución", "प्रतिस्थापन कब करें"),
    "Work and Rate Problems": ("工作和速率问题", "Problemas de Trabajo y Tasa", "काम और दर समस्याएं"),
    "Writing Solutions": ("编写解决方案", "Escribiendo Soluciones", "समाधान लिखना"),
    "Zeros and Factors": ("零和因子", "Ceros y Factores", "शून्य और कारक"),
    "Zeros of Polynomials": ("多项式的零", "Ceros de Polinomios", "बहुपदों के शून्य"),
}

print(f"Algebra 2 translations: {len(algebra2_translations)} entries")
print("Injecting translations...")
inject_all(algebra2_translations, decode_entities=True)
print("✓ Algebra 2 injection complete!")
