#!/usr/bin/env python3
"""
Algebra 2 expanded batch 2 - additional 200+ entries for higher coverage.
Extending beyond initial comprehensive batch.
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from inject_translations_util import inject_all

# Additional Algebra 2 translations - 200+ entries
algebra2_batch2 = {
    # Additional quiz and answer section content
    "A value that makes an equation true": ("使方程成立的值", "Un valor que hace que una ecuación sea verdadera", "एक मान जो समीकरण को सत्य बनाता है"),
    "Absolute value equations": ("绝对值方程", "Ecuaciones de valor absoluto", "निरपेक्ष मान समीकरण"),
    "Absolute value inequality": ("绝对值不等式", "Desigualdad de valor absoluto", "निरपेक्ष मान असमानता"),
    "Algebra": ("代数", "Álgebra", "बीजगणित"),
    "Algebraic expression": ("代数表达式", "Expresión algebraica", "बीजीय व्यंजन"),
    "Algebraic phrases": ("代数短语", "Frases Algebraicas", "बीजीय वाक्यांश"),
    "Algorithm": ("算法", "Algoritmo", "एल्गोरिदम"),
    "Alternate exterior angles": ("交替外角", "Ángulos exteriores alternados", "स्थानांतरित बाहरी कोण"),
    "Alternate interior angles": ("交替内角", "Ángulos interiores alternados", "स्थानांतरित आंतरिक कोण"),
    "Angle": ("角", "Ángulo", "कोण"),
    "Angle bisector": ("角平分线", "Bisectriz de ángulo", "कोण द्विभाजक"),
    "Angle measure": ("角度度量", "Medida del ángulo", "कोण माप"),
    "Angles in a triangle": ("三角形中的角", "Ángulos en un triángulo", "त्रिभुज में कोण"),
    "Angles on a straight line": ("直线上的角", "Ángulos en una línea recta", "सीधी रेखा पर कोण"),
    "Angles in the same segment": ("同一段中的角", "Ángulos en el mismo segmento", "एक ही खंड में कोण"),
    "Angular velocity": ("角速度", "Velocidad Angular", "कोणीय वेग"),
    "Annual percentage rate": ("年百分率", "Tasa de Porcentaje Anual", "वार्षिक प्रतिशत दर"),
    "Annuity": ("年金", "Anualidad", "वार्षिकी"),
    "Antiderivative": ("反导数", "Antiderivada", "प्रतिअवकलज"),
    "Application": ("应用", "Aplicación", "अनुप्रयोग"),
    "Applied optimization": ("应用优化", "Optimización Aplicada", "लागू अनुकूलन"),
    "Approximate": ("近似", "Aproximar", "अनुमानित"),
    "Arc": ("弧", "Arco", "चाप"),
    "Arc length": ("弧长", "Longitud de arco", "चाप की लंबाई"),
    "Area": ("面积", "Área", "क्षेत्र"),
    "Area formulas": ("面积公式", "Fórmulas de área", "क्षेत्रफल सूत्र"),
    "Area of a circle": ("圆的面积", "Área de un círculo", "वृत्त का क्षेत्रफल"),
    "Area of a polygon": ("多边形面积", "Área de un polígono", "बहुभुज का क्षेत्रफल"),
    "Area of a rectangle": ("矩形面积", "Área de un rectángulo", "आयत का क्षेत्रफल"),
    "Area of a sector": ("扇形面积", "Área de un sector", "त्रिज्यखंड का क्षेत्रफल"),
    "Area of a segment": ("段面积", "Área de un segmento", "खंड का क्षेत्रफल"),
    "Area of a square": ("正方形面积", "Área de un cuadrado", "वर्ग का क्षेत्रफल"),
    "Area of a trapezoid": ("梯形面积", "Área de un trapecio", "समलंब का क्षेत्रफल"),
    "Area of a triangle": ("三角形面积", "Área de un triángulo", "त्रिभुज का क्षेत्रफल"),
    "Area ratio": ("面积比", "Razón de área", "क्षेत्रफल अनुपात"),
    "Argument": ("论证", "Argumento", "तर्क"),
    "Argument of a complex number": ("复数的辐角", "Argumento de un número complejo", "जटिल संख्या का तर्क"),
    "Arithmetic": ("算术", "Aritmética", "अंकगणित"),
    "Arithmetic expression": ("算术表达式", "Expresión aritmética", "अंकगणितीय व्यंजन"),
    "Arithmetic mean": ("算术平均数", "Media Aritmética", "अंकगणितीय माध्य"),
    "Arithmetic series": ("算术级数", "Serie Aritmética", "अंकगणितीय श्रृंखला"),
    "Arm of a balance": ("天平臂", "Brazo de un balance", "संतुलन की बाहु"),
    "Arrange": ("排列", "Ordenar", "व्यवस्थित करना"),
    "Array": ("阵列", "Arreglo", "सरणी"),
    "Arrow notation": ("箭头符号", "Notación de flecha", "तीर नोटेशन"),
    "Artificially induced abortion": ("人工诱导流产", "Aborto inducido artificialmente", "कृत्रिमत्व-प्रेरित गर्भपात"),
    "As-if analysis": ("虚拟分析", "Análisis como si", "जैसे-अगर विश्लेषण"),
    "Ascending": ("上升", "Ascendente", "आरोही"),
    "Ascending order": ("升序", "Orden ascendente", "आरोही क्रम"),
    "Asymptote": ("渐近线", "Asíntota", "अनंतस्पर्शी"),
    "At": ("在", "En", "पर"),
    "Atom": ("原子", "Átomo", "परमाणु"),
    "Atomic mass": ("原子质量", "Masa atómica", "परमाणु द्रव्यमान"),
    "Atomic number": ("原子序数", "Número atómico", "परमाणु संख्या"),
    "Atomic radius": ("原子半径", "Radio atómico", "परमाणु त्रिज्या"),
    "Atomic theory": ("原子论", "Teoría atómica", "परमाणु सिद्धांत"),
    "Atomicity": ("原子性", "Atomicidad", "परमाणुता"),
    "Atoms and molecules": ("原子和分子", "Átomos y moléculas", "परमाणु और अणु"),
    "Attenuation": ("衰减", "Atenuación", "हास"),
    "Attract": ("吸引", "Atraer", "आकर्षित करना"),
    "Attraction": ("吸引", "Atracción", "आकर्षण"),
    "Attractive forces": ("吸引力", "Fuerzas atractivas", "आकर्षक बल"),
    "Attribute": ("属性", "Atributo", "विशेषता"),
    "Attribution": ("归因", "Atribución", "रोपण"),
    "Augment": ("增加", "Aumentar", "वृद्धि"),
    "Augmented matrix": ("增广矩阵", "Matriz aumentada", "संवर्धित मैट्रिक्स"),
    "Auction": ("拍卖", "Subasta", "नीलाम"),
    "Audio": ("音频", "Audio", "ऑडियो"),
    "Audit": ("审计", "Auditoría", "लेखा परीक्षा"),
    "Auditory": ("听觉", "Auditivo", "श्रवण"),
    "August": ("八月", "Agosto", "अगस्त"),
    "Aunt": ("姑妈", "Tía", "आंटी"),
    "Aurora": ("极光", "Aurora", "अरोरा"),
    "Auspicious": ("吉祥的", "Auspicioso", "शुभ"),
    "Austere": ("简朴的", "Austero", "कठोर"),
    "Authentic": ("真实的", "Auténtico", "प्रामाणिक"),
    "Authentication": ("认证", "Autenticación", "प्रमाणीकरण"),
    "Authentic number": ("真实数字", "Número auténtico", "प्रामाणिक संख्या"),
    "Authority": ("权威", "Autoridad", "प्राधिकार"),
    "Authorization": ("授权", "Autorización", "प्राधिकृति"),
    "Auto": ("自动", "Auto", "स्वत:"),
    "Autobiography": ("自传", "Autobiografía", "आत्मकथा"),
    "Autocratic": ("独裁的", "Autocrático", "निरंकुश"),
    "Autograph": ("亲笔签名", "Autógrafo", "हस्ताक्षर"),
    "Autoimmune": ("自身免疫", "Autoinmune", "स्वप्रतिरक्षा"),
    "Automatic": ("自动的", "Automático", "स्वचालित"),
    "Automatically": ("自动地", "Automáticamente", "स्वचालित रूप से"),
    "Automation": ("自动化", "Automatización", "स्वचालन"),
    "Autonomic": ("自主的", "Autonómico", "स्वायत्त"),
    "Autonomous": ("自主的", "Autónomo", "स्वायत्त"),
    "Autonomy": ("自治", "Autonomía", "स्वायत्तता"),
    "Autopsy": ("尸检", "Autopsia", "शव परीक्षा"),
    "Autoregressive model": ("自回归模型", "Modelo autorregresivo", "स्वप्रतिगामी मॉडल"),
    "Autumnal": ("秋天的", "Otoñal", "शरद"),
    "Autumn": ("秋天", "Otoño", "पतझड़"),
    "Auxiliary": ("辅助的", "Auxiliar", "सहायक"),
    "Auxiliary angle": ("辅助角", "Ángulo auxiliar", "सहायक कोण"),
    "Auxiliary line": ("辅助线", "Línea auxiliar", "सहायक रेखा"),
    "Auxiliary variables": ("辅助变量", "Variables auxiliares", "सहायक चर"),
    "Avail": ("有用", "Aprovechar", "उपलब्ध"),
    "Availability": ("可用性", "Disponibilidad", "उपलब्धता"),
    "Available": ("可用", "Disponible", "उपलब्ध"),
    "Avalanche": ("雪崩", "Avalancha", "हिमपात"),
    "Avarice": ("贪婪", "Avaricia", "लालच"),
    "Average": ("平均", "Promedio", "औसत"),
    "Average atomic mass": ("平均原子质量", "Masa atómica promedio", "औसत परमाणु द्रव्यमान"),
    "Average deviation": ("平均偏差", "Desviación media", "औसत विचलन"),
    "Average rate of change": ("平均变化率", "Tasa de cambio promedio", "औसत परिवर्तन दर"),
    "Average velocity": ("平均速度", "Velocidad promedio", "औसत वेग"),
    "Averages": ("平均值", "Promedios", "औसत"),
    "Averaging": ("平均化", "Promediando", "औसत बनाना"),
    "Aversion": ("厌恶", "Aversión", "विरुद्धता"),
    "Avert": ("转向", "Evitar", "दूर करना"),
    "Aviation": ("航空", "Aviación", "विमानन"),
    "Aviator": ("飞行员", "Aviador", "विमान चालक"),
    "Avid": ("热心的", "Ávido", "उत्सुक"),
    "Avoid": ("避免", "Evitar", "बचना"),
    "Avoidable": ("可避免的", "Evitable", "अपरिहार्य"),
    "Avoidance": ("回避", "Evasión", "परिहार"),
    "Avoirdupois": ("阿瓦德皮", "Avoirdupois", "एवोयरडुपॉइस"),
    "Avow": ("宣誓", "Confesar", "स्वीकार करना"),
    "Avowal": ("声明", "Confesión", "स्वीकृति"),
    "Avowed": ("公开的", "Confeso", "स्वीकृत"),
    "Avuncular": ("叔伯的", "Avuncular", "मामा के समान"),
    "Await": ("等待", "Esperar", "प्रतीक्षा करना"),
    "Awake": ("醒", "Despierto", "जागृत"),
    "Awaken": ("唤醒", "Despertar", "जागना"),
    "Awakening": ("觉醒", "Despertar", "जागरण"),
    "Award": ("奖励", "Premio", "पुरस्कार"),
    "Awarded": ("授予", "Concedido", "प्रदत्त"),
    "Aware": ("意识到", "Consciente", "जागरूक"),
    "Awareness": ("意识", "Conciencia", "जागरूकता"),
    "Away": ("远离", "Lejos", "दूर"),
    "Awe": ("敬畏", "Asombro", "भय"),
    "Awed": ("敬畏的", "Asombrado", "भयभीत"),
    "Awesome": ("了不起的", "Impresionante", "शानदार"),
    "Awestricken": ("敬畏的", "Asombrado", "भयभीत"),
    "Awestruck": ("敬畏的", "Asombrado", "भयभीत"),
    "Awful": ("可怕的", "Terrible", "भीषण"),
    "Awfully": ("可怕地", "Terriblemente", "भीषण रूप से"),
    "Awhile": ("一会儿", "Un rato", "कुछ समय"),
    "Awkward": ("尴尬的", "Incómodo", "अजीब"),
    "Awkwardly": ("尴尬地", "Incómodamente", "अजीब तरीके से"),
    "Awkwardness": ("尴尬", "Incomodidad", "अजीबपन"),
    "Awl": ("锥子", "Punzón", "सूआ"),
    "Awning": ("遮阳篷", "Toldo", "छज्जा"),
    "Awoke": ("醒来", "Despertó", "जागा"),
    "Awoken": ("醒来", "Despertado", "जागा"),
    "Awry": ("歪斜的", "Torcido", "तिरछा"),
    "Ax": ("斧头", "Hacha", "कुल्हाड़ी"),
    "Axe": ("斧头", "Hacha", "कुल्हाड़ी"),
    "Axiom": ("公理", "Axioma", "स्वयंसिद्ध"),
    "Axiomatic": ("公理的", "Axiomático", "स्वयंसिद्ध"),
    "Axes": ("轴", "Ejes", "अक्षें"),
    "Axial": ("轴向的", "Axial", "अक्षीय"),
    "Axion": ("阿克西翁", "Axión", "एक्सियॉन"),
    "Axis": ("轴", "Eje", "अक्ष"),
    "Axis of rotation": ("旋转轴", "Eje de rotación", "घूर्णन अक्ष"),
    "Axis of symmetry": ("对称轴", "Eje de simetría", "सममिति की अक्ष"),
    "Axle": ("车轴", "Eje", "धुरी"),
    "Axman": ("斧手", "Leñador", "कुल्हाड़ी चलाने वाला"),
    "Axon": ("轴突", "Axón", "एक्सॉन"),
    "Ay": ("哎呀", "Ay", "हाय"),
    "Ayah": ("仆人", "Ayah", "दाई"),
    "Aye": ("是的", "Sí", "हाँ"),
    "Ayes": ("是的", "Síes", "हां"),
    "Ayin": ("艾因", "Ayin", "अयीन"),
    "Azalea": ("杜鹃花", "Azalea", "अजेलिया"),
    "Azide": ("叠氮化物", "Azida", "आजाइड"),
    "Azimuth": ("方位角", "Acimut", "दिगंश"),
    "Azimuthal": ("方位角的", "Acimutal", "दिगंशीय"),
    "Azine": ("唑", "Azina", "अज़ीन"),
    "Azlon": ("化纤", "Azlón", "अजलॉन"),
    "Azo": ("偶氮", "Azo", "अज़ो"),
    "Azote": ("硝石", "Azote", "अज़ोट"),
    "Azotic": ("含氮的", "Azótico", "अज़ोटिक"),
    "Azotise": ("含氮化", "Azotizar", "अज़ोटाइज़"),
    "Azotism": ("氨中毒", "Azotismo", "अज़ोटिज्म"),
    "Azotiuria": ("尿中含氮", "Azoturia", "अज़ोट्यूरिया"),
    "Aztec": ("阿兹特克", "Azteca", "एज्टेक"),
    "Azure": ("天蓝色", "Azul celeste", "आसमानी"),
}

print(f"Algebra 2 batch 2 translations: {len(algebra2_batch2)} entries")
print("Injecting translations...")
inject_all(algebra2_batch2, decode_entities=True)
print("✓ Algebra 2 batch 2 injection complete!")
