#!/usr/bin/env python3
"""
Second pass: translate the remaining 406 strings that still have English text.
Uses more aggressive pattern matching and individual translations.
"""
import json, re

with open("/workspaces/ArisEdu/algebra2_full_translations.json", "r", encoding="utf-8") as f:
    translations = json.load(f)

# Manual translations for remaining strings
manual = {
    # ── Complex questions ──
    "4. Complex fraction (1/(x+1))/(1/(x−1))": "4. 复合分式 (1/(x+1))/(1/(x−1))",
    "(−∞,−1): pos, (−1,2): neg, (2,∞): pos": "(−∞,−1)：正，(−1,2)：负，(2,∞)：正",
    "2. Pump A: 1/6 min, B: 1/9 min. Fill?": "2. 泵A：1/6分钟，泵B：1/9分钟。多久填满？",
    "6. Test corner (2, 3) in P = x + 2y": "6. 在 P = x + 2y 中测试顶点 (2, 3)",
    "1. f(x)=2x³+5x−3. Remainder by x−2": "1. f(x)=2x³+5x−3。除以 x−2 的余数",
    "2. Corner points: x≥0, y≥0, x+y≤6": "2. 顶点坐标：x≥0, y≥0, x+y≤6",
    "21. Sum 0.5 + 0.25 + 0.125 + ...?": "21. 求和 0.5 + 0.25 + 0.125 + ...？",
    "7. Sum 0.5 + 0.25 + 0.125 + ...?": "7. 求和 0.5 + 0.25 + 0.125 + ...？",
    "6. Max/min of f(x) = 3(x+1)² + 2": "6. f(x) = 3(x+1)² + 2 的最大值/最小值",
    "3. Break-even R(x) = −3x² + 300x": "3. 盈亏平衡 R(x) = −3x² + 300x",
    "7. Heron A = √[s(s−a)(s−b)(s−c)]": "7. 海伦公式 A = √[s(s−a)(s−b)(s−c)]",
    "14. Perfect square x² + 8x + 16": "14. 完全平方式 x² + 8x + 16",
    "7. Perfect square x² + 8x + 16": "7. 完全平方式 x² + 8x + 16",
    "20. Synthetic div divisor (x−5)": "20. 综合除法除数 (x−5)",
    "6. Synthetic div divisor (x−5)": "6. 综合除法除数 (x−5)",
    "1. Vertex of f(x) = x² − 4x + 3": "1. f(x) = x² − 4x + 3 的顶点",
    "7. Application type fixed perim": "7. 固定周长的应用题类型",
    "3. Sign analysis (x−1)(x+2) > 0": "3. 符号分析 (x−1)(x+2) > 0",
    "26. Sign analysis (x+1)/(x−2)": "26. 符号分析 (x+1)/(x−2)",
    "5. Sign analysis (x+1)/(x−2)": "5. 符号分析 (x+1)/(x−2)",
    "11. Pythagorean sin²θ+cos²θ = ?": "11. 勾股恒等式 sin²θ+cos²θ = ?",
    "4. Pythagorean sin²θ+cos²θ = ?": "4. 勾股恒等式 sin²θ+cos²θ = ?",
    "2. Boundary line for 2x − y < 5": "2. 2x − y < 5 的边界线",
    "7. Optimal value in LP found at": "7. 线性规划最优值出现在",
    "5. Normal curve symmetric about": "5. 正态曲线关于…对称",
    "26. Dot product ⟨1,2⟩·⟨3,4⟩ = ?": "26. 点积 ⟨1,2⟩·⟨3,4⟩ = ?",
    "5. Dot product ⟨1,2⟩·⟨3,4⟩ = ?": "5. 点积 ⟨1,2⟩·⟨3,4⟩ = ?",
    "27. Orthogonal vectors dot prod": "27. 正交向量的点积",
    "6. Orthogonal vectors dot prod": "6. 正交向量的点积",
    "28. Boundary: included/excluded": "28. 边界：包含/不包含",
    "7. Boundary: included/excluded": "7. 边界：包含/不包含",
    "16. Remainder (2x³+3x−5)÷(x−2)": "16. (2x³+3x−5)÷(x−2) 的余数",
    "2. Remainder (2x³+3x−5)÷(x−2)": "2. (2x³+3x−5)÷(x−2) 的余数",
    "5. Remainder 3x⁵−2x²+7 by x+2": "5. 3x⁵−2x²+7 除以 x+2 的余数",
    "21. Remainder 3x³−5x+2 by x+1": "21. 3x³−5x+2 除以 x+1 的余数",
    "7. Remainder 3x³−5x+2 by x+1": "7. 3x³−5x+2 除以 x+1 的余数",
    "27. Sketch (x+1)²(x−2): mult?": "27. 画 (x+1)²(x−2) 的图：重数？",
    "6. Sketch (x+1)²(x−2): mult?": "6. 画 (x+1)²(x−2) 的图：重数？",
    "21. Completing square derives": "21. 配方法推导",
    "7. Completing square derives": "7. 配方法推导",
    "10. Deck: P(2nd ace|1st ace)?": "10. 扑克牌：P(第二张A|第一张A)？",
    "3. Deck: P(2nd ace|1st ace)?": "3. 扑克牌：P(第二张A|第一张A)？",
    "17. Curve x = cos t, y = sin t": "17. 曲线 x = cos t, y = sin t",
    "3. Curve x = cos t, y = sin t": "3. 曲线 x = cos t, y = sin t",
    "7. Leading coeff of 5x⁴−3x²+2": "7. 5x⁴−3x²+2 的首项系数",
    "2. Test x=1/2 in 2x³+x²−5x+2": "2. 在 2x³+x²−5x+2 中测试 x=1/2",
    "13. Difference cubes x³ − 27": "13. 立方差 x³ − 27",
    "6. Difference cubes x³ − 27": "6. 立方差 x³ − 27",
    "7. Vertex (5, 3) with upward": "7. 顶点 (5, 3) 开口朝上",
    "5. Test (0,0) in 3x + 2y ≥ 6": "5. 在 3x + 2y ≥ 6 中测试 (0,0)",
    "12. Horiz asymp (x−2)/(x³+1)": "12. (x−2)/(x³+1) 的水平渐近线",
    "5. Horiz asymp (x−2)/(x³+1)": "5. (x−2)/(x³+1) 的水平渐近线",
    "5. Sum ∞ geom |r| < 1: S = ?": "5. 无穷等比级数 |r| < 1：S = ?",
    "19. Sum ∞ geom |r| < 1: S = ?": "19. 无穷等比级数 |r| < 1：S = ?",
    "28. Difference cos(A−B) = ?": "28. 余弦差角公式 cos(A−B) = ?",
    "7. Difference cos(A−B) = ?": "7. 余弦差角公式 cos(A−B) = ?",
    "24. Unit vector ⟨3,4⟩/5 = ?": "24. 单位向量 ⟨3,4⟩/5 = ?",
    "3. Unit vector ⟨3,4⟩/5 = ?": "3. 单位向量 ⟨3,4⟩/5 = ?",
    "7. Remainder 0 in division": "7. 除法余数为0",
    "5. If ±2+i root, conjugate": "5. 若 ±2+i 为根，共轭复根",
    "16. Vertex of x² − 10x + 7": "16. x² − 10x + 7 的顶点",
    "2. Vertex of x² − 10x + 7": "2. x² − 10x + 7 的顶点",
    "3. Complement P(not A) = ?": "3. 补事件 P(非A) = ?",
    "7. P(impossible event) = ?": "7. P(不可能事件) = ?",
    "27. Index variable in ∑ is": "27. ∑ 中的指标变量是",
    "6. Index variable in ∑ is": "6. ∑ 中的指标变量是",
    "sin A cos B + cos A sin B": "sin A cos B + cos A sin B",
    "cos A cos B + sin A sin B": "cos A cos B + sin A sin B",
    "2. Conditional P(A|B) = ?": "2. 条件概率 P(A|B) = ?",
    "9. Conditional P(A|B) = ?": "9. 条件概率 P(A|B) = ?",
    "27. Binomial requirement:": "27. 二项分布条件：",
    "6. Binomial requirement:": "6. 二项分布条件：",
    "18. log_b x + log_b y = ?": "18. log_b x + log_b y = ?",
    "4. log_b x + log_b y = ?": "4. log_b x + log_b y = ?",
    "23. Magnitude |⟨3,4⟩| = ?": "23. 模 |⟨3,4⟩| = ?",
    "2. Magnitude |⟨3,4⟩| = ?": "2. 模 |⟨3,4⟩| = ?",
    "18. Quotient x⁴−16÷(x−2)": "18. x⁴−16÷(x−2) 的商",
    "4. Quotient x⁴−16÷(x−2)": "4. x⁴−16÷(x−2) 的商",
    "14. Vertex of −3(x−2)²+5": "14. −3(x−2)²+5 的顶点",
    "7. Vertex of −3(x−2)²+5": "7. −3(x−2)²+5 的顶点",
    "5. Check sin(π/3) = √3/2": "5. 验证 sin(π/3) = √3/2",
    "13. Reciprocal sec θ = ?": "13. 倒数 sec θ = ?",
    "6. Reciprocal sec θ = ?": "6. 倒数 sec θ = ?",
    "5. Free variable creates": "5. 自由变量产生",
    "1. Roll die, P(even) = ?": "1. 掷骰子，P(偶数) = ?",
    "2. Cards 52, P(red) = ?": "2. 52张牌，P(红色) = ?",
    "3. 68-95-99.7 rule: 1 σ": "3. 68-95-99.7 法则：1 σ",
    "13. Bayes theorem setup": "13. 贝叶斯定理设置",
    "6. Bayes theorem setup": "6. 贝叶斯定理设置",
    "22. Binomial P(X=k) = ?": "22. 二项概率 P(X=k) = ?",
    "10. Difference x² − 16": "10. 平方差 x² − 16",
    "3. Difference x² − 16": "3. 平方差 x² − 16",
    "11. GCF of 12x³ + 18x²": "11. 12x³ + 18x² 的最大公因式",
    "4. GCF of 12x³ + 18x²": "4. 12x³ + 18x² 的最大公因式",
    "13. y = 0.5f(x) effect": "13. y = 0.5f(x) 的效果",
    "6. y = 0.5f(x) effect": "6. y = 0.5f(x) 的效果",
    "20. y = −sin x reflect": "20. y = −sin x 反射",
    "6. y = −sin x reflect": "6. y = −sin x 反射",
    "26. Standard dev σ = ?": "26. 标准差 σ = ?",
    "5. Standard dev σ = ?": "5. 标准差 σ = ?",
    "4. pH formula −log[H⁺]": "4. pH公式 −log[H⁺]",
    "cos θ = (u·v)/(|u||v|)": "cos θ = (u·v)/(|u||v|)",
    "1. Sum of 1+2+3+...+10": "1. 求和 1+2+3+...+10",
    "8. Sum of 1+2+3+...+10": "8. 求和 1+2+3+...+10",
    "2. y = f(x) − 5 shift": "2. y = f(x) − 5 的平移",
    "9. y = f(x) − 5 shift": "9. y = f(x) − 5 的平移",
    "dec (−∞,2], inc [2,∞)": "递减 (−∞,2]，递增 [2,∞)",
    "5. Optimization steps": "5. 优化步骤",
    "6. Compound 1 ≤ x ≤ 5": "6. 复合不等式 1 ≤ x ≤ 5",
    "6. Hypothesis test H₀": "6. 假设检验 H₀",
    "7. P-value < α reject": "7. P值 < α 拒绝",
    "3. Conjugate of 4−7i": "3. 4−7i 的共轭复数",
    "10. y = f(x+3) shift": "10. y = f(x+3) 的平移",
    "3. y = f(x+3) shift": "3. y = f(x+3) 的平移",
    "27. Sum sin(A+B) = ?": "27. 正弦和角公式 sin(A+B) = ?",
    "6. Sum sin(A+B) = ?": "6. 正弦和角公式 sin(A+B) = ?",
    "7. Standard normal μ": "7. 标准正态 μ",
    "2. Normal std dev σ": "2. 正态标准差 σ",
    "12. Tree diagram use": "12. 树状图的用途",
    "5. Tree diagram use": "5. 树状图的用途",
    "use tan 2α = B/(A−C)": "用 tan 2α = B/(A−C)",
    "adjust for direction": "调整方向",
    "7. Upper bound test": "7. 上界测试",
    "4. Use Cosines when": "4. 何时使用余弦定律",
    "a² + b² − 2ab cos C": "a² + b² − 2ab cos C",
    "4. r² = coefficient": "4. r² = 决定系数",
    "3. 95% CI z* value": "3. 95% 置信区间 z* 值",
    "21. Order matters?": "21. 顺序重要吗？",
    "7. Order matters?": "7. 顺序重要吗？",
    "Incorrect Option 1": "错误选项 1",
    "Incorrect Option 2": "错误选项 2",
    "Incorrect Option 3": "错误选项 3",
    "Correct Answer": "正确答案",
    "19. log_b(x/y) = ?": "19. log_b(x/y) = ?",
    "5. log_b(x/y) = ?": "5. log_b(x/y) = ?",
    "7. sin⁻¹(1/2) = ?": "7. sin⁻¹(1/2) = ?",
    "b/sin B = c/sin C": "b/sin B = c/sin C",
    "change in y per x": "y 对 x 的变化率",
    "log_b x − log_b y": "log_b x − log_b y",
    "log_b x + log_b y": "log_b x + log_b y",
    "all except x=2,−2": "除 x=2,−2 外全部",
    "liters/% = amount": "升/% = 总量",
    "liters × % = amount": "升 × % = 总量",
    "liters + % = amount": "升 + % = 总量",
    "2tan x/(1−tan²x)": "2tan x/(1−tan²x)",
    "10. tan(π/3) = ?": "10. tan(π/3) = ?",
    "1. sin(π/6) = ?": "1. sin(π/6) = ?",
    "2. cos(π/4) = ?": "2. cos(π/4) = ?",
    "3. tan(π/3) = ?": "3. tan(π/3) = ?",
    "8. sin(π/6) = ?": "8. sin(π/6) = ?",
    "9. cos(π/4) = ?": "9. cos(π/4) = ?",
    "(1−cos x)/sin x": "(1−cos x)/sin x",
    "6. Converges if": "6. 收敛条件",
    "20. Converges if": "20. 收敛条件",
    "avoids fractions": "避免分数",
    "weighted average": "加权平均",
    "conditional prob": "条件概率",
    "5. σ unknown use": "5. σ未知时使用",
    "anywhere in region": "区域内任意点",
    "all three possible": "三种都可能",
    "faster with integers": "整数运算更快",
    "doesn't satisfy orig": "不满足原方程",
    "increases with mass": "随质量增加",
    "depends on temp": "取决于温度",
    "6. Division f(x)=(x−2)q(x)+r": "6. 除法 f(x)=(x−2)q(x)+r",
    "quotient q, remainder r": "商 q，余数 r",
    "only quotient": "只有商",
    "only remainder": "只有余数",
    "√((1−cos x)/2)": "√((1−cos x)/2)",
    "(a·b)/sin(A·B)": "(a·b)/sin(A·B)",
    "23. sin 2x = ?": "23. sin 2x = ?",
    "24. cos 2x = ?": "24. cos 2x = ?",
    "2. sin 2x = ?": "2. sin 2x = ?",
    "3. cos 2x = ?": "3. cos 2x = ?",
    "need more info": "需要更多信息",
    "boundary lines": "边界线",
    "point ± margin": "点 ± 误差",
    "t-distribution": "t分布",
    "15. n! read as": "15. n! 读作",
    "1. n! read as": "1. n! 读作",
    "1. log₂ 32 = ?": "1. log₂ 32 = ?",
    "2. log₃ 27 = ?": "2. log₃ 27 = ?",
    "8. log₂ 32 = ?": "8. log₂ 32 = ?",
    "9. log₃ 27 = ?": "9. log₃ 27 = ?",
    "same as others": "与其他相同",
    "all except x=3": "除 x=3 外全部",
    "no horiz asymp": "无水平渐近线",
    "horiz asymp y=0": "水平渐近线 y=0",
    "dummy variable": "虚拟变量",
    "infinitely many": "无穷多",
    "edge connecting": "连接边",
    "null hypothesis": "零假设",
    "log_b x·log_b y": "log_b x·log_b y",
    "log_b x/log_b y": "log_b x/log_b y",
    "derivative sign": "导数符号",
    "cos = adj/hyp": "cos = 邻边/斜边",
    "sin = opp/hyp": "sin = 对边/斜边",
    "tan = opp/adj": "tan = 对边/邻边",
    "cos²x − sin²x": "cos²x − sin²x",
    "both possible": "两者都可能",
    "yes important": "是，重要",
    "least squares": "最小二乘法",
    "extrapolation": "外推法",
    "interpolation": "内插法",
    "x=−1 (no sol)": "x=−1（无解）",
    "row reduction": "行化简",
    "(ln x)³": "(ln x)³",
    "(log_b x)−y": "(log_b x)−y",
    "0, 1, or 2 solns": "0、1或2个解",
    
    # ── Short answer options ──
    "isolate a variable": "分离一个变量",
    "Isolate a variable": "分离一个变量",
    "graph both lines": "画出两条线",
    "eliminate a variable": "消去一个变量",
    "solve for x": "求解x",
    "solve for y": "求解y",
    "one unique solution": "一个唯一解",
    "no solutions": "无解",
    "exactly one": "恰好一个",
    "any corner point": "任意顶点",
    "interior point": "内部点",
    "center point": "中心点",
    "corner point": "顶点",
    
    # ── Additional patterns ──
    "(1/2)ab": "(1/2)ab",
    "(1/2)ab sin C": "(1/2)ab sin C",
    "(1/2)ln x": "(1/2)ln x",
    "(1/2)·(ln 1+ln x)": "(1/2)·(ln 1+ln x)",
    "0 to 1": "0 到 1",
    "0 to 4": "0 到 4",
    "0 to 100": "0 到 100",
    "1 to ∞": "1 到 ∞",
    "0.5 hrs": "0.5 小时",
    "0.75 hrs": "0.75 小时",
    "1 hr": "1 小时",
    "1 or 2": "1 或 2",
    "1, 3, or 5": "1、3或5",
    "$1500": "$1500",
    "$2000": "$2000",
    "$2500": "$2500",
    "$3000": "$3000",
}

# Apply manual translations
updated_count = 0
for text, trans in translations.items():
    if text in manual:
        translations[text] = manual[text]
        updated_count += 1
    elif re.search(r'[a-zA-Z]{3,}', trans) and text == trans:
        # Try pattern-based for remaining
        result = text
        
        # Word-level replacements (order matters)
        replacements = [
            # Multi-word first
            ("Complete the square", "配方"),
            ("Completing square", "配方法"),
            ("Break-even", "盈亏平衡"),
            ("break-even", "盈亏平衡"),
            ("Perfect square", "完全平方式"),
            ("perfect square", "完全平方式"),
            ("Corner points", "顶点坐标"),
            ("corner points", "顶点坐标"),
            ("Corner point", "顶点"),
            ("corner point", "顶点"),
            ("Test corner", "测试顶点"),
            ("Sign analysis", "符号分析"),
            ("sign analysis", "符号分析"),
            ("Leading coeff", "首项系数"),
            ("leading coeff", "首项系数"),
            ("Completing square", "配方法"),
            ("completing square", "配方法"),
            ("Difference cubes", "立方差"),
            ("difference cubes", "立方差"),
            ("Difference", "差"),
            ("Free variable", "自由变量"),
            ("free variable", "自由变量"),
            ("Upper bound", "上界"),
            ("upper bound", "上界"),
            ("Binomial requirement", "二项分布条件"),
            ("Index variable", "指标变量"),
            ("Normal curve", "正态曲线"),
            ("normal curve", "正态曲线"),
            ("Standard normal", "标准正态"),
            ("standard normal", "标准正态"),
            ("Standard dev", "标准差"),
            ("standard dev", "标准差"),
            ("Normal std dev", "正态标准差"),
            ("Standard position", "标准位置"),
            ("Hypothesis test", "假设检验"),
            ("Tree diagram", "树状图"),
            ("tree diagram", "树状图"),
            ("Bayes theorem", "贝叶斯定理"),
            ("Dot product", "点积"),
            ("dot product", "点积"),
            ("Orthogonal vectors", "正交向量"),
            ("orthogonal vectors", "正交向量"),
            ("Unit vector", "单位向量"),
            ("unit vector", "单位向量"),
            ("Pythagorean", "勾股恒等式"),
            ("pythagorean", "勾股恒等式"),
            ("Magnitude", "模"),
            ("magnitude", "模"),
            ("Conditional", "条件概率"),
            ("conditional", "条件概率"),
            ("Complement", "补事件"),
            ("complement", "补事件"),
            ("Synthetic div", "综合除法"),
            ("synthetic div", "综合除法"),
            ("Horiz asymp", "水平渐近线"),
            ("horiz asymp", "水平渐近线"),
            ("Converges if", "收敛条件"),
            ("converges if", "收敛条件"),
            ("Optimization", "优化"),
            ("optimization", "优化"),
            ("Application type", "应用题类型"),
            ("Boundary line", "边界线"),
            ("boundary line", "边界线"),
            ("Boundary", "边界"),
            ("boundary", "边界"),
            ("Optimal value", "最优值"),
            ("optimal value", "最优值"),
            ("Reciprocal", "倒数"),
            ("reciprocal", "倒数"),
            ("Conjugate", "共轭复数"),
            ("conjugate", "共轭复数"),
            ("Compound", "复合"),
            ("compound", "复合"),
            ("Remainder", "余数"),
            ("remainder", "余数"),
            ("Quotient", "商"),
            ("quotient", "商"),
            ("Division", "除法"),
            ("division", "除法"),
            ("Vertex", "顶点"),
            ("vertex", "顶点"),
            ("Sketch", "画图"),
            ("sketch", "画图"),
            ("Pump", "泵"),
            ("pump", "泵"),
            ("Check", "验证"),
            ("check", "验证"),
            ("effect", "效果"),
            ("reflect", "反射"),
            ("shift", "平移"),
            ("Reject", "拒绝"),
            ("reject", "拒绝"),
            ("Max/min", "最大值/最小值"),
            ("max/min", "最大值/最小值"),
            ("Max", "最大值"),
            ("Min", "最小值"),
            ("Sum", "求和"),
            ("sum", "求和"),
            ("Converges", "收敛"),
            ("Diverges", "发散"),
            ("GCF of", "的最大公因式"),
            ("GCF", "最大公因式"),
            ("Order matters", "顺序重要吗"),
            ("order matters", "顺序重要吗"),
            ("Deck", "扑克牌"),
            ("Roll die", "掷骰子"),
            ("Cards", "牌"),
            ("Curve", "曲线"),
            ("curve", "曲线"),
            ("Use Cosines when", "何时使用余弦定律"),
            ("Heron", "海伦公式"),
            ("heron", "海伦公式"),
            ("symmetric about", "关于…对称"),
            ("found at", "出现在"),
            ("fixed perim", "固定周长"),
            ("derives", "推导"),
            ("steps", "步骤"),
            ("upward", "朝上"),
            ("downward", "朝下"),
            ("Test", "测试"),
            ("Fill", "填满"),
            ("read as", "读作"),
            ("mult", "重数"),
            ("included/excluded", "包含/不包含"),
            ("Incorrect Option", "错误选项"),
            ("Correct Answer", "正确答案"),
            ("P-value", "P值"),
            ("setup", "设置"),
            ("Creates", "产生"),
            ("creates", "产生"),
            ("unknown use", "未知时使用"),
        ]
        
        for eng, chn in replacements:
            if eng in result:
                result = result.replace(eng, chn)
        
        if result != text:
            translations[text] = result
            updated_count += 1

print(f"Updated translations: {updated_count}")

# Final check
still_unchanged = []
for text, trans in translations.items():
    if re.search(r'[a-zA-Z]{3,}', trans) and text == trans:
        still_unchanged.append(text)

print(f"Still unchanged: {len(still_unchanged)}")
if still_unchanged:
    for s in sorted(still_unchanged, key=len, reverse=True)[:20]:
        print(f"  {repr(s[:120])}")

# Save updated
with open("/workspaces/ArisEdu/algebra2_full_translations.json", "w", encoding="utf-8") as f:
    json.dump(translations, f, ensure_ascii=False, indent=2)

print(f"\nTotal translations: {len(translations)}")
print("Saved to algebra2_full_translations.json")
