#!/usr/bin/env python3
"""
Translate all missing content from Chemistry, Physics, Biology, Geometry
"""

import json
import re

# Comprehensive translation dictionary covering all subjects
SUBJECT_TRANSLATIONS = {
    # Chemistry terms
    "Solid": "固体",
    "solid": "固体",
    "Liquid": "液体",
    "liquid": "液体",
    "Gas": "气体",
    "gas": "气体",
    "Atom": "原子",
    "atom": "原子",
    "Molecule": "分子",
    "molecule": "分子",
    "Compound": "化合物",
    "compound": "化合物",
    "Element": "元素",
    "element": "元素",
    "Chemical": "化学",
    "chemical": "化学",
    "Reaction": "反应",
    "reaction": "反应",
    "Bond": "键",
    "bond": "键",
    "Electron": "电子",
    "electron": "电子",
    "Proton": "质子",
    "proton": "质子",
    "Neutron": "中子",
    "neutron": "中子",
    "Ion": "离子",
    "ion": "离子",
    "Energy": "能量",
    "energy": "能量",
    "Temperature": "温度",
    "temperature": "温度",
    "Pressure": "压强",
    "pressure": "压强",
    "Concentration": "浓度",
    "concentration": "浓度",
    "pH": "pH值",
    "Acid": "酸",
    "acid": "酸",
    "Base": "碱",
    "base": "碱",
    "Salt": "盐",
    "salt": "盐",
    "Oxidation": "氧化",
    "oxidation": "氧化",
    "Reduction": "还原",
    "reduction": "还原",
    
    # Physics terms
    "Force": "力",
    "force": "力",
    "Motion": "运动",
    "motion": "运动",
    "Velocity": "速度",
    "velocity": "速度",
    "Acceleration": "加速度",
    "acceleration": "加速度",
    "Mass": "质量",
    "mass": "质量",
    "Weight": "重量",
    "weight": "重量",
    "Momentum": "动量",
    "momentum": "动量",
    "Work": "功",
    "work": "功",
    "Power": "功率",
    "power": "功率",
    "Kinetic": "动能",
    "kinetic": "动能",
    "Potential": "势能",
    "potential": "势能",
    "Wave": "波",
    "wave": "波",
    "Frequency": "频率",
    "frequency": "频率",
    "Wavelength": "波长",
    "wavelength": "波长",
    "Light": "光",
    "light": "光",
    "Sound": "声音",
    "sound": "声音",
    "Electricity": "电",
    "electricity": "电",
    "Electric": "电的",
    "electric": "电的",
    "Magnetic": "磁的",
    "magnetic": "磁的",
    "Magnet": "磁铁",
    "magnet": "磁铁",
    "Circuit": "电路",
    "circuit": "电路",
    "Current": "电流",
    "current": "电流",
    "Voltage": "电压",
    "voltage": "电压",
    "Resistance": "电阻",
    "resistance": "电阻",
    "Thermal": "热的",
    "thermal": "热的",
    "Heat": "热",
    "heat": "热",
    "Friction": "摩擦力",
    "friction": "摩擦力",
    "Gravity": "重力",
    "gravity": "重力",
    "Orbit": "轨道",
    "orbit": "轨道",
    
    # Biology terms
    "Cell": "细胞",
    "cell": "细胞",
    "Organism": "生物",
    "organism": "生物",
    "Protein": "蛋白质",
    "protein": "蛋白质",
    "DNA": "DNA",
    "Gene": "基因",
    "gene": "基因",
    "Chromosome": "染色体",
    "chromosome": "染色体",
    "Mitochondria": "线粒体",
    "mitochondria": "线粒体",
    "Photosynthesis": "光合作用",
    "photosynthesis": "光合作用",
    "Respiration": "呼吸作用",
    "respiration": "呼吸作用",
    "Enzyme": "酶",
    "enzyme": "酶",
    "Metabolism": "代谢",
    "metabolism": "代谢",
    "Evolution": "进化",
    "evolution": "进化",
    "Species": "物种",
    "species": "物种",
    "Population": "种群",
    "population": "种群",
    "Ecosystem": "生态系统",
    "ecosystem": "生态系统",
    "Reproduction": "生殖",
    "reproduction": "生殖",
    "Organ": "器官",
    "organ": "器官",
    "Tissue": "组织",
    "tissue": "组织",
    "System": "系统",
    "system": "系统",
    "Muscle": "肌肉",
    "muscle": "肌肉",
    "Bone": "骨头",
    "bone": "骨头",
    "Blood": "血液",
    "blood": "血液",
    "Heart": "心脏",
    "heart": "心脏",
    "Brain": "脑",
    "brain": "脑",
    "Nerve": "神经",
    "nerve": "神经",
    "Plant": "植物",
    "plant": "植物",
    "Animal": "动物",
    "animal": "动物",
    
    # Geometry terms
    "Triangle": "三角形",
    "triangle": "三角形",
    "Square": "正方形",
    "square": "正方形",
    "Rectangle": "矩形",
    "rectangle": "矩形",
    "Circle": "圆",
    "circle": "圆",
    "Angle": "角",
    "angle": "角",
    "Line": "线",
    "line": "线",
    "Point": "点",
    "point": "点",
    "Parallel": "平行",
    "parallel": "平行",
    "Perpendicular": "垂直",
    "perpendicular": "垂直",
    "Area": "面积",
    "area": "面积",
    "Perimeter": "周长",
    "perimeter": "周长",
    "Volume": "体积",
    "volume": "体积",
    "Surface": "表面",
    "surface": "表面",
    "Radius": "半径",
    "radius": "半径",
    "Diameter": "直径",
    "diameter": "直径",
    "Hypotenuse": "斜边",
    "hypotenuse": "斜边",
    "Vertex": "顶点",
    "vertex": "顶点",
    "Edge": "边",
    "edge": "边",
    "Face": "面",
    "face": "面",
    "Congruent": "全等",
    "congruent": "全等",
    "Similar": "相似",
    "similar": "相似",
    "Equilateral": "等边",
    "equilateral": "等边",
    "Isosceles": "等腰",
    "isosceles": "等腰",
    "Scalene": "不等边",
    "scalene": "不等边",
    "Right": "直角",
    "Obtuse": "钝",
    "obtuse": "钝",
    "Acute": "锐",
    "acute": "锐",
    
    # Common academic phrases
    "Define": "定义",
    "define": "定义",
    "Identify": "识别",
    "identify": "识别",
    "Explain": "解释",
    "explain": "解释",
    "Calculate": "计算",
    "calculate": "计算",
    "Determine": "确定",
    "determine": "确定",
    "Apply": "应用",
    "apply": "应用",
    "Compare": "比较",
    "compare": "比较",
    "Contrast": "对比",
    "contrast": "对比",
    "Analyze": "分析",
    "analyze": "分析",
    "Evaluate": "评估",
    "evaluate": "评估",
    "Describe": "描述",
    "describe": "描述",
    "Predict": "预测",
    "predict": "预测",
    "Observe": "观察",
    "observe": "观察",
    "Measure": "测量",
    "measure": "测量",
    "Example": "例子",
    "example": "例子",
    "Note": "注意",
    "note": "注意",
    "Important": "重要",
    "important": "重要",
    "Key": "关键的",
    "key": "关键的",
    "Concept": "概念",
    "concept": "概念",
    "Property": "属性",
    "property": "属性",
    "Characteristic": "特征",
    "characteristic": "特征",
    "Function": "函数",
    "function": "函数",
    "Structure": "结构",
    "structure": "结构",
}

def smart_translate(text):
    """Translate text using pattern matching"""
    result = text
    
    # Try exact matches first
    for eng, chi in sorted(SUBJECT_TRANSLATIONS.items(), key=lambda x: -len(x[0])):
        if len(eng) <= 15:
            pattern = r'\b' + re.escape(eng) + r'\b'
            result = re.sub(pattern, chi, result, flags=re.IGNORECASE)
        else:
            result = result.replace(eng, chi)
    
    return result

def main():
    # Read missing strings
    with open('/workspaces/ArisEdu/other_courses_missing.json', 'r', encoding='utf-8') as f:
        missing = json.load(f)
    
    print(f"Translating {len(missing)} missing strings...")
    
    translations = {}
    for i, s in enumerate(missing):
        translations[s] = smart_translate(s)
        if (i + 1) % 500 == 0:
            print(f"  Translated {i + 1}/{len(missing)}")
    
    # Save
    with open('/workspaces/ArisEdu/other_courses_translations.json', 'w', encoding='utf-8') as f:
        json.dump(translations, f, ensure_ascii=False, indent=2)
    
    print(f"✓ Translated {len(translations)} strings")
    return translations

if __name__ == "__main__":
    main()
