import json
import os

base = r"C:\Users\Peter\pkang6689-pixel.github.io\content_data\LinearAlgebraLessons"

def q(num, text, opts, exp, correct_idx=0):
    options = []
    for i, o in enumerate(opts):
        options.append({"text": o, "is_correct": i == correct_idx, "data_i18n": None})
    return {"question_number": num, "question_text": text, "attempted": 2, "data_i18n": None, "options": options, "explanation": exp}

def write_quiz(unit, lesson, title, questions):
    data = {"unit": unit, "lesson_number": lesson, "title": title, "course": "Linear Algebra", "quiz_questions": questions}
    path = os.path.join(base, f"Unit{unit}", f"Lesson{lesson}_Quiz.json")
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Wrote {path} with {len(questions)} questions")

# 4.2 Finding Inverses (row reduction method)
qs = [
    q(1,"To find the inverse of A using row reduction, you form the augmented matrix:",["[A | 0]","[A | I]","[I | A]","[A | A]"],"You augment A with the identity matrix I on the right: [A | I], then row reduce until the left side becomes I.",1),
    q(2,"After row reducing [A | I] to [I | B], what is B?",["A^T","A^2","A^(-1)","det(A)*I"],"When the left side becomes I, the right side is the inverse: B = A^(-1).",2),
    q(3,"Find the inverse of [[1,2],[3,7]] using row reduction. What is A^(-1)?",["[[7,-2],[-3,1]]","[[-7,2],[3,-1]]","[[1,-2],[-3,7]]","[[7,2],[3,1]]"],"det=7-6=1. A^(-1) = [[7,-2],[-3,1]]. Verify: [[1,2],[3,7]]*[[7,-2],[-3,1]] = [[1,0],[0,1]].",0),
    q(4,"During row reduction of [A|I], if you encounter a row of all zeros on the left side, what does this mean?",["Continue row reducing","A is invertible","A is singular and has no inverse","Swap with another row"],"A row of all zeros on the left means A cannot be reduced to I, so A is singular and has no inverse.",2),
    q(5,"Row reduce [[2,4|1,0],[1,3|0,1]]. After R1<->R2 and elimination, what is A^(-1)?",["[[3,-4],[-1,2]]","[[3/2,-2],[-1/2,1]]","[[1.5,-2],[-0.5,1]]","Both B and C"],"Swap rows: [[1,3|0,1],[2,4|1,0]]. R2-2R1: [[1,3|0,1],[0,-2|1,-2]]. R2/-2: [[1,3|0,1],[0,1|-1/2,1]]. R1-3R2: [[1,0|3/2,-2],[0,1|-1/2,1]]. A^(-1)=[[3/2,-2],[-1/2,1]].",3),
    q(6,"What is the inverse of the 2x2 identity matrix?",["The zero matrix","Itself (the identity matrix)","Does not exist","[[0,1],[1,0]]"],"I*I = I, so I^(-1) = I.",1),
    q(7,"For a 3x3 matrix, the augmented matrix [A|I] has dimensions:",["3x3","3x6","6x3","6x6"],"A is 3x3 and I is 3x3, so [A|I] is 3x6.",1),
    q(8,"If row reduction of [A|I] yields [[1,0,0|2,-1,0],[0,1,0|-3,2,1],[0,0,1|1,0,-1]], what is A^(-1)?",["[[2,-1,0],[-3,2,1],[1,0,-1]]","[[1,0,0],[0,1,0],[0,0,1]]","Cannot be determined","The transpose of the left side"],"The right side after complete reduction gives A^(-1) = [[2,-1,0],[-3,2,1],[1,0,-1]].",0),
    q(9,"Can you find the inverse of a non-square matrix using row reduction?",["Yes, for any matrix","Only for tall matrices","Only for wide matrices","No, inverses only exist for square matrices"],"Matrix inverses (two-sided) are defined only for square matrices. Non-square matrices may have left or right inverses but not a full inverse.",3),
    q(10,"What is the computational cost of finding an inverse via row reduction for an nxn matrix?",["O(n^2)","O(n^3)","O(n^4)","O(2^n)"],"Row reducing [A|I] to [I|A^(-1)] requires roughly 2n^3/3 + n^3 = O(n^3) operations, similar to solving n systems.",1),
    q(11,"What does 'augmenting with the identity' mean?",["Placing the identity matrix to the right of A to form [A|I]","Adding I to A","Multiplying A by I","Replacing A with I"],"Augmenting with the identity means writing A and I side by side: [A | I]. Row operations on this matrix simultaneously transform both A and I.",0),
    q(12,"What does 'elementary row operations preserve invertibility' mean?",["Row operations cannot change whether a matrix is invertible","Row operations always make a matrix invertible","Row operations can only be applied to invertible matrices","Row operations convert invertible matrices to singular ones"],"Elementary row operations are themselves invertible operations (each can be undone). They do not change whether the original matrix A is invertible or not.",0),
    q(13,"What is a 'row reduction algorithm' for finding inverses?",["A systematic process of applying row operations to [A|I] until the left side becomes I, at which point the right side is A^(-1)","Random row swaps until the identity appears","Computing the determinant first, then dividing","Multiplying A by random matrices"],"The algorithm applies forward elimination and back elimination (Gauss-Jordan) to [A|I], transforming the left side to I and the right side to A^(-1).",0),
    q(14,"What does 'pivot position' tell you about invertibility during row reduction?",["If every column has a pivot, the matrix is invertible","If any column lacks a pivot, the matrix is invertible","Pivots are unrelated to invertibility","Only the first pivot matters"],"During row reduction, if every column of A contains a pivot (full rank), A is invertible. If any column lacks a pivot, A is singular.",0),
    q(15,"What does 'RREF of [A|I]' give?",["[I|A^(-1)] if A is invertible, or a matrix with a zero row on the left if A is singular","Always the identity","Always [A|A]","The determinant"],"If A is invertible, RREF of [A|I] = [I|A^(-1)]. If A is singular, a zero row appears on the left side.",0),
    q(16,"What does 'checking the inverse' mean?",["Verifying that A*A^(-1) = I and A^(-1)*A = I","Checking that det(A^(-1)) = 1","Ensuring A^(-1) has no zeros","Computing the trace of A^(-1)"],"After computing A^(-1), multiply A*A^(-1) and verify it equals I. This catches arithmetic errors.",0),
    q(17,"What is the 'Gauss-Jordan method' for inverses?",["Using both forward and backward elimination on [A|I] to reach [I|A^(-1)]","Using only forward elimination","Computing cofactors","Finding eigenvalues"],"Gauss-Jordan applies forward elimination (zeros below pivots) and backward elimination (zeros above pivots) plus pivot scaling to transform A into I.",0),
    q(18,"What does 'ill-conditioned matrix' mean for inverse computation?",["The matrix is rectangular","The inverse exists but is very sensitive to rounding errors","The matrix has no inverse","The matrix is diagonal"],"An ill-conditioned matrix has a large condition number. Its inverse exists but is numerically unreliable due to amplification of rounding errors.",1),
    q(19,"What is 'partial pivoting' used for in inverse computation?",["Improving numerical stability by swapping rows to place the largest entry in the pivot position","Making computation faster","Reducing memory usage","Ensuring the inverse is symmetric"],"Partial pivoting selects the largest absolute value in the pivot column, reducing numerical errors during row reduction.",0),
    q(20,"What is the relationship between row reducing A to I and expressing I as a product of elementary matrices times A?",["Each row operation corresponds to left-multiplication by an elementary matrix, so I = E_k...E_2*E_1*A, meaning A^(-1) = E_k...E_1","They are unrelated","Row reduction is division","Elementary matrices are only theoretical"],"Row reduction of A to I means E_k...E_1*A = I, so A^(-1) = E_k...E_1. The same operations applied to I give A^(-1).",0),
    q(21,"A pharmacist needs to solve Ax = b1, Ax = b2, and Ax = b3 for the same 3x3 matrix A. She decides to compute A^(-1) first. Is this efficient?",["Yes, computing A^(-1) once allows quick solutions for all three right-hand sides","No, she should use Gaussian elimination three separate times","Only if A is diagonal","Only if all b vectors are the same"],"Computing A^(-1) once costs O(n^3). Then each x = A^(-1)*b costs O(n^2). For multiple right-hand sides, this is more efficient than repeating full elimination.",0),
    q(22,"An electrical engineer row-reduces [[1,-1|1,0],[2,3|0,1]]. After R2-2R1: [[1,-1|1,0],[0,5|-2,1]]. After R2/5 and R1+R2: what is A^(-1)?",["[[3/5,1/5],[-2/5,1/5]]","[[3,1],[-2,1]]","[[0.6,0.2],[-0.4,0.2]]","Both A and C"],"R2/5: [[1,-1|1,0],[0,1|-2/5,1/5]]. R1+R2: [[1,0|3/5,1/5],[0,1|-2/5,1/5]]. A^(-1)=[[3/5,1/5],[-2/5,1/5]] = [[0.6,0.2],[-0.4,0.2]].",3),
    q(23,"A data scientist row-reduces a 100x100 matrix [A|I] and finds a zero row on the left at row 73. What should she conclude?",["A is invertible with a special structure","A is singular and has no inverse","She made a computational error","The inverse is a 73x73 matrix"],"A zero row on the left during reduction means A does not have full rank and is singular. No inverse exists.",1),
    q(24,"A control systems engineer needs A^(-1) for a 4x4 matrix. She uses software that reports 'matrix is singular or nearly singular.' What should she do?",["Force the computation anyway","Check the condition number and consider regularization or an alternative formulation","Conclude that no solution exists to Ax=b","Increase the matrix size"],"A singularity warning means either the matrix is exactly singular or very ill-conditioned. She should check the condition number and consider alternatives.",1),
    q(25,"A navigation engineer has matrix A = [[1,0,1],[0,1,1],[1,1,0]]. She augments with I and row reduces. After elimination, the left side becomes I. She reads A^(-1) from the right. Verify: is det(A) nonzero?",["Yes, det = -2","No, det = 0","Yes, det = 2","Yes, det = 1"],"det = 1(0-1) - 0 + 1(0-1) = -1 - 1 = -2. Since det != 0, A is invertible.",0),
    q(26,"A biologist models population dynamics with P = [[0.8,0.3],[0.2,0.7]]. She computes P^(-1) to reverse-forecast past populations. Is P invertible?",["Yes, det = 0.56-0.06 = 0.50 != 0","No, population matrices are never invertible","Yes, det = 1","Cannot determine"],"det = 0.8(0.7) - 0.3(0.2) = 0.56 - 0.06 = 0.50 != 0. P is invertible.",0),
    q(27,"A teacher shows students that for A = [[a,b],[c,d]], A^(-1) = (1/(ad-bc))*[[d,-b],[-c,a]]. A student asks: why is this the same as the row reduction result? What should the teacher say?",["Both methods are mathematically equivalent; the formula is derived from row reducing [A|I]","They give different results","The formula only works for integer matrices","Row reduction is an approximation"],"The 2x2 inverse formula can be derived by performing Gauss-Jordan elimination on [[a,b|1,0],[c,d|0,1]], yielding the same result.",0),
    q(28,"A game developer needs to invert a 3x3 rotation matrix R. She knows R is orthogonal. What is the fastest way?",["Row reduce [R|I]","Compute R^(-1) = R^T (just transpose)","Use the adjugate formula","Compute determinants"],"For orthogonal matrices, R^(-1) = R^T. Simply transposing is O(n^2), much faster than row reduction.",1),
    q(29,"A chemical engineer has a lower triangular matrix L. To find L^(-1) by row reduction, she notices the process is simpler. Why?",["L is already partially in echelon form, so fewer operations are needed","L has no inverse","The inverse of a lower triangular matrix is upper triangular","Both A and C"],"Lower triangular matrices are already in echelon form (forward elimination is done). The inverse of a lower triangular matrix is also lower triangular, simplifying computation.",3),
    q(30,"A climate researcher row-reduces [A|I] for a 5x5 matrix and successfully obtains [I|B]. She wants to verify B = A^(-1). What is the most reliable check?",["Compute A*B and verify it equals I","Check that det(B) = 1","Verify B is symmetric","Check that B has no negative entries"],"The definitive verification is A*B = I (and optionally B*A = I). This directly confirms B is the inverse.",0)
]
write_quiz(4, "4.2", "Finding Inverses (row reduction method)", qs)

# 4.3 Adjoint Method
qs = [
    q(1,"The adjoint (classical adjoint) of a matrix A is:",["The transpose of the cofactor matrix","The conjugate transpose","The transpose of A","The determinant times I"],"adj(A) = (cofactor matrix)^T. It is used in the formula A^(-1) = adj(A)/det(A).",0),
    q(2,"The inverse formula using the adjoint is A^(-1) = ?",["adj(A) * det(A)","adj(A) / det(A)","det(A) / adj(A)","adj(A) + det(A)*I"],"A^(-1) = (1/det(A)) * adj(A), provided det(A) != 0.",1),
    q(3,"For A = [[a,b],[c,d]], adj(A) = ?",["[[d,-b],[-c,a]]","[[a,-b],[-c,d]]","[[-d,b],[c,-a]]","[[d,b],[c,a]]"],"For 2x2: adj(A) = [[d,-b],[-c,a]]. Swap diagonal entries, negate off-diagonal entries.",0),
    q(4,"What is adj(I) for the nxn identity matrix?",["The zero matrix","I itself","nI","I^T"],"Since the cofactor of each entry of I gives back I's structure, adj(I) = I.",1),
    q(5,"If det(A) = 3 and adj(A) = [[6,-3],[0,3]], what is A^(-1)?",["[[2,-1],[0,1]]","[[6,-3],[0,3]]","[[18,-9],[0,9]]","[[1/6,-1/3],[0,1/3]]"],"A^(-1) = adj(A)/det(A) = (1/3)*[[6,-3],[0,3]] = [[2,-1],[0,1]].",0),
    q(6,"The property A * adj(A) = det(A) * I holds for:",["Only 2x2 matrices","Only invertible matrices","All square matrices","Only diagonal matrices"],"A * adj(A) = det(A) * I is true for all square matrices, even singular ones (where both sides equal the zero matrix).",2),
    q(7,"For a 3x3 matrix, computing adj(A) requires finding how many cofactors?",["3","6","9","27"],"A 3x3 matrix has 9 entries, each with a cofactor. All 9 cofactors must be computed to form the cofactor matrix.",2),
    q(8,"What is the computational complexity of the adjoint method for an nxn inverse?",["O(n^2)","O(n^3)","O(n^4) or higher","O(n log n)"],"Computing n^2 cofactors, each requiring an (n-1)x(n-1) determinant, gives O(n^2 * n^2) = O(n^4) using cofactor expansion, or O(n^2 * (n-1)^3) using elimination for each.",2),
    q(9,"If A = [[2,1],[5,3]], what is adj(A)?",["[[3,-1],[-5,2]]","[[2,5],[1,3]]","[[-3,1],[5,-2]]","[[3,1],[5,2]]"],"For 2x2: swap diagonal (2,3)->(3,2), negate off-diagonal (1,5)->(-1,-5). adj(A) = [[3,-1],[-5,2]].",0),
    q(10,"For a singular matrix (det=0), what is adj(A)?",["Undefined","The zero matrix always","May be nonzero, but A*adj(A) = 0","The identity"],"A*adj(A) = det(A)*I = 0*I = 0. The adjugate itself may have nonzero entries, but the product with A is always zero.",2),
    q(11,"What does 'classical adjoint' mean?",["The transpose of the cofactor matrix, also called the adjugate","The complex conjugate of A","The adjoint operator in functional analysis","The transpose of A"],"The classical adjoint (adjugate) is the transpose of the matrix of cofactors. It should not be confused with the conjugate transpose used in other contexts.",0),
    q(12,"What does 'cofactor matrix' mean?",["The matrix where entry (i,j) is the cofactor C_{ij} = (-1)^(i+j) * M_{ij}","A matrix of all minors without signs","The inverse of A","The determinant matrix"],"The cofactor matrix replaces each entry a_{ij} with its cofactor C_{ij}. The adjugate is the transpose of this matrix.",0),
    q(13,"What is the 'adjugate' of a matrix?",["Another name for the classical adjoint: adj(A) = (cofactor matrix)^T","The absolute value of the determinant","The matrix of eigenvalues","A diagonal matrix"],"Adjugate is the modern mathematical term for the classical adjoint, to avoid confusion with the Hermitian adjoint.",0),
    q(14,"What does 'Cramer-adjoint connection' refer to?",["The entries of A^(-1) can be expressed as cofactors divided by det(A), connecting Cramer's rule to the adjugate","A formula for determinants using Cramer's name","A method for solving systems without determinants","The relationship between adj and trace"],"The (i,j) entry of A^(-1) is C_{ji}/det(A), which connects the adjugate formula to Cramer's rule for each variable.",0),
    q(15,"What does adj(AB) equal?",["adj(A)*adj(B)","adj(B)*adj(A)","adj(A)+adj(B)","(AB)^T"],"adj(AB) = adj(B)*adj(A), similar to how (AB)^(-1) = B^(-1)A^(-1). The order reverses.",1),
    q(16,"What is det(adj(A)) for an nxn matrix A?",["det(A)","det(A)^(n-1)","det(A)^n","1"],"det(adj(A)) = det(A)^(n-1). This follows from A*adj(A) = det(A)*I and taking determinants of both sides.",1),
    q(17,"What does 'symbolic inverse' mean?",["An inverse expressed in terms of symbolic entries (like a, b, c, d) rather than numbers","An inverse that does not exist","A graphical representation of the inverse","An approximate inverse"],"Using the adjugate method, A^(-1) can be written as a formula involving symbolic entries and determinants, useful for theoretical analysis.",0),
    q(18,"What is the adjugate of a diagonal matrix diag(a,b,c)?",["diag(bc, ac, ab)","diag(1/a, 1/b, 1/c)","diag(a,b,c)","The zero matrix"],"For a diagonal matrix, the cofactors give products of the other diagonal entries: adj = diag(bc, ac, ab).",0),
    q(19,"What does A^(-1) = adj(A)/det(A) reveal about the structure of inverses?",["Each entry of A^(-1) is a polynomial in the entries of A divided by det(A)","The inverse is always an integer matrix","The inverse has the same structure as A","The entries of A^(-1) are always positive"],"The adjugate entries are polynomials in the entries of A (sums of products of entries). Dividing by det(A) shows each entry of A^(-1) is a rational function of A's entries.",0),
    q(20,"What is the use of the adjugate in differential equations?",["The adjugate appears in the formula for the matrix exponential and in solving systems of ODEs","It is not used in differential equations","It replaces the derivative operator","It computes eigenvalues directly"],"In systems of ODEs dx/dt = Ax, the adjugate of (sI-A) appears in the Laplace transform solution and transfer functions.",0),
    q(21,"A cryptographer needs the inverse of [[3,5],[2,7]] modulo 26. det = 11, and 11^(-1) mod 26 = 19. Using adj(A) = [[7,-5],[-2,3]], what is A^(-1) mod 26?",["[[133,-95],[-38,57]] mod 26 = [[3,9],[14,5]]","[[7,-5],[-2,3]]","[[19,19],[19,19]]","Cannot be computed"],"A^(-1) = 19*[[7,-5],[-2,3]] mod 26 = [[133,-95],[-38,57]] mod 26 = [[3,9],[14,5]].",0),
    q(22,"An engineer needs to find the (2,1) entry of A^(-1) for a 3x3 matrix without computing the full inverse. Using the adjugate, this entry is:",["C_{12}/det(A), where C_{12} is the cofactor of a_{12}","C_{21}/det(A)","a_{21}/det(A)","The minor M_{21}"],"The (i,j) entry of A^(-1) = (1/det(A)) * adj(A)_{ij} = C_{ji}/det(A). For position (2,1): C_{12}/det(A).",0),
    q(23,"A physics student computes adj(A) for A = [[1,0,2],[0,1,0],[3,0,1]]. The cofactor C_{11} = det([[1,0],[0,1]]) = 1. Is this correct?",["Yes","No, C_{11} should include a sign factor","No, the wrong submatrix was used","C_{11} = -1"],"C_{11} = (-1)^(1+1) * det([[1,0],[0,1]]) = (+1)(1) = 1. The sign factor is +1 and the submatrix is correct.",0),
    q(24,"A control engineer has a 2x2 transfer function matrix. She uses the adjugate to find the inverse symbolically: if A = [[s+1, 2],[3, s+4]], what is adj(A)?",["[[s+4, -2],[-3, s+1]]","[[s+1, -2],[-3, s+4]]","[[s+4, 2],[3, s+1]]","[[s+4, 3],[2, s+1]]"],"For 2x2: swap diagonal entries and negate off-diagonal: adj = [[s+4, -2],[-3, s+1]].",0),
    q(25,"A mathematician proves that for any nxn matrix A, A*adj(A) = det(A)*I. If A is 3x3 with det(A)=5, what is A*adj(A)?",["5*I = [[5,0,0],[0,5,0],[0,0,5]]","I","adj(A)","25*I"],"A*adj(A) = det(A)*I = 5*I = diag(5,5,5).",0),
    q(26,"A numerical analyst compares the adjugate method to row reduction for a 10x10 matrix. Which is more efficient?",["Adjugate method (fewer operations)","Row reduction (O(n^3) vs O(n^4+) for adjugate)","Both are equally efficient","Neither can handle 10x10"],"Row reduction is O(n^3) while the adjugate method requires computing n^2 cofactors, making it O(n^4) or worse. Row reduction is far more efficient for large n.",1),
    q(27,"A statistics student needs A^(-1) for a symmetric positive definite matrix. Using the adjugate, she knows adj(A) is also symmetric. Why?",["Because cofactors of a symmetric matrix form a symmetric cofactor matrix, and transposing it preserves symmetry","All adjugates are symmetric","Symmetry is unrelated to the adjugate","Only for 2x2 matrices"],"For symmetric A, M_{ij} = M_{ji}, and the sign pattern (-1)^(i+j) is symmetric. So adj(A) is symmetric.",0),
    q(28,"A chemical engineer uses the formula adj(A)/det(A) for A = [[4,7],[2,6]]. det = 24-14 = 10. adj = [[6,-7],[-2,4]]. What is A^(-1)?",["[[0.6,-0.7],[-0.2,0.4]]","[[6,-7],[-2,4]]","[[4,7],[2,6]]","[[0.4,0.7],[0.2,0.6]]"],"A^(-1) = (1/10)*[[6,-7],[-2,4]] = [[0.6,-0.7],[-0.2,0.4]].",0),
    q(29,"A professor tells students: 'The adjugate method is theoretically important but practically limited.' She means:",["The formula gives insight into the structure of inverses but is computationally expensive for large matrices","The method only works for 2x2 matrices","The method is inaccurate","The method requires eigenvalues"],"The adjugate formula A^(-1) = adj(A)/det(A) provides a closed-form expression and is useful for proofs and small matrices, but it is O(n^4+) and impractical for large n.",0),
    q(30,"A robotics researcher needs to compute the inverse of a parameterized 3x3 matrix symbolically (entries are functions of joint angles). Which method is most suitable?",["Gaussian elimination with numerical values","The adjugate method, which gives a symbolic closed-form inverse","Iterative methods","LU decomposition"],"For symbolic computation, the adjugate method is ideal because it produces an exact formula in terms of the parameters, unlike numerical methods.",1)
]
write_quiz(4, "4.3", "Adjoint Method", qs)

print("Done with 4.2 and 4.3")
