#!/usr/bin/env python3
"""
Extract and translate ALL summary content from biology lessons.
Extracts text from h3, p, li, b elements and generates translations.
"""

import re
from pathlib import Path
from html.parser import HTMLParser

BIOLOGY_DIR = Path(r"c:\Users\Peter\pkang6689-pixel.github.io\ArisEdu Project Folder\BiologyLessons")
TRANSLATIONS_FILE = Path(r"c:\Users\Peter\pkang6689-pixel.github.io\ArisEdu Project Folder\scripts\global_translations.js")

# Complete translations for summary content
SUMMARY_TRANSLATIONS = {
    # === LESSON 1.1: Introduction to Biology ===
    "Key Concepts: Introduction to Biology": "关键概念：生物学导论",
    "What is Biology?": "什么是生物学？",
    "Biology is the scientific study of life and living organisms.": "生物学是对生命和生物的科学研究。",
    "It examines how living things function, grow, reproduce, and interact with their environment.": "它研究生物如何运作、生长、繁殖以及与环境相互作用。",
    "Scope of Biology": "生物学的范围",
    "From microscopic bacteria to massive ecosystems, biology covers all scales of life.": "从微观细菌到庞大的生态系统，生物学涵盖了所有生命的尺度。",
    "Why Study Biology?": "为什么要学习生物学？",
    "Understanding health and disease": "了解健康和疾病",
    "Developing medicines and treatments": "开发药物和治疗方法",
    "Addressing environmental challenges": "应对环境挑战",
    "Improving agriculture and food production": "改善农业和粮食生产",
    
    # === LESSON 1.2: The Science of Life ===
    "Key Concepts: The Science of Life": "关键概念：生命科学",
    "Biology as an Interdisciplinary Science": "生物学作为跨学科科学",
    "Biology connects with chemistry, physics, and mathematics to explain life processes.": "生物学与化学、物理学和数学相结合来解释生命过程。",
    "Core Principles": "核心原则",
    "All living things are made of cells": "所有生物都由细胞组成",
    "Living things obtain and use energy": "生物获取并使用能量",
    "Living things grow and develop": "生物生长和发育",
    "Living things reproduce": "生物繁殖",
    "Living things respond to their environment": "生物对环境作出反应",
    "Living things adapt and evolve": "生物适应和进化",
    
    # === LESSON 1.3: The Nature of Science ===
    "Key Concepts: The Nature of Science": "关键概念：科学的本质",
    "Characteristics of Science": "科学的特征",
    "Science is a way of knowing about the natural world based on evidence and logical reasoning.": "科学是一种基于证据和逻辑推理来认识自然界的方法。",
    "Science is a way of knowing about the natural world based on": "科学是一种基于",
    "evidence": "证据",
    "and": "和",
    "logical reasoning": "逻辑推理",
    "Empirical": "实证性",
    "Based on observation and experimentation": "基于观察和实验",
    "Testable": "可检验性",
    "Claims can be verified or falsified": "主张可以被验证或证伪",
    "Tentative": "暂时性",
    "Conclusions can change with new evidence": "结论可以随新证据改变",
    "Objective": "客观性",
    "Minimizes personal bias": "尽量减少个人偏见",
    "Theory vs. Law": "理论与定律",
    "Scientific Theory": "科学理论",
    "A well-tested explanation supported by extensive evidence (e.g., cell theory, evolution)": "经过充分验证并有大量证据支持的解释（如细胞学说、进化论）",
    "Scientific Law": "科学定律",
    "A description of a natural phenomenon that always occurs (e.g., law of gravity)": "对总是发生的自然现象的描述（如万有引力定律）",
    
    # === LESSON 1.4: Characteristics of Life ===
    "Key Concepts: Characteristics of Life": "关键概念：生命的特征",
    "The 7 Characteristics of Life": "生命的7个特征",
    "All living things share these characteristics:": "所有生物都具有这些特征：",
    "Organization": "组织性",
    "Made of cells, the basic unit of life": "由细胞组成，细胞是生命的基本单位",
    "Metabolism": "新陈代谢",
    "Chemical reactions to obtain and use energy": "获取和使用能量的化学反应",
    "Homeostasis": "稳态",
    "Maintaining stable internal conditions": "维持稳定的内部条件",
    "Growth": "生长",
    "An increase in size and/or number of cells": "细胞大小和/或数量的增加",
    "Reproduction": "繁殖",
    "The process of producing offspring": "产生后代的过程",
    "Response": "应激性",
    "Reacting to stimuli in the environment": "对环境中的刺激作出反应",
    "Adaptation": "适应性",
    "Evolving over generations to better survive": "通过世代进化以更好地生存",
    
    # === LESSON 1.5: Levels of Biological Organization ===
    "Key Concepts: Levels of Biological Organization": "关键概念：生物组织层次",
    "Hierarchy of Life": "生命的层次结构",
    "Life is organized in a hierarchical structure:": "生命按层次结构组织：",
    "Atom": "原子",
    "Smallest unit of matter": "物质的最小单位",
    "Molecule": "分子",
    "Two or more atoms bonded together": "两个或多个原子结合在一起",
    "Organelle": "细胞器",
    "Specialized structures within cells": "细胞内的专门结构",
    "Cell": "细胞",
    "Basic unit of life": "生命的基本单位",
    "Tissue": "组织",
    "Similar cells working together": "相似细胞共同工作",
    "Organ": "器官",
    "Different tissues working together": "不同组织共同工作",
    "Organ System": "器官系统",
    "Organs working together": "器官共同工作",
    "Organism": "生物体",
    "An individual living thing": "单个生物个体",
    "Population": "种群",
    "Members of one species in an area": "一个地区内同一物种的成员",
    "Community": "群落",
    "All populations in an area": "一个地区的所有种群",
    "Ecosystem": "生态系统",
    "Community plus physical environment": "群落加上物理环境",
    "Biosphere": "生物圈",
    "All life on Earth": "地球上所有的生命",
    
    # === LESSON 1.6: Branches of Biology ===
    "Key Concepts: Branches of Biology": "关键概念：生物学分支",
    "Major Branches": "主要分支",
    "Biology is divided into many specialized fields:": "生物学分为许多专业领域：",
    "Botany": "植物学",
    "Study of plants": "研究植物",
    "Zoology": "动物学",
    "Study of animals": "研究动物",
    "Microbiology": "微生物学",
    "Study of microorganisms": "研究微生物",
    "Genetics": "遗传学",
    "Study of heredity and genes": "研究遗传和基因",
    "Ecology": "生态学",
    "Study of organisms and their environments": "研究生物及其环境",
    "Cell Biology": "细胞生物学",
    "Study of cell structure and function": "研究细胞结构和功能",
    "Biochemistry": "生物化学",
    "Study of chemical processes in living things": "研究生物体内的化学过程",
    "Marine Biology": "海洋生物学",
    "Study of ocean organisms and ecosystems": "研究海洋生物和生态系统",
    "Immunology": "免疫学",
    "Study of the immune system": "研究免疫系统",
    
    # === LESSON 1.7: Careers in Biology ===
    "Key Concepts: Careers in Biology": "关键概念：生物学职业",
    "Career Paths": "职业道路",
    "A biology degree opens many career opportunities:": "生物学学位开辟了许多职业机会：",
    "Healthcare": "医疗保健",
    "Doctor, nurse, pharmacist": "医生、护士、药剂师",
    "Research": "研究",
    "Laboratory scientist, research professor": "实验室科学家、研究教授",
    "Environmental": "环境",
    "Conservation biologist, environmental consultant": "保护生物学家、环境顾问",
    "Biotechnology": "生物技术",
    "Genetic engineer, biotech researcher": "基因工程师、生物技术研究员",
    "Agriculture": "农业",
    "Agricultural scientist, food scientist": "农业科学家、食品科学家",
    "Forensics": "法医学",
    "Forensic biologist, crime scene investigator": "法医生物学家、犯罪现场调查员",
    
    # === LESSON 2.1: Matter and Atomic Structure ===
    "Key Concepts: Matter and Atomic Structure": "关键概念：物质和原子结构",
    "Basic Chemistry": "基础化学",
    "Understanding matter is essential for understanding life:": "理解物质对于理解生命至关重要：",
    "Matter": "物质",
    "Anything that has mass and takes up space": "具有质量并占据空间的任何东西",
    "Atoms": "原子",
    "Building blocks of matter": "物质的组成单元",
    "Elements": "元素",
    "Pure substances made of one type of atom": "由一种原子组成的纯物质",
    "Compounds": "化合物",
    "Substances made of two or more elements": "由两种或多种元素组成的物质",
    "Atomic Structure": "原子结构",
    "Protons": "质子",
    "Positive charge, in nucleus": "正电荷，位于原子核中",
    "Neutrons": "中子",
    "No charge, in nucleus": "无电荷，位于原子核中",
    "Electrons": "电子",
    "Negative charge, orbit nucleus": "负电荷，围绕原子核运动",
    
    # === LESSON 2.2: Water and Its Solutions ===
    "Key Concepts: Water and Its Solutions": "关键概念：水及其溶液",
    "Properties of Water": "水的性质",
    "Water is essential for life due to its unique properties:": "水由于其独特性质而对生命至关重要：",
    "Polarity": "极性",
    "Uneven distribution of charge": "电荷分布不均匀",
    "Hydrogen Bonding": "氢键",
    "Attraction between water molecules": "水分子之间的吸引力",
    "High Heat Capacity": "高比热容",
    "Resists temperature changes": "抵抗温度变化",
    "Universal Solvent": "万能溶剂",
    "Dissolves many substances": "溶解许多物质",
    "Cohesion and Adhesion": "内聚力和附着力",
    "Water molecules stick together and to surfaces": "水分子相互粘附并附着在表面",
    
    # === LESSON 2.3: The Building Blocks of Life ===
    "Key Concepts: The Building Blocks of Life": "关键概念：生命的组成单元",
    "Carbon-Based Molecules": "碳基分子",
    "Life is based on carbon compounds called organic molecules:": "生命以称为有机分子的碳化合物为基础：",
    "Carbohydrates": "碳水化合物",
    "Energy source (sugars, starches)": "能量来源（糖、淀粉）",
    "Lipids": "脂质",
    "Energy storage, cell membranes (fats, oils)": "能量储存、细胞膜（脂肪、油）",
    "Proteins": "蛋白质",
    "Structure, enzymes, transport (amino acids)": "结构、酶、运输（氨基酸）",
    "Nucleic Acids": "核酸",
    "Genetic information (DNA, RNA)": "遗传信息（DNA、RNA）",
    
    # === LESSON 2.4: Chemical Reactions and Enzymes ===
    "Key Concepts: Chemical Reactions and Enzymes": "关键概念：化学反应和酶",
    "Chemical Reactions in Life": "生命中的化学反应",
    "Living things rely on chemical reactions:": "生物依赖化学反应：",
    "Reactants": "反应物",
    "Starting materials": "起始物质",
    "Products": "产物",
    "End results of reaction": "反应的最终结果",
    "Activation Energy": "活化能",
    "Energy needed to start reaction": "启动反应所需的能量",
    "Enzymes": "酶",
    "Biological catalysts that speed up reactions:": "加速反应的生物催化剂：",
    "Highly specific": "高度特异性",
    "Reusable": "可重复使用",
    "Not consumed in reactions": "在反应中不被消耗",
    "Affected by temperature and pH": "受温度和pH影响",
    
    # === LESSON 2.5: Chemical Energy and ATP ===
    "Key Concepts: Chemical Energy and ATP": "关键概念：化学能和ATP",
    "Energy in Living Systems": "生命系统中的能量",
    "Cells need energy to perform work:": "细胞需要能量来做功：",
    "ATP (Adenosine Triphosphate)": "ATP（三磷酸腺苷）",
    "Main energy currency of cells": "细胞的主要能量货币",
    "Energy is released when ATP loses a phosphate group": "当ATP失去一个磷酸基团时释放能量",
    "ATP → ADP + Energy": "ATP → ADP + 能量",
    "ATP can be regenerated from ADP": "ATP可以从ADP再生",
    
    # === LESSON 2.6: Energy Flow in Living Systems ===
    "Key Concepts: Energy Flow in Living Systems": "关键概念：生命系统中的能量流动",
    "Energy Transformations": "能量转换",
    "Energy flows through living systems:": "能量流经生命系统：",
    "Photosynthesis": "光合作用",
    "Light energy → Chemical energy (glucose)": "光能 → 化学能（葡萄糖）",
    "Cellular Respiration": "细胞呼吸",
    "Chemical energy (glucose) → ATP": "化学能（葡萄糖）→ ATP",
    "Energy flows one way through ecosystems": "能量单向流经生态系统",
    "Matter cycles through ecosystems": "物质在生态系统中循环",
    
    # === LESSON 3.1: Cell Discovery and Theory ===
    "Key Concepts: Cell Discovery and Theory": "关键概念：细胞发现与学说",
    "History of Cell Discovery": "细胞发现的历史",
    "The cell theory was developed over time:": "细胞学说是随时间发展的：",
    "Robert Hooke (1665)": "罗伯特·胡克（1665）",
    "First observed cells in cork": "首次在软木中观察到细胞",
    "Anton van Leeuwenhoek": "安东·范·列文虎克",
    "First to see living cells": "首次看到活细胞",
    "Matthias Schleiden (1838)": "马蒂亚斯·施莱登（1838）",
    "Plants are made of cells": "植物由细胞组成",
    "Theodor Schwann (1839)": "西奥多·施旺（1839）",
    "Animals are made of cells": "动物由细胞组成",
    "Rudolf Virchow (1855)": "鲁道夫·菲尔绍（1855）",
    "Cells come from existing cells": "细胞来自现有细胞",
    "Cell Theory": "细胞学说",
    "All living things are made of cells": "所有生物都由细胞组成",
    "Cells are the basic unit of structure and function": "细胞是结构和功能的基本单位",
    "All cells come from pre-existing cells": "所有细胞都来自先前存在的细胞",
    
    # === LESSON 3.2: Prokaryotic vs. Eukaryotic Cells ===
    "Key Concepts: Prokaryotic vs. Eukaryotic Cells": "关键概念：原核细胞与真核细胞",
    "Two Types of Cells": "两种类型的细胞",
    "Cells are classified as prokaryotic or eukaryotic:": "细胞分为原核细胞和真核细胞：",
    "Prokaryotic Cells": "原核细胞",
    "No nucleus": "无细胞核",
    "No membrane-bound organelles": "无膜结合细胞器",
    "Smaller and simpler": "更小、更简单",
    "Examples: bacteria, archaea": "例如：细菌、古菌",
    "Eukaryotic Cells": "真核细胞",
    "Have a nucleus": "有细胞核",
    "Have membrane-bound organelles": "有膜结合细胞器",
    "Larger and more complex": "更大、更复杂",
    "Examples: plants, animals, fungi": "例如：植物、动物、真菌",
    
    # === LESSON 3.3: Cell Structure and Function ===
    "Key Concepts: Cell Structure and Function": "关键概念：细胞结构与功能",
    "Cell Organelles": "细胞器",
    "Each organelle has a specific function:": "每个细胞器都有特定功能：",
    "Nucleus": "细胞核",
    "Contains DNA, controls cell activities": "包含DNA，控制细胞活动",
    "Mitochondria": "线粒体",
    "Produces ATP (cellular respiration)": "产生ATP（细胞呼吸）",
    "Ribosomes": "核糖体",
    "Protein synthesis": "蛋白质合成",
    "Endoplasmic Reticulum (ER)": "内质网",
    "Protein and lipid processing": "蛋白质和脂质加工",
    "Golgi Apparatus": "高尔基体",
    "Modifies and packages proteins": "修饰和包装蛋白质",
    "Lysosomes": "溶酶体",
    "Digests waste and foreign materials": "消化废物和外来物质",
    "Chloroplasts (plants only)": "叶绿体（仅植物）",
    "Photosynthesis": "光合作用",
    "Cell Wall (plants only)": "细胞壁（仅植物）",
    "Provides structure and support": "提供结构和支撑",
    "Vacuole": "液泡",
    "Storage of water and nutrients": "储存水和营养物质",
    
    # === LESSON 3.4: The Plasma Membrane ===
    "Key Concepts: The Plasma Membrane": "关键概念：质膜",
    "Structure of the Plasma Membrane": "质膜的结构",
    "The plasma membrane controls what enters and exits the cell:": "质膜控制进出细胞的物质：",
    "Phospholipid Bilayer": "磷脂双分子层",
    "Two layers of phospholipids": "两层磷脂",
    "Fluid Mosaic Model": "流动镶嵌模型",
    "Proteins embedded in the membrane": "蛋白质嵌入膜中",
    "Selectively Permeable": "选择性渗透",
    "Only certain substances can pass through": "只有某些物质可以通过",
    "Functions": "功能",
    "Protection": "保护",
    "Transport": "运输",
    "Cell communication": "细胞通讯",
    
    # === LESSON 3.5: Cellular Transport ===
    "Key Concepts: Cellular Transport": "关键概念：细胞运输",
    "Types of Transport": "运输类型",
    "Substances move in and out of cells in different ways:": "物质以不同方式进出细胞：",
    "Passive Transport": "被动运输",
    "No energy required": "不需要能量",
    "Diffusion": "扩散",
    "Movement from high to low concentration": "从高浓度向低浓度移动",
    "Osmosis": "渗透",
    "Diffusion of water": "水的扩散",
    "Facilitated Diffusion": "易化扩散",
    "Uses transport proteins": "使用转运蛋白",
    "Active Transport": "主动运输",
    "Requires energy (ATP)": "需要能量（ATP）",
    "Movement against concentration gradient": "逆浓度梯度移动",
    "Endocytosis and Exocytosis": "内吞和外排",
    "Moving large molecules": "移动大分子",
    
    # === LESSON 3.6: Structures and Organelles ===
    "Key Concepts: Structures and Organelles": "关键概念：结构与细胞器",
    "Specialized Structures": "专门结构",
    "Cells have many specialized structures:": "细胞有许多专门结构：",
    "Cytoskeleton": "细胞骨架",
    "Network of protein fibers": "蛋白质纤维网络",
    "Provides shape and support": "提供形状和支撑",
    "Enables movement": "使运动成为可能",
    "Centrioles": "中心粒",
    "Important for cell division": "对细胞分裂很重要",
    "Cilia and Flagella": "纤毛和鞭毛",
    "Used for movement": "用于运动",
    
    # === LESSON 4.1: Photosynthesis ===
    "Key Concepts: Photosynthesis": "关键概念：光合作用",
    "The Process of Photosynthesis": "光合作用过程",
    "Plants convert light energy to chemical energy:": "植物将光能转化为化学能：",
    "Location": "位置",
    "Chloroplasts": "叶绿体",
    "Equation": "方程式",
    "6CO₂ + 6H₂O + Light → C₆H₁₂O₆ + 6O₂": "6CO₂ + 6H₂O + 光 → C₆H₁₂O₆ + 6O₂",
    "Light Reactions": "光反应",
    "Occur in thylakoid membranes": "发生在类囊体膜中",
    "Produce ATP and NADPH": "产生ATP和NADPH",
    "Calvin Cycle": "卡尔文循环",
    "Occurs in stroma": "发生在基质中",
    "Produces glucose": "产生葡萄糖",
    
    # === LESSON 4.2: Cellular Respiration ===
    "Key Concepts: Cellular Respiration": "关键概念：细胞呼吸",
    "The Process of Cellular Respiration": "细胞呼吸过程",
    "Cells break down glucose to release energy:": "细胞分解葡萄糖释放能量：",
    "Mitochondria": "线粒体",
    "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP": "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP",
    "Glycolysis": "糖酵解",
    "Occurs in cytoplasm": "发生在细胞质中",
    "Produces 2 ATP": "产生2个ATP",
    "Krebs Cycle": "克雷布斯循环",
    "Occurs in mitochondrial matrix": "发生在线粒体基质中",
    "Electron Transport Chain": "电子传递链",
    "Produces most ATP (about 34)": "产生大部分ATP（约34个）",
    
    # === LESSON 4.3: Fermentation ===
    "Key Concepts: Fermentation": "关键概念：发酵",
    "Anaerobic Respiration": "厌氧呼吸",
    "When oxygen is not available, cells use fermentation:": "当没有氧气时，细胞使用发酵：",
    "Lactic Acid Fermentation": "乳酸发酵",
    "Occurs in muscles during intense exercise": "在剧烈运动期间发生在肌肉中",
    "Produces lactic acid": "产生乳酸",
    "Alcoholic Fermentation": "酒精发酵",
    "Occurs in yeast and some bacteria": "发生在酵母和某些细菌中",
    "Produces ethanol and CO₂": "产生乙醇和CO₂",
    "Both processes produce only 2 ATP": "两种过程只产生2个ATP",
    "Less efficient than aerobic respiration": "效率低于有氧呼吸",
    
    # === LESSON 4.4: How Organisms Obtain Energy ===
    "Key Concepts: How Organisms Obtain Energy": "关键概念：生物如何获取能量",
    "Energy Sources": "能量来源",
    "Organisms obtain energy in different ways:": "生物以不同方式获取能量：",
    "Autotrophs": "自养生物",
    "Make their own food": "自己制造食物",
    "Photoautotrophs use light": "光能自养生物使用光",
    "Chemoautotrophs use chemicals": "化能自养生物使用化学物质",
    "Heterotrophs": "异养生物",
    "Consume other organisms": "消耗其他生物",
    "Herbivores eat plants": "草食动物吃植物",
    "Carnivores eat animals": "肉食动物吃动物",
    "Omnivores eat both": "杂食动物两者都吃",
    "Decomposers": "分解者",
    "Break down dead matter": "分解死亡物质",
    "Recycle nutrients": "回收营养物质",
    
    # === LESSON 4.5: Mitosis ===
    "Key Concepts: Mitosis": "关键概念：有丝分裂",
    "Cell Division": "细胞分裂",
    "Mitosis produces two identical daughter cells:": "有丝分裂产生两个相同的子细胞：",
    "Interphase": "间期",
    "Cell grows and DNA replicates": "细胞生长，DNA复制",
    "Prophase": "前期",
    "Chromosomes condense, nuclear envelope breaks down": "染色体凝聚，核膜分解",
    "Metaphase": "中期",
    "Chromosomes align at cell equator": "染色体排列在细胞赤道板",
    "Anaphase": "后期",
    "Sister chromatids separate": "姐妹染色单体分离",
    "Telophase": "末期",
    "Nuclear envelopes reform": "核膜重新形成",
    "Cytokinesis": "胞质分裂",
    "Cytoplasm divides": "细胞质分裂",
    
    # === LESSON 4.6: The Cell Cycle and Cancer ===
    "Key Concepts: The Cell Cycle and Cancer": "关键概念：细胞周期与癌症",
    "Cell Cycle Regulation": "细胞周期调控",
    "The cell cycle is carefully controlled:": "细胞周期被严格控制：",
    "Checkpoints": "检查点",
    "Control points that ensure proper division": "确保正确分裂的控制点",
    "Cyclins and CDKs": "周期蛋白和CDK",
    "Proteins that regulate the cycle": "调节周期的蛋白质",
    "Cancer": "癌症",
    "Uncontrolled cell division": "不受控制的细胞分裂",
    "Mutations in cell cycle genes": "细胞周期基因的突变",
    "Oncogenes": "癌基因",
    "Promote cell division": "促进细胞分裂",
    "Tumor Suppressor Genes": "肿瘤抑制基因",
    "Inhibit cell division": "抑制细胞分裂",
    
    # === LESSON 5.1: Introduction to Ecology ===
    "Key Concepts: Introduction to Ecology": "关键概念：生态学导论",
    "What is Ecology?": "什么是生态学？",
    "Ecology studies interactions between organisms and their environment:": "生态学研究生物与其环境之间的相互作用：",
    "Biotic Factors": "生物因素",
    "Living components": "有生命的成分",
    "Abiotic Factors": "非生物因素",
    "Non-living components": "无生命的成分",
    "Levels of Ecological Organization": "生态组织层次",
    "Individual → Population → Community → Ecosystem → Biome → Biosphere": "个体 → 种群 → 群落 → 生态系统 → 生物群落 → 生物圈",
    
    # === LESSON 5.2: Producers, Consumers, and Decomposers ===
    "Key Concepts: Producers, Consumers, and Decomposers": "关键概念：生产者、消费者和分解者",
    "Trophic Levels": "营养级",
    "Organisms are classified by how they obtain energy:": "生物按获取能量的方式分类：",
    "Producers (Autotrophs)": "生产者（自养生物）",
    "Make their own food through photosynthesis": "通过光合作用自己制造食物",
    "Primary Consumers (Herbivores)": "初级消费者（草食动物）",
    "Eat producers": "吃生产者",
    "Secondary Consumers (Carnivores)": "次级消费者（肉食动物）",
    "Eat primary consumers": "吃初级消费者",
    "Tertiary Consumers": "三级消费者",
    "Top predators": "顶级捕食者",
    "Break down dead organisms": "分解死亡生物",
    "Return nutrients to the soil": "将营养物质归还土壤",
    
    # === LESSON 5.3: Trophic Levels and Energy Transfer ===
    "Key Concepts: Trophic Levels and Energy Transfer": "关键概念：营养级和能量传递",
    "Energy Transfer": "能量传递",
    "Energy flows through ecosystems:": "能量流经生态系统：",
    "10% Rule": "10%法则",
    "Only about 10% of energy transfers to the next level": "只有约10%的能量传递到下一级",
    "Energy Pyramids": "能量金字塔",
    "Show energy at each trophic level": "显示每个营养级的能量",
    "Energy Lost": "能量损失",
    "Lost as heat through metabolism": "通过新陈代谢以热量形式损失",
    "Used for life processes": "用于生命过程",
    
    # === LESSON 5.4: Food Chains and Food Webs ===
    "Key Concepts: Food Chains and Food Webs": "关键概念：食物链和食物网",
    "Food Chains": "食物链",
    "Show a single pathway of energy flow:": "显示能量流动的单一途径：",
    "Producer → Primary Consumer → Secondary Consumer → Tertiary Consumer": "生产者 → 初级消费者 → 次级消费者 → 三级消费者",
    "Food Webs": "食物网",
    "Show interconnected food chains:": "显示相互连接的食物链：",
    "More realistic representation": "更真实的表现",
    "Show complex feeding relationships": "显示复杂的摄食关系",
    
    # === LESSON 5.5: Energy in Ecosystems ===
    "Key Concepts: Energy in Ecosystems": "关键概念：生态系统中的能量",
    "Energy Flow": "能量流动",
    "Understanding energy in ecosystems:": "理解生态系统中的能量：",
    "Sun is the ultimate energy source": "太阳是最终的能量来源",
    "Energy flows one direction (up trophic levels)": "能量单向流动（向上营养级）",
    "Matter is recycled but energy is not": "物质被循环但能量不循环",
    "NPP (Net Primary Productivity)": "NPP（净初级生产力）",
    "Energy available to consumers": "可供消费者使用的能量",
    
    # === LESSON 5.6: Biodiversity ===
    "Key Concepts: Biodiversity": "关键概念：生物多样性",
    "What is Biodiversity?": "什么是生物多样性？",
    "The variety of life in an area:": "一个地区生命的多样性：",
    "Genetic Diversity": "遗传多样性",
    "Variety of genes within a species": "物种内基因的多样性",
    "Species Diversity": "物种多样性",
    "Variety of species in an ecosystem": "生态系统中物种的多样性",
    "Ecosystem Diversity": "生态系统多样性",
    "Variety of ecosystems in a region": "一个地区生态系统的多样性",
    "Importance of Biodiversity": "生物多样性的重要性",
    "Ecosystem stability": "生态系统稳定性",
    "Medicine and resources": "医药和资源",
    "Food security": "食品安全",
    
    # === LESSON 6.1: The Carbon and Water Cycles ===
    "Key Concepts: The Carbon and Water Cycles": "关键概念：碳循环和水循环",
    "Carbon Cycle": "碳循环",
    "Carbon moves through ecosystems:": "碳在生态系统中移动：",
    "Enters living things through photosynthesis (CO₂)": "通过光合作用进入生物（CO₂）",
    "Released through respiration, decomposition, combustion": "通过呼吸、分解、燃烧释放",
    "Stored in fossil fuels, oceans, and organisms": "储存在化石燃料、海洋和生物中",
    "Water Cycle": "水循环",
    "Water moves through Earth's systems:": "水在地球系统中移动：",
    "Evaporation": "蒸发",
    "Water becomes water vapor": "水变成水蒸气",
    "Condensation": "凝结",
    "Water vapor forms clouds": "水蒸气形成云",
    "Precipitation": "降水",
    "Water falls as rain/snow": "水以雨/雪形式降落",
    "Collection": "汇集",
    "Water collects in bodies of water": "水汇集在水体中",
    
    # === LESSON 6.2: Nitrogen and Phosphorus Cycles ===
    "Key Concepts: Nitrogen and Phosphorus Cycles": "关键概念：氮循环和磷循环",
    "Nitrogen Cycle": "氮循环",
    "Nitrogen is essential for proteins and DNA:": "氮对蛋白质和DNA至关重要：",
    "Nitrogen Fixation": "固氮作用",
    "Bacteria convert N₂ to usable forms": "细菌将N₂转化为可用形式",
    "Nitrification": "硝化作用",
    "Ammonia converted to nitrates": "氨转化为硝酸盐",
    "Assimilation": "同化作用",
    "Organisms absorb nitrogen": "生物吸收氮",
    "Denitrification": "反硝化作用",
    "Nitrates converted back to N₂": "硝酸盐转化回N₂",
    "Phosphorus Cycle": "磷循环",
    "Phosphorus is essential for ATP and DNA:": "磷对ATP和DNA至关重要：",
    "No atmospheric component": "没有大气成分",
    "Released from rocks by weathering": "通过风化从岩石中释放",
    "Absorbed by plants": "被植物吸收",
    "Returned to soil by decomposition": "通过分解归还土壤",
    
    # === LESSON 6.3: Biogeochemical Cycles ===
    "Key Concepts: Biogeochemical Cycles": "关键概念：生物地球化学循环",
    "Cycling of Matter": "物质循环",
    "Matter cycles through ecosystems:": "物质在生态系统中循环：",
    "All biogeochemical cycles involve:": "所有生物地球化学循环涉及：",
    "Biological processes": "生物过程",
    "Geological processes": "地质过程",
    "Chemical processes": "化学过程",
    "Human Impact": "人类影响",
    "Human activities affect cycles:": "人类活动影响循环：",
    "Burning fossil fuels (carbon cycle)": "燃烧化石燃料（碳循环）",
    "Fertilizers (nitrogen cycle)": "化肥（氮循环）",
    "Deforestation (water cycle)": "砍伐森林（水循环）",
    
    # === LESSON 6.4: Population Dynamics ===
    "Key Concepts: Population Dynamics": "关键概念：种群动态",
    "Population Growth": "种群增长",
    "Populations change over time:": "种群随时间变化：",
    "Birth Rate": "出生率",
    "Number of births per unit time": "单位时间内的出生数",
    "Death Rate": "死亡率",
    "Number of deaths per unit time": "单位时间内的死亡数",
    "Immigration": "迁入",
    "Individuals moving in": "个体迁入",
    "Emigration": "迁出",
    "Individuals moving out": "个体迁出",
    "Growth Patterns": "增长模式",
    "Exponential Growth": "指数增长",
    "J-shaped curve, unlimited resources": "J形曲线，无限资源",
    "Logistic Growth": "逻辑斯蒂增长",
    "S-shaped curve, limited resources": "S形曲线，有限资源",
    
    # === LESSON 6.5: Carrying Capacity and Limiting Factors ===
    "Key Concepts: Carrying Capacity and Limiting Factors": "关键概念：承载力和限制因素",
    "Carrying Capacity (K)": "承载力（K）",
    "Maximum population an environment can support:": "环境能够支持的最大种群数量：",
    "Determined by available resources": "由可用资源决定",
    "Population oscillates around K": "种群在K附近波动",
    "Limiting Factors": "限制因素",
    "Factors that limit population growth:": "限制种群增长的因素：",
    "Density-Dependent": "密度依赖性",
    "Competition, predation, disease": "竞争、捕食、疾病",
    "Density-Independent": "密度非依赖性",
    "Weather, natural disasters": "天气、自然灾害",
    
    # === LESSON 6.6: Population Regulation ===
    "Key Concepts: Population Regulation": "关键概念：种群调节",
    "Population Control": "种群控制",
    "Populations are regulated by:": "种群受以下因素调节：",
    "Top-Down Regulation": "自上而下调节",
    "Predators control prey populations": "捕食者控制猎物种群",
    "Bottom-Up Regulation": "自下而上调节",
    "Resources control populations": "资源控制种群",
    "Feedback Mechanisms": "反馈机制",
    "Negative Feedback": "负反馈",
    "Keeps population near carrying capacity": "使种群保持在承载力附近",
    "Positive Feedback": "正反馈",
    "Can lead to population crashes": "可能导致种群崩溃",
    
    # === LESSON 7.1: Community Ecology ===
    "Key Concepts: Community Ecology": "关键概念：群落生态学",
    "Community Interactions": "群落相互作用",
    "Species in a community interact:": "群落中的物种相互作用：",
    "Competition": "竞争",
    "Species compete for same resources": "物种竞争相同资源",
    "Predation": "捕食",
    "One species hunts another": "一个物种捕食另一个",
    "Symbiosis": "共生",
    "Close relationships between species": "物种之间的密切关系",
    "Mutualism": "互利共生",
    "Both benefit": "双方都受益",
    "Commensalism": "偏利共生",
    "One benefits, other unaffected": "一方受益，另一方不受影响",
    "Parasitism": "寄生",
    "One benefits, other harmed": "一方受益，另一方受害",
    
    # === LESSON 7.2: Competition and Predation ===
    "Key Concepts: Competition and Predation": "关键概念：竞争与捕食",
    "Types of Competition": "竞争类型",
    "Competition occurs when resources are limited:": "当资源有限时发生竞争：",
    "Intraspecific Competition": "种内竞争",
    "Between members of same species": "同一物种成员之间",
    "Interspecific Competition": "种间竞争",
    "Between different species": "不同物种之间",
    "Competitive Exclusion Principle": "竞争排斥原理",
    "Two species cannot occupy the same niche": "两个物种不能占据相同的生态位",
    "Predator-Prey Relationships": "捕食者-猎物关系",
    "Predator and prey populations affect each other": "捕食者和猎物种群相互影响",
    "Cycles of population change": "种群变化的周期",
    
    # === LESSON 7.3: Symbiosis and Species Interactions ===
    "Key Concepts: Symbiosis and Species Interactions": "关键概念：共生与物种相互作用",
    "Types of Symbiosis": "共生类型",
    "Symbiotic relationships:": "共生关系：",
    "Example: bees and flowers": "例如：蜜蜂和花",
    "Example: barnacles on whales": "例如：鲸鱼身上的藤壶",
    "Example: tapeworms in intestines": "例如：肠道中的绦虫",
    "Coevolution": "协同进化",
    "Species evolve together": "物种共同进化",
    "Predator and prey adaptations": "捕食者和猎物的适应",
    
    # === LESSON 7.4: Ecological Succession ===
    "Key Concepts: Ecological Succession": "关键概念：生态演替",
    "What is Succession?": "什么是演替？",
    "Gradual change in species composition:": "物种组成的逐渐变化：",
    "Pioneer Species": "先锋物种",
    "First species to colonize an area": "最先定居某地区的物种",
    "Climax Community": "顶极群落",
    "Stable, mature community": "稳定、成熟的群落",
    "Types of Succession": "演替类型",
    "Primary Succession": "初级演替",
    "Occurs on bare rock or new surfaces": "发生在裸露岩石或新表面",
    "Secondary Succession": "次级演替",
    "Occurs after disturbance, soil present": "扰动后发生，土壤存在",
    "Faster than primary succession": "比初级演替更快",
    
    # === LESSON 7.5: Primary and Secondary Succession ===
    "Key Concepts: Primary and Secondary Succession": "关键概念：初级演替和次级演替",
    "Primary Succession Stages": "初级演替阶段",
    "Starting from bare rock:": "从裸露岩石开始：",
    "Lichens colonize first": "地衣首先定居",
    "Mosses grow": "苔藓生长",
    "Soil develops": "土壤发育",
    "Grasses and shrubs establish": "草和灌木建立",
    "Trees eventually dominate": "树木最终占主导",
    "Secondary Succession Stages": "次级演替阶段",
    "After a disturbance:": "扰动后：",
    "Annual plants appear first": "一年生植物首先出现",
    "Perennial plants follow": "多年生植物随后",
    "Shrubs and saplings grow": "灌木和幼树生长",
    "Forest returns": "森林恢复",
    
    # === LESSON 7.6: Environmental Biology ===
    "Key Concepts: Environmental Biology": "关键概念：环境生物学",
    "Environmental Issues": "环境问题",
    "Human impacts on the environment:": "人类对环境的影响：",
    "Pollution": "污染",
    "Air, water, and soil contamination": "空气、水和土壤污染",
    "Climate Change": "气候变化",
    "Global temperature increase": "全球温度上升",
    "Habitat Loss": "栖息地丧失",
    "Destruction of natural areas": "自然区域的破坏",
    "Overexploitation": "过度开发",
    "Using resources faster than replacement": "使用资源的速度超过补充速度",
    "Conservation Solutions": "保护解决方案",
    "Sustainable practices": "可持续做法",
    "Protected areas": "保护区",
    "Species recovery programs": "物种恢复计划",
    
    # === LESSON 8.1: Terrestrial Biomes ===
    "Key Concepts: Terrestrial Biomes": "关键概念：陆地生物群落",
    "Major Land Biomes": "主要陆地生物群落",
    "Biomes are large regions with similar climate and organisms:": "生物群落是具有相似气候和生物的大区域：",
    "Tropical Rainforest": "热带雨林",
    "Hot, wet, high biodiversity": "炎热、潮湿、高生物多样性",
    "Desert": "沙漠",
    "Hot or cold, very dry": "炎热或寒冷、非常干燥",
    "Grassland": "草原",
    "Moderate rainfall, grasses dominate": "中等降雨、草类占主导",
    "Temperate Forest": "温带森林",
    "Four seasons, deciduous trees": "四季分明、落叶树木",
    "Taiga (Boreal Forest)": "针叶林（北方森林）",
    "Cold, coniferous trees": "寒冷、针叶树",
    "Tundra": "苔原",
    "Very cold, permafrost": "非常寒冷、永久冻土",
    
    # === LESSON 8.2: Aquatic Ecosystems ===
    "Key Concepts: Aquatic Ecosystems": "关键概念：水生生态系统",
    "Types of Aquatic Ecosystems": "水生生态系统类型",
    "Freshwater Ecosystems": "淡水生态系统",
    "Lakes, ponds, rivers, streams": "湖泊、池塘、河流、溪流",
    "Marine Ecosystems": "海洋生态系统",
    "Oceans, coral reefs, estuaries": "海洋、珊瑚礁、河口",
    "Zones in Aquatic Ecosystems": "水生生态系统中的分区",
    "Photic Zone": "光合作用带",
    "Light penetrates, photosynthesis occurs": "光线穿透、光合作用发生",
    "Aphotic Zone": "无光带",
    "No light, deep water": "无光、深水区",
    "Intertidal Zone": "潮间带",
    "Area between high and low tide": "高潮和低潮之间的区域",
    
    # === LESSON 8.3: Threats to Biodiversity ===
    "Key Concepts: Threats to Biodiversity": "关键概念：生物多样性的威胁",
    "Major Threats": "主要威胁",
    "Biodiversity is declining due to:": "生物多样性正在下降，原因是：",
    "Habitat Destruction": "栖息地破坏",
    "Loss of natural areas": "自然区域的丧失",
    "Invasive Species": "入侵物种",
    "Non-native species outcompete natives": "非本地物种胜过本地物种",
    "Overexploitation of resources": "资源的过度开发",
    "Rising temperatures affect habitats": "温度上升影响栖息地",
    "Air, water, soil contamination": "空气、水、土壤污染",
    
    # === LESSON 8.4: Endangered Species and Conservation Strategies ===
    "Key Concepts: Endangered Species and Conservation Strategies": "关键概念：濒危物种和保护策略",
    "Endangered Species": "濒危物种",
    "Species at risk of extinction:": "面临灭绝风险的物种：",
    "Endangered": "濒危",
    "At high risk of extinction": "灭绝风险高",
    "Vulnerable": "易危",
    "At risk of becoming endangered": "面临濒危风险",
    "Conservation Strategies": "保护策略",
    "Protecting species and habitats:": "保护物种和栖息地：",
    "Protected Areas": "保护区",
    "National parks, reserves": "国家公园、保护区",
    "Captive Breeding": "人工繁殖",
    "Breeding in zoos and facilities": "在动物园和设施中繁殖",
    "Habitat Restoration": "栖息地恢复",
    "Restoring damaged ecosystems": "恢复受损生态系统",
    
    # === LESSON 8.5: Climate Change and Ecosystem Shifts ===
    "Key Concepts: Climate Change and Ecosystem Shifts": "关键概念：气候变化和生态系统变迁",
    "Effects of Climate Change": "气候变化的影响",
    "Climate change affects ecosystems:": "气候变化影响生态系统：",
    "Temperature Changes": "温度变化",
    "Species move to new areas": "物种迁移到新地区",
    "Phenology Changes": "物候变化",
    "Timing of seasonal events shifts": "季节性事件的时间改变",
    "Range Shifts": "分布范围变化",
    "Species distributions change": "物种分布发生变化",
    "Ecosystem Impacts": "生态系统影响",
    "Coral bleaching": "珊瑚白化",
    "Melting ice": "冰层融化",
    "Sea level rise": "海平面上升",
    
    # === LESSON 8.6: Conservation and Sustainable Development ===
    "Key Concepts: Conservation and Sustainable Development": "关键概念：保护与可持续发展",
    "Sustainable Development": "可持续发展",
    "Meeting present needs without compromising future:": "满足当前需求而不损害未来：",
    "Reduce, Reuse, Recycle": "减少、再利用、回收",
    "Minimize waste": "减少废物",
    "Renewable Energy": "可再生能源",
    "Solar, wind, hydroelectric": "太阳能、风能、水电",
    "Sustainable Agriculture": "可持续农业",
    "Farming that preserves resources": "保护资源的农业",
    "Conservation Efforts": "保护工作",
    "International agreements": "国际协议",
    "Local conservation projects": "当地保护项目",
    "Individual actions matter": "个人行动很重要",
    
    # === LESSON 9.1: DNA and RNA ===
    "Key Concepts: DNA and RNA": "关键概念：DNA和RNA",
    "Nucleic Acids": "核酸",
    "DNA and RNA store genetic information:": "DNA和RNA存储遗传信息：",
    "DNA (Deoxyribonucleic Acid)": "DNA（脱氧核糖核酸）",
    "Double helix structure": "双螺旋结构",
    "Contains adenine, thymine, guanine, cytosine": "含有腺嘌呤、胸腺嘧啶、鸟嘌呤、胞嘧啶",
    "Stores genetic information": "存储遗传信息",
    "RNA (Ribonucleic Acid)": "RNA（核糖核酸）",
    "Single-stranded": "单链",
    "Contains uracil instead of thymine": "含有尿嘧啶而不是胸腺嘧啶",
    "mRNA, tRNA, rRNA": "mRNA、tRNA、rRNA",
    
    # === LESSON 9.2: Meiosis and Sexual Reproduction ===
    "Key Concepts: Meiosis and Sexual Reproduction": "关键概念：减数分裂和有性生殖",
    "Meiosis": "减数分裂",
    "Cell division that produces gametes:": "产生配子的细胞分裂：",
    "Produces 4 haploid cells": "产生4个单倍体细胞",
    "Two divisions (meiosis I and II)": "两次分裂（减数分裂I和II）",
    "Crossing over increases genetic diversity": "交叉互换增加遗传多样性",
    "Sexual Reproduction": "有性生殖",
    "Combining genetic material from two parents:": "结合来自两个亲本的遗传物质：",
    "Gametes (egg and sperm)": "配子（卵子和精子）",
    "Fertilization creates zygote": "受精产生受精卵",
    "Offspring have unique combinations": "后代具有独特的组合",
    
    # === LESSON 9.3: Cellular Reproduction ===
    "Key Concepts: Cellular Reproduction": "关键概念：细胞繁殖",
    "Types of Reproduction": "繁殖类型",
    "Cells reproduce in different ways:": "细胞以不同方式繁殖：",
    "Asexual Reproduction": "无性繁殖",
    "One parent, identical offspring": "一个亲本，相同的后代",
    "Binary fission, budding, fragmentation": "二分裂、出芽、断裂",
    "Produces genetically diverse offspring": "产生遗传多样性的后代",
    "Requires two parents (usually)": "通常需要两个亲本",
    "Comparison": "比较",
    "Asexual is faster, sexual is more diverse": "无性繁殖更快，有性繁殖更多样",
    
    # === LESSON 9.4: Microscopy and Cell Imaging ===
    "Key Concepts: Microscopy and Cell Imaging": "关键概念：显微镜术和细胞成像",
    "Types of Microscopes": "显微镜类型",
    "Different microscopes for different purposes:": "不同目的使用不同显微镜：",
    "Light Microscope": "光学显微镜",
    "Uses visible light": "使用可见光",
    "Lower magnification (up to 1000x)": "较低放大倍数（最高1000倍）",
    "Electron Microscope": "电子显微镜",
    "Uses electron beams": "使用电子束",
    "Higher magnification (up to 1,000,000x)": "较高放大倍数（最高1,000,000倍）",
    "TEM shows internal structures": "透射电镜显示内部结构",
    "SEM shows surface details": "扫描电镜显示表面细节",
    
    # === LESSON 10.1: Mendelian Genetics ===
    "Key Concepts: Mendelian Genetics": "关键概念：孟德尔遗传学",
    "Gregor Mendel's Work": "格雷戈尔·孟德尔的研究",
    "Mendel discovered inheritance patterns:": "孟德尔发现了遗传规律：",
    "Law of Segregation": "分离定律",
    "Alleles separate during gamete formation": "等位基因在配子形成时分离",
    "Law of Independent Assortment": "自由组合定律",
    "Genes for different traits sort independently": "不同性状的基因独立分配",
    "Dominant vs. Recessive": "显性与隐性",
    "Dominant alleles mask recessive alleles": "显性等位基因掩盖隐性等位基因",
    "Genotype and Phenotype": "基因型和表型",
    "Genotype: genetic makeup": "基因型：遗传组成",
    "Phenotype: observable traits": "表型：可观察的性状",
    
    # === LESSON 10.2: Non-Mendelian Genetics ===
    "Key Concepts: Non-Mendelian Genetics": "关键概念：非孟德尔遗传学",
    "Exceptions to Mendel's Laws": "孟德尔定律的例外",
    "Some inheritance patterns are more complex:": "一些遗传模式更为复杂：",
    "Incomplete Dominance": "不完全显性",
    "Blended phenotype": "混合表型",
    "Codominance": "共显性",
    "Both alleles fully expressed": "两个等位基因都完全表达",
    "Multiple Alleles": "多等位基因",
    "More than two alleles exist": "存在两个以上的等位基因",
    "Polygenic Traits": "多基因性状",
    "Controlled by multiple genes": "由多个基因控制",
    "Sex-Linked Traits": "伴性遗传性状",
    "Genes on sex chromosomes": "位于性染色体上的基因",
    
    # === LESSON 10.3: DNA Replication, Transcription, and Translation ===
    "Key Concepts: DNA Replication, Transcription, and Translation": "关键概念：DNA复制、转录和翻译",
    "Central Dogma": "中心法则",
    "DNA → RNA → Protein": "DNA → RNA → 蛋白质",
    "DNA Replication": "DNA复制",
    "DNA copies itself:": "DNA复制自身：",
    "Semi-conservative": "半保留复制",
    "Each strand serves as template": "每条链作为模板",
    "Transcription": "转录",
    "DNA → mRNA:": "DNA → mRNA：",
    "Occurs in nucleus": "发生在细胞核中",
    "RNA polymerase reads DNA": "RNA聚合酶读取DNA",
    "Translation": "翻译",
    "mRNA → Protein:": "mRNA → 蛋白质：",
    "Occurs at ribosomes": "发生在核糖体上",
    "tRNA brings amino acids": "tRNA带来氨基酸",
    "Codons specify amino acids": "密码子指定氨基酸",
    
    # === LESSON 10.4: Gene Regulation and Expression ===
    "Key Concepts: Gene Regulation and Expression": "关键概念：基因调控与表达",
    "Gene Expression": "基因表达",
    "Genes can be turned on or off:": "基因可以被打开或关闭：",
    "Promoters": "启动子",
    "Control gene activation": "控制基因激活",
    "Transcription Factors": "转录因子",
    "Proteins that regulate transcription": "调节转录的蛋白质",
    "Epigenetics": "表观遗传学",
    "Changes without altering DNA sequence": "不改变DNA序列的变化",
    "Operons (in bacteria)": "操纵子（在细菌中）",
    "Groups of genes controlled together": "一起控制的基因组",
    
    # === LESSON 10.5: Biotechnology (CRISPR, cloning, GMOs) ===
    "Key Concepts: Biotechnology (CRISPR, cloning, GMOs)": "关键概念：生物技术（CRISPR、克隆、转基因生物）",
    "Modern Biotechnology": "现代生物技术",
    "Technologies that modify genetic material:": "修改遗传物质的技术：",
    "CRISPR-Cas9": "CRISPR-Cas9",
    "Gene editing tool": "基因编辑工具",
    "Cuts DNA at specific locations": "在特定位置切割DNA",
    "Cloning": "克隆",
    "Creating genetically identical copies": "创建遗传相同的副本",
    "Reproductive vs. therapeutic cloning": "生殖克隆与治疗性克隆",
    "GMOs (Genetically Modified Organisms)": "转基因生物",
    "Organisms with altered genes": "基因被改变的生物",
    "Applications in agriculture and medicine": "在农业和医学中的应用",
    
    # === LESSON 10.6: Human Genetics and Genetic Disorders ===
    "Key Concepts: Human Genetics and Genetic Disorders": "关键概念：人类遗传学和遗传疾病",
    "Human Chromosomes": "人类染色体",
    "Humans have 46 chromosomes (23 pairs):": "人类有46条染色体（23对）：",
    "22 pairs of autosomes": "22对常染色体",
    "1 pair of sex chromosomes (XX or XY)": "1对性染色体（XX或XY）",
    "Genetic Disorders": "遗传疾病",
    "Diseases caused by gene mutations:": "由基因突变引起的疾病：",
    "Single Gene Disorders": "单基因疾病",
    "Cystic fibrosis, sickle cell disease": "囊性纤维化、镰状细胞病",
    "Chromosomal Disorders": "染色体疾病",
    "Down syndrome (trisomy 21)": "唐氏综合症（21三体）",
    "Genetic Screening": "基因检测",
    "Testing for genetic conditions": "检测遗传疾病",
    
    # === LESSON 11.1: Organization of the Human Body ===
    "Key Concepts: Organization of the Human Body": "关键概念：人体组织",
    "Body Organization": "身体组织",
    "The human body is organized hierarchically:": "人体按层次结构组织：",
    "Cells → Tissues → Organs → Organ Systems → Organism": "细胞 → 组织 → 器官 → 器官系统 → 生物体",
    "Types of Tissues": "组织类型",
    "Epithelial": "上皮组织",
    "Covers surfaces": "覆盖表面",
    "Connective": "结缔组织",
    "Supports and connects": "支撑和连接",
    "Muscle": "肌肉组织",
    "Allows movement": "允许运动",
    "Nervous": "神经组织",
    "Transmits signals": "传递信号",
    
    # === LESSON 11.2: Digestive System ===
    "Key Concepts: Digestive System": "关键概念：消化系统",
    "Functions of Digestion": "消化功能",
    "The digestive system breaks down food:": "消化系统分解食物：",
    "Mechanical Digestion": "机械消化",
    "Physical breakdown (chewing)": "物理分解（咀嚼）",
    "Chemical Digestion": "化学消化",
    "Enzymes break down molecules": "酶分解分子",
    "Major Organs": "主要器官",
    "Mouth, esophagus, stomach": "口腔、食道、胃",
    "Small intestine (absorption)": "小肠（吸收）",
    "Large intestine (water absorption)": "大肠（水分吸收）",
    "Accessory Organs": "附属器官",
    "Liver, pancreas, gallbladder": "肝脏、胰腺、胆囊",
    
    # === LESSON 11.3: Circulatory System ===
    "Key Concepts: Circulatory System": "关键概念：循环系统",
    "Functions of Circulation": "循环功能",
    "The circulatory system transports materials:": "循环系统运输物质：",
    "Heart": "心脏",
    "Pumps blood through body": "将血液泵送到全身",
    "Blood Vessels": "血管",
    "Arteries carry blood away from heart": "动脉将血液从心脏输送出去",
    "Veins carry blood to heart": "静脉将血液输送回心脏",
    "Capillaries for gas exchange": "毛细血管进行气体交换",
    "Blood": "血液",
    "Red blood cells (oxygen)": "红细胞（氧气）",
    "White blood cells (immunity)": "白细胞（免疫）",
    "Platelets (clotting)": "血小板（凝血）",
    
    # === LESSON 11.4: Respiratory System ===
    "Key Concepts: Respiratory System": "关键概念：呼吸系统",
    "Functions of Respiration": "呼吸功能",
    "The respiratory system exchanges gases:": "呼吸系统进行气体交换：",
    "Breathing": "呼吸",
    "Air moves in and out of lungs": "空气进出肺部",
    "Gas Exchange": "气体交换",
    "O₂ enters blood, CO₂ exits": "O₂进入血液，CO₂排出",
    "Structures": "结构",
    "Nose, pharynx, larynx, trachea": "鼻子、咽、喉、气管",
    "Bronchi and bronchioles": "支气管和细支气管",
    "Alveoli (gas exchange)": "肺泡（气体交换）",
    
    # === LESSON 11.5: Nervous System ===
    "Key Concepts: Nervous System": "关键概念：神经系统",
    "Functions of the Nervous System": "神经系统的功能",
    "The nervous system coordinates body activities:": "神经系统协调身体活动：",
    "Central Nervous System (CNS)": "中枢神经系统",
    "Brain and spinal cord": "大脑和脊髓",
    "Peripheral Nervous System (PNS)": "周围神经系统",
    "Nerves throughout the body": "遍布全身的神经",
    "Neurons": "神经元",
    "Dendrites receive signals": "树突接收信号",
    "Axons transmit signals": "轴突传递信号",
    "Synapses connect neurons": "突触连接神经元",
    
    # === LESSON 11.6: Immune System ===
    "Key Concepts: Immune System": "关键概念：免疫系统",
    "Immune Defense": "免疫防御",
    "The immune system protects against disease:": "免疫系统防止疾病：",
    "Innate Immunity": "先天免疫",
    "Non-specific defenses (skin, inflammation)": "非特异性防御（皮肤、炎症）",
    "Adaptive Immunity": "适应性免疫",
    "Specific responses to pathogens": "对病原体的特异性反应",
    "Immune Cells": "免疫细胞",
    "B cells (antibodies)": "B细胞（抗体）",
    "T cells (cell-mediated immunity)": "T细胞（细胞介导免疫）",
    "Vaccines": "疫苗",
    "Train immune system to recognize pathogens": "训练免疫系统识别病原体",
    
    # === LESSON 12.1: Biotechnology and Genetic Engineering ===
    "Key Concepts: Biotechnology and Genetic Engineering": "关键概念：生物技术与基因工程",
    "Genetic Engineering Techniques": "基因工程技术",
    "Modifying organisms using DNA technology:": "使用DNA技术修改生物：",
    "Recombinant DNA": "重组DNA",
    "DNA from different sources combined": "来自不同来源的DNA组合",
    "Gene Cloning": "基因克隆",
    "Making copies of specific genes": "制作特定基因的副本",
    "PCR (Polymerase Chain Reaction)": "PCR（聚合酶链式反应）",
    "Amplifying DNA": "扩增DNA",
    "Applications": "应用",
    "Medicine": "医学",
    "Producing insulin, gene therapy": "生产胰岛素、基因治疗",
    "Agriculture": "农业",
    "Pest-resistant crops": "抗虫作物",
    
    # === LESSON 12.2: Stem Cells and Regenerative Medicine ===
    "Key Concepts: Stem Cells and Regenerative Medicine": "关键概念：干细胞和再生医学",
    "What are Stem Cells?": "什么是干细胞？",
    "Stem cells can become many cell types:": "干细胞可以变成许多细胞类型：",
    "Embryonic Stem Cells": "胚胎干细胞",
    "Can become any cell type (pluripotent)": "可以变成任何细胞类型（多能）",
    "Adult Stem Cells": "成体干细胞",
    "More limited differentiation": "分化能力更有限",
    "Induced Pluripotent Stem Cells (iPSCs)": "诱导多能干细胞",
    "Adult cells reprogrammed to be pluripotent": "成体细胞重编程为多能细胞",
    "Regenerative Medicine": "再生医学",
    "Repairing or replacing tissues": "修复或替换组织",
    "Treating diseases like Parkinson's": "治疗帕金森病等疾病",
    
    # === LESSON 12.3: Bioethics (cloning, stem cells, genetic privacy) ===
    "Key Concepts: Bioethics (cloning, stem cells, genetic privacy)": "关键概念：生物伦理学（克隆、干细胞、基因隐私）",
    "Ethical Issues in Biotechnology": "生物技术中的伦理问题",
    "Important considerations:": "重要考虑因素：",
    "Cloning Ethics": "克隆伦理",
    "Human cloning controversies": "人类克隆争议",
    "Stem Cell Ethics": "干细胞伦理",
    "Embryonic stem cell use": "胚胎干细胞使用",
    "Genetic Privacy": "基因隐私",
    "Protection of genetic information": "遗传信息的保护",
    "Genetic discrimination concerns": "基因歧视忧虑",
    "Balancing Progress and Ethics": "平衡进步与伦理",
    "Regulations and oversight": "法规和监督",
    
    # === LESSON 12.4: Medicine and Pharmacology ===
    "Key Concepts: Medicine and Pharmacology": "关键概念：医学和药理学",
    "Pharmacology": "药理学",
    "The study of drugs and their effects:": "药物及其作用的研究：",
    "Drug Development": "药物开发",
    "Discovery, testing, approval": "发现、测试、批准",
    "Drug Targets": "药物靶点",
    "Receptors, enzymes, channels": "受体、酶、通道",
    "Personalized Medicine": "个性化医学",
    "Tailoring treatment to individuals": "为个人量身定制治疗方案",
    "Based on genetic information": "基于遗传信息",
    "Pharmacogenomics": "药物基因组学",
    "How genes affect drug response": "基因如何影响药物反应",
    
    # === LESSON 12.5: Biochemistry in Everyday Life ===
    "Key Concepts: Biochemistry in Everyday Life": "关键概念：日常生活中的生物化学",
    "Biochemistry Applications": "生物化学应用",
    "Biochemistry affects our daily lives:": "生物化学影响我们的日常生活：",
    "Food and Nutrition": "食物和营养",
    "Understanding nutrients and digestion": "了解营养物质和消化",
    "Food additives and preservatives": "食品添加剂和防腐剂",
    "Health and Fitness": "健康和健身",
    "Metabolism and energy": "新陈代谢和能量",
    "Sports nutrition": "运动营养",
    "Household Products": "家用产品",
    "Detergents and cleaners (enzymes)": "洗涤剂和清洁剂（酶）",
    "Personal care products": "个人护理产品",
    
    # === LESSON 12.6: Astrobiology and the Search for Life Beyond Earth ===
    "Key Concepts: Astrobiology and the Search for Life Beyond Earth": "关键概念：天体生物学和地球外生命的探索",
    "What is Astrobiology?": "什么是天体生物学？",
    "The study of life in the universe:": "宇宙中生命的研究：",
    "Origin of Life": "生命起源",
    "How life began on Earth": "生命如何在地球上开始",
    "Conditions for Life": "生命条件",
    "Water, energy, organic molecules": "水、能量、有机分子",
    "Search for Extraterrestrial Life": "搜寻地外生命",
    "Mars exploration": "火星探索",
    "Europa and Enceladus": "木卫二和土卫二",
    "Exoplanet searches": "系外行星搜索",
    "Extremophiles": "极端生物",
    "Life in extreme conditions": "极端条件下的生命",
    "Help us understand where life could exist": "帮助我们了解生命可能存在的地方",
    
    # Common phrases
    "Understanding": "理解",
    "Example": "例如",
    "Examples": "例如",
    "e.g.": "例如",
    "Key Concepts": "关键概念",
    "Important": "重要",
    "Definition": "定义",
    "Process": "过程",
    "Structure": "结构",
    "Function": "功能",
    "Type": "类型",
    "Types": "类型",
    "Features": "特征",
    "Characteristics": "特征",
    "Summary": "总结",
    "Review": "复习",
    "Remember": "记住",
}

def add_translations_to_file(translations):
    """Add summary translations to global_translations.js."""
    with open(TRANSLATIONS_FILE, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Filter out already existing
    new_translations = {}
    existing = 0
    for eng, zh in translations.items():
        eng_escaped = eng.replace('"', '\\"')
        if f'"{eng}"' not in content and f'"{eng_escaped}"' not in content:
            new_translations[eng] = zh
        else:
            existing += 1
    
    if not new_translations:
        print(f"All {existing} translations already exist.")
        return 0
    
    # Build new lines
    new_lines = '\n  /* Biology Summary Content Translations */\n'
    for eng, zh in sorted(new_translations.items(), key=lambda x: x[0].lower()):
        eng_escaped = eng.replace('"', '\\"').replace('\n', '\\n')
        zh_escaped = zh.replace('"', '\\"').replace('\n', '\\n')
        new_lines += f'  "{eng_escaped}": "{zh_escaped}",\n'
    
    # Insert before closing
    import re
    match = re.search(r'(\n\};\n\n\s*// Expose translations globally)', content)
    if match:
        insert_pos = match.start(1)
        content = content[:insert_pos] + new_lines + content[insert_pos:]
        
        with open(TRANSLATIONS_FILE, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"Added {len(new_translations)} new translations ({existing} already existed)")
        return len(new_translations)
    else:
        print("Could not find insertion point")
        return 0

if __name__ == "__main__":
    count = add_translations_to_file(SUMMARY_TRANSLATIONS)
    print(f"Summary translation complete. Added {count} translations.")
