#!/usr/bin/env python3
"""
Comprehensive Biology Content Translations
Adds all flashcard, quiz, and summary translations to global_translations.js
"""

import re
import os

TRANSLATIONS_FILE = r"c:\Users\Peter\pkang6689-pixel.github.io\ArisEdu Project Folder\scripts\global_translations.js"

# Comprehensive biology translations organized by unit/topic
TRANSLATIONS = {
    # ==================== UNIT 1: STUDY OF LIFE ====================
    # Lesson 1.1 - Introduction to Biology
    "What is biology?": "什么是生物学？",
    "The scientific study of life and living organisms": "对生命和生物的科学研究",
    "What does 'bios' mean in Greek?": "'bios'在希腊语中是什么意思？",
    "Life": "生命",
    "What does 'logos' mean in Greek?": "'logos'在希腊语中是什么意思？",
    "Study or knowledge": "研究或知识",
    "Name three reasons to study biology.": "列举三个学习生物学的原因。",
    "Understanding health/disease, developing medicines, addressing environmental challenges": "了解健康/疾病、开发药物、应对环境挑战",
    "What sciences does modern biology integrate?": "现代生物学整合了哪些科学？",
    "Chemistry, physics, and mathematics": "化学、物理和数学",
    "What is the scope of biology?": "生物学的范围是什么？",
    "From microscopic bacteria to massive ecosystems": "从微观细菌到庞大的生态系统",
    "How does biology help with disease?": "生物学如何帮助治疗疾病？",
    "By understanding causes, prevention, and treatment of illnesses": "通过了解疾病的原因、预防和治疗",
    "How does biology impact agriculture?": "生物学如何影响农业？",
    "By improving crop yields, disease resistance, and food production": "通过提高作物产量、抗病性和粮食生产",
    "What makes something 'living'?": "什么使事物成为'活的'？",
    "It exhibits characteristics of life like metabolism, growth, and reproduction": "它表现出新陈代谢、生长和繁殖等生命特征",
    "Why is biology considered an interdisciplinary science?": "为什么生物学被认为是一门跨学科科学？",
    "It combines principles from chemistry, physics, and math to study life": "它结合化学、物理和数学原理来研究生命",
    
    # Lesson 1.2 - The Science of Life / Scientific Method
    "What is the scientific method?": "什么是科学方法？",
    "A systematic approach to investigating phenomena through observation, hypothesis, experimentation, and conclusion": "通过观察、假设、实验和结论系统研究现象的方法",
    "What is a hypothesis?": "什么是假设？",
    "A testable explanation for observations": "对观察结果的可检验解释",
    "What is a control group?": "什么是对照组？",
    "A group in an experiment that is not exposed to the variable being tested": "实验中不接受测试变量的组",
    "What does 'reproducible' mean in science?": "在科学中'可重复'是什么意思？",
    "Other scientists can repeat the experiment and get the same results": "其他科学家可以重复实验并得到相同的结果",
    "What is a variable in an experiment?": "实验中的变量是什么？",
    "A factor that can be changed or controlled": "可以改变或控制的因素",
    "What is the independent variable?": "什么是自变量？",
    "The variable that the scientist changes or manipulates": "科学家改变或操纵的变量",
    "What is the dependent variable?": "什么是因变量？",
    "The variable that is measured in response to changes": "响应变化而测量的变量",
    "What is data in science?": "科学中的数据是什么？",
    "Information collected during an experiment": "实验过程中收集的信息",
    "Why do scientists use controls?": "为什么科学家使用对照？",
    "To have a baseline for comparing experimental results": "为比较实验结果提供基准",
    "What makes an experiment valid?": "什么使实验有效？",
    "Proper controls, single variable changes, and reproducibility": "适当的对照、单一变量变化和可重复性",
    
    # Lesson 1.3 - The Nature of Science
    "What does 'empirical' mean?": "'经验性'是什么意思？",
    "Based on observation and experimentation": "基于观察和实验",
    "What is a scientific theory?": "什么是科学理论？",
    "A well-tested explanation supported by extensive evidence": "经过充分验证并有大量证据支持的解释",
    "What is a scientific law?": "什么是科学定律？",
    "A description of a natural phenomenon that always occurs": "对总是发生的自然现象的描述",
    "Why is science considered 'tentative'?": "为什么科学被认为是'暂时性的'？",
    "Because conclusions can change with new evidence": "因为结论可能随着新证据而改变",
    "What does 'objective' mean in science?": "在科学中'客观'是什么意思？",
    "Minimizing personal bias in observations and conclusions": "在观察和结论中尽量减少个人偏见",
    "Give an example of a scientific theory.": "举一个科学理论的例子。",
    "Cell theory, theory of evolution, germ theory": "细胞学说、进化论、病原体学说",
    "Give an example of a scientific law.": "举一个科学定律的例子。",
    "Law of gravity, laws of thermodynamics": "万有引力定律、热力学定律",
    "What does 'testable' mean?": "'可检验'是什么意思？",
    "Claims can be verified or proven false through experimentation": "主张可以通过实验验证或证伪",
    "How is a theory different from a guess?": "理论与猜测有什么不同？",
    "A theory is supported by extensive evidence and testing": "理论有大量证据和测试支持",
    "Why must science be evidence-based?": "为什么科学必须基于证据？",
    "To ensure conclusions are based on facts, not opinions": "确保结论基于事实而非意见",
    
    # Lesson 1.4 - Characteristics of Life
    "What is homeostasis?": "什么是稳态？",
    "Maintaining stable internal conditions": "维持稳定的内部条件",
    "What is metabolism?": "什么是新陈代谢？",
    "Chemical reactions to obtain and use energy": "获取和使用能量的化学反应",
    "What is the basic unit of life?": "生命的基本单位是什么？",
    "The cell": "细胞",
    "What does 'response to stimuli' mean?": "'对刺激的反应'是什么意思？",
    "Reacting to changes in the environment": "对环境变化作出反应",
    "What is adaptation?": "什么是适应？",
    "Evolving over generations to better survive in an environment": "通过世代进化以更好地适应环境",
    "Name the 7 characteristics of life.": "列举生命的7个特征。",
    "Organization, metabolism, homeostasis, growth, reproduction, response, adaptation": "组织性、新陈代谢、稳态、生长、繁殖、应激性、适应性",
    "What is reproduction?": "什么是繁殖？",
    "The process of producing offspring": "产生后代的过程",
    "What is growth in living things?": "生物的生长是什么？",
    "An increase in size and/or number of cells": "细胞大小和/或数量的增加",
    "Why is organization important for life?": "为什么组织性对生命很重要？",
    "Cells provide structure and carry out life functions": "细胞提供结构并执行生命功能",
    "How do organisms maintain homeostasis?": "生物如何维持稳态？",
    "Through internal regulation of temperature, pH, water, etc.": "通过内部调节温度、pH值、水分等",
    
    # Lesson 1.5 - Levels of Biological Organization
    "What is a population?": "什么是种群？",
    "All members of one species living in the same area": "生活在同一区域的同一物种的所有成员",
    "What is a community?": "什么是群落？",
    "All populations of different species living in the same area": "生活在同一区域的不同物种的所有种群",
    "What is an ecosystem?": "什么是生态系统？",
    "A community plus its physical environment": "群落加上其物理环境",
    "What is the biosphere?": "什么是生物圈？",
    "All ecosystems on Earth; the global sum of all life": "地球上所有的生态系统；所有生命的全球总和",
    "What is the correct order from smallest to largest?": "从小到大的正确顺序是什么？",
    "Cell → Tissue → Organ → Organ System → Organism": "细胞 → 组织 → 器官 → 器官系统 → 生物体",
    "What is an organelle?": "什么是细胞器？",
    "A specialized structure within a cell that performs a specific function": "细胞内执行特定功能的专门结构",
    "What is a tissue?": "什么是组织？",
    "A group of similar cells working together": "一组相似细胞共同工作",
    "What is an organ?": "什么是器官？",
    "A structure made of different tissues working together": "由不同组织共同工作组成的结构",
    "What is an organ system?": "什么是器官系统？",
    "Multiple organs working together for a common function": "多个器官为共同功能而协同工作",
    "What is the smallest level of life?": "生命的最小层次是什么？",
    "Atom, then molecule": "原子，然后是分子",
    
    # Lesson 1.6 - Branches of Biology
    "What is zoology?": "什么是动物学？",
    "The study of animals": "对动物的研究",
    "What is botany?": "什么是植物学？",
    "The study of plants": "对植物的研究",
    "What is microbiology?": "什么是微生物学？",
    "The study of microorganisms": "对微生物的研究",
    "What is genetics?": "什么是遗传学？",
    "The study of heredity and genes": "对遗传和基因的研究",
    "What is ecology?": "什么是生态学？",
    "The study of organisms and their environments": "对生物及其环境的研究",
    "What is the difference between anatomy and physiology?": "解剖学和生理学有什么区别？",
    "Anatomy studies structure; physiology studies function": "解剖学研究结构；生理学研究功能",
    "What is biochemistry?": "什么是生物化学？",
    "The study of chemical processes in living things": "对生物体内化学过程的研究",
    "What is cell biology?": "什么是细胞生物学？",
    "The study of cell structure and function": "对细胞结构和功能的研究",
    "What is marine biology?": "什么是海洋生物学？",
    "The study of ocean organisms and ecosystems": "对海洋生物和生态系统的研究",
    "What is immunology?": "什么是免疫学？",
    "The study of the immune system": "对免疫系统的研究",
    
    # Lesson 1.7 - Careers in Biology
    "Name three healthcare careers related to biology.": "列举三个与生物学相关的医疗职业。",
    "Doctor, nurse, pharmacist": "医生、护士、药剂师",
    "What does a wildlife biologist do?": "野生动物生物学家做什么？",
    "Studies animals in their natural habitats and works on conservation": "研究自然栖息地中的动物并从事保护工作",
    "What is biotechnology?": "什么是生物技术？",
    "The use of living systems to develop products and technologies": "利用生命系统开发产品和技术",
    "What degree is typically needed for biology careers?": "生物学职业通常需要什么学位？",
    "At least a bachelor's degree": "至少学士学位",
    "What does a forensic scientist do?": "法医科学家做什么？",
    "Applies biological knowledge to solve crimes": "运用生物学知识解决犯罪",
    "What does an ecologist study?": "生态学家研究什么？",
    "The relationships between organisms and their environment": "生物与其环境之间的关系",
    "What is a genetic engineer?": "什么是基因工程师？",
    "A scientist who modifies genes to create desired traits": "修改基因以创造所需性状的科学家",
    "What does a pharmacist do?": "药剂师做什么？",
    "Prepares and dispenses medications": "准备和分发药物",
    "What does an agronomist do?": "农学家做什么？",
    "Studies crops and soil to improve food production": "研究作物和土壤以改善粮食生产",
    "What advanced degree helps biology careers?": "什么高级学位有助于生物学职业？",
    "Master's or doctoral degree": "硕士或博士学位",
    
    # ==================== UNIT 2: ECOLOGY ====================
    "What is ecology?": "什么是生态学？",
    "The study of interactions between organisms and their environment": "对生物与其环境之间相互作用的研究",
    "What are biotic factors?": "什么是生物因素？",
    "Living components of an ecosystem": "生态系统中的生物成分",
    "What are abiotic factors?": "什么是非生物因素？",
    "Non-living components of an ecosystem": "生态系统中的非生物成分",
    "What is a producer?": "什么是生产者？",
    "An organism that makes its own food through photosynthesis": "通过光合作用自己制造食物的生物",
    "What is a consumer?": "什么是消费者？",
    "An organism that obtains energy by eating other organisms": "通过吃其他生物获取能量的生物",
    "What is a decomposer?": "什么是分解者？",
    "An organism that breaks down dead organic matter": "分解死亡有机物的生物",
    "What is a food chain?": "什么是食物链？",
    "A linear sequence of organisms through which energy flows": "能量流动的生物线性序列",
    "What is a food web?": "什么是食物网？",
    "Interconnected food chains in an ecosystem": "生态系统中相互连接的食物链",
    "What is a trophic level?": "什么是营养级？",
    "A feeding position in a food chain or web": "食物链或食物网中的摄食位置",
    "What is energy flow?": "什么是能量流动？",
    "The transfer of energy from one organism to another": "能量从一种生物转移到另一种生物",
    "How much energy transfers between trophic levels?": "营养级之间有多少能量转移？",
    "About 10%": "约10%",
    "What is the 10% rule?": "什么是10%法则？",
    "Only about 10% of energy transfers to the next trophic level": "只有约10%的能量转移到下一个营养级",
    "What is a niche?": "什么是生态位？",
    "An organism's role and position in its environment": "生物在其环境中的角色和位置",
    "What is a habitat?": "什么是栖息地？",
    "The physical place where an organism lives": "生物生活的物理场所",
    "What is ecological succession?": "什么是生态演替？",
    "The gradual replacement of one community by another": "一个群落逐渐被另一个群落取代",
    "What is primary succession?": "什么是初级演替？",
    "Succession that begins in an area with no soil": "在没有土壤的地区开始的演替",
    "What is secondary succession?": "什么是次级演替？",
    "Succession that begins in an area where soil already exists": "在已有土壤的地区开始的演替",
    "What is a pioneer species?": "什么是先锋物种？",
    "The first species to colonize a disturbed area": "最先在受干扰地区定居的物种",
    "What is a climax community?": "什么是顶极群落？",
    "A stable, mature community at the end of succession": "演替结束时稳定、成熟的群落",
    "What is the carbon cycle?": "什么是碳循环？",
    "The movement of carbon through ecosystems": "碳在生态系统中的移动",
    "What is the nitrogen cycle?": "什么是氮循环？",
    "The movement of nitrogen through ecosystems": "氮在生态系统中的移动",
    "What is the water cycle?": "什么是水循环？",
    "The movement of water through ecosystems": "水在生态系统中的移动",
    "What is nitrogen fixation?": "什么是固氮？",
    "Converting atmospheric nitrogen to usable forms": "将大气氮转化为可用形式",
    
    # ==================== UNIT 3: BIOSPHERE ====================
    "What is a biome?": "什么是生物群落？",
    "A large region characterized by climate and organisms": "以气候和生物为特征的大型区域",
    "What is biodiversity?": "什么是生物多样性？",
    "The variety of life in an area": "一个地区生命的多样性",
    "What is climate?": "什么是气候？",
    "Average weather conditions over a long period": "长期的平均天气条件",
    "What factors determine a biome?": "什么因素决定生物群落？",
    "Temperature and precipitation": "温度和降水",
    "What is a terrestrial biome?": "什么是陆地生物群落？",
    "A land-based biome": "陆地上的生物群落",
    "What is an aquatic ecosystem?": "什么是水生生态系统？",
    "A water-based ecosystem": "以水为基础的生态系统",
    "Name the major terrestrial biomes.": "列举主要的陆地生物群落。",
    "Tundra, taiga, temperate forest, tropical rainforest, desert, grassland": "苔原、针叶林、温带森林、热带雨林、沙漠、草原",
    "What characterizes the tundra?": "苔原的特征是什么？",
    "Cold temperatures, permafrost, low biodiversity": "低温、永久冻土、低生物多样性",
    "What characterizes tropical rainforests?": "热带雨林的特征是什么？",
    "Warm temperatures, high rainfall, high biodiversity": "温暖的温度、高降雨量、高生物多样性",
    "What characterizes deserts?": "沙漠的特征是什么？",
    "Low precipitation, extreme temperatures": "低降水量、极端温度",
    
    # ==================== UNIT 4: EVOLUTION ====================
    "Who proposed the theory of evolution by natural selection?": "谁提出了自然选择的进化论？",
    "Charles Darwin": "查尔斯·达尔文",
    "What is natural selection?": "什么是自然选择？",
    "The process by which organisms with favorable traits survive and reproduce": "具有有利性状的生物存活和繁殖的过程",
    "What is adaptation?": "什么是适应？",
    "A trait that helps an organism survive in its environment": "帮助生物在其环境中生存的性状",
    "What is fitness in evolution?": "进化中的适应度是什么？",
    "An organism's ability to survive and reproduce": "生物存活和繁殖的能力",
    "What is a fossil?": "什么是化石？",
    "Preserved remains or traces of ancient organisms": "古代生物的保存遗骸或痕迹",
    "What is homologous structure?": "什么是同源结构？",
    "Similar structures in different species from common ancestry": "不同物种中来自共同祖先的相似结构",
    "What is analogous structure?": "什么是类似结构？",
    "Similar structures in unrelated species with similar functions": "不相关物种中具有相似功能的相似结构",
    "What is vestigial structure?": "什么是退化结构？",
    "A reduced structure with little or no function": "功能很小或没有功能的退化结构",
    "What is genetic variation?": "什么是遗传变异？",
    "Differences in DNA among individuals": "个体之间DNA的差异",
    "What causes genetic variation?": "什么导致遗传变异？",
    "Mutations, sexual reproduction, genetic recombination": "突变、有性生殖、基因重组",
    "What is the Hardy-Weinberg equilibrium?": "什么是哈迪-温伯格平衡？",
    "A population where allele frequencies remain constant": "等位基因频率保持不变的种群",
    "What conditions are needed for Hardy-Weinberg equilibrium?": "哈迪-温伯格平衡需要什么条件？",
    "No mutation, no migration, large population, random mating, no selection": "无突变、无迁移、大种群、随机交配、无选择",
    "What is speciation?": "什么是物种形成？",
    "The formation of new species": "新物种的形成",
    "What is reproductive isolation?": "什么是生殖隔离？",
    "The inability of species to interbreed": "物种无法杂交",
    
    # ==================== UNIT 5: CLASSIFICATION ====================
    "What is taxonomy?": "什么是分类学？",
    "The science of classifying organisms": "对生物进行分类的科学",
    "Who developed the binomial nomenclature system?": "谁发明了二名法命名系统？",
    "Carl Linnaeus": "卡尔·林奈",
    "What is binomial nomenclature?": "什么是二名法？",
    "A two-part naming system using genus and species": "使用属名和种名的双名命名系统",
    "What are the three domains of life?": "生命的三个域是什么？",
    "Bacteria, Archaea, Eukarya": "细菌域、古菌域、真核域",
    "What are the six kingdoms?": "六界是什么？",
    "Bacteria, Archaea, Protista, Fungi, Plantae, Animalia": "细菌界、古菌界、原生生物界、真菌界、植物界、动物界",
    "What is a phylogenetic tree?": "什么是系统发育树？",
    "A diagram showing evolutionary relationships": "显示进化关系的图表",
    "What is a cladogram?": "什么是支序图？",
    "A branching diagram showing shared characteristics": "显示共同特征的分支图",
    "What is a derived character?": "什么是衍生特征？",
    "A trait that evolved in a lineage": "在一个谱系中进化的性状",
    "What is an ancestral character?": "什么是祖先特征？",
    "A trait inherited from a distant ancestor": "从远古祖先继承的性状",
    
    # ==================== UNIT 6: CELLS ====================
    "What is the cell theory?": "什么是细胞学说？",
    "All organisms are made of cells, cells are the basic unit of life, cells come from existing cells": "所有生物都由细胞组成，细胞是生命的基本单位，细胞来自现有细胞",
    "What is the difference between prokaryotic and eukaryotic cells?": "原核细胞和真核细胞有什么区别？",
    "Prokaryotic cells lack membrane-bound organelles; eukaryotic cells have them": "原核细胞缺乏膜结合细胞器；真核细胞有",
    "What is the nucleus?": "什么是细胞核？",
    "The organelle that contains DNA": "包含DNA的细胞器",
    "What is the cell membrane?": "什么是细胞膜？",
    "A barrier that controls what enters and exits the cell": "控制物质进出细胞的屏障",
    "What is the function of mitochondria?": "线粒体的功能是什么？",
    "To produce ATP through cellular respiration": "通过细胞呼吸产生ATP",
    "What is the function of ribosomes?": "核糖体的功能是什么？",
    "To synthesize proteins": "合成蛋白质",
    "What is the endoplasmic reticulum?": "什么是内质网？",
    "A network for protein and lipid synthesis": "用于蛋白质和脂质合成的网络",
    "What is the rough ER?": "什么是粗面内质网？",
    "ER with ribosomes attached for protein synthesis": "附着核糖体用于蛋白质合成的内质网",
    "What is the smooth ER?": "什么是滑面内质网？",
    "ER without ribosomes for lipid synthesis": "没有核糖体用于脂质合成的内质网",
    "What is the Golgi apparatus?": "什么是高尔基体？",
    "Organelle that modifies, packages, and ships proteins": "修饰、包装和运输蛋白质的细胞器",
    "What is the function of lysosomes?": "溶酶体的功能是什么？",
    "To digest waste and cellular debris": "消化废物和细胞碎片",
    "What is the cytoplasm?": "什么是细胞质？",
    "The gel-like substance inside the cell": "细胞内类似凝胶的物质",
    "What is the cytoskeleton?": "什么是细胞骨架？",
    "A network of fibers that provides structure": "提供结构的纤维网络",
    "What do plant cells have that animal cells don't?": "植物细胞有什么是动物细胞没有的？",
    "Cell wall, chloroplasts, large central vacuole": "细胞壁、叶绿体、大型中央液泡",
    "What is the function of chloroplasts?": "叶绿体的功能是什么？",
    "To carry out photosynthesis": "进行光合作用",
    "What is the cell wall?": "什么是细胞壁？",
    "A rigid layer outside the cell membrane in plants": "植物细胞膜外的坚硬层",
    "What is active transport?": "什么是主动运输？",
    "Moving substances against concentration gradient using energy": "使用能量将物质逆浓度梯度移动",
    "What is passive transport?": "什么是被动运输？",
    "Moving substances down concentration gradient without energy": "不使用能量将物质顺浓度梯度移动",
    "What is diffusion?": "什么是扩散？",
    "Movement of molecules from high to low concentration": "分子从高浓度到低浓度的移动",
    "What is osmosis?": "什么是渗透？",
    "Diffusion of water across a membrane": "水通过膜的扩散",
    
    # ==================== UNIT 7: CELLULAR RESPIRATION ====================
    "What is cellular respiration?": "什么是细胞呼吸？",
    "The process of breaking down glucose to release energy": "分解葡萄糖释放能量的过程",
    "What is the equation for cellular respiration?": "细胞呼吸的方程式是什么？",
    "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP": "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP",
    "What is ATP?": "什么是ATP？",
    "Adenosine triphosphate, the energy currency of cells": "三磷酸腺苷，细胞的能量货币",
    "What are the three stages of cellular respiration?": "细胞呼吸的三个阶段是什么？",
    "Glycolysis, Krebs cycle, electron transport chain": "糖酵解、克雷布斯循环、电子传递链",
    "Where does glycolysis occur?": "糖酵解在哪里发生？",
    "In the cytoplasm": "在细胞质中",
    "What is the product of glycolysis?": "糖酵解的产物是什么？",
    "2 pyruvate, 2 ATP, 2 NADH": "2个丙酮酸、2个ATP、2个NADH",
    "Where does the Krebs cycle occur?": "克雷布斯循环在哪里发生？",
    "In the mitochondrial matrix": "在线粒体基质中",
    "What does the Krebs cycle produce?": "克雷布斯循环产生什么？",
    "ATP, NADH, FADH₂, CO₂": "ATP、NADH、FADH₂、CO₂",
    "Where does the electron transport chain occur?": "电子传递链在哪里发生？",
    "In the inner mitochondrial membrane": "在线粒体内膜",
    "How many ATP are produced from one glucose?": "一个葡萄糖产生多少ATP？",
    "36-38 ATP": "36-38个ATP",
    "What is fermentation?": "什么是发酵？",
    "Anaerobic respiration when oxygen is not available": "氧气不可用时的厌氧呼吸",
    "What is lactic acid fermentation?": "什么是乳酸发酵？",
    "Fermentation that produces lactic acid in muscles": "在肌肉中产生乳酸的发酵",
    "What is alcoholic fermentation?": "什么是酒精发酵？",
    "Fermentation that produces ethanol and CO₂": "产生乙醇和CO₂的发酵",
    
    # ==================== UNIT 8: PHOTOSYNTHESIS ====================
    "What is photosynthesis?": "什么是光合作用？",
    "The process of converting light energy to glucose": "将光能转化为葡萄糖的过程",
    "What is the equation for photosynthesis?": "光合作用的方程式是什么？",
    "6CO₂ + 6H₂O + light energy → C₆H₁₂O₆ + 6O₂": "6CO₂ + 6H₂O + 光能 → C₆H₁₂O₆ + 6O₂",
    "Where does photosynthesis occur?": "光合作用在哪里发生？",
    "In the chloroplasts": "在叶绿体中",
    "What are the two stages of photosynthesis?": "光合作用的两个阶段是什么？",
    "Light-dependent reactions and Calvin cycle": "光反应和卡尔文循环",
    "Where do light-dependent reactions occur?": "光反应在哪里发生？",
    "In the thylakoid membranes": "在类囊体膜中",
    "What do light reactions produce?": "光反应产生什么？",
    "ATP, NADPH, and oxygen": "ATP、NADPH和氧气",
    "Where does the Calvin cycle occur?": "卡尔文循环在哪里发生？",
    "In the stroma of chloroplasts": "在叶绿体基质中",
    "What does the Calvin cycle produce?": "卡尔文循环产生什么？",
    "Glucose (G3P)": "葡萄糖（G3P）",
    "What is chlorophyll?": "什么是叶绿素？",
    "The green pigment that absorbs light for photosynthesis": "吸收光用于光合作用的绿色色素",
    "What factors affect photosynthesis?": "什么因素影响光合作用？",
    "Light intensity, CO₂ concentration, temperature": "光照强度、CO₂浓度、温度",
    "What is the role of water in photosynthesis?": "水在光合作用中的作用是什么？",
    "It provides electrons and hydrogen atoms": "它提供电子和氢原子",
    "What happens to oxygen in photosynthesis?": "光合作用中氧气发生了什么？",
    "It is released as a byproduct": "它作为副产品释放",
    
    # ==================== UNIT 9: CELL CYCLE ====================
    "What is the cell cycle?": "什么是细胞周期？",
    "The series of events in a cell's life leading to division": "导致细胞分裂的一系列事件",
    "What are the three main stages of the cell cycle?": "细胞周期的三个主要阶段是什么？",
    "Interphase, mitosis, cytokinesis": "间期、有丝分裂、胞质分裂",
    "What happens during interphase?": "间期发生什么？",
    "Cell grows and DNA replicates": "细胞生长和DNA复制",
    "What are the three parts of interphase?": "间期的三个部分是什么？",
    "G1, S phase, G2": "G1期、S期、G2期",
    "What happens during G1?": "G1期发生什么？",
    "Cell growth and normal functions": "细胞生长和正常功能",
    "What happens during S phase?": "S期发生什么？",
    "DNA replication": "DNA复制",
    "What happens during G2?": "G2期发生什么？",
    "Preparation for cell division": "为细胞分裂做准备",
    "What is mitosis?": "什么是有丝分裂？",
    "Division of the nucleus into two identical nuclei": "细胞核分裂成两个相同的细胞核",
    "What are the four phases of mitosis?": "有丝分裂的四个阶段是什么？",
    "Prophase, metaphase, anaphase, telophase": "前期、中期、后期、末期",
    "What happens during prophase?": "前期发生什么？",
    "Chromosomes condense and spindle forms": "染色体凝缩，纺锤体形成",
    "What happens during metaphase?": "中期发生什么？",
    "Chromosomes line up at the cell equator": "染色体排列在细胞赤道",
    "What happens during anaphase?": "后期发生什么？",
    "Sister chromatids separate and move to poles": "姐妹染色单体分离并移向两极",
    "What happens during telophase?": "末期发生什么？",
    "Nuclear membranes reform and chromosomes decondense": "核膜重新形成，染色体解凝",
    "What is cytokinesis?": "什么是胞质分裂？",
    "Division of the cytoplasm into two cells": "细胞质分裂成两个细胞",
    "What controls the cell cycle?": "什么控制细胞周期？",
    "Cyclins and cyclin-dependent kinases": "细胞周期蛋白和细胞周期蛋白依赖性激酶",
    "What is cancer?": "什么是癌症？",
    "Uncontrolled cell division": "不受控制的细胞分裂",
    "What are checkpoints?": "什么是检查点？",
    "Control points that regulate cell cycle progression": "调节细胞周期进程的控制点",
    
    # ==================== UNIT 10: MEIOSIS ====================
    "What is meiosis?": "什么是减数分裂？",
    "Cell division that produces gametes with half the chromosomes": "产生染色体数目减半的配子的细胞分裂",
    "How many divisions occur in meiosis?": "减数分裂发生几次分裂？",
    "Two divisions": "两次分裂",
    "What is the result of meiosis?": "减数分裂的结果是什么？",
    "Four haploid cells": "四个单倍体细胞",
    "What is a haploid cell?": "什么是单倍体细胞？",
    "A cell with half the normal number of chromosomes": "染色体数目为正常一半的细胞",
    "What is a diploid cell?": "什么是二倍体细胞？",
    "A cell with the full number of chromosomes": "具有完整染色体数目的细胞",
    "What is crossing over?": "什么是交叉互换？",
    "Exchange of genetic material between homologous chromosomes": "同源染色体之间交换遗传物质",
    "When does crossing over occur?": "交叉互换什么时候发生？",
    "During prophase I of meiosis": "在减数分裂I的前期",
    "What is independent assortment?": "什么是自由组合？",
    "Random distribution of chromosomes during meiosis": "减数分裂期间染色体的随机分配",
    "What are homologous chromosomes?": "什么是同源染色体？",
    "Chromosome pairs with the same genes": "具有相同基因的染色体对",
    "What is a tetrad?": "什么是四分体？",
    "Four chromatids from paired homologous chromosomes": "配对的同源染色体的四条染色单体",
    "What is the difference between meiosis I and meiosis II?": "减数分裂I和减数分裂II有什么区别？",
    "Meiosis I separates homologs; Meiosis II separates sister chromatids": "减数分裂I分离同源染色体；减数分裂II分离姐妹染色单体",
    "What is nondisjunction?": "什么是染色体不分离？",
    "Failure of chromosomes to separate properly": "染色体未能正确分离",
    "What causes Down syndrome?": "什么导致唐氏综合症？",
    "Trisomy 21 - an extra chromosome 21": "21三体 - 多了一条21号染色体",
    
    # ==================== UNIT 11: GENETICS ====================
    "Who is the father of genetics?": "谁是遗传学之父？",
    "Gregor Mendel": "格雷戈尔·孟德尔",
    "What are Mendel's laws?": "孟德尔定律是什么？",
    "Law of segregation and law of independent assortment": "分离定律和自由组合定律",
    "What is the law of segregation?": "什么是分离定律？",
    "Alleles separate during gamete formation": "等位基因在配子形成过程中分离",
    "What is a Punnett square?": "什么是庞尼特方表？",
    "A diagram used to predict genetic crosses": "用于预测遗传杂交的图表",
    "What is a monohybrid cross?": "什么是单因子杂交？",
    "A cross examining one trait": "研究一种性状的杂交",
    "What is a dihybrid cross?": "什么是双因子杂交？",
    "A cross examining two traits": "研究两种性状的杂交",
    "What is a dominant allele?": "什么是显性等位基因？",
    "An allele that masks another allele": "掩盖其他等位基因的等位基因",
    "What is a recessive allele?": "什么是隐性等位基因？",
    "An allele that is masked by a dominant allele": "被显性等位基因掩盖的等位基因",
    "What is a genotype?": "什么是基因型？",
    "The genetic makeup of an organism": "生物的遗传组成",
    "What is a phenotype?": "什么是表型？",
    "The physical appearance of an organism": "生物的外观表现",
    "What is homozygous?": "什么是纯合子？",
    "Having two identical alleles for a trait": "某一性状具有两个相同的等位基因",
    "What is heterozygous?": "什么是杂合子？",
    "Having two different alleles for a trait": "某一性状具有两个不同的等位基因",
    "What is incomplete dominance?": "什么是不完全显性？",
    "When neither allele is completely dominant": "当两个等位基因都不完全显性时",
    "What is codominance?": "什么是共显性？",
    "When both alleles are fully expressed": "当两个等位基因都完全表达时",
    "What is a pedigree?": "什么是家系图？",
    "A diagram showing inheritance patterns in a family": "显示家族遗传模式的图表",
    "What is polygenic inheritance?": "什么是多基因遗传？",
    "When multiple genes affect one trait": "当多个基因影响一个性状时",
    
    # ==================== UNIT 12: MOLECULAR BIOLOGY ====================
    "What is DNA?": "什么是DNA？",
    "Deoxyribonucleic acid, the genetic material": "脱氧核糖核酸，遗传物质",
    "What is the structure of DNA?": "DNA的结构是什么？",
    "A double helix made of nucleotides": "由核苷酸组成的双螺旋",
    "What are the four DNA bases?": "DNA的四种碱基是什么？",
    "Adenine, thymine, guanine, cytosine": "腺嘌呤、胸腺嘧啶、鸟嘌呤、胞嘧啶",
    "What is base pairing?": "什么是碱基配对？",
    "A pairs with T; G pairs with C": "A与T配对；G与C配对",
    "What is DNA replication?": "什么是DNA复制？",
    "The process of copying DNA": "复制DNA的过程",
    "What is semiconservative replication?": "什么是半保留复制？",
    "Each new DNA has one old and one new strand": "每个新DNA有一条旧链和一条新链",
    "What enzyme unwinds DNA?": "什么酶解开DNA？",
    "Helicase": "解旋酶",
    "What enzyme builds new DNA strands?": "什么酶构建新的DNA链？",
    "DNA polymerase": "DNA聚合酶",
    "What is RNA?": "什么是RNA？",
    "Ribonucleic acid, used to make proteins": "核糖核酸，用于制造蛋白质",
    "What is transcription?": "什么是转录？",
    "Making mRNA from DNA": "从DNA制作mRNA",
    "What is translation?": "什么是翻译？",
    "Making proteins from mRNA": "从mRNA制作蛋白质",
    "What is a codon?": "什么是密码子？",
    "A three-nucleotide sequence on mRNA": "mRNA上的三核苷酸序列",
    "What is an anticodon?": "什么是反密码子？",
    "A three-nucleotide sequence on tRNA": "tRNA上的三核苷酸序列",
    "What is the central dogma?": "什么是中心法则？",
    "DNA → RNA → Protein": "DNA → RNA → 蛋白质",
    "What is a mutation?": "什么是突变？",
    "A change in DNA sequence": "DNA序列的改变",
    "What is genetic engineering?": "什么是基因工程？",
    "Modifying an organism's DNA": "修改生物的DNA",
    "What is a GMO?": "什么是转基因生物？",
    "A genetically modified organism": "转基因生物",
    "What is CRISPR?": "什么是CRISPR？",
    "A gene-editing technology": "一种基因编辑技术",
    "What is PCR?": "什么是PCR？",
    "Polymerase chain reaction, a method to amplify DNA": "聚合酶链式反应，一种扩增DNA的方法",
    "What is gel electrophoresis?": "什么是凝胶电泳？",
    "A technique to separate DNA fragments by size": "按大小分离DNA片段的技术",
    
    # ==================== COMMON UI ELEMENTS ====================
    "Check Answer": "检查答案",
    "Submit Answer": "提交答案",
    "Try Again": "重试",
    "Correct!": "正确！",
    "Incorrect": "错误",
    "Attempts left:": "剩余尝试次数：",
    "Get another question": "获取另一个问题",
    "Next Up: Quiz": "下一步：测验",
    "Next Up: Practice": "下一步：练习",
    "Next Up: Summary": "下一步：总结",
    "Next Up: Play": "下一步：练习",
    "Back to Biology": "返回生物",
    "Review Flashcards": "复习卡片",
    "Start Unit Test": "开始单元测试",
    "Shuffle": "随机排列",
    "Key Concepts:": "关键概念：",
    "Key Concepts": "关键概念",
    "Summary": "总结",
    
    # ==================== COMMON QUIZ OPTIONS ====================
    "True": "正确",
    "False": "错误",
    "All of the above": "以上all",
    "None of the above": "以上都不是",
    "Both A and B": "A和B都是",
}

def add_translations():
    """Add comprehensive biology translations to global_translations.js."""
    with open(TRANSLATIONS_FILE, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Count existing and new
    existing_count = 0
    new_translations = {}
    
    for eng, zh in TRANSLATIONS.items():
        # Check if already exists (with escaped quotes)
        eng_check = eng.replace("'", "\\'")
        if f'"{eng}"' in content or f'"{eng_check}"' in content:
            existing_count += 1
        else:
            new_translations[eng] = zh
    
    if not new_translations:
        print(f"All {existing_count} translations already exist.")
        return
    
    # Build new translations block
    new_lines = '\n  /* Biology Content Translations - Flashcards, Quizzes, Summaries */\n'
    for eng, zh in sorted(new_translations.items()):
        eng_escaped = eng.replace('"', '\\"').replace("'", "\\'")
        zh_escaped = zh.replace('"', '\\"').replace("'", "\\'")
        new_lines += f'  "{eng_escaped}": "{zh_escaped}",\n'
    
    # Find insertion point - before the closing of translations object
    match = re.search(r'(\n\};\n\n\s+// Expose translations globally)', content)
    if match:
        insert_pos = match.start(1)
        content = content[:insert_pos] + new_lines + content[insert_pos:]
        
        with open(TRANSLATIONS_FILE, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"Added {len(new_translations)} new translations ({existing_count} already existed)")
    else:
        print("Could not find insertion point")

if __name__ == "__main__":
    add_translations()
